local protobuf = protobuf
autoImport("xCmd_pb")
local xCmd_pb = xCmd_pb
module("ActHitPolly_pb")
ACTHIYPOLLYPARAM = protobuf.EnumDescriptor()
ACTHIYPOLLYPARAM_ACTHIYPOLLYPARAM_QUERY_HITPOLLY_LIST_ENUM = protobuf.EnumValueDescriptor()
ACTHIYPOLLYPARAM_ACTHIYPOLLYPARAM_HIT_POLLY_ENUM = protobuf.EnumValueDescriptor()
ACTHIYPOLLYPARAM_ACTHIYPOLLYPARAM_SYNC_ACT_ENUM = protobuf.EnumValueDescriptor()
ACTHIYPOLLYPARAM_ACTHIYPOLLYPARAM_SUBMIT_QUEST_ENUM = protobuf.EnumValueDescriptor()
ACTHIYPOLLYPARAM_ACTHIYPOLLYPARAM_QUEST_NTF_ENUM = protobuf.EnumValueDescriptor()
EACTHITPOLLYQUESTSTATUS = protobuf.EnumDescriptor()
EACTHITPOLLYQUESTSTATUS_EACCHITPOLLY_QUEST_NOT_OPEN_ENUM = protobuf.EnumValueDescriptor()
EACTHITPOLLYQUESTSTATUS_EACCHITPOLLY_QUEST_ON_ENUM = protobuf.EnumValueDescriptor()
EACTHITPOLLYQUESTSTATUS_EACCHITPOLLY_QUEST_SUBMITABLE_ENUM = protobuf.EnumValueDescriptor()
EACTHITPOLLYQUESTSTATUS_EACCHITPOLLY_QUEST_FINISH_ENUM = protobuf.EnumValueDescriptor()
ACTIVITYHITPOLLYQUESTITEM = protobuf.Descriptor()
ACTIVITYHITPOLLYQUESTITEM_QUESTID_FIELD = protobuf.FieldDescriptor()
ACTIVITYHITPOLLYQUESTITEM_STATUS_FIELD = protobuf.FieldDescriptor()
ACTIVITYHITPOLLYQUESTITEM_PROCESS_FIELD = protobuf.FieldDescriptor()
ACTIVITYHITPOLLYQUESTITEM_UPDATETIME_FIELD = protobuf.FieldDescriptor()
ACTITYHITEDPOLLYINFO = protobuf.Descriptor()
ACTITYHITEDPOLLYINFO_ROUND_FIELD = protobuf.FieldDescriptor()
ACTITYHITEDPOLLYINFO_POS_FIELD = protobuf.FieldDescriptor()
ACTITYHITEDPOLLYINFO_REWARDID_FIELD = protobuf.FieldDescriptor()
ACTITYQUERYHITEDLIST = protobuf.Descriptor()
ACTITYQUERYHITEDLIST_CMD_FIELD = protobuf.FieldDescriptor()
ACTITYQUERYHITEDLIST_PARAM_FIELD = protobuf.FieldDescriptor()
ACTITYQUERYHITEDLIST_ROUND_FIELD = protobuf.FieldDescriptor()
ACTITYQUERYHITEDLIST_CURRENTROUND_FIELD = protobuf.FieldDescriptor()
ACTITYQUERYHITEDLIST_LIST_FIELD = protobuf.FieldDescriptor()
ACTITYQUERYHITEDLIST_RESTBUY_FIELD = protobuf.FieldDescriptor()
ACTIVITYHITPOLLY = protobuf.Descriptor()
ACTIVITYHITPOLLY_CMD_FIELD = protobuf.FieldDescriptor()
ACTIVITYHITPOLLY_PARAM_FIELD = protobuf.FieldDescriptor()
ACTIVITYHITPOLLY_ROUND_FIELD = protobuf.FieldDescriptor()
ACTIVITYHITPOLLY_POS_FIELD = protobuf.FieldDescriptor()
ACTIVITYHITPOLLY_REWARDID_FIELD = protobuf.FieldDescriptor()
ACTITYHITPOLLYSYNC = protobuf.Descriptor()
ACTITYHITPOLLYSYNC_CMD_FIELD = protobuf.FieldDescriptor()
ACTITYHITPOLLYSYNC_PARAM_FIELD = protobuf.FieldDescriptor()
ACTITYHITPOLLYSYNC_GLOBALACTID_FIELD = protobuf.FieldDescriptor()
ACTITYHITPOLLYSYNC_CURROUND_FIELD = protobuf.FieldDescriptor()
ACTITYHITPOLLYSYNC_QUESTS_FIELD = protobuf.FieldDescriptor()
ACTITYHITPOLLYSUBMITQUEST = protobuf.Descriptor()
ACTITYHITPOLLYSUBMITQUEST_CMD_FIELD = protobuf.FieldDescriptor()
ACTITYHITPOLLYSUBMITQUEST_PARAM_FIELD = protobuf.FieldDescriptor()
ACTITYHITPOLLYSUBMITQUEST_QUESTID_FIELD = protobuf.FieldDescriptor()
ACTITYHITPOLLYNTFQUEST = protobuf.Descriptor()
ACTITYHITPOLLYNTFQUEST_CMD_FIELD = protobuf.FieldDescriptor()
ACTITYHITPOLLYNTFQUEST_PARAM_FIELD = protobuf.FieldDescriptor()
ACTITYHITPOLLYNTFQUEST_QUESTS_FIELD = protobuf.FieldDescriptor()
ACTHIYPOLLYPARAM_ACTHIYPOLLYPARAM_QUERY_HITPOLLY_LIST_ENUM.name = "ACTHIYPOLLYPARAM_QUERY_HITPOLLY_LIST"
ACTHIYPOLLYPARAM_ACTHIYPOLLYPARAM_QUERY_HITPOLLY_LIST_ENUM.index = 0
ACTHIYPOLLYPARAM_ACTHIYPOLLYPARAM_QUERY_HITPOLLY_LIST_ENUM.number = 1
ACTHIYPOLLYPARAM_ACTHIYPOLLYPARAM_HIT_POLLY_ENUM.name = "ACTHIYPOLLYPARAM_HIT_POLLY"
ACTHIYPOLLYPARAM_ACTHIYPOLLYPARAM_HIT_POLLY_ENUM.index = 1
ACTHIYPOLLYPARAM_ACTHIYPOLLYPARAM_HIT_POLLY_ENUM.number = 2
ACTHIYPOLLYPARAM_ACTHIYPOLLYPARAM_SYNC_ACT_ENUM.name = "ACTHIYPOLLYPARAM_SYNC_ACT"
ACTHIYPOLLYPARAM_ACTHIYPOLLYPARAM_SYNC_ACT_ENUM.index = 2
ACTHIYPOLLYPARAM_ACTHIYPOLLYPARAM_SYNC_ACT_ENUM.number = 3
ACTHIYPOLLYPARAM_ACTHIYPOLLYPARAM_SUBMIT_QUEST_ENUM.name = "ACTHIYPOLLYPARAM_SUBMIT_QUEST"
ACTHIYPOLLYPARAM_ACTHIYPOLLYPARAM_SUBMIT_QUEST_ENUM.index = 3
ACTHIYPOLLYPARAM_ACTHIYPOLLYPARAM_SUBMIT_QUEST_ENUM.number = 4
ACTHIYPOLLYPARAM_ACTHIYPOLLYPARAM_QUEST_NTF_ENUM.name = "ACTHIYPOLLYPARAM_QUEST_NTF"
ACTHIYPOLLYPARAM_ACTHIYPOLLYPARAM_QUEST_NTF_ENUM.index = 4
ACTHIYPOLLYPARAM_ACTHIYPOLLYPARAM_QUEST_NTF_ENUM.number = 5
ACTHIYPOLLYPARAM.name = "ActHiyPollyParam"
ACTHIYPOLLYPARAM.full_name = ".Cmd.ActHiyPollyParam"
ACTHIYPOLLYPARAM.values = {
  ACTHIYPOLLYPARAM_ACTHIYPOLLYPARAM_QUERY_HITPOLLY_LIST_ENUM,
  ACTHIYPOLLYPARAM_ACTHIYPOLLYPARAM_HIT_POLLY_ENUM,
  ACTHIYPOLLYPARAM_ACTHIYPOLLYPARAM_SYNC_ACT_ENUM,
  ACTHIYPOLLYPARAM_ACTHIYPOLLYPARAM_SUBMIT_QUEST_ENUM,
  ACTHIYPOLLYPARAM_ACTHIYPOLLYPARAM_QUEST_NTF_ENUM
}
EACTHITPOLLYQUESTSTATUS_EACCHITPOLLY_QUEST_NOT_OPEN_ENUM.name = "EACCHITPOLLY_QUEST_NOT_OPEN"
EACTHITPOLLYQUESTSTATUS_EACCHITPOLLY_QUEST_NOT_OPEN_ENUM.index = 0
EACTHITPOLLYQUESTSTATUS_EACCHITPOLLY_QUEST_NOT_OPEN_ENUM.number = 0
EACTHITPOLLYQUESTSTATUS_EACCHITPOLLY_QUEST_ON_ENUM.name = "EACCHITPOLLY_QUEST_ON"
EACTHITPOLLYQUESTSTATUS_EACCHITPOLLY_QUEST_ON_ENUM.index = 1
EACTHITPOLLYQUESTSTATUS_EACCHITPOLLY_QUEST_ON_ENUM.number = 1
EACTHITPOLLYQUESTSTATUS_EACCHITPOLLY_QUEST_SUBMITABLE_ENUM.name = "EACCHITPOLLY_QUEST_SUBMITABLE"
EACTHITPOLLYQUESTSTATUS_EACCHITPOLLY_QUEST_SUBMITABLE_ENUM.index = 2
EACTHITPOLLYQUESTSTATUS_EACCHITPOLLY_QUEST_SUBMITABLE_ENUM.number = 2
EACTHITPOLLYQUESTSTATUS_EACCHITPOLLY_QUEST_FINISH_ENUM.name = "EACCHITPOLLY_QUEST_FINISH"
EACTHITPOLLYQUESTSTATUS_EACCHITPOLLY_QUEST_FINISH_ENUM.index = 3
EACTHITPOLLYQUESTSTATUS_EACCHITPOLLY_QUEST_FINISH_ENUM.number = 3
EACTHITPOLLYQUESTSTATUS.name = "EActHitPollyQuestStatus"
EACTHITPOLLYQUESTSTATUS.full_name = ".Cmd.EActHitPollyQuestStatus"
EACTHITPOLLYQUESTSTATUS.values = {
  EACTHITPOLLYQUESTSTATUS_EACCHITPOLLY_QUEST_NOT_OPEN_ENUM,
  EACTHITPOLLYQUESTSTATUS_EACCHITPOLLY_QUEST_ON_ENUM,
  EACTHITPOLLYQUESTSTATUS_EACCHITPOLLY_QUEST_SUBMITABLE_ENUM,
  EACTHITPOLLYQUESTSTATUS_EACCHITPOLLY_QUEST_FINISH_ENUM
}
ACTIVITYHITPOLLYQUESTITEM_QUESTID_FIELD.name = "questid"
ACTIVITYHITPOLLYQUESTITEM_QUESTID_FIELD.full_name = ".Cmd.ActivityHitPollyQuestItem.questid"
ACTIVITYHITPOLLYQUESTITEM_QUESTID_FIELD.number = 1
ACTIVITYHITPOLLYQUESTITEM_QUESTID_FIELD.index = 0
ACTIVITYHITPOLLYQUESTITEM_QUESTID_FIELD.label = 1
ACTIVITYHITPOLLYQUESTITEM_QUESTID_FIELD.has_default_value = false
ACTIVITYHITPOLLYQUESTITEM_QUESTID_FIELD.default_value = 0
ACTIVITYHITPOLLYQUESTITEM_QUESTID_FIELD.type = 13
ACTIVITYHITPOLLYQUESTITEM_QUESTID_FIELD.cpp_type = 3
ACTIVITYHITPOLLYQUESTITEM_STATUS_FIELD.name = "status"
ACTIVITYHITPOLLYQUESTITEM_STATUS_FIELD.full_name = ".Cmd.ActivityHitPollyQuestItem.status"
ACTIVITYHITPOLLYQUESTITEM_STATUS_FIELD.number = 2
ACTIVITYHITPOLLYQUESTITEM_STATUS_FIELD.index = 1
ACTIVITYHITPOLLYQUESTITEM_STATUS_FIELD.label = 1
ACTIVITYHITPOLLYQUESTITEM_STATUS_FIELD.has_default_value = true
ACTIVITYHITPOLLYQUESTITEM_STATUS_FIELD.default_value = 0
ACTIVITYHITPOLLYQUESTITEM_STATUS_FIELD.enum_type = EACTHITPOLLYQUESTSTATUS
ACTIVITYHITPOLLYQUESTITEM_STATUS_FIELD.type = 14
ACTIVITYHITPOLLYQUESTITEM_STATUS_FIELD.cpp_type = 8
ACTIVITYHITPOLLYQUESTITEM_PROCESS_FIELD.name = "process"
ACTIVITYHITPOLLYQUESTITEM_PROCESS_FIELD.full_name = ".Cmd.ActivityHitPollyQuestItem.process"
ACTIVITYHITPOLLYQUESTITEM_PROCESS_FIELD.number = 3
ACTIVITYHITPOLLYQUESTITEM_PROCESS_FIELD.index = 2
ACTIVITYHITPOLLYQUESTITEM_PROCESS_FIELD.label = 1
ACTIVITYHITPOLLYQUESTITEM_PROCESS_FIELD.has_default_value = false
ACTIVITYHITPOLLYQUESTITEM_PROCESS_FIELD.default_value = 0
ACTIVITYHITPOLLYQUESTITEM_PROCESS_FIELD.type = 13
ACTIVITYHITPOLLYQUESTITEM_PROCESS_FIELD.cpp_type = 3
ACTIVITYHITPOLLYQUESTITEM_UPDATETIME_FIELD.name = "updatetime"
ACTIVITYHITPOLLYQUESTITEM_UPDATETIME_FIELD.full_name = ".Cmd.ActivityHitPollyQuestItem.updatetime"
ACTIVITYHITPOLLYQUESTITEM_UPDATETIME_FIELD.number = 4
ACTIVITYHITPOLLYQUESTITEM_UPDATETIME_FIELD.index = 3
ACTIVITYHITPOLLYQUESTITEM_UPDATETIME_FIELD.label = 1
ACTIVITYHITPOLLYQUESTITEM_UPDATETIME_FIELD.has_default_value = false
ACTIVITYHITPOLLYQUESTITEM_UPDATETIME_FIELD.default_value = 0
ACTIVITYHITPOLLYQUESTITEM_UPDATETIME_FIELD.type = 13
ACTIVITYHITPOLLYQUESTITEM_UPDATETIME_FIELD.cpp_type = 3
ACTIVITYHITPOLLYQUESTITEM.name = "ActivityHitPollyQuestItem"
ACTIVITYHITPOLLYQUESTITEM.full_name = ".Cmd.ActivityHitPollyQuestItem"
ACTIVITYHITPOLLYQUESTITEM.nested_types = {}
ACTIVITYHITPOLLYQUESTITEM.enum_types = {}
ACTIVITYHITPOLLYQUESTITEM.fields = {
  ACTIVITYHITPOLLYQUESTITEM_QUESTID_FIELD,
  ACTIVITYHITPOLLYQUESTITEM_STATUS_FIELD,
  ACTIVITYHITPOLLYQUESTITEM_PROCESS_FIELD,
  ACTIVITYHITPOLLYQUESTITEM_UPDATETIME_FIELD
}
ACTIVITYHITPOLLYQUESTITEM.is_extendable = false
ACTIVITYHITPOLLYQUESTITEM.extensions = {}
ACTITYHITEDPOLLYINFO_ROUND_FIELD.name = "round"
ACTITYHITEDPOLLYINFO_ROUND_FIELD.full_name = ".Cmd.ActityHitedPollyInfo.round"
ACTITYHITEDPOLLYINFO_ROUND_FIELD.number = 1
ACTITYHITEDPOLLYINFO_ROUND_FIELD.index = 0
ACTITYHITEDPOLLYINFO_ROUND_FIELD.label = 1
ACTITYHITEDPOLLYINFO_ROUND_FIELD.has_default_value = false
ACTITYHITEDPOLLYINFO_ROUND_FIELD.default_value = 0
ACTITYHITEDPOLLYINFO_ROUND_FIELD.type = 13
ACTITYHITEDPOLLYINFO_ROUND_FIELD.cpp_type = 3
ACTITYHITEDPOLLYINFO_POS_FIELD.name = "pos"
ACTITYHITEDPOLLYINFO_POS_FIELD.full_name = ".Cmd.ActityHitedPollyInfo.pos"
ACTITYHITEDPOLLYINFO_POS_FIELD.number = 2
ACTITYHITEDPOLLYINFO_POS_FIELD.index = 1
ACTITYHITEDPOLLYINFO_POS_FIELD.label = 1
ACTITYHITEDPOLLYINFO_POS_FIELD.has_default_value = false
ACTITYHITEDPOLLYINFO_POS_FIELD.default_value = 0
ACTITYHITEDPOLLYINFO_POS_FIELD.type = 13
ACTITYHITEDPOLLYINFO_POS_FIELD.cpp_type = 3
ACTITYHITEDPOLLYINFO_REWARDID_FIELD.name = "rewardid"
ACTITYHITEDPOLLYINFO_REWARDID_FIELD.full_name = ".Cmd.ActityHitedPollyInfo.rewardid"
ACTITYHITEDPOLLYINFO_REWARDID_FIELD.number = 3
ACTITYHITEDPOLLYINFO_REWARDID_FIELD.index = 2
ACTITYHITEDPOLLYINFO_REWARDID_FIELD.label = 1
ACTITYHITEDPOLLYINFO_REWARDID_FIELD.has_default_value = false
ACTITYHITEDPOLLYINFO_REWARDID_FIELD.default_value = 0
ACTITYHITEDPOLLYINFO_REWARDID_FIELD.type = 13
ACTITYHITEDPOLLYINFO_REWARDID_FIELD.cpp_type = 3
ACTITYHITEDPOLLYINFO.name = "ActityHitedPollyInfo"
ACTITYHITEDPOLLYINFO.full_name = ".Cmd.ActityHitedPollyInfo"
ACTITYHITEDPOLLYINFO.nested_types = {}
ACTITYHITEDPOLLYINFO.enum_types = {}
ACTITYHITEDPOLLYINFO.fields = {
  ACTITYHITEDPOLLYINFO_ROUND_FIELD,
  ACTITYHITEDPOLLYINFO_POS_FIELD,
  ACTITYHITEDPOLLYINFO_REWARDID_FIELD
}
ACTITYHITEDPOLLYINFO.is_extendable = false
ACTITYHITEDPOLLYINFO.extensions = {}
ACTITYQUERYHITEDLIST_CMD_FIELD.name = "cmd"
ACTITYQUERYHITEDLIST_CMD_FIELD.full_name = ".Cmd.ActityQueryHitedList.cmd"
ACTITYQUERYHITEDLIST_CMD_FIELD.number = 1
ACTITYQUERYHITEDLIST_CMD_FIELD.index = 0
ACTITYQUERYHITEDLIST_CMD_FIELD.label = 1
ACTITYQUERYHITEDLIST_CMD_FIELD.has_default_value = true
ACTITYQUERYHITEDLIST_CMD_FIELD.default_value = 226
ACTITYQUERYHITEDLIST_CMD_FIELD.enum_type = XCMD_PB_COMMAND
ACTITYQUERYHITEDLIST_CMD_FIELD.type = 14
ACTITYQUERYHITEDLIST_CMD_FIELD.cpp_type = 8
ACTITYQUERYHITEDLIST_PARAM_FIELD.name = "param"
ACTITYQUERYHITEDLIST_PARAM_FIELD.full_name = ".Cmd.ActityQueryHitedList.param"
ACTITYQUERYHITEDLIST_PARAM_FIELD.number = 2
ACTITYQUERYHITEDLIST_PARAM_FIELD.index = 1
ACTITYQUERYHITEDLIST_PARAM_FIELD.label = 1
ACTITYQUERYHITEDLIST_PARAM_FIELD.has_default_value = true
ACTITYQUERYHITEDLIST_PARAM_FIELD.default_value = 1
ACTITYQUERYHITEDLIST_PARAM_FIELD.enum_type = ACTHIYPOLLYPARAM
ACTITYQUERYHITEDLIST_PARAM_FIELD.type = 14
ACTITYQUERYHITEDLIST_PARAM_FIELD.cpp_type = 8
ACTITYQUERYHITEDLIST_ROUND_FIELD.name = "round"
ACTITYQUERYHITEDLIST_ROUND_FIELD.full_name = ".Cmd.ActityQueryHitedList.round"
ACTITYQUERYHITEDLIST_ROUND_FIELD.number = 3
ACTITYQUERYHITEDLIST_ROUND_FIELD.index = 2
ACTITYQUERYHITEDLIST_ROUND_FIELD.label = 1
ACTITYQUERYHITEDLIST_ROUND_FIELD.has_default_value = false
ACTITYQUERYHITEDLIST_ROUND_FIELD.default_value = 0
ACTITYQUERYHITEDLIST_ROUND_FIELD.type = 13
ACTITYQUERYHITEDLIST_ROUND_FIELD.cpp_type = 3
ACTITYQUERYHITEDLIST_CURRENTROUND_FIELD.name = "currentround"
ACTITYQUERYHITEDLIST_CURRENTROUND_FIELD.full_name = ".Cmd.ActityQueryHitedList.currentround"
ACTITYQUERYHITEDLIST_CURRENTROUND_FIELD.number = 4
ACTITYQUERYHITEDLIST_CURRENTROUND_FIELD.index = 3
ACTITYQUERYHITEDLIST_CURRENTROUND_FIELD.label = 1
ACTITYQUERYHITEDLIST_CURRENTROUND_FIELD.has_default_value = false
ACTITYQUERYHITEDLIST_CURRENTROUND_FIELD.default_value = 0
ACTITYQUERYHITEDLIST_CURRENTROUND_FIELD.type = 13
ACTITYQUERYHITEDLIST_CURRENTROUND_FIELD.cpp_type = 3
ACTITYQUERYHITEDLIST_LIST_FIELD.name = "list"
ACTITYQUERYHITEDLIST_LIST_FIELD.full_name = ".Cmd.ActityQueryHitedList.list"
ACTITYQUERYHITEDLIST_LIST_FIELD.number = 5
ACTITYQUERYHITEDLIST_LIST_FIELD.index = 4
ACTITYQUERYHITEDLIST_LIST_FIELD.label = 3
ACTITYQUERYHITEDLIST_LIST_FIELD.has_default_value = false
ACTITYQUERYHITEDLIST_LIST_FIELD.default_value = {}
ACTITYQUERYHITEDLIST_LIST_FIELD.message_type = ACTITYHITEDPOLLYINFO
ACTITYQUERYHITEDLIST_LIST_FIELD.type = 11
ACTITYQUERYHITEDLIST_LIST_FIELD.cpp_type = 10
ACTITYQUERYHITEDLIST_RESTBUY_FIELD.name = "restbuy"
ACTITYQUERYHITEDLIST_RESTBUY_FIELD.full_name = ".Cmd.ActityQueryHitedList.restbuy"
ACTITYQUERYHITEDLIST_RESTBUY_FIELD.number = 6
ACTITYQUERYHITEDLIST_RESTBUY_FIELD.index = 5
ACTITYQUERYHITEDLIST_RESTBUY_FIELD.label = 1
ACTITYQUERYHITEDLIST_RESTBUY_FIELD.has_default_value = false
ACTITYQUERYHITEDLIST_RESTBUY_FIELD.default_value = 0
ACTITYQUERYHITEDLIST_RESTBUY_FIELD.type = 13
ACTITYQUERYHITEDLIST_RESTBUY_FIELD.cpp_type = 3
ACTITYQUERYHITEDLIST.name = "ActityQueryHitedList"
ACTITYQUERYHITEDLIST.full_name = ".Cmd.ActityQueryHitedList"
ACTITYQUERYHITEDLIST.nested_types = {}
ACTITYQUERYHITEDLIST.enum_types = {}
ACTITYQUERYHITEDLIST.fields = {
  ACTITYQUERYHITEDLIST_CMD_FIELD,
  ACTITYQUERYHITEDLIST_PARAM_FIELD,
  ACTITYQUERYHITEDLIST_ROUND_FIELD,
  ACTITYQUERYHITEDLIST_CURRENTROUND_FIELD,
  ACTITYQUERYHITEDLIST_LIST_FIELD,
  ACTITYQUERYHITEDLIST_RESTBUY_FIELD
}
ACTITYQUERYHITEDLIST.is_extendable = false
ACTITYQUERYHITEDLIST.extensions = {}
ACTIVITYHITPOLLY_CMD_FIELD.name = "cmd"
ACTIVITYHITPOLLY_CMD_FIELD.full_name = ".Cmd.ActivityHitPolly.cmd"
ACTIVITYHITPOLLY_CMD_FIELD.number = 1
ACTIVITYHITPOLLY_CMD_FIELD.index = 0
ACTIVITYHITPOLLY_CMD_FIELD.label = 1
ACTIVITYHITPOLLY_CMD_FIELD.has_default_value = true
ACTIVITYHITPOLLY_CMD_FIELD.default_value = 226
ACTIVITYHITPOLLY_CMD_FIELD.enum_type = XCMD_PB_COMMAND
ACTIVITYHITPOLLY_CMD_FIELD.type = 14
ACTIVITYHITPOLLY_CMD_FIELD.cpp_type = 8
ACTIVITYHITPOLLY_PARAM_FIELD.name = "param"
ACTIVITYHITPOLLY_PARAM_FIELD.full_name = ".Cmd.ActivityHitPolly.param"
ACTIVITYHITPOLLY_PARAM_FIELD.number = 2
ACTIVITYHITPOLLY_PARAM_FIELD.index = 1
ACTIVITYHITPOLLY_PARAM_FIELD.label = 1
ACTIVITYHITPOLLY_PARAM_FIELD.has_default_value = true
ACTIVITYHITPOLLY_PARAM_FIELD.default_value = 2
ACTIVITYHITPOLLY_PARAM_FIELD.enum_type = ACTHIYPOLLYPARAM
ACTIVITYHITPOLLY_PARAM_FIELD.type = 14
ACTIVITYHITPOLLY_PARAM_FIELD.cpp_type = 8
ACTIVITYHITPOLLY_ROUND_FIELD.name = "round"
ACTIVITYHITPOLLY_ROUND_FIELD.full_name = ".Cmd.ActivityHitPolly.round"
ACTIVITYHITPOLLY_ROUND_FIELD.number = 3
ACTIVITYHITPOLLY_ROUND_FIELD.index = 2
ACTIVITYHITPOLLY_ROUND_FIELD.label = 1
ACTIVITYHITPOLLY_ROUND_FIELD.has_default_value = false
ACTIVITYHITPOLLY_ROUND_FIELD.default_value = 0
ACTIVITYHITPOLLY_ROUND_FIELD.type = 13
ACTIVITYHITPOLLY_ROUND_FIELD.cpp_type = 3
ACTIVITYHITPOLLY_POS_FIELD.name = "pos"
ACTIVITYHITPOLLY_POS_FIELD.full_name = ".Cmd.ActivityHitPolly.pos"
ACTIVITYHITPOLLY_POS_FIELD.number = 4
ACTIVITYHITPOLLY_POS_FIELD.index = 3
ACTIVITYHITPOLLY_POS_FIELD.label = 1
ACTIVITYHITPOLLY_POS_FIELD.has_default_value = false
ACTIVITYHITPOLLY_POS_FIELD.default_value = 0
ACTIVITYHITPOLLY_POS_FIELD.type = 13
ACTIVITYHITPOLLY_POS_FIELD.cpp_type = 3
ACTIVITYHITPOLLY_REWARDID_FIELD.name = "rewardid"
ACTIVITYHITPOLLY_REWARDID_FIELD.full_name = ".Cmd.ActivityHitPolly.rewardid"
ACTIVITYHITPOLLY_REWARDID_FIELD.number = 5
ACTIVITYHITPOLLY_REWARDID_FIELD.index = 4
ACTIVITYHITPOLLY_REWARDID_FIELD.label = 1
ACTIVITYHITPOLLY_REWARDID_FIELD.has_default_value = false
ACTIVITYHITPOLLY_REWARDID_FIELD.default_value = 0
ACTIVITYHITPOLLY_REWARDID_FIELD.type = 13
ACTIVITYHITPOLLY_REWARDID_FIELD.cpp_type = 3
ACTIVITYHITPOLLY.name = "ActivityHitPolly"
ACTIVITYHITPOLLY.full_name = ".Cmd.ActivityHitPolly"
ACTIVITYHITPOLLY.nested_types = {}
ACTIVITYHITPOLLY.enum_types = {}
ACTIVITYHITPOLLY.fields = {
  ACTIVITYHITPOLLY_CMD_FIELD,
  ACTIVITYHITPOLLY_PARAM_FIELD,
  ACTIVITYHITPOLLY_ROUND_FIELD,
  ACTIVITYHITPOLLY_POS_FIELD,
  ACTIVITYHITPOLLY_REWARDID_FIELD
}
ACTIVITYHITPOLLY.is_extendable = false
ACTIVITYHITPOLLY.extensions = {}
ACTITYHITPOLLYSYNC_CMD_FIELD.name = "cmd"
ACTITYHITPOLLYSYNC_CMD_FIELD.full_name = ".Cmd.ActityHitPollySync.cmd"
ACTITYHITPOLLYSYNC_CMD_FIELD.number = 1
ACTITYHITPOLLYSYNC_CMD_FIELD.index = 0
ACTITYHITPOLLYSYNC_CMD_FIELD.label = 1
ACTITYHITPOLLYSYNC_CMD_FIELD.has_default_value = true
ACTITYHITPOLLYSYNC_CMD_FIELD.default_value = 226
ACTITYHITPOLLYSYNC_CMD_FIELD.enum_type = XCMD_PB_COMMAND
ACTITYHITPOLLYSYNC_CMD_FIELD.type = 14
ACTITYHITPOLLYSYNC_CMD_FIELD.cpp_type = 8
ACTITYHITPOLLYSYNC_PARAM_FIELD.name = "param"
ACTITYHITPOLLYSYNC_PARAM_FIELD.full_name = ".Cmd.ActityHitPollySync.param"
ACTITYHITPOLLYSYNC_PARAM_FIELD.number = 2
ACTITYHITPOLLYSYNC_PARAM_FIELD.index = 1
ACTITYHITPOLLYSYNC_PARAM_FIELD.label = 1
ACTITYHITPOLLYSYNC_PARAM_FIELD.has_default_value = true
ACTITYHITPOLLYSYNC_PARAM_FIELD.default_value = 3
ACTITYHITPOLLYSYNC_PARAM_FIELD.enum_type = ACTHIYPOLLYPARAM
ACTITYHITPOLLYSYNC_PARAM_FIELD.type = 14
ACTITYHITPOLLYSYNC_PARAM_FIELD.cpp_type = 8
ACTITYHITPOLLYSYNC_GLOBALACTID_FIELD.name = "globalactid"
ACTITYHITPOLLYSYNC_GLOBALACTID_FIELD.full_name = ".Cmd.ActityHitPollySync.globalactid"
ACTITYHITPOLLYSYNC_GLOBALACTID_FIELD.number = 3
ACTITYHITPOLLYSYNC_GLOBALACTID_FIELD.index = 2
ACTITYHITPOLLYSYNC_GLOBALACTID_FIELD.label = 1
ACTITYHITPOLLYSYNC_GLOBALACTID_FIELD.has_default_value = false
ACTITYHITPOLLYSYNC_GLOBALACTID_FIELD.default_value = 0
ACTITYHITPOLLYSYNC_GLOBALACTID_FIELD.type = 13
ACTITYHITPOLLYSYNC_GLOBALACTID_FIELD.cpp_type = 3
ACTITYHITPOLLYSYNC_CURROUND_FIELD.name = "curround"
ACTITYHITPOLLYSYNC_CURROUND_FIELD.full_name = ".Cmd.ActityHitPollySync.curround"
ACTITYHITPOLLYSYNC_CURROUND_FIELD.number = 4
ACTITYHITPOLLYSYNC_CURROUND_FIELD.index = 3
ACTITYHITPOLLYSYNC_CURROUND_FIELD.label = 1
ACTITYHITPOLLYSYNC_CURROUND_FIELD.has_default_value = false
ACTITYHITPOLLYSYNC_CURROUND_FIELD.default_value = 0
ACTITYHITPOLLYSYNC_CURROUND_FIELD.type = 13
ACTITYHITPOLLYSYNC_CURROUND_FIELD.cpp_type = 3
ACTITYHITPOLLYSYNC_QUESTS_FIELD.name = "quests"
ACTITYHITPOLLYSYNC_QUESTS_FIELD.full_name = ".Cmd.ActityHitPollySync.quests"
ACTITYHITPOLLYSYNC_QUESTS_FIELD.number = 5
ACTITYHITPOLLYSYNC_QUESTS_FIELD.index = 4
ACTITYHITPOLLYSYNC_QUESTS_FIELD.label = 3
ACTITYHITPOLLYSYNC_QUESTS_FIELD.has_default_value = false
ACTITYHITPOLLYSYNC_QUESTS_FIELD.default_value = {}
ACTITYHITPOLLYSYNC_QUESTS_FIELD.message_type = ACTIVITYHITPOLLYQUESTITEM
ACTITYHITPOLLYSYNC_QUESTS_FIELD.type = 11
ACTITYHITPOLLYSYNC_QUESTS_FIELD.cpp_type = 10
ACTITYHITPOLLYSYNC.name = "ActityHitPollySync"
ACTITYHITPOLLYSYNC.full_name = ".Cmd.ActityHitPollySync"
ACTITYHITPOLLYSYNC.nested_types = {}
ACTITYHITPOLLYSYNC.enum_types = {}
ACTITYHITPOLLYSYNC.fields = {
  ACTITYHITPOLLYSYNC_CMD_FIELD,
  ACTITYHITPOLLYSYNC_PARAM_FIELD,
  ACTITYHITPOLLYSYNC_GLOBALACTID_FIELD,
  ACTITYHITPOLLYSYNC_CURROUND_FIELD,
  ACTITYHITPOLLYSYNC_QUESTS_FIELD
}
ACTITYHITPOLLYSYNC.is_extendable = false
ACTITYHITPOLLYSYNC.extensions = {}
ACTITYHITPOLLYSUBMITQUEST_CMD_FIELD.name = "cmd"
ACTITYHITPOLLYSUBMITQUEST_CMD_FIELD.full_name = ".Cmd.ActityHitPollySubmitQuest.cmd"
ACTITYHITPOLLYSUBMITQUEST_CMD_FIELD.number = 1
ACTITYHITPOLLYSUBMITQUEST_CMD_FIELD.index = 0
ACTITYHITPOLLYSUBMITQUEST_CMD_FIELD.label = 1
ACTITYHITPOLLYSUBMITQUEST_CMD_FIELD.has_default_value = true
ACTITYHITPOLLYSUBMITQUEST_CMD_FIELD.default_value = 226
ACTITYHITPOLLYSUBMITQUEST_CMD_FIELD.enum_type = XCMD_PB_COMMAND
ACTITYHITPOLLYSUBMITQUEST_CMD_FIELD.type = 14
ACTITYHITPOLLYSUBMITQUEST_CMD_FIELD.cpp_type = 8
ACTITYHITPOLLYSUBMITQUEST_PARAM_FIELD.name = "param"
ACTITYHITPOLLYSUBMITQUEST_PARAM_FIELD.full_name = ".Cmd.ActityHitPollySubmitQuest.param"
ACTITYHITPOLLYSUBMITQUEST_PARAM_FIELD.number = 2
ACTITYHITPOLLYSUBMITQUEST_PARAM_FIELD.index = 1
ACTITYHITPOLLYSUBMITQUEST_PARAM_FIELD.label = 1
ACTITYHITPOLLYSUBMITQUEST_PARAM_FIELD.has_default_value = true
ACTITYHITPOLLYSUBMITQUEST_PARAM_FIELD.default_value = 4
ACTITYHITPOLLYSUBMITQUEST_PARAM_FIELD.enum_type = ACTHIYPOLLYPARAM
ACTITYHITPOLLYSUBMITQUEST_PARAM_FIELD.type = 14
ACTITYHITPOLLYSUBMITQUEST_PARAM_FIELD.cpp_type = 8
ACTITYHITPOLLYSUBMITQUEST_QUESTID_FIELD.name = "questid"
ACTITYHITPOLLYSUBMITQUEST_QUESTID_FIELD.full_name = ".Cmd.ActityHitPollySubmitQuest.questid"
ACTITYHITPOLLYSUBMITQUEST_QUESTID_FIELD.number = 3
ACTITYHITPOLLYSUBMITQUEST_QUESTID_FIELD.index = 2
ACTITYHITPOLLYSUBMITQUEST_QUESTID_FIELD.label = 1
ACTITYHITPOLLYSUBMITQUEST_QUESTID_FIELD.has_default_value = false
ACTITYHITPOLLYSUBMITQUEST_QUESTID_FIELD.default_value = 0
ACTITYHITPOLLYSUBMITQUEST_QUESTID_FIELD.type = 13
ACTITYHITPOLLYSUBMITQUEST_QUESTID_FIELD.cpp_type = 3
ACTITYHITPOLLYSUBMITQUEST.name = "ActityHitPollySubmitQuest"
ACTITYHITPOLLYSUBMITQUEST.full_name = ".Cmd.ActityHitPollySubmitQuest"
ACTITYHITPOLLYSUBMITQUEST.nested_types = {}
ACTITYHITPOLLYSUBMITQUEST.enum_types = {}
ACTITYHITPOLLYSUBMITQUEST.fields = {
  ACTITYHITPOLLYSUBMITQUEST_CMD_FIELD,
  ACTITYHITPOLLYSUBMITQUEST_PARAM_FIELD,
  ACTITYHITPOLLYSUBMITQUEST_QUESTID_FIELD
}
ACTITYHITPOLLYSUBMITQUEST.is_extendable = false
ACTITYHITPOLLYSUBMITQUEST.extensions = {}
ACTITYHITPOLLYNTFQUEST_CMD_FIELD.name = "cmd"
ACTITYHITPOLLYNTFQUEST_CMD_FIELD.full_name = ".Cmd.ActityHitPollyNtfQuest.cmd"
ACTITYHITPOLLYNTFQUEST_CMD_FIELD.number = 1
ACTITYHITPOLLYNTFQUEST_CMD_FIELD.index = 0
ACTITYHITPOLLYNTFQUEST_CMD_FIELD.label = 1
ACTITYHITPOLLYNTFQUEST_CMD_FIELD.has_default_value = true
ACTITYHITPOLLYNTFQUEST_CMD_FIELD.default_value = 226
ACTITYHITPOLLYNTFQUEST_CMD_FIELD.enum_type = XCMD_PB_COMMAND
ACTITYHITPOLLYNTFQUEST_CMD_FIELD.type = 14
ACTITYHITPOLLYNTFQUEST_CMD_FIELD.cpp_type = 8
ACTITYHITPOLLYNTFQUEST_PARAM_FIELD.name = "param"
ACTITYHITPOLLYNTFQUEST_PARAM_FIELD.full_name = ".Cmd.ActityHitPollyNtfQuest.param"
ACTITYHITPOLLYNTFQUEST_PARAM_FIELD.number = 2
ACTITYHITPOLLYNTFQUEST_PARAM_FIELD.index = 1
ACTITYHITPOLLYNTFQUEST_PARAM_FIELD.label = 1
ACTITYHITPOLLYNTFQUEST_PARAM_FIELD.has_default_value = true
ACTITYHITPOLLYNTFQUEST_PARAM_FIELD.default_value = 5
ACTITYHITPOLLYNTFQUEST_PARAM_FIELD.enum_type = ACTHIYPOLLYPARAM
ACTITYHITPOLLYNTFQUEST_PARAM_FIELD.type = 14
ACTITYHITPOLLYNTFQUEST_PARAM_FIELD.cpp_type = 8
ACTITYHITPOLLYNTFQUEST_QUESTS_FIELD.name = "quests"
ACTITYHITPOLLYNTFQUEST_QUESTS_FIELD.full_name = ".Cmd.ActityHitPollyNtfQuest.quests"
ACTITYHITPOLLYNTFQUEST_QUESTS_FIELD.number = 7
ACTITYHITPOLLYNTFQUEST_QUESTS_FIELD.index = 2
ACTITYHITPOLLYNTFQUEST_QUESTS_FIELD.label = 3
ACTITYHITPOLLYNTFQUEST_QUESTS_FIELD.has_default_value = false
ACTITYHITPOLLYNTFQUEST_QUESTS_FIELD.default_value = {}
ACTITYHITPOLLYNTFQUEST_QUESTS_FIELD.message_type = ACTIVITYHITPOLLYQUESTITEM
ACTITYHITPOLLYNTFQUEST_QUESTS_FIELD.type = 11
ACTITYHITPOLLYNTFQUEST_QUESTS_FIELD.cpp_type = 10
ACTITYHITPOLLYNTFQUEST.name = "ActityHitPollyNtfQuest"
ACTITYHITPOLLYNTFQUEST.full_name = ".Cmd.ActityHitPollyNtfQuest"
ACTITYHITPOLLYNTFQUEST.nested_types = {}
ACTITYHITPOLLYNTFQUEST.enum_types = {}
ACTITYHITPOLLYNTFQUEST.fields = {
  ACTITYHITPOLLYNTFQUEST_CMD_FIELD,
  ACTITYHITPOLLYNTFQUEST_PARAM_FIELD,
  ACTITYHITPOLLYNTFQUEST_QUESTS_FIELD
}
ACTITYHITPOLLYNTFQUEST.is_extendable = false
ACTITYHITPOLLYNTFQUEST.extensions = {}
ACTHIYPOLLYPARAM_HIT_POLLY = 2
ACTHIYPOLLYPARAM_QUERY_HITPOLLY_LIST = 1
ACTHIYPOLLYPARAM_QUEST_NTF = 5
ACTHIYPOLLYPARAM_SUBMIT_QUEST = 4
ACTHIYPOLLYPARAM_SYNC_ACT = 3
ActityHitPollyNtfQuest = protobuf.Message(ACTITYHITPOLLYNTFQUEST)
ActityHitPollySubmitQuest = protobuf.Message(ACTITYHITPOLLYSUBMITQUEST)
ActityHitPollySync = protobuf.Message(ACTITYHITPOLLYSYNC)
ActityHitedPollyInfo = protobuf.Message(ACTITYHITEDPOLLYINFO)
ActityQueryHitedList = protobuf.Message(ACTITYQUERYHITEDLIST)
ActivityHitPolly = protobuf.Message(ACTIVITYHITPOLLY)
ActivityHitPollyQuestItem = protobuf.Message(ACTIVITYHITPOLLYQUESTITEM)
EACCHITPOLLY_QUEST_FINISH = 3
EACCHITPOLLY_QUEST_NOT_OPEN = 0
EACCHITPOLLY_QUEST_ON = 1
EACCHITPOLLY_QUEST_SUBMITABLE = 2
