local protobuf = protobuf
autoImport("xCmd_pb")
local xCmd_pb = xCmd_pb
module("ActMiniRoCmd_pb")
ACTMINIROPARAM = protobuf.EnumDescriptor()
ACTMINIROPARAM_ACTMINIROPARAM_OPENPAGE_ENUM = protobuf.EnumValueDescriptor()
ACTMINIROPARAM_ACTMINIROPARAM_CAST_DICE_ENUM = protobuf.EnumValueDescriptor()
ACTMINIROPARAM_ACTMINIROPARAM_GET_ONEKEY_ENUM = protobuf.EnumValueDescriptor()
ACTMINIROPARAM_ACTMINIROPARAM_FREEDICE_SYNC_ENUM = protobuf.EnumValueDescriptor()
ACTMINIROPARAM_ACTMINIROPARAM_EVENT_FAQS_ENUM = protobuf.EnumValueDescriptor()
ACTMINIROPARAM_ACTMINIROPARAM_CHECK_CIRCLEREWARD_ENUM = protobuf.EnumValueDescriptor()
EACTMINIRODICETYPE = protobuf.EnumDescriptor()
EACTMINIRODICETYPE_EACTMINIRODICETYPE_NORMAL_ENUM = protobuf.EnumValueDescriptor()
EACTMINIRODICETYPE_EACTMINIRODICETYPE_ASSIGN_ENUM = protobuf.EnumValueDescriptor()
ACTMINIRODICE = protobuf.Descriptor()
ACTMINIRODICE_TYPE_FIELD = protobuf.FieldDescriptor()
ACTMINIRODICE_OWN_FIELD = protobuf.FieldDescriptor()
ACTMINIRODICEACCUMULATEINFO = protobuf.Descriptor()
ACTMINIRODICEACCUMULATEINFO_STORE_FIELD = protobuf.FieldDescriptor()
ACTMINIRODICEACCUMULATEINFO_STOREMAX_FIELD = protobuf.FieldDescriptor()
ACTMINIRODICEACCUMULATEINFO_NEXTTIMESTAMP_FIELD = protobuf.FieldDescriptor()
ACTMINIRODIALOGINFO = protobuf.Descriptor()
ACTMINIRODIALOGINFO_STEP_FIELD = protobuf.FieldDescriptor()
ACTMINIRODIALOGINFO_DIALOGID_FIELD = protobuf.FieldDescriptor()
ACTMINIROOPENPAGE = protobuf.Descriptor()
ACTMINIROOPENPAGE_CMD_FIELD = protobuf.FieldDescriptor()
ACTMINIROOPENPAGE_PARAM_FIELD = protobuf.FieldDescriptor()
ACTMINIROOPENPAGE_CURINDEX_FIELD = protobuf.FieldDescriptor()
ACTMINIROOPENPAGE_CIRCLES_FIELD = protobuf.FieldDescriptor()
ACTMINIROOPENPAGE_ONETIMEREWARDS_FIELD = protobuf.FieldDescriptor()
ACTMINIROOPENPAGE_DAYFIRST_FIELD = protobuf.FieldDescriptor()
ACTMINIROOPENPAGE_DICES_FIELD = protobuf.FieldDescriptor()
ACTMINIROOPENPAGE_DICEFREE_FIELD = protobuf.FieldDescriptor()
ACTMINIROOPENPAGE_UNANSWERQID_FIELD = protobuf.FieldDescriptor()
ACTMINIROOPENPAGE_DIALOGINFO_FIELD = protobuf.FieldDescriptor()
ACTMINIROCASTDICE = protobuf.Descriptor()
ACTMINIROCASTDICE_CMD_FIELD = protobuf.FieldDescriptor()
ACTMINIROCASTDICE_PARAM_FIELD = protobuf.FieldDescriptor()
ACTMINIROCASTDICE_TYPE_FIELD = protobuf.FieldDescriptor()
ACTMINIROCASTDICE_STEP_FIELD = protobuf.FieldDescriptor()
ACTMINIRODICESYNC = protobuf.Descriptor()
ACTMINIRODICESYNC_CMD_FIELD = protobuf.FieldDescriptor()
ACTMINIRODICESYNC_PARAM_FIELD = protobuf.FieldDescriptor()
ACTMINIRODICESYNC_DICESYNC_FIELD = protobuf.FieldDescriptor()
ACTMINIROGETONEKEY = protobuf.Descriptor()
ACTMINIROGETONEKEY_CMD_FIELD = protobuf.FieldDescriptor()
ACTMINIROGETONEKEY_PARAM_FIELD = protobuf.FieldDescriptor()
ACTMINIROEVENTFAQS = protobuf.Descriptor()
ACTMINIROEVENTFAQS_CMD_FIELD = protobuf.FieldDescriptor()
ACTMINIROEVENTFAQS_PARAM_FIELD = protobuf.FieldDescriptor()
ACTMINIROEVENTFAQS_QUESTIONID_FIELD = protobuf.FieldDescriptor()
ACTMINIROEVENTFAQS_ANSWER_FIELD = protobuf.FieldDescriptor()
ACTMINIROEVENTFAQS_RESULT_FIELD = protobuf.FieldDescriptor()
ACTMINIROCHECKCIRCLEREWARD = protobuf.Descriptor()
ACTMINIROCHECKCIRCLEREWARD_CMD_FIELD = protobuf.FieldDescriptor()
ACTMINIROCHECKCIRCLEREWARD_PARAM_FIELD = protobuf.FieldDescriptor()
ACTMINIROPARAM_ACTMINIROPARAM_OPENPAGE_ENUM.name = "ACTMINIROPARAM_OPENPAGE"
ACTMINIROPARAM_ACTMINIROPARAM_OPENPAGE_ENUM.index = 0
ACTMINIROPARAM_ACTMINIROPARAM_OPENPAGE_ENUM.number = 1
ACTMINIROPARAM_ACTMINIROPARAM_CAST_DICE_ENUM.name = "ACTMINIROPARAM_CAST_DICE"
ACTMINIROPARAM_ACTMINIROPARAM_CAST_DICE_ENUM.index = 1
ACTMINIROPARAM_ACTMINIROPARAM_CAST_DICE_ENUM.number = 2
ACTMINIROPARAM_ACTMINIROPARAM_GET_ONEKEY_ENUM.name = "ACTMINIROPARAM_GET_ONEKEY"
ACTMINIROPARAM_ACTMINIROPARAM_GET_ONEKEY_ENUM.index = 2
ACTMINIROPARAM_ACTMINIROPARAM_GET_ONEKEY_ENUM.number = 3
ACTMINIROPARAM_ACTMINIROPARAM_FREEDICE_SYNC_ENUM.name = "ACTMINIROPARAM_FREEDICE_SYNC"
ACTMINIROPARAM_ACTMINIROPARAM_FREEDICE_SYNC_ENUM.index = 3
ACTMINIROPARAM_ACTMINIROPARAM_FREEDICE_SYNC_ENUM.number = 4
ACTMINIROPARAM_ACTMINIROPARAM_EVENT_FAQS_ENUM.name = "ACTMINIROPARAM_EVENT_FAQS"
ACTMINIROPARAM_ACTMINIROPARAM_EVENT_FAQS_ENUM.index = 4
ACTMINIROPARAM_ACTMINIROPARAM_EVENT_FAQS_ENUM.number = 5
ACTMINIROPARAM_ACTMINIROPARAM_CHECK_CIRCLEREWARD_ENUM.name = "ACTMINIROPARAM_CHECK_CIRCLEREWARD"
ACTMINIROPARAM_ACTMINIROPARAM_CHECK_CIRCLEREWARD_ENUM.index = 5
ACTMINIROPARAM_ACTMINIROPARAM_CHECK_CIRCLEREWARD_ENUM.number = 6
ACTMINIROPARAM.name = "ActMiniRoParam"
ACTMINIROPARAM.full_name = ".Cmd.ActMiniRoParam"
ACTMINIROPARAM.values = {
  ACTMINIROPARAM_ACTMINIROPARAM_OPENPAGE_ENUM,
  ACTMINIROPARAM_ACTMINIROPARAM_CAST_DICE_ENUM,
  ACTMINIROPARAM_ACTMINIROPARAM_GET_ONEKEY_ENUM,
  ACTMINIROPARAM_ACTMINIROPARAM_FREEDICE_SYNC_ENUM,
  ACTMINIROPARAM_ACTMINIROPARAM_EVENT_FAQS_ENUM,
  ACTMINIROPARAM_ACTMINIROPARAM_CHECK_CIRCLEREWARD_ENUM
}
EACTMINIRODICETYPE_EACTMINIRODICETYPE_NORMAL_ENUM.name = "EACTMINIRODICETYPE_NORMAL"
EACTMINIRODICETYPE_EACTMINIRODICETYPE_NORMAL_ENUM.index = 0
EACTMINIRODICETYPE_EACTMINIRODICETYPE_NORMAL_ENUM.number = 1
EACTMINIRODICETYPE_EACTMINIRODICETYPE_ASSIGN_ENUM.name = "EACTMINIRODICETYPE_ASSIGN"
EACTMINIRODICETYPE_EACTMINIRODICETYPE_ASSIGN_ENUM.index = 1
EACTMINIRODICETYPE_EACTMINIRODICETYPE_ASSIGN_ENUM.number = 2
EACTMINIRODICETYPE.name = "EActMiniRoDiceType"
EACTMINIRODICETYPE.full_name = ".Cmd.EActMiniRoDiceType"
EACTMINIRODICETYPE.values = {
  EACTMINIRODICETYPE_EACTMINIRODICETYPE_NORMAL_ENUM,
  EACTMINIRODICETYPE_EACTMINIRODICETYPE_ASSIGN_ENUM
}
ACTMINIRODICE_TYPE_FIELD.name = "type"
ACTMINIRODICE_TYPE_FIELD.full_name = ".Cmd.ActMiniRoDice.type"
ACTMINIRODICE_TYPE_FIELD.number = 1
ACTMINIRODICE_TYPE_FIELD.index = 0
ACTMINIRODICE_TYPE_FIELD.label = 1
ACTMINIRODICE_TYPE_FIELD.has_default_value = false
ACTMINIRODICE_TYPE_FIELD.default_value = nil
ACTMINIRODICE_TYPE_FIELD.enum_type = EACTMINIRODICETYPE
ACTMINIRODICE_TYPE_FIELD.type = 14
ACTMINIRODICE_TYPE_FIELD.cpp_type = 8
ACTMINIRODICE_OWN_FIELD.name = "own"
ACTMINIRODICE_OWN_FIELD.full_name = ".Cmd.ActMiniRoDice.own"
ACTMINIRODICE_OWN_FIELD.number = 2
ACTMINIRODICE_OWN_FIELD.index = 1
ACTMINIRODICE_OWN_FIELD.label = 1
ACTMINIRODICE_OWN_FIELD.has_default_value = false
ACTMINIRODICE_OWN_FIELD.default_value = 0
ACTMINIRODICE_OWN_FIELD.type = 13
ACTMINIRODICE_OWN_FIELD.cpp_type = 3
ACTMINIRODICE.name = "ActMiniRoDice"
ACTMINIRODICE.full_name = ".Cmd.ActMiniRoDice"
ACTMINIRODICE.nested_types = {}
ACTMINIRODICE.enum_types = {}
ACTMINIRODICE.fields = {
  ACTMINIRODICE_TYPE_FIELD,
  ACTMINIRODICE_OWN_FIELD
}
ACTMINIRODICE.is_extendable = false
ACTMINIRODICE.extensions = {}
ACTMINIRODICEACCUMULATEINFO_STORE_FIELD.name = "store"
ACTMINIRODICEACCUMULATEINFO_STORE_FIELD.full_name = ".Cmd.ActMiniRoDiceAccumulateInfo.store"
ACTMINIRODICEACCUMULATEINFO_STORE_FIELD.number = 1
ACTMINIRODICEACCUMULATEINFO_STORE_FIELD.index = 0
ACTMINIRODICEACCUMULATEINFO_STORE_FIELD.label = 1
ACTMINIRODICEACCUMULATEINFO_STORE_FIELD.has_default_value = false
ACTMINIRODICEACCUMULATEINFO_STORE_FIELD.default_value = 0
ACTMINIRODICEACCUMULATEINFO_STORE_FIELD.type = 13
ACTMINIRODICEACCUMULATEINFO_STORE_FIELD.cpp_type = 3
ACTMINIRODICEACCUMULATEINFO_STOREMAX_FIELD.name = "storemax"
ACTMINIRODICEACCUMULATEINFO_STOREMAX_FIELD.full_name = ".Cmd.ActMiniRoDiceAccumulateInfo.storemax"
ACTMINIRODICEACCUMULATEINFO_STOREMAX_FIELD.number = 2
ACTMINIRODICEACCUMULATEINFO_STOREMAX_FIELD.index = 1
ACTMINIRODICEACCUMULATEINFO_STOREMAX_FIELD.label = 1
ACTMINIRODICEACCUMULATEINFO_STOREMAX_FIELD.has_default_value = false
ACTMINIRODICEACCUMULATEINFO_STOREMAX_FIELD.default_value = 0
ACTMINIRODICEACCUMULATEINFO_STOREMAX_FIELD.type = 13
ACTMINIRODICEACCUMULATEINFO_STOREMAX_FIELD.cpp_type = 3
ACTMINIRODICEACCUMULATEINFO_NEXTTIMESTAMP_FIELD.name = "nexttimestamp"
ACTMINIRODICEACCUMULATEINFO_NEXTTIMESTAMP_FIELD.full_name = ".Cmd.ActMiniRoDiceAccumulateInfo.nexttimestamp"
ACTMINIRODICEACCUMULATEINFO_NEXTTIMESTAMP_FIELD.number = 3
ACTMINIRODICEACCUMULATEINFO_NEXTTIMESTAMP_FIELD.index = 2
ACTMINIRODICEACCUMULATEINFO_NEXTTIMESTAMP_FIELD.label = 1
ACTMINIRODICEACCUMULATEINFO_NEXTTIMESTAMP_FIELD.has_default_value = false
ACTMINIRODICEACCUMULATEINFO_NEXTTIMESTAMP_FIELD.default_value = 0
ACTMINIRODICEACCUMULATEINFO_NEXTTIMESTAMP_FIELD.type = 13
ACTMINIRODICEACCUMULATEINFO_NEXTTIMESTAMP_FIELD.cpp_type = 3
ACTMINIRODICEACCUMULATEINFO.name = "ActMiniRoDiceAccumulateInfo"
ACTMINIRODICEACCUMULATEINFO.full_name = ".Cmd.ActMiniRoDiceAccumulateInfo"
ACTMINIRODICEACCUMULATEINFO.nested_types = {}
ACTMINIRODICEACCUMULATEINFO.enum_types = {}
ACTMINIRODICEACCUMULATEINFO.fields = {
  ACTMINIRODICEACCUMULATEINFO_STORE_FIELD,
  ACTMINIRODICEACCUMULATEINFO_STOREMAX_FIELD,
  ACTMINIRODICEACCUMULATEINFO_NEXTTIMESTAMP_FIELD
}
ACTMINIRODICEACCUMULATEINFO.is_extendable = false
ACTMINIRODICEACCUMULATEINFO.extensions = {}
ACTMINIRODIALOGINFO_STEP_FIELD.name = "step"
ACTMINIRODIALOGINFO_STEP_FIELD.full_name = ".Cmd.ActMiniRoDialogInfo.step"
ACTMINIRODIALOGINFO_STEP_FIELD.number = 1
ACTMINIRODIALOGINFO_STEP_FIELD.index = 0
ACTMINIRODIALOGINFO_STEP_FIELD.label = 1
ACTMINIRODIALOGINFO_STEP_FIELD.has_default_value = false
ACTMINIRODIALOGINFO_STEP_FIELD.default_value = 0
ACTMINIRODIALOGINFO_STEP_FIELD.type = 13
ACTMINIRODIALOGINFO_STEP_FIELD.cpp_type = 3
ACTMINIRODIALOGINFO_DIALOGID_FIELD.name = "dialogid"
ACTMINIRODIALOGINFO_DIALOGID_FIELD.full_name = ".Cmd.ActMiniRoDialogInfo.dialogid"
ACTMINIRODIALOGINFO_DIALOGID_FIELD.number = 2
ACTMINIRODIALOGINFO_DIALOGID_FIELD.index = 1
ACTMINIRODIALOGINFO_DIALOGID_FIELD.label = 1
ACTMINIRODIALOGINFO_DIALOGID_FIELD.has_default_value = false
ACTMINIRODIALOGINFO_DIALOGID_FIELD.default_value = 0
ACTMINIRODIALOGINFO_DIALOGID_FIELD.type = 13
ACTMINIRODIALOGINFO_DIALOGID_FIELD.cpp_type = 3
ACTMINIRODIALOGINFO.name = "ActMiniRoDialogInfo"
ACTMINIRODIALOGINFO.full_name = ".Cmd.ActMiniRoDialogInfo"
ACTMINIRODIALOGINFO.nested_types = {}
ACTMINIRODIALOGINFO.enum_types = {}
ACTMINIRODIALOGINFO.fields = {
  ACTMINIRODIALOGINFO_STEP_FIELD,
  ACTMINIRODIALOGINFO_DIALOGID_FIELD
}
ACTMINIRODIALOGINFO.is_extendable = false
ACTMINIRODIALOGINFO.extensions = {}
ACTMINIROOPENPAGE_CMD_FIELD.name = "cmd"
ACTMINIROOPENPAGE_CMD_FIELD.full_name = ".Cmd.ActMiniRoOpenPage.cmd"
ACTMINIROOPENPAGE_CMD_FIELD.number = 1
ACTMINIROOPENPAGE_CMD_FIELD.index = 0
ACTMINIROOPENPAGE_CMD_FIELD.label = 1
ACTMINIROOPENPAGE_CMD_FIELD.has_default_value = true
ACTMINIROOPENPAGE_CMD_FIELD.default_value = 229
ACTMINIROOPENPAGE_CMD_FIELD.enum_type = XCMD_PB_COMMAND
ACTMINIROOPENPAGE_CMD_FIELD.type = 14
ACTMINIROOPENPAGE_CMD_FIELD.cpp_type = 8
ACTMINIROOPENPAGE_PARAM_FIELD.name = "param"
ACTMINIROOPENPAGE_PARAM_FIELD.full_name = ".Cmd.ActMiniRoOpenPage.param"
ACTMINIROOPENPAGE_PARAM_FIELD.number = 2
ACTMINIROOPENPAGE_PARAM_FIELD.index = 1
ACTMINIROOPENPAGE_PARAM_FIELD.label = 1
ACTMINIROOPENPAGE_PARAM_FIELD.has_default_value = true
ACTMINIROOPENPAGE_PARAM_FIELD.default_value = 1
ACTMINIROOPENPAGE_PARAM_FIELD.enum_type = ACTMINIROPARAM
ACTMINIROOPENPAGE_PARAM_FIELD.type = 14
ACTMINIROOPENPAGE_PARAM_FIELD.cpp_type = 8
ACTMINIROOPENPAGE_CURINDEX_FIELD.name = "curindex"
ACTMINIROOPENPAGE_CURINDEX_FIELD.full_name = ".Cmd.ActMiniRoOpenPage.curindex"
ACTMINIROOPENPAGE_CURINDEX_FIELD.number = 3
ACTMINIROOPENPAGE_CURINDEX_FIELD.index = 2
ACTMINIROOPENPAGE_CURINDEX_FIELD.label = 1
ACTMINIROOPENPAGE_CURINDEX_FIELD.has_default_value = false
ACTMINIROOPENPAGE_CURINDEX_FIELD.default_value = 0
ACTMINIROOPENPAGE_CURINDEX_FIELD.type = 13
ACTMINIROOPENPAGE_CURINDEX_FIELD.cpp_type = 3
ACTMINIROOPENPAGE_CIRCLES_FIELD.name = "circles"
ACTMINIROOPENPAGE_CIRCLES_FIELD.full_name = ".Cmd.ActMiniRoOpenPage.circles"
ACTMINIROOPENPAGE_CIRCLES_FIELD.number = 4
ACTMINIROOPENPAGE_CIRCLES_FIELD.index = 3
ACTMINIROOPENPAGE_CIRCLES_FIELD.label = 1
ACTMINIROOPENPAGE_CIRCLES_FIELD.has_default_value = false
ACTMINIROOPENPAGE_CIRCLES_FIELD.default_value = 0
ACTMINIROOPENPAGE_CIRCLES_FIELD.type = 13
ACTMINIROOPENPAGE_CIRCLES_FIELD.cpp_type = 3
ACTMINIROOPENPAGE_ONETIMEREWARDS_FIELD.name = "onetimerewards"
ACTMINIROOPENPAGE_ONETIMEREWARDS_FIELD.full_name = ".Cmd.ActMiniRoOpenPage.onetimerewards"
ACTMINIROOPENPAGE_ONETIMEREWARDS_FIELD.number = 5
ACTMINIROOPENPAGE_ONETIMEREWARDS_FIELD.index = 4
ACTMINIROOPENPAGE_ONETIMEREWARDS_FIELD.label = 3
ACTMINIROOPENPAGE_ONETIMEREWARDS_FIELD.has_default_value = false
ACTMINIROOPENPAGE_ONETIMEREWARDS_FIELD.default_value = {}
ACTMINIROOPENPAGE_ONETIMEREWARDS_FIELD.type = 13
ACTMINIROOPENPAGE_ONETIMEREWARDS_FIELD.cpp_type = 3
ACTMINIROOPENPAGE_DAYFIRST_FIELD.name = "dayfirst"
ACTMINIROOPENPAGE_DAYFIRST_FIELD.full_name = ".Cmd.ActMiniRoOpenPage.dayfirst"
ACTMINIROOPENPAGE_DAYFIRST_FIELD.number = 6
ACTMINIROOPENPAGE_DAYFIRST_FIELD.index = 5
ACTMINIROOPENPAGE_DAYFIRST_FIELD.label = 1
ACTMINIROOPENPAGE_DAYFIRST_FIELD.has_default_value = true
ACTMINIROOPENPAGE_DAYFIRST_FIELD.default_value = false
ACTMINIROOPENPAGE_DAYFIRST_FIELD.type = 8
ACTMINIROOPENPAGE_DAYFIRST_FIELD.cpp_type = 7
ACTMINIROOPENPAGE_DICES_FIELD.name = "dices"
ACTMINIROOPENPAGE_DICES_FIELD.full_name = ".Cmd.ActMiniRoOpenPage.dices"
ACTMINIROOPENPAGE_DICES_FIELD.number = 7
ACTMINIROOPENPAGE_DICES_FIELD.index = 6
ACTMINIROOPENPAGE_DICES_FIELD.label = 3
ACTMINIROOPENPAGE_DICES_FIELD.has_default_value = false
ACTMINIROOPENPAGE_DICES_FIELD.default_value = {}
ACTMINIROOPENPAGE_DICES_FIELD.message_type = ACTMINIRODICE
ACTMINIROOPENPAGE_DICES_FIELD.type = 11
ACTMINIROOPENPAGE_DICES_FIELD.cpp_type = 10
ACTMINIROOPENPAGE_DICEFREE_FIELD.name = "dicefree"
ACTMINIROOPENPAGE_DICEFREE_FIELD.full_name = ".Cmd.ActMiniRoOpenPage.dicefree"
ACTMINIROOPENPAGE_DICEFREE_FIELD.number = 8
ACTMINIROOPENPAGE_DICEFREE_FIELD.index = 7
ACTMINIROOPENPAGE_DICEFREE_FIELD.label = 1
ACTMINIROOPENPAGE_DICEFREE_FIELD.has_default_value = false
ACTMINIROOPENPAGE_DICEFREE_FIELD.default_value = nil
ACTMINIROOPENPAGE_DICEFREE_FIELD.message_type = ACTMINIRODICEACCUMULATEINFO
ACTMINIROOPENPAGE_DICEFREE_FIELD.type = 11
ACTMINIROOPENPAGE_DICEFREE_FIELD.cpp_type = 10
ACTMINIROOPENPAGE_UNANSWERQID_FIELD.name = "unanswerqid"
ACTMINIROOPENPAGE_UNANSWERQID_FIELD.full_name = ".Cmd.ActMiniRoOpenPage.unanswerqid"
ACTMINIROOPENPAGE_UNANSWERQID_FIELD.number = 9
ACTMINIROOPENPAGE_UNANSWERQID_FIELD.index = 8
ACTMINIROOPENPAGE_UNANSWERQID_FIELD.label = 1
ACTMINIROOPENPAGE_UNANSWERQID_FIELD.has_default_value = false
ACTMINIROOPENPAGE_UNANSWERQID_FIELD.default_value = 0
ACTMINIROOPENPAGE_UNANSWERQID_FIELD.type = 13
ACTMINIROOPENPAGE_UNANSWERQID_FIELD.cpp_type = 3
ACTMINIROOPENPAGE_DIALOGINFO_FIELD.name = "dialoginfo"
ACTMINIROOPENPAGE_DIALOGINFO_FIELD.full_name = ".Cmd.ActMiniRoOpenPage.dialoginfo"
ACTMINIROOPENPAGE_DIALOGINFO_FIELD.number = 10
ACTMINIROOPENPAGE_DIALOGINFO_FIELD.index = 9
ACTMINIROOPENPAGE_DIALOGINFO_FIELD.label = 1
ACTMINIROOPENPAGE_DIALOGINFO_FIELD.has_default_value = false
ACTMINIROOPENPAGE_DIALOGINFO_FIELD.default_value = nil
ACTMINIROOPENPAGE_DIALOGINFO_FIELD.message_type = ACTMINIRODIALOGINFO
ACTMINIROOPENPAGE_DIALOGINFO_FIELD.type = 11
ACTMINIROOPENPAGE_DIALOGINFO_FIELD.cpp_type = 10
ACTMINIROOPENPAGE.name = "ActMiniRoOpenPage"
ACTMINIROOPENPAGE.full_name = ".Cmd.ActMiniRoOpenPage"
ACTMINIROOPENPAGE.nested_types = {}
ACTMINIROOPENPAGE.enum_types = {}
ACTMINIROOPENPAGE.fields = {
  ACTMINIROOPENPAGE_CMD_FIELD,
  ACTMINIROOPENPAGE_PARAM_FIELD,
  ACTMINIROOPENPAGE_CURINDEX_FIELD,
  ACTMINIROOPENPAGE_CIRCLES_FIELD,
  ACTMINIROOPENPAGE_ONETIMEREWARDS_FIELD,
  ACTMINIROOPENPAGE_DAYFIRST_FIELD,
  ACTMINIROOPENPAGE_DICES_FIELD,
  ACTMINIROOPENPAGE_DICEFREE_FIELD,
  ACTMINIROOPENPAGE_UNANSWERQID_FIELD,
  ACTMINIROOPENPAGE_DIALOGINFO_FIELD
}
ACTMINIROOPENPAGE.is_extendable = false
ACTMINIROOPENPAGE.extensions = {}
ACTMINIROCASTDICE_CMD_FIELD.name = "cmd"
ACTMINIROCASTDICE_CMD_FIELD.full_name = ".Cmd.ActMiniRoCastDice.cmd"
ACTMINIROCASTDICE_CMD_FIELD.number = 1
ACTMINIROCASTDICE_CMD_FIELD.index = 0
ACTMINIROCASTDICE_CMD_FIELD.label = 1
ACTMINIROCASTDICE_CMD_FIELD.has_default_value = true
ACTMINIROCASTDICE_CMD_FIELD.default_value = 229
ACTMINIROCASTDICE_CMD_FIELD.enum_type = XCMD_PB_COMMAND
ACTMINIROCASTDICE_CMD_FIELD.type = 14
ACTMINIROCASTDICE_CMD_FIELD.cpp_type = 8
ACTMINIROCASTDICE_PARAM_FIELD.name = "param"
ACTMINIROCASTDICE_PARAM_FIELD.full_name = ".Cmd.ActMiniRoCastDice.param"
ACTMINIROCASTDICE_PARAM_FIELD.number = 2
ACTMINIROCASTDICE_PARAM_FIELD.index = 1
ACTMINIROCASTDICE_PARAM_FIELD.label = 1
ACTMINIROCASTDICE_PARAM_FIELD.has_default_value = true
ACTMINIROCASTDICE_PARAM_FIELD.default_value = 2
ACTMINIROCASTDICE_PARAM_FIELD.enum_type = ACTMINIROPARAM
ACTMINIROCASTDICE_PARAM_FIELD.type = 14
ACTMINIROCASTDICE_PARAM_FIELD.cpp_type = 8
ACTMINIROCASTDICE_TYPE_FIELD.name = "type"
ACTMINIROCASTDICE_TYPE_FIELD.full_name = ".Cmd.ActMiniRoCastDice.type"
ACTMINIROCASTDICE_TYPE_FIELD.number = 3
ACTMINIROCASTDICE_TYPE_FIELD.index = 2
ACTMINIROCASTDICE_TYPE_FIELD.label = 1
ACTMINIROCASTDICE_TYPE_FIELD.has_default_value = false
ACTMINIROCASTDICE_TYPE_FIELD.default_value = nil
ACTMINIROCASTDICE_TYPE_FIELD.enum_type = EACTMINIRODICETYPE
ACTMINIROCASTDICE_TYPE_FIELD.type = 14
ACTMINIROCASTDICE_TYPE_FIELD.cpp_type = 8
ACTMINIROCASTDICE_STEP_FIELD.name = "step"
ACTMINIROCASTDICE_STEP_FIELD.full_name = ".Cmd.ActMiniRoCastDice.step"
ACTMINIROCASTDICE_STEP_FIELD.number = 4
ACTMINIROCASTDICE_STEP_FIELD.index = 3
ACTMINIROCASTDICE_STEP_FIELD.label = 1
ACTMINIROCASTDICE_STEP_FIELD.has_default_value = false
ACTMINIROCASTDICE_STEP_FIELD.default_value = 0
ACTMINIROCASTDICE_STEP_FIELD.type = 13
ACTMINIROCASTDICE_STEP_FIELD.cpp_type = 3
ACTMINIROCASTDICE.name = "ActMiniRoCastDice"
ACTMINIROCASTDICE.full_name = ".Cmd.ActMiniRoCastDice"
ACTMINIROCASTDICE.nested_types = {}
ACTMINIROCASTDICE.enum_types = {}
ACTMINIROCASTDICE.fields = {
  ACTMINIROCASTDICE_CMD_FIELD,
  ACTMINIROCASTDICE_PARAM_FIELD,
  ACTMINIROCASTDICE_TYPE_FIELD,
  ACTMINIROCASTDICE_STEP_FIELD
}
ACTMINIROCASTDICE.is_extendable = false
ACTMINIROCASTDICE.extensions = {}
ACTMINIRODICESYNC_CMD_FIELD.name = "cmd"
ACTMINIRODICESYNC_CMD_FIELD.full_name = ".Cmd.ActMiniRoDiceSync.cmd"
ACTMINIRODICESYNC_CMD_FIELD.number = 1
ACTMINIRODICESYNC_CMD_FIELD.index = 0
ACTMINIRODICESYNC_CMD_FIELD.label = 1
ACTMINIRODICESYNC_CMD_FIELD.has_default_value = true
ACTMINIRODICESYNC_CMD_FIELD.default_value = 229
ACTMINIRODICESYNC_CMD_FIELD.enum_type = XCMD_PB_COMMAND
ACTMINIRODICESYNC_CMD_FIELD.type = 14
ACTMINIRODICESYNC_CMD_FIELD.cpp_type = 8
ACTMINIRODICESYNC_PARAM_FIELD.name = "param"
ACTMINIRODICESYNC_PARAM_FIELD.full_name = ".Cmd.ActMiniRoDiceSync.param"
ACTMINIRODICESYNC_PARAM_FIELD.number = 2
ACTMINIRODICESYNC_PARAM_FIELD.index = 1
ACTMINIRODICESYNC_PARAM_FIELD.label = 1
ACTMINIRODICESYNC_PARAM_FIELD.has_default_value = true
ACTMINIRODICESYNC_PARAM_FIELD.default_value = 4
ACTMINIRODICESYNC_PARAM_FIELD.enum_type = ACTMINIROPARAM
ACTMINIRODICESYNC_PARAM_FIELD.type = 14
ACTMINIRODICESYNC_PARAM_FIELD.cpp_type = 8
ACTMINIRODICESYNC_DICESYNC_FIELD.name = "dicesync"
ACTMINIRODICESYNC_DICESYNC_FIELD.full_name = ".Cmd.ActMiniRoDiceSync.dicesync"
ACTMINIRODICESYNC_DICESYNC_FIELD.number = 3
ACTMINIRODICESYNC_DICESYNC_FIELD.index = 2
ACTMINIRODICESYNC_DICESYNC_FIELD.label = 1
ACTMINIRODICESYNC_DICESYNC_FIELD.has_default_value = false
ACTMINIRODICESYNC_DICESYNC_FIELD.default_value = nil
ACTMINIRODICESYNC_DICESYNC_FIELD.message_type = ACTMINIRODICEACCUMULATEINFO
ACTMINIRODICESYNC_DICESYNC_FIELD.type = 11
ACTMINIRODICESYNC_DICESYNC_FIELD.cpp_type = 10
ACTMINIRODICESYNC.name = "ActMiniRoDiceSync"
ACTMINIRODICESYNC.full_name = ".Cmd.ActMiniRoDiceSync"
ACTMINIRODICESYNC.nested_types = {}
ACTMINIRODICESYNC.enum_types = {}
ACTMINIRODICESYNC.fields = {
  ACTMINIRODICESYNC_CMD_FIELD,
  ACTMINIRODICESYNC_PARAM_FIELD,
  ACTMINIRODICESYNC_DICESYNC_FIELD
}
ACTMINIRODICESYNC.is_extendable = false
ACTMINIRODICESYNC.extensions = {}
ACTMINIROGETONEKEY_CMD_FIELD.name = "cmd"
ACTMINIROGETONEKEY_CMD_FIELD.full_name = ".Cmd.ActMiniRoGetOneKey.cmd"
ACTMINIROGETONEKEY_CMD_FIELD.number = 1
ACTMINIROGETONEKEY_CMD_FIELD.index = 0
ACTMINIROGETONEKEY_CMD_FIELD.label = 1
ACTMINIROGETONEKEY_CMD_FIELD.has_default_value = true
ACTMINIROGETONEKEY_CMD_FIELD.default_value = 229
ACTMINIROGETONEKEY_CMD_FIELD.enum_type = XCMD_PB_COMMAND
ACTMINIROGETONEKEY_CMD_FIELD.type = 14
ACTMINIROGETONEKEY_CMD_FIELD.cpp_type = 8
ACTMINIROGETONEKEY_PARAM_FIELD.name = "param"
ACTMINIROGETONEKEY_PARAM_FIELD.full_name = ".Cmd.ActMiniRoGetOneKey.param"
ACTMINIROGETONEKEY_PARAM_FIELD.number = 2
ACTMINIROGETONEKEY_PARAM_FIELD.index = 1
ACTMINIROGETONEKEY_PARAM_FIELD.label = 1
ACTMINIROGETONEKEY_PARAM_FIELD.has_default_value = true
ACTMINIROGETONEKEY_PARAM_FIELD.default_value = 3
ACTMINIROGETONEKEY_PARAM_FIELD.enum_type = ACTMINIROPARAM
ACTMINIROGETONEKEY_PARAM_FIELD.type = 14
ACTMINIROGETONEKEY_PARAM_FIELD.cpp_type = 8
ACTMINIROGETONEKEY.name = "ActMiniRoGetOneKey"
ACTMINIROGETONEKEY.full_name = ".Cmd.ActMiniRoGetOneKey"
ACTMINIROGETONEKEY.nested_types = {}
ACTMINIROGETONEKEY.enum_types = {}
ACTMINIROGETONEKEY.fields = {
  ACTMINIROGETONEKEY_CMD_FIELD,
  ACTMINIROGETONEKEY_PARAM_FIELD
}
ACTMINIROGETONEKEY.is_extendable = false
ACTMINIROGETONEKEY.extensions = {}
ACTMINIROEVENTFAQS_CMD_FIELD.name = "cmd"
ACTMINIROEVENTFAQS_CMD_FIELD.full_name = ".Cmd.ActMiniRoEventFAQS.cmd"
ACTMINIROEVENTFAQS_CMD_FIELD.number = 1
ACTMINIROEVENTFAQS_CMD_FIELD.index = 0
ACTMINIROEVENTFAQS_CMD_FIELD.label = 1
ACTMINIROEVENTFAQS_CMD_FIELD.has_default_value = true
ACTMINIROEVENTFAQS_CMD_FIELD.default_value = 229
ACTMINIROEVENTFAQS_CMD_FIELD.enum_type = XCMD_PB_COMMAND
ACTMINIROEVENTFAQS_CMD_FIELD.type = 14
ACTMINIROEVENTFAQS_CMD_FIELD.cpp_type = 8
ACTMINIROEVENTFAQS_PARAM_FIELD.name = "param"
ACTMINIROEVENTFAQS_PARAM_FIELD.full_name = ".Cmd.ActMiniRoEventFAQS.param"
ACTMINIROEVENTFAQS_PARAM_FIELD.number = 2
ACTMINIROEVENTFAQS_PARAM_FIELD.index = 1
ACTMINIROEVENTFAQS_PARAM_FIELD.label = 1
ACTMINIROEVENTFAQS_PARAM_FIELD.has_default_value = true
ACTMINIROEVENTFAQS_PARAM_FIELD.default_value = 5
ACTMINIROEVENTFAQS_PARAM_FIELD.enum_type = ACTMINIROPARAM
ACTMINIROEVENTFAQS_PARAM_FIELD.type = 14
ACTMINIROEVENTFAQS_PARAM_FIELD.cpp_type = 8
ACTMINIROEVENTFAQS_QUESTIONID_FIELD.name = "questionid"
ACTMINIROEVENTFAQS_QUESTIONID_FIELD.full_name = ".Cmd.ActMiniRoEventFAQS.questionid"
ACTMINIROEVENTFAQS_QUESTIONID_FIELD.number = 3
ACTMINIROEVENTFAQS_QUESTIONID_FIELD.index = 2
ACTMINIROEVENTFAQS_QUESTIONID_FIELD.label = 1
ACTMINIROEVENTFAQS_QUESTIONID_FIELD.has_default_value = false
ACTMINIROEVENTFAQS_QUESTIONID_FIELD.default_value = 0
ACTMINIROEVENTFAQS_QUESTIONID_FIELD.type = 13
ACTMINIROEVENTFAQS_QUESTIONID_FIELD.cpp_type = 3
ACTMINIROEVENTFAQS_ANSWER_FIELD.name = "answer"
ACTMINIROEVENTFAQS_ANSWER_FIELD.full_name = ".Cmd.ActMiniRoEventFAQS.answer"
ACTMINIROEVENTFAQS_ANSWER_FIELD.number = 4
ACTMINIROEVENTFAQS_ANSWER_FIELD.index = 3
ACTMINIROEVENTFAQS_ANSWER_FIELD.label = 1
ACTMINIROEVENTFAQS_ANSWER_FIELD.has_default_value = false
ACTMINIROEVENTFAQS_ANSWER_FIELD.default_value = 0
ACTMINIROEVENTFAQS_ANSWER_FIELD.type = 13
ACTMINIROEVENTFAQS_ANSWER_FIELD.cpp_type = 3
ACTMINIROEVENTFAQS_RESULT_FIELD.name = "result"
ACTMINIROEVENTFAQS_RESULT_FIELD.full_name = ".Cmd.ActMiniRoEventFAQS.result"
ACTMINIROEVENTFAQS_RESULT_FIELD.number = 5
ACTMINIROEVENTFAQS_RESULT_FIELD.index = 4
ACTMINIROEVENTFAQS_RESULT_FIELD.label = 1
ACTMINIROEVENTFAQS_RESULT_FIELD.has_default_value = false
ACTMINIROEVENTFAQS_RESULT_FIELD.default_value = false
ACTMINIROEVENTFAQS_RESULT_FIELD.type = 8
ACTMINIROEVENTFAQS_RESULT_FIELD.cpp_type = 7
ACTMINIROEVENTFAQS.name = "ActMiniRoEventFAQS"
ACTMINIROEVENTFAQS.full_name = ".Cmd.ActMiniRoEventFAQS"
ACTMINIROEVENTFAQS.nested_types = {}
ACTMINIROEVENTFAQS.enum_types = {}
ACTMINIROEVENTFAQS.fields = {
  ACTMINIROEVENTFAQS_CMD_FIELD,
  ACTMINIROEVENTFAQS_PARAM_FIELD,
  ACTMINIROEVENTFAQS_QUESTIONID_FIELD,
  ACTMINIROEVENTFAQS_ANSWER_FIELD,
  ACTMINIROEVENTFAQS_RESULT_FIELD
}
ACTMINIROEVENTFAQS.is_extendable = false
ACTMINIROEVENTFAQS.extensions = {}
ACTMINIROCHECKCIRCLEREWARD_CMD_FIELD.name = "cmd"
ACTMINIROCHECKCIRCLEREWARD_CMD_FIELD.full_name = ".Cmd.ActMiniRoCheckCircleReward.cmd"
ACTMINIROCHECKCIRCLEREWARD_CMD_FIELD.number = 1
ACTMINIROCHECKCIRCLEREWARD_CMD_FIELD.index = 0
ACTMINIROCHECKCIRCLEREWARD_CMD_FIELD.label = 1
ACTMINIROCHECKCIRCLEREWARD_CMD_FIELD.has_default_value = true
ACTMINIROCHECKCIRCLEREWARD_CMD_FIELD.default_value = 229
ACTMINIROCHECKCIRCLEREWARD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
ACTMINIROCHECKCIRCLEREWARD_CMD_FIELD.type = 14
ACTMINIROCHECKCIRCLEREWARD_CMD_FIELD.cpp_type = 8
ACTMINIROCHECKCIRCLEREWARD_PARAM_FIELD.name = "param"
ACTMINIROCHECKCIRCLEREWARD_PARAM_FIELD.full_name = ".Cmd.ActMiniRoCheckCircleReward.param"
ACTMINIROCHECKCIRCLEREWARD_PARAM_FIELD.number = 2
ACTMINIROCHECKCIRCLEREWARD_PARAM_FIELD.index = 1
ACTMINIROCHECKCIRCLEREWARD_PARAM_FIELD.label = 1
ACTMINIROCHECKCIRCLEREWARD_PARAM_FIELD.has_default_value = true
ACTMINIROCHECKCIRCLEREWARD_PARAM_FIELD.default_value = 6
ACTMINIROCHECKCIRCLEREWARD_PARAM_FIELD.enum_type = ACTMINIROPARAM
ACTMINIROCHECKCIRCLEREWARD_PARAM_FIELD.type = 14
ACTMINIROCHECKCIRCLEREWARD_PARAM_FIELD.cpp_type = 8
ACTMINIROCHECKCIRCLEREWARD.name = "ActMiniRoCheckCircleReward"
ACTMINIROCHECKCIRCLEREWARD.full_name = ".Cmd.ActMiniRoCheckCircleReward"
ACTMINIROCHECKCIRCLEREWARD.nested_types = {}
ACTMINIROCHECKCIRCLEREWARD.enum_types = {}
ACTMINIROCHECKCIRCLEREWARD.fields = {
  ACTMINIROCHECKCIRCLEREWARD_CMD_FIELD,
  ACTMINIROCHECKCIRCLEREWARD_PARAM_FIELD
}
ACTMINIROCHECKCIRCLEREWARD.is_extendable = false
ACTMINIROCHECKCIRCLEREWARD.extensions = {}
ACTMINIROPARAM_CAST_DICE = 2
ACTMINIROPARAM_CHECK_CIRCLEREWARD = 6
ACTMINIROPARAM_EVENT_FAQS = 5
ACTMINIROPARAM_FREEDICE_SYNC = 4
ACTMINIROPARAM_GET_ONEKEY = 3
ACTMINIROPARAM_OPENPAGE = 1
ActMiniRoCastDice = protobuf.Message(ACTMINIROCASTDICE)
ActMiniRoCheckCircleReward = protobuf.Message(ACTMINIROCHECKCIRCLEREWARD)
ActMiniRoDialogInfo = protobuf.Message(ACTMINIRODIALOGINFO)
ActMiniRoDice = protobuf.Message(ACTMINIRODICE)
ActMiniRoDiceAccumulateInfo = protobuf.Message(ACTMINIRODICEACCUMULATEINFO)
ActMiniRoDiceSync = protobuf.Message(ACTMINIRODICESYNC)
ActMiniRoEventFAQS = protobuf.Message(ACTMINIROEVENTFAQS)
ActMiniRoGetOneKey = protobuf.Message(ACTMINIROGETONEKEY)
ActMiniRoOpenPage = protobuf.Message(ACTMINIROOPENPAGE)
EACTMINIRODICETYPE_ASSIGN = 2
EACTMINIRODICETYPE_NORMAL = 1
