local protobuf = protobuf
autoImport("xCmd_pb")
local xCmd_pb = xCmd_pb
module("BattlePass_pb")
EBATTLEPASSPARAM = protobuf.EnumDescriptor()
EBATTLEPASSPARAM_BATTLEPASS_GET_REWAD_ENUM = protobuf.EnumValueDescriptor()
EBATTLEPASSPARAM_BATTLEPASS_UPDATE_REWARD_ENUM = protobuf.EnumValueDescriptor()
EBATTLEPASSPARAM_BATTLEPASS_BUY_LEVEL_ENUM = protobuf.EnumValueDescriptor()
EBATTLEPASSPARAM_BATTLEPASS_BUY_ADVANCE_ENUM = protobuf.EnumValueDescriptor()
EBATTLEPASSPARAM_BATTLEPASS_SYNC_INFO_ENUM = protobuf.EnumValueDescriptor()
EBATTLEPASSPARAM_BATTLEPASS_QUEST_INFO_ENUM = protobuf.EnumValueDescriptor()
GETREWARDBATTLEPASSCMD = protobuf.Descriptor()
GETREWARDBATTLEPASSCMD_CMD_FIELD = protobuf.FieldDescriptor()
GETREWARDBATTLEPASSCMD_PARAM_FIELD = protobuf.FieldDescriptor()
GETREWARDBATTLEPASSCMD_ALL_FIELD = protobuf.FieldDescriptor()
GETREWARDBATTLEPASSCMD_NORMAL_LV_FIELD = protobuf.FieldDescriptor()
GETREWARDBATTLEPASSCMD_PRO_LV_FIELD = protobuf.FieldDescriptor()
GETREWARDBATTLEPASSCMD_SU_LV_FIELD = protobuf.FieldDescriptor()
UPDATEREWARDBATTLEPASSCMD = protobuf.Descriptor()
UPDATEREWARDBATTLEPASSCMD_CMD_FIELD = protobuf.FieldDescriptor()
UPDATEREWARDBATTLEPASSCMD_PARAM_FIELD = protobuf.FieldDescriptor()
UPDATEREWARDBATTLEPASSCMD_LEVELS_FIELD = protobuf.FieldDescriptor()
UPDATEREWARDBATTLEPASSCMD_PROLEVELS_FIELD = protobuf.FieldDescriptor()
UPDATEREWARDBATTLEPASSCMD_SULEVELS_FIELD = protobuf.FieldDescriptor()
BUYLEVELBATTLEPASSCMD = protobuf.Descriptor()
BUYLEVELBATTLEPASSCMD_CMD_FIELD = protobuf.FieldDescriptor()
BUYLEVELBATTLEPASSCMD_PARAM_FIELD = protobuf.FieldDescriptor()
BUYLEVELBATTLEPASSCMD_LEVEL_FIELD = protobuf.FieldDescriptor()
ADVANCEBATTLEPASSCMD = protobuf.Descriptor()
ADVANCEBATTLEPASSCMD_CMD_FIELD = protobuf.FieldDescriptor()
ADVANCEBATTLEPASSCMD_PARAM_FIELD = protobuf.FieldDescriptor()
ADVANCEBATTLEPASSCMD_LEVEL_FIELD = protobuf.FieldDescriptor()
ADVANCEBATTLEPASSCMD_SUPER_FIELD = protobuf.FieldDescriptor()
SYNCINFOBATTLEPASSCMD = protobuf.Descriptor()
SYNCINFOBATTLEPASSCMD_CMD_FIELD = protobuf.FieldDescriptor()
SYNCINFOBATTLEPASSCMD_PARAM_FIELD = protobuf.FieldDescriptor()
SYNCINFOBATTLEPASSCMD_LEVEL_FIELD = protobuf.FieldDescriptor()
SYNCINFOBATTLEPASSCMD_PRO_LEVEL_FIELD = protobuf.FieldDescriptor()
SYNCINFOBATTLEPASSCMD_REWARDLVS_FIELD = protobuf.FieldDescriptor()
SYNCINFOBATTLEPASSCMD_REWARD_PROLVS_FIELD = protobuf.FieldDescriptor()
SYNCINFOBATTLEPASSCMD_EXP_FIELD = protobuf.FieldDescriptor()
SYNCINFOBATTLEPASSCMD_SU_LEVEL_FIELD = protobuf.FieldDescriptor()
SYNCINFOBATTLEPASSCMD_REWARD_SULVS_FIELD = protobuf.FieldDescriptor()
SYNCINFOBATTLEPASSCMD_VERSION_FIELD = protobuf.FieldDescriptor()
BATTLEPASSQUESTINFO = protobuf.Descriptor()
BATTLEPASSQUESTINFO_ID_FIELD = protobuf.FieldDescriptor()
BATTLEPASSQUESTINFO_PROCESS_FIELD = protobuf.FieldDescriptor()
BATTLEPASSQUESTINFOCMD = protobuf.Descriptor()
BATTLEPASSQUESTINFOCMD_CMD_FIELD = protobuf.FieldDescriptor()
BATTLEPASSQUESTINFOCMD_PARAM_FIELD = protobuf.FieldDescriptor()
BATTLEPASSQUESTINFOCMD_QUESTS_FIELD = protobuf.FieldDescriptor()
EBATTLEPASSPARAM_BATTLEPASS_GET_REWAD_ENUM.name = "BATTLEPASS_GET_REWAD"
EBATTLEPASSPARAM_BATTLEPASS_GET_REWAD_ENUM.index = 0
EBATTLEPASSPARAM_BATTLEPASS_GET_REWAD_ENUM.number = 1
EBATTLEPASSPARAM_BATTLEPASS_UPDATE_REWARD_ENUM.name = "BATTLEPASS_UPDATE_REWARD"
EBATTLEPASSPARAM_BATTLEPASS_UPDATE_REWARD_ENUM.index = 1
EBATTLEPASSPARAM_BATTLEPASS_UPDATE_REWARD_ENUM.number = 2
EBATTLEPASSPARAM_BATTLEPASS_BUY_LEVEL_ENUM.name = "BATTLEPASS_BUY_LEVEL"
EBATTLEPASSPARAM_BATTLEPASS_BUY_LEVEL_ENUM.index = 2
EBATTLEPASSPARAM_BATTLEPASS_BUY_LEVEL_ENUM.number = 3
EBATTLEPASSPARAM_BATTLEPASS_BUY_ADVANCE_ENUM.name = "BATTLEPASS_BUY_ADVANCE"
EBATTLEPASSPARAM_BATTLEPASS_BUY_ADVANCE_ENUM.index = 3
EBATTLEPASSPARAM_BATTLEPASS_BUY_ADVANCE_ENUM.number = 4
EBATTLEPASSPARAM_BATTLEPASS_SYNC_INFO_ENUM.name = "BATTLEPASS_SYNC_INFO"
EBATTLEPASSPARAM_BATTLEPASS_SYNC_INFO_ENUM.index = 4
EBATTLEPASSPARAM_BATTLEPASS_SYNC_INFO_ENUM.number = 5
EBATTLEPASSPARAM_BATTLEPASS_QUEST_INFO_ENUM.name = "BATTLEPASS_QUEST_INFO"
EBATTLEPASSPARAM_BATTLEPASS_QUEST_INFO_ENUM.index = 5
EBATTLEPASSPARAM_BATTLEPASS_QUEST_INFO_ENUM.number = 6
EBATTLEPASSPARAM.name = "EBattlePassParam"
EBATTLEPASSPARAM.full_name = ".Cmd.EBattlePassParam"
EBATTLEPASSPARAM.values = {
  EBATTLEPASSPARAM_BATTLEPASS_GET_REWAD_ENUM,
  EBATTLEPASSPARAM_BATTLEPASS_UPDATE_REWARD_ENUM,
  EBATTLEPASSPARAM_BATTLEPASS_BUY_LEVEL_ENUM,
  EBATTLEPASSPARAM_BATTLEPASS_BUY_ADVANCE_ENUM,
  EBATTLEPASSPARAM_BATTLEPASS_SYNC_INFO_ENUM,
  EBATTLEPASSPARAM_BATTLEPASS_QUEST_INFO_ENUM
}
GETREWARDBATTLEPASSCMD_CMD_FIELD.name = "cmd"
GETREWARDBATTLEPASSCMD_CMD_FIELD.full_name = ".Cmd.GetRewardBattlePassCmd.cmd"
GETREWARDBATTLEPASSCMD_CMD_FIELD.number = 1
GETREWARDBATTLEPASSCMD_CMD_FIELD.index = 0
GETREWARDBATTLEPASSCMD_CMD_FIELD.label = 1
GETREWARDBATTLEPASSCMD_CMD_FIELD.has_default_value = true
GETREWARDBATTLEPASSCMD_CMD_FIELD.default_value = 222
GETREWARDBATTLEPASSCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
GETREWARDBATTLEPASSCMD_CMD_FIELD.type = 14
GETREWARDBATTLEPASSCMD_CMD_FIELD.cpp_type = 8
GETREWARDBATTLEPASSCMD_PARAM_FIELD.name = "param"
GETREWARDBATTLEPASSCMD_PARAM_FIELD.full_name = ".Cmd.GetRewardBattlePassCmd.param"
GETREWARDBATTLEPASSCMD_PARAM_FIELD.number = 2
GETREWARDBATTLEPASSCMD_PARAM_FIELD.index = 1
GETREWARDBATTLEPASSCMD_PARAM_FIELD.label = 1
GETREWARDBATTLEPASSCMD_PARAM_FIELD.has_default_value = true
GETREWARDBATTLEPASSCMD_PARAM_FIELD.default_value = 1
GETREWARDBATTLEPASSCMD_PARAM_FIELD.enum_type = EBATTLEPASSPARAM
GETREWARDBATTLEPASSCMD_PARAM_FIELD.type = 14
GETREWARDBATTLEPASSCMD_PARAM_FIELD.cpp_type = 8
GETREWARDBATTLEPASSCMD_ALL_FIELD.name = "all"
GETREWARDBATTLEPASSCMD_ALL_FIELD.full_name = ".Cmd.GetRewardBattlePassCmd.all"
GETREWARDBATTLEPASSCMD_ALL_FIELD.number = 3
GETREWARDBATTLEPASSCMD_ALL_FIELD.index = 2
GETREWARDBATTLEPASSCMD_ALL_FIELD.label = 1
GETREWARDBATTLEPASSCMD_ALL_FIELD.has_default_value = true
GETREWARDBATTLEPASSCMD_ALL_FIELD.default_value = false
GETREWARDBATTLEPASSCMD_ALL_FIELD.type = 8
GETREWARDBATTLEPASSCMD_ALL_FIELD.cpp_type = 7
GETREWARDBATTLEPASSCMD_NORMAL_LV_FIELD.name = "normal_lv"
GETREWARDBATTLEPASSCMD_NORMAL_LV_FIELD.full_name = ".Cmd.GetRewardBattlePassCmd.normal_lv"
GETREWARDBATTLEPASSCMD_NORMAL_LV_FIELD.number = 4
GETREWARDBATTLEPASSCMD_NORMAL_LV_FIELD.index = 3
GETREWARDBATTLEPASSCMD_NORMAL_LV_FIELD.label = 1
GETREWARDBATTLEPASSCMD_NORMAL_LV_FIELD.has_default_value = true
GETREWARDBATTLEPASSCMD_NORMAL_LV_FIELD.default_value = 0
GETREWARDBATTLEPASSCMD_NORMAL_LV_FIELD.type = 13
GETREWARDBATTLEPASSCMD_NORMAL_LV_FIELD.cpp_type = 3
GETREWARDBATTLEPASSCMD_PRO_LV_FIELD.name = "pro_lv"
GETREWARDBATTLEPASSCMD_PRO_LV_FIELD.full_name = ".Cmd.GetRewardBattlePassCmd.pro_lv"
GETREWARDBATTLEPASSCMD_PRO_LV_FIELD.number = 5
GETREWARDBATTLEPASSCMD_PRO_LV_FIELD.index = 4
GETREWARDBATTLEPASSCMD_PRO_LV_FIELD.label = 1
GETREWARDBATTLEPASSCMD_PRO_LV_FIELD.has_default_value = true
GETREWARDBATTLEPASSCMD_PRO_LV_FIELD.default_value = 0
GETREWARDBATTLEPASSCMD_PRO_LV_FIELD.type = 13
GETREWARDBATTLEPASSCMD_PRO_LV_FIELD.cpp_type = 3
GETREWARDBATTLEPASSCMD_SU_LV_FIELD.name = "su_lv"
GETREWARDBATTLEPASSCMD_SU_LV_FIELD.full_name = ".Cmd.GetRewardBattlePassCmd.su_lv"
GETREWARDBATTLEPASSCMD_SU_LV_FIELD.number = 6
GETREWARDBATTLEPASSCMD_SU_LV_FIELD.index = 5
GETREWARDBATTLEPASSCMD_SU_LV_FIELD.label = 1
GETREWARDBATTLEPASSCMD_SU_LV_FIELD.has_default_value = true
GETREWARDBATTLEPASSCMD_SU_LV_FIELD.default_value = 0
GETREWARDBATTLEPASSCMD_SU_LV_FIELD.type = 13
GETREWARDBATTLEPASSCMD_SU_LV_FIELD.cpp_type = 3
GETREWARDBATTLEPASSCMD.name = "GetRewardBattlePassCmd"
GETREWARDBATTLEPASSCMD.full_name = ".Cmd.GetRewardBattlePassCmd"
GETREWARDBATTLEPASSCMD.nested_types = {}
GETREWARDBATTLEPASSCMD.enum_types = {}
GETREWARDBATTLEPASSCMD.fields = {
  GETREWARDBATTLEPASSCMD_CMD_FIELD,
  GETREWARDBATTLEPASSCMD_PARAM_FIELD,
  GETREWARDBATTLEPASSCMD_ALL_FIELD,
  GETREWARDBATTLEPASSCMD_NORMAL_LV_FIELD,
  GETREWARDBATTLEPASSCMD_PRO_LV_FIELD,
  GETREWARDBATTLEPASSCMD_SU_LV_FIELD
}
GETREWARDBATTLEPASSCMD.is_extendable = false
GETREWARDBATTLEPASSCMD.extensions = {}
UPDATEREWARDBATTLEPASSCMD_CMD_FIELD.name = "cmd"
UPDATEREWARDBATTLEPASSCMD_CMD_FIELD.full_name = ".Cmd.UpdateRewardBattlePassCmd.cmd"
UPDATEREWARDBATTLEPASSCMD_CMD_FIELD.number = 1
UPDATEREWARDBATTLEPASSCMD_CMD_FIELD.index = 0
UPDATEREWARDBATTLEPASSCMD_CMD_FIELD.label = 1
UPDATEREWARDBATTLEPASSCMD_CMD_FIELD.has_default_value = true
UPDATEREWARDBATTLEPASSCMD_CMD_FIELD.default_value = 222
UPDATEREWARDBATTLEPASSCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
UPDATEREWARDBATTLEPASSCMD_CMD_FIELD.type = 14
UPDATEREWARDBATTLEPASSCMD_CMD_FIELD.cpp_type = 8
UPDATEREWARDBATTLEPASSCMD_PARAM_FIELD.name = "param"
UPDATEREWARDBATTLEPASSCMD_PARAM_FIELD.full_name = ".Cmd.UpdateRewardBattlePassCmd.param"
UPDATEREWARDBATTLEPASSCMD_PARAM_FIELD.number = 2
UPDATEREWARDBATTLEPASSCMD_PARAM_FIELD.index = 1
UPDATEREWARDBATTLEPASSCMD_PARAM_FIELD.label = 1
UPDATEREWARDBATTLEPASSCMD_PARAM_FIELD.has_default_value = true
UPDATEREWARDBATTLEPASSCMD_PARAM_FIELD.default_value = 2
UPDATEREWARDBATTLEPASSCMD_PARAM_FIELD.enum_type = EBATTLEPASSPARAM
UPDATEREWARDBATTLEPASSCMD_PARAM_FIELD.type = 14
UPDATEREWARDBATTLEPASSCMD_PARAM_FIELD.cpp_type = 8
UPDATEREWARDBATTLEPASSCMD_LEVELS_FIELD.name = "levels"
UPDATEREWARDBATTLEPASSCMD_LEVELS_FIELD.full_name = ".Cmd.UpdateRewardBattlePassCmd.levels"
UPDATEREWARDBATTLEPASSCMD_LEVELS_FIELD.number = 3
UPDATEREWARDBATTLEPASSCMD_LEVELS_FIELD.index = 2
UPDATEREWARDBATTLEPASSCMD_LEVELS_FIELD.label = 3
UPDATEREWARDBATTLEPASSCMD_LEVELS_FIELD.has_default_value = false
UPDATEREWARDBATTLEPASSCMD_LEVELS_FIELD.default_value = {}
UPDATEREWARDBATTLEPASSCMD_LEVELS_FIELD.type = 13
UPDATEREWARDBATTLEPASSCMD_LEVELS_FIELD.cpp_type = 3
UPDATEREWARDBATTLEPASSCMD_PROLEVELS_FIELD.name = "prolevels"
UPDATEREWARDBATTLEPASSCMD_PROLEVELS_FIELD.full_name = ".Cmd.UpdateRewardBattlePassCmd.prolevels"
UPDATEREWARDBATTLEPASSCMD_PROLEVELS_FIELD.number = 4
UPDATEREWARDBATTLEPASSCMD_PROLEVELS_FIELD.index = 3
UPDATEREWARDBATTLEPASSCMD_PROLEVELS_FIELD.label = 3
UPDATEREWARDBATTLEPASSCMD_PROLEVELS_FIELD.has_default_value = false
UPDATEREWARDBATTLEPASSCMD_PROLEVELS_FIELD.default_value = {}
UPDATEREWARDBATTLEPASSCMD_PROLEVELS_FIELD.type = 13
UPDATEREWARDBATTLEPASSCMD_PROLEVELS_FIELD.cpp_type = 3
UPDATEREWARDBATTLEPASSCMD_SULEVELS_FIELD.name = "sulevels"
UPDATEREWARDBATTLEPASSCMD_SULEVELS_FIELD.full_name = ".Cmd.UpdateRewardBattlePassCmd.sulevels"
UPDATEREWARDBATTLEPASSCMD_SULEVELS_FIELD.number = 5
UPDATEREWARDBATTLEPASSCMD_SULEVELS_FIELD.index = 4
UPDATEREWARDBATTLEPASSCMD_SULEVELS_FIELD.label = 3
UPDATEREWARDBATTLEPASSCMD_SULEVELS_FIELD.has_default_value = false
UPDATEREWARDBATTLEPASSCMD_SULEVELS_FIELD.default_value = {}
UPDATEREWARDBATTLEPASSCMD_SULEVELS_FIELD.type = 13
UPDATEREWARDBATTLEPASSCMD_SULEVELS_FIELD.cpp_type = 3
UPDATEREWARDBATTLEPASSCMD.name = "UpdateRewardBattlePassCmd"
UPDATEREWARDBATTLEPASSCMD.full_name = ".Cmd.UpdateRewardBattlePassCmd"
UPDATEREWARDBATTLEPASSCMD.nested_types = {}
UPDATEREWARDBATTLEPASSCMD.enum_types = {}
UPDATEREWARDBATTLEPASSCMD.fields = {
  UPDATEREWARDBATTLEPASSCMD_CMD_FIELD,
  UPDATEREWARDBATTLEPASSCMD_PARAM_FIELD,
  UPDATEREWARDBATTLEPASSCMD_LEVELS_FIELD,
  UPDATEREWARDBATTLEPASSCMD_PROLEVELS_FIELD,
  UPDATEREWARDBATTLEPASSCMD_SULEVELS_FIELD
}
UPDATEREWARDBATTLEPASSCMD.is_extendable = false
UPDATEREWARDBATTLEPASSCMD.extensions = {}
BUYLEVELBATTLEPASSCMD_CMD_FIELD.name = "cmd"
BUYLEVELBATTLEPASSCMD_CMD_FIELD.full_name = ".Cmd.BuyLevelBattlePassCmd.cmd"
BUYLEVELBATTLEPASSCMD_CMD_FIELD.number = 1
BUYLEVELBATTLEPASSCMD_CMD_FIELD.index = 0
BUYLEVELBATTLEPASSCMD_CMD_FIELD.label = 1
BUYLEVELBATTLEPASSCMD_CMD_FIELD.has_default_value = true
BUYLEVELBATTLEPASSCMD_CMD_FIELD.default_value = 222
BUYLEVELBATTLEPASSCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
BUYLEVELBATTLEPASSCMD_CMD_FIELD.type = 14
BUYLEVELBATTLEPASSCMD_CMD_FIELD.cpp_type = 8
BUYLEVELBATTLEPASSCMD_PARAM_FIELD.name = "param"
BUYLEVELBATTLEPASSCMD_PARAM_FIELD.full_name = ".Cmd.BuyLevelBattlePassCmd.param"
BUYLEVELBATTLEPASSCMD_PARAM_FIELD.number = 2
BUYLEVELBATTLEPASSCMD_PARAM_FIELD.index = 1
BUYLEVELBATTLEPASSCMD_PARAM_FIELD.label = 1
BUYLEVELBATTLEPASSCMD_PARAM_FIELD.has_default_value = true
BUYLEVELBATTLEPASSCMD_PARAM_FIELD.default_value = 3
BUYLEVELBATTLEPASSCMD_PARAM_FIELD.enum_type = EBATTLEPASSPARAM
BUYLEVELBATTLEPASSCMD_PARAM_FIELD.type = 14
BUYLEVELBATTLEPASSCMD_PARAM_FIELD.cpp_type = 8
BUYLEVELBATTLEPASSCMD_LEVEL_FIELD.name = "level"
BUYLEVELBATTLEPASSCMD_LEVEL_FIELD.full_name = ".Cmd.BuyLevelBattlePassCmd.level"
BUYLEVELBATTLEPASSCMD_LEVEL_FIELD.number = 3
BUYLEVELBATTLEPASSCMD_LEVEL_FIELD.index = 2
BUYLEVELBATTLEPASSCMD_LEVEL_FIELD.label = 1
BUYLEVELBATTLEPASSCMD_LEVEL_FIELD.has_default_value = true
BUYLEVELBATTLEPASSCMD_LEVEL_FIELD.default_value = 0
BUYLEVELBATTLEPASSCMD_LEVEL_FIELD.type = 13
BUYLEVELBATTLEPASSCMD_LEVEL_FIELD.cpp_type = 3
BUYLEVELBATTLEPASSCMD.name = "BuyLevelBattlePassCmd"
BUYLEVELBATTLEPASSCMD.full_name = ".Cmd.BuyLevelBattlePassCmd"
BUYLEVELBATTLEPASSCMD.nested_types = {}
BUYLEVELBATTLEPASSCMD.enum_types = {}
BUYLEVELBATTLEPASSCMD.fields = {
  BUYLEVELBATTLEPASSCMD_CMD_FIELD,
  BUYLEVELBATTLEPASSCMD_PARAM_FIELD,
  BUYLEVELBATTLEPASSCMD_LEVEL_FIELD
}
BUYLEVELBATTLEPASSCMD.is_extendable = false
BUYLEVELBATTLEPASSCMD.extensions = {}
ADVANCEBATTLEPASSCMD_CMD_FIELD.name = "cmd"
ADVANCEBATTLEPASSCMD_CMD_FIELD.full_name = ".Cmd.AdvanceBattlePassCmd.cmd"
ADVANCEBATTLEPASSCMD_CMD_FIELD.number = 1
ADVANCEBATTLEPASSCMD_CMD_FIELD.index = 0
ADVANCEBATTLEPASSCMD_CMD_FIELD.label = 1
ADVANCEBATTLEPASSCMD_CMD_FIELD.has_default_value = true
ADVANCEBATTLEPASSCMD_CMD_FIELD.default_value = 222
ADVANCEBATTLEPASSCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
ADVANCEBATTLEPASSCMD_CMD_FIELD.type = 14
ADVANCEBATTLEPASSCMD_CMD_FIELD.cpp_type = 8
ADVANCEBATTLEPASSCMD_PARAM_FIELD.name = "param"
ADVANCEBATTLEPASSCMD_PARAM_FIELD.full_name = ".Cmd.AdvanceBattlePassCmd.param"
ADVANCEBATTLEPASSCMD_PARAM_FIELD.number = 2
ADVANCEBATTLEPASSCMD_PARAM_FIELD.index = 1
ADVANCEBATTLEPASSCMD_PARAM_FIELD.label = 1
ADVANCEBATTLEPASSCMD_PARAM_FIELD.has_default_value = true
ADVANCEBATTLEPASSCMD_PARAM_FIELD.default_value = 4
ADVANCEBATTLEPASSCMD_PARAM_FIELD.enum_type = EBATTLEPASSPARAM
ADVANCEBATTLEPASSCMD_PARAM_FIELD.type = 14
ADVANCEBATTLEPASSCMD_PARAM_FIELD.cpp_type = 8
ADVANCEBATTLEPASSCMD_LEVEL_FIELD.name = "level"
ADVANCEBATTLEPASSCMD_LEVEL_FIELD.full_name = ".Cmd.AdvanceBattlePassCmd.level"
ADVANCEBATTLEPASSCMD_LEVEL_FIELD.number = 3
ADVANCEBATTLEPASSCMD_LEVEL_FIELD.index = 2
ADVANCEBATTLEPASSCMD_LEVEL_FIELD.label = 1
ADVANCEBATTLEPASSCMD_LEVEL_FIELD.has_default_value = true
ADVANCEBATTLEPASSCMD_LEVEL_FIELD.default_value = 0
ADVANCEBATTLEPASSCMD_LEVEL_FIELD.type = 13
ADVANCEBATTLEPASSCMD_LEVEL_FIELD.cpp_type = 3
ADVANCEBATTLEPASSCMD_SUPER_FIELD.name = "super"
ADVANCEBATTLEPASSCMD_SUPER_FIELD.full_name = ".Cmd.AdvanceBattlePassCmd.super"
ADVANCEBATTLEPASSCMD_SUPER_FIELD.number = 4
ADVANCEBATTLEPASSCMD_SUPER_FIELD.index = 3
ADVANCEBATTLEPASSCMD_SUPER_FIELD.label = 1
ADVANCEBATTLEPASSCMD_SUPER_FIELD.has_default_value = true
ADVANCEBATTLEPASSCMD_SUPER_FIELD.default_value = false
ADVANCEBATTLEPASSCMD_SUPER_FIELD.type = 8
ADVANCEBATTLEPASSCMD_SUPER_FIELD.cpp_type = 7
ADVANCEBATTLEPASSCMD.name = "AdvanceBattlePassCmd"
ADVANCEBATTLEPASSCMD.full_name = ".Cmd.AdvanceBattlePassCmd"
ADVANCEBATTLEPASSCMD.nested_types = {}
ADVANCEBATTLEPASSCMD.enum_types = {}
ADVANCEBATTLEPASSCMD.fields = {
  ADVANCEBATTLEPASSCMD_CMD_FIELD,
  ADVANCEBATTLEPASSCMD_PARAM_FIELD,
  ADVANCEBATTLEPASSCMD_LEVEL_FIELD,
  ADVANCEBATTLEPASSCMD_SUPER_FIELD
}
ADVANCEBATTLEPASSCMD.is_extendable = false
ADVANCEBATTLEPASSCMD.extensions = {}
SYNCINFOBATTLEPASSCMD_CMD_FIELD.name = "cmd"
SYNCINFOBATTLEPASSCMD_CMD_FIELD.full_name = ".Cmd.SyncInfoBattlePassCmd.cmd"
SYNCINFOBATTLEPASSCMD_CMD_FIELD.number = 1
SYNCINFOBATTLEPASSCMD_CMD_FIELD.index = 0
SYNCINFOBATTLEPASSCMD_CMD_FIELD.label = 1
SYNCINFOBATTLEPASSCMD_CMD_FIELD.has_default_value = true
SYNCINFOBATTLEPASSCMD_CMD_FIELD.default_value = 222
SYNCINFOBATTLEPASSCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
SYNCINFOBATTLEPASSCMD_CMD_FIELD.type = 14
SYNCINFOBATTLEPASSCMD_CMD_FIELD.cpp_type = 8
SYNCINFOBATTLEPASSCMD_PARAM_FIELD.name = "param"
SYNCINFOBATTLEPASSCMD_PARAM_FIELD.full_name = ".Cmd.SyncInfoBattlePassCmd.param"
SYNCINFOBATTLEPASSCMD_PARAM_FIELD.number = 2
SYNCINFOBATTLEPASSCMD_PARAM_FIELD.index = 1
SYNCINFOBATTLEPASSCMD_PARAM_FIELD.label = 1
SYNCINFOBATTLEPASSCMD_PARAM_FIELD.has_default_value = true
SYNCINFOBATTLEPASSCMD_PARAM_FIELD.default_value = 5
SYNCINFOBATTLEPASSCMD_PARAM_FIELD.enum_type = EBATTLEPASSPARAM
SYNCINFOBATTLEPASSCMD_PARAM_FIELD.type = 14
SYNCINFOBATTLEPASSCMD_PARAM_FIELD.cpp_type = 8
SYNCINFOBATTLEPASSCMD_LEVEL_FIELD.name = "level"
SYNCINFOBATTLEPASSCMD_LEVEL_FIELD.full_name = ".Cmd.SyncInfoBattlePassCmd.level"
SYNCINFOBATTLEPASSCMD_LEVEL_FIELD.number = 3
SYNCINFOBATTLEPASSCMD_LEVEL_FIELD.index = 2
SYNCINFOBATTLEPASSCMD_LEVEL_FIELD.label = 1
SYNCINFOBATTLEPASSCMD_LEVEL_FIELD.has_default_value = true
SYNCINFOBATTLEPASSCMD_LEVEL_FIELD.default_value = 0
SYNCINFOBATTLEPASSCMD_LEVEL_FIELD.type = 13
SYNCINFOBATTLEPASSCMD_LEVEL_FIELD.cpp_type = 3
SYNCINFOBATTLEPASSCMD_PRO_LEVEL_FIELD.name = "pro_level"
SYNCINFOBATTLEPASSCMD_PRO_LEVEL_FIELD.full_name = ".Cmd.SyncInfoBattlePassCmd.pro_level"
SYNCINFOBATTLEPASSCMD_PRO_LEVEL_FIELD.number = 4
SYNCINFOBATTLEPASSCMD_PRO_LEVEL_FIELD.index = 3
SYNCINFOBATTLEPASSCMD_PRO_LEVEL_FIELD.label = 1
SYNCINFOBATTLEPASSCMD_PRO_LEVEL_FIELD.has_default_value = true
SYNCINFOBATTLEPASSCMD_PRO_LEVEL_FIELD.default_value = 0
SYNCINFOBATTLEPASSCMD_PRO_LEVEL_FIELD.type = 13
SYNCINFOBATTLEPASSCMD_PRO_LEVEL_FIELD.cpp_type = 3
SYNCINFOBATTLEPASSCMD_REWARDLVS_FIELD.name = "rewardlvs"
SYNCINFOBATTLEPASSCMD_REWARDLVS_FIELD.full_name = ".Cmd.SyncInfoBattlePassCmd.rewardlvs"
SYNCINFOBATTLEPASSCMD_REWARDLVS_FIELD.number = 5
SYNCINFOBATTLEPASSCMD_REWARDLVS_FIELD.index = 4
SYNCINFOBATTLEPASSCMD_REWARDLVS_FIELD.label = 3
SYNCINFOBATTLEPASSCMD_REWARDLVS_FIELD.has_default_value = false
SYNCINFOBATTLEPASSCMD_REWARDLVS_FIELD.default_value = {}
SYNCINFOBATTLEPASSCMD_REWARDLVS_FIELD.type = 13
SYNCINFOBATTLEPASSCMD_REWARDLVS_FIELD.cpp_type = 3
SYNCINFOBATTLEPASSCMD_REWARD_PROLVS_FIELD.name = "reward_prolvs"
SYNCINFOBATTLEPASSCMD_REWARD_PROLVS_FIELD.full_name = ".Cmd.SyncInfoBattlePassCmd.reward_prolvs"
SYNCINFOBATTLEPASSCMD_REWARD_PROLVS_FIELD.number = 6
SYNCINFOBATTLEPASSCMD_REWARD_PROLVS_FIELD.index = 5
SYNCINFOBATTLEPASSCMD_REWARD_PROLVS_FIELD.label = 3
SYNCINFOBATTLEPASSCMD_REWARD_PROLVS_FIELD.has_default_value = false
SYNCINFOBATTLEPASSCMD_REWARD_PROLVS_FIELD.default_value = {}
SYNCINFOBATTLEPASSCMD_REWARD_PROLVS_FIELD.type = 13
SYNCINFOBATTLEPASSCMD_REWARD_PROLVS_FIELD.cpp_type = 3
SYNCINFOBATTLEPASSCMD_EXP_FIELD.name = "exp"
SYNCINFOBATTLEPASSCMD_EXP_FIELD.full_name = ".Cmd.SyncInfoBattlePassCmd.exp"
SYNCINFOBATTLEPASSCMD_EXP_FIELD.number = 7
SYNCINFOBATTLEPASSCMD_EXP_FIELD.index = 6
SYNCINFOBATTLEPASSCMD_EXP_FIELD.label = 1
SYNCINFOBATTLEPASSCMD_EXP_FIELD.has_default_value = true
SYNCINFOBATTLEPASSCMD_EXP_FIELD.default_value = 0
SYNCINFOBATTLEPASSCMD_EXP_FIELD.type = 13
SYNCINFOBATTLEPASSCMD_EXP_FIELD.cpp_type = 3
SYNCINFOBATTLEPASSCMD_SU_LEVEL_FIELD.name = "su_level"
SYNCINFOBATTLEPASSCMD_SU_LEVEL_FIELD.full_name = ".Cmd.SyncInfoBattlePassCmd.su_level"
SYNCINFOBATTLEPASSCMD_SU_LEVEL_FIELD.number = 8
SYNCINFOBATTLEPASSCMD_SU_LEVEL_FIELD.index = 7
SYNCINFOBATTLEPASSCMD_SU_LEVEL_FIELD.label = 1
SYNCINFOBATTLEPASSCMD_SU_LEVEL_FIELD.has_default_value = false
SYNCINFOBATTLEPASSCMD_SU_LEVEL_FIELD.default_value = 0
SYNCINFOBATTLEPASSCMD_SU_LEVEL_FIELD.type = 13
SYNCINFOBATTLEPASSCMD_SU_LEVEL_FIELD.cpp_type = 3
SYNCINFOBATTLEPASSCMD_REWARD_SULVS_FIELD.name = "reward_sulvs"
SYNCINFOBATTLEPASSCMD_REWARD_SULVS_FIELD.full_name = ".Cmd.SyncInfoBattlePassCmd.reward_sulvs"
SYNCINFOBATTLEPASSCMD_REWARD_SULVS_FIELD.number = 9
SYNCINFOBATTLEPASSCMD_REWARD_SULVS_FIELD.index = 8
SYNCINFOBATTLEPASSCMD_REWARD_SULVS_FIELD.label = 3
SYNCINFOBATTLEPASSCMD_REWARD_SULVS_FIELD.has_default_value = false
SYNCINFOBATTLEPASSCMD_REWARD_SULVS_FIELD.default_value = {}
SYNCINFOBATTLEPASSCMD_REWARD_SULVS_FIELD.type = 13
SYNCINFOBATTLEPASSCMD_REWARD_SULVS_FIELD.cpp_type = 3
SYNCINFOBATTLEPASSCMD_VERSION_FIELD.name = "version"
SYNCINFOBATTLEPASSCMD_VERSION_FIELD.full_name = ".Cmd.SyncInfoBattlePassCmd.version"
SYNCINFOBATTLEPASSCMD_VERSION_FIELD.number = 10
SYNCINFOBATTLEPASSCMD_VERSION_FIELD.index = 9
SYNCINFOBATTLEPASSCMD_VERSION_FIELD.label = 1
SYNCINFOBATTLEPASSCMD_VERSION_FIELD.has_default_value = true
SYNCINFOBATTLEPASSCMD_VERSION_FIELD.default_value = 0
SYNCINFOBATTLEPASSCMD_VERSION_FIELD.type = 13
SYNCINFOBATTLEPASSCMD_VERSION_FIELD.cpp_type = 3
SYNCINFOBATTLEPASSCMD.name = "SyncInfoBattlePassCmd"
SYNCINFOBATTLEPASSCMD.full_name = ".Cmd.SyncInfoBattlePassCmd"
SYNCINFOBATTLEPASSCMD.nested_types = {}
SYNCINFOBATTLEPASSCMD.enum_types = {}
SYNCINFOBATTLEPASSCMD.fields = {
  SYNCINFOBATTLEPASSCMD_CMD_FIELD,
  SYNCINFOBATTLEPASSCMD_PARAM_FIELD,
  SYNCINFOBATTLEPASSCMD_LEVEL_FIELD,
  SYNCINFOBATTLEPASSCMD_PRO_LEVEL_FIELD,
  SYNCINFOBATTLEPASSCMD_REWARDLVS_FIELD,
  SYNCINFOBATTLEPASSCMD_REWARD_PROLVS_FIELD,
  SYNCINFOBATTLEPASSCMD_EXP_FIELD,
  SYNCINFOBATTLEPASSCMD_SU_LEVEL_FIELD,
  SYNCINFOBATTLEPASSCMD_REWARD_SULVS_FIELD,
  SYNCINFOBATTLEPASSCMD_VERSION_FIELD
}
SYNCINFOBATTLEPASSCMD.is_extendable = false
SYNCINFOBATTLEPASSCMD.extensions = {}
BATTLEPASSQUESTINFO_ID_FIELD.name = "id"
BATTLEPASSQUESTINFO_ID_FIELD.full_name = ".Cmd.BattlePassQuestInfo.id"
BATTLEPASSQUESTINFO_ID_FIELD.number = 1
BATTLEPASSQUESTINFO_ID_FIELD.index = 0
BATTLEPASSQUESTINFO_ID_FIELD.label = 1
BATTLEPASSQUESTINFO_ID_FIELD.has_default_value = false
BATTLEPASSQUESTINFO_ID_FIELD.default_value = 0
BATTLEPASSQUESTINFO_ID_FIELD.type = 13
BATTLEPASSQUESTINFO_ID_FIELD.cpp_type = 3
BATTLEPASSQUESTINFO_PROCESS_FIELD.name = "process"
BATTLEPASSQUESTINFO_PROCESS_FIELD.full_name = ".Cmd.BattlePassQuestInfo.process"
BATTLEPASSQUESTINFO_PROCESS_FIELD.number = 2
BATTLEPASSQUESTINFO_PROCESS_FIELD.index = 1
BATTLEPASSQUESTINFO_PROCESS_FIELD.label = 1
BATTLEPASSQUESTINFO_PROCESS_FIELD.has_default_value = false
BATTLEPASSQUESTINFO_PROCESS_FIELD.default_value = 0
BATTLEPASSQUESTINFO_PROCESS_FIELD.type = 13
BATTLEPASSQUESTINFO_PROCESS_FIELD.cpp_type = 3
BATTLEPASSQUESTINFO.name = "BattlePassQuestInfo"
BATTLEPASSQUESTINFO.full_name = ".Cmd.BattlePassQuestInfo"
BATTLEPASSQUESTINFO.nested_types = {}
BATTLEPASSQUESTINFO.enum_types = {}
BATTLEPASSQUESTINFO.fields = {
  BATTLEPASSQUESTINFO_ID_FIELD,
  BATTLEPASSQUESTINFO_PROCESS_FIELD
}
BATTLEPASSQUESTINFO.is_extendable = false
BATTLEPASSQUESTINFO.extensions = {}
BATTLEPASSQUESTINFOCMD_CMD_FIELD.name = "cmd"
BATTLEPASSQUESTINFOCMD_CMD_FIELD.full_name = ".Cmd.BattlePassQuestInfoCmd.cmd"
BATTLEPASSQUESTINFOCMD_CMD_FIELD.number = 1
BATTLEPASSQUESTINFOCMD_CMD_FIELD.index = 0
BATTLEPASSQUESTINFOCMD_CMD_FIELD.label = 1
BATTLEPASSQUESTINFOCMD_CMD_FIELD.has_default_value = true
BATTLEPASSQUESTINFOCMD_CMD_FIELD.default_value = 222
BATTLEPASSQUESTINFOCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
BATTLEPASSQUESTINFOCMD_CMD_FIELD.type = 14
BATTLEPASSQUESTINFOCMD_CMD_FIELD.cpp_type = 8
BATTLEPASSQUESTINFOCMD_PARAM_FIELD.name = "param"
BATTLEPASSQUESTINFOCMD_PARAM_FIELD.full_name = ".Cmd.BattlePassQuestInfoCmd.param"
BATTLEPASSQUESTINFOCMD_PARAM_FIELD.number = 2
BATTLEPASSQUESTINFOCMD_PARAM_FIELD.index = 1
BATTLEPASSQUESTINFOCMD_PARAM_FIELD.label = 1
BATTLEPASSQUESTINFOCMD_PARAM_FIELD.has_default_value = true
BATTLEPASSQUESTINFOCMD_PARAM_FIELD.default_value = 6
BATTLEPASSQUESTINFOCMD_PARAM_FIELD.enum_type = EBATTLEPASSPARAM
BATTLEPASSQUESTINFOCMD_PARAM_FIELD.type = 14
BATTLEPASSQUESTINFOCMD_PARAM_FIELD.cpp_type = 8
BATTLEPASSQUESTINFOCMD_QUESTS_FIELD.name = "quests"
BATTLEPASSQUESTINFOCMD_QUESTS_FIELD.full_name = ".Cmd.BattlePassQuestInfoCmd.quests"
BATTLEPASSQUESTINFOCMD_QUESTS_FIELD.number = 3
BATTLEPASSQUESTINFOCMD_QUESTS_FIELD.index = 2
BATTLEPASSQUESTINFOCMD_QUESTS_FIELD.label = 3
BATTLEPASSQUESTINFOCMD_QUESTS_FIELD.has_default_value = false
BATTLEPASSQUESTINFOCMD_QUESTS_FIELD.default_value = {}
BATTLEPASSQUESTINFOCMD_QUESTS_FIELD.message_type = BATTLEPASSQUESTINFO
BATTLEPASSQUESTINFOCMD_QUESTS_FIELD.type = 11
BATTLEPASSQUESTINFOCMD_QUESTS_FIELD.cpp_type = 10
BATTLEPASSQUESTINFOCMD.name = "BattlePassQuestInfoCmd"
BATTLEPASSQUESTINFOCMD.full_name = ".Cmd.BattlePassQuestInfoCmd"
BATTLEPASSQUESTINFOCMD.nested_types = {}
BATTLEPASSQUESTINFOCMD.enum_types = {}
BATTLEPASSQUESTINFOCMD.fields = {
  BATTLEPASSQUESTINFOCMD_CMD_FIELD,
  BATTLEPASSQUESTINFOCMD_PARAM_FIELD,
  BATTLEPASSQUESTINFOCMD_QUESTS_FIELD
}
BATTLEPASSQUESTINFOCMD.is_extendable = false
BATTLEPASSQUESTINFOCMD.extensions = {}
AdvanceBattlePassCmd = protobuf.Message(ADVANCEBATTLEPASSCMD)
BATTLEPASS_BUY_ADVANCE = 4
BATTLEPASS_BUY_LEVEL = 3
BATTLEPASS_GET_REWAD = 1
BATTLEPASS_QUEST_INFO = 6
BATTLEPASS_SYNC_INFO = 5
BATTLEPASS_UPDATE_REWARD = 2
BattlePassQuestInfo = protobuf.Message(BATTLEPASSQUESTINFO)
BattlePassQuestInfoCmd = protobuf.Message(BATTLEPASSQUESTINFOCMD)
BuyLevelBattlePassCmd = protobuf.Message(BUYLEVELBATTLEPASSCMD)
GetRewardBattlePassCmd = protobuf.Message(GETREWARDBATTLEPASSCMD)
SyncInfoBattlePassCmd = protobuf.Message(SYNCINFOBATTLEPASSCMD)
UpdateRewardBattlePassCmd = protobuf.Message(UPDATEREWARDBATTLEPASSCMD)
