local protobuf = protobuf
autoImport("xCmd_pb")
local xCmd_pb = xCmd_pb
autoImport("ProtoCommon_pb")
local ProtoCommon_pb = ProtoCommon_pb
module("MessCCmd_pb")
MESSCPARAM = protobuf.EnumDescriptor()
MESSCPARAM_MESSCPARAM_CHOOSE_NEW_PROFESSION_ENUM = protobuf.EnumValueDescriptor()
MESSCPARAM_MESSCPARAM_INVITER_SEND_LOVE_CONFESSION_ENUM = protobuf.EnumValueDescriptor()
MESSCPARAM_MESSCPARAM_INVITEE_RECEIVE_LOVE_CONFESSION_ENUM = protobuf.EnumValueDescriptor()
MESSCPARAM_MESSCPARAM_INVITEE_PROCESS_LOVE_CONFESSION_ENUM = protobuf.EnumValueDescriptor()
MESSCPARAM_MESSCPARAM_INVITER_RECEIVE_LOVE_CONFESSION_ENUM = protobuf.EnumValueDescriptor()
MESSCPARAM_MESSCPARAM_FINGER_GUESS_LOVE_CONFESSION_ENUM = protobuf.EnumValueDescriptor()
MESSCPARAM_MESSCPARAM_FINGER_LOSE_LOVE_CONFESSION_ENUM = protobuf.EnumValueDescriptor()
MESSCPARAM_MESSCPARAM_INVITER_RESULT_LOVE_CONFESSION_ENUM = protobuf.EnumValueDescriptor()
MESSCPARAM_SYNC_MAPSTEP_FOREVER_REWARD_INFO_ENUM = protobuf.EnumValueDescriptor()
MESSCPARAM_BALANCE_MODE_CHOOSE_ENUM = protobuf.EnumValueDescriptor()
MESSCPARAM_SET_PIPPI_STATE_ENUM = protobuf.EnumValueDescriptor()
MESSCPARAM_SYNC_DESTINY_GRAPH_ENUM = protobuf.EnumValueDescriptor()
MESSCPARAM_LIGHTEN_DESTINY_GRAPH_ENUM = protobuf.EnumValueDescriptor()
MESSCPARAM_ASTRAL_REWARD_ENUM = protobuf.EnumValueDescriptor()
MESSCPARAM_PURIFY_PRODUCTS_MATERIALS_ENUM = protobuf.EnumValueDescriptor()
MESSCPARAM_PURIFY_PRODUCTS_REFINE_ENUM = protobuf.EnumValueDescriptor()
MESSCPARAM_ASTRAL_SEASON_ENUM = protobuf.EnumValueDescriptor()
FINGERGUESSITEM = protobuf.EnumDescriptor()
FINGERGUESSITEM_FINGER_GUESS_MIN_ENUM = protobuf.EnumValueDescriptor()
FINGERGUESSITEM_FINGER_GUESS_ROCK_ENUM = protobuf.EnumValueDescriptor()
FINGERGUESSITEM_FINGER_GUESS_SCISSORS_ENUM = protobuf.EnumValueDescriptor()
FINGERGUESSITEM_FINGER_GUESS_PAPER_ENUM = protobuf.EnumValueDescriptor()
FINGERGUESSITEM_FINGER_GUESS_RANDOM_ENUM = protobuf.EnumValueDescriptor()
EPIPPISTATE = protobuf.EnumDescriptor()
EPIPPISTATE_EPIPPISTATE_LIVE_SHOW_ENUM = protobuf.EnumValueDescriptor()
EPIPPISTATE_EPIPPISTATE_LIVE_HIDE_ENUM = protobuf.EnumValueDescriptor()
EPIPPISTATE_EPIPPISTATE_DIE_SHOW_ENUM = protobuf.EnumValueDescriptor()
EPIPPISTATE_EPIPPISTATE_DIE_HIDE_ENUM = protobuf.EnumValueDescriptor()
EGRAPHPOINTSTATE = protobuf.EnumDescriptor()
EGRAPHPOINTSTATE_EGRAPH_POINT_STATE_LOCKED_ENUM = protobuf.EnumValueDescriptor()
EGRAPHPOINTSTATE_EGRAPH_POINT_STATE_UNLOCKED_ENUM = protobuf.EnumValueDescriptor()
EGRAPHPOINTSTATE_EGRAPH_POINT_STATE_LIGHT_ENUM = protobuf.EnumValueDescriptor()
CHOOSENEWPROFESSIONMESSCCMD = protobuf.Descriptor()
CHOOSENEWPROFESSIONMESSCCMD_CMD_FIELD = protobuf.FieldDescriptor()
CHOOSENEWPROFESSIONMESSCCMD_PARAM_FIELD = protobuf.FieldDescriptor()
CHOOSENEWPROFESSIONMESSCCMD_BORNPROFESSION_FIELD = protobuf.FieldDescriptor()
CHOOSENEWPROFESSIONMESSCCMD_CHOOSEPROFESSION_FIELD = protobuf.FieldDescriptor()
INVITERSENDLOVECONFESSIONMESSCCMD = protobuf.Descriptor()
INVITERSENDLOVECONFESSIONMESSCCMD_CMD_FIELD = protobuf.FieldDescriptor()
INVITERSENDLOVECONFESSIONMESSCCMD_PARAM_FIELD = protobuf.FieldDescriptor()
INVITERSENDLOVECONFESSIONMESSCCMD_INVITEE_FIELD = protobuf.FieldDescriptor()
INVITERSENDLOVECONFESSIONMESSCCMD_INVITERNAME_FIELD = protobuf.FieldDescriptor()
INVITEERECEIVELOVECONFESSIONMESSCCMD = protobuf.Descriptor()
INVITEERECEIVELOVECONFESSIONMESSCCMD_CMD_FIELD = protobuf.FieldDescriptor()
INVITEERECEIVELOVECONFESSIONMESSCCMD_PARAM_FIELD = protobuf.FieldDescriptor()
INVITEERECEIVELOVECONFESSIONMESSCCMD_INVITERNAME_FIELD = protobuf.FieldDescriptor()
INVITEERECEIVELOVECONFESSIONMESSCCMD_INVITER_FIELD = protobuf.FieldDescriptor()
INVITEEPROCESSLOVECONFESSIONMESSCCMD = protobuf.Descriptor()
INVITEEPROCESSLOVECONFESSIONMESSCCMD_CMD_FIELD = protobuf.FieldDescriptor()
INVITEEPROCESSLOVECONFESSIONMESSCCMD_PARAM_FIELD = protobuf.FieldDescriptor()
INVITEEPROCESSLOVECONFESSIONMESSCCMD_ACCEPT_FIELD = protobuf.FieldDescriptor()
INVITEEPROCESSLOVECONFESSIONMESSCCMD_INVITER_FIELD = protobuf.FieldDescriptor()
INVITERRECEIVECONFESSIONMESSCCMD = protobuf.Descriptor()
INVITERRECEIVECONFESSIONMESSCCMD_CMD_FIELD = protobuf.FieldDescriptor()
INVITERRECEIVECONFESSIONMESSCCMD_PARAM_FIELD = protobuf.FieldDescriptor()
INVITERRECEIVECONFESSIONMESSCCMD_ACCEPT_FIELD = protobuf.FieldDescriptor()
INVITERRECEIVECONFESSIONMESSCCMD_INVITER_FIELD = protobuf.FieldDescriptor()
FINGERGUESSLOVECONFESSIONMESSCCMD = protobuf.Descriptor()
FINGERGUESSLOVECONFESSIONMESSCCMD_CMD_FIELD = protobuf.FieldDescriptor()
FINGERGUESSLOVECONFESSIONMESSCCMD_PARAM_FIELD = protobuf.FieldDescriptor()
FINGERGUESSLOVECONFESSIONMESSCCMD_ITEM_FIELD = protobuf.FieldDescriptor()
FINGERGUESSLOVECONFESSIONMESSCCMD_INVITER_FIELD = protobuf.FieldDescriptor()
FINGERLOSELOVECONFESSIONMESSCCMD = protobuf.Descriptor()
FINGERLOSELOVECONFESSIONMESSCCMD_CMD_FIELD = protobuf.FieldDescriptor()
FINGERLOSELOVECONFESSIONMESSCCMD_PARAM_FIELD = protobuf.FieldDescriptor()
FINGERLOSELOVECONFESSIONMESSCCMD_INVITER_FIELD = protobuf.FieldDescriptor()
FINGERLOSELOVECONFESSIONMESSCCMD_WINNERFINGER_FIELD = protobuf.FieldDescriptor()
FINGERLOSELOVECONFESSIONMESSCCMD_LOSERFINGER_FIELD = protobuf.FieldDescriptor()
FINGERLOSELOVECONFESSIONMESSCCMD_WINNER_FIELD = protobuf.FieldDescriptor()
INVITERRESULTLOVECONFESSIONMESSCCMD = protobuf.Descriptor()
INVITERRESULTLOVECONFESSIONMESSCCMD_CMD_FIELD = protobuf.FieldDescriptor()
INVITERRESULTLOVECONFESSIONMESSCCMD_PARAM_FIELD = protobuf.FieldDescriptor()
INVITERRESULTLOVECONFESSIONMESSCCMD_SUCCESS_FIELD = protobuf.FieldDescriptor()
INVITERRESULTLOVECONFESSIONMESSCCMD_INVITEE_FIELD = protobuf.FieldDescriptor()
MAPSTEPFOREVERREWARDITEM = protobuf.Descriptor()
MAPSTEPFOREVERREWARDITEM_MAPSTEP_QUESTID_FIELD = protobuf.FieldDescriptor()
MAPSTEPFOREVERREWARDITEM_MAPSTEP_GROUPID_FIELD = protobuf.FieldDescriptor()
SYNCMAPSTEPFOREVERREWARDINFO = protobuf.Descriptor()
SYNCMAPSTEPFOREVERREWARDINFO_CMD_FIELD = protobuf.FieldDescriptor()
SYNCMAPSTEPFOREVERREWARDINFO_PARAM_FIELD = protobuf.FieldDescriptor()
SYNCMAPSTEPFOREVERREWARDINFO_INFOS_FIELD = protobuf.FieldDescriptor()
BALANCEMODECHOOSEMESSCCMD = protobuf.Descriptor()
BALANCEMODECHOOSEMESSCCMD_CMD_FIELD = protobuf.FieldDescriptor()
BALANCEMODECHOOSEMESSCCMD_PARAM_FIELD = protobuf.FieldDescriptor()
BALANCEMODECHOOSEMESSCCMD_EXTRACTION_ATK_ID_FIELD = protobuf.FieldDescriptor()
BALANCEMODECHOOSEMESSCCMD_EXTRACTION_DEF_ID_FIELD = protobuf.FieldDescriptor()
BALANCEMODECHOOSEMESSCCMD_PERSONAL_ARTIFACT_ID_FIELD = protobuf.FieldDescriptor()
SETPIPPISTATEMESSCCMD = protobuf.Descriptor()
SETPIPPISTATEMESSCCMD_CMD_FIELD = protobuf.FieldDescriptor()
SETPIPPISTATEMESSCCMD_PARAM_FIELD = protobuf.FieldDescriptor()
SETPIPPISTATEMESSCCMD_SUMMON_FIELD = protobuf.FieldDescriptor()
SETPIPPISTATEMESSCCMD_TIME_FIELD = protobuf.FieldDescriptor()
SETPIPPISTATEMESSCCMD_STATE_FIELD = protobuf.FieldDescriptor()
GRAPHPOINTINFO = protobuf.Descriptor()
GRAPHPOINTINFO_POINT_FIELD = protobuf.FieldDescriptor()
GRAPHPOINTINFO_STATE_FIELD = protobuf.FieldDescriptor()
DESTINYGRAPHINFO = protobuf.Descriptor()
DESTINYGRAPHINFO_SEASON_FIELD = protobuf.FieldDescriptor()
DESTINYGRAPHINFO_POINTINFOS_FIELD = protobuf.FieldDescriptor()
SYNCDESTINYGRAPHMESSCCMD = protobuf.Descriptor()
SYNCDESTINYGRAPHMESSCCMD_CMD_FIELD = protobuf.FieldDescriptor()
SYNCDESTINYGRAPHMESSCCMD_PARAM_FIELD = protobuf.FieldDescriptor()
SYNCDESTINYGRAPHMESSCCMD_GRAPHINFOS_FIELD = protobuf.FieldDescriptor()
SYNCDESTINYGRAPHMESSCCMD_CURSEASON_FIELD = protobuf.FieldDescriptor()
LIGHTENDESTINYGRAPHMESSCCMD = protobuf.Descriptor()
LIGHTENDESTINYGRAPHMESSCCMD_CMD_FIELD = protobuf.FieldDescriptor()
LIGHTENDESTINYGRAPHMESSCCMD_PARAM_FIELD = protobuf.FieldDescriptor()
LIGHTENDESTINYGRAPHMESSCCMD_SEASON_FIELD = protobuf.FieldDescriptor()
LIGHTENDESTINYGRAPHMESSCCMD_POINT_FIELD = protobuf.FieldDescriptor()
ASTRALREWARDMESSCCMD = protobuf.Descriptor()
ASTRALREWARDMESSCCMD_CMD_FIELD = protobuf.FieldDescriptor()
ASTRALREWARDMESSCCMD_PARAM_FIELD = protobuf.FieldDescriptor()
ASTRALREWARDMESSCCMD_SEASON_FIELD = protobuf.FieldDescriptor()
ASTRALREWARDMESSCCMD_PASS_NUM_FIELD = protobuf.FieldDescriptor()
PURIFYMATERIALS = protobuf.Descriptor()
PURIFYMATERIALS_ITEMID_FIELD = protobuf.FieldDescriptor()
PURIFYMATERIALS_NUM_FIELD = protobuf.FieldDescriptor()
PURIFYTIMES = protobuf.Descriptor()
PURIFYTIMES_TYPE_FIELD = protobuf.FieldDescriptor()
PURIFYTIMES_TOTALTIMES_FIELD = protobuf.FieldDescriptor()
PURIFYTIMES_LEFTTIMES_FIELD = protobuf.FieldDescriptor()
PURIFYPRODUCTS = protobuf.Descriptor()
PURIFYPRODUCTS_PRODUCTID_FIELD = protobuf.FieldDescriptor()
PURIFYPRODUCTS_MATERIALS_FIELD = protobuf.FieldDescriptor()
PURIFYPRODUCTS_TIMES_FIELD = protobuf.FieldDescriptor()
PURIFYPRODUCTS_NEWMARK_FIELD = protobuf.FieldDescriptor()
PURIFYPRODUCTS_CLOSE_FIELD = protobuf.FieldDescriptor()
PURIFYPRODUCTS_CONFIRM_FIELD = protobuf.FieldDescriptor()
PURIFYPRODUCTSMATERIALSMESSCCMD = protobuf.Descriptor()
PURIFYPRODUCTSMATERIALSMESSCCMD_CMD_FIELD = protobuf.FieldDescriptor()
PURIFYPRODUCTSMATERIALSMESSCCMD_PARAM_FIELD = protobuf.FieldDescriptor()
PURIFYPRODUCTSMATERIALSMESSCCMD_MATERIALS_FIELD = protobuf.FieldDescriptor()
PURIFYPRODUCTSREFINEMESSCCMD = protobuf.Descriptor()
PURIFYPRODUCTSREFINEMESSCCMD_CMD_FIELD = protobuf.FieldDescriptor()
PURIFYPRODUCTSREFINEMESSCCMD_PARAM_FIELD = protobuf.FieldDescriptor()
PURIFYPRODUCTSREFINEMESSCCMD_PRODUCTID_FIELD = protobuf.FieldDescriptor()
PURIFYPRODUCTSREFINEMESSCCMD_TIMES_FIELD = protobuf.FieldDescriptor()
ASTRALSYNCSEASONINFOMESSCCMD = protobuf.Descriptor()
ASTRALSYNCSEASONINFOMESSCCMD_CMD_FIELD = protobuf.FieldDescriptor()
ASTRALSYNCSEASONINFOMESSCCMD_PARAM_FIELD = protobuf.FieldDescriptor()
ASTRALSYNCSEASONINFOMESSCCMD_SEASON_FIELD = protobuf.FieldDescriptor()
PURIFYPRODUCTSMATERIALSDATA = protobuf.Descriptor()
PURIFYPRODUCTSMATERIALSDATA_TRADEGROUPID_FIELD = protobuf.FieldDescriptor()
PURIFYPRODUCTSMATERIALSDATA_MATERIALS_FIELD = protobuf.FieldDescriptor()
PURIFYPRODUCTSSAVEDATA = protobuf.Descriptor()
PURIFYPRODUCTSSAVEDATA_CUR_DATA_FIELD = protobuf.FieldDescriptor()
PURIFYPRODUCTSSAVEDATA_LAST_DATA_FIELD = protobuf.FieldDescriptor()
PURIFYPRODUCTSSAVEDATA_WEEK_REFRESH_TIME_FIELD = protobuf.FieldDescriptor()
PURIFYPRODUCTSSAVEDATA_DAY_REFRESH_TIME_FIELD = protobuf.FieldDescriptor()
MESSCPARAM_MESSCPARAM_CHOOSE_NEW_PROFESSION_ENUM.name = "MESSCPARAM_CHOOSE_NEW_PROFESSION"
MESSCPARAM_MESSCPARAM_CHOOSE_NEW_PROFESSION_ENUM.index = 0
MESSCPARAM_MESSCPARAM_CHOOSE_NEW_PROFESSION_ENUM.number = 1
MESSCPARAM_MESSCPARAM_INVITER_SEND_LOVE_CONFESSION_ENUM.name = "MESSCPARAM_INVITER_SEND_LOVE_CONFESSION"
MESSCPARAM_MESSCPARAM_INVITER_SEND_LOVE_CONFESSION_ENUM.index = 1
MESSCPARAM_MESSCPARAM_INVITER_SEND_LOVE_CONFESSION_ENUM.number = 2
MESSCPARAM_MESSCPARAM_INVITEE_RECEIVE_LOVE_CONFESSION_ENUM.name = "MESSCPARAM_INVITEE_RECEIVE_LOVE_CONFESSION"
MESSCPARAM_MESSCPARAM_INVITEE_RECEIVE_LOVE_CONFESSION_ENUM.index = 2
MESSCPARAM_MESSCPARAM_INVITEE_RECEIVE_LOVE_CONFESSION_ENUM.number = 3
MESSCPARAM_MESSCPARAM_INVITEE_PROCESS_LOVE_CONFESSION_ENUM.name = "MESSCPARAM_INVITEE_PROCESS_LOVE_CONFESSION"
MESSCPARAM_MESSCPARAM_INVITEE_PROCESS_LOVE_CONFESSION_ENUM.index = 3
MESSCPARAM_MESSCPARAM_INVITEE_PROCESS_LOVE_CONFESSION_ENUM.number = 4
MESSCPARAM_MESSCPARAM_INVITER_RECEIVE_LOVE_CONFESSION_ENUM.name = "MESSCPARAM_INVITER_RECEIVE_LOVE_CONFESSION"
MESSCPARAM_MESSCPARAM_INVITER_RECEIVE_LOVE_CONFESSION_ENUM.index = 4
MESSCPARAM_MESSCPARAM_INVITER_RECEIVE_LOVE_CONFESSION_ENUM.number = 5
MESSCPARAM_MESSCPARAM_FINGER_GUESS_LOVE_CONFESSION_ENUM.name = "MESSCPARAM_FINGER_GUESS_LOVE_CONFESSION"
MESSCPARAM_MESSCPARAM_FINGER_GUESS_LOVE_CONFESSION_ENUM.index = 5
MESSCPARAM_MESSCPARAM_FINGER_GUESS_LOVE_CONFESSION_ENUM.number = 6
MESSCPARAM_MESSCPARAM_FINGER_LOSE_LOVE_CONFESSION_ENUM.name = "MESSCPARAM_FINGER_LOSE_LOVE_CONFESSION"
MESSCPARAM_MESSCPARAM_FINGER_LOSE_LOVE_CONFESSION_ENUM.index = 6
MESSCPARAM_MESSCPARAM_FINGER_LOSE_LOVE_CONFESSION_ENUM.number = 7
MESSCPARAM_MESSCPARAM_INVITER_RESULT_LOVE_CONFESSION_ENUM.name = "MESSCPARAM_INVITER_RESULT_LOVE_CONFESSION"
MESSCPARAM_MESSCPARAM_INVITER_RESULT_LOVE_CONFESSION_ENUM.index = 7
MESSCPARAM_MESSCPARAM_INVITER_RESULT_LOVE_CONFESSION_ENUM.number = 8
MESSCPARAM_SYNC_MAPSTEP_FOREVER_REWARD_INFO_ENUM.name = "SYNC_MAPSTEP_FOREVER_REWARD_INFO"
MESSCPARAM_SYNC_MAPSTEP_FOREVER_REWARD_INFO_ENUM.index = 8
MESSCPARAM_SYNC_MAPSTEP_FOREVER_REWARD_INFO_ENUM.number = 9
MESSCPARAM_BALANCE_MODE_CHOOSE_ENUM.name = "BALANCE_MODE_CHOOSE"
MESSCPARAM_BALANCE_MODE_CHOOSE_ENUM.index = 9
MESSCPARAM_BALANCE_MODE_CHOOSE_ENUM.number = 10
MESSCPARAM_SET_PIPPI_STATE_ENUM.name = "SET_PIPPI_STATE"
MESSCPARAM_SET_PIPPI_STATE_ENUM.index = 10
MESSCPARAM_SET_PIPPI_STATE_ENUM.number = 11
MESSCPARAM_SYNC_DESTINY_GRAPH_ENUM.name = "SYNC_DESTINY_GRAPH"
MESSCPARAM_SYNC_DESTINY_GRAPH_ENUM.index = 11
MESSCPARAM_SYNC_DESTINY_GRAPH_ENUM.number = 12
MESSCPARAM_LIGHTEN_DESTINY_GRAPH_ENUM.name = "LIGHTEN_DESTINY_GRAPH"
MESSCPARAM_LIGHTEN_DESTINY_GRAPH_ENUM.index = 12
MESSCPARAM_LIGHTEN_DESTINY_GRAPH_ENUM.number = 13
MESSCPARAM_ASTRAL_REWARD_ENUM.name = "ASTRAL_REWARD"
MESSCPARAM_ASTRAL_REWARD_ENUM.index = 13
MESSCPARAM_ASTRAL_REWARD_ENUM.number = 14
MESSCPARAM_PURIFY_PRODUCTS_MATERIALS_ENUM.name = "PURIFY_PRODUCTS_MATERIALS"
MESSCPARAM_PURIFY_PRODUCTS_MATERIALS_ENUM.index = 14
MESSCPARAM_PURIFY_PRODUCTS_MATERIALS_ENUM.number = 15
MESSCPARAM_PURIFY_PRODUCTS_REFINE_ENUM.name = "PURIFY_PRODUCTS_REFINE"
MESSCPARAM_PURIFY_PRODUCTS_REFINE_ENUM.index = 15
MESSCPARAM_PURIFY_PRODUCTS_REFINE_ENUM.number = 16
MESSCPARAM_ASTRAL_SEASON_ENUM.name = "ASTRAL_SEASON"
MESSCPARAM_ASTRAL_SEASON_ENUM.index = 16
MESSCPARAM_ASTRAL_SEASON_ENUM.number = 17
MESSCPARAM.name = "MessCParam"
MESSCPARAM.full_name = ".Cmd.MessCParam"
MESSCPARAM.values = {
  MESSCPARAM_MESSCPARAM_CHOOSE_NEW_PROFESSION_ENUM,
  MESSCPARAM_MESSCPARAM_INVITER_SEND_LOVE_CONFESSION_ENUM,
  MESSCPARAM_MESSCPARAM_INVITEE_RECEIVE_LOVE_CONFESSION_ENUM,
  MESSCPARAM_MESSCPARAM_INVITEE_PROCESS_LOVE_CONFESSION_ENUM,
  MESSCPARAM_MESSCPARAM_INVITER_RECEIVE_LOVE_CONFESSION_ENUM,
  MESSCPARAM_MESSCPARAM_FINGER_GUESS_LOVE_CONFESSION_ENUM,
  MESSCPARAM_MESSCPARAM_FINGER_LOSE_LOVE_CONFESSION_ENUM,
  MESSCPARAM_MESSCPARAM_INVITER_RESULT_LOVE_CONFESSION_ENUM,
  MESSCPARAM_SYNC_MAPSTEP_FOREVER_REWARD_INFO_ENUM,
  MESSCPARAM_BALANCE_MODE_CHOOSE_ENUM,
  MESSCPARAM_SET_PIPPI_STATE_ENUM,
  MESSCPARAM_SYNC_DESTINY_GRAPH_ENUM,
  MESSCPARAM_LIGHTEN_DESTINY_GRAPH_ENUM,
  MESSCPARAM_ASTRAL_REWARD_ENUM,
  MESSCPARAM_PURIFY_PRODUCTS_MATERIALS_ENUM,
  MESSCPARAM_PURIFY_PRODUCTS_REFINE_ENUM,
  MESSCPARAM_ASTRAL_SEASON_ENUM
}
FINGERGUESSITEM_FINGER_GUESS_MIN_ENUM.name = "FINGER_GUESS_MIN"
FINGERGUESSITEM_FINGER_GUESS_MIN_ENUM.index = 0
FINGERGUESSITEM_FINGER_GUESS_MIN_ENUM.number = 0
FINGERGUESSITEM_FINGER_GUESS_ROCK_ENUM.name = "FINGER_GUESS_ROCK"
FINGERGUESSITEM_FINGER_GUESS_ROCK_ENUM.index = 1
FINGERGUESSITEM_FINGER_GUESS_ROCK_ENUM.number = 1
FINGERGUESSITEM_FINGER_GUESS_SCISSORS_ENUM.name = "FINGER_GUESS_SCISSORS"
FINGERGUESSITEM_FINGER_GUESS_SCISSORS_ENUM.index = 2
FINGERGUESSITEM_FINGER_GUESS_SCISSORS_ENUM.number = 2
FINGERGUESSITEM_FINGER_GUESS_PAPER_ENUM.name = "FINGER_GUESS_PAPER"
FINGERGUESSITEM_FINGER_GUESS_PAPER_ENUM.index = 3
FINGERGUESSITEM_FINGER_GUESS_PAPER_ENUM.number = 3
FINGERGUESSITEM_FINGER_GUESS_RANDOM_ENUM.name = "FINGER_GUESS_RANDOM"
FINGERGUESSITEM_FINGER_GUESS_RANDOM_ENUM.index = 4
FINGERGUESSITEM_FINGER_GUESS_RANDOM_ENUM.number = 4
FINGERGUESSITEM.name = "FingerGuessItem"
FINGERGUESSITEM.full_name = ".Cmd.FingerGuessItem"
FINGERGUESSITEM.values = {
  FINGERGUESSITEM_FINGER_GUESS_MIN_ENUM,
  FINGERGUESSITEM_FINGER_GUESS_ROCK_ENUM,
  FINGERGUESSITEM_FINGER_GUESS_SCISSORS_ENUM,
  FINGERGUESSITEM_FINGER_GUESS_PAPER_ENUM,
  FINGERGUESSITEM_FINGER_GUESS_RANDOM_ENUM
}
EPIPPISTATE_EPIPPISTATE_LIVE_SHOW_ENUM.name = "EPIPPISTATE_LIVE_SHOW"
EPIPPISTATE_EPIPPISTATE_LIVE_SHOW_ENUM.index = 0
EPIPPISTATE_EPIPPISTATE_LIVE_SHOW_ENUM.number = 0
EPIPPISTATE_EPIPPISTATE_LIVE_HIDE_ENUM.name = "EPIPPISTATE_LIVE_HIDE"
EPIPPISTATE_EPIPPISTATE_LIVE_HIDE_ENUM.index = 1
EPIPPISTATE_EPIPPISTATE_LIVE_HIDE_ENUM.number = 1
EPIPPISTATE_EPIPPISTATE_DIE_SHOW_ENUM.name = "EPIPPISTATE_DIE_SHOW"
EPIPPISTATE_EPIPPISTATE_DIE_SHOW_ENUM.index = 2
EPIPPISTATE_EPIPPISTATE_DIE_SHOW_ENUM.number = 2
EPIPPISTATE_EPIPPISTATE_DIE_HIDE_ENUM.name = "EPIPPISTATE_DIE_HIDE"
EPIPPISTATE_EPIPPISTATE_DIE_HIDE_ENUM.index = 3
EPIPPISTATE_EPIPPISTATE_DIE_HIDE_ENUM.number = 3
EPIPPISTATE.name = "EPippiState"
EPIPPISTATE.full_name = ".Cmd.EPippiState"
EPIPPISTATE.values = {
  EPIPPISTATE_EPIPPISTATE_LIVE_SHOW_ENUM,
  EPIPPISTATE_EPIPPISTATE_LIVE_HIDE_ENUM,
  EPIPPISTATE_EPIPPISTATE_DIE_SHOW_ENUM,
  EPIPPISTATE_EPIPPISTATE_DIE_HIDE_ENUM
}
EGRAPHPOINTSTATE_EGRAPH_POINT_STATE_LOCKED_ENUM.name = "EGRAPH_POINT_STATE_LOCKED"
EGRAPHPOINTSTATE_EGRAPH_POINT_STATE_LOCKED_ENUM.index = 0
EGRAPHPOINTSTATE_EGRAPH_POINT_STATE_LOCKED_ENUM.number = 0
EGRAPHPOINTSTATE_EGRAPH_POINT_STATE_UNLOCKED_ENUM.name = "EGRAPH_POINT_STATE_UNLOCKED"
EGRAPHPOINTSTATE_EGRAPH_POINT_STATE_UNLOCKED_ENUM.index = 1
EGRAPHPOINTSTATE_EGRAPH_POINT_STATE_UNLOCKED_ENUM.number = 1
EGRAPHPOINTSTATE_EGRAPH_POINT_STATE_LIGHT_ENUM.name = "EGRAPH_POINT_STATE_LIGHT"
EGRAPHPOINTSTATE_EGRAPH_POINT_STATE_LIGHT_ENUM.index = 2
EGRAPHPOINTSTATE_EGRAPH_POINT_STATE_LIGHT_ENUM.number = 2
EGRAPHPOINTSTATE.name = "EGraphPointState"
EGRAPHPOINTSTATE.full_name = ".Cmd.EGraphPointState"
EGRAPHPOINTSTATE.values = {
  EGRAPHPOINTSTATE_EGRAPH_POINT_STATE_LOCKED_ENUM,
  EGRAPHPOINTSTATE_EGRAPH_POINT_STATE_UNLOCKED_ENUM,
  EGRAPHPOINTSTATE_EGRAPH_POINT_STATE_LIGHT_ENUM
}
CHOOSENEWPROFESSIONMESSCCMD_CMD_FIELD.name = "cmd"
CHOOSENEWPROFESSIONMESSCCMD_CMD_FIELD.full_name = ".Cmd.ChooseNewProfessionMessCCmd.cmd"
CHOOSENEWPROFESSIONMESSCCMD_CMD_FIELD.number = 1
CHOOSENEWPROFESSIONMESSCCMD_CMD_FIELD.index = 0
CHOOSENEWPROFESSIONMESSCCMD_CMD_FIELD.label = 1
CHOOSENEWPROFESSIONMESSCCMD_CMD_FIELD.has_default_value = true
CHOOSENEWPROFESSIONMESSCCMD_CMD_FIELD.default_value = 83
CHOOSENEWPROFESSIONMESSCCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
CHOOSENEWPROFESSIONMESSCCMD_CMD_FIELD.type = 14
CHOOSENEWPROFESSIONMESSCCMD_CMD_FIELD.cpp_type = 8
CHOOSENEWPROFESSIONMESSCCMD_PARAM_FIELD.name = "param"
CHOOSENEWPROFESSIONMESSCCMD_PARAM_FIELD.full_name = ".Cmd.ChooseNewProfessionMessCCmd.param"
CHOOSENEWPROFESSIONMESSCCMD_PARAM_FIELD.number = 2
CHOOSENEWPROFESSIONMESSCCMD_PARAM_FIELD.index = 1
CHOOSENEWPROFESSIONMESSCCMD_PARAM_FIELD.label = 1
CHOOSENEWPROFESSIONMESSCCMD_PARAM_FIELD.has_default_value = true
CHOOSENEWPROFESSIONMESSCCMD_PARAM_FIELD.default_value = 1
CHOOSENEWPROFESSIONMESSCCMD_PARAM_FIELD.enum_type = MESSCPARAM
CHOOSENEWPROFESSIONMESSCCMD_PARAM_FIELD.type = 14
CHOOSENEWPROFESSIONMESSCCMD_PARAM_FIELD.cpp_type = 8
CHOOSENEWPROFESSIONMESSCCMD_BORNPROFESSION_FIELD.name = "bornprofession"
CHOOSENEWPROFESSIONMESSCCMD_BORNPROFESSION_FIELD.full_name = ".Cmd.ChooseNewProfessionMessCCmd.bornprofession"
CHOOSENEWPROFESSIONMESSCCMD_BORNPROFESSION_FIELD.number = 3
CHOOSENEWPROFESSIONMESSCCMD_BORNPROFESSION_FIELD.index = 2
CHOOSENEWPROFESSIONMESSCCMD_BORNPROFESSION_FIELD.label = 1
CHOOSENEWPROFESSIONMESSCCMD_BORNPROFESSION_FIELD.has_default_value = false
CHOOSENEWPROFESSIONMESSCCMD_BORNPROFESSION_FIELD.default_value = nil
CHOOSENEWPROFESSIONMESSCCMD_BORNPROFESSION_FIELD.enum_type = PROTOCOMMON_PB_EPROFESSION
CHOOSENEWPROFESSIONMESSCCMD_BORNPROFESSION_FIELD.type = 14
CHOOSENEWPROFESSIONMESSCCMD_BORNPROFESSION_FIELD.cpp_type = 8
CHOOSENEWPROFESSIONMESSCCMD_CHOOSEPROFESSION_FIELD.name = "chooseprofession"
CHOOSENEWPROFESSIONMESSCCMD_CHOOSEPROFESSION_FIELD.full_name = ".Cmd.ChooseNewProfessionMessCCmd.chooseprofession"
CHOOSENEWPROFESSIONMESSCCMD_CHOOSEPROFESSION_FIELD.number = 4
CHOOSENEWPROFESSIONMESSCCMD_CHOOSEPROFESSION_FIELD.index = 3
CHOOSENEWPROFESSIONMESSCCMD_CHOOSEPROFESSION_FIELD.label = 1
CHOOSENEWPROFESSIONMESSCCMD_CHOOSEPROFESSION_FIELD.has_default_value = false
CHOOSENEWPROFESSIONMESSCCMD_CHOOSEPROFESSION_FIELD.default_value = nil
CHOOSENEWPROFESSIONMESSCCMD_CHOOSEPROFESSION_FIELD.enum_type = PROTOCOMMON_PB_EPROFESSION
CHOOSENEWPROFESSIONMESSCCMD_CHOOSEPROFESSION_FIELD.type = 14
CHOOSENEWPROFESSIONMESSCCMD_CHOOSEPROFESSION_FIELD.cpp_type = 8
CHOOSENEWPROFESSIONMESSCCMD.name = "ChooseNewProfessionMessCCmd"
CHOOSENEWPROFESSIONMESSCCMD.full_name = ".Cmd.ChooseNewProfessionMessCCmd"
CHOOSENEWPROFESSIONMESSCCMD.nested_types = {}
CHOOSENEWPROFESSIONMESSCCMD.enum_types = {}
CHOOSENEWPROFESSIONMESSCCMD.fields = {
  CHOOSENEWPROFESSIONMESSCCMD_CMD_FIELD,
  CHOOSENEWPROFESSIONMESSCCMD_PARAM_FIELD,
  CHOOSENEWPROFESSIONMESSCCMD_BORNPROFESSION_FIELD,
  CHOOSENEWPROFESSIONMESSCCMD_CHOOSEPROFESSION_FIELD
}
CHOOSENEWPROFESSIONMESSCCMD.is_extendable = false
CHOOSENEWPROFESSIONMESSCCMD.extensions = {}
INVITERSENDLOVECONFESSIONMESSCCMD_CMD_FIELD.name = "cmd"
INVITERSENDLOVECONFESSIONMESSCCMD_CMD_FIELD.full_name = ".Cmd.InviterSendLoveConfessionMessCCmd.cmd"
INVITERSENDLOVECONFESSIONMESSCCMD_CMD_FIELD.number = 1
INVITERSENDLOVECONFESSIONMESSCCMD_CMD_FIELD.index = 0
INVITERSENDLOVECONFESSIONMESSCCMD_CMD_FIELD.label = 1
INVITERSENDLOVECONFESSIONMESSCCMD_CMD_FIELD.has_default_value = true
INVITERSENDLOVECONFESSIONMESSCCMD_CMD_FIELD.default_value = 83
INVITERSENDLOVECONFESSIONMESSCCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
INVITERSENDLOVECONFESSIONMESSCCMD_CMD_FIELD.type = 14
INVITERSENDLOVECONFESSIONMESSCCMD_CMD_FIELD.cpp_type = 8
INVITERSENDLOVECONFESSIONMESSCCMD_PARAM_FIELD.name = "param"
INVITERSENDLOVECONFESSIONMESSCCMD_PARAM_FIELD.full_name = ".Cmd.InviterSendLoveConfessionMessCCmd.param"
INVITERSENDLOVECONFESSIONMESSCCMD_PARAM_FIELD.number = 2
INVITERSENDLOVECONFESSIONMESSCCMD_PARAM_FIELD.index = 1
INVITERSENDLOVECONFESSIONMESSCCMD_PARAM_FIELD.label = 1
INVITERSENDLOVECONFESSIONMESSCCMD_PARAM_FIELD.has_default_value = true
INVITERSENDLOVECONFESSIONMESSCCMD_PARAM_FIELD.default_value = 2
INVITERSENDLOVECONFESSIONMESSCCMD_PARAM_FIELD.enum_type = MESSCPARAM
INVITERSENDLOVECONFESSIONMESSCCMD_PARAM_FIELD.type = 14
INVITERSENDLOVECONFESSIONMESSCCMD_PARAM_FIELD.cpp_type = 8
INVITERSENDLOVECONFESSIONMESSCCMD_INVITEE_FIELD.name = "invitee"
INVITERSENDLOVECONFESSIONMESSCCMD_INVITEE_FIELD.full_name = ".Cmd.InviterSendLoveConfessionMessCCmd.invitee"
INVITERSENDLOVECONFESSIONMESSCCMD_INVITEE_FIELD.number = 3
INVITERSENDLOVECONFESSIONMESSCCMD_INVITEE_FIELD.index = 2
INVITERSENDLOVECONFESSIONMESSCCMD_INVITEE_FIELD.label = 1
INVITERSENDLOVECONFESSIONMESSCCMD_INVITEE_FIELD.has_default_value = false
INVITERSENDLOVECONFESSIONMESSCCMD_INVITEE_FIELD.default_value = 0
INVITERSENDLOVECONFESSIONMESSCCMD_INVITEE_FIELD.type = 4
INVITERSENDLOVECONFESSIONMESSCCMD_INVITEE_FIELD.cpp_type = 4
INVITERSENDLOVECONFESSIONMESSCCMD_INVITERNAME_FIELD.name = "invitername"
INVITERSENDLOVECONFESSIONMESSCCMD_INVITERNAME_FIELD.full_name = ".Cmd.InviterSendLoveConfessionMessCCmd.invitername"
INVITERSENDLOVECONFESSIONMESSCCMD_INVITERNAME_FIELD.number = 4
INVITERSENDLOVECONFESSIONMESSCCMD_INVITERNAME_FIELD.index = 3
INVITERSENDLOVECONFESSIONMESSCCMD_INVITERNAME_FIELD.label = 1
INVITERSENDLOVECONFESSIONMESSCCMD_INVITERNAME_FIELD.has_default_value = false
INVITERSENDLOVECONFESSIONMESSCCMD_INVITERNAME_FIELD.default_value = ""
INVITERSENDLOVECONFESSIONMESSCCMD_INVITERNAME_FIELD.type = 9
INVITERSENDLOVECONFESSIONMESSCCMD_INVITERNAME_FIELD.cpp_type = 9
INVITERSENDLOVECONFESSIONMESSCCMD.name = "InviterSendLoveConfessionMessCCmd"
INVITERSENDLOVECONFESSIONMESSCCMD.full_name = ".Cmd.InviterSendLoveConfessionMessCCmd"
INVITERSENDLOVECONFESSIONMESSCCMD.nested_types = {}
INVITERSENDLOVECONFESSIONMESSCCMD.enum_types = {}
INVITERSENDLOVECONFESSIONMESSCCMD.fields = {
  INVITERSENDLOVECONFESSIONMESSCCMD_CMD_FIELD,
  INVITERSENDLOVECONFESSIONMESSCCMD_PARAM_FIELD,
  INVITERSENDLOVECONFESSIONMESSCCMD_INVITEE_FIELD,
  INVITERSENDLOVECONFESSIONMESSCCMD_INVITERNAME_FIELD
}
INVITERSENDLOVECONFESSIONMESSCCMD.is_extendable = false
INVITERSENDLOVECONFESSIONMESSCCMD.extensions = {}
INVITEERECEIVELOVECONFESSIONMESSCCMD_CMD_FIELD.name = "cmd"
INVITEERECEIVELOVECONFESSIONMESSCCMD_CMD_FIELD.full_name = ".Cmd.InviteeReceiveLoveConfessionMessCCmd.cmd"
INVITEERECEIVELOVECONFESSIONMESSCCMD_CMD_FIELD.number = 1
INVITEERECEIVELOVECONFESSIONMESSCCMD_CMD_FIELD.index = 0
INVITEERECEIVELOVECONFESSIONMESSCCMD_CMD_FIELD.label = 1
INVITEERECEIVELOVECONFESSIONMESSCCMD_CMD_FIELD.has_default_value = true
INVITEERECEIVELOVECONFESSIONMESSCCMD_CMD_FIELD.default_value = 83
INVITEERECEIVELOVECONFESSIONMESSCCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
INVITEERECEIVELOVECONFESSIONMESSCCMD_CMD_FIELD.type = 14
INVITEERECEIVELOVECONFESSIONMESSCCMD_CMD_FIELD.cpp_type = 8
INVITEERECEIVELOVECONFESSIONMESSCCMD_PARAM_FIELD.name = "param"
INVITEERECEIVELOVECONFESSIONMESSCCMD_PARAM_FIELD.full_name = ".Cmd.InviteeReceiveLoveConfessionMessCCmd.param"
INVITEERECEIVELOVECONFESSIONMESSCCMD_PARAM_FIELD.number = 2
INVITEERECEIVELOVECONFESSIONMESSCCMD_PARAM_FIELD.index = 1
INVITEERECEIVELOVECONFESSIONMESSCCMD_PARAM_FIELD.label = 1
INVITEERECEIVELOVECONFESSIONMESSCCMD_PARAM_FIELD.has_default_value = true
INVITEERECEIVELOVECONFESSIONMESSCCMD_PARAM_FIELD.default_value = 3
INVITEERECEIVELOVECONFESSIONMESSCCMD_PARAM_FIELD.enum_type = MESSCPARAM
INVITEERECEIVELOVECONFESSIONMESSCCMD_PARAM_FIELD.type = 14
INVITEERECEIVELOVECONFESSIONMESSCCMD_PARAM_FIELD.cpp_type = 8
INVITEERECEIVELOVECONFESSIONMESSCCMD_INVITERNAME_FIELD.name = "invitername"
INVITEERECEIVELOVECONFESSIONMESSCCMD_INVITERNAME_FIELD.full_name = ".Cmd.InviteeReceiveLoveConfessionMessCCmd.invitername"
INVITEERECEIVELOVECONFESSIONMESSCCMD_INVITERNAME_FIELD.number = 3
INVITEERECEIVELOVECONFESSIONMESSCCMD_INVITERNAME_FIELD.index = 2
INVITEERECEIVELOVECONFESSIONMESSCCMD_INVITERNAME_FIELD.label = 1
INVITEERECEIVELOVECONFESSIONMESSCCMD_INVITERNAME_FIELD.has_default_value = false
INVITEERECEIVELOVECONFESSIONMESSCCMD_INVITERNAME_FIELD.default_value = ""
INVITEERECEIVELOVECONFESSIONMESSCCMD_INVITERNAME_FIELD.type = 9
INVITEERECEIVELOVECONFESSIONMESSCCMD_INVITERNAME_FIELD.cpp_type = 9
INVITEERECEIVELOVECONFESSIONMESSCCMD_INVITER_FIELD.name = "inviter"
INVITEERECEIVELOVECONFESSIONMESSCCMD_INVITER_FIELD.full_name = ".Cmd.InviteeReceiveLoveConfessionMessCCmd.inviter"
INVITEERECEIVELOVECONFESSIONMESSCCMD_INVITER_FIELD.number = 4
INVITEERECEIVELOVECONFESSIONMESSCCMD_INVITER_FIELD.index = 3
INVITEERECEIVELOVECONFESSIONMESSCCMD_INVITER_FIELD.label = 1
INVITEERECEIVELOVECONFESSIONMESSCCMD_INVITER_FIELD.has_default_value = false
INVITEERECEIVELOVECONFESSIONMESSCCMD_INVITER_FIELD.default_value = 0
INVITEERECEIVELOVECONFESSIONMESSCCMD_INVITER_FIELD.type = 4
INVITEERECEIVELOVECONFESSIONMESSCCMD_INVITER_FIELD.cpp_type = 4
INVITEERECEIVELOVECONFESSIONMESSCCMD.name = "InviteeReceiveLoveConfessionMessCCmd"
INVITEERECEIVELOVECONFESSIONMESSCCMD.full_name = ".Cmd.InviteeReceiveLoveConfessionMessCCmd"
INVITEERECEIVELOVECONFESSIONMESSCCMD.nested_types = {}
INVITEERECEIVELOVECONFESSIONMESSCCMD.enum_types = {}
INVITEERECEIVELOVECONFESSIONMESSCCMD.fields = {
  INVITEERECEIVELOVECONFESSIONMESSCCMD_CMD_FIELD,
  INVITEERECEIVELOVECONFESSIONMESSCCMD_PARAM_FIELD,
  INVITEERECEIVELOVECONFESSIONMESSCCMD_INVITERNAME_FIELD,
  INVITEERECEIVELOVECONFESSIONMESSCCMD_INVITER_FIELD
}
INVITEERECEIVELOVECONFESSIONMESSCCMD.is_extendable = false
INVITEERECEIVELOVECONFESSIONMESSCCMD.extensions = {}
INVITEEPROCESSLOVECONFESSIONMESSCCMD_CMD_FIELD.name = "cmd"
INVITEEPROCESSLOVECONFESSIONMESSCCMD_CMD_FIELD.full_name = ".Cmd.InviteeProcessLoveConfessionMessCCmd.cmd"
INVITEEPROCESSLOVECONFESSIONMESSCCMD_CMD_FIELD.number = 1
INVITEEPROCESSLOVECONFESSIONMESSCCMD_CMD_FIELD.index = 0
INVITEEPROCESSLOVECONFESSIONMESSCCMD_CMD_FIELD.label = 1
INVITEEPROCESSLOVECONFESSIONMESSCCMD_CMD_FIELD.has_default_value = true
INVITEEPROCESSLOVECONFESSIONMESSCCMD_CMD_FIELD.default_value = 83
INVITEEPROCESSLOVECONFESSIONMESSCCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
INVITEEPROCESSLOVECONFESSIONMESSCCMD_CMD_FIELD.type = 14
INVITEEPROCESSLOVECONFESSIONMESSCCMD_CMD_FIELD.cpp_type = 8
INVITEEPROCESSLOVECONFESSIONMESSCCMD_PARAM_FIELD.name = "param"
INVITEEPROCESSLOVECONFESSIONMESSCCMD_PARAM_FIELD.full_name = ".Cmd.InviteeProcessLoveConfessionMessCCmd.param"
INVITEEPROCESSLOVECONFESSIONMESSCCMD_PARAM_FIELD.number = 2
INVITEEPROCESSLOVECONFESSIONMESSCCMD_PARAM_FIELD.index = 1
INVITEEPROCESSLOVECONFESSIONMESSCCMD_PARAM_FIELD.label = 1
INVITEEPROCESSLOVECONFESSIONMESSCCMD_PARAM_FIELD.has_default_value = true
INVITEEPROCESSLOVECONFESSIONMESSCCMD_PARAM_FIELD.default_value = 4
INVITEEPROCESSLOVECONFESSIONMESSCCMD_PARAM_FIELD.enum_type = MESSCPARAM
INVITEEPROCESSLOVECONFESSIONMESSCCMD_PARAM_FIELD.type = 14
INVITEEPROCESSLOVECONFESSIONMESSCCMD_PARAM_FIELD.cpp_type = 8
INVITEEPROCESSLOVECONFESSIONMESSCCMD_ACCEPT_FIELD.name = "accept"
INVITEEPROCESSLOVECONFESSIONMESSCCMD_ACCEPT_FIELD.full_name = ".Cmd.InviteeProcessLoveConfessionMessCCmd.accept"
INVITEEPROCESSLOVECONFESSIONMESSCCMD_ACCEPT_FIELD.number = 3
INVITEEPROCESSLOVECONFESSIONMESSCCMD_ACCEPT_FIELD.index = 2
INVITEEPROCESSLOVECONFESSIONMESSCCMD_ACCEPT_FIELD.label = 1
INVITEEPROCESSLOVECONFESSIONMESSCCMD_ACCEPT_FIELD.has_default_value = false
INVITEEPROCESSLOVECONFESSIONMESSCCMD_ACCEPT_FIELD.default_value = false
INVITEEPROCESSLOVECONFESSIONMESSCCMD_ACCEPT_FIELD.type = 8
INVITEEPROCESSLOVECONFESSIONMESSCCMD_ACCEPT_FIELD.cpp_type = 7
INVITEEPROCESSLOVECONFESSIONMESSCCMD_INVITER_FIELD.name = "inviter"
INVITEEPROCESSLOVECONFESSIONMESSCCMD_INVITER_FIELD.full_name = ".Cmd.InviteeProcessLoveConfessionMessCCmd.inviter"
INVITEEPROCESSLOVECONFESSIONMESSCCMD_INVITER_FIELD.number = 4
INVITEEPROCESSLOVECONFESSIONMESSCCMD_INVITER_FIELD.index = 3
INVITEEPROCESSLOVECONFESSIONMESSCCMD_INVITER_FIELD.label = 1
INVITEEPROCESSLOVECONFESSIONMESSCCMD_INVITER_FIELD.has_default_value = false
INVITEEPROCESSLOVECONFESSIONMESSCCMD_INVITER_FIELD.default_value = 0
INVITEEPROCESSLOVECONFESSIONMESSCCMD_INVITER_FIELD.type = 4
INVITEEPROCESSLOVECONFESSIONMESSCCMD_INVITER_FIELD.cpp_type = 4
INVITEEPROCESSLOVECONFESSIONMESSCCMD.name = "InviteeProcessLoveConfessionMessCCmd"
INVITEEPROCESSLOVECONFESSIONMESSCCMD.full_name = ".Cmd.InviteeProcessLoveConfessionMessCCmd"
INVITEEPROCESSLOVECONFESSIONMESSCCMD.nested_types = {}
INVITEEPROCESSLOVECONFESSIONMESSCCMD.enum_types = {}
INVITEEPROCESSLOVECONFESSIONMESSCCMD.fields = {
  INVITEEPROCESSLOVECONFESSIONMESSCCMD_CMD_FIELD,
  INVITEEPROCESSLOVECONFESSIONMESSCCMD_PARAM_FIELD,
  INVITEEPROCESSLOVECONFESSIONMESSCCMD_ACCEPT_FIELD,
  INVITEEPROCESSLOVECONFESSIONMESSCCMD_INVITER_FIELD
}
INVITEEPROCESSLOVECONFESSIONMESSCCMD.is_extendable = false
INVITEEPROCESSLOVECONFESSIONMESSCCMD.extensions = {}
INVITERRECEIVECONFESSIONMESSCCMD_CMD_FIELD.name = "cmd"
INVITERRECEIVECONFESSIONMESSCCMD_CMD_FIELD.full_name = ".Cmd.InviterReceiveConfessionMessCCmd.cmd"
INVITERRECEIVECONFESSIONMESSCCMD_CMD_FIELD.number = 1
INVITERRECEIVECONFESSIONMESSCCMD_CMD_FIELD.index = 0
INVITERRECEIVECONFESSIONMESSCCMD_CMD_FIELD.label = 1
INVITERRECEIVECONFESSIONMESSCCMD_CMD_FIELD.has_default_value = true
INVITERRECEIVECONFESSIONMESSCCMD_CMD_FIELD.default_value = 83
INVITERRECEIVECONFESSIONMESSCCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
INVITERRECEIVECONFESSIONMESSCCMD_CMD_FIELD.type = 14
INVITERRECEIVECONFESSIONMESSCCMD_CMD_FIELD.cpp_type = 8
INVITERRECEIVECONFESSIONMESSCCMD_PARAM_FIELD.name = "param"
INVITERRECEIVECONFESSIONMESSCCMD_PARAM_FIELD.full_name = ".Cmd.InviterReceiveConfessionMessCCmd.param"
INVITERRECEIVECONFESSIONMESSCCMD_PARAM_FIELD.number = 2
INVITERRECEIVECONFESSIONMESSCCMD_PARAM_FIELD.index = 1
INVITERRECEIVECONFESSIONMESSCCMD_PARAM_FIELD.label = 1
INVITERRECEIVECONFESSIONMESSCCMD_PARAM_FIELD.has_default_value = true
INVITERRECEIVECONFESSIONMESSCCMD_PARAM_FIELD.default_value = 5
INVITERRECEIVECONFESSIONMESSCCMD_PARAM_FIELD.enum_type = MESSCPARAM
INVITERRECEIVECONFESSIONMESSCCMD_PARAM_FIELD.type = 14
INVITERRECEIVECONFESSIONMESSCCMD_PARAM_FIELD.cpp_type = 8
INVITERRECEIVECONFESSIONMESSCCMD_ACCEPT_FIELD.name = "accept"
INVITERRECEIVECONFESSIONMESSCCMD_ACCEPT_FIELD.full_name = ".Cmd.InviterReceiveConfessionMessCCmd.accept"
INVITERRECEIVECONFESSIONMESSCCMD_ACCEPT_FIELD.number = 3
INVITERRECEIVECONFESSIONMESSCCMD_ACCEPT_FIELD.index = 2
INVITERRECEIVECONFESSIONMESSCCMD_ACCEPT_FIELD.label = 1
INVITERRECEIVECONFESSIONMESSCCMD_ACCEPT_FIELD.has_default_value = false
INVITERRECEIVECONFESSIONMESSCCMD_ACCEPT_FIELD.default_value = false
INVITERRECEIVECONFESSIONMESSCCMD_ACCEPT_FIELD.type = 8
INVITERRECEIVECONFESSIONMESSCCMD_ACCEPT_FIELD.cpp_type = 7
INVITERRECEIVECONFESSIONMESSCCMD_INVITER_FIELD.name = "inviter"
INVITERRECEIVECONFESSIONMESSCCMD_INVITER_FIELD.full_name = ".Cmd.InviterReceiveConfessionMessCCmd.inviter"
INVITERRECEIVECONFESSIONMESSCCMD_INVITER_FIELD.number = 4
INVITERRECEIVECONFESSIONMESSCCMD_INVITER_FIELD.index = 3
INVITERRECEIVECONFESSIONMESSCCMD_INVITER_FIELD.label = 1
INVITERRECEIVECONFESSIONMESSCCMD_INVITER_FIELD.has_default_value = false
INVITERRECEIVECONFESSIONMESSCCMD_INVITER_FIELD.default_value = 0
INVITERRECEIVECONFESSIONMESSCCMD_INVITER_FIELD.type = 4
INVITERRECEIVECONFESSIONMESSCCMD_INVITER_FIELD.cpp_type = 4
INVITERRECEIVECONFESSIONMESSCCMD.name = "InviterReceiveConfessionMessCCmd"
INVITERRECEIVECONFESSIONMESSCCMD.full_name = ".Cmd.InviterReceiveConfessionMessCCmd"
INVITERRECEIVECONFESSIONMESSCCMD.nested_types = {}
INVITERRECEIVECONFESSIONMESSCCMD.enum_types = {}
INVITERRECEIVECONFESSIONMESSCCMD.fields = {
  INVITERRECEIVECONFESSIONMESSCCMD_CMD_FIELD,
  INVITERRECEIVECONFESSIONMESSCCMD_PARAM_FIELD,
  INVITERRECEIVECONFESSIONMESSCCMD_ACCEPT_FIELD,
  INVITERRECEIVECONFESSIONMESSCCMD_INVITER_FIELD
}
INVITERRECEIVECONFESSIONMESSCCMD.is_extendable = false
INVITERRECEIVECONFESSIONMESSCCMD.extensions = {}
FINGERGUESSLOVECONFESSIONMESSCCMD_CMD_FIELD.name = "cmd"
FINGERGUESSLOVECONFESSIONMESSCCMD_CMD_FIELD.full_name = ".Cmd.FingerGuessLoveConfessionMessCCmd.cmd"
FINGERGUESSLOVECONFESSIONMESSCCMD_CMD_FIELD.number = 1
FINGERGUESSLOVECONFESSIONMESSCCMD_CMD_FIELD.index = 0
FINGERGUESSLOVECONFESSIONMESSCCMD_CMD_FIELD.label = 1
FINGERGUESSLOVECONFESSIONMESSCCMD_CMD_FIELD.has_default_value = true
FINGERGUESSLOVECONFESSIONMESSCCMD_CMD_FIELD.default_value = 83
FINGERGUESSLOVECONFESSIONMESSCCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
FINGERGUESSLOVECONFESSIONMESSCCMD_CMD_FIELD.type = 14
FINGERGUESSLOVECONFESSIONMESSCCMD_CMD_FIELD.cpp_type = 8
FINGERGUESSLOVECONFESSIONMESSCCMD_PARAM_FIELD.name = "param"
FINGERGUESSLOVECONFESSIONMESSCCMD_PARAM_FIELD.full_name = ".Cmd.FingerGuessLoveConfessionMessCCmd.param"
FINGERGUESSLOVECONFESSIONMESSCCMD_PARAM_FIELD.number = 2
FINGERGUESSLOVECONFESSIONMESSCCMD_PARAM_FIELD.index = 1
FINGERGUESSLOVECONFESSIONMESSCCMD_PARAM_FIELD.label = 1
FINGERGUESSLOVECONFESSIONMESSCCMD_PARAM_FIELD.has_default_value = true
FINGERGUESSLOVECONFESSIONMESSCCMD_PARAM_FIELD.default_value = 6
FINGERGUESSLOVECONFESSIONMESSCCMD_PARAM_FIELD.enum_type = MESSCPARAM
FINGERGUESSLOVECONFESSIONMESSCCMD_PARAM_FIELD.type = 14
FINGERGUESSLOVECONFESSIONMESSCCMD_PARAM_FIELD.cpp_type = 8
FINGERGUESSLOVECONFESSIONMESSCCMD_ITEM_FIELD.name = "item"
FINGERGUESSLOVECONFESSIONMESSCCMD_ITEM_FIELD.full_name = ".Cmd.FingerGuessLoveConfessionMessCCmd.item"
FINGERGUESSLOVECONFESSIONMESSCCMD_ITEM_FIELD.number = 3
FINGERGUESSLOVECONFESSIONMESSCCMD_ITEM_FIELD.index = 2
FINGERGUESSLOVECONFESSIONMESSCCMD_ITEM_FIELD.label = 1
FINGERGUESSLOVECONFESSIONMESSCCMD_ITEM_FIELD.has_default_value = false
FINGERGUESSLOVECONFESSIONMESSCCMD_ITEM_FIELD.default_value = nil
FINGERGUESSLOVECONFESSIONMESSCCMD_ITEM_FIELD.enum_type = FINGERGUESSITEM
FINGERGUESSLOVECONFESSIONMESSCCMD_ITEM_FIELD.type = 14
FINGERGUESSLOVECONFESSIONMESSCCMD_ITEM_FIELD.cpp_type = 8
FINGERGUESSLOVECONFESSIONMESSCCMD_INVITER_FIELD.name = "inviter"
FINGERGUESSLOVECONFESSIONMESSCCMD_INVITER_FIELD.full_name = ".Cmd.FingerGuessLoveConfessionMessCCmd.inviter"
FINGERGUESSLOVECONFESSIONMESSCCMD_INVITER_FIELD.number = 4
FINGERGUESSLOVECONFESSIONMESSCCMD_INVITER_FIELD.index = 3
FINGERGUESSLOVECONFESSIONMESSCCMD_INVITER_FIELD.label = 1
FINGERGUESSLOVECONFESSIONMESSCCMD_INVITER_FIELD.has_default_value = false
FINGERGUESSLOVECONFESSIONMESSCCMD_INVITER_FIELD.default_value = 0
FINGERGUESSLOVECONFESSIONMESSCCMD_INVITER_FIELD.type = 4
FINGERGUESSLOVECONFESSIONMESSCCMD_INVITER_FIELD.cpp_type = 4
FINGERGUESSLOVECONFESSIONMESSCCMD.name = "FingerGuessLoveConfessionMessCCmd"
FINGERGUESSLOVECONFESSIONMESSCCMD.full_name = ".Cmd.FingerGuessLoveConfessionMessCCmd"
FINGERGUESSLOVECONFESSIONMESSCCMD.nested_types = {}
FINGERGUESSLOVECONFESSIONMESSCCMD.enum_types = {}
FINGERGUESSLOVECONFESSIONMESSCCMD.fields = {
  FINGERGUESSLOVECONFESSIONMESSCCMD_CMD_FIELD,
  FINGERGUESSLOVECONFESSIONMESSCCMD_PARAM_FIELD,
  FINGERGUESSLOVECONFESSIONMESSCCMD_ITEM_FIELD,
  FINGERGUESSLOVECONFESSIONMESSCCMD_INVITER_FIELD
}
FINGERGUESSLOVECONFESSIONMESSCCMD.is_extendable = false
FINGERGUESSLOVECONFESSIONMESSCCMD.extensions = {}
FINGERLOSELOVECONFESSIONMESSCCMD_CMD_FIELD.name = "cmd"
FINGERLOSELOVECONFESSIONMESSCCMD_CMD_FIELD.full_name = ".Cmd.FingerLoseLoveConfessionMessCCmd.cmd"
FINGERLOSELOVECONFESSIONMESSCCMD_CMD_FIELD.number = 1
FINGERLOSELOVECONFESSIONMESSCCMD_CMD_FIELD.index = 0
FINGERLOSELOVECONFESSIONMESSCCMD_CMD_FIELD.label = 1
FINGERLOSELOVECONFESSIONMESSCCMD_CMD_FIELD.has_default_value = true
FINGERLOSELOVECONFESSIONMESSCCMD_CMD_FIELD.default_value = 83
FINGERLOSELOVECONFESSIONMESSCCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
FINGERLOSELOVECONFESSIONMESSCCMD_CMD_FIELD.type = 14
FINGERLOSELOVECONFESSIONMESSCCMD_CMD_FIELD.cpp_type = 8
FINGERLOSELOVECONFESSIONMESSCCMD_PARAM_FIELD.name = "param"
FINGERLOSELOVECONFESSIONMESSCCMD_PARAM_FIELD.full_name = ".Cmd.FingerLoseLoveConfessionMessCCmd.param"
FINGERLOSELOVECONFESSIONMESSCCMD_PARAM_FIELD.number = 2
FINGERLOSELOVECONFESSIONMESSCCMD_PARAM_FIELD.index = 1
FINGERLOSELOVECONFESSIONMESSCCMD_PARAM_FIELD.label = 1
FINGERLOSELOVECONFESSIONMESSCCMD_PARAM_FIELD.has_default_value = true
FINGERLOSELOVECONFESSIONMESSCCMD_PARAM_FIELD.default_value = 7
FINGERLOSELOVECONFESSIONMESSCCMD_PARAM_FIELD.enum_type = MESSCPARAM
FINGERLOSELOVECONFESSIONMESSCCMD_PARAM_FIELD.type = 14
FINGERLOSELOVECONFESSIONMESSCCMD_PARAM_FIELD.cpp_type = 8
FINGERLOSELOVECONFESSIONMESSCCMD_INVITER_FIELD.name = "inviter"
FINGERLOSELOVECONFESSIONMESSCCMD_INVITER_FIELD.full_name = ".Cmd.FingerLoseLoveConfessionMessCCmd.inviter"
FINGERLOSELOVECONFESSIONMESSCCMD_INVITER_FIELD.number = 3
FINGERLOSELOVECONFESSIONMESSCCMD_INVITER_FIELD.index = 2
FINGERLOSELOVECONFESSIONMESSCCMD_INVITER_FIELD.label = 1
FINGERLOSELOVECONFESSIONMESSCCMD_INVITER_FIELD.has_default_value = false
FINGERLOSELOVECONFESSIONMESSCCMD_INVITER_FIELD.default_value = 0
FINGERLOSELOVECONFESSIONMESSCCMD_INVITER_FIELD.type = 4
FINGERLOSELOVECONFESSIONMESSCCMD_INVITER_FIELD.cpp_type = 4
FINGERLOSELOVECONFESSIONMESSCCMD_WINNERFINGER_FIELD.name = "winnerfinger"
FINGERLOSELOVECONFESSIONMESSCCMD_WINNERFINGER_FIELD.full_name = ".Cmd.FingerLoseLoveConfessionMessCCmd.winnerfinger"
FINGERLOSELOVECONFESSIONMESSCCMD_WINNERFINGER_FIELD.number = 4
FINGERLOSELOVECONFESSIONMESSCCMD_WINNERFINGER_FIELD.index = 3
FINGERLOSELOVECONFESSIONMESSCCMD_WINNERFINGER_FIELD.label = 1
FINGERLOSELOVECONFESSIONMESSCCMD_WINNERFINGER_FIELD.has_default_value = false
FINGERLOSELOVECONFESSIONMESSCCMD_WINNERFINGER_FIELD.default_value = nil
FINGERLOSELOVECONFESSIONMESSCCMD_WINNERFINGER_FIELD.enum_type = FINGERGUESSITEM
FINGERLOSELOVECONFESSIONMESSCCMD_WINNERFINGER_FIELD.type = 14
FINGERLOSELOVECONFESSIONMESSCCMD_WINNERFINGER_FIELD.cpp_type = 8
FINGERLOSELOVECONFESSIONMESSCCMD_LOSERFINGER_FIELD.name = "loserfinger"
FINGERLOSELOVECONFESSIONMESSCCMD_LOSERFINGER_FIELD.full_name = ".Cmd.FingerLoseLoveConfessionMessCCmd.loserfinger"
FINGERLOSELOVECONFESSIONMESSCCMD_LOSERFINGER_FIELD.number = 5
FINGERLOSELOVECONFESSIONMESSCCMD_LOSERFINGER_FIELD.index = 4
FINGERLOSELOVECONFESSIONMESSCCMD_LOSERFINGER_FIELD.label = 1
FINGERLOSELOVECONFESSIONMESSCCMD_LOSERFINGER_FIELD.has_default_value = false
FINGERLOSELOVECONFESSIONMESSCCMD_LOSERFINGER_FIELD.default_value = nil
FINGERLOSELOVECONFESSIONMESSCCMD_LOSERFINGER_FIELD.enum_type = FINGERGUESSITEM
FINGERLOSELOVECONFESSIONMESSCCMD_LOSERFINGER_FIELD.type = 14
FINGERLOSELOVECONFESSIONMESSCCMD_LOSERFINGER_FIELD.cpp_type = 8
FINGERLOSELOVECONFESSIONMESSCCMD_WINNER_FIELD.name = "winner"
FINGERLOSELOVECONFESSIONMESSCCMD_WINNER_FIELD.full_name = ".Cmd.FingerLoseLoveConfessionMessCCmd.winner"
FINGERLOSELOVECONFESSIONMESSCCMD_WINNER_FIELD.number = 6
FINGERLOSELOVECONFESSIONMESSCCMD_WINNER_FIELD.index = 5
FINGERLOSELOVECONFESSIONMESSCCMD_WINNER_FIELD.label = 1
FINGERLOSELOVECONFESSIONMESSCCMD_WINNER_FIELD.has_default_value = false
FINGERLOSELOVECONFESSIONMESSCCMD_WINNER_FIELD.default_value = 0
FINGERLOSELOVECONFESSIONMESSCCMD_WINNER_FIELD.type = 4
FINGERLOSELOVECONFESSIONMESSCCMD_WINNER_FIELD.cpp_type = 4
FINGERLOSELOVECONFESSIONMESSCCMD.name = "FingerLoseLoveConfessionMessCCmd"
FINGERLOSELOVECONFESSIONMESSCCMD.full_name = ".Cmd.FingerLoseLoveConfessionMessCCmd"
FINGERLOSELOVECONFESSIONMESSCCMD.nested_types = {}
FINGERLOSELOVECONFESSIONMESSCCMD.enum_types = {}
FINGERLOSELOVECONFESSIONMESSCCMD.fields = {
  FINGERLOSELOVECONFESSIONMESSCCMD_CMD_FIELD,
  FINGERLOSELOVECONFESSIONMESSCCMD_PARAM_FIELD,
  FINGERLOSELOVECONFESSIONMESSCCMD_INVITER_FIELD,
  FINGERLOSELOVECONFESSIONMESSCCMD_WINNERFINGER_FIELD,
  FINGERLOSELOVECONFESSIONMESSCCMD_LOSERFINGER_FIELD,
  FINGERLOSELOVECONFESSIONMESSCCMD_WINNER_FIELD
}
FINGERLOSELOVECONFESSIONMESSCCMD.is_extendable = false
FINGERLOSELOVECONFESSIONMESSCCMD.extensions = {}
INVITERRESULTLOVECONFESSIONMESSCCMD_CMD_FIELD.name = "cmd"
INVITERRESULTLOVECONFESSIONMESSCCMD_CMD_FIELD.full_name = ".Cmd.InviterResultLoveConfessionMessCCmd.cmd"
INVITERRESULTLOVECONFESSIONMESSCCMD_CMD_FIELD.number = 1
INVITERRESULTLOVECONFESSIONMESSCCMD_CMD_FIELD.index = 0
INVITERRESULTLOVECONFESSIONMESSCCMD_CMD_FIELD.label = 1
INVITERRESULTLOVECONFESSIONMESSCCMD_CMD_FIELD.has_default_value = true
INVITERRESULTLOVECONFESSIONMESSCCMD_CMD_FIELD.default_value = 83
INVITERRESULTLOVECONFESSIONMESSCCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
INVITERRESULTLOVECONFESSIONMESSCCMD_CMD_FIELD.type = 14
INVITERRESULTLOVECONFESSIONMESSCCMD_CMD_FIELD.cpp_type = 8
INVITERRESULTLOVECONFESSIONMESSCCMD_PARAM_FIELD.name = "param"
INVITERRESULTLOVECONFESSIONMESSCCMD_PARAM_FIELD.full_name = ".Cmd.InviterResultLoveConfessionMessCCmd.param"
INVITERRESULTLOVECONFESSIONMESSCCMD_PARAM_FIELD.number = 2
INVITERRESULTLOVECONFESSIONMESSCCMD_PARAM_FIELD.index = 1
INVITERRESULTLOVECONFESSIONMESSCCMD_PARAM_FIELD.label = 1
INVITERRESULTLOVECONFESSIONMESSCCMD_PARAM_FIELD.has_default_value = true
INVITERRESULTLOVECONFESSIONMESSCCMD_PARAM_FIELD.default_value = 8
INVITERRESULTLOVECONFESSIONMESSCCMD_PARAM_FIELD.enum_type = MESSCPARAM
INVITERRESULTLOVECONFESSIONMESSCCMD_PARAM_FIELD.type = 14
INVITERRESULTLOVECONFESSIONMESSCCMD_PARAM_FIELD.cpp_type = 8
INVITERRESULTLOVECONFESSIONMESSCCMD_SUCCESS_FIELD.name = "success"
INVITERRESULTLOVECONFESSIONMESSCCMD_SUCCESS_FIELD.full_name = ".Cmd.InviterResultLoveConfessionMessCCmd.success"
INVITERRESULTLOVECONFESSIONMESSCCMD_SUCCESS_FIELD.number = 3
INVITERRESULTLOVECONFESSIONMESSCCMD_SUCCESS_FIELD.index = 2
INVITERRESULTLOVECONFESSIONMESSCCMD_SUCCESS_FIELD.label = 1
INVITERRESULTLOVECONFESSIONMESSCCMD_SUCCESS_FIELD.has_default_value = false
INVITERRESULTLOVECONFESSIONMESSCCMD_SUCCESS_FIELD.default_value = false
INVITERRESULTLOVECONFESSIONMESSCCMD_SUCCESS_FIELD.type = 8
INVITERRESULTLOVECONFESSIONMESSCCMD_SUCCESS_FIELD.cpp_type = 7
INVITERRESULTLOVECONFESSIONMESSCCMD_INVITEE_FIELD.name = "invitee"
INVITERRESULTLOVECONFESSIONMESSCCMD_INVITEE_FIELD.full_name = ".Cmd.InviterResultLoveConfessionMessCCmd.invitee"
INVITERRESULTLOVECONFESSIONMESSCCMD_INVITEE_FIELD.number = 4
INVITERRESULTLOVECONFESSIONMESSCCMD_INVITEE_FIELD.index = 3
INVITERRESULTLOVECONFESSIONMESSCCMD_INVITEE_FIELD.label = 1
INVITERRESULTLOVECONFESSIONMESSCCMD_INVITEE_FIELD.has_default_value = false
INVITERRESULTLOVECONFESSIONMESSCCMD_INVITEE_FIELD.default_value = 0
INVITERRESULTLOVECONFESSIONMESSCCMD_INVITEE_FIELD.type = 4
INVITERRESULTLOVECONFESSIONMESSCCMD_INVITEE_FIELD.cpp_type = 4
INVITERRESULTLOVECONFESSIONMESSCCMD.name = "InviterResultLoveConfessionMessCCmd"
INVITERRESULTLOVECONFESSIONMESSCCMD.full_name = ".Cmd.InviterResultLoveConfessionMessCCmd"
INVITERRESULTLOVECONFESSIONMESSCCMD.nested_types = {}
INVITERRESULTLOVECONFESSIONMESSCCMD.enum_types = {}
INVITERRESULTLOVECONFESSIONMESSCCMD.fields = {
  INVITERRESULTLOVECONFESSIONMESSCCMD_CMD_FIELD,
  INVITERRESULTLOVECONFESSIONMESSCCMD_PARAM_FIELD,
  INVITERRESULTLOVECONFESSIONMESSCCMD_SUCCESS_FIELD,
  INVITERRESULTLOVECONFESSIONMESSCCMD_INVITEE_FIELD
}
INVITERRESULTLOVECONFESSIONMESSCCMD.is_extendable = false
INVITERRESULTLOVECONFESSIONMESSCCMD.extensions = {}
MAPSTEPFOREVERREWARDITEM_MAPSTEP_QUESTID_FIELD.name = "mapstep_questid"
MAPSTEPFOREVERREWARDITEM_MAPSTEP_QUESTID_FIELD.full_name = ".Cmd.MapStepForeverRewardItem.mapstep_questid"
MAPSTEPFOREVERREWARDITEM_MAPSTEP_QUESTID_FIELD.number = 1
MAPSTEPFOREVERREWARDITEM_MAPSTEP_QUESTID_FIELD.index = 0
MAPSTEPFOREVERREWARDITEM_MAPSTEP_QUESTID_FIELD.label = 1
MAPSTEPFOREVERREWARDITEM_MAPSTEP_QUESTID_FIELD.has_default_value = false
MAPSTEPFOREVERREWARDITEM_MAPSTEP_QUESTID_FIELD.default_value = 0
MAPSTEPFOREVERREWARDITEM_MAPSTEP_QUESTID_FIELD.type = 13
MAPSTEPFOREVERREWARDITEM_MAPSTEP_QUESTID_FIELD.cpp_type = 3
MAPSTEPFOREVERREWARDITEM_MAPSTEP_GROUPID_FIELD.name = "mapstep_groupid"
MAPSTEPFOREVERREWARDITEM_MAPSTEP_GROUPID_FIELD.full_name = ".Cmd.MapStepForeverRewardItem.mapstep_groupid"
MAPSTEPFOREVERREWARDITEM_MAPSTEP_GROUPID_FIELD.number = 2
MAPSTEPFOREVERREWARDITEM_MAPSTEP_GROUPID_FIELD.index = 1
MAPSTEPFOREVERREWARDITEM_MAPSTEP_GROUPID_FIELD.label = 1
MAPSTEPFOREVERREWARDITEM_MAPSTEP_GROUPID_FIELD.has_default_value = false
MAPSTEPFOREVERREWARDITEM_MAPSTEP_GROUPID_FIELD.default_value = 0
MAPSTEPFOREVERREWARDITEM_MAPSTEP_GROUPID_FIELD.type = 13
MAPSTEPFOREVERREWARDITEM_MAPSTEP_GROUPID_FIELD.cpp_type = 3
MAPSTEPFOREVERREWARDITEM.name = "MapStepForeverRewardItem"
MAPSTEPFOREVERREWARDITEM.full_name = ".Cmd.MapStepForeverRewardItem"
MAPSTEPFOREVERREWARDITEM.nested_types = {}
MAPSTEPFOREVERREWARDITEM.enum_types = {}
MAPSTEPFOREVERREWARDITEM.fields = {
  MAPSTEPFOREVERREWARDITEM_MAPSTEP_QUESTID_FIELD,
  MAPSTEPFOREVERREWARDITEM_MAPSTEP_GROUPID_FIELD
}
MAPSTEPFOREVERREWARDITEM.is_extendable = false
MAPSTEPFOREVERREWARDITEM.extensions = {}
SYNCMAPSTEPFOREVERREWARDINFO_CMD_FIELD.name = "cmd"
SYNCMAPSTEPFOREVERREWARDINFO_CMD_FIELD.full_name = ".Cmd.SyncMapStepForeverRewardInfo.cmd"
SYNCMAPSTEPFOREVERREWARDINFO_CMD_FIELD.number = 1
SYNCMAPSTEPFOREVERREWARDINFO_CMD_FIELD.index = 0
SYNCMAPSTEPFOREVERREWARDINFO_CMD_FIELD.label = 1
SYNCMAPSTEPFOREVERREWARDINFO_CMD_FIELD.has_default_value = true
SYNCMAPSTEPFOREVERREWARDINFO_CMD_FIELD.default_value = 83
SYNCMAPSTEPFOREVERREWARDINFO_CMD_FIELD.enum_type = XCMD_PB_COMMAND
SYNCMAPSTEPFOREVERREWARDINFO_CMD_FIELD.type = 14
SYNCMAPSTEPFOREVERREWARDINFO_CMD_FIELD.cpp_type = 8
SYNCMAPSTEPFOREVERREWARDINFO_PARAM_FIELD.name = "param"
SYNCMAPSTEPFOREVERREWARDINFO_PARAM_FIELD.full_name = ".Cmd.SyncMapStepForeverRewardInfo.param"
SYNCMAPSTEPFOREVERREWARDINFO_PARAM_FIELD.number = 2
SYNCMAPSTEPFOREVERREWARDINFO_PARAM_FIELD.index = 1
SYNCMAPSTEPFOREVERREWARDINFO_PARAM_FIELD.label = 1
SYNCMAPSTEPFOREVERREWARDINFO_PARAM_FIELD.has_default_value = true
SYNCMAPSTEPFOREVERREWARDINFO_PARAM_FIELD.default_value = 9
SYNCMAPSTEPFOREVERREWARDINFO_PARAM_FIELD.enum_type = MESSCPARAM
SYNCMAPSTEPFOREVERREWARDINFO_PARAM_FIELD.type = 14
SYNCMAPSTEPFOREVERREWARDINFO_PARAM_FIELD.cpp_type = 8
SYNCMAPSTEPFOREVERREWARDINFO_INFOS_FIELD.name = "infos"
SYNCMAPSTEPFOREVERREWARDINFO_INFOS_FIELD.full_name = ".Cmd.SyncMapStepForeverRewardInfo.infos"
SYNCMAPSTEPFOREVERREWARDINFO_INFOS_FIELD.number = 3
SYNCMAPSTEPFOREVERREWARDINFO_INFOS_FIELD.index = 2
SYNCMAPSTEPFOREVERREWARDINFO_INFOS_FIELD.label = 3
SYNCMAPSTEPFOREVERREWARDINFO_INFOS_FIELD.has_default_value = false
SYNCMAPSTEPFOREVERREWARDINFO_INFOS_FIELD.default_value = {}
SYNCMAPSTEPFOREVERREWARDINFO_INFOS_FIELD.message_type = MAPSTEPFOREVERREWARDITEM
SYNCMAPSTEPFOREVERREWARDINFO_INFOS_FIELD.type = 11
SYNCMAPSTEPFOREVERREWARDINFO_INFOS_FIELD.cpp_type = 10
SYNCMAPSTEPFOREVERREWARDINFO.name = "SyncMapStepForeverRewardInfo"
SYNCMAPSTEPFOREVERREWARDINFO.full_name = ".Cmd.SyncMapStepForeverRewardInfo"
SYNCMAPSTEPFOREVERREWARDINFO.nested_types = {}
SYNCMAPSTEPFOREVERREWARDINFO.enum_types = {}
SYNCMAPSTEPFOREVERREWARDINFO.fields = {
  SYNCMAPSTEPFOREVERREWARDINFO_CMD_FIELD,
  SYNCMAPSTEPFOREVERREWARDINFO_PARAM_FIELD,
  SYNCMAPSTEPFOREVERREWARDINFO_INFOS_FIELD
}
SYNCMAPSTEPFOREVERREWARDINFO.is_extendable = false
SYNCMAPSTEPFOREVERREWARDINFO.extensions = {}
BALANCEMODECHOOSEMESSCCMD_CMD_FIELD.name = "cmd"
BALANCEMODECHOOSEMESSCCMD_CMD_FIELD.full_name = ".Cmd.BalanceModeChooseMessCCmd.cmd"
BALANCEMODECHOOSEMESSCCMD_CMD_FIELD.number = 1
BALANCEMODECHOOSEMESSCCMD_CMD_FIELD.index = 0
BALANCEMODECHOOSEMESSCCMD_CMD_FIELD.label = 1
BALANCEMODECHOOSEMESSCCMD_CMD_FIELD.has_default_value = true
BALANCEMODECHOOSEMESSCCMD_CMD_FIELD.default_value = 83
BALANCEMODECHOOSEMESSCCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
BALANCEMODECHOOSEMESSCCMD_CMD_FIELD.type = 14
BALANCEMODECHOOSEMESSCCMD_CMD_FIELD.cpp_type = 8
BALANCEMODECHOOSEMESSCCMD_PARAM_FIELD.name = "param"
BALANCEMODECHOOSEMESSCCMD_PARAM_FIELD.full_name = ".Cmd.BalanceModeChooseMessCCmd.param"
BALANCEMODECHOOSEMESSCCMD_PARAM_FIELD.number = 2
BALANCEMODECHOOSEMESSCCMD_PARAM_FIELD.index = 1
BALANCEMODECHOOSEMESSCCMD_PARAM_FIELD.label = 1
BALANCEMODECHOOSEMESSCCMD_PARAM_FIELD.has_default_value = true
BALANCEMODECHOOSEMESSCCMD_PARAM_FIELD.default_value = 10
BALANCEMODECHOOSEMESSCCMD_PARAM_FIELD.enum_type = MESSCPARAM
BALANCEMODECHOOSEMESSCCMD_PARAM_FIELD.type = 14
BALANCEMODECHOOSEMESSCCMD_PARAM_FIELD.cpp_type = 8
BALANCEMODECHOOSEMESSCCMD_EXTRACTION_ATK_ID_FIELD.name = "extraction_atk_id"
BALANCEMODECHOOSEMESSCCMD_EXTRACTION_ATK_ID_FIELD.full_name = ".Cmd.BalanceModeChooseMessCCmd.extraction_atk_id"
BALANCEMODECHOOSEMESSCCMD_EXTRACTION_ATK_ID_FIELD.number = 3
BALANCEMODECHOOSEMESSCCMD_EXTRACTION_ATK_ID_FIELD.index = 2
BALANCEMODECHOOSEMESSCCMD_EXTRACTION_ATK_ID_FIELD.label = 1
BALANCEMODECHOOSEMESSCCMD_EXTRACTION_ATK_ID_FIELD.has_default_value = false
BALANCEMODECHOOSEMESSCCMD_EXTRACTION_ATK_ID_FIELD.default_value = 0
BALANCEMODECHOOSEMESSCCMD_EXTRACTION_ATK_ID_FIELD.type = 13
BALANCEMODECHOOSEMESSCCMD_EXTRACTION_ATK_ID_FIELD.cpp_type = 3
BALANCEMODECHOOSEMESSCCMD_EXTRACTION_DEF_ID_FIELD.name = "extraction_def_id"
BALANCEMODECHOOSEMESSCCMD_EXTRACTION_DEF_ID_FIELD.full_name = ".Cmd.BalanceModeChooseMessCCmd.extraction_def_id"
BALANCEMODECHOOSEMESSCCMD_EXTRACTION_DEF_ID_FIELD.number = 4
BALANCEMODECHOOSEMESSCCMD_EXTRACTION_DEF_ID_FIELD.index = 3
BALANCEMODECHOOSEMESSCCMD_EXTRACTION_DEF_ID_FIELD.label = 1
BALANCEMODECHOOSEMESSCCMD_EXTRACTION_DEF_ID_FIELD.has_default_value = false
BALANCEMODECHOOSEMESSCCMD_EXTRACTION_DEF_ID_FIELD.default_value = 0
BALANCEMODECHOOSEMESSCCMD_EXTRACTION_DEF_ID_FIELD.type = 13
BALANCEMODECHOOSEMESSCCMD_EXTRACTION_DEF_ID_FIELD.cpp_type = 3
BALANCEMODECHOOSEMESSCCMD_PERSONAL_ARTIFACT_ID_FIELD.name = "personal_artifact_id"
BALANCEMODECHOOSEMESSCCMD_PERSONAL_ARTIFACT_ID_FIELD.full_name = ".Cmd.BalanceModeChooseMessCCmd.personal_artifact_id"
BALANCEMODECHOOSEMESSCCMD_PERSONAL_ARTIFACT_ID_FIELD.number = 5
BALANCEMODECHOOSEMESSCCMD_PERSONAL_ARTIFACT_ID_FIELD.index = 4
BALANCEMODECHOOSEMESSCCMD_PERSONAL_ARTIFACT_ID_FIELD.label = 1
BALANCEMODECHOOSEMESSCCMD_PERSONAL_ARTIFACT_ID_FIELD.has_default_value = false
BALANCEMODECHOOSEMESSCCMD_PERSONAL_ARTIFACT_ID_FIELD.default_value = 0
BALANCEMODECHOOSEMESSCCMD_PERSONAL_ARTIFACT_ID_FIELD.type = 13
BALANCEMODECHOOSEMESSCCMD_PERSONAL_ARTIFACT_ID_FIELD.cpp_type = 3
BALANCEMODECHOOSEMESSCCMD.name = "BalanceModeChooseMessCCmd"
BALANCEMODECHOOSEMESSCCMD.full_name = ".Cmd.BalanceModeChooseMessCCmd"
BALANCEMODECHOOSEMESSCCMD.nested_types = {}
BALANCEMODECHOOSEMESSCCMD.enum_types = {}
BALANCEMODECHOOSEMESSCCMD.fields = {
  BALANCEMODECHOOSEMESSCCMD_CMD_FIELD,
  BALANCEMODECHOOSEMESSCCMD_PARAM_FIELD,
  BALANCEMODECHOOSEMESSCCMD_EXTRACTION_ATK_ID_FIELD,
  BALANCEMODECHOOSEMESSCCMD_EXTRACTION_DEF_ID_FIELD,
  BALANCEMODECHOOSEMESSCCMD_PERSONAL_ARTIFACT_ID_FIELD
}
BALANCEMODECHOOSEMESSCCMD.is_extendable = false
BALANCEMODECHOOSEMESSCCMD.extensions = {}
SETPIPPISTATEMESSCCMD_CMD_FIELD.name = "cmd"
SETPIPPISTATEMESSCCMD_CMD_FIELD.full_name = ".Cmd.SetPippiStateMessCCmd.cmd"
SETPIPPISTATEMESSCCMD_CMD_FIELD.number = 1
SETPIPPISTATEMESSCCMD_CMD_FIELD.index = 0
SETPIPPISTATEMESSCCMD_CMD_FIELD.label = 1
SETPIPPISTATEMESSCCMD_CMD_FIELD.has_default_value = true
SETPIPPISTATEMESSCCMD_CMD_FIELD.default_value = 83
SETPIPPISTATEMESSCCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
SETPIPPISTATEMESSCCMD_CMD_FIELD.type = 14
SETPIPPISTATEMESSCCMD_CMD_FIELD.cpp_type = 8
SETPIPPISTATEMESSCCMD_PARAM_FIELD.name = "param"
SETPIPPISTATEMESSCCMD_PARAM_FIELD.full_name = ".Cmd.SetPippiStateMessCCmd.param"
SETPIPPISTATEMESSCCMD_PARAM_FIELD.number = 2
SETPIPPISTATEMESSCCMD_PARAM_FIELD.index = 1
SETPIPPISTATEMESSCCMD_PARAM_FIELD.label = 1
SETPIPPISTATEMESSCCMD_PARAM_FIELD.has_default_value = true
SETPIPPISTATEMESSCCMD_PARAM_FIELD.default_value = 11
SETPIPPISTATEMESSCCMD_PARAM_FIELD.enum_type = MESSCPARAM
SETPIPPISTATEMESSCCMD_PARAM_FIELD.type = 14
SETPIPPISTATEMESSCCMD_PARAM_FIELD.cpp_type = 8
SETPIPPISTATEMESSCCMD_SUMMON_FIELD.name = "summon"
SETPIPPISTATEMESSCCMD_SUMMON_FIELD.full_name = ".Cmd.SetPippiStateMessCCmd.summon"
SETPIPPISTATEMESSCCMD_SUMMON_FIELD.number = 3
SETPIPPISTATEMESSCCMD_SUMMON_FIELD.index = 2
SETPIPPISTATEMESSCCMD_SUMMON_FIELD.label = 1
SETPIPPISTATEMESSCCMD_SUMMON_FIELD.has_default_value = false
SETPIPPISTATEMESSCCMD_SUMMON_FIELD.default_value = false
SETPIPPISTATEMESSCCMD_SUMMON_FIELD.type = 8
SETPIPPISTATEMESSCCMD_SUMMON_FIELD.cpp_type = 7
SETPIPPISTATEMESSCCMD_TIME_FIELD.name = "time"
SETPIPPISTATEMESSCCMD_TIME_FIELD.full_name = ".Cmd.SetPippiStateMessCCmd.time"
SETPIPPISTATEMESSCCMD_TIME_FIELD.number = 4
SETPIPPISTATEMESSCCMD_TIME_FIELD.index = 3
SETPIPPISTATEMESSCCMD_TIME_FIELD.label = 1
SETPIPPISTATEMESSCCMD_TIME_FIELD.has_default_value = false
SETPIPPISTATEMESSCCMD_TIME_FIELD.default_value = 0
SETPIPPISTATEMESSCCMD_TIME_FIELD.type = 13
SETPIPPISTATEMESSCCMD_TIME_FIELD.cpp_type = 3
SETPIPPISTATEMESSCCMD_STATE_FIELD.name = "state"
SETPIPPISTATEMESSCCMD_STATE_FIELD.full_name = ".Cmd.SetPippiStateMessCCmd.state"
SETPIPPISTATEMESSCCMD_STATE_FIELD.number = 5
SETPIPPISTATEMESSCCMD_STATE_FIELD.index = 4
SETPIPPISTATEMESSCCMD_STATE_FIELD.label = 1
SETPIPPISTATEMESSCCMD_STATE_FIELD.has_default_value = false
SETPIPPISTATEMESSCCMD_STATE_FIELD.default_value = nil
SETPIPPISTATEMESSCCMD_STATE_FIELD.enum_type = EPIPPISTATE
SETPIPPISTATEMESSCCMD_STATE_FIELD.type = 14
SETPIPPISTATEMESSCCMD_STATE_FIELD.cpp_type = 8
SETPIPPISTATEMESSCCMD.name = "SetPippiStateMessCCmd"
SETPIPPISTATEMESSCCMD.full_name = ".Cmd.SetPippiStateMessCCmd"
SETPIPPISTATEMESSCCMD.nested_types = {}
SETPIPPISTATEMESSCCMD.enum_types = {}
SETPIPPISTATEMESSCCMD.fields = {
  SETPIPPISTATEMESSCCMD_CMD_FIELD,
  SETPIPPISTATEMESSCCMD_PARAM_FIELD,
  SETPIPPISTATEMESSCCMD_SUMMON_FIELD,
  SETPIPPISTATEMESSCCMD_TIME_FIELD,
  SETPIPPISTATEMESSCCMD_STATE_FIELD
}
SETPIPPISTATEMESSCCMD.is_extendable = false
SETPIPPISTATEMESSCCMD.extensions = {}
GRAPHPOINTINFO_POINT_FIELD.name = "point"
GRAPHPOINTINFO_POINT_FIELD.full_name = ".Cmd.GraphPointInfo.point"
GRAPHPOINTINFO_POINT_FIELD.number = 1
GRAPHPOINTINFO_POINT_FIELD.index = 0
GRAPHPOINTINFO_POINT_FIELD.label = 1
GRAPHPOINTINFO_POINT_FIELD.has_default_value = false
GRAPHPOINTINFO_POINT_FIELD.default_value = 0
GRAPHPOINTINFO_POINT_FIELD.type = 13
GRAPHPOINTINFO_POINT_FIELD.cpp_type = 3
GRAPHPOINTINFO_STATE_FIELD.name = "state"
GRAPHPOINTINFO_STATE_FIELD.full_name = ".Cmd.GraphPointInfo.state"
GRAPHPOINTINFO_STATE_FIELD.number = 2
GRAPHPOINTINFO_STATE_FIELD.index = 1
GRAPHPOINTINFO_STATE_FIELD.label = 1
GRAPHPOINTINFO_STATE_FIELD.has_default_value = false
GRAPHPOINTINFO_STATE_FIELD.default_value = nil
GRAPHPOINTINFO_STATE_FIELD.enum_type = EGRAPHPOINTSTATE
GRAPHPOINTINFO_STATE_FIELD.type = 14
GRAPHPOINTINFO_STATE_FIELD.cpp_type = 8
GRAPHPOINTINFO.name = "GraphPointInfo"
GRAPHPOINTINFO.full_name = ".Cmd.GraphPointInfo"
GRAPHPOINTINFO.nested_types = {}
GRAPHPOINTINFO.enum_types = {}
GRAPHPOINTINFO.fields = {
  GRAPHPOINTINFO_POINT_FIELD,
  GRAPHPOINTINFO_STATE_FIELD
}
GRAPHPOINTINFO.is_extendable = false
GRAPHPOINTINFO.extensions = {}
DESTINYGRAPHINFO_SEASON_FIELD.name = "season"
DESTINYGRAPHINFO_SEASON_FIELD.full_name = ".Cmd.DestinyGraphInfo.season"
DESTINYGRAPHINFO_SEASON_FIELD.number = 1
DESTINYGRAPHINFO_SEASON_FIELD.index = 0
DESTINYGRAPHINFO_SEASON_FIELD.label = 1
DESTINYGRAPHINFO_SEASON_FIELD.has_default_value = false
DESTINYGRAPHINFO_SEASON_FIELD.default_value = 0
DESTINYGRAPHINFO_SEASON_FIELD.type = 13
DESTINYGRAPHINFO_SEASON_FIELD.cpp_type = 3
DESTINYGRAPHINFO_POINTINFOS_FIELD.name = "pointinfos"
DESTINYGRAPHINFO_POINTINFOS_FIELD.full_name = ".Cmd.DestinyGraphInfo.pointinfos"
DESTINYGRAPHINFO_POINTINFOS_FIELD.number = 2
DESTINYGRAPHINFO_POINTINFOS_FIELD.index = 1
DESTINYGRAPHINFO_POINTINFOS_FIELD.label = 3
DESTINYGRAPHINFO_POINTINFOS_FIELD.has_default_value = false
DESTINYGRAPHINFO_POINTINFOS_FIELD.default_value = {}
DESTINYGRAPHINFO_POINTINFOS_FIELD.message_type = GRAPHPOINTINFO
DESTINYGRAPHINFO_POINTINFOS_FIELD.type = 11
DESTINYGRAPHINFO_POINTINFOS_FIELD.cpp_type = 10
DESTINYGRAPHINFO.name = "DestinyGraphInfo"
DESTINYGRAPHINFO.full_name = ".Cmd.DestinyGraphInfo"
DESTINYGRAPHINFO.nested_types = {}
DESTINYGRAPHINFO.enum_types = {}
DESTINYGRAPHINFO.fields = {
  DESTINYGRAPHINFO_SEASON_FIELD,
  DESTINYGRAPHINFO_POINTINFOS_FIELD
}
DESTINYGRAPHINFO.is_extendable = false
DESTINYGRAPHINFO.extensions = {}
SYNCDESTINYGRAPHMESSCCMD_CMD_FIELD.name = "cmd"
SYNCDESTINYGRAPHMESSCCMD_CMD_FIELD.full_name = ".Cmd.SyncDestinyGraphMessCCmd.cmd"
SYNCDESTINYGRAPHMESSCCMD_CMD_FIELD.number = 1
SYNCDESTINYGRAPHMESSCCMD_CMD_FIELD.index = 0
SYNCDESTINYGRAPHMESSCCMD_CMD_FIELD.label = 1
SYNCDESTINYGRAPHMESSCCMD_CMD_FIELD.has_default_value = true
SYNCDESTINYGRAPHMESSCCMD_CMD_FIELD.default_value = 83
SYNCDESTINYGRAPHMESSCCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
SYNCDESTINYGRAPHMESSCCMD_CMD_FIELD.type = 14
SYNCDESTINYGRAPHMESSCCMD_CMD_FIELD.cpp_type = 8
SYNCDESTINYGRAPHMESSCCMD_PARAM_FIELD.name = "param"
SYNCDESTINYGRAPHMESSCCMD_PARAM_FIELD.full_name = ".Cmd.SyncDestinyGraphMessCCmd.param"
SYNCDESTINYGRAPHMESSCCMD_PARAM_FIELD.number = 2
SYNCDESTINYGRAPHMESSCCMD_PARAM_FIELD.index = 1
SYNCDESTINYGRAPHMESSCCMD_PARAM_FIELD.label = 1
SYNCDESTINYGRAPHMESSCCMD_PARAM_FIELD.has_default_value = true
SYNCDESTINYGRAPHMESSCCMD_PARAM_FIELD.default_value = 12
SYNCDESTINYGRAPHMESSCCMD_PARAM_FIELD.enum_type = MESSCPARAM
SYNCDESTINYGRAPHMESSCCMD_PARAM_FIELD.type = 14
SYNCDESTINYGRAPHMESSCCMD_PARAM_FIELD.cpp_type = 8
SYNCDESTINYGRAPHMESSCCMD_GRAPHINFOS_FIELD.name = "graphinfos"
SYNCDESTINYGRAPHMESSCCMD_GRAPHINFOS_FIELD.full_name = ".Cmd.SyncDestinyGraphMessCCmd.graphinfos"
SYNCDESTINYGRAPHMESSCCMD_GRAPHINFOS_FIELD.number = 3
SYNCDESTINYGRAPHMESSCCMD_GRAPHINFOS_FIELD.index = 2
SYNCDESTINYGRAPHMESSCCMD_GRAPHINFOS_FIELD.label = 3
SYNCDESTINYGRAPHMESSCCMD_GRAPHINFOS_FIELD.has_default_value = false
SYNCDESTINYGRAPHMESSCCMD_GRAPHINFOS_FIELD.default_value = {}
SYNCDESTINYGRAPHMESSCCMD_GRAPHINFOS_FIELD.message_type = DESTINYGRAPHINFO
SYNCDESTINYGRAPHMESSCCMD_GRAPHINFOS_FIELD.type = 11
SYNCDESTINYGRAPHMESSCCMD_GRAPHINFOS_FIELD.cpp_type = 10
SYNCDESTINYGRAPHMESSCCMD_CURSEASON_FIELD.name = "curseason"
SYNCDESTINYGRAPHMESSCCMD_CURSEASON_FIELD.full_name = ".Cmd.SyncDestinyGraphMessCCmd.curseason"
SYNCDESTINYGRAPHMESSCCMD_CURSEASON_FIELD.number = 4
SYNCDESTINYGRAPHMESSCCMD_CURSEASON_FIELD.index = 3
SYNCDESTINYGRAPHMESSCCMD_CURSEASON_FIELD.label = 1
SYNCDESTINYGRAPHMESSCCMD_CURSEASON_FIELD.has_default_value = false
SYNCDESTINYGRAPHMESSCCMD_CURSEASON_FIELD.default_value = 0
SYNCDESTINYGRAPHMESSCCMD_CURSEASON_FIELD.type = 13
SYNCDESTINYGRAPHMESSCCMD_CURSEASON_FIELD.cpp_type = 3
SYNCDESTINYGRAPHMESSCCMD.name = "SyncDestinyGraphMessCCmd"
SYNCDESTINYGRAPHMESSCCMD.full_name = ".Cmd.SyncDestinyGraphMessCCmd"
SYNCDESTINYGRAPHMESSCCMD.nested_types = {}
SYNCDESTINYGRAPHMESSCCMD.enum_types = {}
SYNCDESTINYGRAPHMESSCCMD.fields = {
  SYNCDESTINYGRAPHMESSCCMD_CMD_FIELD,
  SYNCDESTINYGRAPHMESSCCMD_PARAM_FIELD,
  SYNCDESTINYGRAPHMESSCCMD_GRAPHINFOS_FIELD,
  SYNCDESTINYGRAPHMESSCCMD_CURSEASON_FIELD
}
SYNCDESTINYGRAPHMESSCCMD.is_extendable = false
SYNCDESTINYGRAPHMESSCCMD.extensions = {}
LIGHTENDESTINYGRAPHMESSCCMD_CMD_FIELD.name = "cmd"
LIGHTENDESTINYGRAPHMESSCCMD_CMD_FIELD.full_name = ".Cmd.LightenDestinyGraphMessCCmd.cmd"
LIGHTENDESTINYGRAPHMESSCCMD_CMD_FIELD.number = 1
LIGHTENDESTINYGRAPHMESSCCMD_CMD_FIELD.index = 0
LIGHTENDESTINYGRAPHMESSCCMD_CMD_FIELD.label = 1
LIGHTENDESTINYGRAPHMESSCCMD_CMD_FIELD.has_default_value = true
LIGHTENDESTINYGRAPHMESSCCMD_CMD_FIELD.default_value = 83
LIGHTENDESTINYGRAPHMESSCCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
LIGHTENDESTINYGRAPHMESSCCMD_CMD_FIELD.type = 14
LIGHTENDESTINYGRAPHMESSCCMD_CMD_FIELD.cpp_type = 8
LIGHTENDESTINYGRAPHMESSCCMD_PARAM_FIELD.name = "param"
LIGHTENDESTINYGRAPHMESSCCMD_PARAM_FIELD.full_name = ".Cmd.LightenDestinyGraphMessCCmd.param"
LIGHTENDESTINYGRAPHMESSCCMD_PARAM_FIELD.number = 2
LIGHTENDESTINYGRAPHMESSCCMD_PARAM_FIELD.index = 1
LIGHTENDESTINYGRAPHMESSCCMD_PARAM_FIELD.label = 1
LIGHTENDESTINYGRAPHMESSCCMD_PARAM_FIELD.has_default_value = true
LIGHTENDESTINYGRAPHMESSCCMD_PARAM_FIELD.default_value = 13
LIGHTENDESTINYGRAPHMESSCCMD_PARAM_FIELD.enum_type = MESSCPARAM
LIGHTENDESTINYGRAPHMESSCCMD_PARAM_FIELD.type = 14
LIGHTENDESTINYGRAPHMESSCCMD_PARAM_FIELD.cpp_type = 8
LIGHTENDESTINYGRAPHMESSCCMD_SEASON_FIELD.name = "season"
LIGHTENDESTINYGRAPHMESSCCMD_SEASON_FIELD.full_name = ".Cmd.LightenDestinyGraphMessCCmd.season"
LIGHTENDESTINYGRAPHMESSCCMD_SEASON_FIELD.number = 3
LIGHTENDESTINYGRAPHMESSCCMD_SEASON_FIELD.index = 2
LIGHTENDESTINYGRAPHMESSCCMD_SEASON_FIELD.label = 1
LIGHTENDESTINYGRAPHMESSCCMD_SEASON_FIELD.has_default_value = false
LIGHTENDESTINYGRAPHMESSCCMD_SEASON_FIELD.default_value = 0
LIGHTENDESTINYGRAPHMESSCCMD_SEASON_FIELD.type = 13
LIGHTENDESTINYGRAPHMESSCCMD_SEASON_FIELD.cpp_type = 3
LIGHTENDESTINYGRAPHMESSCCMD_POINT_FIELD.name = "point"
LIGHTENDESTINYGRAPHMESSCCMD_POINT_FIELD.full_name = ".Cmd.LightenDestinyGraphMessCCmd.point"
LIGHTENDESTINYGRAPHMESSCCMD_POINT_FIELD.number = 4
LIGHTENDESTINYGRAPHMESSCCMD_POINT_FIELD.index = 3
LIGHTENDESTINYGRAPHMESSCCMD_POINT_FIELD.label = 1
LIGHTENDESTINYGRAPHMESSCCMD_POINT_FIELD.has_default_value = false
LIGHTENDESTINYGRAPHMESSCCMD_POINT_FIELD.default_value = 0
LIGHTENDESTINYGRAPHMESSCCMD_POINT_FIELD.type = 13
LIGHTENDESTINYGRAPHMESSCCMD_POINT_FIELD.cpp_type = 3
LIGHTENDESTINYGRAPHMESSCCMD.name = "LightenDestinyGraphMessCCmd"
LIGHTENDESTINYGRAPHMESSCCMD.full_name = ".Cmd.LightenDestinyGraphMessCCmd"
LIGHTENDESTINYGRAPHMESSCCMD.nested_types = {}
LIGHTENDESTINYGRAPHMESSCCMD.enum_types = {}
LIGHTENDESTINYGRAPHMESSCCMD.fields = {
  LIGHTENDESTINYGRAPHMESSCCMD_CMD_FIELD,
  LIGHTENDESTINYGRAPHMESSCCMD_PARAM_FIELD,
  LIGHTENDESTINYGRAPHMESSCCMD_SEASON_FIELD,
  LIGHTENDESTINYGRAPHMESSCCMD_POINT_FIELD
}
LIGHTENDESTINYGRAPHMESSCCMD.is_extendable = false
LIGHTENDESTINYGRAPHMESSCCMD.extensions = {}
ASTRALREWARDMESSCCMD_CMD_FIELD.name = "cmd"
ASTRALREWARDMESSCCMD_CMD_FIELD.full_name = ".Cmd.AstralRewardMessCCmd.cmd"
ASTRALREWARDMESSCCMD_CMD_FIELD.number = 1
ASTRALREWARDMESSCCMD_CMD_FIELD.index = 0
ASTRALREWARDMESSCCMD_CMD_FIELD.label = 1
ASTRALREWARDMESSCCMD_CMD_FIELD.has_default_value = true
ASTRALREWARDMESSCCMD_CMD_FIELD.default_value = 83
ASTRALREWARDMESSCCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
ASTRALREWARDMESSCCMD_CMD_FIELD.type = 14
ASTRALREWARDMESSCCMD_CMD_FIELD.cpp_type = 8
ASTRALREWARDMESSCCMD_PARAM_FIELD.name = "param"
ASTRALREWARDMESSCCMD_PARAM_FIELD.full_name = ".Cmd.AstralRewardMessCCmd.param"
ASTRALREWARDMESSCCMD_PARAM_FIELD.number = 2
ASTRALREWARDMESSCCMD_PARAM_FIELD.index = 1
ASTRALREWARDMESSCCMD_PARAM_FIELD.label = 1
ASTRALREWARDMESSCCMD_PARAM_FIELD.has_default_value = true
ASTRALREWARDMESSCCMD_PARAM_FIELD.default_value = 14
ASTRALREWARDMESSCCMD_PARAM_FIELD.enum_type = MESSCPARAM
ASTRALREWARDMESSCCMD_PARAM_FIELD.type = 14
ASTRALREWARDMESSCCMD_PARAM_FIELD.cpp_type = 8
ASTRALREWARDMESSCCMD_SEASON_FIELD.name = "season"
ASTRALREWARDMESSCCMD_SEASON_FIELD.full_name = ".Cmd.AstralRewardMessCCmd.season"
ASTRALREWARDMESSCCMD_SEASON_FIELD.number = 3
ASTRALREWARDMESSCCMD_SEASON_FIELD.index = 2
ASTRALREWARDMESSCCMD_SEASON_FIELD.label = 1
ASTRALREWARDMESSCCMD_SEASON_FIELD.has_default_value = false
ASTRALREWARDMESSCCMD_SEASON_FIELD.default_value = 0
ASTRALREWARDMESSCCMD_SEASON_FIELD.type = 13
ASTRALREWARDMESSCCMD_SEASON_FIELD.cpp_type = 3
ASTRALREWARDMESSCCMD_PASS_NUM_FIELD.name = "pass_num"
ASTRALREWARDMESSCCMD_PASS_NUM_FIELD.full_name = ".Cmd.AstralRewardMessCCmd.pass_num"
ASTRALREWARDMESSCCMD_PASS_NUM_FIELD.number = 4
ASTRALREWARDMESSCCMD_PASS_NUM_FIELD.index = 3
ASTRALREWARDMESSCCMD_PASS_NUM_FIELD.label = 1
ASTRALREWARDMESSCCMD_PASS_NUM_FIELD.has_default_value = false
ASTRALREWARDMESSCCMD_PASS_NUM_FIELD.default_value = 0
ASTRALREWARDMESSCCMD_PASS_NUM_FIELD.type = 13
ASTRALREWARDMESSCCMD_PASS_NUM_FIELD.cpp_type = 3
ASTRALREWARDMESSCCMD.name = "AstralRewardMessCCmd"
ASTRALREWARDMESSCCMD.full_name = ".Cmd.AstralRewardMessCCmd"
ASTRALREWARDMESSCCMD.nested_types = {}
ASTRALREWARDMESSCCMD.enum_types = {}
ASTRALREWARDMESSCCMD.fields = {
  ASTRALREWARDMESSCCMD_CMD_FIELD,
  ASTRALREWARDMESSCCMD_PARAM_FIELD,
  ASTRALREWARDMESSCCMD_SEASON_FIELD,
  ASTRALREWARDMESSCCMD_PASS_NUM_FIELD
}
ASTRALREWARDMESSCCMD.is_extendable = false
ASTRALREWARDMESSCCMD.extensions = {}
PURIFYMATERIALS_ITEMID_FIELD.name = "itemid"
PURIFYMATERIALS_ITEMID_FIELD.full_name = ".Cmd.PurifyMaterials.itemid"
PURIFYMATERIALS_ITEMID_FIELD.number = 1
PURIFYMATERIALS_ITEMID_FIELD.index = 0
PURIFYMATERIALS_ITEMID_FIELD.label = 1
PURIFYMATERIALS_ITEMID_FIELD.has_default_value = false
PURIFYMATERIALS_ITEMID_FIELD.default_value = 0
PURIFYMATERIALS_ITEMID_FIELD.type = 13
PURIFYMATERIALS_ITEMID_FIELD.cpp_type = 3
PURIFYMATERIALS_NUM_FIELD.name = "num"
PURIFYMATERIALS_NUM_FIELD.full_name = ".Cmd.PurifyMaterials.num"
PURIFYMATERIALS_NUM_FIELD.number = 2
PURIFYMATERIALS_NUM_FIELD.index = 1
PURIFYMATERIALS_NUM_FIELD.label = 1
PURIFYMATERIALS_NUM_FIELD.has_default_value = false
PURIFYMATERIALS_NUM_FIELD.default_value = 0
PURIFYMATERIALS_NUM_FIELD.type = 13
PURIFYMATERIALS_NUM_FIELD.cpp_type = 3
PURIFYMATERIALS.name = "PurifyMaterials"
PURIFYMATERIALS.full_name = ".Cmd.PurifyMaterials"
PURIFYMATERIALS.nested_types = {}
PURIFYMATERIALS.enum_types = {}
PURIFYMATERIALS.fields = {
  PURIFYMATERIALS_ITEMID_FIELD,
  PURIFYMATERIALS_NUM_FIELD
}
PURIFYMATERIALS.is_extendable = false
PURIFYMATERIALS.extensions = {}
PURIFYTIMES_TYPE_FIELD.name = "type"
PURIFYTIMES_TYPE_FIELD.full_name = ".Cmd.PurifyTimes.type"
PURIFYTIMES_TYPE_FIELD.number = 1
PURIFYTIMES_TYPE_FIELD.index = 0
PURIFYTIMES_TYPE_FIELD.label = 1
PURIFYTIMES_TYPE_FIELD.has_default_value = false
PURIFYTIMES_TYPE_FIELD.default_value = ""
PURIFYTIMES_TYPE_FIELD.type = 9
PURIFYTIMES_TYPE_FIELD.cpp_type = 9
PURIFYTIMES_TOTALTIMES_FIELD.name = "totaltimes"
PURIFYTIMES_TOTALTIMES_FIELD.full_name = ".Cmd.PurifyTimes.totaltimes"
PURIFYTIMES_TOTALTIMES_FIELD.number = 2
PURIFYTIMES_TOTALTIMES_FIELD.index = 1
PURIFYTIMES_TOTALTIMES_FIELD.label = 1
PURIFYTIMES_TOTALTIMES_FIELD.has_default_value = false
PURIFYTIMES_TOTALTIMES_FIELD.default_value = 0
PURIFYTIMES_TOTALTIMES_FIELD.type = 13
PURIFYTIMES_TOTALTIMES_FIELD.cpp_type = 3
PURIFYTIMES_LEFTTIMES_FIELD.name = "lefttimes"
PURIFYTIMES_LEFTTIMES_FIELD.full_name = ".Cmd.PurifyTimes.lefttimes"
PURIFYTIMES_LEFTTIMES_FIELD.number = 3
PURIFYTIMES_LEFTTIMES_FIELD.index = 2
PURIFYTIMES_LEFTTIMES_FIELD.label = 1
PURIFYTIMES_LEFTTIMES_FIELD.has_default_value = false
PURIFYTIMES_LEFTTIMES_FIELD.default_value = 0
PURIFYTIMES_LEFTTIMES_FIELD.type = 13
PURIFYTIMES_LEFTTIMES_FIELD.cpp_type = 3
PURIFYTIMES.name = "PurifyTimes"
PURIFYTIMES.full_name = ".Cmd.PurifyTimes"
PURIFYTIMES.nested_types = {}
PURIFYTIMES.enum_types = {}
PURIFYTIMES.fields = {
  PURIFYTIMES_TYPE_FIELD,
  PURIFYTIMES_TOTALTIMES_FIELD,
  PURIFYTIMES_LEFTTIMES_FIELD
}
PURIFYTIMES.is_extendable = false
PURIFYTIMES.extensions = {}
PURIFYPRODUCTS_PRODUCTID_FIELD.name = "productid"
PURIFYPRODUCTS_PRODUCTID_FIELD.full_name = ".Cmd.PurifyProducts.productid"
PURIFYPRODUCTS_PRODUCTID_FIELD.number = 1
PURIFYPRODUCTS_PRODUCTID_FIELD.index = 0
PURIFYPRODUCTS_PRODUCTID_FIELD.label = 1
PURIFYPRODUCTS_PRODUCTID_FIELD.has_default_value = false
PURIFYPRODUCTS_PRODUCTID_FIELD.default_value = 0
PURIFYPRODUCTS_PRODUCTID_FIELD.type = 13
PURIFYPRODUCTS_PRODUCTID_FIELD.cpp_type = 3
PURIFYPRODUCTS_MATERIALS_FIELD.name = "materials"
PURIFYPRODUCTS_MATERIALS_FIELD.full_name = ".Cmd.PurifyProducts.materials"
PURIFYPRODUCTS_MATERIALS_FIELD.number = 2
PURIFYPRODUCTS_MATERIALS_FIELD.index = 1
PURIFYPRODUCTS_MATERIALS_FIELD.label = 3
PURIFYPRODUCTS_MATERIALS_FIELD.has_default_value = false
PURIFYPRODUCTS_MATERIALS_FIELD.default_value = {}
PURIFYPRODUCTS_MATERIALS_FIELD.message_type = PURIFYMATERIALS
PURIFYPRODUCTS_MATERIALS_FIELD.type = 11
PURIFYPRODUCTS_MATERIALS_FIELD.cpp_type = 10
PURIFYPRODUCTS_TIMES_FIELD.name = "times"
PURIFYPRODUCTS_TIMES_FIELD.full_name = ".Cmd.PurifyProducts.times"
PURIFYPRODUCTS_TIMES_FIELD.number = 3
PURIFYPRODUCTS_TIMES_FIELD.index = 2
PURIFYPRODUCTS_TIMES_FIELD.label = 1
PURIFYPRODUCTS_TIMES_FIELD.has_default_value = false
PURIFYPRODUCTS_TIMES_FIELD.default_value = nil
PURIFYPRODUCTS_TIMES_FIELD.message_type = PURIFYTIMES
PURIFYPRODUCTS_TIMES_FIELD.type = 11
PURIFYPRODUCTS_TIMES_FIELD.cpp_type = 10
PURIFYPRODUCTS_NEWMARK_FIELD.name = "newmark"
PURIFYPRODUCTS_NEWMARK_FIELD.full_name = ".Cmd.PurifyProducts.newmark"
PURIFYPRODUCTS_NEWMARK_FIELD.number = 4
PURIFYPRODUCTS_NEWMARK_FIELD.index = 3
PURIFYPRODUCTS_NEWMARK_FIELD.label = 1
PURIFYPRODUCTS_NEWMARK_FIELD.has_default_value = false
PURIFYPRODUCTS_NEWMARK_FIELD.default_value = false
PURIFYPRODUCTS_NEWMARK_FIELD.type = 8
PURIFYPRODUCTS_NEWMARK_FIELD.cpp_type = 7
PURIFYPRODUCTS_CLOSE_FIELD.name = "close"
PURIFYPRODUCTS_CLOSE_FIELD.full_name = ".Cmd.PurifyProducts.close"
PURIFYPRODUCTS_CLOSE_FIELD.number = 5
PURIFYPRODUCTS_CLOSE_FIELD.index = 4
PURIFYPRODUCTS_CLOSE_FIELD.label = 1
PURIFYPRODUCTS_CLOSE_FIELD.has_default_value = false
PURIFYPRODUCTS_CLOSE_FIELD.default_value = false
PURIFYPRODUCTS_CLOSE_FIELD.type = 8
PURIFYPRODUCTS_CLOSE_FIELD.cpp_type = 7
PURIFYPRODUCTS_CONFIRM_FIELD.name = "confirm"
PURIFYPRODUCTS_CONFIRM_FIELD.full_name = ".Cmd.PurifyProducts.confirm"
PURIFYPRODUCTS_CONFIRM_FIELD.number = 6
PURIFYPRODUCTS_CONFIRM_FIELD.index = 5
PURIFYPRODUCTS_CONFIRM_FIELD.label = 1
PURIFYPRODUCTS_CONFIRM_FIELD.has_default_value = false
PURIFYPRODUCTS_CONFIRM_FIELD.default_value = false
PURIFYPRODUCTS_CONFIRM_FIELD.type = 8
PURIFYPRODUCTS_CONFIRM_FIELD.cpp_type = 7
PURIFYPRODUCTS.name = "PurifyProducts"
PURIFYPRODUCTS.full_name = ".Cmd.PurifyProducts"
PURIFYPRODUCTS.nested_types = {}
PURIFYPRODUCTS.enum_types = {}
PURIFYPRODUCTS.fields = {
  PURIFYPRODUCTS_PRODUCTID_FIELD,
  PURIFYPRODUCTS_MATERIALS_FIELD,
  PURIFYPRODUCTS_TIMES_FIELD,
  PURIFYPRODUCTS_NEWMARK_FIELD,
  PURIFYPRODUCTS_CLOSE_FIELD,
  PURIFYPRODUCTS_CONFIRM_FIELD
}
PURIFYPRODUCTS.is_extendable = false
PURIFYPRODUCTS.extensions = {}
PURIFYPRODUCTSMATERIALSMESSCCMD_CMD_FIELD.name = "cmd"
PURIFYPRODUCTSMATERIALSMESSCCMD_CMD_FIELD.full_name = ".Cmd.PurifyProductsMaterialsMessCCmd.cmd"
PURIFYPRODUCTSMATERIALSMESSCCMD_CMD_FIELD.number = 1
PURIFYPRODUCTSMATERIALSMESSCCMD_CMD_FIELD.index = 0
PURIFYPRODUCTSMATERIALSMESSCCMD_CMD_FIELD.label = 1
PURIFYPRODUCTSMATERIALSMESSCCMD_CMD_FIELD.has_default_value = true
PURIFYPRODUCTSMATERIALSMESSCCMD_CMD_FIELD.default_value = 83
PURIFYPRODUCTSMATERIALSMESSCCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
PURIFYPRODUCTSMATERIALSMESSCCMD_CMD_FIELD.type = 14
PURIFYPRODUCTSMATERIALSMESSCCMD_CMD_FIELD.cpp_type = 8
PURIFYPRODUCTSMATERIALSMESSCCMD_PARAM_FIELD.name = "param"
PURIFYPRODUCTSMATERIALSMESSCCMD_PARAM_FIELD.full_name = ".Cmd.PurifyProductsMaterialsMessCCmd.param"
PURIFYPRODUCTSMATERIALSMESSCCMD_PARAM_FIELD.number = 2
PURIFYPRODUCTSMATERIALSMESSCCMD_PARAM_FIELD.index = 1
PURIFYPRODUCTSMATERIALSMESSCCMD_PARAM_FIELD.label = 1
PURIFYPRODUCTSMATERIALSMESSCCMD_PARAM_FIELD.has_default_value = true
PURIFYPRODUCTSMATERIALSMESSCCMD_PARAM_FIELD.default_value = 15
PURIFYPRODUCTSMATERIALSMESSCCMD_PARAM_FIELD.enum_type = MESSCPARAM
PURIFYPRODUCTSMATERIALSMESSCCMD_PARAM_FIELD.type = 14
PURIFYPRODUCTSMATERIALSMESSCCMD_PARAM_FIELD.cpp_type = 8
PURIFYPRODUCTSMATERIALSMESSCCMD_MATERIALS_FIELD.name = "materials"
PURIFYPRODUCTSMATERIALSMESSCCMD_MATERIALS_FIELD.full_name = ".Cmd.PurifyProductsMaterialsMessCCmd.materials"
PURIFYPRODUCTSMATERIALSMESSCCMD_MATERIALS_FIELD.number = 3
PURIFYPRODUCTSMATERIALSMESSCCMD_MATERIALS_FIELD.index = 2
PURIFYPRODUCTSMATERIALSMESSCCMD_MATERIALS_FIELD.label = 3
PURIFYPRODUCTSMATERIALSMESSCCMD_MATERIALS_FIELD.has_default_value = false
PURIFYPRODUCTSMATERIALSMESSCCMD_MATERIALS_FIELD.default_value = {}
PURIFYPRODUCTSMATERIALSMESSCCMD_MATERIALS_FIELD.message_type = PURIFYPRODUCTS
PURIFYPRODUCTSMATERIALSMESSCCMD_MATERIALS_FIELD.type = 11
PURIFYPRODUCTSMATERIALSMESSCCMD_MATERIALS_FIELD.cpp_type = 10
PURIFYPRODUCTSMATERIALSMESSCCMD.name = "PurifyProductsMaterialsMessCCmd"
PURIFYPRODUCTSMATERIALSMESSCCMD.full_name = ".Cmd.PurifyProductsMaterialsMessCCmd"
PURIFYPRODUCTSMATERIALSMESSCCMD.nested_types = {}
PURIFYPRODUCTSMATERIALSMESSCCMD.enum_types = {}
PURIFYPRODUCTSMATERIALSMESSCCMD.fields = {
  PURIFYPRODUCTSMATERIALSMESSCCMD_CMD_FIELD,
  PURIFYPRODUCTSMATERIALSMESSCCMD_PARAM_FIELD,
  PURIFYPRODUCTSMATERIALSMESSCCMD_MATERIALS_FIELD
}
PURIFYPRODUCTSMATERIALSMESSCCMD.is_extendable = false
PURIFYPRODUCTSMATERIALSMESSCCMD.extensions = {}
PURIFYPRODUCTSREFINEMESSCCMD_CMD_FIELD.name = "cmd"
PURIFYPRODUCTSREFINEMESSCCMD_CMD_FIELD.full_name = ".Cmd.PurifyProductsRefineMessCCmd.cmd"
PURIFYPRODUCTSREFINEMESSCCMD_CMD_FIELD.number = 1
PURIFYPRODUCTSREFINEMESSCCMD_CMD_FIELD.index = 0
PURIFYPRODUCTSREFINEMESSCCMD_CMD_FIELD.label = 1
PURIFYPRODUCTSREFINEMESSCCMD_CMD_FIELD.has_default_value = true
PURIFYPRODUCTSREFINEMESSCCMD_CMD_FIELD.default_value = 83
PURIFYPRODUCTSREFINEMESSCCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
PURIFYPRODUCTSREFINEMESSCCMD_CMD_FIELD.type = 14
PURIFYPRODUCTSREFINEMESSCCMD_CMD_FIELD.cpp_type = 8
PURIFYPRODUCTSREFINEMESSCCMD_PARAM_FIELD.name = "param"
PURIFYPRODUCTSREFINEMESSCCMD_PARAM_FIELD.full_name = ".Cmd.PurifyProductsRefineMessCCmd.param"
PURIFYPRODUCTSREFINEMESSCCMD_PARAM_FIELD.number = 2
PURIFYPRODUCTSREFINEMESSCCMD_PARAM_FIELD.index = 1
PURIFYPRODUCTSREFINEMESSCCMD_PARAM_FIELD.label = 1
PURIFYPRODUCTSREFINEMESSCCMD_PARAM_FIELD.has_default_value = true
PURIFYPRODUCTSREFINEMESSCCMD_PARAM_FIELD.default_value = 16
PURIFYPRODUCTSREFINEMESSCCMD_PARAM_FIELD.enum_type = MESSCPARAM
PURIFYPRODUCTSREFINEMESSCCMD_PARAM_FIELD.type = 14
PURIFYPRODUCTSREFINEMESSCCMD_PARAM_FIELD.cpp_type = 8
PURIFYPRODUCTSREFINEMESSCCMD_PRODUCTID_FIELD.name = "productid"
PURIFYPRODUCTSREFINEMESSCCMD_PRODUCTID_FIELD.full_name = ".Cmd.PurifyProductsRefineMessCCmd.productid"
PURIFYPRODUCTSREFINEMESSCCMD_PRODUCTID_FIELD.number = 3
PURIFYPRODUCTSREFINEMESSCCMD_PRODUCTID_FIELD.index = 2
PURIFYPRODUCTSREFINEMESSCCMD_PRODUCTID_FIELD.label = 1
PURIFYPRODUCTSREFINEMESSCCMD_PRODUCTID_FIELD.has_default_value = false
PURIFYPRODUCTSREFINEMESSCCMD_PRODUCTID_FIELD.default_value = 0
PURIFYPRODUCTSREFINEMESSCCMD_PRODUCTID_FIELD.type = 13
PURIFYPRODUCTSREFINEMESSCCMD_PRODUCTID_FIELD.cpp_type = 3
PURIFYPRODUCTSREFINEMESSCCMD_TIMES_FIELD.name = "times"
PURIFYPRODUCTSREFINEMESSCCMD_TIMES_FIELD.full_name = ".Cmd.PurifyProductsRefineMessCCmd.times"
PURIFYPRODUCTSREFINEMESSCCMD_TIMES_FIELD.number = 4
PURIFYPRODUCTSREFINEMESSCCMD_TIMES_FIELD.index = 3
PURIFYPRODUCTSREFINEMESSCCMD_TIMES_FIELD.label = 1
PURIFYPRODUCTSREFINEMESSCCMD_TIMES_FIELD.has_default_value = false
PURIFYPRODUCTSREFINEMESSCCMD_TIMES_FIELD.default_value = 0
PURIFYPRODUCTSREFINEMESSCCMD_TIMES_FIELD.type = 13
PURIFYPRODUCTSREFINEMESSCCMD_TIMES_FIELD.cpp_type = 3
PURIFYPRODUCTSREFINEMESSCCMD.name = "PurifyProductsRefineMessCCmd"
PURIFYPRODUCTSREFINEMESSCCMD.full_name = ".Cmd.PurifyProductsRefineMessCCmd"
PURIFYPRODUCTSREFINEMESSCCMD.nested_types = {}
PURIFYPRODUCTSREFINEMESSCCMD.enum_types = {}
PURIFYPRODUCTSREFINEMESSCCMD.fields = {
  PURIFYPRODUCTSREFINEMESSCCMD_CMD_FIELD,
  PURIFYPRODUCTSREFINEMESSCCMD_PARAM_FIELD,
  PURIFYPRODUCTSREFINEMESSCCMD_PRODUCTID_FIELD,
  PURIFYPRODUCTSREFINEMESSCCMD_TIMES_FIELD
}
PURIFYPRODUCTSREFINEMESSCCMD.is_extendable = false
PURIFYPRODUCTSREFINEMESSCCMD.extensions = {}
ASTRALSYNCSEASONINFOMESSCCMD_CMD_FIELD.name = "cmd"
ASTRALSYNCSEASONINFOMESSCCMD_CMD_FIELD.full_name = ".Cmd.AstralSyncSeasonInfoMessCCmd.cmd"
ASTRALSYNCSEASONINFOMESSCCMD_CMD_FIELD.number = 1
ASTRALSYNCSEASONINFOMESSCCMD_CMD_FIELD.index = 0
ASTRALSYNCSEASONINFOMESSCCMD_CMD_FIELD.label = 1
ASTRALSYNCSEASONINFOMESSCCMD_CMD_FIELD.has_default_value = true
ASTRALSYNCSEASONINFOMESSCCMD_CMD_FIELD.default_value = 83
ASTRALSYNCSEASONINFOMESSCCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
ASTRALSYNCSEASONINFOMESSCCMD_CMD_FIELD.type = 14
ASTRALSYNCSEASONINFOMESSCCMD_CMD_FIELD.cpp_type = 8
ASTRALSYNCSEASONINFOMESSCCMD_PARAM_FIELD.name = "param"
ASTRALSYNCSEASONINFOMESSCCMD_PARAM_FIELD.full_name = ".Cmd.AstralSyncSeasonInfoMessCCmd.param"
ASTRALSYNCSEASONINFOMESSCCMD_PARAM_FIELD.number = 2
ASTRALSYNCSEASONINFOMESSCCMD_PARAM_FIELD.index = 1
ASTRALSYNCSEASONINFOMESSCCMD_PARAM_FIELD.label = 1
ASTRALSYNCSEASONINFOMESSCCMD_PARAM_FIELD.has_default_value = true
ASTRALSYNCSEASONINFOMESSCCMD_PARAM_FIELD.default_value = 17
ASTRALSYNCSEASONINFOMESSCCMD_PARAM_FIELD.enum_type = MESSCPARAM
ASTRALSYNCSEASONINFOMESSCCMD_PARAM_FIELD.type = 14
ASTRALSYNCSEASONINFOMESSCCMD_PARAM_FIELD.cpp_type = 8
ASTRALSYNCSEASONINFOMESSCCMD_SEASON_FIELD.name = "season"
ASTRALSYNCSEASONINFOMESSCCMD_SEASON_FIELD.full_name = ".Cmd.AstralSyncSeasonInfoMessCCmd.season"
ASTRALSYNCSEASONINFOMESSCCMD_SEASON_FIELD.number = 3
ASTRALSYNCSEASONINFOMESSCCMD_SEASON_FIELD.index = 2
ASTRALSYNCSEASONINFOMESSCCMD_SEASON_FIELD.label = 1
ASTRALSYNCSEASONINFOMESSCCMD_SEASON_FIELD.has_default_value = false
ASTRALSYNCSEASONINFOMESSCCMD_SEASON_FIELD.default_value = 0
ASTRALSYNCSEASONINFOMESSCCMD_SEASON_FIELD.type = 13
ASTRALSYNCSEASONINFOMESSCCMD_SEASON_FIELD.cpp_type = 3
ASTRALSYNCSEASONINFOMESSCCMD.name = "AstralSyncSeasonInfoMessCCmd"
ASTRALSYNCSEASONINFOMESSCCMD.full_name = ".Cmd.AstralSyncSeasonInfoMessCCmd"
ASTRALSYNCSEASONINFOMESSCCMD.nested_types = {}
ASTRALSYNCSEASONINFOMESSCCMD.enum_types = {}
ASTRALSYNCSEASONINFOMESSCCMD.fields = {
  ASTRALSYNCSEASONINFOMESSCCMD_CMD_FIELD,
  ASTRALSYNCSEASONINFOMESSCCMD_PARAM_FIELD,
  ASTRALSYNCSEASONINFOMESSCCMD_SEASON_FIELD
}
ASTRALSYNCSEASONINFOMESSCCMD.is_extendable = false
ASTRALSYNCSEASONINFOMESSCCMD.extensions = {}
PURIFYPRODUCTSMATERIALSDATA_TRADEGROUPID_FIELD.name = "tradegroupid"
PURIFYPRODUCTSMATERIALSDATA_TRADEGROUPID_FIELD.full_name = ".Cmd.PurifyProductsMaterialsData.tradegroupid"
PURIFYPRODUCTSMATERIALSDATA_TRADEGROUPID_FIELD.number = 1
PURIFYPRODUCTSMATERIALSDATA_TRADEGROUPID_FIELD.index = 0
PURIFYPRODUCTSMATERIALSDATA_TRADEGROUPID_FIELD.label = 1
PURIFYPRODUCTSMATERIALSDATA_TRADEGROUPID_FIELD.has_default_value = false
PURIFYPRODUCTSMATERIALSDATA_TRADEGROUPID_FIELD.default_value = 0
PURIFYPRODUCTSMATERIALSDATA_TRADEGROUPID_FIELD.type = 13
PURIFYPRODUCTSMATERIALSDATA_TRADEGROUPID_FIELD.cpp_type = 3
PURIFYPRODUCTSMATERIALSDATA_MATERIALS_FIELD.name = "materials"
PURIFYPRODUCTSMATERIALSDATA_MATERIALS_FIELD.full_name = ".Cmd.PurifyProductsMaterialsData.materials"
PURIFYPRODUCTSMATERIALSDATA_MATERIALS_FIELD.number = 2
PURIFYPRODUCTSMATERIALSDATA_MATERIALS_FIELD.index = 1
PURIFYPRODUCTSMATERIALSDATA_MATERIALS_FIELD.label = 3
PURIFYPRODUCTSMATERIALSDATA_MATERIALS_FIELD.has_default_value = false
PURIFYPRODUCTSMATERIALSDATA_MATERIALS_FIELD.default_value = {}
PURIFYPRODUCTSMATERIALSDATA_MATERIALS_FIELD.message_type = PURIFYPRODUCTS
PURIFYPRODUCTSMATERIALSDATA_MATERIALS_FIELD.type = 11
PURIFYPRODUCTSMATERIALSDATA_MATERIALS_FIELD.cpp_type = 10
PURIFYPRODUCTSMATERIALSDATA.name = "PurifyProductsMaterialsData"
PURIFYPRODUCTSMATERIALSDATA.full_name = ".Cmd.PurifyProductsMaterialsData"
PURIFYPRODUCTSMATERIALSDATA.nested_types = {}
PURIFYPRODUCTSMATERIALSDATA.enum_types = {}
PURIFYPRODUCTSMATERIALSDATA.fields = {
  PURIFYPRODUCTSMATERIALSDATA_TRADEGROUPID_FIELD,
  PURIFYPRODUCTSMATERIALSDATA_MATERIALS_FIELD
}
PURIFYPRODUCTSMATERIALSDATA.is_extendable = false
PURIFYPRODUCTSMATERIALSDATA.extensions = {}
PURIFYPRODUCTSSAVEDATA_CUR_DATA_FIELD.name = "cur_data"
PURIFYPRODUCTSSAVEDATA_CUR_DATA_FIELD.full_name = ".Cmd.PurifyProductsSaveData.cur_data"
PURIFYPRODUCTSSAVEDATA_CUR_DATA_FIELD.number = 1
PURIFYPRODUCTSSAVEDATA_CUR_DATA_FIELD.index = 0
PURIFYPRODUCTSSAVEDATA_CUR_DATA_FIELD.label = 3
PURIFYPRODUCTSSAVEDATA_CUR_DATA_FIELD.has_default_value = false
PURIFYPRODUCTSSAVEDATA_CUR_DATA_FIELD.default_value = {}
PURIFYPRODUCTSSAVEDATA_CUR_DATA_FIELD.message_type = PURIFYPRODUCTSMATERIALSDATA
PURIFYPRODUCTSSAVEDATA_CUR_DATA_FIELD.type = 11
PURIFYPRODUCTSSAVEDATA_CUR_DATA_FIELD.cpp_type = 10
PURIFYPRODUCTSSAVEDATA_LAST_DATA_FIELD.name = "last_data"
PURIFYPRODUCTSSAVEDATA_LAST_DATA_FIELD.full_name = ".Cmd.PurifyProductsSaveData.last_data"
PURIFYPRODUCTSSAVEDATA_LAST_DATA_FIELD.number = 2
PURIFYPRODUCTSSAVEDATA_LAST_DATA_FIELD.index = 1
PURIFYPRODUCTSSAVEDATA_LAST_DATA_FIELD.label = 3
PURIFYPRODUCTSSAVEDATA_LAST_DATA_FIELD.has_default_value = false
PURIFYPRODUCTSSAVEDATA_LAST_DATA_FIELD.default_value = {}
PURIFYPRODUCTSSAVEDATA_LAST_DATA_FIELD.message_type = PURIFYPRODUCTSMATERIALSDATA
PURIFYPRODUCTSSAVEDATA_LAST_DATA_FIELD.type = 11
PURIFYPRODUCTSSAVEDATA_LAST_DATA_FIELD.cpp_type = 10
PURIFYPRODUCTSSAVEDATA_WEEK_REFRESH_TIME_FIELD.name = "week_refresh_time"
PURIFYPRODUCTSSAVEDATA_WEEK_REFRESH_TIME_FIELD.full_name = ".Cmd.PurifyProductsSaveData.week_refresh_time"
PURIFYPRODUCTSSAVEDATA_WEEK_REFRESH_TIME_FIELD.number = 3
PURIFYPRODUCTSSAVEDATA_WEEK_REFRESH_TIME_FIELD.index = 2
PURIFYPRODUCTSSAVEDATA_WEEK_REFRESH_TIME_FIELD.label = 1
PURIFYPRODUCTSSAVEDATA_WEEK_REFRESH_TIME_FIELD.has_default_value = false
PURIFYPRODUCTSSAVEDATA_WEEK_REFRESH_TIME_FIELD.default_value = 0
PURIFYPRODUCTSSAVEDATA_WEEK_REFRESH_TIME_FIELD.type = 13
PURIFYPRODUCTSSAVEDATA_WEEK_REFRESH_TIME_FIELD.cpp_type = 3
PURIFYPRODUCTSSAVEDATA_DAY_REFRESH_TIME_FIELD.name = "day_refresh_time"
PURIFYPRODUCTSSAVEDATA_DAY_REFRESH_TIME_FIELD.full_name = ".Cmd.PurifyProductsSaveData.day_refresh_time"
PURIFYPRODUCTSSAVEDATA_DAY_REFRESH_TIME_FIELD.number = 4
PURIFYPRODUCTSSAVEDATA_DAY_REFRESH_TIME_FIELD.index = 3
PURIFYPRODUCTSSAVEDATA_DAY_REFRESH_TIME_FIELD.label = 1
PURIFYPRODUCTSSAVEDATA_DAY_REFRESH_TIME_FIELD.has_default_value = false
PURIFYPRODUCTSSAVEDATA_DAY_REFRESH_TIME_FIELD.default_value = 0
PURIFYPRODUCTSSAVEDATA_DAY_REFRESH_TIME_FIELD.type = 13
PURIFYPRODUCTSSAVEDATA_DAY_REFRESH_TIME_FIELD.cpp_type = 3
PURIFYPRODUCTSSAVEDATA.name = "PurifyProductsSaveData"
PURIFYPRODUCTSSAVEDATA.full_name = ".Cmd.PurifyProductsSaveData"
PURIFYPRODUCTSSAVEDATA.nested_types = {}
PURIFYPRODUCTSSAVEDATA.enum_types = {}
PURIFYPRODUCTSSAVEDATA.fields = {
  PURIFYPRODUCTSSAVEDATA_CUR_DATA_FIELD,
  PURIFYPRODUCTSSAVEDATA_LAST_DATA_FIELD,
  PURIFYPRODUCTSSAVEDATA_WEEK_REFRESH_TIME_FIELD,
  PURIFYPRODUCTSSAVEDATA_DAY_REFRESH_TIME_FIELD
}
PURIFYPRODUCTSSAVEDATA.is_extendable = false
PURIFYPRODUCTSSAVEDATA.extensions = {}
ASTRAL_REWARD = 14
ASTRAL_SEASON = 17
AstralRewardMessCCmd = protobuf.Message(ASTRALREWARDMESSCCMD)
AstralSyncSeasonInfoMessCCmd = protobuf.Message(ASTRALSYNCSEASONINFOMESSCCMD)
BALANCE_MODE_CHOOSE = 10
BalanceModeChooseMessCCmd = protobuf.Message(BALANCEMODECHOOSEMESSCCMD)
ChooseNewProfessionMessCCmd = protobuf.Message(CHOOSENEWPROFESSIONMESSCCMD)
DestinyGraphInfo = protobuf.Message(DESTINYGRAPHINFO)
EGRAPH_POINT_STATE_LIGHT = 2
EGRAPH_POINT_STATE_LOCKED = 0
EGRAPH_POINT_STATE_UNLOCKED = 1
EPIPPISTATE_DIE_HIDE = 3
EPIPPISTATE_DIE_SHOW = 2
EPIPPISTATE_LIVE_HIDE = 1
EPIPPISTATE_LIVE_SHOW = 0
FINGER_GUESS_MIN = 0
FINGER_GUESS_PAPER = 3
FINGER_GUESS_RANDOM = 4
FINGER_GUESS_ROCK = 1
FINGER_GUESS_SCISSORS = 2
FingerGuessLoveConfessionMessCCmd = protobuf.Message(FINGERGUESSLOVECONFESSIONMESSCCMD)
FingerLoseLoveConfessionMessCCmd = protobuf.Message(FINGERLOSELOVECONFESSIONMESSCCMD)
GraphPointInfo = protobuf.Message(GRAPHPOINTINFO)
InviteeProcessLoveConfessionMessCCmd = protobuf.Message(INVITEEPROCESSLOVECONFESSIONMESSCCMD)
InviteeReceiveLoveConfessionMessCCmd = protobuf.Message(INVITEERECEIVELOVECONFESSIONMESSCCMD)
InviterReceiveConfessionMessCCmd = protobuf.Message(INVITERRECEIVECONFESSIONMESSCCMD)
InviterResultLoveConfessionMessCCmd = protobuf.Message(INVITERRESULTLOVECONFESSIONMESSCCMD)
InviterSendLoveConfessionMessCCmd = protobuf.Message(INVITERSENDLOVECONFESSIONMESSCCMD)
LIGHTEN_DESTINY_GRAPH = 13
LightenDestinyGraphMessCCmd = protobuf.Message(LIGHTENDESTINYGRAPHMESSCCMD)
MESSCPARAM_CHOOSE_NEW_PROFESSION = 1
MESSCPARAM_FINGER_GUESS_LOVE_CONFESSION = 6
MESSCPARAM_FINGER_LOSE_LOVE_CONFESSION = 7
MESSCPARAM_INVITEE_PROCESS_LOVE_CONFESSION = 4
MESSCPARAM_INVITEE_RECEIVE_LOVE_CONFESSION = 3
MESSCPARAM_INVITER_RECEIVE_LOVE_CONFESSION = 5
MESSCPARAM_INVITER_RESULT_LOVE_CONFESSION = 8
MESSCPARAM_INVITER_SEND_LOVE_CONFESSION = 2
MapStepForeverRewardItem = protobuf.Message(MAPSTEPFOREVERREWARDITEM)
PURIFY_PRODUCTS_MATERIALS = 15
PURIFY_PRODUCTS_REFINE = 16
PurifyMaterials = protobuf.Message(PURIFYMATERIALS)
PurifyProducts = protobuf.Message(PURIFYPRODUCTS)
PurifyProductsMaterialsData = protobuf.Message(PURIFYPRODUCTSMATERIALSDATA)
PurifyProductsMaterialsMessCCmd = protobuf.Message(PURIFYPRODUCTSMATERIALSMESSCCMD)
PurifyProductsRefineMessCCmd = protobuf.Message(PURIFYPRODUCTSREFINEMESSCCMD)
PurifyProductsSaveData = protobuf.Message(PURIFYPRODUCTSSAVEDATA)
PurifyTimes = protobuf.Message(PURIFYTIMES)
SET_PIPPI_STATE = 11
SYNC_DESTINY_GRAPH = 12
SYNC_MAPSTEP_FOREVER_REWARD_INFO = 9
SetPippiStateMessCCmd = protobuf.Message(SETPIPPISTATEMESSCCMD)
SyncDestinyGraphMessCCmd = protobuf.Message(SYNCDESTINYGRAPHMESSCCMD)
SyncMapStepForeverRewardInfo = protobuf.Message(SYNCMAPSTEPFOREVERREWARDINFO)
