local protobuf = protobuf
autoImport("xCmd_pb")
local xCmd_pb = xCmd_pb
autoImport("ProtoCommon_pb")
local ProtoCommon_pb = ProtoCommon_pb
module("MiniGameCmd_pb")
EMINIGAMECMDPARAM = protobuf.EnumDescriptor()
EMINIGAMECMDPARAM_MINIGAMEPARAM_NTF_MONSTER_SHOT_ENUM = protobuf.EnumValueDescriptor()
EMINIGAMECMDPARAM_MINIGAMEPARAM_SUBMIT_MONSTER_SHOT_ENUM = protobuf.EnumValueDescriptor()
EMINIGAMECMDPARAM_MINIGAMEPARAM_RES_SUBMIT_MONSTER_SHOT_ENUM = protobuf.EnumValueDescriptor()
EMINIGAMECMDPARAM_MINIGAMEPARAM_NTF_MONSTER_ANSWER_ENUM = protobuf.EnumValueDescriptor()
EMINIGAMECMDPARAM_MINIGAMEPARAM_SUBMIT_MONSTER_ANSWER_ENUM = protobuf.EnumValueDescriptor()
EMINIGAMECMDPARAM_MINIGAMEPARAM_GET_UNLOCKLIST_ENUM = protobuf.EnumValueDescriptor()
EMINIGAMECMDPARAM_MINIGAMEPARAM_RES_GET_UNLOCKLIST_ENUM = protobuf.EnumValueDescriptor()
EMINIGAMECMDPARAM_MINIGAMEPARAM_ACTION_START_ENUM = protobuf.EnumValueDescriptor()
EMINIGAMECMDPARAM_MINIGAMEPARAM_ACTION_NEXTROUND_ENUM = protobuf.EnumValueDescriptor()
EMINIGAMECMDPARAM_MINIGAMEPARAM_NTF_GAME_OVER_ENUM = protobuf.EnumValueDescriptor()
EMINIGAMECMDPARAM_MINIGAMEPARAM_OVERGAME_ENUM = protobuf.EnumValueDescriptor()
EMINIGAMECMDPARAM_MINIGAMEPARAM_USE_ASSIST_ENUM = protobuf.EnumValueDescriptor()
EMINIGAMECMDPARAM_MINIGAMEPARAM_ROUNDEND_NTF_ENUM = protobuf.EnumValueDescriptor()
EMINIGAMECMDPARAM_MINIGAMEPARAM_QUERYRANK_ENUM = protobuf.EnumValueDescriptor()
EMINIGAMETYPE = protobuf.EnumDescriptor()
EMINIGAMETYPE_EMINIGAMETYPE_NONE_ENUM = protobuf.EnumValueDescriptor()
EMINIGAMETYPE_EMINIGAMETYPE_MONSTER_ANSWER_ENUM = protobuf.EnumValueDescriptor()
EMINIGAMETYPE_EMINIGAMETYPE_MONSTER_PHOTO_ENUM = protobuf.EnumValueDescriptor()
EMINIGAMETYPE_EMINIGAMETYPE_CARD_PAIR_ENUM = protobuf.EnumValueDescriptor()
EMINIGAMETYPE_EMINIGAMETYPE_MAX_ENUM = protobuf.EnumValueDescriptor()
EMINIGAMEERRCODE = protobuf.EnumDescriptor()
EMINIGAMEERRCODE_EMINIGAME_ERROR_NONE_ENUM = protobuf.EnumValueDescriptor()
EMINIGAMEERRCODE_EMINIGAME_ERROR_DIFFICULTY_NOT_UNLOCK_ENUM = protobuf.EnumValueDescriptor()
EMINIGAMEERRCODE_EMINIGAME_ERROR_MONSTER_ANSWER_ERROR_ENUM = protobuf.EnumValueDescriptor()
EMINIGAMEERRCODE_ENIMIGAME_ERROR_OVER_ALREADY_ENUM = protobuf.EnumValueDescriptor()
EMINIGAMEERRCODE_ENIMIGAME_ERROR_NO_MAPRAID_ENUM = protobuf.EnumValueDescriptor()
EMINIGAMEERRCODE_ENIMIGAME_ERROR_DIFFICULTY_ILLEGAL_ENUM = protobuf.EnumValueDescriptor()
EMINIGAMEERRCODE_ENIMIGAME_ERROR_TYPE_ILLEGAL_ENUM = protobuf.EnumValueDescriptor()
EMINIGAMEERRCODE_ENIMIGAME_ERROR_MAP_NOMATCH_ENUM = protobuf.EnumValueDescriptor()
EMINIGAMEERRCODE_ENIMIGAME_ERROR_REACH_LIMIT_ENUM = protobuf.EnumValueDescriptor()
EMINIGAMEERRCODE_ENIMIGAME_ERROR_INGAME_ALREADY_ENUM = protobuf.EnumValueDescriptor()
EMINIGAMEERRCODE_ENIMIGAME_ERROR_NOT_INGAME_ENUM = protobuf.EnumValueDescriptor()
EMINIGAMEOVERRESULT = protobuf.EnumDescriptor()
EMINIGAMEOVERRESULT_EMINIGAME_OVER_WIN_ENUM = protobuf.EnumValueDescriptor()
EMINIGAMEOVERRESULT_EMINIGAME_OVER_LOSE_ENUM = protobuf.EnumValueDescriptor()
EMONSTERSHOTCOMPARE = protobuf.EnumDescriptor()
EMONSTERSHOTCOMPARE_EMONSTERSHOT_COMPARE_NONE_ENUM = protobuf.EnumValueDescriptor()
EMONSTERSHOTCOMPARE_EMONSTERSHOT_COMPARE_LT_ENUM = protobuf.EnumValueDescriptor()
EMONSTERSHOTCOMPARE_EMONSTERSHOT_COMPARE_EQ_ENUM = protobuf.EnumValueDescriptor()
EMONSTERSHOTCOMPARE_EMONSTERSHOT_COMPARE_GT_ENUM = protobuf.EnumValueDescriptor()
EMONSTERANWSERQUESTTYPE = protobuf.EnumDescriptor()
EMONSTERANWSERQUESTTYPE_EMONSTERANWSER_QUESTTYPE_FEET_ENUM = protobuf.EnumValueDescriptor()
EMONSTERANWSERQUESTTYPE_EMONSTERANWSER_QUESTTYPE_ELEMENT_ENUM = protobuf.EnumValueDescriptor()
EMONSTERANWSERQUESTTYPE_EMONSTERANWSER_QUESTTYPE_COLOR_ENUM = protobuf.EnumValueDescriptor()
EMONSTERANWSERQUESTTYPE_EMONSTERADIFFICULTYNWSER_QUESTTYPE_RACE_ENUM = protobuf.EnumValueDescriptor()
EMONSTERANWSERQUESTTYPE_EMONSTERANWSER_QUESTTYPE_MAX_ENUM = protobuf.EnumValueDescriptor()
EMONSTERANSWERLINKSYMBOL = protobuf.EnumDescriptor()
EMONSTERANSWERLINKSYMBOL_EMONSTERANSWER_LINKSYMBOL_NONE_ENUM = protobuf.EnumValueDescriptor()
EMONSTERANSWERLINKSYMBOL_EMONSTERANSWER_LINKSYMBOL_AND_ENUM = protobuf.EnumValueDescriptor()
EMONSTERANSWERLINKSYMBOL_EMONSTERANSWER_LINKSYMBOL_OR_ENUM = protobuf.EnumValueDescriptor()
ELASTREPLYSTATUS = protobuf.EnumDescriptor()
ELASTREPLYSTATUS_ELASTREPLYSTATUS_NONE_ENUM = protobuf.EnumValueDescriptor()
ELASTREPLYSTATUS_ELASTREPLYSTATUS_ERROR_ENUM = protobuf.EnumValueDescriptor()
ELASTREPLYSTATUS_ELASTREPLYSTATUS_RIGHT_ENUM = protobuf.EnumValueDescriptor()
EASSISTTYPE = protobuf.EnumDescriptor()
EASSISTTYPE_EASSISTTYPE_ADDTIME_ENUM = protobuf.EnumValueDescriptor()
EASSISTTYPE_EASSISTTYPE_QUICK_FINISH_ENUM = protobuf.EnumValueDescriptor()
EASSISTTYPE_EASSISTTYPE_TIPS_ENUM = protobuf.EnumValueDescriptor()
EMINIGAMEMODE = protobuf.EnumDescriptor()
EMINIGAMEMODE_EMINIGAMEMODE_NORMAL_ENUM = protobuf.EnumValueDescriptor()
EMINIGAMEMODE_EMINIGAMEMODE_CHALLENGE_ENUM = protobuf.EnumValueDescriptor()
MINIGAMEASSIST = protobuf.Descriptor()
MINIGAMEASSIST_TYPE_FIELD = protobuf.FieldDescriptor()
MINIGAMEASSIST_COUNT_FIELD = protobuf.FieldDescriptor()
MINIGAMEASSIST_EFFECT_FIELD = protobuf.FieldDescriptor()
MONSTERSHOTREQUIREPAIR = protobuf.Descriptor()
MONSTERSHOTREQUIREPAIR_CMPTYPE_FIELD = protobuf.FieldDescriptor()
MONSTERSHOTREQUIREPAIR_VALUE_FIELD = protobuf.FieldDescriptor()
MONSTERSHOTREQUIREPAIR_PLUSLEFT_FIELD = protobuf.FieldDescriptor()
MONSTERSHOTREQUIREPAIR_PLUSRIGHT_FIELD = protobuf.FieldDescriptor()
MINIGAMENTFMONSTERSHOT = protobuf.Descriptor()
MINIGAMENTFMONSTERSHOT_CMD_FIELD = protobuf.FieldDescriptor()
MINIGAMENTFMONSTERSHOT_PARAM_FIELD = protobuf.FieldDescriptor()
MINIGAMENTFMONSTERSHOT_COUNTDOWN_FIELD = protobuf.FieldDescriptor()
MINIGAMENTFMONSTERSHOT_REQUIRES_FIELD = protobuf.FieldDescriptor()
MINIGAMENTFMONSTERSHOT_MISSTIMEREST_FIELD = protobuf.FieldDescriptor()
MINIGAMENTFMONSTERSHOT_TOTALROUNDS_FIELD = protobuf.FieldDescriptor()
MINIGAMENTFMONSTERSHOT_CURROUND_FIELD = protobuf.FieldDescriptor()
MINIGAMENTFMONSTERSHOT_USEPLUS_FIELD = protobuf.FieldDescriptor()
MINIGAMEMONSTERSHOTACTION = protobuf.Descriptor()
MINIGAMEMONSTERSHOTACTION_CMD_FIELD = protobuf.FieldDescriptor()
MINIGAMEMONSTERSHOTACTION_PARAM_FIELD = protobuf.FieldDescriptor()
MINIGAMEMONSTERSHOTACTION_CLIENTJUDGESUC_FIELD = protobuf.FieldDescriptor()
MINIGAMEMONSTERSHOTACTION_ERRCODE_FIELD = protobuf.FieldDescriptor()
MONSTERANSWERQUESTPART = protobuf.Descriptor()
MONSTERANSWERQUESTPART_TYPE_FIELD = protobuf.FieldDescriptor()
MONSTERANSWERQUESTPART_SUBPARAM_FIELD = protobuf.FieldDescriptor()
MINIGAMENTFMONSTERANSWER = protobuf.Descriptor()
MINIGAMENTFMONSTERANSWER_CMD_FIELD = protobuf.FieldDescriptor()
MINIGAMENTFMONSTERANSWER_PARAM_FIELD = protobuf.FieldDescriptor()
MINIGAMENTFMONSTERANSWER_COUNTDOWN_FIELD = protobuf.FieldDescriptor()
MINIGAMENTFMONSTERANSWER_LINKSYMBOL_FIELD = protobuf.FieldDescriptor()
MINIGAMENTFMONSTERANSWER_QUESTPARTS_FIELD = protobuf.FieldDescriptor()
MINIGAMENTFMONSTERANSWER_LASTREPLYSTATUS_FIELD = protobuf.FieldDescriptor()
MINIGAMESUBMITMONSTERANSWER = protobuf.Descriptor()
MINIGAMESUBMITMONSTERANSWER_CMD_FIELD = protobuf.FieldDescriptor()
MINIGAMESUBMITMONSTERANSWER_PARAM_FIELD = protobuf.FieldDescriptor()
MINIGAMESUBMITMONSTERANSWER_ANSWER_FIELD = protobuf.FieldDescriptor()
MINIGAMEACTION = protobuf.Descriptor()
MINIGAMEACTION_CMD_FIELD = protobuf.FieldDescriptor()
MINIGAMEACTION_PARAM_FIELD = protobuf.FieldDescriptor()
MINIGAMEACTION_MODE_FIELD = protobuf.FieldDescriptor()
MINIGAMEACTION_GAMETYPE_FIELD = protobuf.FieldDescriptor()
MINIGAMEACTION_DIFFICULTY_FIELD = protobuf.FieldDescriptor()
MINIGAMEACTION_ERRCODE_FIELD = protobuf.FieldDescriptor()
MINIGAMEACTION_ENDCARDPAIR_FIELD = protobuf.FieldDescriptor()
MINIGAMEACTION_ADDSECONDS_FIELD = protobuf.FieldDescriptor()
MINIGAMEACTION_MINUSSECONDS_FIELD = protobuf.FieldDescriptor()
MINIGAMEACTION_ENDTIME_FIELD = protobuf.FieldDescriptor()
MINIGAMEACTION_CARDFAILFORCE_FIELD = protobuf.FieldDescriptor()
MINIGAMEACTION_ROUNDENDFLAG_FIELD = protobuf.FieldDescriptor()
MINIGAMENEXTROUND = protobuf.Descriptor()
MINIGAMENEXTROUND_CMD_FIELD = protobuf.FieldDescriptor()
MINIGAMENEXTROUND_PARAM_FIELD = protobuf.FieldDescriptor()
MINIGAMENEXTROUND_GAMETYPE_FIELD = protobuf.FieldDescriptor()
MINIGAMENEXTROUND_ASSISTLIST_FIELD = protobuf.FieldDescriptor()
MINIGAMENEXTROUND_ENDTIME_FIELD = protobuf.FieldDescriptor()
MINIGAMENEXTROUND_CARDUSEFLAG_FIELD = protobuf.FieldDescriptor()
MINIGAMECHANLEGERECORD = protobuf.Descriptor()
MINIGAMECHANLEGERECORD_TYPE_FIELD = protobuf.FieldDescriptor()
MINIGAMECHANLEGERECORD_VALUE_FIELD = protobuf.FieldDescriptor()
MINIGAMECHANLEGERECORD_TIMESTAMP_FIELD = protobuf.FieldDescriptor()
MINIGAMEUNLOCKPAIR = protobuf.Descriptor()
MINIGAMEUNLOCKPAIR_TYPE_FIELD = protobuf.FieldDescriptor()
MINIGAMEUNLOCKPAIR_DIFFICULTY_FIELD = protobuf.FieldDescriptor()
MINIGAMEUNLOCKPAIR_LASTREWARD_FIELD = protobuf.FieldDescriptor()
MINIGAMEUNLOCKPAIR_DAILYREST_FIELD = protobuf.FieldDescriptor()
MINIGAMEUNLOCKPAIR_PASSALL_FIELD = protobuf.FieldDescriptor()
MINIGAMEUNLOCKPAIR_CHALLENGERECORD_FIELD = protobuf.FieldDescriptor()
MINIGAMEWINPAIR = protobuf.Descriptor()
MINIGAMEWINPAIR_TYPE_FIELD = protobuf.FieldDescriptor()
MINIGAMEWINPAIR_WINTIMES_FIELD = protobuf.FieldDescriptor()
MINIGAMEUNLOCKLIST = protobuf.Descriptor()
MINIGAMEUNLOCKLIST_CMD_FIELD = protobuf.FieldDescriptor()
MINIGAMEUNLOCKLIST_PARAM_FIELD = protobuf.FieldDescriptor()
MINIGAMEUNLOCKLIST_LIST_FIELD = protobuf.FieldDescriptor()
MINIGAMENTFGAMEOVERCMD = protobuf.Descriptor()
MINIGAMENTFGAMEOVERCMD_CMD_FIELD = protobuf.FieldDescriptor()
MINIGAMENTFGAMEOVERCMD_PARAM_FIELD = protobuf.FieldDescriptor()
MINIGAMENTFGAMEOVERCMD_TYPE_FIELD = protobuf.FieldDescriptor()
MINIGAMENTFGAMEOVERCMD_RESULT_FIELD = protobuf.FieldDescriptor()
MINIGAMEREQOVER = protobuf.Descriptor()
MINIGAMEREQOVER_CMD_FIELD = protobuf.FieldDescriptor()
MINIGAMEREQOVER_PARAM_FIELD = protobuf.FieldDescriptor()
MINIGAMEREQOVER_TYPE_FIELD = protobuf.FieldDescriptor()
MINIGAMEUSEASSIST = protobuf.Descriptor()
MINIGAMEUSEASSIST_CMD_FIELD = protobuf.FieldDescriptor()
MINIGAMEUSEASSIST_PARAM_FIELD = protobuf.FieldDescriptor()
MINIGAMEUSEASSIST_TYPE_FIELD = protobuf.FieldDescriptor()
MINIGAMEUSEASSIST_ASSISTTYPE_FIELD = protobuf.FieldDescriptor()
MINIGAMENTFROUNDOVER = protobuf.Descriptor()
MINIGAMENTFROUNDOVER_CMD_FIELD = protobuf.FieldDescriptor()
MINIGAMENTFROUNDOVER_PARAM_FIELD = protobuf.FieldDescriptor()
MINIGAMENTFROUNDOVER_TYPE_FIELD = protobuf.FieldDescriptor()
MINIGAMENTFROUNDOVER_ANSWER_FIELD = protobuf.FieldDescriptor()
MINIGAMENTFROUNDOVER_LASTREPLYSTATUS_FIELD = protobuf.FieldDescriptor()
MINIGAMERANKUSER = protobuf.Descriptor()
MINIGAMERANKUSER_CHARID_FIELD = protobuf.FieldDescriptor()
MINIGAMERANKUSER_NAME_FIELD = protobuf.FieldDescriptor()
MINIGAMERANKUSER_PROFESSION_FIELD = protobuf.FieldDescriptor()
MINIGAMERANKUSER_PORTRAIT_FIELD = protobuf.FieldDescriptor()
MINIGAMERANKBASE = protobuf.Descriptor()
MINIGAMERANKBASE_RECORD_FIELD = protobuf.FieldDescriptor()
MINIGAMERANKBASE_USER_FIELD = protobuf.FieldDescriptor()
MINIGAMERANKBASE_MYSELF_FIELD = protobuf.FieldDescriptor()
MINIGAMEQUERYRANK = protobuf.Descriptor()
MINIGAMEQUERYRANK_CMD_FIELD = protobuf.FieldDescriptor()
MINIGAMEQUERYRANK_PARAM_FIELD = protobuf.FieldDescriptor()
MINIGAMEQUERYRANK_TYPE_FIELD = protobuf.FieldDescriptor()
MINIGAMEQUERYRANK_RANKS_FIELD = protobuf.FieldDescriptor()
EMINIGAMECMDPARAM_MINIGAMEPARAM_NTF_MONSTER_SHOT_ENUM.name = "MINIGAMEPARAM_NTF_MONSTER_SHOT"
EMINIGAMECMDPARAM_MINIGAMEPARAM_NTF_MONSTER_SHOT_ENUM.index = 0
EMINIGAMECMDPARAM_MINIGAMEPARAM_NTF_MONSTER_SHOT_ENUM.number = 1
EMINIGAMECMDPARAM_MINIGAMEPARAM_SUBMIT_MONSTER_SHOT_ENUM.name = "MINIGAMEPARAM_SUBMIT_MONSTER_SHOT"
EMINIGAMECMDPARAM_MINIGAMEPARAM_SUBMIT_MONSTER_SHOT_ENUM.index = 1
EMINIGAMECMDPARAM_MINIGAMEPARAM_SUBMIT_MONSTER_SHOT_ENUM.number = 2
EMINIGAMECMDPARAM_MINIGAMEPARAM_RES_SUBMIT_MONSTER_SHOT_ENUM.name = "MINIGAMEPARAM_RES_SUBMIT_MONSTER_SHOT"
EMINIGAMECMDPARAM_MINIGAMEPARAM_RES_SUBMIT_MONSTER_SHOT_ENUM.index = 2
EMINIGAMECMDPARAM_MINIGAMEPARAM_RES_SUBMIT_MONSTER_SHOT_ENUM.number = 3
EMINIGAMECMDPARAM_MINIGAMEPARAM_NTF_MONSTER_ANSWER_ENUM.name = "MINIGAMEPARAM_NTF_MONSTER_ANSWER"
EMINIGAMECMDPARAM_MINIGAMEPARAM_NTF_MONSTER_ANSWER_ENUM.index = 3
EMINIGAMECMDPARAM_MINIGAMEPARAM_NTF_MONSTER_ANSWER_ENUM.number = 9
EMINIGAMECMDPARAM_MINIGAMEPARAM_SUBMIT_MONSTER_ANSWER_ENUM.name = "MINIGAMEPARAM_SUBMIT_MONSTER_ANSWER"
EMINIGAMECMDPARAM_MINIGAMEPARAM_SUBMIT_MONSTER_ANSWER_ENUM.index = 4
EMINIGAMECMDPARAM_MINIGAMEPARAM_SUBMIT_MONSTER_ANSWER_ENUM.number = 10
EMINIGAMECMDPARAM_MINIGAMEPARAM_GET_UNLOCKLIST_ENUM.name = "MINIGAMEPARAM_GET_UNLOCKLIST"
EMINIGAMECMDPARAM_MINIGAMEPARAM_GET_UNLOCKLIST_ENUM.index = 5
EMINIGAMECMDPARAM_MINIGAMEPARAM_GET_UNLOCKLIST_ENUM.number = 11
EMINIGAMECMDPARAM_MINIGAMEPARAM_RES_GET_UNLOCKLIST_ENUM.name = "MINIGAMEPARAM_RES_GET_UNLOCKLIST"
EMINIGAMECMDPARAM_MINIGAMEPARAM_RES_GET_UNLOCKLIST_ENUM.index = 6
EMINIGAMECMDPARAM_MINIGAMEPARAM_RES_GET_UNLOCKLIST_ENUM.number = 12
EMINIGAMECMDPARAM_MINIGAMEPARAM_ACTION_START_ENUM.name = "MINIGAMEPARAM_ACTION_START"
EMINIGAMECMDPARAM_MINIGAMEPARAM_ACTION_START_ENUM.index = 7
EMINIGAMECMDPARAM_MINIGAMEPARAM_ACTION_START_ENUM.number = 13
EMINIGAMECMDPARAM_MINIGAMEPARAM_ACTION_NEXTROUND_ENUM.name = "MINIGAMEPARAM_ACTION_NEXTROUND"
EMINIGAMECMDPARAM_MINIGAMEPARAM_ACTION_NEXTROUND_ENUM.index = 8
EMINIGAMECMDPARAM_MINIGAMEPARAM_ACTION_NEXTROUND_ENUM.number = 14
EMINIGAMECMDPARAM_MINIGAMEPARAM_NTF_GAME_OVER_ENUM.name = "MINIGAMEPARAM_NTF_GAME_OVER"
EMINIGAMECMDPARAM_MINIGAMEPARAM_NTF_GAME_OVER_ENUM.index = 9
EMINIGAMECMDPARAM_MINIGAMEPARAM_NTF_GAME_OVER_ENUM.number = 15
EMINIGAMECMDPARAM_MINIGAMEPARAM_OVERGAME_ENUM.name = "MINIGAMEPARAM_OVERGAME"
EMINIGAMECMDPARAM_MINIGAMEPARAM_OVERGAME_ENUM.index = 10
EMINIGAMECMDPARAM_MINIGAMEPARAM_OVERGAME_ENUM.number = 16
EMINIGAMECMDPARAM_MINIGAMEPARAM_USE_ASSIST_ENUM.name = "MINIGAMEPARAM_USE_ASSIST"
EMINIGAMECMDPARAM_MINIGAMEPARAM_USE_ASSIST_ENUM.index = 11
EMINIGAMECMDPARAM_MINIGAMEPARAM_USE_ASSIST_ENUM.number = 17
EMINIGAMECMDPARAM_MINIGAMEPARAM_ROUNDEND_NTF_ENUM.name = "MINIGAMEPARAM_ROUNDEND_NTF"
EMINIGAMECMDPARAM_MINIGAMEPARAM_ROUNDEND_NTF_ENUM.index = 12
EMINIGAMECMDPARAM_MINIGAMEPARAM_ROUNDEND_NTF_ENUM.number = 18
EMINIGAMECMDPARAM_MINIGAMEPARAM_QUERYRANK_ENUM.name = "MINIGAMEPARAM_QUERYRANK"
EMINIGAMECMDPARAM_MINIGAMEPARAM_QUERYRANK_ENUM.index = 13
EMINIGAMECMDPARAM_MINIGAMEPARAM_QUERYRANK_ENUM.number = 19
EMINIGAMECMDPARAM.name = "EMiniGameCmdParam"
EMINIGAMECMDPARAM.full_name = ".Cmd.EMiniGameCmdParam"
EMINIGAMECMDPARAM.values = {
  EMINIGAMECMDPARAM_MINIGAMEPARAM_NTF_MONSTER_SHOT_ENUM,
  EMINIGAMECMDPARAM_MINIGAMEPARAM_SUBMIT_MONSTER_SHOT_ENUM,
  EMINIGAMECMDPARAM_MINIGAMEPARAM_RES_SUBMIT_MONSTER_SHOT_ENUM,
  EMINIGAMECMDPARAM_MINIGAMEPARAM_NTF_MONSTER_ANSWER_ENUM,
  EMINIGAMECMDPARAM_MINIGAMEPARAM_SUBMIT_MONSTER_ANSWER_ENUM,
  EMINIGAMECMDPARAM_MINIGAMEPARAM_GET_UNLOCKLIST_ENUM,
  EMINIGAMECMDPARAM_MINIGAMEPARAM_RES_GET_UNLOCKLIST_ENUM,
  EMINIGAMECMDPARAM_MINIGAMEPARAM_ACTION_START_ENUM,
  EMINIGAMECMDPARAM_MINIGAMEPARAM_ACTION_NEXTROUND_ENUM,
  EMINIGAMECMDPARAM_MINIGAMEPARAM_NTF_GAME_OVER_ENUM,
  EMINIGAMECMDPARAM_MINIGAMEPARAM_OVERGAME_ENUM,
  EMINIGAMECMDPARAM_MINIGAMEPARAM_USE_ASSIST_ENUM,
  EMINIGAMECMDPARAM_MINIGAMEPARAM_ROUNDEND_NTF_ENUM,
  EMINIGAMECMDPARAM_MINIGAMEPARAM_QUERYRANK_ENUM
}
EMINIGAMETYPE_EMINIGAMETYPE_NONE_ENUM.name = "EMINIGAMETYPE_NONE"
EMINIGAMETYPE_EMINIGAMETYPE_NONE_ENUM.index = 0
EMINIGAMETYPE_EMINIGAMETYPE_NONE_ENUM.number = 0
EMINIGAMETYPE_EMINIGAMETYPE_MONSTER_ANSWER_ENUM.name = "EMINIGAMETYPE_MONSTER_ANSWER"
EMINIGAMETYPE_EMINIGAMETYPE_MONSTER_ANSWER_ENUM.index = 1
EMINIGAMETYPE_EMINIGAMETYPE_MONSTER_ANSWER_ENUM.number = 1
EMINIGAMETYPE_EMINIGAMETYPE_MONSTER_PHOTO_ENUM.name = "EMINIGAMETYPE_MONSTER_PHOTO"
EMINIGAMETYPE_EMINIGAMETYPE_MONSTER_PHOTO_ENUM.index = 2
EMINIGAMETYPE_EMINIGAMETYPE_MONSTER_PHOTO_ENUM.number = 2
EMINIGAMETYPE_EMINIGAMETYPE_CARD_PAIR_ENUM.name = "EMINIGAMETYPE_CARD_PAIR"
EMINIGAMETYPE_EMINIGAMETYPE_CARD_PAIR_ENUM.index = 3
EMINIGAMETYPE_EMINIGAMETYPE_CARD_PAIR_ENUM.number = 3
EMINIGAMETYPE_EMINIGAMETYPE_MAX_ENUM.name = "EMINIGAMETYPE_MAX"
EMINIGAMETYPE_EMINIGAMETYPE_MAX_ENUM.index = 4
EMINIGAMETYPE_EMINIGAMETYPE_MAX_ENUM.number = 4
EMINIGAMETYPE.name = "EMiniGameType"
EMINIGAMETYPE.full_name = ".Cmd.EMiniGameType"
EMINIGAMETYPE.values = {
  EMINIGAMETYPE_EMINIGAMETYPE_NONE_ENUM,
  EMINIGAMETYPE_EMINIGAMETYPE_MONSTER_ANSWER_ENUM,
  EMINIGAMETYPE_EMINIGAMETYPE_MONSTER_PHOTO_ENUM,
  EMINIGAMETYPE_EMINIGAMETYPE_CARD_PAIR_ENUM,
  EMINIGAMETYPE_EMINIGAMETYPE_MAX_ENUM
}
EMINIGAMEERRCODE_EMINIGAME_ERROR_NONE_ENUM.name = "EMINIGAME_ERROR_NONE"
EMINIGAMEERRCODE_EMINIGAME_ERROR_NONE_ENUM.index = 0
EMINIGAMEERRCODE_EMINIGAME_ERROR_NONE_ENUM.number = 0
EMINIGAMEERRCODE_EMINIGAME_ERROR_DIFFICULTY_NOT_UNLOCK_ENUM.name = "EMINIGAME_ERROR_DIFFICULTY_NOT_UNLOCK"
EMINIGAMEERRCODE_EMINIGAME_ERROR_DIFFICULTY_NOT_UNLOCK_ENUM.index = 1
EMINIGAMEERRCODE_EMINIGAME_ERROR_DIFFICULTY_NOT_UNLOCK_ENUM.number = 1
EMINIGAMEERRCODE_EMINIGAME_ERROR_MONSTER_ANSWER_ERROR_ENUM.name = "EMINIGAME_ERROR_MONSTER_ANSWER_ERROR"
EMINIGAMEERRCODE_EMINIGAME_ERROR_MONSTER_ANSWER_ERROR_ENUM.index = 2
EMINIGAMEERRCODE_EMINIGAME_ERROR_MONSTER_ANSWER_ERROR_ENUM.number = 2
EMINIGAMEERRCODE_ENIMIGAME_ERROR_OVER_ALREADY_ENUM.name = "ENIMIGAME_ERROR_OVER_ALREADY"
EMINIGAMEERRCODE_ENIMIGAME_ERROR_OVER_ALREADY_ENUM.index = 3
EMINIGAMEERRCODE_ENIMIGAME_ERROR_OVER_ALREADY_ENUM.number = 3
EMINIGAMEERRCODE_ENIMIGAME_ERROR_NO_MAPRAID_ENUM.name = "ENIMIGAME_ERROR_NO_MAPRAID"
EMINIGAMEERRCODE_ENIMIGAME_ERROR_NO_MAPRAID_ENUM.index = 4
EMINIGAMEERRCODE_ENIMIGAME_ERROR_NO_MAPRAID_ENUM.number = 4
EMINIGAMEERRCODE_ENIMIGAME_ERROR_DIFFICULTY_ILLEGAL_ENUM.name = "ENIMIGAME_ERROR_DIFFICULTY_ILLEGAL"
EMINIGAMEERRCODE_ENIMIGAME_ERROR_DIFFICULTY_ILLEGAL_ENUM.index = 5
EMINIGAMEERRCODE_ENIMIGAME_ERROR_DIFFICULTY_ILLEGAL_ENUM.number = 5
EMINIGAMEERRCODE_ENIMIGAME_ERROR_TYPE_ILLEGAL_ENUM.name = "ENIMIGAME_ERROR_TYPE_ILLEGAL"
EMINIGAMEERRCODE_ENIMIGAME_ERROR_TYPE_ILLEGAL_ENUM.index = 6
EMINIGAMEERRCODE_ENIMIGAME_ERROR_TYPE_ILLEGAL_ENUM.number = 6
EMINIGAMEERRCODE_ENIMIGAME_ERROR_MAP_NOMATCH_ENUM.name = "ENIMIGAME_ERROR_MAP_NOMATCH"
EMINIGAMEERRCODE_ENIMIGAME_ERROR_MAP_NOMATCH_ENUM.index = 7
EMINIGAMEERRCODE_ENIMIGAME_ERROR_MAP_NOMATCH_ENUM.number = 7
EMINIGAMEERRCODE_ENIMIGAME_ERROR_REACH_LIMIT_ENUM.name = "ENIMIGAME_ERROR_REACH_LIMIT"
EMINIGAMEERRCODE_ENIMIGAME_ERROR_REACH_LIMIT_ENUM.index = 8
EMINIGAMEERRCODE_ENIMIGAME_ERROR_REACH_LIMIT_ENUM.number = 8
EMINIGAMEERRCODE_ENIMIGAME_ERROR_INGAME_ALREADY_ENUM.name = "ENIMIGAME_ERROR_INGAME_ALREADY"
EMINIGAMEERRCODE_ENIMIGAME_ERROR_INGAME_ALREADY_ENUM.index = 9
EMINIGAMEERRCODE_ENIMIGAME_ERROR_INGAME_ALREADY_ENUM.number = 9
EMINIGAMEERRCODE_ENIMIGAME_ERROR_NOT_INGAME_ENUM.name = "ENIMIGAME_ERROR_NOT_INGAME"
EMINIGAMEERRCODE_ENIMIGAME_ERROR_NOT_INGAME_ENUM.index = 10
EMINIGAMEERRCODE_ENIMIGAME_ERROR_NOT_INGAME_ENUM.number = 10
EMINIGAMEERRCODE.name = "EMiniGameErrcode"
EMINIGAMEERRCODE.full_name = ".Cmd.EMiniGameErrcode"
EMINIGAMEERRCODE.values = {
  EMINIGAMEERRCODE_EMINIGAME_ERROR_NONE_ENUM,
  EMINIGAMEERRCODE_EMINIGAME_ERROR_DIFFICULTY_NOT_UNLOCK_ENUM,
  EMINIGAMEERRCODE_EMINIGAME_ERROR_MONSTER_ANSWER_ERROR_ENUM,
  EMINIGAMEERRCODE_ENIMIGAME_ERROR_OVER_ALREADY_ENUM,
  EMINIGAMEERRCODE_ENIMIGAME_ERROR_NO_MAPRAID_ENUM,
  EMINIGAMEERRCODE_ENIMIGAME_ERROR_DIFFICULTY_ILLEGAL_ENUM,
  EMINIGAMEERRCODE_ENIMIGAME_ERROR_TYPE_ILLEGAL_ENUM,
  EMINIGAMEERRCODE_ENIMIGAME_ERROR_MAP_NOMATCH_ENUM,
  EMINIGAMEERRCODE_ENIMIGAME_ERROR_REACH_LIMIT_ENUM,
  EMINIGAMEERRCODE_ENIMIGAME_ERROR_INGAME_ALREADY_ENUM,
  EMINIGAMEERRCODE_ENIMIGAME_ERROR_NOT_INGAME_ENUM
}
EMINIGAMEOVERRESULT_EMINIGAME_OVER_WIN_ENUM.name = "EMINIGAME_OVER_WIN"
EMINIGAMEOVERRESULT_EMINIGAME_OVER_WIN_ENUM.index = 0
EMINIGAMEOVERRESULT_EMINIGAME_OVER_WIN_ENUM.number = 0
EMINIGAMEOVERRESULT_EMINIGAME_OVER_LOSE_ENUM.name = "EMINIGAME_OVER_LOSE"
EMINIGAMEOVERRESULT_EMINIGAME_OVER_LOSE_ENUM.index = 1
EMINIGAMEOVERRESULT_EMINIGAME_OVER_LOSE_ENUM.number = 1
EMINIGAMEOVERRESULT.name = "EMiniGameOverResult"
EMINIGAMEOVERRESULT.full_name = ".Cmd.EMiniGameOverResult"
EMINIGAMEOVERRESULT.values = {
  EMINIGAMEOVERRESULT_EMINIGAME_OVER_WIN_ENUM,
  EMINIGAMEOVERRESULT_EMINIGAME_OVER_LOSE_ENUM
}
EMONSTERSHOTCOMPARE_EMONSTERSHOT_COMPARE_NONE_ENUM.name = "EMONSTERSHOT_COMPARE_NONE"
EMONSTERSHOTCOMPARE_EMONSTERSHOT_COMPARE_NONE_ENUM.index = 0
EMONSTERSHOTCOMPARE_EMONSTERSHOT_COMPARE_NONE_ENUM.number = 0
EMONSTERSHOTCOMPARE_EMONSTERSHOT_COMPARE_LT_ENUM.name = "EMONSTERSHOT_COMPARE_LT"
EMONSTERSHOTCOMPARE_EMONSTERSHOT_COMPARE_LT_ENUM.index = 1
EMONSTERSHOTCOMPARE_EMONSTERSHOT_COMPARE_LT_ENUM.number = 1
EMONSTERSHOTCOMPARE_EMONSTERSHOT_COMPARE_EQ_ENUM.name = "EMONSTERSHOT_COMPARE_EQ"
EMONSTERSHOTCOMPARE_EMONSTERSHOT_COMPARE_EQ_ENUM.index = 2
EMONSTERSHOTCOMPARE_EMONSTERSHOT_COMPARE_EQ_ENUM.number = 2
EMONSTERSHOTCOMPARE_EMONSTERSHOT_COMPARE_GT_ENUM.name = "EMONSTERSHOT_COMPARE_GT"
EMONSTERSHOTCOMPARE_EMONSTERSHOT_COMPARE_GT_ENUM.index = 3
EMONSTERSHOTCOMPARE_EMONSTERSHOT_COMPARE_GT_ENUM.number = 3
EMONSTERSHOTCOMPARE.name = "EMonsterShotCompare"
EMONSTERSHOTCOMPARE.full_name = ".Cmd.EMonsterShotCompare"
EMONSTERSHOTCOMPARE.values = {
  EMONSTERSHOTCOMPARE_EMONSTERSHOT_COMPARE_NONE_ENUM,
  EMONSTERSHOTCOMPARE_EMONSTERSHOT_COMPARE_LT_ENUM,
  EMONSTERSHOTCOMPARE_EMONSTERSHOT_COMPARE_EQ_ENUM,
  EMONSTERSHOTCOMPARE_EMONSTERSHOT_COMPARE_GT_ENUM
}
EMONSTERANWSERQUESTTYPE_EMONSTERANWSER_QUESTTYPE_FEET_ENUM.name = "EMONSTERANWSER_QUESTTYPE_FEET"
EMONSTERANWSERQUESTTYPE_EMONSTERANWSER_QUESTTYPE_FEET_ENUM.index = 0
EMONSTERANWSERQUESTTYPE_EMONSTERANWSER_QUESTTYPE_FEET_ENUM.number = 0
EMONSTERANWSERQUESTTYPE_EMONSTERANWSER_QUESTTYPE_ELEMENT_ENUM.name = "EMONSTERANWSER_QUESTTYPE_ELEMENT"
EMONSTERANWSERQUESTTYPE_EMONSTERANWSER_QUESTTYPE_ELEMENT_ENUM.index = 1
EMONSTERANWSERQUESTTYPE_EMONSTERANWSER_QUESTTYPE_ELEMENT_ENUM.number = 1
EMONSTERANWSERQUESTTYPE_EMONSTERANWSER_QUESTTYPE_COLOR_ENUM.name = "EMONSTERANWSER_QUESTTYPE_COLOR"
EMONSTERANWSERQUESTTYPE_EMONSTERANWSER_QUESTTYPE_COLOR_ENUM.index = 2
EMONSTERANWSERQUESTTYPE_EMONSTERANWSER_QUESTTYPE_COLOR_ENUM.number = 2
EMONSTERANWSERQUESTTYPE_EMONSTERADIFFICULTYNWSER_QUESTTYPE_RACE_ENUM.name = "EMONSTERAdifficultyNWSER_QUESTTYPE_RACE"
EMONSTERANWSERQUESTTYPE_EMONSTERADIFFICULTYNWSER_QUESTTYPE_RACE_ENUM.index = 3
EMONSTERANWSERQUESTTYPE_EMONSTERADIFFICULTYNWSER_QUESTTYPE_RACE_ENUM.number = 3
EMONSTERANWSERQUESTTYPE_EMONSTERANWSER_QUESTTYPE_MAX_ENUM.name = "EMONSTERANWSER_QUESTTYPE_MAX"
EMONSTERANWSERQUESTTYPE_EMONSTERANWSER_QUESTTYPE_MAX_ENUM.index = 4
EMONSTERANWSERQUESTTYPE_EMONSTERANWSER_QUESTTYPE_MAX_ENUM.number = 4
EMONSTERANWSERQUESTTYPE.name = "EMonsterAnwserQuestType"
EMONSTERANWSERQUESTTYPE.full_name = ".Cmd.EMonsterAnwserQuestType"
EMONSTERANWSERQUESTTYPE.values = {
  EMONSTERANWSERQUESTTYPE_EMONSTERANWSER_QUESTTYPE_FEET_ENUM,
  EMONSTERANWSERQUESTTYPE_EMONSTERANWSER_QUESTTYPE_ELEMENT_ENUM,
  EMONSTERANWSERQUESTTYPE_EMONSTERANWSER_QUESTTYPE_COLOR_ENUM,
  EMONSTERANWSERQUESTTYPE_EMONSTERADIFFICULTYNWSER_QUESTTYPE_RACE_ENUM,
  EMONSTERANWSERQUESTTYPE_EMONSTERANWSER_QUESTTYPE_MAX_ENUM
}
EMONSTERANSWERLINKSYMBOL_EMONSTERANSWER_LINKSYMBOL_NONE_ENUM.name = "EMONSTERANSWER_LINKSYMBOL_NONE"
EMONSTERANSWERLINKSYMBOL_EMONSTERANSWER_LINKSYMBOL_NONE_ENUM.index = 0
EMONSTERANSWERLINKSYMBOL_EMONSTERANSWER_LINKSYMBOL_NONE_ENUM.number = 0
EMONSTERANSWERLINKSYMBOL_EMONSTERANSWER_LINKSYMBOL_AND_ENUM.name = "EMONSTERANSWER_LINKSYMBOL_AND"
EMONSTERANSWERLINKSYMBOL_EMONSTERANSWER_LINKSYMBOL_AND_ENUM.index = 1
EMONSTERANSWERLINKSYMBOL_EMONSTERANSWER_LINKSYMBOL_AND_ENUM.number = 1
EMONSTERANSWERLINKSYMBOL_EMONSTERANSWER_LINKSYMBOL_OR_ENUM.name = "EMONSTERANSWER_LINKSYMBOL_OR"
EMONSTERANSWERLINKSYMBOL_EMONSTERANSWER_LINKSYMBOL_OR_ENUM.index = 2
EMONSTERANSWERLINKSYMBOL_EMONSTERANSWER_LINKSYMBOL_OR_ENUM.number = 2
EMONSTERANSWERLINKSYMBOL.name = "EMonsterAnswerLinkSymbol"
EMONSTERANSWERLINKSYMBOL.full_name = ".Cmd.EMonsterAnswerLinkSymbol"
EMONSTERANSWERLINKSYMBOL.values = {
  EMONSTERANSWERLINKSYMBOL_EMONSTERANSWER_LINKSYMBOL_NONE_ENUM,
  EMONSTERANSWERLINKSYMBOL_EMONSTERANSWER_LINKSYMBOL_AND_ENUM,
  EMONSTERANSWERLINKSYMBOL_EMONSTERANSWER_LINKSYMBOL_OR_ENUM
}
ELASTREPLYSTATUS_ELASTREPLYSTATUS_NONE_ENUM.name = "ELASTREPLYSTATUS_NONE"
ELASTREPLYSTATUS_ELASTREPLYSTATUS_NONE_ENUM.index = 0
ELASTREPLYSTATUS_ELASTREPLYSTATUS_NONE_ENUM.number = 0
ELASTREPLYSTATUS_ELASTREPLYSTATUS_ERROR_ENUM.name = "ELASTREPLYSTATUS_ERROR"
ELASTREPLYSTATUS_ELASTREPLYSTATUS_ERROR_ENUM.index = 1
ELASTREPLYSTATUS_ELASTREPLYSTATUS_ERROR_ENUM.number = 1
ELASTREPLYSTATUS_ELASTREPLYSTATUS_RIGHT_ENUM.name = "ELASTREPLYSTATUS_RIGHT"
ELASTREPLYSTATUS_ELASTREPLYSTATUS_RIGHT_ENUM.index = 2
ELASTREPLYSTATUS_ELASTREPLYSTATUS_RIGHT_ENUM.number = 2
ELASTREPLYSTATUS.name = "ELastReplyStatus"
ELASTREPLYSTATUS.full_name = ".Cmd.ELastReplyStatus"
ELASTREPLYSTATUS.values = {
  ELASTREPLYSTATUS_ELASTREPLYSTATUS_NONE_ENUM,
  ELASTREPLYSTATUS_ELASTREPLYSTATUS_ERROR_ENUM,
  ELASTREPLYSTATUS_ELASTREPLYSTATUS_RIGHT_ENUM
}
EASSISTTYPE_EASSISTTYPE_ADDTIME_ENUM.name = "EASSISTTYPE_ADDTIME"
EASSISTTYPE_EASSISTTYPE_ADDTIME_ENUM.index = 0
EASSISTTYPE_EASSISTTYPE_ADDTIME_ENUM.number = 1
EASSISTTYPE_EASSISTTYPE_QUICK_FINISH_ENUM.name = "EASSISTTYPE_QUICK_FINISH"
EASSISTTYPE_EASSISTTYPE_QUICK_FINISH_ENUM.index = 1
EASSISTTYPE_EASSISTTYPE_QUICK_FINISH_ENUM.number = 2
EASSISTTYPE_EASSISTTYPE_TIPS_ENUM.name = "EASSISTTYPE_TIPS"
EASSISTTYPE_EASSISTTYPE_TIPS_ENUM.index = 2
EASSISTTYPE_EASSISTTYPE_TIPS_ENUM.number = 3
EASSISTTYPE.name = "EAssistType"
EASSISTTYPE.full_name = ".Cmd.EAssistType"
EASSISTTYPE.values = {
  EASSISTTYPE_EASSISTTYPE_ADDTIME_ENUM,
  EASSISTTYPE_EASSISTTYPE_QUICK_FINISH_ENUM,
  EASSISTTYPE_EASSISTTYPE_TIPS_ENUM
}
EMINIGAMEMODE_EMINIGAMEMODE_NORMAL_ENUM.name = "EMINIGAMEMODE_NORMAL"
EMINIGAMEMODE_EMINIGAMEMODE_NORMAL_ENUM.index = 0
EMINIGAMEMODE_EMINIGAMEMODE_NORMAL_ENUM.number = 1
EMINIGAMEMODE_EMINIGAMEMODE_CHALLENGE_ENUM.name = "EMINIGAMEMODE_CHALLENGE"
EMINIGAMEMODE_EMINIGAMEMODE_CHALLENGE_ENUM.index = 1
EMINIGAMEMODE_EMINIGAMEMODE_CHALLENGE_ENUM.number = 2
EMINIGAMEMODE.name = "EMinigameMode"
EMINIGAMEMODE.full_name = ".Cmd.EMinigameMode"
EMINIGAMEMODE.values = {
  EMINIGAMEMODE_EMINIGAMEMODE_NORMAL_ENUM,
  EMINIGAMEMODE_EMINIGAMEMODE_CHALLENGE_ENUM
}
MINIGAMEASSIST_TYPE_FIELD.name = "type"
MINIGAMEASSIST_TYPE_FIELD.full_name = ".Cmd.MiniGameAssist.type"
MINIGAMEASSIST_TYPE_FIELD.number = 1
MINIGAMEASSIST_TYPE_FIELD.index = 0
MINIGAMEASSIST_TYPE_FIELD.label = 1
MINIGAMEASSIST_TYPE_FIELD.has_default_value = false
MINIGAMEASSIST_TYPE_FIELD.default_value = nil
MINIGAMEASSIST_TYPE_FIELD.enum_type = EASSISTTYPE
MINIGAMEASSIST_TYPE_FIELD.type = 14
MINIGAMEASSIST_TYPE_FIELD.cpp_type = 8
MINIGAMEASSIST_COUNT_FIELD.name = "count"
MINIGAMEASSIST_COUNT_FIELD.full_name = ".Cmd.MiniGameAssist.count"
MINIGAMEASSIST_COUNT_FIELD.number = 2
MINIGAMEASSIST_COUNT_FIELD.index = 1
MINIGAMEASSIST_COUNT_FIELD.label = 1
MINIGAMEASSIST_COUNT_FIELD.has_default_value = false
MINIGAMEASSIST_COUNT_FIELD.default_value = 0
MINIGAMEASSIST_COUNT_FIELD.type = 13
MINIGAMEASSIST_COUNT_FIELD.cpp_type = 3
MINIGAMEASSIST_EFFECT_FIELD.name = "effect"
MINIGAMEASSIST_EFFECT_FIELD.full_name = ".Cmd.MiniGameAssist.effect"
MINIGAMEASSIST_EFFECT_FIELD.number = 3
MINIGAMEASSIST_EFFECT_FIELD.index = 2
MINIGAMEASSIST_EFFECT_FIELD.label = 1
MINIGAMEASSIST_EFFECT_FIELD.has_default_value = false
MINIGAMEASSIST_EFFECT_FIELD.default_value = 0
MINIGAMEASSIST_EFFECT_FIELD.type = 13
MINIGAMEASSIST_EFFECT_FIELD.cpp_type = 3
MINIGAMEASSIST.name = "MiniGameAssist"
MINIGAMEASSIST.full_name = ".Cmd.MiniGameAssist"
MINIGAMEASSIST.nested_types = {}
MINIGAMEASSIST.enum_types = {}
MINIGAMEASSIST.fields = {
  MINIGAMEASSIST_TYPE_FIELD,
  MINIGAMEASSIST_COUNT_FIELD,
  MINIGAMEASSIST_EFFECT_FIELD
}
MINIGAMEASSIST.is_extendable = false
MINIGAMEASSIST.extensions = {}
MONSTERSHOTREQUIREPAIR_CMPTYPE_FIELD.name = "cmptype"
MONSTERSHOTREQUIREPAIR_CMPTYPE_FIELD.full_name = ".Cmd.MonsterShotRequirePair.cmptype"
MONSTERSHOTREQUIREPAIR_CMPTYPE_FIELD.number = 1
MONSTERSHOTREQUIREPAIR_CMPTYPE_FIELD.index = 0
MONSTERSHOTREQUIREPAIR_CMPTYPE_FIELD.label = 1
MONSTERSHOTREQUIREPAIR_CMPTYPE_FIELD.has_default_value = true
MONSTERSHOTREQUIREPAIR_CMPTYPE_FIELD.default_value = 0
MONSTERSHOTREQUIREPAIR_CMPTYPE_FIELD.enum_type = EMONSTERSHOTCOMPARE
MONSTERSHOTREQUIREPAIR_CMPTYPE_FIELD.type = 14
MONSTERSHOTREQUIREPAIR_CMPTYPE_FIELD.cpp_type = 8
MONSTERSHOTREQUIREPAIR_VALUE_FIELD.name = "value"
MONSTERSHOTREQUIREPAIR_VALUE_FIELD.full_name = ".Cmd.MonsterShotRequirePair.value"
MONSTERSHOTREQUIREPAIR_VALUE_FIELD.number = 2
MONSTERSHOTREQUIREPAIR_VALUE_FIELD.index = 1
MONSTERSHOTREQUIREPAIR_VALUE_FIELD.label = 1
MONSTERSHOTREQUIREPAIR_VALUE_FIELD.has_default_value = true
MONSTERSHOTREQUIREPAIR_VALUE_FIELD.default_value = 0
MONSTERSHOTREQUIREPAIR_VALUE_FIELD.type = 13
MONSTERSHOTREQUIREPAIR_VALUE_FIELD.cpp_type = 3
MONSTERSHOTREQUIREPAIR_PLUSLEFT_FIELD.name = "plusleft"
MONSTERSHOTREQUIREPAIR_PLUSLEFT_FIELD.full_name = ".Cmd.MonsterShotRequirePair.plusleft"
MONSTERSHOTREQUIREPAIR_PLUSLEFT_FIELD.number = 3
MONSTERSHOTREQUIREPAIR_PLUSLEFT_FIELD.index = 2
MONSTERSHOTREQUIREPAIR_PLUSLEFT_FIELD.label = 1
MONSTERSHOTREQUIREPAIR_PLUSLEFT_FIELD.has_default_value = true
MONSTERSHOTREQUIREPAIR_PLUSLEFT_FIELD.default_value = 0
MONSTERSHOTREQUIREPAIR_PLUSLEFT_FIELD.type = 13
MONSTERSHOTREQUIREPAIR_PLUSLEFT_FIELD.cpp_type = 3
MONSTERSHOTREQUIREPAIR_PLUSRIGHT_FIELD.name = "plusright"
MONSTERSHOTREQUIREPAIR_PLUSRIGHT_FIELD.full_name = ".Cmd.MonsterShotRequirePair.plusright"
MONSTERSHOTREQUIREPAIR_PLUSRIGHT_FIELD.number = 4
MONSTERSHOTREQUIREPAIR_PLUSRIGHT_FIELD.index = 3
MONSTERSHOTREQUIREPAIR_PLUSRIGHT_FIELD.label = 1
MONSTERSHOTREQUIREPAIR_PLUSRIGHT_FIELD.has_default_value = true
MONSTERSHOTREQUIREPAIR_PLUSRIGHT_FIELD.default_value = 0
MONSTERSHOTREQUIREPAIR_PLUSRIGHT_FIELD.type = 13
MONSTERSHOTREQUIREPAIR_PLUSRIGHT_FIELD.cpp_type = 3
MONSTERSHOTREQUIREPAIR.name = "MonsterShotRequirePair"
MONSTERSHOTREQUIREPAIR.full_name = ".Cmd.MonsterShotRequirePair"
MONSTERSHOTREQUIREPAIR.nested_types = {}
MONSTERSHOTREQUIREPAIR.enum_types = {}
MONSTERSHOTREQUIREPAIR.fields = {
  MONSTERSHOTREQUIREPAIR_CMPTYPE_FIELD,
  MONSTERSHOTREQUIREPAIR_VALUE_FIELD,
  MONSTERSHOTREQUIREPAIR_PLUSLEFT_FIELD,
  MONSTERSHOTREQUIREPAIR_PLUSRIGHT_FIELD
}
MONSTERSHOTREQUIREPAIR.is_extendable = false
MONSTERSHOTREQUIREPAIR.extensions = {}
MINIGAMENTFMONSTERSHOT_CMD_FIELD.name = "cmd"
MINIGAMENTFMONSTERSHOT_CMD_FIELD.full_name = ".Cmd.MiniGameNtfMonsterShot.cmd"
MINIGAMENTFMONSTERSHOT_CMD_FIELD.number = 1
MINIGAMENTFMONSTERSHOT_CMD_FIELD.index = 0
MINIGAMENTFMONSTERSHOT_CMD_FIELD.label = 1
MINIGAMENTFMONSTERSHOT_CMD_FIELD.has_default_value = true
MINIGAMENTFMONSTERSHOT_CMD_FIELD.default_value = 223
MINIGAMENTFMONSTERSHOT_CMD_FIELD.enum_type = XCMD_PB_COMMAND
MINIGAMENTFMONSTERSHOT_CMD_FIELD.type = 14
MINIGAMENTFMONSTERSHOT_CMD_FIELD.cpp_type = 8
MINIGAMENTFMONSTERSHOT_PARAM_FIELD.name = "param"
MINIGAMENTFMONSTERSHOT_PARAM_FIELD.full_name = ".Cmd.MiniGameNtfMonsterShot.param"
MINIGAMENTFMONSTERSHOT_PARAM_FIELD.number = 2
MINIGAMENTFMONSTERSHOT_PARAM_FIELD.index = 1
MINIGAMENTFMONSTERSHOT_PARAM_FIELD.label = 1
MINIGAMENTFMONSTERSHOT_PARAM_FIELD.has_default_value = true
MINIGAMENTFMONSTERSHOT_PARAM_FIELD.default_value = 1
MINIGAMENTFMONSTERSHOT_PARAM_FIELD.enum_type = EMINIGAMECMDPARAM
MINIGAMENTFMONSTERSHOT_PARAM_FIELD.type = 14
MINIGAMENTFMONSTERSHOT_PARAM_FIELD.cpp_type = 8
MINIGAMENTFMONSTERSHOT_COUNTDOWN_FIELD.name = "countdown"
MINIGAMENTFMONSTERSHOT_COUNTDOWN_FIELD.full_name = ".Cmd.MiniGameNtfMonsterShot.countdown"
MINIGAMENTFMONSTERSHOT_COUNTDOWN_FIELD.number = 3
MINIGAMENTFMONSTERSHOT_COUNTDOWN_FIELD.index = 2
MINIGAMENTFMONSTERSHOT_COUNTDOWN_FIELD.label = 1
MINIGAMENTFMONSTERSHOT_COUNTDOWN_FIELD.has_default_value = true
MINIGAMENTFMONSTERSHOT_COUNTDOWN_FIELD.default_value = 0
MINIGAMENTFMONSTERSHOT_COUNTDOWN_FIELD.type = 13
MINIGAMENTFMONSTERSHOT_COUNTDOWN_FIELD.cpp_type = 3
MINIGAMENTFMONSTERSHOT_REQUIRES_FIELD.name = "requires"
MINIGAMENTFMONSTERSHOT_REQUIRES_FIELD.full_name = ".Cmd.MiniGameNtfMonsterShot.requires"
MINIGAMENTFMONSTERSHOT_REQUIRES_FIELD.number = 4
MINIGAMENTFMONSTERSHOT_REQUIRES_FIELD.index = 3
MINIGAMENTFMONSTERSHOT_REQUIRES_FIELD.label = 3
MINIGAMENTFMONSTERSHOT_REQUIRES_FIELD.has_default_value = false
MINIGAMENTFMONSTERSHOT_REQUIRES_FIELD.default_value = {}
MINIGAMENTFMONSTERSHOT_REQUIRES_FIELD.message_type = MONSTERSHOTREQUIREPAIR
MINIGAMENTFMONSTERSHOT_REQUIRES_FIELD.type = 11
MINIGAMENTFMONSTERSHOT_REQUIRES_FIELD.cpp_type = 10
MINIGAMENTFMONSTERSHOT_MISSTIMEREST_FIELD.name = "misstimerest"
MINIGAMENTFMONSTERSHOT_MISSTIMEREST_FIELD.full_name = ".Cmd.MiniGameNtfMonsterShot.misstimerest"
MINIGAMENTFMONSTERSHOT_MISSTIMEREST_FIELD.number = 5
MINIGAMENTFMONSTERSHOT_MISSTIMEREST_FIELD.index = 4
MINIGAMENTFMONSTERSHOT_MISSTIMEREST_FIELD.label = 1
MINIGAMENTFMONSTERSHOT_MISSTIMEREST_FIELD.has_default_value = true
MINIGAMENTFMONSTERSHOT_MISSTIMEREST_FIELD.default_value = 0
MINIGAMENTFMONSTERSHOT_MISSTIMEREST_FIELD.type = 13
MINIGAMENTFMONSTERSHOT_MISSTIMEREST_FIELD.cpp_type = 3
MINIGAMENTFMONSTERSHOT_TOTALROUNDS_FIELD.name = "totalrounds"
MINIGAMENTFMONSTERSHOT_TOTALROUNDS_FIELD.full_name = ".Cmd.MiniGameNtfMonsterShot.totalrounds"
MINIGAMENTFMONSTERSHOT_TOTALROUNDS_FIELD.number = 6
MINIGAMENTFMONSTERSHOT_TOTALROUNDS_FIELD.index = 5
MINIGAMENTFMONSTERSHOT_TOTALROUNDS_FIELD.label = 1
MINIGAMENTFMONSTERSHOT_TOTALROUNDS_FIELD.has_default_value = true
MINIGAMENTFMONSTERSHOT_TOTALROUNDS_FIELD.default_value = 0
MINIGAMENTFMONSTERSHOT_TOTALROUNDS_FIELD.type = 13
MINIGAMENTFMONSTERSHOT_TOTALROUNDS_FIELD.cpp_type = 3
MINIGAMENTFMONSTERSHOT_CURROUND_FIELD.name = "curround"
MINIGAMENTFMONSTERSHOT_CURROUND_FIELD.full_name = ".Cmd.MiniGameNtfMonsterShot.curround"
MINIGAMENTFMONSTERSHOT_CURROUND_FIELD.number = 7
MINIGAMENTFMONSTERSHOT_CURROUND_FIELD.index = 6
MINIGAMENTFMONSTERSHOT_CURROUND_FIELD.label = 1
MINIGAMENTFMONSTERSHOT_CURROUND_FIELD.has_default_value = true
MINIGAMENTFMONSTERSHOT_CURROUND_FIELD.default_value = 0
MINIGAMENTFMONSTERSHOT_CURROUND_FIELD.type = 13
MINIGAMENTFMONSTERSHOT_CURROUND_FIELD.cpp_type = 3
MINIGAMENTFMONSTERSHOT_USEPLUS_FIELD.name = "useplus"
MINIGAMENTFMONSTERSHOT_USEPLUS_FIELD.full_name = ".Cmd.MiniGameNtfMonsterShot.useplus"
MINIGAMENTFMONSTERSHOT_USEPLUS_FIELD.number = 8
MINIGAMENTFMONSTERSHOT_USEPLUS_FIELD.index = 7
MINIGAMENTFMONSTERSHOT_USEPLUS_FIELD.label = 1
MINIGAMENTFMONSTERSHOT_USEPLUS_FIELD.has_default_value = true
MINIGAMENTFMONSTERSHOT_USEPLUS_FIELD.default_value = false
MINIGAMENTFMONSTERSHOT_USEPLUS_FIELD.type = 8
MINIGAMENTFMONSTERSHOT_USEPLUS_FIELD.cpp_type = 7
MINIGAMENTFMONSTERSHOT.name = "MiniGameNtfMonsterShot"
MINIGAMENTFMONSTERSHOT.full_name = ".Cmd.MiniGameNtfMonsterShot"
MINIGAMENTFMONSTERSHOT.nested_types = {}
MINIGAMENTFMONSTERSHOT.enum_types = {}
MINIGAMENTFMONSTERSHOT.fields = {
  MINIGAMENTFMONSTERSHOT_CMD_FIELD,
  MINIGAMENTFMONSTERSHOT_PARAM_FIELD,
  MINIGAMENTFMONSTERSHOT_COUNTDOWN_FIELD,
  MINIGAMENTFMONSTERSHOT_REQUIRES_FIELD,
  MINIGAMENTFMONSTERSHOT_MISSTIMEREST_FIELD,
  MINIGAMENTFMONSTERSHOT_TOTALROUNDS_FIELD,
  MINIGAMENTFMONSTERSHOT_CURROUND_FIELD,
  MINIGAMENTFMONSTERSHOT_USEPLUS_FIELD
}
MINIGAMENTFMONSTERSHOT.is_extendable = false
MINIGAMENTFMONSTERSHOT.extensions = {}
MINIGAMEMONSTERSHOTACTION_CMD_FIELD.name = "cmd"
MINIGAMEMONSTERSHOTACTION_CMD_FIELD.full_name = ".Cmd.MiniGameMonsterShotAction.cmd"
MINIGAMEMONSTERSHOTACTION_CMD_FIELD.number = 1
MINIGAMEMONSTERSHOTACTION_CMD_FIELD.index = 0
MINIGAMEMONSTERSHOTACTION_CMD_FIELD.label = 1
MINIGAMEMONSTERSHOTACTION_CMD_FIELD.has_default_value = true
MINIGAMEMONSTERSHOTACTION_CMD_FIELD.default_value = 223
MINIGAMEMONSTERSHOTACTION_CMD_FIELD.enum_type = XCMD_PB_COMMAND
MINIGAMEMONSTERSHOTACTION_CMD_FIELD.type = 14
MINIGAMEMONSTERSHOTACTION_CMD_FIELD.cpp_type = 8
MINIGAMEMONSTERSHOTACTION_PARAM_FIELD.name = "param"
MINIGAMEMONSTERSHOTACTION_PARAM_FIELD.full_name = ".Cmd.MiniGameMonsterShotAction.param"
MINIGAMEMONSTERSHOTACTION_PARAM_FIELD.number = 2
MINIGAMEMONSTERSHOTACTION_PARAM_FIELD.index = 1
MINIGAMEMONSTERSHOTACTION_PARAM_FIELD.label = 1
MINIGAMEMONSTERSHOTACTION_PARAM_FIELD.has_default_value = true
MINIGAMEMONSTERSHOTACTION_PARAM_FIELD.default_value = 2
MINIGAMEMONSTERSHOTACTION_PARAM_FIELD.enum_type = EMINIGAMECMDPARAM
MINIGAMEMONSTERSHOTACTION_PARAM_FIELD.type = 14
MINIGAMEMONSTERSHOTACTION_PARAM_FIELD.cpp_type = 8
MINIGAMEMONSTERSHOTACTION_CLIENTJUDGESUC_FIELD.name = "clientjudgesuc"
MINIGAMEMONSTERSHOTACTION_CLIENTJUDGESUC_FIELD.full_name = ".Cmd.MiniGameMonsterShotAction.clientjudgesuc"
MINIGAMEMONSTERSHOTACTION_CLIENTJUDGESUC_FIELD.number = 3
MINIGAMEMONSTERSHOTACTION_CLIENTJUDGESUC_FIELD.index = 2
MINIGAMEMONSTERSHOTACTION_CLIENTJUDGESUC_FIELD.label = 1
MINIGAMEMONSTERSHOTACTION_CLIENTJUDGESUC_FIELD.has_default_value = true
MINIGAMEMONSTERSHOTACTION_CLIENTJUDGESUC_FIELD.default_value = false
MINIGAMEMONSTERSHOTACTION_CLIENTJUDGESUC_FIELD.type = 8
MINIGAMEMONSTERSHOTACTION_CLIENTJUDGESUC_FIELD.cpp_type = 7
MINIGAMEMONSTERSHOTACTION_ERRCODE_FIELD.name = "errcode"
MINIGAMEMONSTERSHOTACTION_ERRCODE_FIELD.full_name = ".Cmd.MiniGameMonsterShotAction.errcode"
MINIGAMEMONSTERSHOTACTION_ERRCODE_FIELD.number = 4
MINIGAMEMONSTERSHOTACTION_ERRCODE_FIELD.index = 3
MINIGAMEMONSTERSHOTACTION_ERRCODE_FIELD.label = 1
MINIGAMEMONSTERSHOTACTION_ERRCODE_FIELD.has_default_value = true
MINIGAMEMONSTERSHOTACTION_ERRCODE_FIELD.default_value = 0
MINIGAMEMONSTERSHOTACTION_ERRCODE_FIELD.enum_type = EMINIGAMEERRCODE
MINIGAMEMONSTERSHOTACTION_ERRCODE_FIELD.type = 14
MINIGAMEMONSTERSHOTACTION_ERRCODE_FIELD.cpp_type = 8
MINIGAMEMONSTERSHOTACTION.name = "MiniGameMonsterShotAction"
MINIGAMEMONSTERSHOTACTION.full_name = ".Cmd.MiniGameMonsterShotAction"
MINIGAMEMONSTERSHOTACTION.nested_types = {}
MINIGAMEMONSTERSHOTACTION.enum_types = {}
MINIGAMEMONSTERSHOTACTION.fields = {
  MINIGAMEMONSTERSHOTACTION_CMD_FIELD,
  MINIGAMEMONSTERSHOTACTION_PARAM_FIELD,
  MINIGAMEMONSTERSHOTACTION_CLIENTJUDGESUC_FIELD,
  MINIGAMEMONSTERSHOTACTION_ERRCODE_FIELD
}
MINIGAMEMONSTERSHOTACTION.is_extendable = false
MINIGAMEMONSTERSHOTACTION.extensions = {}
MONSTERANSWERQUESTPART_TYPE_FIELD.name = "type"
MONSTERANSWERQUESTPART_TYPE_FIELD.full_name = ".Cmd.MonsterAnswerQuestPart.type"
MONSTERANSWERQUESTPART_TYPE_FIELD.number = 1
MONSTERANSWERQUESTPART_TYPE_FIELD.index = 0
MONSTERANSWERQUESTPART_TYPE_FIELD.label = 1
MONSTERANSWERQUESTPART_TYPE_FIELD.has_default_value = true
MONSTERANSWERQUESTPART_TYPE_FIELD.default_value = 0
MONSTERANSWERQUESTPART_TYPE_FIELD.enum_type = EMONSTERANWSERQUESTTYPE
MONSTERANSWERQUESTPART_TYPE_FIELD.type = 14
MONSTERANSWERQUESTPART_TYPE_FIELD.cpp_type = 8
MONSTERANSWERQUESTPART_SUBPARAM_FIELD.name = "subparam"
MONSTERANSWERQUESTPART_SUBPARAM_FIELD.full_name = ".Cmd.MonsterAnswerQuestPart.subparam"
MONSTERANSWERQUESTPART_SUBPARAM_FIELD.number = 2
MONSTERANSWERQUESTPART_SUBPARAM_FIELD.index = 1
MONSTERANSWERQUESTPART_SUBPARAM_FIELD.label = 1
MONSTERANSWERQUESTPART_SUBPARAM_FIELD.has_default_value = false
MONSTERANSWERQUESTPART_SUBPARAM_FIELD.default_value = 0
MONSTERANSWERQUESTPART_SUBPARAM_FIELD.type = 13
MONSTERANSWERQUESTPART_SUBPARAM_FIELD.cpp_type = 3
MONSTERANSWERQUESTPART.name = "MonsterAnswerQuestPart"
MONSTERANSWERQUESTPART.full_name = ".Cmd.MonsterAnswerQuestPart"
MONSTERANSWERQUESTPART.nested_types = {}
MONSTERANSWERQUESTPART.enum_types = {}
MONSTERANSWERQUESTPART.fields = {
  MONSTERANSWERQUESTPART_TYPE_FIELD,
  MONSTERANSWERQUESTPART_SUBPARAM_FIELD
}
MONSTERANSWERQUESTPART.is_extendable = false
MONSTERANSWERQUESTPART.extensions = {}
MINIGAMENTFMONSTERANSWER_CMD_FIELD.name = "cmd"
MINIGAMENTFMONSTERANSWER_CMD_FIELD.full_name = ".Cmd.MiniGameNtfMonsterAnswer.cmd"
MINIGAMENTFMONSTERANSWER_CMD_FIELD.number = 1
MINIGAMENTFMONSTERANSWER_CMD_FIELD.index = 0
MINIGAMENTFMONSTERANSWER_CMD_FIELD.label = 1
MINIGAMENTFMONSTERANSWER_CMD_FIELD.has_default_value = true
MINIGAMENTFMONSTERANSWER_CMD_FIELD.default_value = 223
MINIGAMENTFMONSTERANSWER_CMD_FIELD.enum_type = XCMD_PB_COMMAND
MINIGAMENTFMONSTERANSWER_CMD_FIELD.type = 14
MINIGAMENTFMONSTERANSWER_CMD_FIELD.cpp_type = 8
MINIGAMENTFMONSTERANSWER_PARAM_FIELD.name = "param"
MINIGAMENTFMONSTERANSWER_PARAM_FIELD.full_name = ".Cmd.MiniGameNtfMonsterAnswer.param"
MINIGAMENTFMONSTERANSWER_PARAM_FIELD.number = 2
MINIGAMENTFMONSTERANSWER_PARAM_FIELD.index = 1
MINIGAMENTFMONSTERANSWER_PARAM_FIELD.label = 1
MINIGAMENTFMONSTERANSWER_PARAM_FIELD.has_default_value = true
MINIGAMENTFMONSTERANSWER_PARAM_FIELD.default_value = 9
MINIGAMENTFMONSTERANSWER_PARAM_FIELD.enum_type = EMINIGAMECMDPARAM
MINIGAMENTFMONSTERANSWER_PARAM_FIELD.type = 14
MINIGAMENTFMONSTERANSWER_PARAM_FIELD.cpp_type = 8
MINIGAMENTFMONSTERANSWER_COUNTDOWN_FIELD.name = "countdown"
MINIGAMENTFMONSTERANSWER_COUNTDOWN_FIELD.full_name = ".Cmd.MiniGameNtfMonsterAnswer.countdown"
MINIGAMENTFMONSTERANSWER_COUNTDOWN_FIELD.number = 3
MINIGAMENTFMONSTERANSWER_COUNTDOWN_FIELD.index = 2
MINIGAMENTFMONSTERANSWER_COUNTDOWN_FIELD.label = 1
MINIGAMENTFMONSTERANSWER_COUNTDOWN_FIELD.has_default_value = true
MINIGAMENTFMONSTERANSWER_COUNTDOWN_FIELD.default_value = 0
MINIGAMENTFMONSTERANSWER_COUNTDOWN_FIELD.type = 13
MINIGAMENTFMONSTERANSWER_COUNTDOWN_FIELD.cpp_type = 3
MINIGAMENTFMONSTERANSWER_LINKSYMBOL_FIELD.name = "linksymbol"
MINIGAMENTFMONSTERANSWER_LINKSYMBOL_FIELD.full_name = ".Cmd.MiniGameNtfMonsterAnswer.linksymbol"
MINIGAMENTFMONSTERANSWER_LINKSYMBOL_FIELD.number = 4
MINIGAMENTFMONSTERANSWER_LINKSYMBOL_FIELD.index = 3
MINIGAMENTFMONSTERANSWER_LINKSYMBOL_FIELD.label = 1
MINIGAMENTFMONSTERANSWER_LINKSYMBOL_FIELD.has_default_value = true
MINIGAMENTFMONSTERANSWER_LINKSYMBOL_FIELD.default_value = 0
MINIGAMENTFMONSTERANSWER_LINKSYMBOL_FIELD.enum_type = EMONSTERANSWERLINKSYMBOL
MINIGAMENTFMONSTERANSWER_LINKSYMBOL_FIELD.type = 14
MINIGAMENTFMONSTERANSWER_LINKSYMBOL_FIELD.cpp_type = 8
MINIGAMENTFMONSTERANSWER_QUESTPARTS_FIELD.name = "questparts"
MINIGAMENTFMONSTERANSWER_QUESTPARTS_FIELD.full_name = ".Cmd.MiniGameNtfMonsterAnswer.questparts"
MINIGAMENTFMONSTERANSWER_QUESTPARTS_FIELD.number = 5
MINIGAMENTFMONSTERANSWER_QUESTPARTS_FIELD.index = 4
MINIGAMENTFMONSTERANSWER_QUESTPARTS_FIELD.label = 3
MINIGAMENTFMONSTERANSWER_QUESTPARTS_FIELD.has_default_value = false
MINIGAMENTFMONSTERANSWER_QUESTPARTS_FIELD.default_value = {}
MINIGAMENTFMONSTERANSWER_QUESTPARTS_FIELD.message_type = MONSTERANSWERQUESTPART
MINIGAMENTFMONSTERANSWER_QUESTPARTS_FIELD.type = 11
MINIGAMENTFMONSTERANSWER_QUESTPARTS_FIELD.cpp_type = 10
MINIGAMENTFMONSTERANSWER_LASTREPLYSTATUS_FIELD.name = "lastreplystatus"
MINIGAMENTFMONSTERANSWER_LASTREPLYSTATUS_FIELD.full_name = ".Cmd.MiniGameNtfMonsterAnswer.lastreplystatus"
MINIGAMENTFMONSTERANSWER_LASTREPLYSTATUS_FIELD.number = 6
MINIGAMENTFMONSTERANSWER_LASTREPLYSTATUS_FIELD.index = 5
MINIGAMENTFMONSTERANSWER_LASTREPLYSTATUS_FIELD.label = 1
MINIGAMENTFMONSTERANSWER_LASTREPLYSTATUS_FIELD.has_default_value = true
MINIGAMENTFMONSTERANSWER_LASTREPLYSTATUS_FIELD.default_value = 0
MINIGAMENTFMONSTERANSWER_LASTREPLYSTATUS_FIELD.enum_type = ELASTREPLYSTATUS
MINIGAMENTFMONSTERANSWER_LASTREPLYSTATUS_FIELD.type = 14
MINIGAMENTFMONSTERANSWER_LASTREPLYSTATUS_FIELD.cpp_type = 8
MINIGAMENTFMONSTERANSWER.name = "MiniGameNtfMonsterAnswer"
MINIGAMENTFMONSTERANSWER.full_name = ".Cmd.MiniGameNtfMonsterAnswer"
MINIGAMENTFMONSTERANSWER.nested_types = {}
MINIGAMENTFMONSTERANSWER.enum_types = {}
MINIGAMENTFMONSTERANSWER.fields = {
  MINIGAMENTFMONSTERANSWER_CMD_FIELD,
  MINIGAMENTFMONSTERANSWER_PARAM_FIELD,
  MINIGAMENTFMONSTERANSWER_COUNTDOWN_FIELD,
  MINIGAMENTFMONSTERANSWER_LINKSYMBOL_FIELD,
  MINIGAMENTFMONSTERANSWER_QUESTPARTS_FIELD,
  MINIGAMENTFMONSTERANSWER_LASTREPLYSTATUS_FIELD
}
MINIGAMENTFMONSTERANSWER.is_extendable = false
MINIGAMENTFMONSTERANSWER.extensions = {}
MINIGAMESUBMITMONSTERANSWER_CMD_FIELD.name = "cmd"
MINIGAMESUBMITMONSTERANSWER_CMD_FIELD.full_name = ".Cmd.MiniGameSubmitMonsterAnswer.cmd"
MINIGAMESUBMITMONSTERANSWER_CMD_FIELD.number = 1
MINIGAMESUBMITMONSTERANSWER_CMD_FIELD.index = 0
MINIGAMESUBMITMONSTERANSWER_CMD_FIELD.label = 1
MINIGAMESUBMITMONSTERANSWER_CMD_FIELD.has_default_value = true
MINIGAMESUBMITMONSTERANSWER_CMD_FIELD.default_value = 223
MINIGAMESUBMITMONSTERANSWER_CMD_FIELD.enum_type = XCMD_PB_COMMAND
MINIGAMESUBMITMONSTERANSWER_CMD_FIELD.type = 14
MINIGAMESUBMITMONSTERANSWER_CMD_FIELD.cpp_type = 8
MINIGAMESUBMITMONSTERANSWER_PARAM_FIELD.name = "param"
MINIGAMESUBMITMONSTERANSWER_PARAM_FIELD.full_name = ".Cmd.MiniGameSubmitMonsterAnswer.param"
MINIGAMESUBMITMONSTERANSWER_PARAM_FIELD.number = 2
MINIGAMESUBMITMONSTERANSWER_PARAM_FIELD.index = 1
MINIGAMESUBMITMONSTERANSWER_PARAM_FIELD.label = 1
MINIGAMESUBMITMONSTERANSWER_PARAM_FIELD.has_default_value = true
MINIGAMESUBMITMONSTERANSWER_PARAM_FIELD.default_value = 10
MINIGAMESUBMITMONSTERANSWER_PARAM_FIELD.enum_type = EMINIGAMECMDPARAM
MINIGAMESUBMITMONSTERANSWER_PARAM_FIELD.type = 14
MINIGAMESUBMITMONSTERANSWER_PARAM_FIELD.cpp_type = 8
MINIGAMESUBMITMONSTERANSWER_ANSWER_FIELD.name = "answer"
MINIGAMESUBMITMONSTERANSWER_ANSWER_FIELD.full_name = ".Cmd.MiniGameSubmitMonsterAnswer.answer"
MINIGAMESUBMITMONSTERANSWER_ANSWER_FIELD.number = 3
MINIGAMESUBMITMONSTERANSWER_ANSWER_FIELD.index = 2
MINIGAMESUBMITMONSTERANSWER_ANSWER_FIELD.label = 1
MINIGAMESUBMITMONSTERANSWER_ANSWER_FIELD.has_default_value = true
MINIGAMESUBMITMONSTERANSWER_ANSWER_FIELD.default_value = 0
MINIGAMESUBMITMONSTERANSWER_ANSWER_FIELD.type = 13
MINIGAMESUBMITMONSTERANSWER_ANSWER_FIELD.cpp_type = 3
MINIGAMESUBMITMONSTERANSWER.name = "MiniGameSubmitMonsterAnswer"
MINIGAMESUBMITMONSTERANSWER.full_name = ".Cmd.MiniGameSubmitMonsterAnswer"
MINIGAMESUBMITMONSTERANSWER.nested_types = {}
MINIGAMESUBMITMONSTERANSWER.enum_types = {}
MINIGAMESUBMITMONSTERANSWER.fields = {
  MINIGAMESUBMITMONSTERANSWER_CMD_FIELD,
  MINIGAMESUBMITMONSTERANSWER_PARAM_FIELD,
  MINIGAMESUBMITMONSTERANSWER_ANSWER_FIELD
}
MINIGAMESUBMITMONSTERANSWER.is_extendable = false
MINIGAMESUBMITMONSTERANSWER.extensions = {}
MINIGAMEACTION_CMD_FIELD.name = "cmd"
MINIGAMEACTION_CMD_FIELD.full_name = ".Cmd.MiniGameAction.cmd"
MINIGAMEACTION_CMD_FIELD.number = 1
MINIGAMEACTION_CMD_FIELD.index = 0
MINIGAMEACTION_CMD_FIELD.label = 1
MINIGAMEACTION_CMD_FIELD.has_default_value = true
MINIGAMEACTION_CMD_FIELD.default_value = 223
MINIGAMEACTION_CMD_FIELD.enum_type = XCMD_PB_COMMAND
MINIGAMEACTION_CMD_FIELD.type = 14
MINIGAMEACTION_CMD_FIELD.cpp_type = 8
MINIGAMEACTION_PARAM_FIELD.name = "param"
MINIGAMEACTION_PARAM_FIELD.full_name = ".Cmd.MiniGameAction.param"
MINIGAMEACTION_PARAM_FIELD.number = 2
MINIGAMEACTION_PARAM_FIELD.index = 1
MINIGAMEACTION_PARAM_FIELD.label = 1
MINIGAMEACTION_PARAM_FIELD.has_default_value = true
MINIGAMEACTION_PARAM_FIELD.default_value = 13
MINIGAMEACTION_PARAM_FIELD.enum_type = EMINIGAMECMDPARAM
MINIGAMEACTION_PARAM_FIELD.type = 14
MINIGAMEACTION_PARAM_FIELD.cpp_type = 8
MINIGAMEACTION_MODE_FIELD.name = "mode"
MINIGAMEACTION_MODE_FIELD.full_name = ".Cmd.MiniGameAction.mode"
MINIGAMEACTION_MODE_FIELD.number = 3
MINIGAMEACTION_MODE_FIELD.index = 2
MINIGAMEACTION_MODE_FIELD.label = 1
MINIGAMEACTION_MODE_FIELD.has_default_value = true
MINIGAMEACTION_MODE_FIELD.default_value = 1
MINIGAMEACTION_MODE_FIELD.enum_type = EMINIGAMEMODE
MINIGAMEACTION_MODE_FIELD.type = 14
MINIGAMEACTION_MODE_FIELD.cpp_type = 8
MINIGAMEACTION_GAMETYPE_FIELD.name = "gametype"
MINIGAMEACTION_GAMETYPE_FIELD.full_name = ".Cmd.MiniGameAction.gametype"
MINIGAMEACTION_GAMETYPE_FIELD.number = 4
MINIGAMEACTION_GAMETYPE_FIELD.index = 3
MINIGAMEACTION_GAMETYPE_FIELD.label = 1
MINIGAMEACTION_GAMETYPE_FIELD.has_default_value = true
MINIGAMEACTION_GAMETYPE_FIELD.default_value = 0
MINIGAMEACTION_GAMETYPE_FIELD.enum_type = EMINIGAMETYPE
MINIGAMEACTION_GAMETYPE_FIELD.type = 14
MINIGAMEACTION_GAMETYPE_FIELD.cpp_type = 8
MINIGAMEACTION_DIFFICULTY_FIELD.name = "difficulty"
MINIGAMEACTION_DIFFICULTY_FIELD.full_name = ".Cmd.MiniGameAction.difficulty"
MINIGAMEACTION_DIFFICULTY_FIELD.number = 5
MINIGAMEACTION_DIFFICULTY_FIELD.index = 4
MINIGAMEACTION_DIFFICULTY_FIELD.label = 1
MINIGAMEACTION_DIFFICULTY_FIELD.has_default_value = false
MINIGAMEACTION_DIFFICULTY_FIELD.default_value = 0
MINIGAMEACTION_DIFFICULTY_FIELD.type = 13
MINIGAMEACTION_DIFFICULTY_FIELD.cpp_type = 3
MINIGAMEACTION_ERRCODE_FIELD.name = "errcode"
MINIGAMEACTION_ERRCODE_FIELD.full_name = ".Cmd.MiniGameAction.errcode"
MINIGAMEACTION_ERRCODE_FIELD.number = 6
MINIGAMEACTION_ERRCODE_FIELD.index = 5
MINIGAMEACTION_ERRCODE_FIELD.label = 1
MINIGAMEACTION_ERRCODE_FIELD.has_default_value = true
MINIGAMEACTION_ERRCODE_FIELD.default_value = 0
MINIGAMEACTION_ERRCODE_FIELD.enum_type = EMINIGAMEERRCODE
MINIGAMEACTION_ERRCODE_FIELD.type = 14
MINIGAMEACTION_ERRCODE_FIELD.cpp_type = 8
MINIGAMEACTION_ENDCARDPAIR_FIELD.name = "endcardpair"
MINIGAMEACTION_ENDCARDPAIR_FIELD.full_name = ".Cmd.MiniGameAction.endcardpair"
MINIGAMEACTION_ENDCARDPAIR_FIELD.number = 7
MINIGAMEACTION_ENDCARDPAIR_FIELD.index = 6
MINIGAMEACTION_ENDCARDPAIR_FIELD.label = 1
MINIGAMEACTION_ENDCARDPAIR_FIELD.has_default_value = true
MINIGAMEACTION_ENDCARDPAIR_FIELD.default_value = false
MINIGAMEACTION_ENDCARDPAIR_FIELD.type = 8
MINIGAMEACTION_ENDCARDPAIR_FIELD.cpp_type = 7
MINIGAMEACTION_ADDSECONDS_FIELD.name = "addseconds"
MINIGAMEACTION_ADDSECONDS_FIELD.full_name = ".Cmd.MiniGameAction.addseconds"
MINIGAMEACTION_ADDSECONDS_FIELD.number = 8
MINIGAMEACTION_ADDSECONDS_FIELD.index = 7
MINIGAMEACTION_ADDSECONDS_FIELD.label = 1
MINIGAMEACTION_ADDSECONDS_FIELD.has_default_value = true
MINIGAMEACTION_ADDSECONDS_FIELD.default_value = 0
MINIGAMEACTION_ADDSECONDS_FIELD.type = 13
MINIGAMEACTION_ADDSECONDS_FIELD.cpp_type = 3
MINIGAMEACTION_MINUSSECONDS_FIELD.name = "minusseconds"
MINIGAMEACTION_MINUSSECONDS_FIELD.full_name = ".Cmd.MiniGameAction.minusseconds"
MINIGAMEACTION_MINUSSECONDS_FIELD.number = 9
MINIGAMEACTION_MINUSSECONDS_FIELD.index = 8
MINIGAMEACTION_MINUSSECONDS_FIELD.label = 1
MINIGAMEACTION_MINUSSECONDS_FIELD.has_default_value = true
MINIGAMEACTION_MINUSSECONDS_FIELD.default_value = 0
MINIGAMEACTION_MINUSSECONDS_FIELD.type = 13
MINIGAMEACTION_MINUSSECONDS_FIELD.cpp_type = 3
MINIGAMEACTION_ENDTIME_FIELD.name = "endtime"
MINIGAMEACTION_ENDTIME_FIELD.full_name = ".Cmd.MiniGameAction.endtime"
MINIGAMEACTION_ENDTIME_FIELD.number = 10
MINIGAMEACTION_ENDTIME_FIELD.index = 9
MINIGAMEACTION_ENDTIME_FIELD.label = 1
MINIGAMEACTION_ENDTIME_FIELD.has_default_value = true
MINIGAMEACTION_ENDTIME_FIELD.default_value = 0
MINIGAMEACTION_ENDTIME_FIELD.type = 13
MINIGAMEACTION_ENDTIME_FIELD.cpp_type = 3
MINIGAMEACTION_CARDFAILFORCE_FIELD.name = "cardfailforce"
MINIGAMEACTION_CARDFAILFORCE_FIELD.full_name = ".Cmd.MiniGameAction.cardfailforce"
MINIGAMEACTION_CARDFAILFORCE_FIELD.number = 11
MINIGAMEACTION_CARDFAILFORCE_FIELD.index = 10
MINIGAMEACTION_CARDFAILFORCE_FIELD.label = 1
MINIGAMEACTION_CARDFAILFORCE_FIELD.has_default_value = true
MINIGAMEACTION_CARDFAILFORCE_FIELD.default_value = false
MINIGAMEACTION_CARDFAILFORCE_FIELD.type = 8
MINIGAMEACTION_CARDFAILFORCE_FIELD.cpp_type = 7
MINIGAMEACTION_ROUNDENDFLAG_FIELD.name = "roundendflag"
MINIGAMEACTION_ROUNDENDFLAG_FIELD.full_name = ".Cmd.MiniGameAction.roundendflag"
MINIGAMEACTION_ROUNDENDFLAG_FIELD.number = 12
MINIGAMEACTION_ROUNDENDFLAG_FIELD.index = 11
MINIGAMEACTION_ROUNDENDFLAG_FIELD.label = 1
MINIGAMEACTION_ROUNDENDFLAG_FIELD.has_default_value = false
MINIGAMEACTION_ROUNDENDFLAG_FIELD.default_value = false
MINIGAMEACTION_ROUNDENDFLAG_FIELD.type = 8
MINIGAMEACTION_ROUNDENDFLAG_FIELD.cpp_type = 7
MINIGAMEACTION.name = "MiniGameAction"
MINIGAMEACTION.full_name = ".Cmd.MiniGameAction"
MINIGAMEACTION.nested_types = {}
MINIGAMEACTION.enum_types = {}
MINIGAMEACTION.fields = {
  MINIGAMEACTION_CMD_FIELD,
  MINIGAMEACTION_PARAM_FIELD,
  MINIGAMEACTION_MODE_FIELD,
  MINIGAMEACTION_GAMETYPE_FIELD,
  MINIGAMEACTION_DIFFICULTY_FIELD,
  MINIGAMEACTION_ERRCODE_FIELD,
  MINIGAMEACTION_ENDCARDPAIR_FIELD,
  MINIGAMEACTION_ADDSECONDS_FIELD,
  MINIGAMEACTION_MINUSSECONDS_FIELD,
  MINIGAMEACTION_ENDTIME_FIELD,
  MINIGAMEACTION_CARDFAILFORCE_FIELD,
  MINIGAMEACTION_ROUNDENDFLAG_FIELD
}
MINIGAMEACTION.is_extendable = false
MINIGAMEACTION.extensions = {}
MINIGAMENEXTROUND_CMD_FIELD.name = "cmd"
MINIGAMENEXTROUND_CMD_FIELD.full_name = ".Cmd.MiniGameNextRound.cmd"
MINIGAMENEXTROUND_CMD_FIELD.number = 1
MINIGAMENEXTROUND_CMD_FIELD.index = 0
MINIGAMENEXTROUND_CMD_FIELD.label = 1
MINIGAMENEXTROUND_CMD_FIELD.has_default_value = true
MINIGAMENEXTROUND_CMD_FIELD.default_value = 223
MINIGAMENEXTROUND_CMD_FIELD.enum_type = XCMD_PB_COMMAND
MINIGAMENEXTROUND_CMD_FIELD.type = 14
MINIGAMENEXTROUND_CMD_FIELD.cpp_type = 8
MINIGAMENEXTROUND_PARAM_FIELD.name = "param"
MINIGAMENEXTROUND_PARAM_FIELD.full_name = ".Cmd.MiniGameNextRound.param"
MINIGAMENEXTROUND_PARAM_FIELD.number = 2
MINIGAMENEXTROUND_PARAM_FIELD.index = 1
MINIGAMENEXTROUND_PARAM_FIELD.label = 1
MINIGAMENEXTROUND_PARAM_FIELD.has_default_value = true
MINIGAMENEXTROUND_PARAM_FIELD.default_value = 14
MINIGAMENEXTROUND_PARAM_FIELD.enum_type = EMINIGAMECMDPARAM
MINIGAMENEXTROUND_PARAM_FIELD.type = 14
MINIGAMENEXTROUND_PARAM_FIELD.cpp_type = 8
MINIGAMENEXTROUND_GAMETYPE_FIELD.name = "gametype"
MINIGAMENEXTROUND_GAMETYPE_FIELD.full_name = ".Cmd.MiniGameNextRound.gametype"
MINIGAMENEXTROUND_GAMETYPE_FIELD.number = 3
MINIGAMENEXTROUND_GAMETYPE_FIELD.index = 2
MINIGAMENEXTROUND_GAMETYPE_FIELD.label = 1
MINIGAMENEXTROUND_GAMETYPE_FIELD.has_default_value = true
MINIGAMENEXTROUND_GAMETYPE_FIELD.default_value = 0
MINIGAMENEXTROUND_GAMETYPE_FIELD.enum_type = EMINIGAMETYPE
MINIGAMENEXTROUND_GAMETYPE_FIELD.type = 14
MINIGAMENEXTROUND_GAMETYPE_FIELD.cpp_type = 8
MINIGAMENEXTROUND_ASSISTLIST_FIELD.name = "assistlist"
MINIGAMENEXTROUND_ASSISTLIST_FIELD.full_name = ".Cmd.MiniGameNextRound.assistlist"
MINIGAMENEXTROUND_ASSISTLIST_FIELD.number = 4
MINIGAMENEXTROUND_ASSISTLIST_FIELD.index = 3
MINIGAMENEXTROUND_ASSISTLIST_FIELD.label = 3
MINIGAMENEXTROUND_ASSISTLIST_FIELD.has_default_value = false
MINIGAMENEXTROUND_ASSISTLIST_FIELD.default_value = {}
MINIGAMENEXTROUND_ASSISTLIST_FIELD.message_type = MINIGAMEASSIST
MINIGAMENEXTROUND_ASSISTLIST_FIELD.type = 11
MINIGAMENEXTROUND_ASSISTLIST_FIELD.cpp_type = 10
MINIGAMENEXTROUND_ENDTIME_FIELD.name = "endtime"
MINIGAMENEXTROUND_ENDTIME_FIELD.full_name = ".Cmd.MiniGameNextRound.endtime"
MINIGAMENEXTROUND_ENDTIME_FIELD.number = 5
MINIGAMENEXTROUND_ENDTIME_FIELD.index = 4
MINIGAMENEXTROUND_ENDTIME_FIELD.label = 1
MINIGAMENEXTROUND_ENDTIME_FIELD.has_default_value = true
MINIGAMENEXTROUND_ENDTIME_FIELD.default_value = 0
MINIGAMENEXTROUND_ENDTIME_FIELD.type = 13
MINIGAMENEXTROUND_ENDTIME_FIELD.cpp_type = 3
MINIGAMENEXTROUND_CARDUSEFLAG_FIELD.name = "carduseflag"
MINIGAMENEXTROUND_CARDUSEFLAG_FIELD.full_name = ".Cmd.MiniGameNextRound.carduseflag"
MINIGAMENEXTROUND_CARDUSEFLAG_FIELD.number = 6
MINIGAMENEXTROUND_CARDUSEFLAG_FIELD.index = 5
MINIGAMENEXTROUND_CARDUSEFLAG_FIELD.label = 1
MINIGAMENEXTROUND_CARDUSEFLAG_FIELD.has_default_value = true
MINIGAMENEXTROUND_CARDUSEFLAG_FIELD.default_value = false
MINIGAMENEXTROUND_CARDUSEFLAG_FIELD.type = 8
MINIGAMENEXTROUND_CARDUSEFLAG_FIELD.cpp_type = 7
MINIGAMENEXTROUND.name = "MiniGameNextRound"
MINIGAMENEXTROUND.full_name = ".Cmd.MiniGameNextRound"
MINIGAMENEXTROUND.nested_types = {}
MINIGAMENEXTROUND.enum_types = {}
MINIGAMENEXTROUND.fields = {
  MINIGAMENEXTROUND_CMD_FIELD,
  MINIGAMENEXTROUND_PARAM_FIELD,
  MINIGAMENEXTROUND_GAMETYPE_FIELD,
  MINIGAMENEXTROUND_ASSISTLIST_FIELD,
  MINIGAMENEXTROUND_ENDTIME_FIELD,
  MINIGAMENEXTROUND_CARDUSEFLAG_FIELD
}
MINIGAMENEXTROUND.is_extendable = false
MINIGAMENEXTROUND.extensions = {}
MINIGAMECHANLEGERECORD_TYPE_FIELD.name = "type"
MINIGAMECHANLEGERECORD_TYPE_FIELD.full_name = ".Cmd.MiniGameChanlegeRecord.type"
MINIGAMECHANLEGERECORD_TYPE_FIELD.number = 1
MINIGAMECHANLEGERECORD_TYPE_FIELD.index = 0
MINIGAMECHANLEGERECORD_TYPE_FIELD.label = 1
MINIGAMECHANLEGERECORD_TYPE_FIELD.has_default_value = true
MINIGAMECHANLEGERECORD_TYPE_FIELD.default_value = 0
MINIGAMECHANLEGERECORD_TYPE_FIELD.enum_type = EMINIGAMETYPE
MINIGAMECHANLEGERECORD_TYPE_FIELD.type = 14
MINIGAMECHANLEGERECORD_TYPE_FIELD.cpp_type = 8
MINIGAMECHANLEGERECORD_VALUE_FIELD.name = "value"
MINIGAMECHANLEGERECORD_VALUE_FIELD.full_name = ".Cmd.MiniGameChanlegeRecord.value"
MINIGAMECHANLEGERECORD_VALUE_FIELD.number = 2
MINIGAMECHANLEGERECORD_VALUE_FIELD.index = 1
MINIGAMECHANLEGERECORD_VALUE_FIELD.label = 1
MINIGAMECHANLEGERECORD_VALUE_FIELD.has_default_value = false
MINIGAMECHANLEGERECORD_VALUE_FIELD.default_value = 0
MINIGAMECHANLEGERECORD_VALUE_FIELD.type = 13
MINIGAMECHANLEGERECORD_VALUE_FIELD.cpp_type = 3
MINIGAMECHANLEGERECORD_TIMESTAMP_FIELD.name = "timestamp"
MINIGAMECHANLEGERECORD_TIMESTAMP_FIELD.full_name = ".Cmd.MiniGameChanlegeRecord.timestamp"
MINIGAMECHANLEGERECORD_TIMESTAMP_FIELD.number = 3
MINIGAMECHANLEGERECORD_TIMESTAMP_FIELD.index = 2
MINIGAMECHANLEGERECORD_TIMESTAMP_FIELD.label = 1
MINIGAMECHANLEGERECORD_TIMESTAMP_FIELD.has_default_value = false
MINIGAMECHANLEGERECORD_TIMESTAMP_FIELD.default_value = 0
MINIGAMECHANLEGERECORD_TIMESTAMP_FIELD.type = 13
MINIGAMECHANLEGERECORD_TIMESTAMP_FIELD.cpp_type = 3
MINIGAMECHANLEGERECORD.name = "MiniGameChanlegeRecord"
MINIGAMECHANLEGERECORD.full_name = ".Cmd.MiniGameChanlegeRecord"
MINIGAMECHANLEGERECORD.nested_types = {}
MINIGAMECHANLEGERECORD.enum_types = {}
MINIGAMECHANLEGERECORD.fields = {
  MINIGAMECHANLEGERECORD_TYPE_FIELD,
  MINIGAMECHANLEGERECORD_VALUE_FIELD,
  MINIGAMECHANLEGERECORD_TIMESTAMP_FIELD
}
MINIGAMECHANLEGERECORD.is_extendable = false
MINIGAMECHANLEGERECORD.extensions = {}
MINIGAMEUNLOCKPAIR_TYPE_FIELD.name = "type"
MINIGAMEUNLOCKPAIR_TYPE_FIELD.full_name = ".Cmd.MiniGameUnlockPair.type"
MINIGAMEUNLOCKPAIR_TYPE_FIELD.number = 1
MINIGAMEUNLOCKPAIR_TYPE_FIELD.index = 0
MINIGAMEUNLOCKPAIR_TYPE_FIELD.label = 1
MINIGAMEUNLOCKPAIR_TYPE_FIELD.has_default_value = true
MINIGAMEUNLOCKPAIR_TYPE_FIELD.default_value = 0
MINIGAMEUNLOCKPAIR_TYPE_FIELD.enum_type = EMINIGAMETYPE
MINIGAMEUNLOCKPAIR_TYPE_FIELD.type = 14
MINIGAMEUNLOCKPAIR_TYPE_FIELD.cpp_type = 8
MINIGAMEUNLOCKPAIR_DIFFICULTY_FIELD.name = "difficulty"
MINIGAMEUNLOCKPAIR_DIFFICULTY_FIELD.full_name = ".Cmd.MiniGameUnlockPair.difficulty"
MINIGAMEUNLOCKPAIR_DIFFICULTY_FIELD.number = 2
MINIGAMEUNLOCKPAIR_DIFFICULTY_FIELD.index = 1
MINIGAMEUNLOCKPAIR_DIFFICULTY_FIELD.label = 1
MINIGAMEUNLOCKPAIR_DIFFICULTY_FIELD.has_default_value = false
MINIGAMEUNLOCKPAIR_DIFFICULTY_FIELD.default_value = 0
MINIGAMEUNLOCKPAIR_DIFFICULTY_FIELD.type = 13
MINIGAMEUNLOCKPAIR_DIFFICULTY_FIELD.cpp_type = 3
MINIGAMEUNLOCKPAIR_LASTREWARD_FIELD.name = "lastreward"
MINIGAMEUNLOCKPAIR_LASTREWARD_FIELD.full_name = ".Cmd.MiniGameUnlockPair.lastreward"
MINIGAMEUNLOCKPAIR_LASTREWARD_FIELD.number = 3
MINIGAMEUNLOCKPAIR_LASTREWARD_FIELD.index = 2
MINIGAMEUNLOCKPAIR_LASTREWARD_FIELD.label = 1
MINIGAMEUNLOCKPAIR_LASTREWARD_FIELD.has_default_value = true
MINIGAMEUNLOCKPAIR_LASTREWARD_FIELD.default_value = 0
MINIGAMEUNLOCKPAIR_LASTREWARD_FIELD.type = 13
MINIGAMEUNLOCKPAIR_LASTREWARD_FIELD.cpp_type = 3
MINIGAMEUNLOCKPAIR_DAILYREST_FIELD.name = "dailyrest"
MINIGAMEUNLOCKPAIR_DAILYREST_FIELD.full_name = ".Cmd.MiniGameUnlockPair.dailyrest"
MINIGAMEUNLOCKPAIR_DAILYREST_FIELD.number = 4
MINIGAMEUNLOCKPAIR_DAILYREST_FIELD.index = 3
MINIGAMEUNLOCKPAIR_DAILYREST_FIELD.label = 1
MINIGAMEUNLOCKPAIR_DAILYREST_FIELD.has_default_value = false
MINIGAMEUNLOCKPAIR_DAILYREST_FIELD.default_value = 0
MINIGAMEUNLOCKPAIR_DAILYREST_FIELD.type = 13
MINIGAMEUNLOCKPAIR_DAILYREST_FIELD.cpp_type = 3
MINIGAMEUNLOCKPAIR_PASSALL_FIELD.name = "passall"
MINIGAMEUNLOCKPAIR_PASSALL_FIELD.full_name = ".Cmd.MiniGameUnlockPair.passall"
MINIGAMEUNLOCKPAIR_PASSALL_FIELD.number = 5
MINIGAMEUNLOCKPAIR_PASSALL_FIELD.index = 4
MINIGAMEUNLOCKPAIR_PASSALL_FIELD.label = 1
MINIGAMEUNLOCKPAIR_PASSALL_FIELD.has_default_value = false
MINIGAMEUNLOCKPAIR_PASSALL_FIELD.default_value = false
MINIGAMEUNLOCKPAIR_PASSALL_FIELD.type = 8
MINIGAMEUNLOCKPAIR_PASSALL_FIELD.cpp_type = 7
MINIGAMEUNLOCKPAIR_CHALLENGERECORD_FIELD.name = "challengerecord"
MINIGAMEUNLOCKPAIR_CHALLENGERECORD_FIELD.full_name = ".Cmd.MiniGameUnlockPair.challengerecord"
MINIGAMEUNLOCKPAIR_CHALLENGERECORD_FIELD.number = 6
MINIGAMEUNLOCKPAIR_CHALLENGERECORD_FIELD.index = 5
MINIGAMEUNLOCKPAIR_CHALLENGERECORD_FIELD.label = 1
MINIGAMEUNLOCKPAIR_CHALLENGERECORD_FIELD.has_default_value = false
MINIGAMEUNLOCKPAIR_CHALLENGERECORD_FIELD.default_value = nil
MINIGAMEUNLOCKPAIR_CHALLENGERECORD_FIELD.message_type = MINIGAMECHANLEGERECORD
MINIGAMEUNLOCKPAIR_CHALLENGERECORD_FIELD.type = 11
MINIGAMEUNLOCKPAIR_CHALLENGERECORD_FIELD.cpp_type = 10
MINIGAMEUNLOCKPAIR.name = "MiniGameUnlockPair"
MINIGAMEUNLOCKPAIR.full_name = ".Cmd.MiniGameUnlockPair"
MINIGAMEUNLOCKPAIR.nested_types = {}
MINIGAMEUNLOCKPAIR.enum_types = {}
MINIGAMEUNLOCKPAIR.fields = {
  MINIGAMEUNLOCKPAIR_TYPE_FIELD,
  MINIGAMEUNLOCKPAIR_DIFFICULTY_FIELD,
  MINIGAMEUNLOCKPAIR_LASTREWARD_FIELD,
  MINIGAMEUNLOCKPAIR_DAILYREST_FIELD,
  MINIGAMEUNLOCKPAIR_PASSALL_FIELD,
  MINIGAMEUNLOCKPAIR_CHALLENGERECORD_FIELD
}
MINIGAMEUNLOCKPAIR.is_extendable = false
MINIGAMEUNLOCKPAIR.extensions = {}
MINIGAMEWINPAIR_TYPE_FIELD.name = "type"
MINIGAMEWINPAIR_TYPE_FIELD.full_name = ".Cmd.MiniGameWinPair.type"
MINIGAMEWINPAIR_TYPE_FIELD.number = 1
MINIGAMEWINPAIR_TYPE_FIELD.index = 0
MINIGAMEWINPAIR_TYPE_FIELD.label = 1
MINIGAMEWINPAIR_TYPE_FIELD.has_default_value = true
MINIGAMEWINPAIR_TYPE_FIELD.default_value = 0
MINIGAMEWINPAIR_TYPE_FIELD.enum_type = EMINIGAMETYPE
MINIGAMEWINPAIR_TYPE_FIELD.type = 14
MINIGAMEWINPAIR_TYPE_FIELD.cpp_type = 8
MINIGAMEWINPAIR_WINTIMES_FIELD.name = "wintimes"
MINIGAMEWINPAIR_WINTIMES_FIELD.full_name = ".Cmd.MiniGameWinPair.wintimes"
MINIGAMEWINPAIR_WINTIMES_FIELD.number = 2
MINIGAMEWINPAIR_WINTIMES_FIELD.index = 1
MINIGAMEWINPAIR_WINTIMES_FIELD.label = 1
MINIGAMEWINPAIR_WINTIMES_FIELD.has_default_value = true
MINIGAMEWINPAIR_WINTIMES_FIELD.default_value = 0
MINIGAMEWINPAIR_WINTIMES_FIELD.type = 13
MINIGAMEWINPAIR_WINTIMES_FIELD.cpp_type = 3
MINIGAMEWINPAIR.name = "MiniGameWinPair"
MINIGAMEWINPAIR.full_name = ".Cmd.MiniGameWinPair"
MINIGAMEWINPAIR.nested_types = {}
MINIGAMEWINPAIR.enum_types = {}
MINIGAMEWINPAIR.fields = {
  MINIGAMEWINPAIR_TYPE_FIELD,
  MINIGAMEWINPAIR_WINTIMES_FIELD
}
MINIGAMEWINPAIR.is_extendable = false
MINIGAMEWINPAIR.extensions = {}
MINIGAMEUNLOCKLIST_CMD_FIELD.name = "cmd"
MINIGAMEUNLOCKLIST_CMD_FIELD.full_name = ".Cmd.MiniGameUnlockList.cmd"
MINIGAMEUNLOCKLIST_CMD_FIELD.number = 1
MINIGAMEUNLOCKLIST_CMD_FIELD.index = 0
MINIGAMEUNLOCKLIST_CMD_FIELD.label = 1
MINIGAMEUNLOCKLIST_CMD_FIELD.has_default_value = true
MINIGAMEUNLOCKLIST_CMD_FIELD.default_value = 223
MINIGAMEUNLOCKLIST_CMD_FIELD.enum_type = XCMD_PB_COMMAND
MINIGAMEUNLOCKLIST_CMD_FIELD.type = 14
MINIGAMEUNLOCKLIST_CMD_FIELD.cpp_type = 8
MINIGAMEUNLOCKLIST_PARAM_FIELD.name = "param"
MINIGAMEUNLOCKLIST_PARAM_FIELD.full_name = ".Cmd.MiniGameUnlockList.param"
MINIGAMEUNLOCKLIST_PARAM_FIELD.number = 2
MINIGAMEUNLOCKLIST_PARAM_FIELD.index = 1
MINIGAMEUNLOCKLIST_PARAM_FIELD.label = 1
MINIGAMEUNLOCKLIST_PARAM_FIELD.has_default_value = true
MINIGAMEUNLOCKLIST_PARAM_FIELD.default_value = 11
MINIGAMEUNLOCKLIST_PARAM_FIELD.enum_type = EMINIGAMECMDPARAM
MINIGAMEUNLOCKLIST_PARAM_FIELD.type = 14
MINIGAMEUNLOCKLIST_PARAM_FIELD.cpp_type = 8
MINIGAMEUNLOCKLIST_LIST_FIELD.name = "list"
MINIGAMEUNLOCKLIST_LIST_FIELD.full_name = ".Cmd.MiniGameUnlockList.list"
MINIGAMEUNLOCKLIST_LIST_FIELD.number = 3
MINIGAMEUNLOCKLIST_LIST_FIELD.index = 2
MINIGAMEUNLOCKLIST_LIST_FIELD.label = 3
MINIGAMEUNLOCKLIST_LIST_FIELD.has_default_value = false
MINIGAMEUNLOCKLIST_LIST_FIELD.default_value = {}
MINIGAMEUNLOCKLIST_LIST_FIELD.message_type = MINIGAMEUNLOCKPAIR
MINIGAMEUNLOCKLIST_LIST_FIELD.type = 11
MINIGAMEUNLOCKLIST_LIST_FIELD.cpp_type = 10
MINIGAMEUNLOCKLIST.name = "MiniGameUnlockList"
MINIGAMEUNLOCKLIST.full_name = ".Cmd.MiniGameUnlockList"
MINIGAMEUNLOCKLIST.nested_types = {}
MINIGAMEUNLOCKLIST.enum_types = {}
MINIGAMEUNLOCKLIST.fields = {
  MINIGAMEUNLOCKLIST_CMD_FIELD,
  MINIGAMEUNLOCKLIST_PARAM_FIELD,
  MINIGAMEUNLOCKLIST_LIST_FIELD
}
MINIGAMEUNLOCKLIST.is_extendable = false
MINIGAMEUNLOCKLIST.extensions = {}
MINIGAMENTFGAMEOVERCMD_CMD_FIELD.name = "cmd"
MINIGAMENTFGAMEOVERCMD_CMD_FIELD.full_name = ".Cmd.MiniGameNtfGameOverCmd.cmd"
MINIGAMENTFGAMEOVERCMD_CMD_FIELD.number = 1
MINIGAMENTFGAMEOVERCMD_CMD_FIELD.index = 0
MINIGAMENTFGAMEOVERCMD_CMD_FIELD.label = 1
MINIGAMENTFGAMEOVERCMD_CMD_FIELD.has_default_value = true
MINIGAMENTFGAMEOVERCMD_CMD_FIELD.default_value = 223
MINIGAMENTFGAMEOVERCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
MINIGAMENTFGAMEOVERCMD_CMD_FIELD.type = 14
MINIGAMENTFGAMEOVERCMD_CMD_FIELD.cpp_type = 8
MINIGAMENTFGAMEOVERCMD_PARAM_FIELD.name = "param"
MINIGAMENTFGAMEOVERCMD_PARAM_FIELD.full_name = ".Cmd.MiniGameNtfGameOverCmd.param"
MINIGAMENTFGAMEOVERCMD_PARAM_FIELD.number = 2
MINIGAMENTFGAMEOVERCMD_PARAM_FIELD.index = 1
MINIGAMENTFGAMEOVERCMD_PARAM_FIELD.label = 1
MINIGAMENTFGAMEOVERCMD_PARAM_FIELD.has_default_value = true
MINIGAMENTFGAMEOVERCMD_PARAM_FIELD.default_value = 15
MINIGAMENTFGAMEOVERCMD_PARAM_FIELD.enum_type = EMINIGAMECMDPARAM
MINIGAMENTFGAMEOVERCMD_PARAM_FIELD.type = 14
MINIGAMENTFGAMEOVERCMD_PARAM_FIELD.cpp_type = 8
MINIGAMENTFGAMEOVERCMD_TYPE_FIELD.name = "type"
MINIGAMENTFGAMEOVERCMD_TYPE_FIELD.full_name = ".Cmd.MiniGameNtfGameOverCmd.type"
MINIGAMENTFGAMEOVERCMD_TYPE_FIELD.number = 3
MINIGAMENTFGAMEOVERCMD_TYPE_FIELD.index = 2
MINIGAMENTFGAMEOVERCMD_TYPE_FIELD.label = 1
MINIGAMENTFGAMEOVERCMD_TYPE_FIELD.has_default_value = true
MINIGAMENTFGAMEOVERCMD_TYPE_FIELD.default_value = 0
MINIGAMENTFGAMEOVERCMD_TYPE_FIELD.enum_type = EMINIGAMETYPE
MINIGAMENTFGAMEOVERCMD_TYPE_FIELD.type = 14
MINIGAMENTFGAMEOVERCMD_TYPE_FIELD.cpp_type = 8
MINIGAMENTFGAMEOVERCMD_RESULT_FIELD.name = "result"
MINIGAMENTFGAMEOVERCMD_RESULT_FIELD.full_name = ".Cmd.MiniGameNtfGameOverCmd.result"
MINIGAMENTFGAMEOVERCMD_RESULT_FIELD.number = 4
MINIGAMENTFGAMEOVERCMD_RESULT_FIELD.index = 3
MINIGAMENTFGAMEOVERCMD_RESULT_FIELD.label = 1
MINIGAMENTFGAMEOVERCMD_RESULT_FIELD.has_default_value = true
MINIGAMENTFGAMEOVERCMD_RESULT_FIELD.default_value = 1
MINIGAMENTFGAMEOVERCMD_RESULT_FIELD.enum_type = EMINIGAMEOVERRESULT
MINIGAMENTFGAMEOVERCMD_RESULT_FIELD.type = 14
MINIGAMENTFGAMEOVERCMD_RESULT_FIELD.cpp_type = 8
MINIGAMENTFGAMEOVERCMD.name = "MiniGameNtfGameOverCmd"
MINIGAMENTFGAMEOVERCMD.full_name = ".Cmd.MiniGameNtfGameOverCmd"
MINIGAMENTFGAMEOVERCMD.nested_types = {}
MINIGAMENTFGAMEOVERCMD.enum_types = {}
MINIGAMENTFGAMEOVERCMD.fields = {
  MINIGAMENTFGAMEOVERCMD_CMD_FIELD,
  MINIGAMENTFGAMEOVERCMD_PARAM_FIELD,
  MINIGAMENTFGAMEOVERCMD_TYPE_FIELD,
  MINIGAMENTFGAMEOVERCMD_RESULT_FIELD
}
MINIGAMENTFGAMEOVERCMD.is_extendable = false
MINIGAMENTFGAMEOVERCMD.extensions = {}
MINIGAMEREQOVER_CMD_FIELD.name = "cmd"
MINIGAMEREQOVER_CMD_FIELD.full_name = ".Cmd.MiniGameReqOver.cmd"
MINIGAMEREQOVER_CMD_FIELD.number = 1
MINIGAMEREQOVER_CMD_FIELD.index = 0
MINIGAMEREQOVER_CMD_FIELD.label = 1
MINIGAMEREQOVER_CMD_FIELD.has_default_value = true
MINIGAMEREQOVER_CMD_FIELD.default_value = 223
MINIGAMEREQOVER_CMD_FIELD.enum_type = XCMD_PB_COMMAND
MINIGAMEREQOVER_CMD_FIELD.type = 14
MINIGAMEREQOVER_CMD_FIELD.cpp_type = 8
MINIGAMEREQOVER_PARAM_FIELD.name = "param"
MINIGAMEREQOVER_PARAM_FIELD.full_name = ".Cmd.MiniGameReqOver.param"
MINIGAMEREQOVER_PARAM_FIELD.number = 2
MINIGAMEREQOVER_PARAM_FIELD.index = 1
MINIGAMEREQOVER_PARAM_FIELD.label = 1
MINIGAMEREQOVER_PARAM_FIELD.has_default_value = true
MINIGAMEREQOVER_PARAM_FIELD.default_value = 16
MINIGAMEREQOVER_PARAM_FIELD.enum_type = EMINIGAMECMDPARAM
MINIGAMEREQOVER_PARAM_FIELD.type = 14
MINIGAMEREQOVER_PARAM_FIELD.cpp_type = 8
MINIGAMEREQOVER_TYPE_FIELD.name = "type"
MINIGAMEREQOVER_TYPE_FIELD.full_name = ".Cmd.MiniGameReqOver.type"
MINIGAMEREQOVER_TYPE_FIELD.number = 3
MINIGAMEREQOVER_TYPE_FIELD.index = 2
MINIGAMEREQOVER_TYPE_FIELD.label = 1
MINIGAMEREQOVER_TYPE_FIELD.has_default_value = true
MINIGAMEREQOVER_TYPE_FIELD.default_value = 0
MINIGAMEREQOVER_TYPE_FIELD.enum_type = EMINIGAMETYPE
MINIGAMEREQOVER_TYPE_FIELD.type = 14
MINIGAMEREQOVER_TYPE_FIELD.cpp_type = 8
MINIGAMEREQOVER.name = "MiniGameReqOver"
MINIGAMEREQOVER.full_name = ".Cmd.MiniGameReqOver"
MINIGAMEREQOVER.nested_types = {}
MINIGAMEREQOVER.enum_types = {}
MINIGAMEREQOVER.fields = {
  MINIGAMEREQOVER_CMD_FIELD,
  MINIGAMEREQOVER_PARAM_FIELD,
  MINIGAMEREQOVER_TYPE_FIELD
}
MINIGAMEREQOVER.is_extendable = false
MINIGAMEREQOVER.extensions = {}
MINIGAMEUSEASSIST_CMD_FIELD.name = "cmd"
MINIGAMEUSEASSIST_CMD_FIELD.full_name = ".Cmd.MiniGameUseAssist.cmd"
MINIGAMEUSEASSIST_CMD_FIELD.number = 1
MINIGAMEUSEASSIST_CMD_FIELD.index = 0
MINIGAMEUSEASSIST_CMD_FIELD.label = 1
MINIGAMEUSEASSIST_CMD_FIELD.has_default_value = true
MINIGAMEUSEASSIST_CMD_FIELD.default_value = 223
MINIGAMEUSEASSIST_CMD_FIELD.enum_type = XCMD_PB_COMMAND
MINIGAMEUSEASSIST_CMD_FIELD.type = 14
MINIGAMEUSEASSIST_CMD_FIELD.cpp_type = 8
MINIGAMEUSEASSIST_PARAM_FIELD.name = "param"
MINIGAMEUSEASSIST_PARAM_FIELD.full_name = ".Cmd.MiniGameUseAssist.param"
MINIGAMEUSEASSIST_PARAM_FIELD.number = 2
MINIGAMEUSEASSIST_PARAM_FIELD.index = 1
MINIGAMEUSEASSIST_PARAM_FIELD.label = 1
MINIGAMEUSEASSIST_PARAM_FIELD.has_default_value = true
MINIGAMEUSEASSIST_PARAM_FIELD.default_value = 17
MINIGAMEUSEASSIST_PARAM_FIELD.enum_type = EMINIGAMECMDPARAM
MINIGAMEUSEASSIST_PARAM_FIELD.type = 14
MINIGAMEUSEASSIST_PARAM_FIELD.cpp_type = 8
MINIGAMEUSEASSIST_TYPE_FIELD.name = "type"
MINIGAMEUSEASSIST_TYPE_FIELD.full_name = ".Cmd.MiniGameUseAssist.type"
MINIGAMEUSEASSIST_TYPE_FIELD.number = 3
MINIGAMEUSEASSIST_TYPE_FIELD.index = 2
MINIGAMEUSEASSIST_TYPE_FIELD.label = 1
MINIGAMEUSEASSIST_TYPE_FIELD.has_default_value = true
MINIGAMEUSEASSIST_TYPE_FIELD.default_value = 0
MINIGAMEUSEASSIST_TYPE_FIELD.enum_type = EMINIGAMETYPE
MINIGAMEUSEASSIST_TYPE_FIELD.type = 14
MINIGAMEUSEASSIST_TYPE_FIELD.cpp_type = 8
MINIGAMEUSEASSIST_ASSISTTYPE_FIELD.name = "assisttype"
MINIGAMEUSEASSIST_ASSISTTYPE_FIELD.full_name = ".Cmd.MiniGameUseAssist.assisttype"
MINIGAMEUSEASSIST_ASSISTTYPE_FIELD.number = 4
MINIGAMEUSEASSIST_ASSISTTYPE_FIELD.index = 3
MINIGAMEUSEASSIST_ASSISTTYPE_FIELD.label = 1
MINIGAMEUSEASSIST_ASSISTTYPE_FIELD.has_default_value = false
MINIGAMEUSEASSIST_ASSISTTYPE_FIELD.default_value = nil
MINIGAMEUSEASSIST_ASSISTTYPE_FIELD.enum_type = EASSISTTYPE
MINIGAMEUSEASSIST_ASSISTTYPE_FIELD.type = 14
MINIGAMEUSEASSIST_ASSISTTYPE_FIELD.cpp_type = 8
MINIGAMEUSEASSIST.name = "MiniGameUseAssist"
MINIGAMEUSEASSIST.full_name = ".Cmd.MiniGameUseAssist"
MINIGAMEUSEASSIST.nested_types = {}
MINIGAMEUSEASSIST.enum_types = {}
MINIGAMEUSEASSIST.fields = {
  MINIGAMEUSEASSIST_CMD_FIELD,
  MINIGAMEUSEASSIST_PARAM_FIELD,
  MINIGAMEUSEASSIST_TYPE_FIELD,
  MINIGAMEUSEASSIST_ASSISTTYPE_FIELD
}
MINIGAMEUSEASSIST.is_extendable = false
MINIGAMEUSEASSIST.extensions = {}
MINIGAMENTFROUNDOVER_CMD_FIELD.name = "cmd"
MINIGAMENTFROUNDOVER_CMD_FIELD.full_name = ".Cmd.MiniGameNtfRoundOver.cmd"
MINIGAMENTFROUNDOVER_CMD_FIELD.number = 1
MINIGAMENTFROUNDOVER_CMD_FIELD.index = 0
MINIGAMENTFROUNDOVER_CMD_FIELD.label = 1
MINIGAMENTFROUNDOVER_CMD_FIELD.has_default_value = true
MINIGAMENTFROUNDOVER_CMD_FIELD.default_value = 223
MINIGAMENTFROUNDOVER_CMD_FIELD.enum_type = XCMD_PB_COMMAND
MINIGAMENTFROUNDOVER_CMD_FIELD.type = 14
MINIGAMENTFROUNDOVER_CMD_FIELD.cpp_type = 8
MINIGAMENTFROUNDOVER_PARAM_FIELD.name = "param"
MINIGAMENTFROUNDOVER_PARAM_FIELD.full_name = ".Cmd.MiniGameNtfRoundOver.param"
MINIGAMENTFROUNDOVER_PARAM_FIELD.number = 2
MINIGAMENTFROUNDOVER_PARAM_FIELD.index = 1
MINIGAMENTFROUNDOVER_PARAM_FIELD.label = 1
MINIGAMENTFROUNDOVER_PARAM_FIELD.has_default_value = true
MINIGAMENTFROUNDOVER_PARAM_FIELD.default_value = 18
MINIGAMENTFROUNDOVER_PARAM_FIELD.enum_type = EMINIGAMECMDPARAM
MINIGAMENTFROUNDOVER_PARAM_FIELD.type = 14
MINIGAMENTFROUNDOVER_PARAM_FIELD.cpp_type = 8
MINIGAMENTFROUNDOVER_TYPE_FIELD.name = "type"
MINIGAMENTFROUNDOVER_TYPE_FIELD.full_name = ".Cmd.MiniGameNtfRoundOver.type"
MINIGAMENTFROUNDOVER_TYPE_FIELD.number = 3
MINIGAMENTFROUNDOVER_TYPE_FIELD.index = 2
MINIGAMENTFROUNDOVER_TYPE_FIELD.label = 1
MINIGAMENTFROUNDOVER_TYPE_FIELD.has_default_value = true
MINIGAMENTFROUNDOVER_TYPE_FIELD.default_value = 0
MINIGAMENTFROUNDOVER_TYPE_FIELD.enum_type = EMINIGAMETYPE
MINIGAMENTFROUNDOVER_TYPE_FIELD.type = 14
MINIGAMENTFROUNDOVER_TYPE_FIELD.cpp_type = 8
MINIGAMENTFROUNDOVER_ANSWER_FIELD.name = "answer"
MINIGAMENTFROUNDOVER_ANSWER_FIELD.full_name = ".Cmd.MiniGameNtfRoundOver.answer"
MINIGAMENTFROUNDOVER_ANSWER_FIELD.number = 4
MINIGAMENTFROUNDOVER_ANSWER_FIELD.index = 3
MINIGAMENTFROUNDOVER_ANSWER_FIELD.label = 1
MINIGAMENTFROUNDOVER_ANSWER_FIELD.has_default_value = false
MINIGAMENTFROUNDOVER_ANSWER_FIELD.default_value = 0
MINIGAMENTFROUNDOVER_ANSWER_FIELD.type = 13
MINIGAMENTFROUNDOVER_ANSWER_FIELD.cpp_type = 3
MINIGAMENTFROUNDOVER_LASTREPLYSTATUS_FIELD.name = "lastreplystatus"
MINIGAMENTFROUNDOVER_LASTREPLYSTATUS_FIELD.full_name = ".Cmd.MiniGameNtfRoundOver.lastreplystatus"
MINIGAMENTFROUNDOVER_LASTREPLYSTATUS_FIELD.number = 5
MINIGAMENTFROUNDOVER_LASTREPLYSTATUS_FIELD.index = 4
MINIGAMENTFROUNDOVER_LASTREPLYSTATUS_FIELD.label = 1
MINIGAMENTFROUNDOVER_LASTREPLYSTATUS_FIELD.has_default_value = true
MINIGAMENTFROUNDOVER_LASTREPLYSTATUS_FIELD.default_value = 0
MINIGAMENTFROUNDOVER_LASTREPLYSTATUS_FIELD.enum_type = ELASTREPLYSTATUS
MINIGAMENTFROUNDOVER_LASTREPLYSTATUS_FIELD.type = 14
MINIGAMENTFROUNDOVER_LASTREPLYSTATUS_FIELD.cpp_type = 8
MINIGAMENTFROUNDOVER.name = "MiniGameNtfRoundOver"
MINIGAMENTFROUNDOVER.full_name = ".Cmd.MiniGameNtfRoundOver"
MINIGAMENTFROUNDOVER.nested_types = {}
MINIGAMENTFROUNDOVER.enum_types = {}
MINIGAMENTFROUNDOVER.fields = {
  MINIGAMENTFROUNDOVER_CMD_FIELD,
  MINIGAMENTFROUNDOVER_PARAM_FIELD,
  MINIGAMENTFROUNDOVER_TYPE_FIELD,
  MINIGAMENTFROUNDOVER_ANSWER_FIELD,
  MINIGAMENTFROUNDOVER_LASTREPLYSTATUS_FIELD
}
MINIGAMENTFROUNDOVER.is_extendable = false
MINIGAMENTFROUNDOVER.extensions = {}
MINIGAMERANKUSER_CHARID_FIELD.name = "charid"
MINIGAMERANKUSER_CHARID_FIELD.full_name = ".Cmd.MiniGameRankUser.charid"
MINIGAMERANKUSER_CHARID_FIELD.number = 1
MINIGAMERANKUSER_CHARID_FIELD.index = 0
MINIGAMERANKUSER_CHARID_FIELD.label = 1
MINIGAMERANKUSER_CHARID_FIELD.has_default_value = true
MINIGAMERANKUSER_CHARID_FIELD.default_value = 0
MINIGAMERANKUSER_CHARID_FIELD.type = 4
MINIGAMERANKUSER_CHARID_FIELD.cpp_type = 4
MINIGAMERANKUSER_NAME_FIELD.name = "name"
MINIGAMERANKUSER_NAME_FIELD.full_name = ".Cmd.MiniGameRankUser.name"
MINIGAMERANKUSER_NAME_FIELD.number = 2
MINIGAMERANKUSER_NAME_FIELD.index = 1
MINIGAMERANKUSER_NAME_FIELD.label = 1
MINIGAMERANKUSER_NAME_FIELD.has_default_value = false
MINIGAMERANKUSER_NAME_FIELD.default_value = ""
MINIGAMERANKUSER_NAME_FIELD.type = 9
MINIGAMERANKUSER_NAME_FIELD.cpp_type = 9
MINIGAMERANKUSER_PROFESSION_FIELD.name = "profession"
MINIGAMERANKUSER_PROFESSION_FIELD.full_name = ".Cmd.MiniGameRankUser.profession"
MINIGAMERANKUSER_PROFESSION_FIELD.number = 3
MINIGAMERANKUSER_PROFESSION_FIELD.index = 2
MINIGAMERANKUSER_PROFESSION_FIELD.label = 1
MINIGAMERANKUSER_PROFESSION_FIELD.has_default_value = false
MINIGAMERANKUSER_PROFESSION_FIELD.default_value = nil
MINIGAMERANKUSER_PROFESSION_FIELD.enum_type = PROTOCOMMON_PB_EPROFESSION
MINIGAMERANKUSER_PROFESSION_FIELD.type = 14
MINIGAMERANKUSER_PROFESSION_FIELD.cpp_type = 8
MINIGAMERANKUSER_PORTRAIT_FIELD.name = "portrait"
MINIGAMERANKUSER_PORTRAIT_FIELD.full_name = ".Cmd.MiniGameRankUser.portrait"
MINIGAMERANKUSER_PORTRAIT_FIELD.number = 4
MINIGAMERANKUSER_PORTRAIT_FIELD.index = 3
MINIGAMERANKUSER_PORTRAIT_FIELD.label = 1
MINIGAMERANKUSER_PORTRAIT_FIELD.has_default_value = false
MINIGAMERANKUSER_PORTRAIT_FIELD.default_value = nil
MINIGAMERANKUSER_PORTRAIT_FIELD.message_type = ProtoCommon_pb.USERPORTRAITDATA
MINIGAMERANKUSER_PORTRAIT_FIELD.type = 11
MINIGAMERANKUSER_PORTRAIT_FIELD.cpp_type = 10
MINIGAMERANKUSER.name = "MiniGameRankUser"
MINIGAMERANKUSER.full_name = ".Cmd.MiniGameRankUser"
MINIGAMERANKUSER.nested_types = {}
MINIGAMERANKUSER.enum_types = {}
MINIGAMERANKUSER.fields = {
  MINIGAMERANKUSER_CHARID_FIELD,
  MINIGAMERANKUSER_NAME_FIELD,
  MINIGAMERANKUSER_PROFESSION_FIELD,
  MINIGAMERANKUSER_PORTRAIT_FIELD
}
MINIGAMERANKUSER.is_extendable = false
MINIGAMERANKUSER.extensions = {}
MINIGAMERANKBASE_RECORD_FIELD.name = "record"
MINIGAMERANKBASE_RECORD_FIELD.full_name = ".Cmd.MiniGameRankBase.record"
MINIGAMERANKBASE_RECORD_FIELD.number = 1
MINIGAMERANKBASE_RECORD_FIELD.index = 0
MINIGAMERANKBASE_RECORD_FIELD.label = 1
MINIGAMERANKBASE_RECORD_FIELD.has_default_value = false
MINIGAMERANKBASE_RECORD_FIELD.default_value = nil
MINIGAMERANKBASE_RECORD_FIELD.message_type = MINIGAMECHANLEGERECORD
MINIGAMERANKBASE_RECORD_FIELD.type = 11
MINIGAMERANKBASE_RECORD_FIELD.cpp_type = 10
MINIGAMERANKBASE_USER_FIELD.name = "user"
MINIGAMERANKBASE_USER_FIELD.full_name = ".Cmd.MiniGameRankBase.user"
MINIGAMERANKBASE_USER_FIELD.number = 2
MINIGAMERANKBASE_USER_FIELD.index = 1
MINIGAMERANKBASE_USER_FIELD.label = 1
MINIGAMERANKBASE_USER_FIELD.has_default_value = false
MINIGAMERANKBASE_USER_FIELD.default_value = nil
MINIGAMERANKBASE_USER_FIELD.message_type = MINIGAMERANKUSER
MINIGAMERANKBASE_USER_FIELD.type = 11
MINIGAMERANKBASE_USER_FIELD.cpp_type = 10
MINIGAMERANKBASE_MYSELF_FIELD.name = "myself"
MINIGAMERANKBASE_MYSELF_FIELD.full_name = ".Cmd.MiniGameRankBase.myself"
MINIGAMERANKBASE_MYSELF_FIELD.number = 3
MINIGAMERANKBASE_MYSELF_FIELD.index = 2
MINIGAMERANKBASE_MYSELF_FIELD.label = 1
MINIGAMERANKBASE_MYSELF_FIELD.has_default_value = true
MINIGAMERANKBASE_MYSELF_FIELD.default_value = false
MINIGAMERANKBASE_MYSELF_FIELD.type = 8
MINIGAMERANKBASE_MYSELF_FIELD.cpp_type = 7
MINIGAMERANKBASE.name = "MiniGameRankBase"
MINIGAMERANKBASE.full_name = ".Cmd.MiniGameRankBase"
MINIGAMERANKBASE.nested_types = {}
MINIGAMERANKBASE.enum_types = {}
MINIGAMERANKBASE.fields = {
  MINIGAMERANKBASE_RECORD_FIELD,
  MINIGAMERANKBASE_USER_FIELD,
  MINIGAMERANKBASE_MYSELF_FIELD
}
MINIGAMERANKBASE.is_extendable = false
MINIGAMERANKBASE.extensions = {}
MINIGAMEQUERYRANK_CMD_FIELD.name = "cmd"
MINIGAMEQUERYRANK_CMD_FIELD.full_name = ".Cmd.MiniGameQueryRank.cmd"
MINIGAMEQUERYRANK_CMD_FIELD.number = 1
MINIGAMEQUERYRANK_CMD_FIELD.index = 0
MINIGAMEQUERYRANK_CMD_FIELD.label = 1
MINIGAMEQUERYRANK_CMD_FIELD.has_default_value = true
MINIGAMEQUERYRANK_CMD_FIELD.default_value = 223
MINIGAMEQUERYRANK_CMD_FIELD.enum_type = XCMD_PB_COMMAND
MINIGAMEQUERYRANK_CMD_FIELD.type = 14
MINIGAMEQUERYRANK_CMD_FIELD.cpp_type = 8
MINIGAMEQUERYRANK_PARAM_FIELD.name = "param"
MINIGAMEQUERYRANK_PARAM_FIELD.full_name = ".Cmd.MiniGameQueryRank.param"
MINIGAMEQUERYRANK_PARAM_FIELD.number = 2
MINIGAMEQUERYRANK_PARAM_FIELD.index = 1
MINIGAMEQUERYRANK_PARAM_FIELD.label = 1
MINIGAMEQUERYRANK_PARAM_FIELD.has_default_value = true
MINIGAMEQUERYRANK_PARAM_FIELD.default_value = 19
MINIGAMEQUERYRANK_PARAM_FIELD.enum_type = EMINIGAMECMDPARAM
MINIGAMEQUERYRANK_PARAM_FIELD.type = 14
MINIGAMEQUERYRANK_PARAM_FIELD.cpp_type = 8
MINIGAMEQUERYRANK_TYPE_FIELD.name = "type"
MINIGAMEQUERYRANK_TYPE_FIELD.full_name = ".Cmd.MiniGameQueryRank.type"
MINIGAMEQUERYRANK_TYPE_FIELD.number = 3
MINIGAMEQUERYRANK_TYPE_FIELD.index = 2
MINIGAMEQUERYRANK_TYPE_FIELD.label = 1
MINIGAMEQUERYRANK_TYPE_FIELD.has_default_value = true
MINIGAMEQUERYRANK_TYPE_FIELD.default_value = 0
MINIGAMEQUERYRANK_TYPE_FIELD.enum_type = EMINIGAMETYPE
MINIGAMEQUERYRANK_TYPE_FIELD.type = 14
MINIGAMEQUERYRANK_TYPE_FIELD.cpp_type = 8
MINIGAMEQUERYRANK_RANKS_FIELD.name = "ranks"
MINIGAMEQUERYRANK_RANKS_FIELD.full_name = ".Cmd.MiniGameQueryRank.ranks"
MINIGAMEQUERYRANK_RANKS_FIELD.number = 4
MINIGAMEQUERYRANK_RANKS_FIELD.index = 3
MINIGAMEQUERYRANK_RANKS_FIELD.label = 3
MINIGAMEQUERYRANK_RANKS_FIELD.has_default_value = false
MINIGAMEQUERYRANK_RANKS_FIELD.default_value = {}
MINIGAMEQUERYRANK_RANKS_FIELD.message_type = MINIGAMERANKBASE
MINIGAMEQUERYRANK_RANKS_FIELD.type = 11
MINIGAMEQUERYRANK_RANKS_FIELD.cpp_type = 10
MINIGAMEQUERYRANK.name = "MiniGameQueryRank"
MINIGAMEQUERYRANK.full_name = ".Cmd.MiniGameQueryRank"
MINIGAMEQUERYRANK.nested_types = {}
MINIGAMEQUERYRANK.enum_types = {}
MINIGAMEQUERYRANK.fields = {
  MINIGAMEQUERYRANK_CMD_FIELD,
  MINIGAMEQUERYRANK_PARAM_FIELD,
  MINIGAMEQUERYRANK_TYPE_FIELD,
  MINIGAMEQUERYRANK_RANKS_FIELD
}
MINIGAMEQUERYRANK.is_extendable = false
MINIGAMEQUERYRANK.extensions = {}
EASSISTTYPE_ADDTIME = 1
EASSISTTYPE_QUICK_FINISH = 2
EASSISTTYPE_TIPS = 3
ELASTREPLYSTATUS_ERROR = 1
ELASTREPLYSTATUS_NONE = 0
ELASTREPLYSTATUS_RIGHT = 2
EMINIGAMEMODE_CHALLENGE = 2
EMINIGAMEMODE_NORMAL = 1
EMINIGAMETYPE_CARD_PAIR = 3
EMINIGAMETYPE_MAX = 4
EMINIGAMETYPE_MONSTER_ANSWER = 1
EMINIGAMETYPE_MONSTER_PHOTO = 2
EMINIGAMETYPE_NONE = 0
EMINIGAME_ERROR_DIFFICULTY_NOT_UNLOCK = 1
EMINIGAME_ERROR_MONSTER_ANSWER_ERROR = 2
EMINIGAME_ERROR_NONE = 0
EMINIGAME_OVER_LOSE = 1
EMINIGAME_OVER_WIN = 0
EMONSTERANSWER_LINKSYMBOL_AND = 1
EMONSTERANSWER_LINKSYMBOL_NONE = 0
EMONSTERANSWER_LINKSYMBOL_OR = 2
EMONSTERANWSER_QUESTTYPE_COLOR = 2
EMONSTERANWSER_QUESTTYPE_ELEMENT = 1
EMONSTERANWSER_QUESTTYPE_FEET = 0
EMONSTERANWSER_QUESTTYPE_MAX = 4
EMONSTERAdifficultyNWSER_QUESTTYPE_RACE = 3
EMONSTERSHOT_COMPARE_EQ = 2
EMONSTERSHOT_COMPARE_GT = 3
EMONSTERSHOT_COMPARE_LT = 1
EMONSTERSHOT_COMPARE_NONE = 0
ENIMIGAME_ERROR_DIFFICULTY_ILLEGAL = 5
ENIMIGAME_ERROR_INGAME_ALREADY = 9
ENIMIGAME_ERROR_MAP_NOMATCH = 7
ENIMIGAME_ERROR_NOT_INGAME = 10
ENIMIGAME_ERROR_NO_MAPRAID = 4
ENIMIGAME_ERROR_OVER_ALREADY = 3
ENIMIGAME_ERROR_REACH_LIMIT = 8
ENIMIGAME_ERROR_TYPE_ILLEGAL = 6
MINIGAMEPARAM_ACTION_NEXTROUND = 14
MINIGAMEPARAM_ACTION_START = 13
MINIGAMEPARAM_GET_UNLOCKLIST = 11
MINIGAMEPARAM_NTF_GAME_OVER = 15
MINIGAMEPARAM_NTF_MONSTER_ANSWER = 9
MINIGAMEPARAM_NTF_MONSTER_SHOT = 1
MINIGAMEPARAM_OVERGAME = 16
MINIGAMEPARAM_QUERYRANK = 19
MINIGAMEPARAM_RES_GET_UNLOCKLIST = 12
MINIGAMEPARAM_RES_SUBMIT_MONSTER_SHOT = 3
MINIGAMEPARAM_ROUNDEND_NTF = 18
MINIGAMEPARAM_SUBMIT_MONSTER_ANSWER = 10
MINIGAMEPARAM_SUBMIT_MONSTER_SHOT = 2
MINIGAMEPARAM_USE_ASSIST = 17
MiniGameAction = protobuf.Message(MINIGAMEACTION)
MiniGameAssist = protobuf.Message(MINIGAMEASSIST)
MiniGameChanlegeRecord = protobuf.Message(MINIGAMECHANLEGERECORD)
MiniGameMonsterShotAction = protobuf.Message(MINIGAMEMONSTERSHOTACTION)
MiniGameNextRound = protobuf.Message(MINIGAMENEXTROUND)
MiniGameNtfGameOverCmd = protobuf.Message(MINIGAMENTFGAMEOVERCMD)
MiniGameNtfMonsterAnswer = protobuf.Message(MINIGAMENTFMONSTERANSWER)
MiniGameNtfMonsterShot = protobuf.Message(MINIGAMENTFMONSTERSHOT)
MiniGameNtfRoundOver = protobuf.Message(MINIGAMENTFROUNDOVER)
MiniGameQueryRank = protobuf.Message(MINIGAMEQUERYRANK)
MiniGameRankBase = protobuf.Message(MINIGAMERANKBASE)
MiniGameRankUser = protobuf.Message(MINIGAMERANKUSER)
MiniGameReqOver = protobuf.Message(MINIGAMEREQOVER)
MiniGameSubmitMonsterAnswer = protobuf.Message(MINIGAMESUBMITMONSTERANSWER)
MiniGameUnlockList = protobuf.Message(MINIGAMEUNLOCKLIST)
MiniGameUnlockPair = protobuf.Message(MINIGAMEUNLOCKPAIR)
MiniGameUseAssist = protobuf.Message(MINIGAMEUSEASSIST)
MiniGameWinPair = protobuf.Message(MINIGAMEWINPAIR)
MonsterAnswerQuestPart = protobuf.Message(MONSTERANSWERQUESTPART)
MonsterShotRequirePair = protobuf.Message(MONSTERSHOTREQUIREPAIR)
