local protobuf = protobuf
autoImport("xCmd_pb")
local xCmd_pb = xCmd_pb
autoImport("SceneUser2_pb")
local SceneUser2_pb = SceneUser2_pb
module("NoviceBattlePass_pb")
NOVICEBPPARAM = protobuf.EnumDescriptor()
NOVICEBPPARAM_NOVICEBPPARAM_TARGET_UPDATE_ENUM = protobuf.EnumValueDescriptor()
NOVICEBPPARAM_NOVICEBPPARAM_REWARD_UPDATE_ENUM = protobuf.EnumValueDescriptor()
NOVICEBPPARAM_NOVICEBPPARAM_TARGET_GET_ENUM = protobuf.EnumValueDescriptor()
NOVICEBPPARAM_NOVICEBPPARAM_BUY_LEVEL_ENUM = protobuf.EnumValueDescriptor()
NOVICEBPPARAM_NOVICEBPPARAM_CHALLENGE_UPDATE_ENUM = protobuf.EnumValueDescriptor()
NOVICEBPPARAM_NOVICEBPPARAM_RETURN_TARGET_UPDATE_ENUM = protobuf.EnumValueDescriptor()
NOVICEBPPARAM_NOVICEBPPARAM_RETURN_REWARD_UPDATE_ENUM = protobuf.EnumValueDescriptor()
NOVICEBPPARAM_NOVICEBPPARAM_RETURN_TARGET_REWARD_GET_ENUM = protobuf.EnumValueDescriptor()
NOVICEBPPARAM_NOVICEBPPARAM_RETURN_REWARD_GET_ENUM = protobuf.EnumValueDescriptor()
NOVICEBPPARAM_NOVICEBPPARAM_RETURN_BP_BUY_LEVEL_ENUM = protobuf.EnumValueDescriptor()
NOVICEBPTARGETUPDATECMD = protobuf.Descriptor()
NOVICEBPTARGETUPDATECMD_CMD_FIELD = protobuf.FieldDescriptor()
NOVICEBPTARGETUPDATECMD_PARAM_FIELD = protobuf.FieldDescriptor()
NOVICEBPTARGETUPDATECMD_DATAS_FIELD = protobuf.FieldDescriptor()
NOVICEBPTARGETUPDATECMD_END_TIME_FIELD = protobuf.FieldDescriptor()
NOVICEBPTARGETUPDATECMD_IS_PRO_FIELD = protobuf.FieldDescriptor()
NOVICEBPREWARDUPDATECMD = protobuf.Descriptor()
NOVICEBPREWARDUPDATECMD_CMD_FIELD = protobuf.FieldDescriptor()
NOVICEBPREWARDUPDATECMD_PARAM_FIELD = protobuf.FieldDescriptor()
NOVICEBPREWARDUPDATECMD_REWARDED_NORMAL_LVS_FIELD = protobuf.FieldDescriptor()
NOVICEBPREWARDUPDATECMD_REWARDED_PRO_LVS_FIELD = protobuf.FieldDescriptor()
NOVICEBPTARGETREWARDCMD = protobuf.Descriptor()
NOVICEBPTARGETREWARDCMD_CMD_FIELD = protobuf.FieldDescriptor()
NOVICEBPTARGETREWARDCMD_PARAM_FIELD = protobuf.FieldDescriptor()
NOVICEBPTARGETREWARDCMD_IS_ALL_FIELD = protobuf.FieldDescriptor()
NOVICEBPTARGETREWARDCMD_LV_FIELD = protobuf.FieldDescriptor()
NOVICEBPBUYLEVELCMD = protobuf.Descriptor()
NOVICEBPBUYLEVELCMD_CMD_FIELD = protobuf.FieldDescriptor()
NOVICEBPBUYLEVELCMD_PARAM_FIELD = protobuf.FieldDescriptor()
NOVICEBPBUYLEVELCMD_LEVEL_FIELD = protobuf.FieldDescriptor()
CHALLENGETARGETUPDATECMD = protobuf.Descriptor()
CHALLENGETARGETUPDATECMD_CMD_FIELD = protobuf.FieldDescriptor()
CHALLENGETARGETUPDATECMD_PARAM_FIELD = protobuf.FieldDescriptor()
CHALLENGETARGETUPDATECMD_DATAS_FIELD = protobuf.FieldDescriptor()
RETURNBPTARGETUPDATECMD = protobuf.Descriptor()
RETURNBPTARGETUPDATECMD_CMD_FIELD = protobuf.FieldDescriptor()
RETURNBPTARGETUPDATECMD_PARAM_FIELD = protobuf.FieldDescriptor()
RETURNBPTARGETUPDATECMD_DATAS_FIELD = protobuf.FieldDescriptor()
RETURNBPTARGETUPDATECMD_END_TIME_FIELD = protobuf.FieldDescriptor()
RETURNBPTARGETUPDATECMD_IS_PRO_FIELD = protobuf.FieldDescriptor()
RETURNBPTARGETUPDATECMD_VERSION_FIELD = protobuf.FieldDescriptor()
RETURNBPTARGETUPDATECMD_BP_CLASS_FIELD = protobuf.FieldDescriptor()
RETURNBPTARGETUPDATECMD_RETURN_REWARD_GOT_FIELD = protobuf.FieldDescriptor()
RETURNBPREWARDUPDATECMD = protobuf.Descriptor()
RETURNBPREWARDUPDATECMD_CMD_FIELD = protobuf.FieldDescriptor()
RETURNBPREWARDUPDATECMD_PARAM_FIELD = protobuf.FieldDescriptor()
RETURNBPREWARDUPDATECMD_REWARDED_NORMAL_LVS_FIELD = protobuf.FieldDescriptor()
RETURNBPREWARDUPDATECMD_REWARDED_PRO_LVS_FIELD = protobuf.FieldDescriptor()
RETURNBPTARGETREWARDCMD = protobuf.Descriptor()
RETURNBPTARGETREWARDCMD_CMD_FIELD = protobuf.FieldDescriptor()
RETURNBPTARGETREWARDCMD_PARAM_FIELD = protobuf.FieldDescriptor()
RETURNBPTARGETREWARDCMD_IS_ALL_FIELD = protobuf.FieldDescriptor()
RETURNBPTARGETREWARDCMD_LV_FIELD = protobuf.FieldDescriptor()
RETURNBPRETURNREWARDCMD = protobuf.Descriptor()
RETURNBPRETURNREWARDCMD_CMD_FIELD = protobuf.FieldDescriptor()
RETURNBPRETURNREWARDCMD_PARAM_FIELD = protobuf.FieldDescriptor()
RETURNBPBUYLEVELCMD = protobuf.Descriptor()
RETURNBPBUYLEVELCMD_CMD_FIELD = protobuf.FieldDescriptor()
RETURNBPBUYLEVELCMD_PARAM_FIELD = protobuf.FieldDescriptor()
RETURNBPBUYLEVELCMD_LEVEL_FIELD = protobuf.FieldDescriptor()
NOVICEBPPARAM_NOVICEBPPARAM_TARGET_UPDATE_ENUM.name = "NOVICEBPPARAM_TARGET_UPDATE"
NOVICEBPPARAM_NOVICEBPPARAM_TARGET_UPDATE_ENUM.index = 0
NOVICEBPPARAM_NOVICEBPPARAM_TARGET_UPDATE_ENUM.number = 1
NOVICEBPPARAM_NOVICEBPPARAM_REWARD_UPDATE_ENUM.name = "NOVICEBPPARAM_REWARD_UPDATE"
NOVICEBPPARAM_NOVICEBPPARAM_REWARD_UPDATE_ENUM.index = 1
NOVICEBPPARAM_NOVICEBPPARAM_REWARD_UPDATE_ENUM.number = 2
NOVICEBPPARAM_NOVICEBPPARAM_TARGET_GET_ENUM.name = "NOVICEBPPARAM_TARGET_GET"
NOVICEBPPARAM_NOVICEBPPARAM_TARGET_GET_ENUM.index = 2
NOVICEBPPARAM_NOVICEBPPARAM_TARGET_GET_ENUM.number = 3
NOVICEBPPARAM_NOVICEBPPARAM_BUY_LEVEL_ENUM.name = "NOVICEBPPARAM_BUY_LEVEL"
NOVICEBPPARAM_NOVICEBPPARAM_BUY_LEVEL_ENUM.index = 3
NOVICEBPPARAM_NOVICEBPPARAM_BUY_LEVEL_ENUM.number = 4
NOVICEBPPARAM_NOVICEBPPARAM_CHALLENGE_UPDATE_ENUM.name = "NOVICEBPPARAM_CHALLENGE_UPDATE"
NOVICEBPPARAM_NOVICEBPPARAM_CHALLENGE_UPDATE_ENUM.index = 4
NOVICEBPPARAM_NOVICEBPPARAM_CHALLENGE_UPDATE_ENUM.number = 5
NOVICEBPPARAM_NOVICEBPPARAM_RETURN_TARGET_UPDATE_ENUM.name = "NOVICEBPPARAM_RETURN_TARGET_UPDATE"
NOVICEBPPARAM_NOVICEBPPARAM_RETURN_TARGET_UPDATE_ENUM.index = 5
NOVICEBPPARAM_NOVICEBPPARAM_RETURN_TARGET_UPDATE_ENUM.number = 6
NOVICEBPPARAM_NOVICEBPPARAM_RETURN_REWARD_UPDATE_ENUM.name = "NOVICEBPPARAM_RETURN_REWARD_UPDATE"
NOVICEBPPARAM_NOVICEBPPARAM_RETURN_REWARD_UPDATE_ENUM.index = 6
NOVICEBPPARAM_NOVICEBPPARAM_RETURN_REWARD_UPDATE_ENUM.number = 7
NOVICEBPPARAM_NOVICEBPPARAM_RETURN_TARGET_REWARD_GET_ENUM.name = "NOVICEBPPARAM_RETURN_TARGET_REWARD_GET"
NOVICEBPPARAM_NOVICEBPPARAM_RETURN_TARGET_REWARD_GET_ENUM.index = 7
NOVICEBPPARAM_NOVICEBPPARAM_RETURN_TARGET_REWARD_GET_ENUM.number = 8
NOVICEBPPARAM_NOVICEBPPARAM_RETURN_REWARD_GET_ENUM.name = "NOVICEBPPARAM_RETURN_REWARD_GET"
NOVICEBPPARAM_NOVICEBPPARAM_RETURN_REWARD_GET_ENUM.index = 8
NOVICEBPPARAM_NOVICEBPPARAM_RETURN_REWARD_GET_ENUM.number = 9
NOVICEBPPARAM_NOVICEBPPARAM_RETURN_BP_BUY_LEVEL_ENUM.name = "NOVICEBPPARAM_RETURN_BP_BUY_LEVEL"
NOVICEBPPARAM_NOVICEBPPARAM_RETURN_BP_BUY_LEVEL_ENUM.index = 9
NOVICEBPPARAM_NOVICEBPPARAM_RETURN_BP_BUY_LEVEL_ENUM.number = 10
NOVICEBPPARAM.name = "NoviceBPParam"
NOVICEBPPARAM.full_name = ".Cmd.NoviceBPParam"
NOVICEBPPARAM.values = {
  NOVICEBPPARAM_NOVICEBPPARAM_TARGET_UPDATE_ENUM,
  NOVICEBPPARAM_NOVICEBPPARAM_REWARD_UPDATE_ENUM,
  NOVICEBPPARAM_NOVICEBPPARAM_TARGET_GET_ENUM,
  NOVICEBPPARAM_NOVICEBPPARAM_BUY_LEVEL_ENUM,
  NOVICEBPPARAM_NOVICEBPPARAM_CHALLENGE_UPDATE_ENUM,
  NOVICEBPPARAM_NOVICEBPPARAM_RETURN_TARGET_UPDATE_ENUM,
  NOVICEBPPARAM_NOVICEBPPARAM_RETURN_REWARD_UPDATE_ENUM,
  NOVICEBPPARAM_NOVICEBPPARAM_RETURN_TARGET_REWARD_GET_ENUM,
  NOVICEBPPARAM_NOVICEBPPARAM_RETURN_REWARD_GET_ENUM,
  NOVICEBPPARAM_NOVICEBPPARAM_RETURN_BP_BUY_LEVEL_ENUM
}
NOVICEBPTARGETUPDATECMD_CMD_FIELD.name = "cmd"
NOVICEBPTARGETUPDATECMD_CMD_FIELD.full_name = ".Cmd.NoviceBPTargetUpdateCmd.cmd"
NOVICEBPTARGETUPDATECMD_CMD_FIELD.number = 1
NOVICEBPTARGETUPDATECMD_CMD_FIELD.index = 0
NOVICEBPTARGETUPDATECMD_CMD_FIELD.label = 1
NOVICEBPTARGETUPDATECMD_CMD_FIELD.has_default_value = true
NOVICEBPTARGETUPDATECMD_CMD_FIELD.default_value = 77
NOVICEBPTARGETUPDATECMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
NOVICEBPTARGETUPDATECMD_CMD_FIELD.type = 14
NOVICEBPTARGETUPDATECMD_CMD_FIELD.cpp_type = 8
NOVICEBPTARGETUPDATECMD_PARAM_FIELD.name = "param"
NOVICEBPTARGETUPDATECMD_PARAM_FIELD.full_name = ".Cmd.NoviceBPTargetUpdateCmd.param"
NOVICEBPTARGETUPDATECMD_PARAM_FIELD.number = 2
NOVICEBPTARGETUPDATECMD_PARAM_FIELD.index = 1
NOVICEBPTARGETUPDATECMD_PARAM_FIELD.label = 1
NOVICEBPTARGETUPDATECMD_PARAM_FIELD.has_default_value = true
NOVICEBPTARGETUPDATECMD_PARAM_FIELD.default_value = 1
NOVICEBPTARGETUPDATECMD_PARAM_FIELD.enum_type = NOVICEBPPARAM
NOVICEBPTARGETUPDATECMD_PARAM_FIELD.type = 14
NOVICEBPTARGETUPDATECMD_PARAM_FIELD.cpp_type = 8
NOVICEBPTARGETUPDATECMD_DATAS_FIELD.name = "datas"
NOVICEBPTARGETUPDATECMD_DATAS_FIELD.full_name = ".Cmd.NoviceBPTargetUpdateCmd.datas"
NOVICEBPTARGETUPDATECMD_DATAS_FIELD.number = 3
NOVICEBPTARGETUPDATECMD_DATAS_FIELD.index = 2
NOVICEBPTARGETUPDATECMD_DATAS_FIELD.label = 3
NOVICEBPTARGETUPDATECMD_DATAS_FIELD.has_default_value = false
NOVICEBPTARGETUPDATECMD_DATAS_FIELD.default_value = {}
NOVICEBPTARGETUPDATECMD_DATAS_FIELD.message_type = SceneUser2_pb.NOVICETARGETDATA
NOVICEBPTARGETUPDATECMD_DATAS_FIELD.type = 11
NOVICEBPTARGETUPDATECMD_DATAS_FIELD.cpp_type = 10
NOVICEBPTARGETUPDATECMD_END_TIME_FIELD.name = "end_time"
NOVICEBPTARGETUPDATECMD_END_TIME_FIELD.full_name = ".Cmd.NoviceBPTargetUpdateCmd.end_time"
NOVICEBPTARGETUPDATECMD_END_TIME_FIELD.number = 4
NOVICEBPTARGETUPDATECMD_END_TIME_FIELD.index = 3
NOVICEBPTARGETUPDATECMD_END_TIME_FIELD.label = 1
NOVICEBPTARGETUPDATECMD_END_TIME_FIELD.has_default_value = false
NOVICEBPTARGETUPDATECMD_END_TIME_FIELD.default_value = 0
NOVICEBPTARGETUPDATECMD_END_TIME_FIELD.type = 13
NOVICEBPTARGETUPDATECMD_END_TIME_FIELD.cpp_type = 3
NOVICEBPTARGETUPDATECMD_IS_PRO_FIELD.name = "is_pro"
NOVICEBPTARGETUPDATECMD_IS_PRO_FIELD.full_name = ".Cmd.NoviceBPTargetUpdateCmd.is_pro"
NOVICEBPTARGETUPDATECMD_IS_PRO_FIELD.number = 5
NOVICEBPTARGETUPDATECMD_IS_PRO_FIELD.index = 4
NOVICEBPTARGETUPDATECMD_IS_PRO_FIELD.label = 1
NOVICEBPTARGETUPDATECMD_IS_PRO_FIELD.has_default_value = false
NOVICEBPTARGETUPDATECMD_IS_PRO_FIELD.default_value = false
NOVICEBPTARGETUPDATECMD_IS_PRO_FIELD.type = 8
NOVICEBPTARGETUPDATECMD_IS_PRO_FIELD.cpp_type = 7
NOVICEBPTARGETUPDATECMD.name = "NoviceBPTargetUpdateCmd"
NOVICEBPTARGETUPDATECMD.full_name = ".Cmd.NoviceBPTargetUpdateCmd"
NOVICEBPTARGETUPDATECMD.nested_types = {}
NOVICEBPTARGETUPDATECMD.enum_types = {}
NOVICEBPTARGETUPDATECMD.fields = {
  NOVICEBPTARGETUPDATECMD_CMD_FIELD,
  NOVICEBPTARGETUPDATECMD_PARAM_FIELD,
  NOVICEBPTARGETUPDATECMD_DATAS_FIELD,
  NOVICEBPTARGETUPDATECMD_END_TIME_FIELD,
  NOVICEBPTARGETUPDATECMD_IS_PRO_FIELD
}
NOVICEBPTARGETUPDATECMD.is_extendable = false
NOVICEBPTARGETUPDATECMD.extensions = {}
NOVICEBPREWARDUPDATECMD_CMD_FIELD.name = "cmd"
NOVICEBPREWARDUPDATECMD_CMD_FIELD.full_name = ".Cmd.NoviceBPRewardUpdateCmd.cmd"
NOVICEBPREWARDUPDATECMD_CMD_FIELD.number = 1
NOVICEBPREWARDUPDATECMD_CMD_FIELD.index = 0
NOVICEBPREWARDUPDATECMD_CMD_FIELD.label = 1
NOVICEBPREWARDUPDATECMD_CMD_FIELD.has_default_value = true
NOVICEBPREWARDUPDATECMD_CMD_FIELD.default_value = 77
NOVICEBPREWARDUPDATECMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
NOVICEBPREWARDUPDATECMD_CMD_FIELD.type = 14
NOVICEBPREWARDUPDATECMD_CMD_FIELD.cpp_type = 8
NOVICEBPREWARDUPDATECMD_PARAM_FIELD.name = "param"
NOVICEBPREWARDUPDATECMD_PARAM_FIELD.full_name = ".Cmd.NoviceBPRewardUpdateCmd.param"
NOVICEBPREWARDUPDATECMD_PARAM_FIELD.number = 2
NOVICEBPREWARDUPDATECMD_PARAM_FIELD.index = 1
NOVICEBPREWARDUPDATECMD_PARAM_FIELD.label = 1
NOVICEBPREWARDUPDATECMD_PARAM_FIELD.has_default_value = true
NOVICEBPREWARDUPDATECMD_PARAM_FIELD.default_value = 2
NOVICEBPREWARDUPDATECMD_PARAM_FIELD.enum_type = NOVICEBPPARAM
NOVICEBPREWARDUPDATECMD_PARAM_FIELD.type = 14
NOVICEBPREWARDUPDATECMD_PARAM_FIELD.cpp_type = 8
NOVICEBPREWARDUPDATECMD_REWARDED_NORMAL_LVS_FIELD.name = "rewarded_normal_lvs"
NOVICEBPREWARDUPDATECMD_REWARDED_NORMAL_LVS_FIELD.full_name = ".Cmd.NoviceBPRewardUpdateCmd.rewarded_normal_lvs"
NOVICEBPREWARDUPDATECMD_REWARDED_NORMAL_LVS_FIELD.number = 3
NOVICEBPREWARDUPDATECMD_REWARDED_NORMAL_LVS_FIELD.index = 2
NOVICEBPREWARDUPDATECMD_REWARDED_NORMAL_LVS_FIELD.label = 3
NOVICEBPREWARDUPDATECMD_REWARDED_NORMAL_LVS_FIELD.has_default_value = false
NOVICEBPREWARDUPDATECMD_REWARDED_NORMAL_LVS_FIELD.default_value = {}
NOVICEBPREWARDUPDATECMD_REWARDED_NORMAL_LVS_FIELD.type = 13
NOVICEBPREWARDUPDATECMD_REWARDED_NORMAL_LVS_FIELD.cpp_type = 3
NOVICEBPREWARDUPDATECMD_REWARDED_PRO_LVS_FIELD.name = "rewarded_pro_lvs"
NOVICEBPREWARDUPDATECMD_REWARDED_PRO_LVS_FIELD.full_name = ".Cmd.NoviceBPRewardUpdateCmd.rewarded_pro_lvs"
NOVICEBPREWARDUPDATECMD_REWARDED_PRO_LVS_FIELD.number = 4
NOVICEBPREWARDUPDATECMD_REWARDED_PRO_LVS_FIELD.index = 3
NOVICEBPREWARDUPDATECMD_REWARDED_PRO_LVS_FIELD.label = 3
NOVICEBPREWARDUPDATECMD_REWARDED_PRO_LVS_FIELD.has_default_value = false
NOVICEBPREWARDUPDATECMD_REWARDED_PRO_LVS_FIELD.default_value = {}
NOVICEBPREWARDUPDATECMD_REWARDED_PRO_LVS_FIELD.type = 13
NOVICEBPREWARDUPDATECMD_REWARDED_PRO_LVS_FIELD.cpp_type = 3
NOVICEBPREWARDUPDATECMD.name = "NoviceBPRewardUpdateCmd"
NOVICEBPREWARDUPDATECMD.full_name = ".Cmd.NoviceBPRewardUpdateCmd"
NOVICEBPREWARDUPDATECMD.nested_types = {}
NOVICEBPREWARDUPDATECMD.enum_types = {}
NOVICEBPREWARDUPDATECMD.fields = {
  NOVICEBPREWARDUPDATECMD_CMD_FIELD,
  NOVICEBPREWARDUPDATECMD_PARAM_FIELD,
  NOVICEBPREWARDUPDATECMD_REWARDED_NORMAL_LVS_FIELD,
  NOVICEBPREWARDUPDATECMD_REWARDED_PRO_LVS_FIELD
}
NOVICEBPREWARDUPDATECMD.is_extendable = false
NOVICEBPREWARDUPDATECMD.extensions = {}
NOVICEBPTARGETREWARDCMD_CMD_FIELD.name = "cmd"
NOVICEBPTARGETREWARDCMD_CMD_FIELD.full_name = ".Cmd.NoviceBPTargetRewardCmd.cmd"
NOVICEBPTARGETREWARDCMD_CMD_FIELD.number = 1
NOVICEBPTARGETREWARDCMD_CMD_FIELD.index = 0
NOVICEBPTARGETREWARDCMD_CMD_FIELD.label = 1
NOVICEBPTARGETREWARDCMD_CMD_FIELD.has_default_value = true
NOVICEBPTARGETREWARDCMD_CMD_FIELD.default_value = 77
NOVICEBPTARGETREWARDCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
NOVICEBPTARGETREWARDCMD_CMD_FIELD.type = 14
NOVICEBPTARGETREWARDCMD_CMD_FIELD.cpp_type = 8
NOVICEBPTARGETREWARDCMD_PARAM_FIELD.name = "param"
NOVICEBPTARGETREWARDCMD_PARAM_FIELD.full_name = ".Cmd.NoviceBPTargetRewardCmd.param"
NOVICEBPTARGETREWARDCMD_PARAM_FIELD.number = 2
NOVICEBPTARGETREWARDCMD_PARAM_FIELD.index = 1
NOVICEBPTARGETREWARDCMD_PARAM_FIELD.label = 1
NOVICEBPTARGETREWARDCMD_PARAM_FIELD.has_default_value = true
NOVICEBPTARGETREWARDCMD_PARAM_FIELD.default_value = 3
NOVICEBPTARGETREWARDCMD_PARAM_FIELD.enum_type = NOVICEBPPARAM
NOVICEBPTARGETREWARDCMD_PARAM_FIELD.type = 14
NOVICEBPTARGETREWARDCMD_PARAM_FIELD.cpp_type = 8
NOVICEBPTARGETREWARDCMD_IS_ALL_FIELD.name = "is_all"
NOVICEBPTARGETREWARDCMD_IS_ALL_FIELD.full_name = ".Cmd.NoviceBPTargetRewardCmd.is_all"
NOVICEBPTARGETREWARDCMD_IS_ALL_FIELD.number = 3
NOVICEBPTARGETREWARDCMD_IS_ALL_FIELD.index = 2
NOVICEBPTARGETREWARDCMD_IS_ALL_FIELD.label = 1
NOVICEBPTARGETREWARDCMD_IS_ALL_FIELD.has_default_value = false
NOVICEBPTARGETREWARDCMD_IS_ALL_FIELD.default_value = false
NOVICEBPTARGETREWARDCMD_IS_ALL_FIELD.type = 8
NOVICEBPTARGETREWARDCMD_IS_ALL_FIELD.cpp_type = 7
NOVICEBPTARGETREWARDCMD_LV_FIELD.name = "lv"
NOVICEBPTARGETREWARDCMD_LV_FIELD.full_name = ".Cmd.NoviceBPTargetRewardCmd.lv"
NOVICEBPTARGETREWARDCMD_LV_FIELD.number = 4
NOVICEBPTARGETREWARDCMD_LV_FIELD.index = 3
NOVICEBPTARGETREWARDCMD_LV_FIELD.label = 1
NOVICEBPTARGETREWARDCMD_LV_FIELD.has_default_value = false
NOVICEBPTARGETREWARDCMD_LV_FIELD.default_value = 0
NOVICEBPTARGETREWARDCMD_LV_FIELD.type = 13
NOVICEBPTARGETREWARDCMD_LV_FIELD.cpp_type = 3
NOVICEBPTARGETREWARDCMD.name = "NoviceBPTargetRewardCmd"
NOVICEBPTARGETREWARDCMD.full_name = ".Cmd.NoviceBPTargetRewardCmd"
NOVICEBPTARGETREWARDCMD.nested_types = {}
NOVICEBPTARGETREWARDCMD.enum_types = {}
NOVICEBPTARGETREWARDCMD.fields = {
  NOVICEBPTARGETREWARDCMD_CMD_FIELD,
  NOVICEBPTARGETREWARDCMD_PARAM_FIELD,
  NOVICEBPTARGETREWARDCMD_IS_ALL_FIELD,
  NOVICEBPTARGETREWARDCMD_LV_FIELD
}
NOVICEBPTARGETREWARDCMD.is_extendable = false
NOVICEBPTARGETREWARDCMD.extensions = {}
NOVICEBPBUYLEVELCMD_CMD_FIELD.name = "cmd"
NOVICEBPBUYLEVELCMD_CMD_FIELD.full_name = ".Cmd.NoviceBpBuyLevelCmd.cmd"
NOVICEBPBUYLEVELCMD_CMD_FIELD.number = 1
NOVICEBPBUYLEVELCMD_CMD_FIELD.index = 0
NOVICEBPBUYLEVELCMD_CMD_FIELD.label = 1
NOVICEBPBUYLEVELCMD_CMD_FIELD.has_default_value = true
NOVICEBPBUYLEVELCMD_CMD_FIELD.default_value = 77
NOVICEBPBUYLEVELCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
NOVICEBPBUYLEVELCMD_CMD_FIELD.type = 14
NOVICEBPBUYLEVELCMD_CMD_FIELD.cpp_type = 8
NOVICEBPBUYLEVELCMD_PARAM_FIELD.name = "param"
NOVICEBPBUYLEVELCMD_PARAM_FIELD.full_name = ".Cmd.NoviceBpBuyLevelCmd.param"
NOVICEBPBUYLEVELCMD_PARAM_FIELD.number = 2
NOVICEBPBUYLEVELCMD_PARAM_FIELD.index = 1
NOVICEBPBUYLEVELCMD_PARAM_FIELD.label = 1
NOVICEBPBUYLEVELCMD_PARAM_FIELD.has_default_value = true
NOVICEBPBUYLEVELCMD_PARAM_FIELD.default_value = 4
NOVICEBPBUYLEVELCMD_PARAM_FIELD.enum_type = NOVICEBPPARAM
NOVICEBPBUYLEVELCMD_PARAM_FIELD.type = 14
NOVICEBPBUYLEVELCMD_PARAM_FIELD.cpp_type = 8
NOVICEBPBUYLEVELCMD_LEVEL_FIELD.name = "level"
NOVICEBPBUYLEVELCMD_LEVEL_FIELD.full_name = ".Cmd.NoviceBpBuyLevelCmd.level"
NOVICEBPBUYLEVELCMD_LEVEL_FIELD.number = 3
NOVICEBPBUYLEVELCMD_LEVEL_FIELD.index = 2
NOVICEBPBUYLEVELCMD_LEVEL_FIELD.label = 1
NOVICEBPBUYLEVELCMD_LEVEL_FIELD.has_default_value = false
NOVICEBPBUYLEVELCMD_LEVEL_FIELD.default_value = 0
NOVICEBPBUYLEVELCMD_LEVEL_FIELD.type = 13
NOVICEBPBUYLEVELCMD_LEVEL_FIELD.cpp_type = 3
NOVICEBPBUYLEVELCMD.name = "NoviceBpBuyLevelCmd"
NOVICEBPBUYLEVELCMD.full_name = ".Cmd.NoviceBpBuyLevelCmd"
NOVICEBPBUYLEVELCMD.nested_types = {}
NOVICEBPBUYLEVELCMD.enum_types = {}
NOVICEBPBUYLEVELCMD.fields = {
  NOVICEBPBUYLEVELCMD_CMD_FIELD,
  NOVICEBPBUYLEVELCMD_PARAM_FIELD,
  NOVICEBPBUYLEVELCMD_LEVEL_FIELD
}
NOVICEBPBUYLEVELCMD.is_extendable = false
NOVICEBPBUYLEVELCMD.extensions = {}
CHALLENGETARGETUPDATECMD_CMD_FIELD.name = "cmd"
CHALLENGETARGETUPDATECMD_CMD_FIELD.full_name = ".Cmd.ChallengeTargetUpdateCmd.cmd"
CHALLENGETARGETUPDATECMD_CMD_FIELD.number = 1
CHALLENGETARGETUPDATECMD_CMD_FIELD.index = 0
CHALLENGETARGETUPDATECMD_CMD_FIELD.label = 1
CHALLENGETARGETUPDATECMD_CMD_FIELD.has_default_value = true
CHALLENGETARGETUPDATECMD_CMD_FIELD.default_value = 77
CHALLENGETARGETUPDATECMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
CHALLENGETARGETUPDATECMD_CMD_FIELD.type = 14
CHALLENGETARGETUPDATECMD_CMD_FIELD.cpp_type = 8
CHALLENGETARGETUPDATECMD_PARAM_FIELD.name = "param"
CHALLENGETARGETUPDATECMD_PARAM_FIELD.full_name = ".Cmd.ChallengeTargetUpdateCmd.param"
CHALLENGETARGETUPDATECMD_PARAM_FIELD.number = 2
CHALLENGETARGETUPDATECMD_PARAM_FIELD.index = 1
CHALLENGETARGETUPDATECMD_PARAM_FIELD.label = 1
CHALLENGETARGETUPDATECMD_PARAM_FIELD.has_default_value = true
CHALLENGETARGETUPDATECMD_PARAM_FIELD.default_value = 5
CHALLENGETARGETUPDATECMD_PARAM_FIELD.enum_type = NOVICEBPPARAM
CHALLENGETARGETUPDATECMD_PARAM_FIELD.type = 14
CHALLENGETARGETUPDATECMD_PARAM_FIELD.cpp_type = 8
CHALLENGETARGETUPDATECMD_DATAS_FIELD.name = "datas"
CHALLENGETARGETUPDATECMD_DATAS_FIELD.full_name = ".Cmd.ChallengeTargetUpdateCmd.datas"
CHALLENGETARGETUPDATECMD_DATAS_FIELD.number = 3
CHALLENGETARGETUPDATECMD_DATAS_FIELD.index = 2
CHALLENGETARGETUPDATECMD_DATAS_FIELD.label = 3
CHALLENGETARGETUPDATECMD_DATAS_FIELD.has_default_value = false
CHALLENGETARGETUPDATECMD_DATAS_FIELD.default_value = {}
CHALLENGETARGETUPDATECMD_DATAS_FIELD.message_type = SceneUser2_pb.NOVICETARGETDATA
CHALLENGETARGETUPDATECMD_DATAS_FIELD.type = 11
CHALLENGETARGETUPDATECMD_DATAS_FIELD.cpp_type = 10
CHALLENGETARGETUPDATECMD.name = "ChallengeTargetUpdateCmd"
CHALLENGETARGETUPDATECMD.full_name = ".Cmd.ChallengeTargetUpdateCmd"
CHALLENGETARGETUPDATECMD.nested_types = {}
CHALLENGETARGETUPDATECMD.enum_types = {}
CHALLENGETARGETUPDATECMD.fields = {
  CHALLENGETARGETUPDATECMD_CMD_FIELD,
  CHALLENGETARGETUPDATECMD_PARAM_FIELD,
  CHALLENGETARGETUPDATECMD_DATAS_FIELD
}
CHALLENGETARGETUPDATECMD.is_extendable = false
CHALLENGETARGETUPDATECMD.extensions = {}
RETURNBPTARGETUPDATECMD_CMD_FIELD.name = "cmd"
RETURNBPTARGETUPDATECMD_CMD_FIELD.full_name = ".Cmd.ReturnBpTargetUpdateCmd.cmd"
RETURNBPTARGETUPDATECMD_CMD_FIELD.number = 1
RETURNBPTARGETUPDATECMD_CMD_FIELD.index = 0
RETURNBPTARGETUPDATECMD_CMD_FIELD.label = 1
RETURNBPTARGETUPDATECMD_CMD_FIELD.has_default_value = true
RETURNBPTARGETUPDATECMD_CMD_FIELD.default_value = 77
RETURNBPTARGETUPDATECMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
RETURNBPTARGETUPDATECMD_CMD_FIELD.type = 14
RETURNBPTARGETUPDATECMD_CMD_FIELD.cpp_type = 8
RETURNBPTARGETUPDATECMD_PARAM_FIELD.name = "param"
RETURNBPTARGETUPDATECMD_PARAM_FIELD.full_name = ".Cmd.ReturnBpTargetUpdateCmd.param"
RETURNBPTARGETUPDATECMD_PARAM_FIELD.number = 2
RETURNBPTARGETUPDATECMD_PARAM_FIELD.index = 1
RETURNBPTARGETUPDATECMD_PARAM_FIELD.label = 1
RETURNBPTARGETUPDATECMD_PARAM_FIELD.has_default_value = true
RETURNBPTARGETUPDATECMD_PARAM_FIELD.default_value = 6
RETURNBPTARGETUPDATECMD_PARAM_FIELD.enum_type = NOVICEBPPARAM
RETURNBPTARGETUPDATECMD_PARAM_FIELD.type = 14
RETURNBPTARGETUPDATECMD_PARAM_FIELD.cpp_type = 8
RETURNBPTARGETUPDATECMD_DATAS_FIELD.name = "datas"
RETURNBPTARGETUPDATECMD_DATAS_FIELD.full_name = ".Cmd.ReturnBpTargetUpdateCmd.datas"
RETURNBPTARGETUPDATECMD_DATAS_FIELD.number = 3
RETURNBPTARGETUPDATECMD_DATAS_FIELD.index = 2
RETURNBPTARGETUPDATECMD_DATAS_FIELD.label = 3
RETURNBPTARGETUPDATECMD_DATAS_FIELD.has_default_value = false
RETURNBPTARGETUPDATECMD_DATAS_FIELD.default_value = {}
RETURNBPTARGETUPDATECMD_DATAS_FIELD.message_type = SceneUser2_pb.NOVICETARGETDATA
RETURNBPTARGETUPDATECMD_DATAS_FIELD.type = 11
RETURNBPTARGETUPDATECMD_DATAS_FIELD.cpp_type = 10
RETURNBPTARGETUPDATECMD_END_TIME_FIELD.name = "end_time"
RETURNBPTARGETUPDATECMD_END_TIME_FIELD.full_name = ".Cmd.ReturnBpTargetUpdateCmd.end_time"
RETURNBPTARGETUPDATECMD_END_TIME_FIELD.number = 4
RETURNBPTARGETUPDATECMD_END_TIME_FIELD.index = 3
RETURNBPTARGETUPDATECMD_END_TIME_FIELD.label = 1
RETURNBPTARGETUPDATECMD_END_TIME_FIELD.has_default_value = false
RETURNBPTARGETUPDATECMD_END_TIME_FIELD.default_value = 0
RETURNBPTARGETUPDATECMD_END_TIME_FIELD.type = 13
RETURNBPTARGETUPDATECMD_END_TIME_FIELD.cpp_type = 3
RETURNBPTARGETUPDATECMD_IS_PRO_FIELD.name = "is_pro"
RETURNBPTARGETUPDATECMD_IS_PRO_FIELD.full_name = ".Cmd.ReturnBpTargetUpdateCmd.is_pro"
RETURNBPTARGETUPDATECMD_IS_PRO_FIELD.number = 5
RETURNBPTARGETUPDATECMD_IS_PRO_FIELD.index = 4
RETURNBPTARGETUPDATECMD_IS_PRO_FIELD.label = 1
RETURNBPTARGETUPDATECMD_IS_PRO_FIELD.has_default_value = false
RETURNBPTARGETUPDATECMD_IS_PRO_FIELD.default_value = false
RETURNBPTARGETUPDATECMD_IS_PRO_FIELD.type = 8
RETURNBPTARGETUPDATECMD_IS_PRO_FIELD.cpp_type = 7
RETURNBPTARGETUPDATECMD_VERSION_FIELD.name = "version"
RETURNBPTARGETUPDATECMD_VERSION_FIELD.full_name = ".Cmd.ReturnBpTargetUpdateCmd.version"
RETURNBPTARGETUPDATECMD_VERSION_FIELD.number = 6
RETURNBPTARGETUPDATECMD_VERSION_FIELD.index = 5
RETURNBPTARGETUPDATECMD_VERSION_FIELD.label = 1
RETURNBPTARGETUPDATECMD_VERSION_FIELD.has_default_value = false
RETURNBPTARGETUPDATECMD_VERSION_FIELD.default_value = 0
RETURNBPTARGETUPDATECMD_VERSION_FIELD.type = 13
RETURNBPTARGETUPDATECMD_VERSION_FIELD.cpp_type = 3
RETURNBPTARGETUPDATECMD_BP_CLASS_FIELD.name = "bp_class"
RETURNBPTARGETUPDATECMD_BP_CLASS_FIELD.full_name = ".Cmd.ReturnBpTargetUpdateCmd.bp_class"
RETURNBPTARGETUPDATECMD_BP_CLASS_FIELD.number = 7
RETURNBPTARGETUPDATECMD_BP_CLASS_FIELD.index = 6
RETURNBPTARGETUPDATECMD_BP_CLASS_FIELD.label = 1
RETURNBPTARGETUPDATECMD_BP_CLASS_FIELD.has_default_value = false
RETURNBPTARGETUPDATECMD_BP_CLASS_FIELD.default_value = 0
RETURNBPTARGETUPDATECMD_BP_CLASS_FIELD.type = 13
RETURNBPTARGETUPDATECMD_BP_CLASS_FIELD.cpp_type = 3
RETURNBPTARGETUPDATECMD_RETURN_REWARD_GOT_FIELD.name = "return_reward_got"
RETURNBPTARGETUPDATECMD_RETURN_REWARD_GOT_FIELD.full_name = ".Cmd.ReturnBpTargetUpdateCmd.return_reward_got"
RETURNBPTARGETUPDATECMD_RETURN_REWARD_GOT_FIELD.number = 8
RETURNBPTARGETUPDATECMD_RETURN_REWARD_GOT_FIELD.index = 7
RETURNBPTARGETUPDATECMD_RETURN_REWARD_GOT_FIELD.label = 1
RETURNBPTARGETUPDATECMD_RETURN_REWARD_GOT_FIELD.has_default_value = false
RETURNBPTARGETUPDATECMD_RETURN_REWARD_GOT_FIELD.default_value = false
RETURNBPTARGETUPDATECMD_RETURN_REWARD_GOT_FIELD.type = 8
RETURNBPTARGETUPDATECMD_RETURN_REWARD_GOT_FIELD.cpp_type = 7
RETURNBPTARGETUPDATECMD.name = "ReturnBpTargetUpdateCmd"
RETURNBPTARGETUPDATECMD.full_name = ".Cmd.ReturnBpTargetUpdateCmd"
RETURNBPTARGETUPDATECMD.nested_types = {}
RETURNBPTARGETUPDATECMD.enum_types = {}
RETURNBPTARGETUPDATECMD.fields = {
  RETURNBPTARGETUPDATECMD_CMD_FIELD,
  RETURNBPTARGETUPDATECMD_PARAM_FIELD,
  RETURNBPTARGETUPDATECMD_DATAS_FIELD,
  RETURNBPTARGETUPDATECMD_END_TIME_FIELD,
  RETURNBPTARGETUPDATECMD_IS_PRO_FIELD,
  RETURNBPTARGETUPDATECMD_VERSION_FIELD,
  RETURNBPTARGETUPDATECMD_BP_CLASS_FIELD,
  RETURNBPTARGETUPDATECMD_RETURN_REWARD_GOT_FIELD
}
RETURNBPTARGETUPDATECMD.is_extendable = false
RETURNBPTARGETUPDATECMD.extensions = {}
RETURNBPREWARDUPDATECMD_CMD_FIELD.name = "cmd"
RETURNBPREWARDUPDATECMD_CMD_FIELD.full_name = ".Cmd.ReturnBPRewardUpdateCmd.cmd"
RETURNBPREWARDUPDATECMD_CMD_FIELD.number = 1
RETURNBPREWARDUPDATECMD_CMD_FIELD.index = 0
RETURNBPREWARDUPDATECMD_CMD_FIELD.label = 1
RETURNBPREWARDUPDATECMD_CMD_FIELD.has_default_value = true
RETURNBPREWARDUPDATECMD_CMD_FIELD.default_value = 77
RETURNBPREWARDUPDATECMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
RETURNBPREWARDUPDATECMD_CMD_FIELD.type = 14
RETURNBPREWARDUPDATECMD_CMD_FIELD.cpp_type = 8
RETURNBPREWARDUPDATECMD_PARAM_FIELD.name = "param"
RETURNBPREWARDUPDATECMD_PARAM_FIELD.full_name = ".Cmd.ReturnBPRewardUpdateCmd.param"
RETURNBPREWARDUPDATECMD_PARAM_FIELD.number = 2
RETURNBPREWARDUPDATECMD_PARAM_FIELD.index = 1
RETURNBPREWARDUPDATECMD_PARAM_FIELD.label = 1
RETURNBPREWARDUPDATECMD_PARAM_FIELD.has_default_value = true
RETURNBPREWARDUPDATECMD_PARAM_FIELD.default_value = 7
RETURNBPREWARDUPDATECMD_PARAM_FIELD.enum_type = NOVICEBPPARAM
RETURNBPREWARDUPDATECMD_PARAM_FIELD.type = 14
RETURNBPREWARDUPDATECMD_PARAM_FIELD.cpp_type = 8
RETURNBPREWARDUPDATECMD_REWARDED_NORMAL_LVS_FIELD.name = "rewarded_normal_lvs"
RETURNBPREWARDUPDATECMD_REWARDED_NORMAL_LVS_FIELD.full_name = ".Cmd.ReturnBPRewardUpdateCmd.rewarded_normal_lvs"
RETURNBPREWARDUPDATECMD_REWARDED_NORMAL_LVS_FIELD.number = 3
RETURNBPREWARDUPDATECMD_REWARDED_NORMAL_LVS_FIELD.index = 2
RETURNBPREWARDUPDATECMD_REWARDED_NORMAL_LVS_FIELD.label = 3
RETURNBPREWARDUPDATECMD_REWARDED_NORMAL_LVS_FIELD.has_default_value = false
RETURNBPREWARDUPDATECMD_REWARDED_NORMAL_LVS_FIELD.default_value = {}
RETURNBPREWARDUPDATECMD_REWARDED_NORMAL_LVS_FIELD.type = 13
RETURNBPREWARDUPDATECMD_REWARDED_NORMAL_LVS_FIELD.cpp_type = 3
RETURNBPREWARDUPDATECMD_REWARDED_PRO_LVS_FIELD.name = "rewarded_pro_lvs"
RETURNBPREWARDUPDATECMD_REWARDED_PRO_LVS_FIELD.full_name = ".Cmd.ReturnBPRewardUpdateCmd.rewarded_pro_lvs"
RETURNBPREWARDUPDATECMD_REWARDED_PRO_LVS_FIELD.number = 4
RETURNBPREWARDUPDATECMD_REWARDED_PRO_LVS_FIELD.index = 3
RETURNBPREWARDUPDATECMD_REWARDED_PRO_LVS_FIELD.label = 3
RETURNBPREWARDUPDATECMD_REWARDED_PRO_LVS_FIELD.has_default_value = false
RETURNBPREWARDUPDATECMD_REWARDED_PRO_LVS_FIELD.default_value = {}
RETURNBPREWARDUPDATECMD_REWARDED_PRO_LVS_FIELD.type = 13
RETURNBPREWARDUPDATECMD_REWARDED_PRO_LVS_FIELD.cpp_type = 3
RETURNBPREWARDUPDATECMD.name = "ReturnBPRewardUpdateCmd"
RETURNBPREWARDUPDATECMD.full_name = ".Cmd.ReturnBPRewardUpdateCmd"
RETURNBPREWARDUPDATECMD.nested_types = {}
RETURNBPREWARDUPDATECMD.enum_types = {}
RETURNBPREWARDUPDATECMD.fields = {
  RETURNBPREWARDUPDATECMD_CMD_FIELD,
  RETURNBPREWARDUPDATECMD_PARAM_FIELD,
  RETURNBPREWARDUPDATECMD_REWARDED_NORMAL_LVS_FIELD,
  RETURNBPREWARDUPDATECMD_REWARDED_PRO_LVS_FIELD
}
RETURNBPREWARDUPDATECMD.is_extendable = false
RETURNBPREWARDUPDATECMD.extensions = {}
RETURNBPTARGETREWARDCMD_CMD_FIELD.name = "cmd"
RETURNBPTARGETREWARDCMD_CMD_FIELD.full_name = ".Cmd.ReturnBPTargetRewardCmd.cmd"
RETURNBPTARGETREWARDCMD_CMD_FIELD.number = 1
RETURNBPTARGETREWARDCMD_CMD_FIELD.index = 0
RETURNBPTARGETREWARDCMD_CMD_FIELD.label = 1
RETURNBPTARGETREWARDCMD_CMD_FIELD.has_default_value = true
RETURNBPTARGETREWARDCMD_CMD_FIELD.default_value = 77
RETURNBPTARGETREWARDCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
RETURNBPTARGETREWARDCMD_CMD_FIELD.type = 14
RETURNBPTARGETREWARDCMD_CMD_FIELD.cpp_type = 8
RETURNBPTARGETREWARDCMD_PARAM_FIELD.name = "param"
RETURNBPTARGETREWARDCMD_PARAM_FIELD.full_name = ".Cmd.ReturnBPTargetRewardCmd.param"
RETURNBPTARGETREWARDCMD_PARAM_FIELD.number = 2
RETURNBPTARGETREWARDCMD_PARAM_FIELD.index = 1
RETURNBPTARGETREWARDCMD_PARAM_FIELD.label = 1
RETURNBPTARGETREWARDCMD_PARAM_FIELD.has_default_value = true
RETURNBPTARGETREWARDCMD_PARAM_FIELD.default_value = 8
RETURNBPTARGETREWARDCMD_PARAM_FIELD.enum_type = NOVICEBPPARAM
RETURNBPTARGETREWARDCMD_PARAM_FIELD.type = 14
RETURNBPTARGETREWARDCMD_PARAM_FIELD.cpp_type = 8
RETURNBPTARGETREWARDCMD_IS_ALL_FIELD.name = "is_all"
RETURNBPTARGETREWARDCMD_IS_ALL_FIELD.full_name = ".Cmd.ReturnBPTargetRewardCmd.is_all"
RETURNBPTARGETREWARDCMD_IS_ALL_FIELD.number = 3
RETURNBPTARGETREWARDCMD_IS_ALL_FIELD.index = 2
RETURNBPTARGETREWARDCMD_IS_ALL_FIELD.label = 1
RETURNBPTARGETREWARDCMD_IS_ALL_FIELD.has_default_value = false
RETURNBPTARGETREWARDCMD_IS_ALL_FIELD.default_value = false
RETURNBPTARGETREWARDCMD_IS_ALL_FIELD.type = 8
RETURNBPTARGETREWARDCMD_IS_ALL_FIELD.cpp_type = 7
RETURNBPTARGETREWARDCMD_LV_FIELD.name = "lv"
RETURNBPTARGETREWARDCMD_LV_FIELD.full_name = ".Cmd.ReturnBPTargetRewardCmd.lv"
RETURNBPTARGETREWARDCMD_LV_FIELD.number = 4
RETURNBPTARGETREWARDCMD_LV_FIELD.index = 3
RETURNBPTARGETREWARDCMD_LV_FIELD.label = 1
RETURNBPTARGETREWARDCMD_LV_FIELD.has_default_value = false
RETURNBPTARGETREWARDCMD_LV_FIELD.default_value = 0
RETURNBPTARGETREWARDCMD_LV_FIELD.type = 13
RETURNBPTARGETREWARDCMD_LV_FIELD.cpp_type = 3
RETURNBPTARGETREWARDCMD.name = "ReturnBPTargetRewardCmd"
RETURNBPTARGETREWARDCMD.full_name = ".Cmd.ReturnBPTargetRewardCmd"
RETURNBPTARGETREWARDCMD.nested_types = {}
RETURNBPTARGETREWARDCMD.enum_types = {}
RETURNBPTARGETREWARDCMD.fields = {
  RETURNBPTARGETREWARDCMD_CMD_FIELD,
  RETURNBPTARGETREWARDCMD_PARAM_FIELD,
  RETURNBPTARGETREWARDCMD_IS_ALL_FIELD,
  RETURNBPTARGETREWARDCMD_LV_FIELD
}
RETURNBPTARGETREWARDCMD.is_extendable = false
RETURNBPTARGETREWARDCMD.extensions = {}
RETURNBPRETURNREWARDCMD_CMD_FIELD.name = "cmd"
RETURNBPRETURNREWARDCMD_CMD_FIELD.full_name = ".Cmd.ReturnBPReturnRewardCmd.cmd"
RETURNBPRETURNREWARDCMD_CMD_FIELD.number = 1
RETURNBPRETURNREWARDCMD_CMD_FIELD.index = 0
RETURNBPRETURNREWARDCMD_CMD_FIELD.label = 1
RETURNBPRETURNREWARDCMD_CMD_FIELD.has_default_value = true
RETURNBPRETURNREWARDCMD_CMD_FIELD.default_value = 77
RETURNBPRETURNREWARDCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
RETURNBPRETURNREWARDCMD_CMD_FIELD.type = 14
RETURNBPRETURNREWARDCMD_CMD_FIELD.cpp_type = 8
RETURNBPRETURNREWARDCMD_PARAM_FIELD.name = "param"
RETURNBPRETURNREWARDCMD_PARAM_FIELD.full_name = ".Cmd.ReturnBPReturnRewardCmd.param"
RETURNBPRETURNREWARDCMD_PARAM_FIELD.number = 2
RETURNBPRETURNREWARDCMD_PARAM_FIELD.index = 1
RETURNBPRETURNREWARDCMD_PARAM_FIELD.label = 1
RETURNBPRETURNREWARDCMD_PARAM_FIELD.has_default_value = true
RETURNBPRETURNREWARDCMD_PARAM_FIELD.default_value = 9
RETURNBPRETURNREWARDCMD_PARAM_FIELD.enum_type = NOVICEBPPARAM
RETURNBPRETURNREWARDCMD_PARAM_FIELD.type = 14
RETURNBPRETURNREWARDCMD_PARAM_FIELD.cpp_type = 8
RETURNBPRETURNREWARDCMD.name = "ReturnBPReturnRewardCmd"
RETURNBPRETURNREWARDCMD.full_name = ".Cmd.ReturnBPReturnRewardCmd"
RETURNBPRETURNREWARDCMD.nested_types = {}
RETURNBPRETURNREWARDCMD.enum_types = {}
RETURNBPRETURNREWARDCMD.fields = {
  RETURNBPRETURNREWARDCMD_CMD_FIELD,
  RETURNBPRETURNREWARDCMD_PARAM_FIELD
}
RETURNBPRETURNREWARDCMD.is_extendable = false
RETURNBPRETURNREWARDCMD.extensions = {}
RETURNBPBUYLEVELCMD_CMD_FIELD.name = "cmd"
RETURNBPBUYLEVELCMD_CMD_FIELD.full_name = ".Cmd.ReturnBpBuyLevelCmd.cmd"
RETURNBPBUYLEVELCMD_CMD_FIELD.number = 1
RETURNBPBUYLEVELCMD_CMD_FIELD.index = 0
RETURNBPBUYLEVELCMD_CMD_FIELD.label = 1
RETURNBPBUYLEVELCMD_CMD_FIELD.has_default_value = true
RETURNBPBUYLEVELCMD_CMD_FIELD.default_value = 77
RETURNBPBUYLEVELCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
RETURNBPBUYLEVELCMD_CMD_FIELD.type = 14
RETURNBPBUYLEVELCMD_CMD_FIELD.cpp_type = 8
RETURNBPBUYLEVELCMD_PARAM_FIELD.name = "param"
RETURNBPBUYLEVELCMD_PARAM_FIELD.full_name = ".Cmd.ReturnBpBuyLevelCmd.param"
RETURNBPBUYLEVELCMD_PARAM_FIELD.number = 2
RETURNBPBUYLEVELCMD_PARAM_FIELD.index = 1
RETURNBPBUYLEVELCMD_PARAM_FIELD.label = 1
RETURNBPBUYLEVELCMD_PARAM_FIELD.has_default_value = true
RETURNBPBUYLEVELCMD_PARAM_FIELD.default_value = 10
RETURNBPBUYLEVELCMD_PARAM_FIELD.enum_type = NOVICEBPPARAM
RETURNBPBUYLEVELCMD_PARAM_FIELD.type = 14
RETURNBPBUYLEVELCMD_PARAM_FIELD.cpp_type = 8
RETURNBPBUYLEVELCMD_LEVEL_FIELD.name = "level"
RETURNBPBUYLEVELCMD_LEVEL_FIELD.full_name = ".Cmd.ReturnBpBuyLevelCmd.level"
RETURNBPBUYLEVELCMD_LEVEL_FIELD.number = 3
RETURNBPBUYLEVELCMD_LEVEL_FIELD.index = 2
RETURNBPBUYLEVELCMD_LEVEL_FIELD.label = 1
RETURNBPBUYLEVELCMD_LEVEL_FIELD.has_default_value = false
RETURNBPBUYLEVELCMD_LEVEL_FIELD.default_value = 0
RETURNBPBUYLEVELCMD_LEVEL_FIELD.type = 13
RETURNBPBUYLEVELCMD_LEVEL_FIELD.cpp_type = 3
RETURNBPBUYLEVELCMD.name = "ReturnBpBuyLevelCmd"
RETURNBPBUYLEVELCMD.full_name = ".Cmd.ReturnBpBuyLevelCmd"
RETURNBPBUYLEVELCMD.nested_types = {}
RETURNBPBUYLEVELCMD.enum_types = {}
RETURNBPBUYLEVELCMD.fields = {
  RETURNBPBUYLEVELCMD_CMD_FIELD,
  RETURNBPBUYLEVELCMD_PARAM_FIELD,
  RETURNBPBUYLEVELCMD_LEVEL_FIELD
}
RETURNBPBUYLEVELCMD.is_extendable = false
RETURNBPBUYLEVELCMD.extensions = {}
ChallengeTargetUpdateCmd = protobuf.Message(CHALLENGETARGETUPDATECMD)
NOVICEBPPARAM_BUY_LEVEL = 4
NOVICEBPPARAM_CHALLENGE_UPDATE = 5
NOVICEBPPARAM_RETURN_BP_BUY_LEVEL = 10
NOVICEBPPARAM_RETURN_REWARD_GET = 9
NOVICEBPPARAM_RETURN_REWARD_UPDATE = 7
NOVICEBPPARAM_RETURN_TARGET_REWARD_GET = 8
NOVICEBPPARAM_RETURN_TARGET_UPDATE = 6
NOVICEBPPARAM_REWARD_UPDATE = 2
NOVICEBPPARAM_TARGET_GET = 3
NOVICEBPPARAM_TARGET_UPDATE = 1
NoviceBPRewardUpdateCmd = protobuf.Message(NOVICEBPREWARDUPDATECMD)
NoviceBPTargetRewardCmd = protobuf.Message(NOVICEBPTARGETREWARDCMD)
NoviceBPTargetUpdateCmd = protobuf.Message(NOVICEBPTARGETUPDATECMD)
NoviceBpBuyLevelCmd = protobuf.Message(NOVICEBPBUYLEVELCMD)
ReturnBPReturnRewardCmd = protobuf.Message(RETURNBPRETURNREWARDCMD)
ReturnBPRewardUpdateCmd = protobuf.Message(RETURNBPREWARDUPDATECMD)
ReturnBPTargetRewardCmd = protobuf.Message(RETURNBPTARGETREWARDCMD)
ReturnBpBuyLevelCmd = protobuf.Message(RETURNBPBUYLEVELCMD)
ReturnBpTargetUpdateCmd = protobuf.Message(RETURNBPTARGETUPDATECMD)
