local protobuf = protobuf
autoImport("xCmd_pb")
local xCmd_pb = xCmd_pb
module("QueueEnterCmd_pb")
QUEUEENTERPARAM = protobuf.EnumDescriptor()
QUEUEENTERPARAM_QUEUE_ENTER_NOTIFY_ENUM = protobuf.EnumValueDescriptor()
QUEUEENTERPARAM_QUEUE_ENTER_REQ_ENUM = protobuf.EnumValueDescriptor()
QUEUEENTERPARAM_QUEUE_ENTER_RESULT_ENUM = protobuf.EnumValueDescriptor()
QUEUEENTERPARAM_QUEUE_ENTER_UPDATE_ENUM = protobuf.EnumValueDescriptor()
EQUEUEENTERTYPE = protobuf.EnumDescriptor()
EQUEUEENTERTYPE_EQUEUEENTERTYPE_MIN_ENUM = protobuf.EnumValueDescriptor()
EQUEUEENTERTYPE_EQUEUEENTERTYPE_GVG_ATT_ENUM = protobuf.EnumValueDescriptor()
EQUEUEENTERTYPE_EQUEUEENTERTYPE_GVG_DEF_ENUM = protobuf.EnumValueDescriptor()
QUEUEENTERRETCMD = protobuf.Descriptor()
QUEUEENTERRETCMD_CMD_FIELD = protobuf.FieldDescriptor()
QUEUEENTERRETCMD_PARAM_FIELD = protobuf.FieldDescriptor()
QUEUEENTERRETCMD_STOP_FIELD = protobuf.FieldDescriptor()
QUEUEENTERRETCMD_WAITNUM_FIELD = protobuf.FieldDescriptor()
QUEUEENTERRETCMD_ETYPE_FIELD = protobuf.FieldDescriptor()
QUEUEUPDATECOUNTCMD = protobuf.Descriptor()
QUEUEUPDATECOUNTCMD_CMD_FIELD = protobuf.FieldDescriptor()
QUEUEUPDATECOUNTCMD_PARAM_FIELD = protobuf.FieldDescriptor()
QUEUEUPDATECOUNTCMD_DEC_NUM_FIELD = protobuf.FieldDescriptor()
QUEUEUPDATECOUNTCMD_ETYPE_FIELD = protobuf.FieldDescriptor()
REQUIREQUEUENOTIFYCMD = protobuf.Descriptor()
REQUIREQUEUENOTIFYCMD_CMD_FIELD = protobuf.FieldDescriptor()
REQUIREQUEUENOTIFYCMD_PARAM_FIELD = protobuf.FieldDescriptor()
REQUIREQUEUENOTIFYCMD_ETYPE_FIELD = protobuf.FieldDescriptor()
REQQUEUEENTERCMD = protobuf.Descriptor()
REQQUEUEENTERCMD_CMD_FIELD = protobuf.FieldDescriptor()
REQQUEUEENTERCMD_PARAM_FIELD = protobuf.FieldDescriptor()
REQQUEUEENTERCMD_STOP_FIELD = protobuf.FieldDescriptor()
REQQUEUEENTERCMD_ETYPE_FIELD = protobuf.FieldDescriptor()
QUEUEENTERPARAM_QUEUE_ENTER_NOTIFY_ENUM.name = "QUEUE_ENTER_NOTIFY"
QUEUEENTERPARAM_QUEUE_ENTER_NOTIFY_ENUM.index = 0
QUEUEENTERPARAM_QUEUE_ENTER_NOTIFY_ENUM.number = 1
QUEUEENTERPARAM_QUEUE_ENTER_REQ_ENUM.name = "QUEUE_ENTER_REQ"
QUEUEENTERPARAM_QUEUE_ENTER_REQ_ENUM.index = 1
QUEUEENTERPARAM_QUEUE_ENTER_REQ_ENUM.number = 2
QUEUEENTERPARAM_QUEUE_ENTER_RESULT_ENUM.name = "QUEUE_ENTER_RESULT"
QUEUEENTERPARAM_QUEUE_ENTER_RESULT_ENUM.index = 2
QUEUEENTERPARAM_QUEUE_ENTER_RESULT_ENUM.number = 3
QUEUEENTERPARAM_QUEUE_ENTER_UPDATE_ENUM.name = "QUEUE_ENTER_UPDATE"
QUEUEENTERPARAM_QUEUE_ENTER_UPDATE_ENUM.index = 3
QUEUEENTERPARAM_QUEUE_ENTER_UPDATE_ENUM.number = 4
QUEUEENTERPARAM.name = "QueueEnterParam"
QUEUEENTERPARAM.full_name = ".Cmd.QueueEnterParam"
QUEUEENTERPARAM.values = {
  QUEUEENTERPARAM_QUEUE_ENTER_NOTIFY_ENUM,
  QUEUEENTERPARAM_QUEUE_ENTER_REQ_ENUM,
  QUEUEENTERPARAM_QUEUE_ENTER_RESULT_ENUM,
  QUEUEENTERPARAM_QUEUE_ENTER_UPDATE_ENUM
}
EQUEUEENTERTYPE_EQUEUEENTERTYPE_MIN_ENUM.name = "EQUEUEENTERTYPE_MIN"
EQUEUEENTERTYPE_EQUEUEENTERTYPE_MIN_ENUM.index = 0
EQUEUEENTERTYPE_EQUEUEENTERTYPE_MIN_ENUM.number = 0
EQUEUEENTERTYPE_EQUEUEENTERTYPE_GVG_ATT_ENUM.name = "EQUEUEENTERTYPE_GVG_ATT"
EQUEUEENTERTYPE_EQUEUEENTERTYPE_GVG_ATT_ENUM.index = 1
EQUEUEENTERTYPE_EQUEUEENTERTYPE_GVG_ATT_ENUM.number = 1
EQUEUEENTERTYPE_EQUEUEENTERTYPE_GVG_DEF_ENUM.name = "EQUEUEENTERTYPE_GVG_DEF"
EQUEUEENTERTYPE_EQUEUEENTERTYPE_GVG_DEF_ENUM.index = 2
EQUEUEENTERTYPE_EQUEUEENTERTYPE_GVG_DEF_ENUM.number = 2
EQUEUEENTERTYPE.name = "EQueueEnterType"
EQUEUEENTERTYPE.full_name = ".Cmd.EQueueEnterType"
EQUEUEENTERTYPE.values = {
  EQUEUEENTERTYPE_EQUEUEENTERTYPE_MIN_ENUM,
  EQUEUEENTERTYPE_EQUEUEENTERTYPE_GVG_ATT_ENUM,
  EQUEUEENTERTYPE_EQUEUEENTERTYPE_GVG_DEF_ENUM
}
QUEUEENTERRETCMD_CMD_FIELD.name = "cmd"
QUEUEENTERRETCMD_CMD_FIELD.full_name = ".Cmd.QueueEnterRetCmd.cmd"
QUEUEENTERRETCMD_CMD_FIELD.number = 1
QUEUEENTERRETCMD_CMD_FIELD.index = 0
QUEUEENTERRETCMD_CMD_FIELD.label = 1
QUEUEENTERRETCMD_CMD_FIELD.has_default_value = true
QUEUEENTERRETCMD_CMD_FIELD.default_value = 78
QUEUEENTERRETCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
QUEUEENTERRETCMD_CMD_FIELD.type = 14
QUEUEENTERRETCMD_CMD_FIELD.cpp_type = 8
QUEUEENTERRETCMD_PARAM_FIELD.name = "param"
QUEUEENTERRETCMD_PARAM_FIELD.full_name = ".Cmd.QueueEnterRetCmd.param"
QUEUEENTERRETCMD_PARAM_FIELD.number = 2
QUEUEENTERRETCMD_PARAM_FIELD.index = 1
QUEUEENTERRETCMD_PARAM_FIELD.label = 1
QUEUEENTERRETCMD_PARAM_FIELD.has_default_value = true
QUEUEENTERRETCMD_PARAM_FIELD.default_value = 3
QUEUEENTERRETCMD_PARAM_FIELD.enum_type = QUEUEENTERPARAM
QUEUEENTERRETCMD_PARAM_FIELD.type = 14
QUEUEENTERRETCMD_PARAM_FIELD.cpp_type = 8
QUEUEENTERRETCMD_STOP_FIELD.name = "stop"
QUEUEENTERRETCMD_STOP_FIELD.full_name = ".Cmd.QueueEnterRetCmd.stop"
QUEUEENTERRETCMD_STOP_FIELD.number = 3
QUEUEENTERRETCMD_STOP_FIELD.index = 2
QUEUEENTERRETCMD_STOP_FIELD.label = 1
QUEUEENTERRETCMD_STOP_FIELD.has_default_value = false
QUEUEENTERRETCMD_STOP_FIELD.default_value = false
QUEUEENTERRETCMD_STOP_FIELD.type = 8
QUEUEENTERRETCMD_STOP_FIELD.cpp_type = 7
QUEUEENTERRETCMD_WAITNUM_FIELD.name = "waitnum"
QUEUEENTERRETCMD_WAITNUM_FIELD.full_name = ".Cmd.QueueEnterRetCmd.waitnum"
QUEUEENTERRETCMD_WAITNUM_FIELD.number = 4
QUEUEENTERRETCMD_WAITNUM_FIELD.index = 3
QUEUEENTERRETCMD_WAITNUM_FIELD.label = 1
QUEUEENTERRETCMD_WAITNUM_FIELD.has_default_value = false
QUEUEENTERRETCMD_WAITNUM_FIELD.default_value = 0
QUEUEENTERRETCMD_WAITNUM_FIELD.type = 13
QUEUEENTERRETCMD_WAITNUM_FIELD.cpp_type = 3
QUEUEENTERRETCMD_ETYPE_FIELD.name = "etype"
QUEUEENTERRETCMD_ETYPE_FIELD.full_name = ".Cmd.QueueEnterRetCmd.etype"
QUEUEENTERRETCMD_ETYPE_FIELD.number = 5
QUEUEENTERRETCMD_ETYPE_FIELD.index = 4
QUEUEENTERRETCMD_ETYPE_FIELD.label = 1
QUEUEENTERRETCMD_ETYPE_FIELD.has_default_value = false
QUEUEENTERRETCMD_ETYPE_FIELD.default_value = nil
QUEUEENTERRETCMD_ETYPE_FIELD.enum_type = EQUEUEENTERTYPE
QUEUEENTERRETCMD_ETYPE_FIELD.type = 14
QUEUEENTERRETCMD_ETYPE_FIELD.cpp_type = 8
QUEUEENTERRETCMD.name = "QueueEnterRetCmd"
QUEUEENTERRETCMD.full_name = ".Cmd.QueueEnterRetCmd"
QUEUEENTERRETCMD.nested_types = {}
QUEUEENTERRETCMD.enum_types = {}
QUEUEENTERRETCMD.fields = {
  QUEUEENTERRETCMD_CMD_FIELD,
  QUEUEENTERRETCMD_PARAM_FIELD,
  QUEUEENTERRETCMD_STOP_FIELD,
  QUEUEENTERRETCMD_WAITNUM_FIELD,
  QUEUEENTERRETCMD_ETYPE_FIELD
}
QUEUEENTERRETCMD.is_extendable = false
QUEUEENTERRETCMD.extensions = {}
QUEUEUPDATECOUNTCMD_CMD_FIELD.name = "cmd"
QUEUEUPDATECOUNTCMD_CMD_FIELD.full_name = ".Cmd.QueueUpdateCountCmd.cmd"
QUEUEUPDATECOUNTCMD_CMD_FIELD.number = 1
QUEUEUPDATECOUNTCMD_CMD_FIELD.index = 0
QUEUEUPDATECOUNTCMD_CMD_FIELD.label = 1
QUEUEUPDATECOUNTCMD_CMD_FIELD.has_default_value = true
QUEUEUPDATECOUNTCMD_CMD_FIELD.default_value = 78
QUEUEUPDATECOUNTCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
QUEUEUPDATECOUNTCMD_CMD_FIELD.type = 14
QUEUEUPDATECOUNTCMD_CMD_FIELD.cpp_type = 8
QUEUEUPDATECOUNTCMD_PARAM_FIELD.name = "param"
QUEUEUPDATECOUNTCMD_PARAM_FIELD.full_name = ".Cmd.QueueUpdateCountCmd.param"
QUEUEUPDATECOUNTCMD_PARAM_FIELD.number = 2
QUEUEUPDATECOUNTCMD_PARAM_FIELD.index = 1
QUEUEUPDATECOUNTCMD_PARAM_FIELD.label = 1
QUEUEUPDATECOUNTCMD_PARAM_FIELD.has_default_value = true
QUEUEUPDATECOUNTCMD_PARAM_FIELD.default_value = 4
QUEUEUPDATECOUNTCMD_PARAM_FIELD.enum_type = QUEUEENTERPARAM
QUEUEUPDATECOUNTCMD_PARAM_FIELD.type = 14
QUEUEUPDATECOUNTCMD_PARAM_FIELD.cpp_type = 8
QUEUEUPDATECOUNTCMD_DEC_NUM_FIELD.name = "dec_num"
QUEUEUPDATECOUNTCMD_DEC_NUM_FIELD.full_name = ".Cmd.QueueUpdateCountCmd.dec_num"
QUEUEUPDATECOUNTCMD_DEC_NUM_FIELD.number = 3
QUEUEUPDATECOUNTCMD_DEC_NUM_FIELD.index = 2
QUEUEUPDATECOUNTCMD_DEC_NUM_FIELD.label = 1
QUEUEUPDATECOUNTCMD_DEC_NUM_FIELD.has_default_value = false
QUEUEUPDATECOUNTCMD_DEC_NUM_FIELD.default_value = 0
QUEUEUPDATECOUNTCMD_DEC_NUM_FIELD.type = 13
QUEUEUPDATECOUNTCMD_DEC_NUM_FIELD.cpp_type = 3
QUEUEUPDATECOUNTCMD_ETYPE_FIELD.name = "etype"
QUEUEUPDATECOUNTCMD_ETYPE_FIELD.full_name = ".Cmd.QueueUpdateCountCmd.etype"
QUEUEUPDATECOUNTCMD_ETYPE_FIELD.number = 4
QUEUEUPDATECOUNTCMD_ETYPE_FIELD.index = 3
QUEUEUPDATECOUNTCMD_ETYPE_FIELD.label = 1
QUEUEUPDATECOUNTCMD_ETYPE_FIELD.has_default_value = false
QUEUEUPDATECOUNTCMD_ETYPE_FIELD.default_value = nil
QUEUEUPDATECOUNTCMD_ETYPE_FIELD.enum_type = EQUEUEENTERTYPE
QUEUEUPDATECOUNTCMD_ETYPE_FIELD.type = 14
QUEUEUPDATECOUNTCMD_ETYPE_FIELD.cpp_type = 8
QUEUEUPDATECOUNTCMD.name = "QueueUpdateCountCmd"
QUEUEUPDATECOUNTCMD.full_name = ".Cmd.QueueUpdateCountCmd"
QUEUEUPDATECOUNTCMD.nested_types = {}
QUEUEUPDATECOUNTCMD.enum_types = {}
QUEUEUPDATECOUNTCMD.fields = {
  QUEUEUPDATECOUNTCMD_CMD_FIELD,
  QUEUEUPDATECOUNTCMD_PARAM_FIELD,
  QUEUEUPDATECOUNTCMD_DEC_NUM_FIELD,
  QUEUEUPDATECOUNTCMD_ETYPE_FIELD
}
QUEUEUPDATECOUNTCMD.is_extendable = false
QUEUEUPDATECOUNTCMD.extensions = {}
REQUIREQUEUENOTIFYCMD_CMD_FIELD.name = "cmd"
REQUIREQUEUENOTIFYCMD_CMD_FIELD.full_name = ".Cmd.RequireQueueNotifyCmd.cmd"
REQUIREQUEUENOTIFYCMD_CMD_FIELD.number = 1
REQUIREQUEUENOTIFYCMD_CMD_FIELD.index = 0
REQUIREQUEUENOTIFYCMD_CMD_FIELD.label = 1
REQUIREQUEUENOTIFYCMD_CMD_FIELD.has_default_value = true
REQUIREQUEUENOTIFYCMD_CMD_FIELD.default_value = 78
REQUIREQUEUENOTIFYCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
REQUIREQUEUENOTIFYCMD_CMD_FIELD.type = 14
REQUIREQUEUENOTIFYCMD_CMD_FIELD.cpp_type = 8
REQUIREQUEUENOTIFYCMD_PARAM_FIELD.name = "param"
REQUIREQUEUENOTIFYCMD_PARAM_FIELD.full_name = ".Cmd.RequireQueueNotifyCmd.param"
REQUIREQUEUENOTIFYCMD_PARAM_FIELD.number = 2
REQUIREQUEUENOTIFYCMD_PARAM_FIELD.index = 1
REQUIREQUEUENOTIFYCMD_PARAM_FIELD.label = 1
REQUIREQUEUENOTIFYCMD_PARAM_FIELD.has_default_value = true
REQUIREQUEUENOTIFYCMD_PARAM_FIELD.default_value = 1
REQUIREQUEUENOTIFYCMD_PARAM_FIELD.enum_type = QUEUEENTERPARAM
REQUIREQUEUENOTIFYCMD_PARAM_FIELD.type = 14
REQUIREQUEUENOTIFYCMD_PARAM_FIELD.cpp_type = 8
REQUIREQUEUENOTIFYCMD_ETYPE_FIELD.name = "etype"
REQUIREQUEUENOTIFYCMD_ETYPE_FIELD.full_name = ".Cmd.RequireQueueNotifyCmd.etype"
REQUIREQUEUENOTIFYCMD_ETYPE_FIELD.number = 3
REQUIREQUEUENOTIFYCMD_ETYPE_FIELD.index = 2
REQUIREQUEUENOTIFYCMD_ETYPE_FIELD.label = 1
REQUIREQUEUENOTIFYCMD_ETYPE_FIELD.has_default_value = false
REQUIREQUEUENOTIFYCMD_ETYPE_FIELD.default_value = nil
REQUIREQUEUENOTIFYCMD_ETYPE_FIELD.enum_type = EQUEUEENTERTYPE
REQUIREQUEUENOTIFYCMD_ETYPE_FIELD.type = 14
REQUIREQUEUENOTIFYCMD_ETYPE_FIELD.cpp_type = 8
REQUIREQUEUENOTIFYCMD.name = "RequireQueueNotifyCmd"
REQUIREQUEUENOTIFYCMD.full_name = ".Cmd.RequireQueueNotifyCmd"
REQUIREQUEUENOTIFYCMD.nested_types = {}
REQUIREQUEUENOTIFYCMD.enum_types = {}
REQUIREQUEUENOTIFYCMD.fields = {
  REQUIREQUEUENOTIFYCMD_CMD_FIELD,
  REQUIREQUEUENOTIFYCMD_PARAM_FIELD,
  REQUIREQUEUENOTIFYCMD_ETYPE_FIELD
}
REQUIREQUEUENOTIFYCMD.is_extendable = false
REQUIREQUEUENOTIFYCMD.extensions = {}
REQQUEUEENTERCMD_CMD_FIELD.name = "cmd"
REQQUEUEENTERCMD_CMD_FIELD.full_name = ".Cmd.ReqQueueEnterCmd.cmd"
REQQUEUEENTERCMD_CMD_FIELD.number = 1
REQQUEUEENTERCMD_CMD_FIELD.index = 0
REQQUEUEENTERCMD_CMD_FIELD.label = 1
REQQUEUEENTERCMD_CMD_FIELD.has_default_value = true
REQQUEUEENTERCMD_CMD_FIELD.default_value = 78
REQQUEUEENTERCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
REQQUEUEENTERCMD_CMD_FIELD.type = 14
REQQUEUEENTERCMD_CMD_FIELD.cpp_type = 8
REQQUEUEENTERCMD_PARAM_FIELD.name = "param"
REQQUEUEENTERCMD_PARAM_FIELD.full_name = ".Cmd.ReqQueueEnterCmd.param"
REQQUEUEENTERCMD_PARAM_FIELD.number = 2
REQQUEUEENTERCMD_PARAM_FIELD.index = 1
REQQUEUEENTERCMD_PARAM_FIELD.label = 1
REQQUEUEENTERCMD_PARAM_FIELD.has_default_value = true
REQQUEUEENTERCMD_PARAM_FIELD.default_value = 2
REQQUEUEENTERCMD_PARAM_FIELD.enum_type = QUEUEENTERPARAM
REQQUEUEENTERCMD_PARAM_FIELD.type = 14
REQQUEUEENTERCMD_PARAM_FIELD.cpp_type = 8
REQQUEUEENTERCMD_STOP_FIELD.name = "stop"
REQQUEUEENTERCMD_STOP_FIELD.full_name = ".Cmd.ReqQueueEnterCmd.stop"
REQQUEUEENTERCMD_STOP_FIELD.number = 3
REQQUEUEENTERCMD_STOP_FIELD.index = 2
REQQUEUEENTERCMD_STOP_FIELD.label = 1
REQQUEUEENTERCMD_STOP_FIELD.has_default_value = false
REQQUEUEENTERCMD_STOP_FIELD.default_value = false
REQQUEUEENTERCMD_STOP_FIELD.type = 8
REQQUEUEENTERCMD_STOP_FIELD.cpp_type = 7
REQQUEUEENTERCMD_ETYPE_FIELD.name = "etype"
REQQUEUEENTERCMD_ETYPE_FIELD.full_name = ".Cmd.ReqQueueEnterCmd.etype"
REQQUEUEENTERCMD_ETYPE_FIELD.number = 4
REQQUEUEENTERCMD_ETYPE_FIELD.index = 3
REQQUEUEENTERCMD_ETYPE_FIELD.label = 1
REQQUEUEENTERCMD_ETYPE_FIELD.has_default_value = false
REQQUEUEENTERCMD_ETYPE_FIELD.default_value = nil
REQQUEUEENTERCMD_ETYPE_FIELD.enum_type = EQUEUEENTERTYPE
REQQUEUEENTERCMD_ETYPE_FIELD.type = 14
REQQUEUEENTERCMD_ETYPE_FIELD.cpp_type = 8
REQQUEUEENTERCMD.name = "ReqQueueEnterCmd"
REQQUEUEENTERCMD.full_name = ".Cmd.ReqQueueEnterCmd"
REQQUEUEENTERCMD.nested_types = {}
REQQUEUEENTERCMD.enum_types = {}
REQQUEUEENTERCMD.fields = {
  REQQUEUEENTERCMD_CMD_FIELD,
  REQQUEUEENTERCMD_PARAM_FIELD,
  REQQUEUEENTERCMD_STOP_FIELD,
  REQQUEUEENTERCMD_ETYPE_FIELD
}
REQQUEUEENTERCMD.is_extendable = false
REQQUEUEENTERCMD.extensions = {}
EQUEUEENTERTYPE_GVG_ATT = 1
EQUEUEENTERTYPE_GVG_DEF = 2
EQUEUEENTERTYPE_MIN = 0
QUEUE_ENTER_NOTIFY = 1
QUEUE_ENTER_REQ = 2
QUEUE_ENTER_RESULT = 3
QUEUE_ENTER_UPDATE = 4
QueueEnterRetCmd = protobuf.Message(QUEUEENTERRETCMD)
QueueUpdateCountCmd = protobuf.Message(QUEUEUPDATECOUNTCMD)
ReqQueueEnterCmd = protobuf.Message(REQQUEUEENTERCMD)
RequireQueueNotifyCmd = protobuf.Message(REQUIREQUEUENOTIFYCMD)
