local protobuf = protobuf
autoImport("xCmd_pb")
local xCmd_pb = xCmd_pb
autoImport("ProtoCommon_pb")
local ProtoCommon_pb = ProtoCommon_pb
module("SceneManor_pb")
MANORPARAM = protobuf.EnumDescriptor()
MANORPARAM_MANORPARAM_BUILD_DATA_NTF_ENUM = protobuf.EnumValueDescriptor()
MANORPARAM_MANORPARAM_BUILD_QUERY_ENUM = protobuf.EnumValueDescriptor()
MANORPARAM_MANORPARAM_BUILD_LEVELUP_ENUM = protobuf.EnumValueDescriptor()
MANORPARAM_MANORPARAM_BUILD_DISPATCH_ENUM = protobuf.EnumValueDescriptor()
MANORPARAM_MANORPARAM_BUILD_LOTTERY_ENUM = protobuf.EnumValueDescriptor()
MANORPARAM_MANORPARAM_BUILD_COLLECT_ENUM = protobuf.EnumValueDescriptor()
MANORPARAM_MANORPARAM_ENTER_RAID_ENUM = protobuf.EnumValueDescriptor()
MANORPARAM_MANORPARAM_PARTNER_INFO_ENUM = protobuf.EnumValueDescriptor()
MANORPARAM_MANORPARAM_PARTNER_STORY_ENUM = protobuf.EnumValueDescriptor()
MANORPARAM_MANORPARAM_PARTNER_IDLE_LIST_ENUM = protobuf.EnumValueDescriptor()
MANORPARAM_MANORPARAM_PARTNER_IDLE_UPDATE_ENUM = protobuf.EnumValueDescriptor()
MANORPARAM_MANORPARAM_PARTNER_GIVE_ENUM = protobuf.EnumValueDescriptor()
MANORPARAM_MANORPARAM_BUILD_FORGE_ENUM = protobuf.EnumValueDescriptor()
MANORPARAM_MANORPARAM_SMITH_INFO_ENUM = protobuf.EnumValueDescriptor()
MANORPARAM_MANORPARAM_SMITH_LEVELUP_ENUM = protobuf.EnumValueDescriptor()
MANORPARAM_MANORPARAM_SMITH_ACCEPT_QUEST_ENUM = protobuf.EnumValueDescriptor()
EMANORFUNCTYPE = protobuf.EnumDescriptor()
EMANORFUNCTYPE_EMANORFUNCTYPE_MIN_ENUM = protobuf.EnumValueDescriptor()
EMANORFUNCTYPE_EMANORFUNCTYPE_PET_COUNT_ENUM = protobuf.EnumValueDescriptor()
EMANORFUNCTYPE_EMANORFUNCTYPE_PET_EQUIP_ENUM = protobuf.EnumValueDescriptor()
EMANORFUNCTYPE_EMANORFUNCTYPE_MAP_ATTR_ENUM = protobuf.EnumValueDescriptor()
EMANORFUNCTYPE_EMANORFUNCTYPE_OPEN_AREA_ENUM = protobuf.EnumValueDescriptor()
EMANORFUNCTYPE_EMANORFUNCTYPE_ADVENTURE_TIMES_ENUM = protobuf.EnumValueDescriptor()
EMANORFUNCTYPE_EMANORFUNCTYPE_MAP_DROP_ENUM = protobuf.EnumValueDescriptor()
EMANORFUNCTYPE_EMANORFUNCTYPE_ADVENTURE_INCOME_ENUM = protobuf.EnumValueDescriptor()
EMANORFUNCTYPE_EMANORFUNCTYPE_OPEN_GOODS_ENUM = protobuf.EnumValueDescriptor()
EMANORFUNCTYPE_EMANORFUNCTYPE_ADD_GOODS_ENUM = protobuf.EnumValueDescriptor()
EMANORFUNCTYPE_EMANORFUNCTYPE_STONE_CAPACITY_ENUM = protobuf.EnumValueDescriptor()
EMANORFUNCTYPE_EMANORFUNCTYPE_STONE_PRODUCE_ENUM = protobuf.EnumValueDescriptor()
EMANORFUNCTYPE_EMANORFUNCTYPE_WOOD_CAPACITY_ENUM = protobuf.EnumValueDescriptor()
EMANORFUNCTYPE_EMANORFUNCTYPE_WOOD_PRODUCE_ENUM = protobuf.EnumValueDescriptor()
EMANORFUNCTYPE_EMANORFUNCTYPE_REDUCE_FORGE_INTERVAL_ENUM = protobuf.EnumValueDescriptor()
EMANORFUNCTYPE_EMANORFUNCTYPE_OPEN_FORGE_PART_ENUM = protobuf.EnumValueDescriptor()
EMANORFUNCTYPE_EMANORFUNCTYPE_FORGE_PRODUCE_ENUM = protobuf.EnumValueDescriptor()
ESMITHQUESTSTATE = protobuf.EnumDescriptor()
ESMITHQUESTSTATE_ESMITH_QUEST_MIN_ENUM = protobuf.EnumValueDescriptor()
ESMITHQUESTSTATE_ESMITH_QUEST_ACCEPTED_ENUM = protobuf.EnumValueDescriptor()
ESMITHQUESTSTATE_ESMITH_QUEST_HELPED_ENUM = protobuf.EnumValueDescriptor()
ESMITHQUESTSTATE_ESMITH_QUEST_DONE_ENUM = protobuf.EnumValueDescriptor()
MANORBUILDFUNCDATA = protobuf.Descriptor()
MANORBUILDFUNCDATA_FUNC_TYPE_FIELD = protobuf.FieldDescriptor()
MANORBUILDFUNCDATA_FUNC_LEVEL_FIELD = protobuf.FieldDescriptor()
MANORDISPATCHGROUP = protobuf.Descriptor()
MANORDISPATCHGROUP_AREA_ID_FIELD = protobuf.FieldDescriptor()
MANORDISPATCHGROUP_PET_ID_FIELD = protobuf.FieldDescriptor()
MANORDISPATCHGROUP_EQUIP_ID_FIELD = protobuf.FieldDescriptor()
MANORDISPATCHGROUP_BEGIN_TIME_FIELD = protobuf.FieldDescriptor()
MANORDISPATCHREWARD = protobuf.Descriptor()
MANORDISPATCHREWARD_REWARD_ID_FIELD = protobuf.FieldDescriptor()
MANORDISPATCHREWARD_REWARD_COUNT_FIELD = protobuf.FieldDescriptor()
MANORDISPATCHREWARD_DISPATCH_COUNT_FIELD = protobuf.FieldDescriptor()
MANORDISPATCHDATA = protobuf.Descriptor()
MANORDISPATCHDATA_GROUPS_FIELD = protobuf.FieldDescriptor()
MANORDISPATCHDATA_REWARDS_FIELD = protobuf.FieldDescriptor()
MANORLOTTERYDATA = protobuf.Descriptor()
MANORLOTTERYDATA_IDS_FIELD = protobuf.FieldDescriptor()
MANORRESOURSEDATA = protobuf.Descriptor()
MANORRESOURSEDATA_RESERVE_FIELD = protobuf.FieldDescriptor()
MANORRESOURSEDATA_BEGIN_TIME_FIELD = protobuf.FieldDescriptor()
MANORFORGEDATA = protobuf.Descriptor()
MANORFORGEDATA_PART_FIELD = protobuf.FieldDescriptor()
MANORFORGEDATA_BEGIN_TIME_FIELD = protobuf.FieldDescriptor()
MANORFORGEDATA_NOTICE_FIELD = protobuf.FieldDescriptor()
MANORBUILDDATA = protobuf.Descriptor()
MANORBUILDDATA_BUILD_ID_FIELD = protobuf.FieldDescriptor()
MANORBUILDDATA_OPEN_TIME_FIELD = protobuf.FieldDescriptor()
MANORBUILDDATA_FUNCS_FIELD = protobuf.FieldDescriptor()
MANORBUILDDATA_DISPATCH_FIELD = protobuf.FieldDescriptor()
MANORBUILDDATA_LOTTERY_FIELD = protobuf.FieldDescriptor()
MANORBUILDDATA_RESOURCE_FIELD = protobuf.FieldDescriptor()
MANORBUILDDATA_ISFORBID_FIELD = protobuf.FieldDescriptor()
MANORBUILDDATA_FORGES_FIELD = protobuf.FieldDescriptor()
MANORBUILDDATA_ACHIEVE_HOUR_FIELD = protobuf.FieldDescriptor()
BUILDDATANTFMANORCMD = protobuf.Descriptor()
BUILDDATANTFMANORCMD_CMD_FIELD = protobuf.FieldDescriptor()
BUILDDATANTFMANORCMD_PARAM_FIELD = protobuf.FieldDescriptor()
BUILDDATANTFMANORCMD_BUILDS_FIELD = protobuf.FieldDescriptor()
MANORSTORYDATA = protobuf.Descriptor()
MANORSTORYDATA_ID_FIELD = protobuf.FieldDescriptor()
MANORSTORYDATA_READ_FIELD = protobuf.FieldDescriptor()
MANORPARTNERDATA = protobuf.Descriptor()
MANORPARTNERDATA_ID_FIELD = protobuf.FieldDescriptor()
MANORPARTNERDATA_FAVOR_FIELD = protobuf.FieldDescriptor()
MANORPARTNERDATA_MAXFAVOR_FIELD = protobuf.FieldDescriptor()
MANORPARTNERDATA_COMPOSES_FIELD = protobuf.FieldDescriptor()
MANORPARTNERDATA_STORIES_FIELD = protobuf.FieldDescriptor()
MANORPARTNERDATA_HIDE_FIELD = protobuf.FieldDescriptor()
MANORPARTNERDATA_ADDTIME_FIELD = protobuf.FieldDescriptor()
BUILDQUERYMANORCMD = protobuf.Descriptor()
BUILDQUERYMANORCMD_CMD_FIELD = protobuf.FieldDescriptor()
BUILDQUERYMANORCMD_PARAM_FIELD = protobuf.FieldDescriptor()
BUILDQUERYMANORCMD_BUILD_FIELD = protobuf.FieldDescriptor()
BUILDLEVELUPMANORCMD = protobuf.Descriptor()
BUILDLEVELUPMANORCMD_CMD_FIELD = protobuf.FieldDescriptor()
BUILDLEVELUPMANORCMD_PARAM_FIELD = protobuf.FieldDescriptor()
BUILDLEVELUPMANORCMD_TYPE_FIELD = protobuf.FieldDescriptor()
BUILDLEVELUPMANORCMD_BUILD_FIELD = protobuf.FieldDescriptor()
BUILDDISPATCHMANORCMD = protobuf.Descriptor()
BUILDDISPATCHMANORCMD_CMD_FIELD = protobuf.FieldDescriptor()
BUILDDISPATCHMANORCMD_PARAM_FIELD = protobuf.FieldDescriptor()
BUILDDISPATCHMANORCMD_PET_ID_FIELD = protobuf.FieldDescriptor()
BUILDDISPATCHMANORCMD_AREA_ID_FIELD = protobuf.FieldDescriptor()
BUILDDISPATCHMANORCMD_EQUIP_ID_FIELD = protobuf.FieldDescriptor()
BUILDDISPATCHMANORCMD_ISREWARD_FIELD = protobuf.FieldDescriptor()
BUILDDISPATCHMANORCMD_BUILD_FIELD = protobuf.FieldDescriptor()
BUILDLOTTERYMANORCMD = protobuf.Descriptor()
BUILDLOTTERYMANORCMD_CMD_FIELD = protobuf.FieldDescriptor()
BUILDLOTTERYMANORCMD_PARAM_FIELD = protobuf.FieldDescriptor()
BUILDLOTTERYMANORCMD_BUILD_FIELD = protobuf.FieldDescriptor()
BUILDCOLLECTMANORCMD = protobuf.Descriptor()
BUILDCOLLECTMANORCMD_CMD_FIELD = protobuf.FieldDescriptor()
BUILDCOLLECTMANORCMD_PARAM_FIELD = protobuf.FieldDescriptor()
BUILDCOLLECTMANORCMD_BUILD_FIELD = protobuf.FieldDescriptor()
REQENTERRAIDMANORCMD = protobuf.Descriptor()
REQENTERRAIDMANORCMD_CMD_FIELD = protobuf.FieldDescriptor()
REQENTERRAIDMANORCMD_PARAM_FIELD = protobuf.FieldDescriptor()
REQENTERRAIDMANORCMD_NPCGUID_FIELD = protobuf.FieldDescriptor()
PARTNERINFOMANORCMD = protobuf.Descriptor()
PARTNERINFOMANORCMD_CMD_FIELD = protobuf.FieldDescriptor()
PARTNERINFOMANORCMD_PARAM_FIELD = protobuf.FieldDescriptor()
PARTNERINFOMANORCMD_PARTNERINFOS_FIELD = protobuf.FieldDescriptor()
PARTNERSTROYMANORCMD = protobuf.Descriptor()
PARTNERSTROYMANORCMD_CMD_FIELD = protobuf.FieldDescriptor()
PARTNERSTROYMANORCMD_PARAM_FIELD = protobuf.FieldDescriptor()
PARTNERSTROYMANORCMD_PARTNERID_FIELD = protobuf.FieldDescriptor()
PARTNERSTROYMANORCMD_STORYID_FIELD = protobuf.FieldDescriptor()
PARTNERQUESTDATA = protobuf.Descriptor()
PARTNERQUESTDATA_QUESTID_FIELD = protobuf.FieldDescriptor()
PARTNERQUESTDATA_PARTNERS_FIELD = protobuf.FieldDescriptor()
PARTNERQUESTDATA_INPROCESS_FIELD = protobuf.FieldDescriptor()
PARTNERQUESTDATA_IGNORENUM_FIELD = protobuf.FieldDescriptor()
ADDPARTNERDATA = protobuf.Descriptor()
ADDPARTNERDATA_PARTNERID_FIELD = protobuf.FieldDescriptor()
ADDPARTNERDATA_POS_FIELD = protobuf.FieldDescriptor()
PARTNERIDLELISTMANORCMD = protobuf.Descriptor()
PARTNERIDLELISTMANORCMD_CMD_FIELD = protobuf.FieldDescriptor()
PARTNERIDLELISTMANORCMD_PARAM_FIELD = protobuf.FieldDescriptor()
PARTNERIDLELISTMANORCMD_PARTNERS_FIELD = protobuf.FieldDescriptor()
PARTNERIDLEUPDATEMANORCMD = protobuf.Descriptor()
PARTNERIDLEUPDATEMANORCMD_CMD_FIELD = protobuf.FieldDescriptor()
PARTNERIDLEUPDATEMANORCMD_PARAM_FIELD = protobuf.FieldDescriptor()
PARTNERIDLEUPDATEMANORCMD_ADDS_FIELD = protobuf.FieldDescriptor()
PARTNERIDLEUPDATEMANORCMD_DELID_FIELD = protobuf.FieldDescriptor()
PARTNERGIVEMANORCMD = protobuf.Descriptor()
PARTNERGIVEMANORCMD_CMD_FIELD = protobuf.FieldDescriptor()
PARTNERGIVEMANORCMD_PARAM_FIELD = protobuf.FieldDescriptor()
PARTNERGIVEMANORCMD_PARTNERID_FIELD = protobuf.FieldDescriptor()
PARTNERGIVEMANORCMD_ITEMID_FIELD = protobuf.FieldDescriptor()
PARTNERGIVEMANORCMD_ITEMNUM_FIELD = protobuf.FieldDescriptor()
BUILDFORGEMANORCMD = protobuf.Descriptor()
BUILDFORGEMANORCMD_CMD_FIELD = protobuf.FieldDescriptor()
BUILDFORGEMANORCMD_PARAM_FIELD = protobuf.FieldDescriptor()
BUILDFORGEMANORCMD_PART_FIELD = protobuf.FieldDescriptor()
BUILDFORGEMANORCMD_ISREWARD_FIELD = protobuf.FieldDescriptor()
BUILDFORGEMANORCMD_BUILD_FIELD = protobuf.FieldDescriptor()
SMITHQUESTDATA = protobuf.Descriptor()
SMITHQUESTDATA_QUESTID_FIELD = protobuf.FieldDescriptor()
SMITHQUESTDATA_QUEST_STATE_FIELD = protobuf.FieldDescriptor()
SMITHQUESTDATA_HAS_FINISHED_FIELD = protobuf.FieldDescriptor()
SMITHQUESTDATA_HELP_FINISH_TIME_FIELD = protobuf.FieldDescriptor()
SMITHQUESTDATA_HELP_PARTNER_FIELD = protobuf.FieldDescriptor()
SMITHINFOMANORCMD = protobuf.Descriptor()
SMITHINFOMANORCMD_CMD_FIELD = protobuf.FieldDescriptor()
SMITHINFOMANORCMD_PARAM_FIELD = protobuf.FieldDescriptor()
SMITHINFOMANORCMD_QUESTS_FIELD = protobuf.FieldDescriptor()
SMITHINFOMANORCMD_ALL_PARTNERS_FIELD = protobuf.FieldDescriptor()
SMITHINFOMANORCMD_LEVEL_FIELD = protobuf.FieldDescriptor()
SMITHINFOMANORCMD_REWARD_LEVEL_FIELD = protobuf.FieldDescriptor()
SMITHLEVELUPMANORCMD = protobuf.Descriptor()
SMITHLEVELUPMANORCMD_CMD_FIELD = protobuf.FieldDescriptor()
SMITHLEVELUPMANORCMD_PARAM_FIELD = protobuf.FieldDescriptor()
SMITHACCEPTQUESTMANORCMD = protobuf.Descriptor()
SMITHACCEPTQUESTMANORCMD_CMD_FIELD = protobuf.FieldDescriptor()
SMITHACCEPTQUESTMANORCMD_PARAM_FIELD = protobuf.FieldDescriptor()
SMITHACCEPTQUESTMANORCMD_QUESTID_FIELD = protobuf.FieldDescriptor()
SMITHACCEPTQUESTMANORCMD_HELP_NPCID_FIELD = protobuf.FieldDescriptor()
MANORPARAM_MANORPARAM_BUILD_DATA_NTF_ENUM.name = "MANORPARAM_BUILD_DATA_NTF"
MANORPARAM_MANORPARAM_BUILD_DATA_NTF_ENUM.index = 0
MANORPARAM_MANORPARAM_BUILD_DATA_NTF_ENUM.number = 1
MANORPARAM_MANORPARAM_BUILD_QUERY_ENUM.name = "MANORPARAM_BUILD_QUERY"
MANORPARAM_MANORPARAM_BUILD_QUERY_ENUM.index = 1
MANORPARAM_MANORPARAM_BUILD_QUERY_ENUM.number = 2
MANORPARAM_MANORPARAM_BUILD_LEVELUP_ENUM.name = "MANORPARAM_BUILD_LEVELUP"
MANORPARAM_MANORPARAM_BUILD_LEVELUP_ENUM.index = 2
MANORPARAM_MANORPARAM_BUILD_LEVELUP_ENUM.number = 3
MANORPARAM_MANORPARAM_BUILD_DISPATCH_ENUM.name = "MANORPARAM_BUILD_DISPATCH"
MANORPARAM_MANORPARAM_BUILD_DISPATCH_ENUM.index = 3
MANORPARAM_MANORPARAM_BUILD_DISPATCH_ENUM.number = 4
MANORPARAM_MANORPARAM_BUILD_LOTTERY_ENUM.name = "MANORPARAM_BUILD_LOTTERY"
MANORPARAM_MANORPARAM_BUILD_LOTTERY_ENUM.index = 4
MANORPARAM_MANORPARAM_BUILD_LOTTERY_ENUM.number = 5
MANORPARAM_MANORPARAM_BUILD_COLLECT_ENUM.name = "MANORPARAM_BUILD_COLLECT"
MANORPARAM_MANORPARAM_BUILD_COLLECT_ENUM.index = 5
MANORPARAM_MANORPARAM_BUILD_COLLECT_ENUM.number = 6
MANORPARAM_MANORPARAM_ENTER_RAID_ENUM.name = "MANORPARAM_ENTER_RAID"
MANORPARAM_MANORPARAM_ENTER_RAID_ENUM.index = 6
MANORPARAM_MANORPARAM_ENTER_RAID_ENUM.number = 7
MANORPARAM_MANORPARAM_PARTNER_INFO_ENUM.name = "MANORPARAM_PARTNER_INFO"
MANORPARAM_MANORPARAM_PARTNER_INFO_ENUM.index = 7
MANORPARAM_MANORPARAM_PARTNER_INFO_ENUM.number = 8
MANORPARAM_MANORPARAM_PARTNER_STORY_ENUM.name = "MANORPARAM_PARTNER_STORY"
MANORPARAM_MANORPARAM_PARTNER_STORY_ENUM.index = 8
MANORPARAM_MANORPARAM_PARTNER_STORY_ENUM.number = 9
MANORPARAM_MANORPARAM_PARTNER_IDLE_LIST_ENUM.name = "MANORPARAM_PARTNER_IDLE_LIST"
MANORPARAM_MANORPARAM_PARTNER_IDLE_LIST_ENUM.index = 9
MANORPARAM_MANORPARAM_PARTNER_IDLE_LIST_ENUM.number = 10
MANORPARAM_MANORPARAM_PARTNER_IDLE_UPDATE_ENUM.name = "MANORPARAM_PARTNER_IDLE_UPDATE"
MANORPARAM_MANORPARAM_PARTNER_IDLE_UPDATE_ENUM.index = 10
MANORPARAM_MANORPARAM_PARTNER_IDLE_UPDATE_ENUM.number = 11
MANORPARAM_MANORPARAM_PARTNER_GIVE_ENUM.name = "MANORPARAM_PARTNER_GIVE"
MANORPARAM_MANORPARAM_PARTNER_GIVE_ENUM.index = 11
MANORPARAM_MANORPARAM_PARTNER_GIVE_ENUM.number = 12
MANORPARAM_MANORPARAM_BUILD_FORGE_ENUM.name = "MANORPARAM_BUILD_FORGE"
MANORPARAM_MANORPARAM_BUILD_FORGE_ENUM.index = 12
MANORPARAM_MANORPARAM_BUILD_FORGE_ENUM.number = 13
MANORPARAM_MANORPARAM_SMITH_INFO_ENUM.name = "MANORPARAM_SMITH_INFO"
MANORPARAM_MANORPARAM_SMITH_INFO_ENUM.index = 13
MANORPARAM_MANORPARAM_SMITH_INFO_ENUM.number = 14
MANORPARAM_MANORPARAM_SMITH_LEVELUP_ENUM.name = "MANORPARAM_SMITH_LEVELUP"
MANORPARAM_MANORPARAM_SMITH_LEVELUP_ENUM.index = 14
MANORPARAM_MANORPARAM_SMITH_LEVELUP_ENUM.number = 15
MANORPARAM_MANORPARAM_SMITH_ACCEPT_QUEST_ENUM.name = "MANORPARAM_SMITH_ACCEPT_QUEST"
MANORPARAM_MANORPARAM_SMITH_ACCEPT_QUEST_ENUM.index = 15
MANORPARAM_MANORPARAM_SMITH_ACCEPT_QUEST_ENUM.number = 16
MANORPARAM.name = "ManorParam"
MANORPARAM.full_name = ".Cmd.ManorParam"
MANORPARAM.values = {
  MANORPARAM_MANORPARAM_BUILD_DATA_NTF_ENUM,
  MANORPARAM_MANORPARAM_BUILD_QUERY_ENUM,
  MANORPARAM_MANORPARAM_BUILD_LEVELUP_ENUM,
  MANORPARAM_MANORPARAM_BUILD_DISPATCH_ENUM,
  MANORPARAM_MANORPARAM_BUILD_LOTTERY_ENUM,
  MANORPARAM_MANORPARAM_BUILD_COLLECT_ENUM,
  MANORPARAM_MANORPARAM_ENTER_RAID_ENUM,
  MANORPARAM_MANORPARAM_PARTNER_INFO_ENUM,
  MANORPARAM_MANORPARAM_PARTNER_STORY_ENUM,
  MANORPARAM_MANORPARAM_PARTNER_IDLE_LIST_ENUM,
  MANORPARAM_MANORPARAM_PARTNER_IDLE_UPDATE_ENUM,
  MANORPARAM_MANORPARAM_PARTNER_GIVE_ENUM,
  MANORPARAM_MANORPARAM_BUILD_FORGE_ENUM,
  MANORPARAM_MANORPARAM_SMITH_INFO_ENUM,
  MANORPARAM_MANORPARAM_SMITH_LEVELUP_ENUM,
  MANORPARAM_MANORPARAM_SMITH_ACCEPT_QUEST_ENUM
}
EMANORFUNCTYPE_EMANORFUNCTYPE_MIN_ENUM.name = "EMANORFUNCTYPE_MIN"
EMANORFUNCTYPE_EMANORFUNCTYPE_MIN_ENUM.index = 0
EMANORFUNCTYPE_EMANORFUNCTYPE_MIN_ENUM.number = 0
EMANORFUNCTYPE_EMANORFUNCTYPE_PET_COUNT_ENUM.name = "EMANORFUNCTYPE_PET_COUNT"
EMANORFUNCTYPE_EMANORFUNCTYPE_PET_COUNT_ENUM.index = 1
EMANORFUNCTYPE_EMANORFUNCTYPE_PET_COUNT_ENUM.number = 1
EMANORFUNCTYPE_EMANORFUNCTYPE_PET_EQUIP_ENUM.name = "EMANORFUNCTYPE_PET_EQUIP"
EMANORFUNCTYPE_EMANORFUNCTYPE_PET_EQUIP_ENUM.index = 2
EMANORFUNCTYPE_EMANORFUNCTYPE_PET_EQUIP_ENUM.number = 2
EMANORFUNCTYPE_EMANORFUNCTYPE_MAP_ATTR_ENUM.name = "EMANORFUNCTYPE_MAP_ATTR"
EMANORFUNCTYPE_EMANORFUNCTYPE_MAP_ATTR_ENUM.index = 3
EMANORFUNCTYPE_EMANORFUNCTYPE_MAP_ATTR_ENUM.number = 3
EMANORFUNCTYPE_EMANORFUNCTYPE_OPEN_AREA_ENUM.name = "EMANORFUNCTYPE_OPEN_AREA"
EMANORFUNCTYPE_EMANORFUNCTYPE_OPEN_AREA_ENUM.index = 4
EMANORFUNCTYPE_EMANORFUNCTYPE_OPEN_AREA_ENUM.number = 4
EMANORFUNCTYPE_EMANORFUNCTYPE_ADVENTURE_TIMES_ENUM.name = "EMANORFUNCTYPE_ADVENTURE_TIMES"
EMANORFUNCTYPE_EMANORFUNCTYPE_ADVENTURE_TIMES_ENUM.index = 5
EMANORFUNCTYPE_EMANORFUNCTYPE_ADVENTURE_TIMES_ENUM.number = 5
EMANORFUNCTYPE_EMANORFUNCTYPE_MAP_DROP_ENUM.name = "EMANORFUNCTYPE_MAP_DROP"
EMANORFUNCTYPE_EMANORFUNCTYPE_MAP_DROP_ENUM.index = 6
EMANORFUNCTYPE_EMANORFUNCTYPE_MAP_DROP_ENUM.number = 6
EMANORFUNCTYPE_EMANORFUNCTYPE_ADVENTURE_INCOME_ENUM.name = "EMANORFUNCTYPE_ADVENTURE_INCOME"
EMANORFUNCTYPE_EMANORFUNCTYPE_ADVENTURE_INCOME_ENUM.index = 7
EMANORFUNCTYPE_EMANORFUNCTYPE_ADVENTURE_INCOME_ENUM.number = 7
EMANORFUNCTYPE_EMANORFUNCTYPE_OPEN_GOODS_ENUM.name = "EMANORFUNCTYPE_OPEN_GOODS"
EMANORFUNCTYPE_EMANORFUNCTYPE_OPEN_GOODS_ENUM.index = 8
EMANORFUNCTYPE_EMANORFUNCTYPE_OPEN_GOODS_ENUM.number = 8
EMANORFUNCTYPE_EMANORFUNCTYPE_ADD_GOODS_ENUM.name = "EMANORFUNCTYPE_ADD_GOODS"
EMANORFUNCTYPE_EMANORFUNCTYPE_ADD_GOODS_ENUM.index = 9
EMANORFUNCTYPE_EMANORFUNCTYPE_ADD_GOODS_ENUM.number = 9
EMANORFUNCTYPE_EMANORFUNCTYPE_STONE_CAPACITY_ENUM.name = "EMANORFUNCTYPE_STONE_CAPACITY"
EMANORFUNCTYPE_EMANORFUNCTYPE_STONE_CAPACITY_ENUM.index = 10
EMANORFUNCTYPE_EMANORFUNCTYPE_STONE_CAPACITY_ENUM.number = 10
EMANORFUNCTYPE_EMANORFUNCTYPE_STONE_PRODUCE_ENUM.name = "EMANORFUNCTYPE_STONE_PRODUCE"
EMANORFUNCTYPE_EMANORFUNCTYPE_STONE_PRODUCE_ENUM.index = 11
EMANORFUNCTYPE_EMANORFUNCTYPE_STONE_PRODUCE_ENUM.number = 11
EMANORFUNCTYPE_EMANORFUNCTYPE_WOOD_CAPACITY_ENUM.name = "EMANORFUNCTYPE_WOOD_CAPACITY"
EMANORFUNCTYPE_EMANORFUNCTYPE_WOOD_CAPACITY_ENUM.index = 12
EMANORFUNCTYPE_EMANORFUNCTYPE_WOOD_CAPACITY_ENUM.number = 12
EMANORFUNCTYPE_EMANORFUNCTYPE_WOOD_PRODUCE_ENUM.name = "EMANORFUNCTYPE_WOOD_PRODUCE"
EMANORFUNCTYPE_EMANORFUNCTYPE_WOOD_PRODUCE_ENUM.index = 13
EMANORFUNCTYPE_EMANORFUNCTYPE_WOOD_PRODUCE_ENUM.number = 13
EMANORFUNCTYPE_EMANORFUNCTYPE_REDUCE_FORGE_INTERVAL_ENUM.name = "EMANORFUNCTYPE_REDUCE_FORGE_INTERVAL"
EMANORFUNCTYPE_EMANORFUNCTYPE_REDUCE_FORGE_INTERVAL_ENUM.index = 14
EMANORFUNCTYPE_EMANORFUNCTYPE_REDUCE_FORGE_INTERVAL_ENUM.number = 14
EMANORFUNCTYPE_EMANORFUNCTYPE_OPEN_FORGE_PART_ENUM.name = "EMANORFUNCTYPE_OPEN_FORGE_PART"
EMANORFUNCTYPE_EMANORFUNCTYPE_OPEN_FORGE_PART_ENUM.index = 15
EMANORFUNCTYPE_EMANORFUNCTYPE_OPEN_FORGE_PART_ENUM.number = 15
EMANORFUNCTYPE_EMANORFUNCTYPE_FORGE_PRODUCE_ENUM.name = "EMANORFUNCTYPE_FORGE_PRODUCE"
EMANORFUNCTYPE_EMANORFUNCTYPE_FORGE_PRODUCE_ENUM.index = 16
EMANORFUNCTYPE_EMANORFUNCTYPE_FORGE_PRODUCE_ENUM.number = 16
EMANORFUNCTYPE.name = "EManorFuncType"
EMANORFUNCTYPE.full_name = ".Cmd.EManorFuncType"
EMANORFUNCTYPE.values = {
  EMANORFUNCTYPE_EMANORFUNCTYPE_MIN_ENUM,
  EMANORFUNCTYPE_EMANORFUNCTYPE_PET_COUNT_ENUM,
  EMANORFUNCTYPE_EMANORFUNCTYPE_PET_EQUIP_ENUM,
  EMANORFUNCTYPE_EMANORFUNCTYPE_MAP_ATTR_ENUM,
  EMANORFUNCTYPE_EMANORFUNCTYPE_OPEN_AREA_ENUM,
  EMANORFUNCTYPE_EMANORFUNCTYPE_ADVENTURE_TIMES_ENUM,
  EMANORFUNCTYPE_EMANORFUNCTYPE_MAP_DROP_ENUM,
  EMANORFUNCTYPE_EMANORFUNCTYPE_ADVENTURE_INCOME_ENUM,
  EMANORFUNCTYPE_EMANORFUNCTYPE_OPEN_GOODS_ENUM,
  EMANORFUNCTYPE_EMANORFUNCTYPE_ADD_GOODS_ENUM,
  EMANORFUNCTYPE_EMANORFUNCTYPE_STONE_CAPACITY_ENUM,
  EMANORFUNCTYPE_EMANORFUNCTYPE_STONE_PRODUCE_ENUM,
  EMANORFUNCTYPE_EMANORFUNCTYPE_WOOD_CAPACITY_ENUM,
  EMANORFUNCTYPE_EMANORFUNCTYPE_WOOD_PRODUCE_ENUM,
  EMANORFUNCTYPE_EMANORFUNCTYPE_REDUCE_FORGE_INTERVAL_ENUM,
  EMANORFUNCTYPE_EMANORFUNCTYPE_OPEN_FORGE_PART_ENUM,
  EMANORFUNCTYPE_EMANORFUNCTYPE_FORGE_PRODUCE_ENUM
}
ESMITHQUESTSTATE_ESMITH_QUEST_MIN_ENUM.name = "ESMITH_QUEST_MIN"
ESMITHQUESTSTATE_ESMITH_QUEST_MIN_ENUM.index = 0
ESMITHQUESTSTATE_ESMITH_QUEST_MIN_ENUM.number = 0
ESMITHQUESTSTATE_ESMITH_QUEST_ACCEPTED_ENUM.name = "ESMITH_QUEST_ACCEPTED"
ESMITHQUESTSTATE_ESMITH_QUEST_ACCEPTED_ENUM.index = 1
ESMITHQUESTSTATE_ESMITH_QUEST_ACCEPTED_ENUM.number = 1
ESMITHQUESTSTATE_ESMITH_QUEST_HELPED_ENUM.name = "ESMITH_QUEST_HELPED"
ESMITHQUESTSTATE_ESMITH_QUEST_HELPED_ENUM.index = 2
ESMITHQUESTSTATE_ESMITH_QUEST_HELPED_ENUM.number = 2
ESMITHQUESTSTATE_ESMITH_QUEST_DONE_ENUM.name = "ESMITH_QUEST_DONE"
ESMITHQUESTSTATE_ESMITH_QUEST_DONE_ENUM.index = 3
ESMITHQUESTSTATE_ESMITH_QUEST_DONE_ENUM.number = 3
ESMITHQUESTSTATE.name = "ESmithQuestState"
ESMITHQUESTSTATE.full_name = ".Cmd.ESmithQuestState"
ESMITHQUESTSTATE.values = {
  ESMITHQUESTSTATE_ESMITH_QUEST_MIN_ENUM,
  ESMITHQUESTSTATE_ESMITH_QUEST_ACCEPTED_ENUM,
  ESMITHQUESTSTATE_ESMITH_QUEST_HELPED_ENUM,
  ESMITHQUESTSTATE_ESMITH_QUEST_DONE_ENUM
}
MANORBUILDFUNCDATA_FUNC_TYPE_FIELD.name = "func_type"
MANORBUILDFUNCDATA_FUNC_TYPE_FIELD.full_name = ".Cmd.ManorBuildFuncData.func_type"
MANORBUILDFUNCDATA_FUNC_TYPE_FIELD.number = 1
MANORBUILDFUNCDATA_FUNC_TYPE_FIELD.index = 0
MANORBUILDFUNCDATA_FUNC_TYPE_FIELD.label = 1
MANORBUILDFUNCDATA_FUNC_TYPE_FIELD.has_default_value = false
MANORBUILDFUNCDATA_FUNC_TYPE_FIELD.default_value = nil
MANORBUILDFUNCDATA_FUNC_TYPE_FIELD.enum_type = EMANORFUNCTYPE
MANORBUILDFUNCDATA_FUNC_TYPE_FIELD.type = 14
MANORBUILDFUNCDATA_FUNC_TYPE_FIELD.cpp_type = 8
MANORBUILDFUNCDATA_FUNC_LEVEL_FIELD.name = "func_level"
MANORBUILDFUNCDATA_FUNC_LEVEL_FIELD.full_name = ".Cmd.ManorBuildFuncData.func_level"
MANORBUILDFUNCDATA_FUNC_LEVEL_FIELD.number = 2
MANORBUILDFUNCDATA_FUNC_LEVEL_FIELD.index = 1
MANORBUILDFUNCDATA_FUNC_LEVEL_FIELD.label = 1
MANORBUILDFUNCDATA_FUNC_LEVEL_FIELD.has_default_value = false
MANORBUILDFUNCDATA_FUNC_LEVEL_FIELD.default_value = 0
MANORBUILDFUNCDATA_FUNC_LEVEL_FIELD.type = 13
MANORBUILDFUNCDATA_FUNC_LEVEL_FIELD.cpp_type = 3
MANORBUILDFUNCDATA.name = "ManorBuildFuncData"
MANORBUILDFUNCDATA.full_name = ".Cmd.ManorBuildFuncData"
MANORBUILDFUNCDATA.nested_types = {}
MANORBUILDFUNCDATA.enum_types = {}
MANORBUILDFUNCDATA.fields = {
  MANORBUILDFUNCDATA_FUNC_TYPE_FIELD,
  MANORBUILDFUNCDATA_FUNC_LEVEL_FIELD
}
MANORBUILDFUNCDATA.is_extendable = false
MANORBUILDFUNCDATA.extensions = {}
MANORDISPATCHGROUP_AREA_ID_FIELD.name = "area_id"
MANORDISPATCHGROUP_AREA_ID_FIELD.full_name = ".Cmd.ManorDispatchGroup.area_id"
MANORDISPATCHGROUP_AREA_ID_FIELD.number = 1
MANORDISPATCHGROUP_AREA_ID_FIELD.index = 0
MANORDISPATCHGROUP_AREA_ID_FIELD.label = 1
MANORDISPATCHGROUP_AREA_ID_FIELD.has_default_value = false
MANORDISPATCHGROUP_AREA_ID_FIELD.default_value = 0
MANORDISPATCHGROUP_AREA_ID_FIELD.type = 13
MANORDISPATCHGROUP_AREA_ID_FIELD.cpp_type = 3
MANORDISPATCHGROUP_PET_ID_FIELD.name = "pet_id"
MANORDISPATCHGROUP_PET_ID_FIELD.full_name = ".Cmd.ManorDispatchGroup.pet_id"
MANORDISPATCHGROUP_PET_ID_FIELD.number = 2
MANORDISPATCHGROUP_PET_ID_FIELD.index = 1
MANORDISPATCHGROUP_PET_ID_FIELD.label = 1
MANORDISPATCHGROUP_PET_ID_FIELD.has_default_value = false
MANORDISPATCHGROUP_PET_ID_FIELD.default_value = 0
MANORDISPATCHGROUP_PET_ID_FIELD.type = 13
MANORDISPATCHGROUP_PET_ID_FIELD.cpp_type = 3
MANORDISPATCHGROUP_EQUIP_ID_FIELD.name = "equip_id"
MANORDISPATCHGROUP_EQUIP_ID_FIELD.full_name = ".Cmd.ManorDispatchGroup.equip_id"
MANORDISPATCHGROUP_EQUIP_ID_FIELD.number = 3
MANORDISPATCHGROUP_EQUIP_ID_FIELD.index = 2
MANORDISPATCHGROUP_EQUIP_ID_FIELD.label = 1
MANORDISPATCHGROUP_EQUIP_ID_FIELD.has_default_value = false
MANORDISPATCHGROUP_EQUIP_ID_FIELD.default_value = 0
MANORDISPATCHGROUP_EQUIP_ID_FIELD.type = 13
MANORDISPATCHGROUP_EQUIP_ID_FIELD.cpp_type = 3
MANORDISPATCHGROUP_BEGIN_TIME_FIELD.name = "begin_time"
MANORDISPATCHGROUP_BEGIN_TIME_FIELD.full_name = ".Cmd.ManorDispatchGroup.begin_time"
MANORDISPATCHGROUP_BEGIN_TIME_FIELD.number = 4
MANORDISPATCHGROUP_BEGIN_TIME_FIELD.index = 3
MANORDISPATCHGROUP_BEGIN_TIME_FIELD.label = 1
MANORDISPATCHGROUP_BEGIN_TIME_FIELD.has_default_value = false
MANORDISPATCHGROUP_BEGIN_TIME_FIELD.default_value = 0
MANORDISPATCHGROUP_BEGIN_TIME_FIELD.type = 13
MANORDISPATCHGROUP_BEGIN_TIME_FIELD.cpp_type = 3
MANORDISPATCHGROUP.name = "ManorDispatchGroup"
MANORDISPATCHGROUP.full_name = ".Cmd.ManorDispatchGroup"
MANORDISPATCHGROUP.nested_types = {}
MANORDISPATCHGROUP.enum_types = {}
MANORDISPATCHGROUP.fields = {
  MANORDISPATCHGROUP_AREA_ID_FIELD,
  MANORDISPATCHGROUP_PET_ID_FIELD,
  MANORDISPATCHGROUP_EQUIP_ID_FIELD,
  MANORDISPATCHGROUP_BEGIN_TIME_FIELD
}
MANORDISPATCHGROUP.is_extendable = false
MANORDISPATCHGROUP.extensions = {}
MANORDISPATCHREWARD_REWARD_ID_FIELD.name = "reward_id"
MANORDISPATCHREWARD_REWARD_ID_FIELD.full_name = ".Cmd.ManorDispatchReward.reward_id"
MANORDISPATCHREWARD_REWARD_ID_FIELD.number = 1
MANORDISPATCHREWARD_REWARD_ID_FIELD.index = 0
MANORDISPATCHREWARD_REWARD_ID_FIELD.label = 1
MANORDISPATCHREWARD_REWARD_ID_FIELD.has_default_value = false
MANORDISPATCHREWARD_REWARD_ID_FIELD.default_value = 0
MANORDISPATCHREWARD_REWARD_ID_FIELD.type = 13
MANORDISPATCHREWARD_REWARD_ID_FIELD.cpp_type = 3
MANORDISPATCHREWARD_REWARD_COUNT_FIELD.name = "reward_count"
MANORDISPATCHREWARD_REWARD_COUNT_FIELD.full_name = ".Cmd.ManorDispatchReward.reward_count"
MANORDISPATCHREWARD_REWARD_COUNT_FIELD.number = 2
MANORDISPATCHREWARD_REWARD_COUNT_FIELD.index = 1
MANORDISPATCHREWARD_REWARD_COUNT_FIELD.label = 1
MANORDISPATCHREWARD_REWARD_COUNT_FIELD.has_default_value = false
MANORDISPATCHREWARD_REWARD_COUNT_FIELD.default_value = 0
MANORDISPATCHREWARD_REWARD_COUNT_FIELD.type = 13
MANORDISPATCHREWARD_REWARD_COUNT_FIELD.cpp_type = 3
MANORDISPATCHREWARD_DISPATCH_COUNT_FIELD.name = "dispatch_count"
MANORDISPATCHREWARD_DISPATCH_COUNT_FIELD.full_name = ".Cmd.ManorDispatchReward.dispatch_count"
MANORDISPATCHREWARD_DISPATCH_COUNT_FIELD.number = 3
MANORDISPATCHREWARD_DISPATCH_COUNT_FIELD.index = 2
MANORDISPATCHREWARD_DISPATCH_COUNT_FIELD.label = 1
MANORDISPATCHREWARD_DISPATCH_COUNT_FIELD.has_default_value = false
MANORDISPATCHREWARD_DISPATCH_COUNT_FIELD.default_value = 0
MANORDISPATCHREWARD_DISPATCH_COUNT_FIELD.type = 13
MANORDISPATCHREWARD_DISPATCH_COUNT_FIELD.cpp_type = 3
MANORDISPATCHREWARD.name = "ManorDispatchReward"
MANORDISPATCHREWARD.full_name = ".Cmd.ManorDispatchReward"
MANORDISPATCHREWARD.nested_types = {}
MANORDISPATCHREWARD.enum_types = {}
MANORDISPATCHREWARD.fields = {
  MANORDISPATCHREWARD_REWARD_ID_FIELD,
  MANORDISPATCHREWARD_REWARD_COUNT_FIELD,
  MANORDISPATCHREWARD_DISPATCH_COUNT_FIELD
}
MANORDISPATCHREWARD.is_extendable = false
MANORDISPATCHREWARD.extensions = {}
MANORDISPATCHDATA_GROUPS_FIELD.name = "groups"
MANORDISPATCHDATA_GROUPS_FIELD.full_name = ".Cmd.ManorDispatchData.groups"
MANORDISPATCHDATA_GROUPS_FIELD.number = 1
MANORDISPATCHDATA_GROUPS_FIELD.index = 0
MANORDISPATCHDATA_GROUPS_FIELD.label = 3
MANORDISPATCHDATA_GROUPS_FIELD.has_default_value = false
MANORDISPATCHDATA_GROUPS_FIELD.default_value = {}
MANORDISPATCHDATA_GROUPS_FIELD.message_type = MANORDISPATCHGROUP
MANORDISPATCHDATA_GROUPS_FIELD.type = 11
MANORDISPATCHDATA_GROUPS_FIELD.cpp_type = 10
MANORDISPATCHDATA_REWARDS_FIELD.name = "rewards"
MANORDISPATCHDATA_REWARDS_FIELD.full_name = ".Cmd.ManorDispatchData.rewards"
MANORDISPATCHDATA_REWARDS_FIELD.number = 2
MANORDISPATCHDATA_REWARDS_FIELD.index = 1
MANORDISPATCHDATA_REWARDS_FIELD.label = 3
MANORDISPATCHDATA_REWARDS_FIELD.has_default_value = false
MANORDISPATCHDATA_REWARDS_FIELD.default_value = {}
MANORDISPATCHDATA_REWARDS_FIELD.message_type = MANORDISPATCHREWARD
MANORDISPATCHDATA_REWARDS_FIELD.type = 11
MANORDISPATCHDATA_REWARDS_FIELD.cpp_type = 10
MANORDISPATCHDATA.name = "ManorDispatchData"
MANORDISPATCHDATA.full_name = ".Cmd.ManorDispatchData"
MANORDISPATCHDATA.nested_types = {}
MANORDISPATCHDATA.enum_types = {}
MANORDISPATCHDATA.fields = {
  MANORDISPATCHDATA_GROUPS_FIELD,
  MANORDISPATCHDATA_REWARDS_FIELD
}
MANORDISPATCHDATA.is_extendable = false
MANORDISPATCHDATA.extensions = {}
MANORLOTTERYDATA_IDS_FIELD.name = "ids"
MANORLOTTERYDATA_IDS_FIELD.full_name = ".Cmd.ManorLotteryData.ids"
MANORLOTTERYDATA_IDS_FIELD.number = 1
MANORLOTTERYDATA_IDS_FIELD.index = 0
MANORLOTTERYDATA_IDS_FIELD.label = 3
MANORLOTTERYDATA_IDS_FIELD.has_default_value = false
MANORLOTTERYDATA_IDS_FIELD.default_value = {}
MANORLOTTERYDATA_IDS_FIELD.type = 13
MANORLOTTERYDATA_IDS_FIELD.cpp_type = 3
MANORLOTTERYDATA.name = "ManorLotteryData"
MANORLOTTERYDATA.full_name = ".Cmd.ManorLotteryData"
MANORLOTTERYDATA.nested_types = {}
MANORLOTTERYDATA.enum_types = {}
MANORLOTTERYDATA.fields = {
  MANORLOTTERYDATA_IDS_FIELD
}
MANORLOTTERYDATA.is_extendable = false
MANORLOTTERYDATA.extensions = {}
MANORRESOURSEDATA_RESERVE_FIELD.name = "reserve"
MANORRESOURSEDATA_RESERVE_FIELD.full_name = ".Cmd.ManorResourseData.reserve"
MANORRESOURSEDATA_RESERVE_FIELD.number = 1
MANORRESOURSEDATA_RESERVE_FIELD.index = 0
MANORRESOURSEDATA_RESERVE_FIELD.label = 1
MANORRESOURSEDATA_RESERVE_FIELD.has_default_value = false
MANORRESOURSEDATA_RESERVE_FIELD.default_value = 0
MANORRESOURSEDATA_RESERVE_FIELD.type = 13
MANORRESOURSEDATA_RESERVE_FIELD.cpp_type = 3
MANORRESOURSEDATA_BEGIN_TIME_FIELD.name = "begin_time"
MANORRESOURSEDATA_BEGIN_TIME_FIELD.full_name = ".Cmd.ManorResourseData.begin_time"
MANORRESOURSEDATA_BEGIN_TIME_FIELD.number = 2
MANORRESOURSEDATA_BEGIN_TIME_FIELD.index = 1
MANORRESOURSEDATA_BEGIN_TIME_FIELD.label = 1
MANORRESOURSEDATA_BEGIN_TIME_FIELD.has_default_value = false
MANORRESOURSEDATA_BEGIN_TIME_FIELD.default_value = 0
MANORRESOURSEDATA_BEGIN_TIME_FIELD.type = 13
MANORRESOURSEDATA_BEGIN_TIME_FIELD.cpp_type = 3
MANORRESOURSEDATA.name = "ManorResourseData"
MANORRESOURSEDATA.full_name = ".Cmd.ManorResourseData"
MANORRESOURSEDATA.nested_types = {}
MANORRESOURSEDATA.enum_types = {}
MANORRESOURSEDATA.fields = {
  MANORRESOURSEDATA_RESERVE_FIELD,
  MANORRESOURSEDATA_BEGIN_TIME_FIELD
}
MANORRESOURSEDATA.is_extendable = false
MANORRESOURSEDATA.extensions = {}
MANORFORGEDATA_PART_FIELD.name = "part"
MANORFORGEDATA_PART_FIELD.full_name = ".Cmd.ManorForgeData.part"
MANORFORGEDATA_PART_FIELD.number = 1
MANORFORGEDATA_PART_FIELD.index = 0
MANORFORGEDATA_PART_FIELD.label = 1
MANORFORGEDATA_PART_FIELD.has_default_value = false
MANORFORGEDATA_PART_FIELD.default_value = 0
MANORFORGEDATA_PART_FIELD.type = 13
MANORFORGEDATA_PART_FIELD.cpp_type = 3
MANORFORGEDATA_BEGIN_TIME_FIELD.name = "begin_time"
MANORFORGEDATA_BEGIN_TIME_FIELD.full_name = ".Cmd.ManorForgeData.begin_time"
MANORFORGEDATA_BEGIN_TIME_FIELD.number = 2
MANORFORGEDATA_BEGIN_TIME_FIELD.index = 1
MANORFORGEDATA_BEGIN_TIME_FIELD.label = 1
MANORFORGEDATA_BEGIN_TIME_FIELD.has_default_value = false
MANORFORGEDATA_BEGIN_TIME_FIELD.default_value = 0
MANORFORGEDATA_BEGIN_TIME_FIELD.type = 13
MANORFORGEDATA_BEGIN_TIME_FIELD.cpp_type = 3
MANORFORGEDATA_NOTICE_FIELD.name = "notice"
MANORFORGEDATA_NOTICE_FIELD.full_name = ".Cmd.ManorForgeData.notice"
MANORFORGEDATA_NOTICE_FIELD.number = 3
MANORFORGEDATA_NOTICE_FIELD.index = 2
MANORFORGEDATA_NOTICE_FIELD.label = 1
MANORFORGEDATA_NOTICE_FIELD.has_default_value = false
MANORFORGEDATA_NOTICE_FIELD.default_value = false
MANORFORGEDATA_NOTICE_FIELD.type = 8
MANORFORGEDATA_NOTICE_FIELD.cpp_type = 7
MANORFORGEDATA.name = "ManorForgeData"
MANORFORGEDATA.full_name = ".Cmd.ManorForgeData"
MANORFORGEDATA.nested_types = {}
MANORFORGEDATA.enum_types = {}
MANORFORGEDATA.fields = {
  MANORFORGEDATA_PART_FIELD,
  MANORFORGEDATA_BEGIN_TIME_FIELD,
  MANORFORGEDATA_NOTICE_FIELD
}
MANORFORGEDATA.is_extendable = false
MANORFORGEDATA.extensions = {}
MANORBUILDDATA_BUILD_ID_FIELD.name = "build_id"
MANORBUILDDATA_BUILD_ID_FIELD.full_name = ".Cmd.ManorBuildData.build_id"
MANORBUILDDATA_BUILD_ID_FIELD.number = 1
MANORBUILDDATA_BUILD_ID_FIELD.index = 0
MANORBUILDDATA_BUILD_ID_FIELD.label = 1
MANORBUILDDATA_BUILD_ID_FIELD.has_default_value = false
MANORBUILDDATA_BUILD_ID_FIELD.default_value = 0
MANORBUILDDATA_BUILD_ID_FIELD.type = 13
MANORBUILDDATA_BUILD_ID_FIELD.cpp_type = 3
MANORBUILDDATA_OPEN_TIME_FIELD.name = "open_time"
MANORBUILDDATA_OPEN_TIME_FIELD.full_name = ".Cmd.ManorBuildData.open_time"
MANORBUILDDATA_OPEN_TIME_FIELD.number = 2
MANORBUILDDATA_OPEN_TIME_FIELD.index = 1
MANORBUILDDATA_OPEN_TIME_FIELD.label = 1
MANORBUILDDATA_OPEN_TIME_FIELD.has_default_value = false
MANORBUILDDATA_OPEN_TIME_FIELD.default_value = 0
MANORBUILDDATA_OPEN_TIME_FIELD.type = 13
MANORBUILDDATA_OPEN_TIME_FIELD.cpp_type = 3
MANORBUILDDATA_FUNCS_FIELD.name = "funcs"
MANORBUILDDATA_FUNCS_FIELD.full_name = ".Cmd.ManorBuildData.funcs"
MANORBUILDDATA_FUNCS_FIELD.number = 3
MANORBUILDDATA_FUNCS_FIELD.index = 2
MANORBUILDDATA_FUNCS_FIELD.label = 3
MANORBUILDDATA_FUNCS_FIELD.has_default_value = false
MANORBUILDDATA_FUNCS_FIELD.default_value = {}
MANORBUILDDATA_FUNCS_FIELD.message_type = MANORBUILDFUNCDATA
MANORBUILDDATA_FUNCS_FIELD.type = 11
MANORBUILDDATA_FUNCS_FIELD.cpp_type = 10
MANORBUILDDATA_DISPATCH_FIELD.name = "dispatch"
MANORBUILDDATA_DISPATCH_FIELD.full_name = ".Cmd.ManorBuildData.dispatch"
MANORBUILDDATA_DISPATCH_FIELD.number = 4
MANORBUILDDATA_DISPATCH_FIELD.index = 3
MANORBUILDDATA_DISPATCH_FIELD.label = 1
MANORBUILDDATA_DISPATCH_FIELD.has_default_value = false
MANORBUILDDATA_DISPATCH_FIELD.default_value = nil
MANORBUILDDATA_DISPATCH_FIELD.message_type = MANORDISPATCHDATA
MANORBUILDDATA_DISPATCH_FIELD.type = 11
MANORBUILDDATA_DISPATCH_FIELD.cpp_type = 10
MANORBUILDDATA_LOTTERY_FIELD.name = "lottery"
MANORBUILDDATA_LOTTERY_FIELD.full_name = ".Cmd.ManorBuildData.lottery"
MANORBUILDDATA_LOTTERY_FIELD.number = 5
MANORBUILDDATA_LOTTERY_FIELD.index = 4
MANORBUILDDATA_LOTTERY_FIELD.label = 1
MANORBUILDDATA_LOTTERY_FIELD.has_default_value = false
MANORBUILDDATA_LOTTERY_FIELD.default_value = nil
MANORBUILDDATA_LOTTERY_FIELD.message_type = MANORLOTTERYDATA
MANORBUILDDATA_LOTTERY_FIELD.type = 11
MANORBUILDDATA_LOTTERY_FIELD.cpp_type = 10
MANORBUILDDATA_RESOURCE_FIELD.name = "resource"
MANORBUILDDATA_RESOURCE_FIELD.full_name = ".Cmd.ManorBuildData.resource"
MANORBUILDDATA_RESOURCE_FIELD.number = 6
MANORBUILDDATA_RESOURCE_FIELD.index = 5
MANORBUILDDATA_RESOURCE_FIELD.label = 1
MANORBUILDDATA_RESOURCE_FIELD.has_default_value = false
MANORBUILDDATA_RESOURCE_FIELD.default_value = nil
MANORBUILDDATA_RESOURCE_FIELD.message_type = MANORRESOURSEDATA
MANORBUILDDATA_RESOURCE_FIELD.type = 11
MANORBUILDDATA_RESOURCE_FIELD.cpp_type = 10
MANORBUILDDATA_ISFORBID_FIELD.name = "isforbid"
MANORBUILDDATA_ISFORBID_FIELD.full_name = ".Cmd.ManorBuildData.isforbid"
MANORBUILDDATA_ISFORBID_FIELD.number = 7
MANORBUILDDATA_ISFORBID_FIELD.index = 6
MANORBUILDDATA_ISFORBID_FIELD.label = 1
MANORBUILDDATA_ISFORBID_FIELD.has_default_value = false
MANORBUILDDATA_ISFORBID_FIELD.default_value = false
MANORBUILDDATA_ISFORBID_FIELD.type = 8
MANORBUILDDATA_ISFORBID_FIELD.cpp_type = 7
MANORBUILDDATA_FORGES_FIELD.name = "forges"
MANORBUILDDATA_FORGES_FIELD.full_name = ".Cmd.ManorBuildData.forges"
MANORBUILDDATA_FORGES_FIELD.number = 8
MANORBUILDDATA_FORGES_FIELD.index = 7
MANORBUILDDATA_FORGES_FIELD.label = 3
MANORBUILDDATA_FORGES_FIELD.has_default_value = false
MANORBUILDDATA_FORGES_FIELD.default_value = {}
MANORBUILDDATA_FORGES_FIELD.message_type = MANORFORGEDATA
MANORBUILDDATA_FORGES_FIELD.type = 11
MANORBUILDDATA_FORGES_FIELD.cpp_type = 10
MANORBUILDDATA_ACHIEVE_HOUR_FIELD.name = "achieve_hour"
MANORBUILDDATA_ACHIEVE_HOUR_FIELD.full_name = ".Cmd.ManorBuildData.achieve_hour"
MANORBUILDDATA_ACHIEVE_HOUR_FIELD.number = 9
MANORBUILDDATA_ACHIEVE_HOUR_FIELD.index = 8
MANORBUILDDATA_ACHIEVE_HOUR_FIELD.label = 1
MANORBUILDDATA_ACHIEVE_HOUR_FIELD.has_default_value = false
MANORBUILDDATA_ACHIEVE_HOUR_FIELD.default_value = 0
MANORBUILDDATA_ACHIEVE_HOUR_FIELD.type = 13
MANORBUILDDATA_ACHIEVE_HOUR_FIELD.cpp_type = 3
MANORBUILDDATA.name = "ManorBuildData"
MANORBUILDDATA.full_name = ".Cmd.ManorBuildData"
MANORBUILDDATA.nested_types = {}
MANORBUILDDATA.enum_types = {}
MANORBUILDDATA.fields = {
  MANORBUILDDATA_BUILD_ID_FIELD,
  MANORBUILDDATA_OPEN_TIME_FIELD,
  MANORBUILDDATA_FUNCS_FIELD,
  MANORBUILDDATA_DISPATCH_FIELD,
  MANORBUILDDATA_LOTTERY_FIELD,
  MANORBUILDDATA_RESOURCE_FIELD,
  MANORBUILDDATA_ISFORBID_FIELD,
  MANORBUILDDATA_FORGES_FIELD,
  MANORBUILDDATA_ACHIEVE_HOUR_FIELD
}
MANORBUILDDATA.is_extendable = false
MANORBUILDDATA.extensions = {}
BUILDDATANTFMANORCMD_CMD_FIELD.name = "cmd"
BUILDDATANTFMANORCMD_CMD_FIELD.full_name = ".Cmd.BuildDataNtfManorCmd.cmd"
BUILDDATANTFMANORCMD_CMD_FIELD.number = 1
BUILDDATANTFMANORCMD_CMD_FIELD.index = 0
BUILDDATANTFMANORCMD_CMD_FIELD.label = 1
BUILDDATANTFMANORCMD_CMD_FIELD.has_default_value = true
BUILDDATANTFMANORCMD_CMD_FIELD.default_value = 233
BUILDDATANTFMANORCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
BUILDDATANTFMANORCMD_CMD_FIELD.type = 14
BUILDDATANTFMANORCMD_CMD_FIELD.cpp_type = 8
BUILDDATANTFMANORCMD_PARAM_FIELD.name = "param"
BUILDDATANTFMANORCMD_PARAM_FIELD.full_name = ".Cmd.BuildDataNtfManorCmd.param"
BUILDDATANTFMANORCMD_PARAM_FIELD.number = 2
BUILDDATANTFMANORCMD_PARAM_FIELD.index = 1
BUILDDATANTFMANORCMD_PARAM_FIELD.label = 1
BUILDDATANTFMANORCMD_PARAM_FIELD.has_default_value = true
BUILDDATANTFMANORCMD_PARAM_FIELD.default_value = 1
BUILDDATANTFMANORCMD_PARAM_FIELD.enum_type = MANORPARAM
BUILDDATANTFMANORCMD_PARAM_FIELD.type = 14
BUILDDATANTFMANORCMD_PARAM_FIELD.cpp_type = 8
BUILDDATANTFMANORCMD_BUILDS_FIELD.name = "builds"
BUILDDATANTFMANORCMD_BUILDS_FIELD.full_name = ".Cmd.BuildDataNtfManorCmd.builds"
BUILDDATANTFMANORCMD_BUILDS_FIELD.number = 3
BUILDDATANTFMANORCMD_BUILDS_FIELD.index = 2
BUILDDATANTFMANORCMD_BUILDS_FIELD.label = 3
BUILDDATANTFMANORCMD_BUILDS_FIELD.has_default_value = false
BUILDDATANTFMANORCMD_BUILDS_FIELD.default_value = {}
BUILDDATANTFMANORCMD_BUILDS_FIELD.message_type = MANORBUILDDATA
BUILDDATANTFMANORCMD_BUILDS_FIELD.type = 11
BUILDDATANTFMANORCMD_BUILDS_FIELD.cpp_type = 10
BUILDDATANTFMANORCMD.name = "BuildDataNtfManorCmd"
BUILDDATANTFMANORCMD.full_name = ".Cmd.BuildDataNtfManorCmd"
BUILDDATANTFMANORCMD.nested_types = {}
BUILDDATANTFMANORCMD.enum_types = {}
BUILDDATANTFMANORCMD.fields = {
  BUILDDATANTFMANORCMD_CMD_FIELD,
  BUILDDATANTFMANORCMD_PARAM_FIELD,
  BUILDDATANTFMANORCMD_BUILDS_FIELD
}
BUILDDATANTFMANORCMD.is_extendable = false
BUILDDATANTFMANORCMD.extensions = {}
MANORSTORYDATA_ID_FIELD.name = "id"
MANORSTORYDATA_ID_FIELD.full_name = ".Cmd.ManorStoryData.id"
MANORSTORYDATA_ID_FIELD.number = 1
MANORSTORYDATA_ID_FIELD.index = 0
MANORSTORYDATA_ID_FIELD.label = 1
MANORSTORYDATA_ID_FIELD.has_default_value = false
MANORSTORYDATA_ID_FIELD.default_value = 0
MANORSTORYDATA_ID_FIELD.type = 13
MANORSTORYDATA_ID_FIELD.cpp_type = 3
MANORSTORYDATA_READ_FIELD.name = "read"
MANORSTORYDATA_READ_FIELD.full_name = ".Cmd.ManorStoryData.read"
MANORSTORYDATA_READ_FIELD.number = 2
MANORSTORYDATA_READ_FIELD.index = 1
MANORSTORYDATA_READ_FIELD.label = 1
MANORSTORYDATA_READ_FIELD.has_default_value = false
MANORSTORYDATA_READ_FIELD.default_value = false
MANORSTORYDATA_READ_FIELD.type = 8
MANORSTORYDATA_READ_FIELD.cpp_type = 7
MANORSTORYDATA.name = "ManorStoryData"
MANORSTORYDATA.full_name = ".Cmd.ManorStoryData"
MANORSTORYDATA.nested_types = {}
MANORSTORYDATA.enum_types = {}
MANORSTORYDATA.fields = {
  MANORSTORYDATA_ID_FIELD,
  MANORSTORYDATA_READ_FIELD
}
MANORSTORYDATA.is_extendable = false
MANORSTORYDATA.extensions = {}
MANORPARTNERDATA_ID_FIELD.name = "id"
MANORPARTNERDATA_ID_FIELD.full_name = ".Cmd.ManorPartnerData.id"
MANORPARTNERDATA_ID_FIELD.number = 1
MANORPARTNERDATA_ID_FIELD.index = 0
MANORPARTNERDATA_ID_FIELD.label = 1
MANORPARTNERDATA_ID_FIELD.has_default_value = false
MANORPARTNERDATA_ID_FIELD.default_value = 0
MANORPARTNERDATA_ID_FIELD.type = 13
MANORPARTNERDATA_ID_FIELD.cpp_type = 3
MANORPARTNERDATA_FAVOR_FIELD.name = "favor"
MANORPARTNERDATA_FAVOR_FIELD.full_name = ".Cmd.ManorPartnerData.favor"
MANORPARTNERDATA_FAVOR_FIELD.number = 2
MANORPARTNERDATA_FAVOR_FIELD.index = 1
MANORPARTNERDATA_FAVOR_FIELD.label = 1
MANORPARTNERDATA_FAVOR_FIELD.has_default_value = false
MANORPARTNERDATA_FAVOR_FIELD.default_value = 0
MANORPARTNERDATA_FAVOR_FIELD.type = 13
MANORPARTNERDATA_FAVOR_FIELD.cpp_type = 3
MANORPARTNERDATA_MAXFAVOR_FIELD.name = "maxfavor"
MANORPARTNERDATA_MAXFAVOR_FIELD.full_name = ".Cmd.ManorPartnerData.maxfavor"
MANORPARTNERDATA_MAXFAVOR_FIELD.number = 3
MANORPARTNERDATA_MAXFAVOR_FIELD.index = 2
MANORPARTNERDATA_MAXFAVOR_FIELD.label = 1
MANORPARTNERDATA_MAXFAVOR_FIELD.has_default_value = false
MANORPARTNERDATA_MAXFAVOR_FIELD.default_value = 0
MANORPARTNERDATA_MAXFAVOR_FIELD.type = 13
MANORPARTNERDATA_MAXFAVOR_FIELD.cpp_type = 3
MANORPARTNERDATA_COMPOSES_FIELD.name = "composes"
MANORPARTNERDATA_COMPOSES_FIELD.full_name = ".Cmd.ManorPartnerData.composes"
MANORPARTNERDATA_COMPOSES_FIELD.number = 4
MANORPARTNERDATA_COMPOSES_FIELD.index = 3
MANORPARTNERDATA_COMPOSES_FIELD.label = 3
MANORPARTNERDATA_COMPOSES_FIELD.has_default_value = false
MANORPARTNERDATA_COMPOSES_FIELD.default_value = {}
MANORPARTNERDATA_COMPOSES_FIELD.type = 13
MANORPARTNERDATA_COMPOSES_FIELD.cpp_type = 3
MANORPARTNERDATA_STORIES_FIELD.name = "stories"
MANORPARTNERDATA_STORIES_FIELD.full_name = ".Cmd.ManorPartnerData.stories"
MANORPARTNERDATA_STORIES_FIELD.number = 5
MANORPARTNERDATA_STORIES_FIELD.index = 4
MANORPARTNERDATA_STORIES_FIELD.label = 3
MANORPARTNERDATA_STORIES_FIELD.has_default_value = false
MANORPARTNERDATA_STORIES_FIELD.default_value = {}
MANORPARTNERDATA_STORIES_FIELD.message_type = MANORSTORYDATA
MANORPARTNERDATA_STORIES_FIELD.type = 11
MANORPARTNERDATA_STORIES_FIELD.cpp_type = 10
MANORPARTNERDATA_HIDE_FIELD.name = "hide"
MANORPARTNERDATA_HIDE_FIELD.full_name = ".Cmd.ManorPartnerData.hide"
MANORPARTNERDATA_HIDE_FIELD.number = 6
MANORPARTNERDATA_HIDE_FIELD.index = 5
MANORPARTNERDATA_HIDE_FIELD.label = 1
MANORPARTNERDATA_HIDE_FIELD.has_default_value = false
MANORPARTNERDATA_HIDE_FIELD.default_value = false
MANORPARTNERDATA_HIDE_FIELD.type = 8
MANORPARTNERDATA_HIDE_FIELD.cpp_type = 7
MANORPARTNERDATA_ADDTIME_FIELD.name = "addtime"
MANORPARTNERDATA_ADDTIME_FIELD.full_name = ".Cmd.ManorPartnerData.addtime"
MANORPARTNERDATA_ADDTIME_FIELD.number = 7
MANORPARTNERDATA_ADDTIME_FIELD.index = 6
MANORPARTNERDATA_ADDTIME_FIELD.label = 1
MANORPARTNERDATA_ADDTIME_FIELD.has_default_value = false
MANORPARTNERDATA_ADDTIME_FIELD.default_value = 0
MANORPARTNERDATA_ADDTIME_FIELD.type = 13
MANORPARTNERDATA_ADDTIME_FIELD.cpp_type = 3
MANORPARTNERDATA.name = "ManorPartnerData"
MANORPARTNERDATA.full_name = ".Cmd.ManorPartnerData"
MANORPARTNERDATA.nested_types = {}
MANORPARTNERDATA.enum_types = {}
MANORPARTNERDATA.fields = {
  MANORPARTNERDATA_ID_FIELD,
  MANORPARTNERDATA_FAVOR_FIELD,
  MANORPARTNERDATA_MAXFAVOR_FIELD,
  MANORPARTNERDATA_COMPOSES_FIELD,
  MANORPARTNERDATA_STORIES_FIELD,
  MANORPARTNERDATA_HIDE_FIELD,
  MANORPARTNERDATA_ADDTIME_FIELD
}
MANORPARTNERDATA.is_extendable = false
MANORPARTNERDATA.extensions = {}
BUILDQUERYMANORCMD_CMD_FIELD.name = "cmd"
BUILDQUERYMANORCMD_CMD_FIELD.full_name = ".Cmd.BuildQueryManorCmd.cmd"
BUILDQUERYMANORCMD_CMD_FIELD.number = 1
BUILDQUERYMANORCMD_CMD_FIELD.index = 0
BUILDQUERYMANORCMD_CMD_FIELD.label = 1
BUILDQUERYMANORCMD_CMD_FIELD.has_default_value = true
BUILDQUERYMANORCMD_CMD_FIELD.default_value = 233
BUILDQUERYMANORCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
BUILDQUERYMANORCMD_CMD_FIELD.type = 14
BUILDQUERYMANORCMD_CMD_FIELD.cpp_type = 8
BUILDQUERYMANORCMD_PARAM_FIELD.name = "param"
BUILDQUERYMANORCMD_PARAM_FIELD.full_name = ".Cmd.BuildQueryManorCmd.param"
BUILDQUERYMANORCMD_PARAM_FIELD.number = 2
BUILDQUERYMANORCMD_PARAM_FIELD.index = 1
BUILDQUERYMANORCMD_PARAM_FIELD.label = 1
BUILDQUERYMANORCMD_PARAM_FIELD.has_default_value = true
BUILDQUERYMANORCMD_PARAM_FIELD.default_value = 2
BUILDQUERYMANORCMD_PARAM_FIELD.enum_type = MANORPARAM
BUILDQUERYMANORCMD_PARAM_FIELD.type = 14
BUILDQUERYMANORCMD_PARAM_FIELD.cpp_type = 8
BUILDQUERYMANORCMD_BUILD_FIELD.name = "build"
BUILDQUERYMANORCMD_BUILD_FIELD.full_name = ".Cmd.BuildQueryManorCmd.build"
BUILDQUERYMANORCMD_BUILD_FIELD.number = 3
BUILDQUERYMANORCMD_BUILD_FIELD.index = 2
BUILDQUERYMANORCMD_BUILD_FIELD.label = 1
BUILDQUERYMANORCMD_BUILD_FIELD.has_default_value = false
BUILDQUERYMANORCMD_BUILD_FIELD.default_value = nil
BUILDQUERYMANORCMD_BUILD_FIELD.message_type = MANORBUILDDATA
BUILDQUERYMANORCMD_BUILD_FIELD.type = 11
BUILDQUERYMANORCMD_BUILD_FIELD.cpp_type = 10
BUILDQUERYMANORCMD.name = "BuildQueryManorCmd"
BUILDQUERYMANORCMD.full_name = ".Cmd.BuildQueryManorCmd"
BUILDQUERYMANORCMD.nested_types = {}
BUILDQUERYMANORCMD.enum_types = {}
BUILDQUERYMANORCMD.fields = {
  BUILDQUERYMANORCMD_CMD_FIELD,
  BUILDQUERYMANORCMD_PARAM_FIELD,
  BUILDQUERYMANORCMD_BUILD_FIELD
}
BUILDQUERYMANORCMD.is_extendable = false
BUILDQUERYMANORCMD.extensions = {}
BUILDLEVELUPMANORCMD_CMD_FIELD.name = "cmd"
BUILDLEVELUPMANORCMD_CMD_FIELD.full_name = ".Cmd.BuildLevelUpManorCmd.cmd"
BUILDLEVELUPMANORCMD_CMD_FIELD.number = 1
BUILDLEVELUPMANORCMD_CMD_FIELD.index = 0
BUILDLEVELUPMANORCMD_CMD_FIELD.label = 1
BUILDLEVELUPMANORCMD_CMD_FIELD.has_default_value = true
BUILDLEVELUPMANORCMD_CMD_FIELD.default_value = 233
BUILDLEVELUPMANORCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
BUILDLEVELUPMANORCMD_CMD_FIELD.type = 14
BUILDLEVELUPMANORCMD_CMD_FIELD.cpp_type = 8
BUILDLEVELUPMANORCMD_PARAM_FIELD.name = "param"
BUILDLEVELUPMANORCMD_PARAM_FIELD.full_name = ".Cmd.BuildLevelUpManorCmd.param"
BUILDLEVELUPMANORCMD_PARAM_FIELD.number = 2
BUILDLEVELUPMANORCMD_PARAM_FIELD.index = 1
BUILDLEVELUPMANORCMD_PARAM_FIELD.label = 1
BUILDLEVELUPMANORCMD_PARAM_FIELD.has_default_value = true
BUILDLEVELUPMANORCMD_PARAM_FIELD.default_value = 3
BUILDLEVELUPMANORCMD_PARAM_FIELD.enum_type = MANORPARAM
BUILDLEVELUPMANORCMD_PARAM_FIELD.type = 14
BUILDLEVELUPMANORCMD_PARAM_FIELD.cpp_type = 8
BUILDLEVELUPMANORCMD_TYPE_FIELD.name = "type"
BUILDLEVELUPMANORCMD_TYPE_FIELD.full_name = ".Cmd.BuildLevelUpManorCmd.type"
BUILDLEVELUPMANORCMD_TYPE_FIELD.number = 3
BUILDLEVELUPMANORCMD_TYPE_FIELD.index = 2
BUILDLEVELUPMANORCMD_TYPE_FIELD.label = 1
BUILDLEVELUPMANORCMD_TYPE_FIELD.has_default_value = false
BUILDLEVELUPMANORCMD_TYPE_FIELD.default_value = nil
BUILDLEVELUPMANORCMD_TYPE_FIELD.enum_type = EMANORFUNCTYPE
BUILDLEVELUPMANORCMD_TYPE_FIELD.type = 14
BUILDLEVELUPMANORCMD_TYPE_FIELD.cpp_type = 8
BUILDLEVELUPMANORCMD_BUILD_FIELD.name = "build"
BUILDLEVELUPMANORCMD_BUILD_FIELD.full_name = ".Cmd.BuildLevelUpManorCmd.build"
BUILDLEVELUPMANORCMD_BUILD_FIELD.number = 4
BUILDLEVELUPMANORCMD_BUILD_FIELD.index = 3
BUILDLEVELUPMANORCMD_BUILD_FIELD.label = 1
BUILDLEVELUPMANORCMD_BUILD_FIELD.has_default_value = false
BUILDLEVELUPMANORCMD_BUILD_FIELD.default_value = nil
BUILDLEVELUPMANORCMD_BUILD_FIELD.message_type = MANORBUILDDATA
BUILDLEVELUPMANORCMD_BUILD_FIELD.type = 11
BUILDLEVELUPMANORCMD_BUILD_FIELD.cpp_type = 10
BUILDLEVELUPMANORCMD.name = "BuildLevelUpManorCmd"
BUILDLEVELUPMANORCMD.full_name = ".Cmd.BuildLevelUpManorCmd"
BUILDLEVELUPMANORCMD.nested_types = {}
BUILDLEVELUPMANORCMD.enum_types = {}
BUILDLEVELUPMANORCMD.fields = {
  BUILDLEVELUPMANORCMD_CMD_FIELD,
  BUILDLEVELUPMANORCMD_PARAM_FIELD,
  BUILDLEVELUPMANORCMD_TYPE_FIELD,
  BUILDLEVELUPMANORCMD_BUILD_FIELD
}
BUILDLEVELUPMANORCMD.is_extendable = false
BUILDLEVELUPMANORCMD.extensions = {}
BUILDDISPATCHMANORCMD_CMD_FIELD.name = "cmd"
BUILDDISPATCHMANORCMD_CMD_FIELD.full_name = ".Cmd.BuildDispatchManorCmd.cmd"
BUILDDISPATCHMANORCMD_CMD_FIELD.number = 1
BUILDDISPATCHMANORCMD_CMD_FIELD.index = 0
BUILDDISPATCHMANORCMD_CMD_FIELD.label = 1
BUILDDISPATCHMANORCMD_CMD_FIELD.has_default_value = true
BUILDDISPATCHMANORCMD_CMD_FIELD.default_value = 233
BUILDDISPATCHMANORCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
BUILDDISPATCHMANORCMD_CMD_FIELD.type = 14
BUILDDISPATCHMANORCMD_CMD_FIELD.cpp_type = 8
BUILDDISPATCHMANORCMD_PARAM_FIELD.name = "param"
BUILDDISPATCHMANORCMD_PARAM_FIELD.full_name = ".Cmd.BuildDispatchManorCmd.param"
BUILDDISPATCHMANORCMD_PARAM_FIELD.number = 2
BUILDDISPATCHMANORCMD_PARAM_FIELD.index = 1
BUILDDISPATCHMANORCMD_PARAM_FIELD.label = 1
BUILDDISPATCHMANORCMD_PARAM_FIELD.has_default_value = true
BUILDDISPATCHMANORCMD_PARAM_FIELD.default_value = 4
BUILDDISPATCHMANORCMD_PARAM_FIELD.enum_type = MANORPARAM
BUILDDISPATCHMANORCMD_PARAM_FIELD.type = 14
BUILDDISPATCHMANORCMD_PARAM_FIELD.cpp_type = 8
BUILDDISPATCHMANORCMD_PET_ID_FIELD.name = "pet_id"
BUILDDISPATCHMANORCMD_PET_ID_FIELD.full_name = ".Cmd.BuildDispatchManorCmd.pet_id"
BUILDDISPATCHMANORCMD_PET_ID_FIELD.number = 3
BUILDDISPATCHMANORCMD_PET_ID_FIELD.index = 2
BUILDDISPATCHMANORCMD_PET_ID_FIELD.label = 1
BUILDDISPATCHMANORCMD_PET_ID_FIELD.has_default_value = false
BUILDDISPATCHMANORCMD_PET_ID_FIELD.default_value = 0
BUILDDISPATCHMANORCMD_PET_ID_FIELD.type = 13
BUILDDISPATCHMANORCMD_PET_ID_FIELD.cpp_type = 3
BUILDDISPATCHMANORCMD_AREA_ID_FIELD.name = "area_id"
BUILDDISPATCHMANORCMD_AREA_ID_FIELD.full_name = ".Cmd.BuildDispatchManorCmd.area_id"
BUILDDISPATCHMANORCMD_AREA_ID_FIELD.number = 4
BUILDDISPATCHMANORCMD_AREA_ID_FIELD.index = 3
BUILDDISPATCHMANORCMD_AREA_ID_FIELD.label = 1
BUILDDISPATCHMANORCMD_AREA_ID_FIELD.has_default_value = false
BUILDDISPATCHMANORCMD_AREA_ID_FIELD.default_value = 0
BUILDDISPATCHMANORCMD_AREA_ID_FIELD.type = 13
BUILDDISPATCHMANORCMD_AREA_ID_FIELD.cpp_type = 3
BUILDDISPATCHMANORCMD_EQUIP_ID_FIELD.name = "equip_id"
BUILDDISPATCHMANORCMD_EQUIP_ID_FIELD.full_name = ".Cmd.BuildDispatchManorCmd.equip_id"
BUILDDISPATCHMANORCMD_EQUIP_ID_FIELD.number = 5
BUILDDISPATCHMANORCMD_EQUIP_ID_FIELD.index = 4
BUILDDISPATCHMANORCMD_EQUIP_ID_FIELD.label = 1
BUILDDISPATCHMANORCMD_EQUIP_ID_FIELD.has_default_value = false
BUILDDISPATCHMANORCMD_EQUIP_ID_FIELD.default_value = 0
BUILDDISPATCHMANORCMD_EQUIP_ID_FIELD.type = 13
BUILDDISPATCHMANORCMD_EQUIP_ID_FIELD.cpp_type = 3
BUILDDISPATCHMANORCMD_ISREWARD_FIELD.name = "isreward"
BUILDDISPATCHMANORCMD_ISREWARD_FIELD.full_name = ".Cmd.BuildDispatchManorCmd.isreward"
BUILDDISPATCHMANORCMD_ISREWARD_FIELD.number = 6
BUILDDISPATCHMANORCMD_ISREWARD_FIELD.index = 5
BUILDDISPATCHMANORCMD_ISREWARD_FIELD.label = 1
BUILDDISPATCHMANORCMD_ISREWARD_FIELD.has_default_value = false
BUILDDISPATCHMANORCMD_ISREWARD_FIELD.default_value = false
BUILDDISPATCHMANORCMD_ISREWARD_FIELD.type = 8
BUILDDISPATCHMANORCMD_ISREWARD_FIELD.cpp_type = 7
BUILDDISPATCHMANORCMD_BUILD_FIELD.name = "build"
BUILDDISPATCHMANORCMD_BUILD_FIELD.full_name = ".Cmd.BuildDispatchManorCmd.build"
BUILDDISPATCHMANORCMD_BUILD_FIELD.number = 7
BUILDDISPATCHMANORCMD_BUILD_FIELD.index = 6
BUILDDISPATCHMANORCMD_BUILD_FIELD.label = 1
BUILDDISPATCHMANORCMD_BUILD_FIELD.has_default_value = false
BUILDDISPATCHMANORCMD_BUILD_FIELD.default_value = nil
BUILDDISPATCHMANORCMD_BUILD_FIELD.message_type = MANORBUILDDATA
BUILDDISPATCHMANORCMD_BUILD_FIELD.type = 11
BUILDDISPATCHMANORCMD_BUILD_FIELD.cpp_type = 10
BUILDDISPATCHMANORCMD.name = "BuildDispatchManorCmd"
BUILDDISPATCHMANORCMD.full_name = ".Cmd.BuildDispatchManorCmd"
BUILDDISPATCHMANORCMD.nested_types = {}
BUILDDISPATCHMANORCMD.enum_types = {}
BUILDDISPATCHMANORCMD.fields = {
  BUILDDISPATCHMANORCMD_CMD_FIELD,
  BUILDDISPATCHMANORCMD_PARAM_FIELD,
  BUILDDISPATCHMANORCMD_PET_ID_FIELD,
  BUILDDISPATCHMANORCMD_AREA_ID_FIELD,
  BUILDDISPATCHMANORCMD_EQUIP_ID_FIELD,
  BUILDDISPATCHMANORCMD_ISREWARD_FIELD,
  BUILDDISPATCHMANORCMD_BUILD_FIELD
}
BUILDDISPATCHMANORCMD.is_extendable = false
BUILDDISPATCHMANORCMD.extensions = {}
BUILDLOTTERYMANORCMD_CMD_FIELD.name = "cmd"
BUILDLOTTERYMANORCMD_CMD_FIELD.full_name = ".Cmd.BuildLotteryManorCmd.cmd"
BUILDLOTTERYMANORCMD_CMD_FIELD.number = 1
BUILDLOTTERYMANORCMD_CMD_FIELD.index = 0
BUILDLOTTERYMANORCMD_CMD_FIELD.label = 1
BUILDLOTTERYMANORCMD_CMD_FIELD.has_default_value = true
BUILDLOTTERYMANORCMD_CMD_FIELD.default_value = 233
BUILDLOTTERYMANORCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
BUILDLOTTERYMANORCMD_CMD_FIELD.type = 14
BUILDLOTTERYMANORCMD_CMD_FIELD.cpp_type = 8
BUILDLOTTERYMANORCMD_PARAM_FIELD.name = "param"
BUILDLOTTERYMANORCMD_PARAM_FIELD.full_name = ".Cmd.BuildLotteryManorCmd.param"
BUILDLOTTERYMANORCMD_PARAM_FIELD.number = 2
BUILDLOTTERYMANORCMD_PARAM_FIELD.index = 1
BUILDLOTTERYMANORCMD_PARAM_FIELD.label = 1
BUILDLOTTERYMANORCMD_PARAM_FIELD.has_default_value = true
BUILDLOTTERYMANORCMD_PARAM_FIELD.default_value = 5
BUILDLOTTERYMANORCMD_PARAM_FIELD.enum_type = MANORPARAM
BUILDLOTTERYMANORCMD_PARAM_FIELD.type = 14
BUILDLOTTERYMANORCMD_PARAM_FIELD.cpp_type = 8
BUILDLOTTERYMANORCMD_BUILD_FIELD.name = "build"
BUILDLOTTERYMANORCMD_BUILD_FIELD.full_name = ".Cmd.BuildLotteryManorCmd.build"
BUILDLOTTERYMANORCMD_BUILD_FIELD.number = 3
BUILDLOTTERYMANORCMD_BUILD_FIELD.index = 2
BUILDLOTTERYMANORCMD_BUILD_FIELD.label = 1
BUILDLOTTERYMANORCMD_BUILD_FIELD.has_default_value = false
BUILDLOTTERYMANORCMD_BUILD_FIELD.default_value = nil
BUILDLOTTERYMANORCMD_BUILD_FIELD.message_type = MANORBUILDDATA
BUILDLOTTERYMANORCMD_BUILD_FIELD.type = 11
BUILDLOTTERYMANORCMD_BUILD_FIELD.cpp_type = 10
BUILDLOTTERYMANORCMD.name = "BuildLotteryManorCmd"
BUILDLOTTERYMANORCMD.full_name = ".Cmd.BuildLotteryManorCmd"
BUILDLOTTERYMANORCMD.nested_types = {}
BUILDLOTTERYMANORCMD.enum_types = {}
BUILDLOTTERYMANORCMD.fields = {
  BUILDLOTTERYMANORCMD_CMD_FIELD,
  BUILDLOTTERYMANORCMD_PARAM_FIELD,
  BUILDLOTTERYMANORCMD_BUILD_FIELD
}
BUILDLOTTERYMANORCMD.is_extendable = false
BUILDLOTTERYMANORCMD.extensions = {}
BUILDCOLLECTMANORCMD_CMD_FIELD.name = "cmd"
BUILDCOLLECTMANORCMD_CMD_FIELD.full_name = ".Cmd.BuildCollectManorCmd.cmd"
BUILDCOLLECTMANORCMD_CMD_FIELD.number = 1
BUILDCOLLECTMANORCMD_CMD_FIELD.index = 0
BUILDCOLLECTMANORCMD_CMD_FIELD.label = 1
BUILDCOLLECTMANORCMD_CMD_FIELD.has_default_value = true
BUILDCOLLECTMANORCMD_CMD_FIELD.default_value = 233
BUILDCOLLECTMANORCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
BUILDCOLLECTMANORCMD_CMD_FIELD.type = 14
BUILDCOLLECTMANORCMD_CMD_FIELD.cpp_type = 8
BUILDCOLLECTMANORCMD_PARAM_FIELD.name = "param"
BUILDCOLLECTMANORCMD_PARAM_FIELD.full_name = ".Cmd.BuildCollectManorCmd.param"
BUILDCOLLECTMANORCMD_PARAM_FIELD.number = 2
BUILDCOLLECTMANORCMD_PARAM_FIELD.index = 1
BUILDCOLLECTMANORCMD_PARAM_FIELD.label = 1
BUILDCOLLECTMANORCMD_PARAM_FIELD.has_default_value = true
BUILDCOLLECTMANORCMD_PARAM_FIELD.default_value = 6
BUILDCOLLECTMANORCMD_PARAM_FIELD.enum_type = MANORPARAM
BUILDCOLLECTMANORCMD_PARAM_FIELD.type = 14
BUILDCOLLECTMANORCMD_PARAM_FIELD.cpp_type = 8
BUILDCOLLECTMANORCMD_BUILD_FIELD.name = "build"
BUILDCOLLECTMANORCMD_BUILD_FIELD.full_name = ".Cmd.BuildCollectManorCmd.build"
BUILDCOLLECTMANORCMD_BUILD_FIELD.number = 3
BUILDCOLLECTMANORCMD_BUILD_FIELD.index = 2
BUILDCOLLECTMANORCMD_BUILD_FIELD.label = 1
BUILDCOLLECTMANORCMD_BUILD_FIELD.has_default_value = false
BUILDCOLLECTMANORCMD_BUILD_FIELD.default_value = nil
BUILDCOLLECTMANORCMD_BUILD_FIELD.message_type = MANORBUILDDATA
BUILDCOLLECTMANORCMD_BUILD_FIELD.type = 11
BUILDCOLLECTMANORCMD_BUILD_FIELD.cpp_type = 10
BUILDCOLLECTMANORCMD.name = "BuildCollectManorCmd"
BUILDCOLLECTMANORCMD.full_name = ".Cmd.BuildCollectManorCmd"
BUILDCOLLECTMANORCMD.nested_types = {}
BUILDCOLLECTMANORCMD.enum_types = {}
BUILDCOLLECTMANORCMD.fields = {
  BUILDCOLLECTMANORCMD_CMD_FIELD,
  BUILDCOLLECTMANORCMD_PARAM_FIELD,
  BUILDCOLLECTMANORCMD_BUILD_FIELD
}
BUILDCOLLECTMANORCMD.is_extendable = false
BUILDCOLLECTMANORCMD.extensions = {}
REQENTERRAIDMANORCMD_CMD_FIELD.name = "cmd"
REQENTERRAIDMANORCMD_CMD_FIELD.full_name = ".Cmd.ReqEnterRaidManorCmd.cmd"
REQENTERRAIDMANORCMD_CMD_FIELD.number = 1
REQENTERRAIDMANORCMD_CMD_FIELD.index = 0
REQENTERRAIDMANORCMD_CMD_FIELD.label = 1
REQENTERRAIDMANORCMD_CMD_FIELD.has_default_value = true
REQENTERRAIDMANORCMD_CMD_FIELD.default_value = 233
REQENTERRAIDMANORCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
REQENTERRAIDMANORCMD_CMD_FIELD.type = 14
REQENTERRAIDMANORCMD_CMD_FIELD.cpp_type = 8
REQENTERRAIDMANORCMD_PARAM_FIELD.name = "param"
REQENTERRAIDMANORCMD_PARAM_FIELD.full_name = ".Cmd.ReqEnterRaidManorCmd.param"
REQENTERRAIDMANORCMD_PARAM_FIELD.number = 2
REQENTERRAIDMANORCMD_PARAM_FIELD.index = 1
REQENTERRAIDMANORCMD_PARAM_FIELD.label = 1
REQENTERRAIDMANORCMD_PARAM_FIELD.has_default_value = true
REQENTERRAIDMANORCMD_PARAM_FIELD.default_value = 7
REQENTERRAIDMANORCMD_PARAM_FIELD.enum_type = MANORPARAM
REQENTERRAIDMANORCMD_PARAM_FIELD.type = 14
REQENTERRAIDMANORCMD_PARAM_FIELD.cpp_type = 8
REQENTERRAIDMANORCMD_NPCGUID_FIELD.name = "npcguid"
REQENTERRAIDMANORCMD_NPCGUID_FIELD.full_name = ".Cmd.ReqEnterRaidManorCmd.npcguid"
REQENTERRAIDMANORCMD_NPCGUID_FIELD.number = 3
REQENTERRAIDMANORCMD_NPCGUID_FIELD.index = 2
REQENTERRAIDMANORCMD_NPCGUID_FIELD.label = 1
REQENTERRAIDMANORCMD_NPCGUID_FIELD.has_default_value = false
REQENTERRAIDMANORCMD_NPCGUID_FIELD.default_value = 0
REQENTERRAIDMANORCMD_NPCGUID_FIELD.type = 4
REQENTERRAIDMANORCMD_NPCGUID_FIELD.cpp_type = 4
REQENTERRAIDMANORCMD.name = "ReqEnterRaidManorCmd"
REQENTERRAIDMANORCMD.full_name = ".Cmd.ReqEnterRaidManorCmd"
REQENTERRAIDMANORCMD.nested_types = {}
REQENTERRAIDMANORCMD.enum_types = {}
REQENTERRAIDMANORCMD.fields = {
  REQENTERRAIDMANORCMD_CMD_FIELD,
  REQENTERRAIDMANORCMD_PARAM_FIELD,
  REQENTERRAIDMANORCMD_NPCGUID_FIELD
}
REQENTERRAIDMANORCMD.is_extendable = false
REQENTERRAIDMANORCMD.extensions = {}
PARTNERINFOMANORCMD_CMD_FIELD.name = "cmd"
PARTNERINFOMANORCMD_CMD_FIELD.full_name = ".Cmd.PartnerInfoManorCmd.cmd"
PARTNERINFOMANORCMD_CMD_FIELD.number = 1
PARTNERINFOMANORCMD_CMD_FIELD.index = 0
PARTNERINFOMANORCMD_CMD_FIELD.label = 1
PARTNERINFOMANORCMD_CMD_FIELD.has_default_value = true
PARTNERINFOMANORCMD_CMD_FIELD.default_value = 233
PARTNERINFOMANORCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
PARTNERINFOMANORCMD_CMD_FIELD.type = 14
PARTNERINFOMANORCMD_CMD_FIELD.cpp_type = 8
PARTNERINFOMANORCMD_PARAM_FIELD.name = "param"
PARTNERINFOMANORCMD_PARAM_FIELD.full_name = ".Cmd.PartnerInfoManorCmd.param"
PARTNERINFOMANORCMD_PARAM_FIELD.number = 2
PARTNERINFOMANORCMD_PARAM_FIELD.index = 1
PARTNERINFOMANORCMD_PARAM_FIELD.label = 1
PARTNERINFOMANORCMD_PARAM_FIELD.has_default_value = true
PARTNERINFOMANORCMD_PARAM_FIELD.default_value = 8
PARTNERINFOMANORCMD_PARAM_FIELD.enum_type = MANORPARAM
PARTNERINFOMANORCMD_PARAM_FIELD.type = 14
PARTNERINFOMANORCMD_PARAM_FIELD.cpp_type = 8
PARTNERINFOMANORCMD_PARTNERINFOS_FIELD.name = "partnerinfos"
PARTNERINFOMANORCMD_PARTNERINFOS_FIELD.full_name = ".Cmd.PartnerInfoManorCmd.partnerinfos"
PARTNERINFOMANORCMD_PARTNERINFOS_FIELD.number = 3
PARTNERINFOMANORCMD_PARTNERINFOS_FIELD.index = 2
PARTNERINFOMANORCMD_PARTNERINFOS_FIELD.label = 3
PARTNERINFOMANORCMD_PARTNERINFOS_FIELD.has_default_value = false
PARTNERINFOMANORCMD_PARTNERINFOS_FIELD.default_value = {}
PARTNERINFOMANORCMD_PARTNERINFOS_FIELD.message_type = MANORPARTNERDATA
PARTNERINFOMANORCMD_PARTNERINFOS_FIELD.type = 11
PARTNERINFOMANORCMD_PARTNERINFOS_FIELD.cpp_type = 10
PARTNERINFOMANORCMD.name = "PartnerInfoManorCmd"
PARTNERINFOMANORCMD.full_name = ".Cmd.PartnerInfoManorCmd"
PARTNERINFOMANORCMD.nested_types = {}
PARTNERINFOMANORCMD.enum_types = {}
PARTNERINFOMANORCMD.fields = {
  PARTNERINFOMANORCMD_CMD_FIELD,
  PARTNERINFOMANORCMD_PARAM_FIELD,
  PARTNERINFOMANORCMD_PARTNERINFOS_FIELD
}
PARTNERINFOMANORCMD.is_extendable = false
PARTNERINFOMANORCMD.extensions = {}
PARTNERSTROYMANORCMD_CMD_FIELD.name = "cmd"
PARTNERSTROYMANORCMD_CMD_FIELD.full_name = ".Cmd.PartnerStroyManorCmd.cmd"
PARTNERSTROYMANORCMD_CMD_FIELD.number = 1
PARTNERSTROYMANORCMD_CMD_FIELD.index = 0
PARTNERSTROYMANORCMD_CMD_FIELD.label = 1
PARTNERSTROYMANORCMD_CMD_FIELD.has_default_value = true
PARTNERSTROYMANORCMD_CMD_FIELD.default_value = 233
PARTNERSTROYMANORCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
PARTNERSTROYMANORCMD_CMD_FIELD.type = 14
PARTNERSTROYMANORCMD_CMD_FIELD.cpp_type = 8
PARTNERSTROYMANORCMD_PARAM_FIELD.name = "param"
PARTNERSTROYMANORCMD_PARAM_FIELD.full_name = ".Cmd.PartnerStroyManorCmd.param"
PARTNERSTROYMANORCMD_PARAM_FIELD.number = 2
PARTNERSTROYMANORCMD_PARAM_FIELD.index = 1
PARTNERSTROYMANORCMD_PARAM_FIELD.label = 1
PARTNERSTROYMANORCMD_PARAM_FIELD.has_default_value = true
PARTNERSTROYMANORCMD_PARAM_FIELD.default_value = 9
PARTNERSTROYMANORCMD_PARAM_FIELD.enum_type = MANORPARAM
PARTNERSTROYMANORCMD_PARAM_FIELD.type = 14
PARTNERSTROYMANORCMD_PARAM_FIELD.cpp_type = 8
PARTNERSTROYMANORCMD_PARTNERID_FIELD.name = "partnerid"
PARTNERSTROYMANORCMD_PARTNERID_FIELD.full_name = ".Cmd.PartnerStroyManorCmd.partnerid"
PARTNERSTROYMANORCMD_PARTNERID_FIELD.number = 3
PARTNERSTROYMANORCMD_PARTNERID_FIELD.index = 2
PARTNERSTROYMANORCMD_PARTNERID_FIELD.label = 1
PARTNERSTROYMANORCMD_PARTNERID_FIELD.has_default_value = false
PARTNERSTROYMANORCMD_PARTNERID_FIELD.default_value = 0
PARTNERSTROYMANORCMD_PARTNERID_FIELD.type = 13
PARTNERSTROYMANORCMD_PARTNERID_FIELD.cpp_type = 3
PARTNERSTROYMANORCMD_STORYID_FIELD.name = "storyid"
PARTNERSTROYMANORCMD_STORYID_FIELD.full_name = ".Cmd.PartnerStroyManorCmd.storyid"
PARTNERSTROYMANORCMD_STORYID_FIELD.number = 4
PARTNERSTROYMANORCMD_STORYID_FIELD.index = 3
PARTNERSTROYMANORCMD_STORYID_FIELD.label = 1
PARTNERSTROYMANORCMD_STORYID_FIELD.has_default_value = false
PARTNERSTROYMANORCMD_STORYID_FIELD.default_value = 0
PARTNERSTROYMANORCMD_STORYID_FIELD.type = 13
PARTNERSTROYMANORCMD_STORYID_FIELD.cpp_type = 3
PARTNERSTROYMANORCMD.name = "PartnerStroyManorCmd"
PARTNERSTROYMANORCMD.full_name = ".Cmd.PartnerStroyManorCmd"
PARTNERSTROYMANORCMD.nested_types = {}
PARTNERSTROYMANORCMD.enum_types = {}
PARTNERSTROYMANORCMD.fields = {
  PARTNERSTROYMANORCMD_CMD_FIELD,
  PARTNERSTROYMANORCMD_PARAM_FIELD,
  PARTNERSTROYMANORCMD_PARTNERID_FIELD,
  PARTNERSTROYMANORCMD_STORYID_FIELD
}
PARTNERSTROYMANORCMD.is_extendable = false
PARTNERSTROYMANORCMD.extensions = {}
PARTNERQUESTDATA_QUESTID_FIELD.name = "questid"
PARTNERQUESTDATA_QUESTID_FIELD.full_name = ".Cmd.PartnerQuestData.questid"
PARTNERQUESTDATA_QUESTID_FIELD.number = 1
PARTNERQUESTDATA_QUESTID_FIELD.index = 0
PARTNERQUESTDATA_QUESTID_FIELD.label = 1
PARTNERQUESTDATA_QUESTID_FIELD.has_default_value = false
PARTNERQUESTDATA_QUESTID_FIELD.default_value = 0
PARTNERQUESTDATA_QUESTID_FIELD.type = 13
PARTNERQUESTDATA_QUESTID_FIELD.cpp_type = 3
PARTNERQUESTDATA_PARTNERS_FIELD.name = "partners"
PARTNERQUESTDATA_PARTNERS_FIELD.full_name = ".Cmd.PartnerQuestData.partners"
PARTNERQUESTDATA_PARTNERS_FIELD.number = 2
PARTNERQUESTDATA_PARTNERS_FIELD.index = 1
PARTNERQUESTDATA_PARTNERS_FIELD.label = 3
PARTNERQUESTDATA_PARTNERS_FIELD.has_default_value = false
PARTNERQUESTDATA_PARTNERS_FIELD.default_value = {}
PARTNERQUESTDATA_PARTNERS_FIELD.type = 13
PARTNERQUESTDATA_PARTNERS_FIELD.cpp_type = 3
PARTNERQUESTDATA_INPROCESS_FIELD.name = "inprocess"
PARTNERQUESTDATA_INPROCESS_FIELD.full_name = ".Cmd.PartnerQuestData.inprocess"
PARTNERQUESTDATA_INPROCESS_FIELD.number = 3
PARTNERQUESTDATA_INPROCESS_FIELD.index = 2
PARTNERQUESTDATA_INPROCESS_FIELD.label = 1
PARTNERQUESTDATA_INPROCESS_FIELD.has_default_value = false
PARTNERQUESTDATA_INPROCESS_FIELD.default_value = false
PARTNERQUESTDATA_INPROCESS_FIELD.type = 8
PARTNERQUESTDATA_INPROCESS_FIELD.cpp_type = 7
PARTNERQUESTDATA_IGNORENUM_FIELD.name = "ignorenum"
PARTNERQUESTDATA_IGNORENUM_FIELD.full_name = ".Cmd.PartnerQuestData.ignorenum"
PARTNERQUESTDATA_IGNORENUM_FIELD.number = 4
PARTNERQUESTDATA_IGNORENUM_FIELD.index = 3
PARTNERQUESTDATA_IGNORENUM_FIELD.label = 1
PARTNERQUESTDATA_IGNORENUM_FIELD.has_default_value = false
PARTNERQUESTDATA_IGNORENUM_FIELD.default_value = false
PARTNERQUESTDATA_IGNORENUM_FIELD.type = 8
PARTNERQUESTDATA_IGNORENUM_FIELD.cpp_type = 7
PARTNERQUESTDATA.name = "PartnerQuestData"
PARTNERQUESTDATA.full_name = ".Cmd.PartnerQuestData"
PARTNERQUESTDATA.nested_types = {}
PARTNERQUESTDATA.enum_types = {}
PARTNERQUESTDATA.fields = {
  PARTNERQUESTDATA_QUESTID_FIELD,
  PARTNERQUESTDATA_PARTNERS_FIELD,
  PARTNERQUESTDATA_INPROCESS_FIELD,
  PARTNERQUESTDATA_IGNORENUM_FIELD
}
PARTNERQUESTDATA.is_extendable = false
PARTNERQUESTDATA.extensions = {}
ADDPARTNERDATA_PARTNERID_FIELD.name = "partnerid"
ADDPARTNERDATA_PARTNERID_FIELD.full_name = ".Cmd.AddPartnerData.partnerid"
ADDPARTNERDATA_PARTNERID_FIELD.number = 1
ADDPARTNERDATA_PARTNERID_FIELD.index = 0
ADDPARTNERDATA_PARTNERID_FIELD.label = 1
ADDPARTNERDATA_PARTNERID_FIELD.has_default_value = false
ADDPARTNERDATA_PARTNERID_FIELD.default_value = 0
ADDPARTNERDATA_PARTNERID_FIELD.type = 13
ADDPARTNERDATA_PARTNERID_FIELD.cpp_type = 3
ADDPARTNERDATA_POS_FIELD.name = "pos"
ADDPARTNERDATA_POS_FIELD.full_name = ".Cmd.AddPartnerData.pos"
ADDPARTNERDATA_POS_FIELD.number = 2
ADDPARTNERDATA_POS_FIELD.index = 1
ADDPARTNERDATA_POS_FIELD.label = 1
ADDPARTNERDATA_POS_FIELD.has_default_value = false
ADDPARTNERDATA_POS_FIELD.default_value = nil
ADDPARTNERDATA_POS_FIELD.message_type = ProtoCommon_pb.SCENEPOS
ADDPARTNERDATA_POS_FIELD.type = 11
ADDPARTNERDATA_POS_FIELD.cpp_type = 10
ADDPARTNERDATA.name = "AddPartnerData"
ADDPARTNERDATA.full_name = ".Cmd.AddPartnerData"
ADDPARTNERDATA.nested_types = {}
ADDPARTNERDATA.enum_types = {}
ADDPARTNERDATA.fields = {
  ADDPARTNERDATA_PARTNERID_FIELD,
  ADDPARTNERDATA_POS_FIELD
}
ADDPARTNERDATA.is_extendable = false
ADDPARTNERDATA.extensions = {}
PARTNERIDLELISTMANORCMD_CMD_FIELD.name = "cmd"
PARTNERIDLELISTMANORCMD_CMD_FIELD.full_name = ".Cmd.PartnerIdleListManorCmd.cmd"
PARTNERIDLELISTMANORCMD_CMD_FIELD.number = 1
PARTNERIDLELISTMANORCMD_CMD_FIELD.index = 0
PARTNERIDLELISTMANORCMD_CMD_FIELD.label = 1
PARTNERIDLELISTMANORCMD_CMD_FIELD.has_default_value = true
PARTNERIDLELISTMANORCMD_CMD_FIELD.default_value = 233
PARTNERIDLELISTMANORCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
PARTNERIDLELISTMANORCMD_CMD_FIELD.type = 14
PARTNERIDLELISTMANORCMD_CMD_FIELD.cpp_type = 8
PARTNERIDLELISTMANORCMD_PARAM_FIELD.name = "param"
PARTNERIDLELISTMANORCMD_PARAM_FIELD.full_name = ".Cmd.PartnerIdleListManorCmd.param"
PARTNERIDLELISTMANORCMD_PARAM_FIELD.number = 2
PARTNERIDLELISTMANORCMD_PARAM_FIELD.index = 1
PARTNERIDLELISTMANORCMD_PARAM_FIELD.label = 1
PARTNERIDLELISTMANORCMD_PARAM_FIELD.has_default_value = true
PARTNERIDLELISTMANORCMD_PARAM_FIELD.default_value = 10
PARTNERIDLELISTMANORCMD_PARAM_FIELD.enum_type = MANORPARAM
PARTNERIDLELISTMANORCMD_PARAM_FIELD.type = 14
PARTNERIDLELISTMANORCMD_PARAM_FIELD.cpp_type = 8
PARTNERIDLELISTMANORCMD_PARTNERS_FIELD.name = "partners"
PARTNERIDLELISTMANORCMD_PARTNERS_FIELD.full_name = ".Cmd.PartnerIdleListManorCmd.partners"
PARTNERIDLELISTMANORCMD_PARTNERS_FIELD.number = 3
PARTNERIDLELISTMANORCMD_PARTNERS_FIELD.index = 2
PARTNERIDLELISTMANORCMD_PARTNERS_FIELD.label = 3
PARTNERIDLELISTMANORCMD_PARTNERS_FIELD.has_default_value = false
PARTNERIDLELISTMANORCMD_PARTNERS_FIELD.default_value = {}
PARTNERIDLELISTMANORCMD_PARTNERS_FIELD.type = 13
PARTNERIDLELISTMANORCMD_PARTNERS_FIELD.cpp_type = 3
PARTNERIDLELISTMANORCMD.name = "PartnerIdleListManorCmd"
PARTNERIDLELISTMANORCMD.full_name = ".Cmd.PartnerIdleListManorCmd"
PARTNERIDLELISTMANORCMD.nested_types = {}
PARTNERIDLELISTMANORCMD.enum_types = {}
PARTNERIDLELISTMANORCMD.fields = {
  PARTNERIDLELISTMANORCMD_CMD_FIELD,
  PARTNERIDLELISTMANORCMD_PARAM_FIELD,
  PARTNERIDLELISTMANORCMD_PARTNERS_FIELD
}
PARTNERIDLELISTMANORCMD.is_extendable = false
PARTNERIDLELISTMANORCMD.extensions = {}
PARTNERIDLEUPDATEMANORCMD_CMD_FIELD.name = "cmd"
PARTNERIDLEUPDATEMANORCMD_CMD_FIELD.full_name = ".Cmd.PartnerIdleUpdateManorCmd.cmd"
PARTNERIDLEUPDATEMANORCMD_CMD_FIELD.number = 1
PARTNERIDLEUPDATEMANORCMD_CMD_FIELD.index = 0
PARTNERIDLEUPDATEMANORCMD_CMD_FIELD.label = 1
PARTNERIDLEUPDATEMANORCMD_CMD_FIELD.has_default_value = true
PARTNERIDLEUPDATEMANORCMD_CMD_FIELD.default_value = 233
PARTNERIDLEUPDATEMANORCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
PARTNERIDLEUPDATEMANORCMD_CMD_FIELD.type = 14
PARTNERIDLEUPDATEMANORCMD_CMD_FIELD.cpp_type = 8
PARTNERIDLEUPDATEMANORCMD_PARAM_FIELD.name = "param"
PARTNERIDLEUPDATEMANORCMD_PARAM_FIELD.full_name = ".Cmd.PartnerIdleUpdateManorCmd.param"
PARTNERIDLEUPDATEMANORCMD_PARAM_FIELD.number = 2
PARTNERIDLEUPDATEMANORCMD_PARAM_FIELD.index = 1
PARTNERIDLEUPDATEMANORCMD_PARAM_FIELD.label = 1
PARTNERIDLEUPDATEMANORCMD_PARAM_FIELD.has_default_value = true
PARTNERIDLEUPDATEMANORCMD_PARAM_FIELD.default_value = 11
PARTNERIDLEUPDATEMANORCMD_PARAM_FIELD.enum_type = MANORPARAM
PARTNERIDLEUPDATEMANORCMD_PARAM_FIELD.type = 14
PARTNERIDLEUPDATEMANORCMD_PARAM_FIELD.cpp_type = 8
PARTNERIDLEUPDATEMANORCMD_ADDS_FIELD.name = "adds"
PARTNERIDLEUPDATEMANORCMD_ADDS_FIELD.full_name = ".Cmd.PartnerIdleUpdateManorCmd.adds"
PARTNERIDLEUPDATEMANORCMD_ADDS_FIELD.number = 3
PARTNERIDLEUPDATEMANORCMD_ADDS_FIELD.index = 2
PARTNERIDLEUPDATEMANORCMD_ADDS_FIELD.label = 3
PARTNERIDLEUPDATEMANORCMD_ADDS_FIELD.has_default_value = false
PARTNERIDLEUPDATEMANORCMD_ADDS_FIELD.default_value = {}
PARTNERIDLEUPDATEMANORCMD_ADDS_FIELD.message_type = ADDPARTNERDATA
PARTNERIDLEUPDATEMANORCMD_ADDS_FIELD.type = 11
PARTNERIDLEUPDATEMANORCMD_ADDS_FIELD.cpp_type = 10
PARTNERIDLEUPDATEMANORCMD_DELID_FIELD.name = "delid"
PARTNERIDLEUPDATEMANORCMD_DELID_FIELD.full_name = ".Cmd.PartnerIdleUpdateManorCmd.delid"
PARTNERIDLEUPDATEMANORCMD_DELID_FIELD.number = 4
PARTNERIDLEUPDATEMANORCMD_DELID_FIELD.index = 3
PARTNERIDLEUPDATEMANORCMD_DELID_FIELD.label = 3
PARTNERIDLEUPDATEMANORCMD_DELID_FIELD.has_default_value = false
PARTNERIDLEUPDATEMANORCMD_DELID_FIELD.default_value = {}
PARTNERIDLEUPDATEMANORCMD_DELID_FIELD.type = 13
PARTNERIDLEUPDATEMANORCMD_DELID_FIELD.cpp_type = 3
PARTNERIDLEUPDATEMANORCMD.name = "PartnerIdleUpdateManorCmd"
PARTNERIDLEUPDATEMANORCMD.full_name = ".Cmd.PartnerIdleUpdateManorCmd"
PARTNERIDLEUPDATEMANORCMD.nested_types = {}
PARTNERIDLEUPDATEMANORCMD.enum_types = {}
PARTNERIDLEUPDATEMANORCMD.fields = {
  PARTNERIDLEUPDATEMANORCMD_CMD_FIELD,
  PARTNERIDLEUPDATEMANORCMD_PARAM_FIELD,
  PARTNERIDLEUPDATEMANORCMD_ADDS_FIELD,
  PARTNERIDLEUPDATEMANORCMD_DELID_FIELD
}
PARTNERIDLEUPDATEMANORCMD.is_extendable = false
PARTNERIDLEUPDATEMANORCMD.extensions = {}
PARTNERGIVEMANORCMD_CMD_FIELD.name = "cmd"
PARTNERGIVEMANORCMD_CMD_FIELD.full_name = ".Cmd.PartnerGiveManorCmd.cmd"
PARTNERGIVEMANORCMD_CMD_FIELD.number = 1
PARTNERGIVEMANORCMD_CMD_FIELD.index = 0
PARTNERGIVEMANORCMD_CMD_FIELD.label = 1
PARTNERGIVEMANORCMD_CMD_FIELD.has_default_value = true
PARTNERGIVEMANORCMD_CMD_FIELD.default_value = 233
PARTNERGIVEMANORCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
PARTNERGIVEMANORCMD_CMD_FIELD.type = 14
PARTNERGIVEMANORCMD_CMD_FIELD.cpp_type = 8
PARTNERGIVEMANORCMD_PARAM_FIELD.name = "param"
PARTNERGIVEMANORCMD_PARAM_FIELD.full_name = ".Cmd.PartnerGiveManorCmd.param"
PARTNERGIVEMANORCMD_PARAM_FIELD.number = 2
PARTNERGIVEMANORCMD_PARAM_FIELD.index = 1
PARTNERGIVEMANORCMD_PARAM_FIELD.label = 1
PARTNERGIVEMANORCMD_PARAM_FIELD.has_default_value = true
PARTNERGIVEMANORCMD_PARAM_FIELD.default_value = 12
PARTNERGIVEMANORCMD_PARAM_FIELD.enum_type = MANORPARAM
PARTNERGIVEMANORCMD_PARAM_FIELD.type = 14
PARTNERGIVEMANORCMD_PARAM_FIELD.cpp_type = 8
PARTNERGIVEMANORCMD_PARTNERID_FIELD.name = "partnerid"
PARTNERGIVEMANORCMD_PARTNERID_FIELD.full_name = ".Cmd.PartnerGiveManorCmd.partnerid"
PARTNERGIVEMANORCMD_PARTNERID_FIELD.number = 3
PARTNERGIVEMANORCMD_PARTNERID_FIELD.index = 2
PARTNERGIVEMANORCMD_PARTNERID_FIELD.label = 1
PARTNERGIVEMANORCMD_PARTNERID_FIELD.has_default_value = false
PARTNERGIVEMANORCMD_PARTNERID_FIELD.default_value = 0
PARTNERGIVEMANORCMD_PARTNERID_FIELD.type = 13
PARTNERGIVEMANORCMD_PARTNERID_FIELD.cpp_type = 3
PARTNERGIVEMANORCMD_ITEMID_FIELD.name = "itemid"
PARTNERGIVEMANORCMD_ITEMID_FIELD.full_name = ".Cmd.PartnerGiveManorCmd.itemid"
PARTNERGIVEMANORCMD_ITEMID_FIELD.number = 4
PARTNERGIVEMANORCMD_ITEMID_FIELD.index = 3
PARTNERGIVEMANORCMD_ITEMID_FIELD.label = 1
PARTNERGIVEMANORCMD_ITEMID_FIELD.has_default_value = false
PARTNERGIVEMANORCMD_ITEMID_FIELD.default_value = 0
PARTNERGIVEMANORCMD_ITEMID_FIELD.type = 13
PARTNERGIVEMANORCMD_ITEMID_FIELD.cpp_type = 3
PARTNERGIVEMANORCMD_ITEMNUM_FIELD.name = "itemnum"
PARTNERGIVEMANORCMD_ITEMNUM_FIELD.full_name = ".Cmd.PartnerGiveManorCmd.itemnum"
PARTNERGIVEMANORCMD_ITEMNUM_FIELD.number = 5
PARTNERGIVEMANORCMD_ITEMNUM_FIELD.index = 4
PARTNERGIVEMANORCMD_ITEMNUM_FIELD.label = 1
PARTNERGIVEMANORCMD_ITEMNUM_FIELD.has_default_value = false
PARTNERGIVEMANORCMD_ITEMNUM_FIELD.default_value = 0
PARTNERGIVEMANORCMD_ITEMNUM_FIELD.type = 13
PARTNERGIVEMANORCMD_ITEMNUM_FIELD.cpp_type = 3
PARTNERGIVEMANORCMD.name = "PartnerGiveManorCmd"
PARTNERGIVEMANORCMD.full_name = ".Cmd.PartnerGiveManorCmd"
PARTNERGIVEMANORCMD.nested_types = {}
PARTNERGIVEMANORCMD.enum_types = {}
PARTNERGIVEMANORCMD.fields = {
  PARTNERGIVEMANORCMD_CMD_FIELD,
  PARTNERGIVEMANORCMD_PARAM_FIELD,
  PARTNERGIVEMANORCMD_PARTNERID_FIELD,
  PARTNERGIVEMANORCMD_ITEMID_FIELD,
  PARTNERGIVEMANORCMD_ITEMNUM_FIELD
}
PARTNERGIVEMANORCMD.is_extendable = false
PARTNERGIVEMANORCMD.extensions = {}
BUILDFORGEMANORCMD_CMD_FIELD.name = "cmd"
BUILDFORGEMANORCMD_CMD_FIELD.full_name = ".Cmd.BuildForgeManorCmd.cmd"
BUILDFORGEMANORCMD_CMD_FIELD.number = 1
BUILDFORGEMANORCMD_CMD_FIELD.index = 0
BUILDFORGEMANORCMD_CMD_FIELD.label = 1
BUILDFORGEMANORCMD_CMD_FIELD.has_default_value = true
BUILDFORGEMANORCMD_CMD_FIELD.default_value = 233
BUILDFORGEMANORCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
BUILDFORGEMANORCMD_CMD_FIELD.type = 14
BUILDFORGEMANORCMD_CMD_FIELD.cpp_type = 8
BUILDFORGEMANORCMD_PARAM_FIELD.name = "param"
BUILDFORGEMANORCMD_PARAM_FIELD.full_name = ".Cmd.BuildForgeManorCmd.param"
BUILDFORGEMANORCMD_PARAM_FIELD.number = 2
BUILDFORGEMANORCMD_PARAM_FIELD.index = 1
BUILDFORGEMANORCMD_PARAM_FIELD.label = 1
BUILDFORGEMANORCMD_PARAM_FIELD.has_default_value = true
BUILDFORGEMANORCMD_PARAM_FIELD.default_value = 13
BUILDFORGEMANORCMD_PARAM_FIELD.enum_type = MANORPARAM
BUILDFORGEMANORCMD_PARAM_FIELD.type = 14
BUILDFORGEMANORCMD_PARAM_FIELD.cpp_type = 8
BUILDFORGEMANORCMD_PART_FIELD.name = "part"
BUILDFORGEMANORCMD_PART_FIELD.full_name = ".Cmd.BuildForgeManorCmd.part"
BUILDFORGEMANORCMD_PART_FIELD.number = 3
BUILDFORGEMANORCMD_PART_FIELD.index = 2
BUILDFORGEMANORCMD_PART_FIELD.label = 1
BUILDFORGEMANORCMD_PART_FIELD.has_default_value = false
BUILDFORGEMANORCMD_PART_FIELD.default_value = 0
BUILDFORGEMANORCMD_PART_FIELD.type = 13
BUILDFORGEMANORCMD_PART_FIELD.cpp_type = 3
BUILDFORGEMANORCMD_ISREWARD_FIELD.name = "isreward"
BUILDFORGEMANORCMD_ISREWARD_FIELD.full_name = ".Cmd.BuildForgeManorCmd.isreward"
BUILDFORGEMANORCMD_ISREWARD_FIELD.number = 4
BUILDFORGEMANORCMD_ISREWARD_FIELD.index = 3
BUILDFORGEMANORCMD_ISREWARD_FIELD.label = 1
BUILDFORGEMANORCMD_ISREWARD_FIELD.has_default_value = false
BUILDFORGEMANORCMD_ISREWARD_FIELD.default_value = false
BUILDFORGEMANORCMD_ISREWARD_FIELD.type = 8
BUILDFORGEMANORCMD_ISREWARD_FIELD.cpp_type = 7
BUILDFORGEMANORCMD_BUILD_FIELD.name = "build"
BUILDFORGEMANORCMD_BUILD_FIELD.full_name = ".Cmd.BuildForgeManorCmd.build"
BUILDFORGEMANORCMD_BUILD_FIELD.number = 5
BUILDFORGEMANORCMD_BUILD_FIELD.index = 4
BUILDFORGEMANORCMD_BUILD_FIELD.label = 1
BUILDFORGEMANORCMD_BUILD_FIELD.has_default_value = false
BUILDFORGEMANORCMD_BUILD_FIELD.default_value = nil
BUILDFORGEMANORCMD_BUILD_FIELD.message_type = MANORBUILDDATA
BUILDFORGEMANORCMD_BUILD_FIELD.type = 11
BUILDFORGEMANORCMD_BUILD_FIELD.cpp_type = 10
BUILDFORGEMANORCMD.name = "BuildForgeManorCmd"
BUILDFORGEMANORCMD.full_name = ".Cmd.BuildForgeManorCmd"
BUILDFORGEMANORCMD.nested_types = {}
BUILDFORGEMANORCMD.enum_types = {}
BUILDFORGEMANORCMD.fields = {
  BUILDFORGEMANORCMD_CMD_FIELD,
  BUILDFORGEMANORCMD_PARAM_FIELD,
  BUILDFORGEMANORCMD_PART_FIELD,
  BUILDFORGEMANORCMD_ISREWARD_FIELD,
  BUILDFORGEMANORCMD_BUILD_FIELD
}
BUILDFORGEMANORCMD.is_extendable = false
BUILDFORGEMANORCMD.extensions = {}
SMITHQUESTDATA_QUESTID_FIELD.name = "questid"
SMITHQUESTDATA_QUESTID_FIELD.full_name = ".Cmd.SmithQuestData.questid"
SMITHQUESTDATA_QUESTID_FIELD.number = 1
SMITHQUESTDATA_QUESTID_FIELD.index = 0
SMITHQUESTDATA_QUESTID_FIELD.label = 1
SMITHQUESTDATA_QUESTID_FIELD.has_default_value = false
SMITHQUESTDATA_QUESTID_FIELD.default_value = 0
SMITHQUESTDATA_QUESTID_FIELD.type = 13
SMITHQUESTDATA_QUESTID_FIELD.cpp_type = 3
SMITHQUESTDATA_QUEST_STATE_FIELD.name = "quest_state"
SMITHQUESTDATA_QUEST_STATE_FIELD.full_name = ".Cmd.SmithQuestData.quest_state"
SMITHQUESTDATA_QUEST_STATE_FIELD.number = 2
SMITHQUESTDATA_QUEST_STATE_FIELD.index = 1
SMITHQUESTDATA_QUEST_STATE_FIELD.label = 1
SMITHQUESTDATA_QUEST_STATE_FIELD.has_default_value = false
SMITHQUESTDATA_QUEST_STATE_FIELD.default_value = nil
SMITHQUESTDATA_QUEST_STATE_FIELD.enum_type = ESMITHQUESTSTATE
SMITHQUESTDATA_QUEST_STATE_FIELD.type = 14
SMITHQUESTDATA_QUEST_STATE_FIELD.cpp_type = 8
SMITHQUESTDATA_HAS_FINISHED_FIELD.name = "has_finished"
SMITHQUESTDATA_HAS_FINISHED_FIELD.full_name = ".Cmd.SmithQuestData.has_finished"
SMITHQUESTDATA_HAS_FINISHED_FIELD.number = 3
SMITHQUESTDATA_HAS_FINISHED_FIELD.index = 2
SMITHQUESTDATA_HAS_FINISHED_FIELD.label = 1
SMITHQUESTDATA_HAS_FINISHED_FIELD.has_default_value = false
SMITHQUESTDATA_HAS_FINISHED_FIELD.default_value = false
SMITHQUESTDATA_HAS_FINISHED_FIELD.type = 8
SMITHQUESTDATA_HAS_FINISHED_FIELD.cpp_type = 7
SMITHQUESTDATA_HELP_FINISH_TIME_FIELD.name = "help_finish_time"
SMITHQUESTDATA_HELP_FINISH_TIME_FIELD.full_name = ".Cmd.SmithQuestData.help_finish_time"
SMITHQUESTDATA_HELP_FINISH_TIME_FIELD.number = 4
SMITHQUESTDATA_HELP_FINISH_TIME_FIELD.index = 3
SMITHQUESTDATA_HELP_FINISH_TIME_FIELD.label = 1
SMITHQUESTDATA_HELP_FINISH_TIME_FIELD.has_default_value = false
SMITHQUESTDATA_HELP_FINISH_TIME_FIELD.default_value = 0
SMITHQUESTDATA_HELP_FINISH_TIME_FIELD.type = 13
SMITHQUESTDATA_HELP_FINISH_TIME_FIELD.cpp_type = 3
SMITHQUESTDATA_HELP_PARTNER_FIELD.name = "help_partner"
SMITHQUESTDATA_HELP_PARTNER_FIELD.full_name = ".Cmd.SmithQuestData.help_partner"
SMITHQUESTDATA_HELP_PARTNER_FIELD.number = 5
SMITHQUESTDATA_HELP_PARTNER_FIELD.index = 4
SMITHQUESTDATA_HELP_PARTNER_FIELD.label = 1
SMITHQUESTDATA_HELP_PARTNER_FIELD.has_default_value = false
SMITHQUESTDATA_HELP_PARTNER_FIELD.default_value = 0
SMITHQUESTDATA_HELP_PARTNER_FIELD.type = 13
SMITHQUESTDATA_HELP_PARTNER_FIELD.cpp_type = 3
SMITHQUESTDATA.name = "SmithQuestData"
SMITHQUESTDATA.full_name = ".Cmd.SmithQuestData"
SMITHQUESTDATA.nested_types = {}
SMITHQUESTDATA.enum_types = {}
SMITHQUESTDATA.fields = {
  SMITHQUESTDATA_QUESTID_FIELD,
  SMITHQUESTDATA_QUEST_STATE_FIELD,
  SMITHQUESTDATA_HAS_FINISHED_FIELD,
  SMITHQUESTDATA_HELP_FINISH_TIME_FIELD,
  SMITHQUESTDATA_HELP_PARTNER_FIELD
}
SMITHQUESTDATA.is_extendable = false
SMITHQUESTDATA.extensions = {}
SMITHINFOMANORCMD_CMD_FIELD.name = "cmd"
SMITHINFOMANORCMD_CMD_FIELD.full_name = ".Cmd.SmithInfoManorCmd.cmd"
SMITHINFOMANORCMD_CMD_FIELD.number = 1
SMITHINFOMANORCMD_CMD_FIELD.index = 0
SMITHINFOMANORCMD_CMD_FIELD.label = 1
SMITHINFOMANORCMD_CMD_FIELD.has_default_value = true
SMITHINFOMANORCMD_CMD_FIELD.default_value = 233
SMITHINFOMANORCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
SMITHINFOMANORCMD_CMD_FIELD.type = 14
SMITHINFOMANORCMD_CMD_FIELD.cpp_type = 8
SMITHINFOMANORCMD_PARAM_FIELD.name = "param"
SMITHINFOMANORCMD_PARAM_FIELD.full_name = ".Cmd.SmithInfoManorCmd.param"
SMITHINFOMANORCMD_PARAM_FIELD.number = 2
SMITHINFOMANORCMD_PARAM_FIELD.index = 1
SMITHINFOMANORCMD_PARAM_FIELD.label = 1
SMITHINFOMANORCMD_PARAM_FIELD.has_default_value = true
SMITHINFOMANORCMD_PARAM_FIELD.default_value = 14
SMITHINFOMANORCMD_PARAM_FIELD.enum_type = MANORPARAM
SMITHINFOMANORCMD_PARAM_FIELD.type = 14
SMITHINFOMANORCMD_PARAM_FIELD.cpp_type = 8
SMITHINFOMANORCMD_QUESTS_FIELD.name = "quests"
SMITHINFOMANORCMD_QUESTS_FIELD.full_name = ".Cmd.SmithInfoManorCmd.quests"
SMITHINFOMANORCMD_QUESTS_FIELD.number = 3
SMITHINFOMANORCMD_QUESTS_FIELD.index = 2
SMITHINFOMANORCMD_QUESTS_FIELD.label = 3
SMITHINFOMANORCMD_QUESTS_FIELD.has_default_value = false
SMITHINFOMANORCMD_QUESTS_FIELD.default_value = {}
SMITHINFOMANORCMD_QUESTS_FIELD.message_type = SMITHQUESTDATA
SMITHINFOMANORCMD_QUESTS_FIELD.type = 11
SMITHINFOMANORCMD_QUESTS_FIELD.cpp_type = 10
SMITHINFOMANORCMD_ALL_PARTNERS_FIELD.name = "all_partners"
SMITHINFOMANORCMD_ALL_PARTNERS_FIELD.full_name = ".Cmd.SmithInfoManorCmd.all_partners"
SMITHINFOMANORCMD_ALL_PARTNERS_FIELD.number = 4
SMITHINFOMANORCMD_ALL_PARTNERS_FIELD.index = 3
SMITHINFOMANORCMD_ALL_PARTNERS_FIELD.label = 3
SMITHINFOMANORCMD_ALL_PARTNERS_FIELD.has_default_value = false
SMITHINFOMANORCMD_ALL_PARTNERS_FIELD.default_value = {}
SMITHINFOMANORCMD_ALL_PARTNERS_FIELD.type = 13
SMITHINFOMANORCMD_ALL_PARTNERS_FIELD.cpp_type = 3
SMITHINFOMANORCMD_LEVEL_FIELD.name = "level"
SMITHINFOMANORCMD_LEVEL_FIELD.full_name = ".Cmd.SmithInfoManorCmd.level"
SMITHINFOMANORCMD_LEVEL_FIELD.number = 5
SMITHINFOMANORCMD_LEVEL_FIELD.index = 4
SMITHINFOMANORCMD_LEVEL_FIELD.label = 1
SMITHINFOMANORCMD_LEVEL_FIELD.has_default_value = false
SMITHINFOMANORCMD_LEVEL_FIELD.default_value = 0
SMITHINFOMANORCMD_LEVEL_FIELD.type = 13
SMITHINFOMANORCMD_LEVEL_FIELD.cpp_type = 3
SMITHINFOMANORCMD_REWARD_LEVEL_FIELD.name = "reward_level"
SMITHINFOMANORCMD_REWARD_LEVEL_FIELD.full_name = ".Cmd.SmithInfoManorCmd.reward_level"
SMITHINFOMANORCMD_REWARD_LEVEL_FIELD.number = 6
SMITHINFOMANORCMD_REWARD_LEVEL_FIELD.index = 5
SMITHINFOMANORCMD_REWARD_LEVEL_FIELD.label = 1
SMITHINFOMANORCMD_REWARD_LEVEL_FIELD.has_default_value = false
SMITHINFOMANORCMD_REWARD_LEVEL_FIELD.default_value = 0
SMITHINFOMANORCMD_REWARD_LEVEL_FIELD.type = 13
SMITHINFOMANORCMD_REWARD_LEVEL_FIELD.cpp_type = 3
SMITHINFOMANORCMD.name = "SmithInfoManorCmd"
SMITHINFOMANORCMD.full_name = ".Cmd.SmithInfoManorCmd"
SMITHINFOMANORCMD.nested_types = {}
SMITHINFOMANORCMD.enum_types = {}
SMITHINFOMANORCMD.fields = {
  SMITHINFOMANORCMD_CMD_FIELD,
  SMITHINFOMANORCMD_PARAM_FIELD,
  SMITHINFOMANORCMD_QUESTS_FIELD,
  SMITHINFOMANORCMD_ALL_PARTNERS_FIELD,
  SMITHINFOMANORCMD_LEVEL_FIELD,
  SMITHINFOMANORCMD_REWARD_LEVEL_FIELD
}
SMITHINFOMANORCMD.is_extendable = false
SMITHINFOMANORCMD.extensions = {}
SMITHLEVELUPMANORCMD_CMD_FIELD.name = "cmd"
SMITHLEVELUPMANORCMD_CMD_FIELD.full_name = ".Cmd.SmithLevelUpManorCmd.cmd"
SMITHLEVELUPMANORCMD_CMD_FIELD.number = 1
SMITHLEVELUPMANORCMD_CMD_FIELD.index = 0
SMITHLEVELUPMANORCMD_CMD_FIELD.label = 1
SMITHLEVELUPMANORCMD_CMD_FIELD.has_default_value = true
SMITHLEVELUPMANORCMD_CMD_FIELD.default_value = 233
SMITHLEVELUPMANORCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
SMITHLEVELUPMANORCMD_CMD_FIELD.type = 14
SMITHLEVELUPMANORCMD_CMD_FIELD.cpp_type = 8
SMITHLEVELUPMANORCMD_PARAM_FIELD.name = "param"
SMITHLEVELUPMANORCMD_PARAM_FIELD.full_name = ".Cmd.SmithLevelUpManorCmd.param"
SMITHLEVELUPMANORCMD_PARAM_FIELD.number = 2
SMITHLEVELUPMANORCMD_PARAM_FIELD.index = 1
SMITHLEVELUPMANORCMD_PARAM_FIELD.label = 1
SMITHLEVELUPMANORCMD_PARAM_FIELD.has_default_value = true
SMITHLEVELUPMANORCMD_PARAM_FIELD.default_value = 15
SMITHLEVELUPMANORCMD_PARAM_FIELD.enum_type = MANORPARAM
SMITHLEVELUPMANORCMD_PARAM_FIELD.type = 14
SMITHLEVELUPMANORCMD_PARAM_FIELD.cpp_type = 8
SMITHLEVELUPMANORCMD.name = "SmithLevelUpManorCmd"
SMITHLEVELUPMANORCMD.full_name = ".Cmd.SmithLevelUpManorCmd"
SMITHLEVELUPMANORCMD.nested_types = {}
SMITHLEVELUPMANORCMD.enum_types = {}
SMITHLEVELUPMANORCMD.fields = {
  SMITHLEVELUPMANORCMD_CMD_FIELD,
  SMITHLEVELUPMANORCMD_PARAM_FIELD
}
SMITHLEVELUPMANORCMD.is_extendable = false
SMITHLEVELUPMANORCMD.extensions = {}
SMITHACCEPTQUESTMANORCMD_CMD_FIELD.name = "cmd"
SMITHACCEPTQUESTMANORCMD_CMD_FIELD.full_name = ".Cmd.SmithAcceptQuestManorCmd.cmd"
SMITHACCEPTQUESTMANORCMD_CMD_FIELD.number = 1
SMITHACCEPTQUESTMANORCMD_CMD_FIELD.index = 0
SMITHACCEPTQUESTMANORCMD_CMD_FIELD.label = 1
SMITHACCEPTQUESTMANORCMD_CMD_FIELD.has_default_value = true
SMITHACCEPTQUESTMANORCMD_CMD_FIELD.default_value = 233
SMITHACCEPTQUESTMANORCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
SMITHACCEPTQUESTMANORCMD_CMD_FIELD.type = 14
SMITHACCEPTQUESTMANORCMD_CMD_FIELD.cpp_type = 8
SMITHACCEPTQUESTMANORCMD_PARAM_FIELD.name = "param"
SMITHACCEPTQUESTMANORCMD_PARAM_FIELD.full_name = ".Cmd.SmithAcceptQuestManorCmd.param"
SMITHACCEPTQUESTMANORCMD_PARAM_FIELD.number = 2
SMITHACCEPTQUESTMANORCMD_PARAM_FIELD.index = 1
SMITHACCEPTQUESTMANORCMD_PARAM_FIELD.label = 1
SMITHACCEPTQUESTMANORCMD_PARAM_FIELD.has_default_value = true
SMITHACCEPTQUESTMANORCMD_PARAM_FIELD.default_value = 16
SMITHACCEPTQUESTMANORCMD_PARAM_FIELD.enum_type = MANORPARAM
SMITHACCEPTQUESTMANORCMD_PARAM_FIELD.type = 14
SMITHACCEPTQUESTMANORCMD_PARAM_FIELD.cpp_type = 8
SMITHACCEPTQUESTMANORCMD_QUESTID_FIELD.name = "questid"
SMITHACCEPTQUESTMANORCMD_QUESTID_FIELD.full_name = ".Cmd.SmithAcceptQuestManorCmd.questid"
SMITHACCEPTQUESTMANORCMD_QUESTID_FIELD.number = 3
SMITHACCEPTQUESTMANORCMD_QUESTID_FIELD.index = 2
SMITHACCEPTQUESTMANORCMD_QUESTID_FIELD.label = 1
SMITHACCEPTQUESTMANORCMD_QUESTID_FIELD.has_default_value = false
SMITHACCEPTQUESTMANORCMD_QUESTID_FIELD.default_value = 0
SMITHACCEPTQUESTMANORCMD_QUESTID_FIELD.type = 13
SMITHACCEPTQUESTMANORCMD_QUESTID_FIELD.cpp_type = 3
SMITHACCEPTQUESTMANORCMD_HELP_NPCID_FIELD.name = "help_npcid"
SMITHACCEPTQUESTMANORCMD_HELP_NPCID_FIELD.full_name = ".Cmd.SmithAcceptQuestManorCmd.help_npcid"
SMITHACCEPTQUESTMANORCMD_HELP_NPCID_FIELD.number = 4
SMITHACCEPTQUESTMANORCMD_HELP_NPCID_FIELD.index = 3
SMITHACCEPTQUESTMANORCMD_HELP_NPCID_FIELD.label = 1
SMITHACCEPTQUESTMANORCMD_HELP_NPCID_FIELD.has_default_value = false
SMITHACCEPTQUESTMANORCMD_HELP_NPCID_FIELD.default_value = 0
SMITHACCEPTQUESTMANORCMD_HELP_NPCID_FIELD.type = 13
SMITHACCEPTQUESTMANORCMD_HELP_NPCID_FIELD.cpp_type = 3
SMITHACCEPTQUESTMANORCMD.name = "SmithAcceptQuestManorCmd"
SMITHACCEPTQUESTMANORCMD.full_name = ".Cmd.SmithAcceptQuestManorCmd"
SMITHACCEPTQUESTMANORCMD.nested_types = {}
SMITHACCEPTQUESTMANORCMD.enum_types = {}
SMITHACCEPTQUESTMANORCMD.fields = {
  SMITHACCEPTQUESTMANORCMD_CMD_FIELD,
  SMITHACCEPTQUESTMANORCMD_PARAM_FIELD,
  SMITHACCEPTQUESTMANORCMD_QUESTID_FIELD,
  SMITHACCEPTQUESTMANORCMD_HELP_NPCID_FIELD
}
SMITHACCEPTQUESTMANORCMD.is_extendable = false
SMITHACCEPTQUESTMANORCMD.extensions = {}
AddPartnerData = protobuf.Message(ADDPARTNERDATA)
BuildCollectManorCmd = protobuf.Message(BUILDCOLLECTMANORCMD)
BuildDataNtfManorCmd = protobuf.Message(BUILDDATANTFMANORCMD)
BuildDispatchManorCmd = protobuf.Message(BUILDDISPATCHMANORCMD)
BuildForgeManorCmd = protobuf.Message(BUILDFORGEMANORCMD)
BuildLevelUpManorCmd = protobuf.Message(BUILDLEVELUPMANORCMD)
BuildLotteryManorCmd = protobuf.Message(BUILDLOTTERYMANORCMD)
BuildQueryManorCmd = protobuf.Message(BUILDQUERYMANORCMD)
EMANORFUNCTYPE_ADD_GOODS = 9
EMANORFUNCTYPE_ADVENTURE_INCOME = 7
EMANORFUNCTYPE_ADVENTURE_TIMES = 5
EMANORFUNCTYPE_FORGE_PRODUCE = 16
EMANORFUNCTYPE_MAP_ATTR = 3
EMANORFUNCTYPE_MAP_DROP = 6
EMANORFUNCTYPE_MIN = 0
EMANORFUNCTYPE_OPEN_AREA = 4
EMANORFUNCTYPE_OPEN_FORGE_PART = 15
EMANORFUNCTYPE_OPEN_GOODS = 8
EMANORFUNCTYPE_PET_COUNT = 1
EMANORFUNCTYPE_PET_EQUIP = 2
EMANORFUNCTYPE_REDUCE_FORGE_INTERVAL = 14
EMANORFUNCTYPE_STONE_CAPACITY = 10
EMANORFUNCTYPE_STONE_PRODUCE = 11
EMANORFUNCTYPE_WOOD_CAPACITY = 12
EMANORFUNCTYPE_WOOD_PRODUCE = 13
ESMITH_QUEST_ACCEPTED = 1
ESMITH_QUEST_DONE = 3
ESMITH_QUEST_HELPED = 2
ESMITH_QUEST_MIN = 0
MANORPARAM_BUILD_COLLECT = 6
MANORPARAM_BUILD_DATA_NTF = 1
MANORPARAM_BUILD_DISPATCH = 4
MANORPARAM_BUILD_FORGE = 13
MANORPARAM_BUILD_LEVELUP = 3
MANORPARAM_BUILD_LOTTERY = 5
MANORPARAM_BUILD_QUERY = 2
MANORPARAM_ENTER_RAID = 7
MANORPARAM_PARTNER_GIVE = 12
MANORPARAM_PARTNER_IDLE_LIST = 10
MANORPARAM_PARTNER_IDLE_UPDATE = 11
MANORPARAM_PARTNER_INFO = 8
MANORPARAM_PARTNER_STORY = 9
MANORPARAM_SMITH_ACCEPT_QUEST = 16
MANORPARAM_SMITH_INFO = 14
MANORPARAM_SMITH_LEVELUP = 15
ManorBuildData = protobuf.Message(MANORBUILDDATA)
ManorBuildFuncData = protobuf.Message(MANORBUILDFUNCDATA)
ManorDispatchData = protobuf.Message(MANORDISPATCHDATA)
ManorDispatchGroup = protobuf.Message(MANORDISPATCHGROUP)
ManorDispatchReward = protobuf.Message(MANORDISPATCHREWARD)
ManorForgeData = protobuf.Message(MANORFORGEDATA)
ManorLotteryData = protobuf.Message(MANORLOTTERYDATA)
ManorPartnerData = protobuf.Message(MANORPARTNERDATA)
ManorResourseData = protobuf.Message(MANORRESOURSEDATA)
ManorStoryData = protobuf.Message(MANORSTORYDATA)
PartnerGiveManorCmd = protobuf.Message(PARTNERGIVEMANORCMD)
PartnerIdleListManorCmd = protobuf.Message(PARTNERIDLELISTMANORCMD)
PartnerIdleUpdateManorCmd = protobuf.Message(PARTNERIDLEUPDATEMANORCMD)
PartnerInfoManorCmd = protobuf.Message(PARTNERINFOMANORCMD)
PartnerQuestData = protobuf.Message(PARTNERQUESTDATA)
PartnerStroyManorCmd = protobuf.Message(PARTNERSTROYMANORCMD)
ReqEnterRaidManorCmd = protobuf.Message(REQENTERRAIDMANORCMD)
SmithAcceptQuestManorCmd = protobuf.Message(SMITHACCEPTQUESTMANORCMD)
SmithInfoManorCmd = protobuf.Message(SMITHINFOMANORCMD)
SmithLevelUpManorCmd = protobuf.Message(SMITHLEVELUPMANORCMD)
SmithQuestData = protobuf.Message(SMITHQUESTDATA)
