local protobuf = protobuf
autoImport("xCmd_pb")
local xCmd_pb = xCmd_pb
module("SceneTip_pb")
TIPPARAM = protobuf.EnumDescriptor()
TIPPARAM_TIPPARAM_RED_ENUM = protobuf.EnumValueDescriptor()
TIPPARAM_TIPPARAM_BROWSE_ENUM = protobuf.EnumValueDescriptor()
TIPPARAM_TIPPARAM_ADDREDTIP_ENUM = protobuf.EnumValueDescriptor()
TIPPARAM_TIPPARAM_MAX_ENUM = protobuf.EnumValueDescriptor()
EREDSYS = protobuf.EnumDescriptor()
EREDSYS_EREDSYS_MIN_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_ADD_POINT_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_NEW_PROFESSION_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_PROFESSION_UP_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_ROLE_IMG_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_MONSTER_IMG_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_PHOTOFRAME_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_SKILL_POINT_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_FOURTH_SKILL_POINT_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_TEAMAPPLY_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_MANUAL_MONSTER_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_MANUAL_HEAD_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_MANUAL_FACE_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_MANUAL_BACK_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_MANUAL_TAIL_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_MANUAL_CARD_WEAPON_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_MANUAL_CARD_ASSISTANT_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_MANUAL_CARD_ARMOUR_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_MANUAL_CARD_ROBE_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_MANUAL_CARD_SHOES_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_MANUAL_CARD_ACCESSORY_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_MANUAL_CARD_HEAD_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_MANUAL_NPC_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_MANUAL_MOUNT_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_SOCIAL_FRIEND_APPLY_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_MANUAL_MONTHCARD_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_MANUAL_NEWTAIL_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_MANUAL_COLLECTION_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_MANUAL_FOOD_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_GUILD_APPLY_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_GUILD_CHALLENGE_ADD_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_GUILD_CHALLENGE_REWARD_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_GUILD_ICON_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_PUZZLE_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_PRIVATE_CHAT_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_MONSTER_PORTRAIT_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_PORTRAIT_FRAME_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_BACKGROUND_FRAME_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_CHAT_FRAME_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_TRADE_RECORD_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_PET_ADVENTURE_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_TUTOR_TUTOR_UNLOCK_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_TUTOR_STUDENT_UNLOCK_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_TUTOR_APPLY_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_TUTOR_TASK_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_TUTOR_GROW_REWARD_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_TUTOR_BOX_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_WALLET_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_WALLET_TYPE_PAGE_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_MANUAL_PRONTERA_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_MANUAL_GEFFEN_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_MANUAL_MOROCC_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_MANUAL_PAYON_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_MANUAL_GLAST_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_PACK_TEMP_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_AUCTION_RECORD_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_PEAK_LEVEL_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_BEING_BODY_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_FUNCTION_OPENING_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_SERVANT_RECOMMNED_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_SERVANT_GROWTH_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_SERVANT_GROWTH_STEP_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_SERVANT_GROWTH_EP_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_SERVANT_GROWTH_TIME_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_SERVANT_RECOMMNED_DAY_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_SERVANT_RECOMMNED_WEEK_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_SERVANT_RECOMMNED_FOREVER_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_SERVANT_RECOMMNED_SHORTCUT_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_DEAD_BOSS_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_SIGNIN_DAY_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_SIGNIN_ACTIVITY_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_ACT_HITPOLLY_QUEST_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_PAY_SIGN_BUY_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_PAY_SIGN_REWARD_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_GROUPON_LOGIN_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_GROUPON_PROGRESS_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_QUESTPUZZLE_CANLOCK_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_NOVICE_TARGET_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_MANOR_PARTNER_STORY_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_SECRET_ENLIGHT_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_MANUAL_GOAL_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_MINIRO_DICE_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_NOVICE_NOTEBOOK_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_SHOP_BUY_NOTIFY_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_DISNEY_GUIDE_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_FAVORITE_REWARD_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_QUESTIONNAIRE_LOGIN_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_DYNAMIC_UPDATE_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_GLOBAL_DONATIONACTIVITY_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_FAMILY_REWARD_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_USERINVITE_INVITE_LOGIN_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_USERINVITE_RECALL_LOGIN_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_USERRETURN_QUEST_AWARD_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_USERRETURN_LOGIN_AWARD_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_SIGNACTIVITY_NOVICE_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_SIGNACTIVITY_NORMAL_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_NOVICE_BP_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_TECHTREE_PRODUCE_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_PVERAID_ENTRANCE_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_GUILD_ASSEMBLY_AWARD_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_GUILD_ASSEMBLY_ACTIVITY_NTF_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_TECHTREE_LEVEL_AWARD_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_PVERAID_ACHIEVE_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_RETURNINVITE_AWARD_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_LOTTERY_BANNER_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_LOTTERY_ACTIVITY_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_STRENGTH_ACCUMULATE_REWARD_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_FIRST_DEPOSIT_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_SERVANT_CHALLENGE_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_BATTLE_FUND_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_NEWBIETECHTREE_LEVEL_AWARD_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_GLOBAL_RECOMMEND_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_GLOBAL_NEWPARTNER_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_RETURN_BP_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_QUESTHERO_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_LOTTERY_DAILY_REWARD_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_LOTTERY_FREE_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_ACCUM_DEPOSIT_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_BOLI_GOLD_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_NEW_TOPIC_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_NEW_TOPIC_REWARD_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_PROFESSION_BRANCH_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_GIFT_TIME_LIMIT_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_HEROSHOP_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_NOVICE_CHARGE_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_ANNIVERSARY_LIVE_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_ACT_BP_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_HERO_GROWTH_QUEST_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_HERO_STORY_QUEST_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_GLOBAL_ACT_REWARD_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_EVENT_ACT_REWARD_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_HOME_GIFT_BOX_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_NEW_SERVER_CHALLENGE_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_PRESTIGE_SYSTEM_REWARD_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_NEW_YEAR_MEMORY_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_MISSION_REWARD_ENUM = protobuf.EnumValueDescriptor()
EREDSYS_EREDSYS_MAX_ENUM = protobuf.EnumValueDescriptor()
ETIPOPT = protobuf.EnumDescriptor()
ETIPOPT_ETIPOPT_MIN_ENUM = protobuf.EnumValueDescriptor()
ETIPOPT_ETIPOPT_UPDATE_ENUM = protobuf.EnumValueDescriptor()
ETIPOPT_ETIPOPT_DELETE_ENUM = protobuf.EnumValueDescriptor()
ETIPITEMOPT = protobuf.EnumDescriptor()
ETIPITEMOPT_ETIPITEMOPT_ADD_ENUM = protobuf.EnumValueDescriptor()
ETIPITEMOPT_ETIPITEMOPT_DELETE_ENUM = protobuf.EnumValueDescriptor()
REDTIP = protobuf.Descriptor()
REDTIP_REDSYS_FIELD = protobuf.FieldDescriptor()
REDTIP_OPTITEM_FIELD = protobuf.FieldDescriptor()
REDTIP_TIPID_FIELD = protobuf.FieldDescriptor()
GAMETIPCMD = protobuf.Descriptor()
GAMETIPCMD_CMD_FIELD = protobuf.FieldDescriptor()
GAMETIPCMD_PARAM_FIELD = protobuf.FieldDescriptor()
GAMETIPCMD_OPT_FIELD = protobuf.FieldDescriptor()
GAMETIPCMD_REDTIP_FIELD = protobuf.FieldDescriptor()
BROWSEREDTIPCMD = protobuf.Descriptor()
BROWSEREDTIPCMD_CMD_FIELD = protobuf.FieldDescriptor()
BROWSEREDTIPCMD_PARAM_FIELD = protobuf.FieldDescriptor()
BROWSEREDTIPCMD_RED_FIELD = protobuf.FieldDescriptor()
BROWSEREDTIPCMD_TIPID_FIELD = protobuf.FieldDescriptor()
ADDREDTIP = protobuf.Descriptor()
ADDREDTIP_CMD_FIELD = protobuf.FieldDescriptor()
ADDREDTIP_PARAM_FIELD = protobuf.FieldDescriptor()
ADDREDTIP_RED_FIELD = protobuf.FieldDescriptor()
ADDREDTIP_TIPID_FIELD = protobuf.FieldDescriptor()
TIPPARAM_TIPPARAM_RED_ENUM.name = "TIPPARAM_RED"
TIPPARAM_TIPPARAM_RED_ENUM.index = 0
TIPPARAM_TIPPARAM_RED_ENUM.number = 1
TIPPARAM_TIPPARAM_BROWSE_ENUM.name = "TIPPARAM_BROWSE"
TIPPARAM_TIPPARAM_BROWSE_ENUM.index = 1
TIPPARAM_TIPPARAM_BROWSE_ENUM.number = 2
TIPPARAM_TIPPARAM_ADDREDTIP_ENUM.name = "TIPPARAM_ADDREDTIP"
TIPPARAM_TIPPARAM_ADDREDTIP_ENUM.index = 2
TIPPARAM_TIPPARAM_ADDREDTIP_ENUM.number = 3
TIPPARAM_TIPPARAM_MAX_ENUM.name = "TIPPARAM_MAX"
TIPPARAM_TIPPARAM_MAX_ENUM.index = 3
TIPPARAM_TIPPARAM_MAX_ENUM.number = 4
TIPPARAM.name = "TipParam"
TIPPARAM.full_name = ".Cmd.TipParam"
TIPPARAM.values = {
  TIPPARAM_TIPPARAM_RED_ENUM,
  TIPPARAM_TIPPARAM_BROWSE_ENUM,
  TIPPARAM_TIPPARAM_ADDREDTIP_ENUM,
  TIPPARAM_TIPPARAM_MAX_ENUM
}
EREDSYS_EREDSYS_MIN_ENUM.name = "EREDSYS_MIN"
EREDSYS_EREDSYS_MIN_ENUM.index = 0
EREDSYS_EREDSYS_MIN_ENUM.number = 0
EREDSYS_EREDSYS_ADD_POINT_ENUM.name = "EREDSYS_ADD_POINT"
EREDSYS_EREDSYS_ADD_POINT_ENUM.index = 1
EREDSYS_EREDSYS_ADD_POINT_ENUM.number = 1
EREDSYS_EREDSYS_NEW_PROFESSION_ENUM.name = "EREDSYS_NEW_PROFESSION"
EREDSYS_EREDSYS_NEW_PROFESSION_ENUM.index = 2
EREDSYS_EREDSYS_NEW_PROFESSION_ENUM.number = 2
EREDSYS_EREDSYS_PROFESSION_UP_ENUM.name = "EREDSYS_PROFESSION_UP"
EREDSYS_EREDSYS_PROFESSION_UP_ENUM.index = 3
EREDSYS_EREDSYS_PROFESSION_UP_ENUM.number = 3
EREDSYS_EREDSYS_ROLE_IMG_ENUM.name = "EREDSYS_ROLE_IMG"
EREDSYS_EREDSYS_ROLE_IMG_ENUM.index = 4
EREDSYS_EREDSYS_ROLE_IMG_ENUM.number = 4
EREDSYS_EREDSYS_MONSTER_IMG_ENUM.name = "EREDSYS_MONSTER_IMG"
EREDSYS_EREDSYS_MONSTER_IMG_ENUM.index = 5
EREDSYS_EREDSYS_MONSTER_IMG_ENUM.number = 5
EREDSYS_EREDSYS_PHOTOFRAME_ENUM.name = "EREDSYS_PHOTOFRAME"
EREDSYS_EREDSYS_PHOTOFRAME_ENUM.index = 6
EREDSYS_EREDSYS_PHOTOFRAME_ENUM.number = 6
EREDSYS_EREDSYS_SKILL_POINT_ENUM.name = "EREDSYS_SKILL_POINT"
EREDSYS_EREDSYS_SKILL_POINT_ENUM.index = 7
EREDSYS_EREDSYS_SKILL_POINT_ENUM.number = 7
EREDSYS_EREDSYS_FOURTH_SKILL_POINT_ENUM.name = "EREDSYS_FOURTH_SKILL_POINT"
EREDSYS_EREDSYS_FOURTH_SKILL_POINT_ENUM.index = 8
EREDSYS_EREDSYS_FOURTH_SKILL_POINT_ENUM.number = 8
EREDSYS_EREDSYS_TEAMAPPLY_ENUM.name = "EREDSYS_TEAMAPPLY"
EREDSYS_EREDSYS_TEAMAPPLY_ENUM.index = 9
EREDSYS_EREDSYS_TEAMAPPLY_ENUM.number = 19
EREDSYS_EREDSYS_MANUAL_MONSTER_ENUM.name = "EREDSYS_MANUAL_MONSTER"
EREDSYS_EREDSYS_MANUAL_MONSTER_ENUM.index = 10
EREDSYS_EREDSYS_MANUAL_MONSTER_ENUM.number = 20
EREDSYS_EREDSYS_MANUAL_HEAD_ENUM.name = "EREDSYS_MANUAL_HEAD"
EREDSYS_EREDSYS_MANUAL_HEAD_ENUM.index = 11
EREDSYS_EREDSYS_MANUAL_HEAD_ENUM.number = 21
EREDSYS_EREDSYS_MANUAL_FACE_ENUM.name = "EREDSYS_MANUAL_FACE"
EREDSYS_EREDSYS_MANUAL_FACE_ENUM.index = 12
EREDSYS_EREDSYS_MANUAL_FACE_ENUM.number = 22
EREDSYS_EREDSYS_MANUAL_BACK_ENUM.name = "EREDSYS_MANUAL_BACK"
EREDSYS_EREDSYS_MANUAL_BACK_ENUM.index = 13
EREDSYS_EREDSYS_MANUAL_BACK_ENUM.number = 23
EREDSYS_EREDSYS_MANUAL_TAIL_ENUM.name = "EREDSYS_MANUAL_TAIL"
EREDSYS_EREDSYS_MANUAL_TAIL_ENUM.index = 14
EREDSYS_EREDSYS_MANUAL_TAIL_ENUM.number = 24
EREDSYS_EREDSYS_MANUAL_CARD_WEAPON_ENUM.name = "EREDSYS_MANUAL_CARD_WEAPON"
EREDSYS_EREDSYS_MANUAL_CARD_WEAPON_ENUM.index = 15
EREDSYS_EREDSYS_MANUAL_CARD_WEAPON_ENUM.number = 25
EREDSYS_EREDSYS_MANUAL_CARD_ASSISTANT_ENUM.name = "EREDSYS_MANUAL_CARD_ASSISTANT"
EREDSYS_EREDSYS_MANUAL_CARD_ASSISTANT_ENUM.index = 16
EREDSYS_EREDSYS_MANUAL_CARD_ASSISTANT_ENUM.number = 26
EREDSYS_EREDSYS_MANUAL_CARD_ARMOUR_ENUM.name = "EREDSYS_MANUAL_CARD_ARMOUR"
EREDSYS_EREDSYS_MANUAL_CARD_ARMOUR_ENUM.index = 17
EREDSYS_EREDSYS_MANUAL_CARD_ARMOUR_ENUM.number = 27
EREDSYS_EREDSYS_MANUAL_CARD_ROBE_ENUM.name = "EREDSYS_MANUAL_CARD_ROBE"
EREDSYS_EREDSYS_MANUAL_CARD_ROBE_ENUM.index = 18
EREDSYS_EREDSYS_MANUAL_CARD_ROBE_ENUM.number = 28
EREDSYS_EREDSYS_MANUAL_CARD_SHOES_ENUM.name = "EREDSYS_MANUAL_CARD_SHOES"
EREDSYS_EREDSYS_MANUAL_CARD_SHOES_ENUM.index = 19
EREDSYS_EREDSYS_MANUAL_CARD_SHOES_ENUM.number = 29
EREDSYS_EREDSYS_MANUAL_CARD_ACCESSORY_ENUM.name = "EREDSYS_MANUAL_CARD_ACCESSORY"
EREDSYS_EREDSYS_MANUAL_CARD_ACCESSORY_ENUM.index = 20
EREDSYS_EREDSYS_MANUAL_CARD_ACCESSORY_ENUM.number = 30
EREDSYS_EREDSYS_MANUAL_CARD_HEAD_ENUM.name = "EREDSYS_MANUAL_CARD_HEAD"
EREDSYS_EREDSYS_MANUAL_CARD_HEAD_ENUM.index = 21
EREDSYS_EREDSYS_MANUAL_CARD_HEAD_ENUM.number = 31
EREDSYS_EREDSYS_MANUAL_NPC_ENUM.name = "EREDSYS_MANUAL_NPC"
EREDSYS_EREDSYS_MANUAL_NPC_ENUM.index = 22
EREDSYS_EREDSYS_MANUAL_NPC_ENUM.number = 32
EREDSYS_EREDSYS_MANUAL_MOUNT_ENUM.name = "EREDSYS_MANUAL_MOUNT"
EREDSYS_EREDSYS_MANUAL_MOUNT_ENUM.index = 23
EREDSYS_EREDSYS_MANUAL_MOUNT_ENUM.number = 33
EREDSYS_EREDSYS_SOCIAL_FRIEND_APPLY_ENUM.name = "EREDSYS_SOCIAL_FRIEND_APPLY"
EREDSYS_EREDSYS_SOCIAL_FRIEND_APPLY_ENUM.index = 24
EREDSYS_EREDSYS_SOCIAL_FRIEND_APPLY_ENUM.number = 34
EREDSYS_EREDSYS_MANUAL_MONTHCARD_ENUM.name = "EREDSYS_MANUAL_MONTHCARD"
EREDSYS_EREDSYS_MANUAL_MONTHCARD_ENUM.index = 25
EREDSYS_EREDSYS_MANUAL_MONTHCARD_ENUM.number = 35
EREDSYS_EREDSYS_MANUAL_NEWTAIL_ENUM.name = "EREDSYS_MANUAL_NEWTAIL"
EREDSYS_EREDSYS_MANUAL_NEWTAIL_ENUM.index = 26
EREDSYS_EREDSYS_MANUAL_NEWTAIL_ENUM.number = 36
EREDSYS_EREDSYS_MANUAL_COLLECTION_ENUM.name = "EREDSYS_MANUAL_COLLECTION"
EREDSYS_EREDSYS_MANUAL_COLLECTION_ENUM.index = 27
EREDSYS_EREDSYS_MANUAL_COLLECTION_ENUM.number = 37
EREDSYS_EREDSYS_MANUAL_FOOD_ENUM.name = "EREDSYS_MANUAL_FOOD"
EREDSYS_EREDSYS_MANUAL_FOOD_ENUM.index = 28
EREDSYS_EREDSYS_MANUAL_FOOD_ENUM.number = 38
EREDSYS_EREDSYS_GUILD_APPLY_ENUM.name = "EREDSYS_GUILD_APPLY"
EREDSYS_EREDSYS_GUILD_APPLY_ENUM.index = 29
EREDSYS_EREDSYS_GUILD_APPLY_ENUM.number = 40
EREDSYS_EREDSYS_GUILD_CHALLENGE_ADD_ENUM.name = "EREDSYS_GUILD_CHALLENGE_ADD"
EREDSYS_EREDSYS_GUILD_CHALLENGE_ADD_ENUM.index = 30
EREDSYS_EREDSYS_GUILD_CHALLENGE_ADD_ENUM.number = 41
EREDSYS_EREDSYS_GUILD_CHALLENGE_REWARD_ENUM.name = "EREDSYS_GUILD_CHALLENGE_REWARD"
EREDSYS_EREDSYS_GUILD_CHALLENGE_REWARD_ENUM.index = 31
EREDSYS_EREDSYS_GUILD_CHALLENGE_REWARD_ENUM.number = 42
EREDSYS_EREDSYS_GUILD_ICON_ENUM.name = "EREDSYS_GUILD_ICON"
EREDSYS_EREDSYS_GUILD_ICON_ENUM.index = 32
EREDSYS_EREDSYS_GUILD_ICON_ENUM.number = 43
EREDSYS_EREDSYS_PUZZLE_ENUM.name = "EREDSYS_PUZZLE"
EREDSYS_EREDSYS_PUZZLE_ENUM.index = 33
EREDSYS_EREDSYS_PUZZLE_ENUM.number = 45
EREDSYS_EREDSYS_PRIVATE_CHAT_ENUM.name = "EREDSYS_PRIVATE_CHAT"
EREDSYS_EREDSYS_PRIVATE_CHAT_ENUM.index = 34
EREDSYS_EREDSYS_PRIVATE_CHAT_ENUM.number = 50
EREDSYS_EREDSYS_MONSTER_PORTRAIT_ENUM.name = "EREDSYS_MONSTER_PORTRAIT"
EREDSYS_EREDSYS_MONSTER_PORTRAIT_ENUM.index = 35
EREDSYS_EREDSYS_MONSTER_PORTRAIT_ENUM.number = 51
EREDSYS_EREDSYS_PORTRAIT_FRAME_ENUM.name = "EREDSYS_PORTRAIT_FRAME"
EREDSYS_EREDSYS_PORTRAIT_FRAME_ENUM.index = 36
EREDSYS_EREDSYS_PORTRAIT_FRAME_ENUM.number = 52
EREDSYS_EREDSYS_BACKGROUND_FRAME_ENUM.name = "EREDSYS_BACKGROUND_FRAME"
EREDSYS_EREDSYS_BACKGROUND_FRAME_ENUM.index = 37
EREDSYS_EREDSYS_BACKGROUND_FRAME_ENUM.number = 53
EREDSYS_EREDSYS_CHAT_FRAME_ENUM.name = "EREDSYS_CHAT_FRAME"
EREDSYS_EREDSYS_CHAT_FRAME_ENUM.index = 38
EREDSYS_EREDSYS_CHAT_FRAME_ENUM.number = 54
EREDSYS_EREDSYS_TRADE_RECORD_ENUM.name = "EREDSYS_TRADE_RECORD"
EREDSYS_EREDSYS_TRADE_RECORD_ENUM.index = 39
EREDSYS_EREDSYS_TRADE_RECORD_ENUM.number = 60
EREDSYS_EREDSYS_PET_ADVENTURE_ENUM.name = "EREDSYS_PET_ADVENTURE"
EREDSYS_EREDSYS_PET_ADVENTURE_ENUM.index = 40
EREDSYS_EREDSYS_PET_ADVENTURE_ENUM.number = 70
EREDSYS_EREDSYS_TUTOR_TUTOR_UNLOCK_ENUM.name = "EREDSYS_TUTOR_TUTOR_UNLOCK"
EREDSYS_EREDSYS_TUTOR_TUTOR_UNLOCK_ENUM.index = 41
EREDSYS_EREDSYS_TUTOR_TUTOR_UNLOCK_ENUM.number = 80
EREDSYS_EREDSYS_TUTOR_STUDENT_UNLOCK_ENUM.name = "EREDSYS_TUTOR_STUDENT_UNLOCK"
EREDSYS_EREDSYS_TUTOR_STUDENT_UNLOCK_ENUM.index = 42
EREDSYS_EREDSYS_TUTOR_STUDENT_UNLOCK_ENUM.number = 81
EREDSYS_EREDSYS_TUTOR_APPLY_ENUM.name = "EREDSYS_TUTOR_APPLY"
EREDSYS_EREDSYS_TUTOR_APPLY_ENUM.index = 43
EREDSYS_EREDSYS_TUTOR_APPLY_ENUM.number = 82
EREDSYS_EREDSYS_TUTOR_TASK_ENUM.name = "EREDSYS_TUTOR_TASK"
EREDSYS_EREDSYS_TUTOR_TASK_ENUM.index = 44
EREDSYS_EREDSYS_TUTOR_TASK_ENUM.number = 83
EREDSYS_EREDSYS_TUTOR_GROW_REWARD_ENUM.name = "EREDSYS_TUTOR_GROW_REWARD"
EREDSYS_EREDSYS_TUTOR_GROW_REWARD_ENUM.index = 45
EREDSYS_EREDSYS_TUTOR_GROW_REWARD_ENUM.number = 85
EREDSYS_EREDSYS_TUTOR_BOX_ENUM.name = "EREDSYS_TUTOR_BOX"
EREDSYS_EREDSYS_TUTOR_BOX_ENUM.index = 46
EREDSYS_EREDSYS_TUTOR_BOX_ENUM.number = 86
EREDSYS_EREDSYS_WALLET_ENUM.name = "EREDSYS_WALLET"
EREDSYS_EREDSYS_WALLET_ENUM.index = 47
EREDSYS_EREDSYS_WALLET_ENUM.number = 87
EREDSYS_EREDSYS_WALLET_TYPE_PAGE_ENUM.name = "EREDSYS_WALLET_TYPE_PAGE"
EREDSYS_EREDSYS_WALLET_TYPE_PAGE_ENUM.index = 48
EREDSYS_EREDSYS_WALLET_TYPE_PAGE_ENUM.number = 88
EREDSYS_EREDSYS_MANUAL_PRONTERA_ENUM.name = "EREDSYS_MANUAL_PRONTERA"
EREDSYS_EREDSYS_MANUAL_PRONTERA_ENUM.index = 49
EREDSYS_EREDSYS_MANUAL_PRONTERA_ENUM.number = 101
EREDSYS_EREDSYS_MANUAL_GEFFEN_ENUM.name = "EREDSYS_MANUAL_GEFFEN"
EREDSYS_EREDSYS_MANUAL_GEFFEN_ENUM.index = 50
EREDSYS_EREDSYS_MANUAL_GEFFEN_ENUM.number = 102
EREDSYS_EREDSYS_MANUAL_MOROCC_ENUM.name = "EREDSYS_MANUAL_MOROCC"
EREDSYS_EREDSYS_MANUAL_MOROCC_ENUM.index = 51
EREDSYS_EREDSYS_MANUAL_MOROCC_ENUM.number = 103
EREDSYS_EREDSYS_MANUAL_PAYON_ENUM.name = "EREDSYS_MANUAL_PAYON"
EREDSYS_EREDSYS_MANUAL_PAYON_ENUM.index = 52
EREDSYS_EREDSYS_MANUAL_PAYON_ENUM.number = 104
EREDSYS_EREDSYS_MANUAL_GLAST_ENUM.name = "EREDSYS_MANUAL_GLAST"
EREDSYS_EREDSYS_MANUAL_GLAST_ENUM.index = 53
EREDSYS_EREDSYS_MANUAL_GLAST_ENUM.number = 105
EREDSYS_EREDSYS_PACK_TEMP_ENUM.name = "EREDSYS_PACK_TEMP"
EREDSYS_EREDSYS_PACK_TEMP_ENUM.index = 54
EREDSYS_EREDSYS_PACK_TEMP_ENUM.number = 106
EREDSYS_EREDSYS_AUCTION_RECORD_ENUM.name = "EREDSYS_AUCTION_RECORD"
EREDSYS_EREDSYS_AUCTION_RECORD_ENUM.index = 55
EREDSYS_EREDSYS_AUCTION_RECORD_ENUM.number = 84
EREDSYS_EREDSYS_PEAK_LEVEL_ENUM.name = "EREDSYS_PEAK_LEVEL"
EREDSYS_EREDSYS_PEAK_LEVEL_ENUM.index = 56
EREDSYS_EREDSYS_PEAK_LEVEL_ENUM.number = 132
EREDSYS_EREDSYS_BEING_BODY_ENUM.name = "EREDSYS_BEING_BODY"
EREDSYS_EREDSYS_BEING_BODY_ENUM.index = 57
EREDSYS_EREDSYS_BEING_BODY_ENUM.number = 300
EREDSYS_EREDSYS_FUNCTION_OPENING_ENUM.name = "EREDSYS_FUNCTION_OPENING"
EREDSYS_EREDSYS_FUNCTION_OPENING_ENUM.index = 58
EREDSYS_EREDSYS_FUNCTION_OPENING_ENUM.number = 310
EREDSYS_EREDSYS_SERVANT_RECOMMNED_ENUM.name = "EREDSYS_SERVANT_RECOMMNED"
EREDSYS_EREDSYS_SERVANT_RECOMMNED_ENUM.index = 59
EREDSYS_EREDSYS_SERVANT_RECOMMNED_ENUM.number = 400
EREDSYS_EREDSYS_SERVANT_GROWTH_ENUM.name = "EREDSYS_SERVANT_GROWTH"
EREDSYS_EREDSYS_SERVANT_GROWTH_ENUM.index = 60
EREDSYS_EREDSYS_SERVANT_GROWTH_ENUM.number = 401
EREDSYS_EREDSYS_SERVANT_GROWTH_STEP_ENUM.name = "EREDSYS_SERVANT_GROWTH_STEP"
EREDSYS_EREDSYS_SERVANT_GROWTH_STEP_ENUM.index = 61
EREDSYS_EREDSYS_SERVANT_GROWTH_STEP_ENUM.number = 402
EREDSYS_EREDSYS_SERVANT_GROWTH_EP_ENUM.name = "EREDSYS_SERVANT_GROWTH_EP"
EREDSYS_EREDSYS_SERVANT_GROWTH_EP_ENUM.index = 62
EREDSYS_EREDSYS_SERVANT_GROWTH_EP_ENUM.number = 403
EREDSYS_EREDSYS_SERVANT_GROWTH_TIME_ENUM.name = "EREDSYS_SERVANT_GROWTH_TIME"
EREDSYS_EREDSYS_SERVANT_GROWTH_TIME_ENUM.index = 63
EREDSYS_EREDSYS_SERVANT_GROWTH_TIME_ENUM.number = 404
EREDSYS_EREDSYS_SERVANT_RECOMMNED_DAY_ENUM.name = "EREDSYS_SERVANT_RECOMMNED_DAY"
EREDSYS_EREDSYS_SERVANT_RECOMMNED_DAY_ENUM.index = 64
EREDSYS_EREDSYS_SERVANT_RECOMMNED_DAY_ENUM.number = 410
EREDSYS_EREDSYS_SERVANT_RECOMMNED_WEEK_ENUM.name = "EREDSYS_SERVANT_RECOMMNED_WEEK"
EREDSYS_EREDSYS_SERVANT_RECOMMNED_WEEK_ENUM.index = 65
EREDSYS_EREDSYS_SERVANT_RECOMMNED_WEEK_ENUM.number = 411
EREDSYS_EREDSYS_SERVANT_RECOMMNED_FOREVER_ENUM.name = "EREDSYS_SERVANT_RECOMMNED_FOREVER"
EREDSYS_EREDSYS_SERVANT_RECOMMNED_FOREVER_ENUM.index = 66
EREDSYS_EREDSYS_SERVANT_RECOMMNED_FOREVER_ENUM.number = 412
EREDSYS_EREDSYS_SERVANT_RECOMMNED_SHORTCUT_ENUM.name = "EREDSYS_SERVANT_RECOMMNED_SHORTCUT"
EREDSYS_EREDSYS_SERVANT_RECOMMNED_SHORTCUT_ENUM.index = 67
EREDSYS_EREDSYS_SERVANT_RECOMMNED_SHORTCUT_ENUM.number = 413
EREDSYS_EREDSYS_DEAD_BOSS_ENUM.name = "EREDSYS_DEAD_BOSS"
EREDSYS_EREDSYS_DEAD_BOSS_ENUM.index = 68
EREDSYS_EREDSYS_DEAD_BOSS_ENUM.number = 600
EREDSYS_EREDSYS_SIGNIN_DAY_ENUM.name = "EREDSYS_SIGNIN_DAY"
EREDSYS_EREDSYS_SIGNIN_DAY_ENUM.index = 69
EREDSYS_EREDSYS_SIGNIN_DAY_ENUM.number = 700
EREDSYS_EREDSYS_SIGNIN_ACTIVITY_ENUM.name = "EREDSYS_SIGNIN_ACTIVITY"
EREDSYS_EREDSYS_SIGNIN_ACTIVITY_ENUM.index = 70
EREDSYS_EREDSYS_SIGNIN_ACTIVITY_ENUM.number = 701
EREDSYS_EREDSYS_ACT_HITPOLLY_QUEST_ENUM.name = "EREDSYS_ACT_HITPOLLY_QUEST"
EREDSYS_EREDSYS_ACT_HITPOLLY_QUEST_ENUM.index = 71
EREDSYS_EREDSYS_ACT_HITPOLLY_QUEST_ENUM.number = 702
EREDSYS_EREDSYS_PAY_SIGN_BUY_ENUM.name = "EREDSYS_PAY_SIGN_BUY"
EREDSYS_EREDSYS_PAY_SIGN_BUY_ENUM.index = 72
EREDSYS_EREDSYS_PAY_SIGN_BUY_ENUM.number = 703
EREDSYS_EREDSYS_PAY_SIGN_REWARD_ENUM.name = "EREDSYS_PAY_SIGN_REWARD"
EREDSYS_EREDSYS_PAY_SIGN_REWARD_ENUM.index = 73
EREDSYS_EREDSYS_PAY_SIGN_REWARD_ENUM.number = 704
EREDSYS_EREDSYS_GROUPON_LOGIN_ENUM.name = "EREDSYS_GROUPON_LOGIN"
EREDSYS_EREDSYS_GROUPON_LOGIN_ENUM.index = 74
EREDSYS_EREDSYS_GROUPON_LOGIN_ENUM.number = 705
EREDSYS_EREDSYS_GROUPON_PROGRESS_ENUM.name = "EREDSYS_GROUPON_PROGRESS"
EREDSYS_EREDSYS_GROUPON_PROGRESS_ENUM.index = 75
EREDSYS_EREDSYS_GROUPON_PROGRESS_ENUM.number = 706
EREDSYS_EREDSYS_QUESTPUZZLE_CANLOCK_ENUM.name = "EREDSYS_QUESTPUZZLE_CANLOCK"
EREDSYS_EREDSYS_QUESTPUZZLE_CANLOCK_ENUM.index = 76
EREDSYS_EREDSYS_QUESTPUZZLE_CANLOCK_ENUM.number = 707
EREDSYS_EREDSYS_NOVICE_TARGET_ENUM.name = "EREDSYS_NOVICE_TARGET"
EREDSYS_EREDSYS_NOVICE_TARGET_ENUM.index = 77
EREDSYS_EREDSYS_NOVICE_TARGET_ENUM.number = 708
EREDSYS_EREDSYS_MANOR_PARTNER_STORY_ENUM.name = "EREDSYS_MANOR_PARTNER_STORY"
EREDSYS_EREDSYS_MANOR_PARTNER_STORY_ENUM.index = 78
EREDSYS_EREDSYS_MANOR_PARTNER_STORY_ENUM.number = 709
EREDSYS_EREDSYS_SECRET_ENLIGHT_ENUM.name = "EREDSYS_SECRET_ENLIGHT"
EREDSYS_EREDSYS_SECRET_ENLIGHT_ENUM.index = 79
EREDSYS_EREDSYS_SECRET_ENLIGHT_ENUM.number = 710
EREDSYS_EREDSYS_MANUAL_GOAL_ENUM.name = "EREDSYS_MANUAL_GOAL"
EREDSYS_EREDSYS_MANUAL_GOAL_ENUM.index = 80
EREDSYS_EREDSYS_MANUAL_GOAL_ENUM.number = 10100
EREDSYS_EREDSYS_MINIRO_DICE_ENUM.name = "EREDSYS_MINIRO_DICE"
EREDSYS_EREDSYS_MINIRO_DICE_ENUM.index = 81
EREDSYS_EREDSYS_MINIRO_DICE_ENUM.number = 10400
EREDSYS_EREDSYS_NOVICE_NOTEBOOK_ENUM.name = "EREDSYS_NOVICE_NOTEBOOK"
EREDSYS_EREDSYS_NOVICE_NOTEBOOK_ENUM.index = 82
EREDSYS_EREDSYS_NOVICE_NOTEBOOK_ENUM.number = 10410
EREDSYS_EREDSYS_SHOP_BUY_NOTIFY_ENUM.name = "EREDSYS_SHOP_BUY_NOTIFY"
EREDSYS_EREDSYS_SHOP_BUY_NOTIFY_ENUM.index = 83
EREDSYS_EREDSYS_SHOP_BUY_NOTIFY_ENUM.number = 10600
EREDSYS_EREDSYS_DISNEY_GUIDE_ENUM.name = "EREDSYS_DISNEY_GUIDE"
EREDSYS_EREDSYS_DISNEY_GUIDE_ENUM.index = 84
EREDSYS_EREDSYS_DISNEY_GUIDE_ENUM.number = 10601
EREDSYS_EREDSYS_FAVORITE_REWARD_ENUM.name = "EREDSYS_FAVORITE_REWARD"
EREDSYS_EREDSYS_FAVORITE_REWARD_ENUM.index = 85
EREDSYS_EREDSYS_FAVORITE_REWARD_ENUM.number = 10602
EREDSYS_EREDSYS_QUESTIONNAIRE_LOGIN_ENUM.name = "EREDSYS_QUESTIONNAIRE_LOGIN"
EREDSYS_EREDSYS_QUESTIONNAIRE_LOGIN_ENUM.index = 86
EREDSYS_EREDSYS_QUESTIONNAIRE_LOGIN_ENUM.number = 10604
EREDSYS_EREDSYS_DYNAMIC_UPDATE_ENUM.name = "EREDSYS_DYNAMIC_UPDATE"
EREDSYS_EREDSYS_DYNAMIC_UPDATE_ENUM.index = 87
EREDSYS_EREDSYS_DYNAMIC_UPDATE_ENUM.number = 10605
EREDSYS_EREDSYS_GLOBAL_DONATIONACTIVITY_ENUM.name = "EREDSYS_GLOBAL_DONATIONACTIVITY"
EREDSYS_EREDSYS_GLOBAL_DONATIONACTIVITY_ENUM.index = 88
EREDSYS_EREDSYS_GLOBAL_DONATIONACTIVITY_ENUM.number = 10606
EREDSYS_EREDSYS_FAMILY_REWARD_ENUM.name = "EREDSYS_FAMILY_REWARD"
EREDSYS_EREDSYS_FAMILY_REWARD_ENUM.index = 89
EREDSYS_EREDSYS_FAMILY_REWARD_ENUM.number = 10607
EREDSYS_EREDSYS_USERINVITE_INVITE_LOGIN_ENUM.name = "EREDSYS_USERINVITE_INVITE_LOGIN"
EREDSYS_EREDSYS_USERINVITE_INVITE_LOGIN_ENUM.index = 90
EREDSYS_EREDSYS_USERINVITE_INVITE_LOGIN_ENUM.number = 10608
EREDSYS_EREDSYS_USERINVITE_RECALL_LOGIN_ENUM.name = "EREDSYS_USERINVITE_RECALL_LOGIN"
EREDSYS_EREDSYS_USERINVITE_RECALL_LOGIN_ENUM.index = 91
EREDSYS_EREDSYS_USERINVITE_RECALL_LOGIN_ENUM.number = 10609
EREDSYS_EREDSYS_USERRETURN_QUEST_AWARD_ENUM.name = "EREDSYS_USERRETURN_QUEST_AWARD"
EREDSYS_EREDSYS_USERRETURN_QUEST_AWARD_ENUM.index = 92
EREDSYS_EREDSYS_USERRETURN_QUEST_AWARD_ENUM.number = 10610
EREDSYS_EREDSYS_USERRETURN_LOGIN_AWARD_ENUM.name = "EREDSYS_USERRETURN_LOGIN_AWARD"
EREDSYS_EREDSYS_USERRETURN_LOGIN_AWARD_ENUM.index = 93
EREDSYS_EREDSYS_USERRETURN_LOGIN_AWARD_ENUM.number = 10612
EREDSYS_EREDSYS_SIGNACTIVITY_NOVICE_ENUM.name = "EREDSYS_SIGNACTIVITY_NOVICE"
EREDSYS_EREDSYS_SIGNACTIVITY_NOVICE_ENUM.index = 94
EREDSYS_EREDSYS_SIGNACTIVITY_NOVICE_ENUM.number = 10615
EREDSYS_EREDSYS_SIGNACTIVITY_NORMAL_ENUM.name = "EREDSYS_SIGNACTIVITY_NORMAL"
EREDSYS_EREDSYS_SIGNACTIVITY_NORMAL_ENUM.index = 95
EREDSYS_EREDSYS_SIGNACTIVITY_NORMAL_ENUM.number = 10616
EREDSYS_EREDSYS_NOVICE_BP_ENUM.name = "EREDSYS_NOVICE_BP"
EREDSYS_EREDSYS_NOVICE_BP_ENUM.index = 96
EREDSYS_EREDSYS_NOVICE_BP_ENUM.number = 10700
EREDSYS_EREDSYS_TECHTREE_PRODUCE_ENUM.name = "EREDSYS_TECHTREE_PRODUCE"
EREDSYS_EREDSYS_TECHTREE_PRODUCE_ENUM.index = 97
EREDSYS_EREDSYS_TECHTREE_PRODUCE_ENUM.number = 10711
EREDSYS_EREDSYS_PVERAID_ENTRANCE_ENUM.name = "EREDSYS_PVERAID_ENTRANCE"
EREDSYS_EREDSYS_PVERAID_ENTRANCE_ENUM.index = 98
EREDSYS_EREDSYS_PVERAID_ENTRANCE_ENUM.number = 10712
EREDSYS_EREDSYS_GUILD_ASSEMBLY_AWARD_ENUM.name = "EREDSYS_GUILD_ASSEMBLY_AWARD"
EREDSYS_EREDSYS_GUILD_ASSEMBLY_AWARD_ENUM.index = 99
EREDSYS_EREDSYS_GUILD_ASSEMBLY_AWARD_ENUM.number = 10713
EREDSYS_EREDSYS_GUILD_ASSEMBLY_ACTIVITY_NTF_ENUM.name = "EREDSYS_GUILD_ASSEMBLY_ACTIVITY_NTF"
EREDSYS_EREDSYS_GUILD_ASSEMBLY_ACTIVITY_NTF_ENUM.index = 100
EREDSYS_EREDSYS_GUILD_ASSEMBLY_ACTIVITY_NTF_ENUM.number = 10714
EREDSYS_EREDSYS_TECHTREE_LEVEL_AWARD_ENUM.name = "EREDSYS_TECHTREE_LEVEL_AWARD"
EREDSYS_EREDSYS_TECHTREE_LEVEL_AWARD_ENUM.index = 101
EREDSYS_EREDSYS_TECHTREE_LEVEL_AWARD_ENUM.number = 10715
EREDSYS_EREDSYS_PVERAID_ACHIEVE_ENUM.name = "EREDSYS_PVERAID_ACHIEVE"
EREDSYS_EREDSYS_PVERAID_ACHIEVE_ENUM.index = 102
EREDSYS_EREDSYS_PVERAID_ACHIEVE_ENUM.number = 10716
EREDSYS_EREDSYS_RETURNINVITE_AWARD_ENUM.name = "EREDSYS_RETURNINVITE_AWARD"
EREDSYS_EREDSYS_RETURNINVITE_AWARD_ENUM.index = 103
EREDSYS_EREDSYS_RETURNINVITE_AWARD_ENUM.number = 10717
EREDSYS_EREDSYS_LOTTERY_BANNER_ENUM.name = "EREDSYS_LOTTERY_BANNER"
EREDSYS_EREDSYS_LOTTERY_BANNER_ENUM.index = 104
EREDSYS_EREDSYS_LOTTERY_BANNER_ENUM.number = 10718
EREDSYS_EREDSYS_LOTTERY_ACTIVITY_ENUM.name = "EREDSYS_LOTTERY_ACTIVITY"
EREDSYS_EREDSYS_LOTTERY_ACTIVITY_ENUM.index = 105
EREDSYS_EREDSYS_LOTTERY_ACTIVITY_ENUM.number = 10719
EREDSYS_EREDSYS_STRENGTH_ACCUMULATE_REWARD_ENUM.name = "EREDSYS_STRENGTH_ACCUMULATE_REWARD"
EREDSYS_EREDSYS_STRENGTH_ACCUMULATE_REWARD_ENUM.index = 106
EREDSYS_EREDSYS_STRENGTH_ACCUMULATE_REWARD_ENUM.number = 10720
EREDSYS_EREDSYS_FIRST_DEPOSIT_ENUM.name = "EREDSYS_FIRST_DEPOSIT"
EREDSYS_EREDSYS_FIRST_DEPOSIT_ENUM.index = 107
EREDSYS_EREDSYS_FIRST_DEPOSIT_ENUM.number = 10721
EREDSYS_EREDSYS_SERVANT_CHALLENGE_ENUM.name = "EREDSYS_SERVANT_CHALLENGE"
EREDSYS_EREDSYS_SERVANT_CHALLENGE_ENUM.index = 108
EREDSYS_EREDSYS_SERVANT_CHALLENGE_ENUM.number = 10722
EREDSYS_EREDSYS_BATTLE_FUND_ENUM.name = "EREDSYS_BATTLE_FUND"
EREDSYS_EREDSYS_BATTLE_FUND_ENUM.index = 109
EREDSYS_EREDSYS_BATTLE_FUND_ENUM.number = 10723
EREDSYS_EREDSYS_NEWBIETECHTREE_LEVEL_AWARD_ENUM.name = "EREDSYS_NEWBIETECHTREE_LEVEL_AWARD"
EREDSYS_EREDSYS_NEWBIETECHTREE_LEVEL_AWARD_ENUM.index = 110
EREDSYS_EREDSYS_NEWBIETECHTREE_LEVEL_AWARD_ENUM.number = 10724
EREDSYS_EREDSYS_GLOBAL_RECOMMEND_ENUM.name = "EREDSYS_GLOBAL_RECOMMEND"
EREDSYS_EREDSYS_GLOBAL_RECOMMEND_ENUM.index = 111
EREDSYS_EREDSYS_GLOBAL_RECOMMEND_ENUM.number = 10725
EREDSYS_EREDSYS_GLOBAL_NEWPARTNER_ENUM.name = "EREDSYS_GLOBAL_NEWPARTNER"
EREDSYS_EREDSYS_GLOBAL_NEWPARTNER_ENUM.index = 112
EREDSYS_EREDSYS_GLOBAL_NEWPARTNER_ENUM.number = 10726
EREDSYS_EREDSYS_RETURN_BP_ENUM.name = "EREDSYS_RETURN_BP"
EREDSYS_EREDSYS_RETURN_BP_ENUM.index = 113
EREDSYS_EREDSYS_RETURN_BP_ENUM.number = 10728
EREDSYS_EREDSYS_QUESTHERO_ENUM.name = "EREDSYS_QUESTHERO"
EREDSYS_EREDSYS_QUESTHERO_ENUM.index = 114
EREDSYS_EREDSYS_QUESTHERO_ENUM.number = 10730
EREDSYS_EREDSYS_LOTTERY_DAILY_REWARD_ENUM.name = "EREDSYS_LOTTERY_DAILY_REWARD"
EREDSYS_EREDSYS_LOTTERY_DAILY_REWARD_ENUM.index = 115
EREDSYS_EREDSYS_LOTTERY_DAILY_REWARD_ENUM.number = 10731
EREDSYS_EREDSYS_LOTTERY_FREE_ENUM.name = "EREDSYS_LOTTERY_FREE"
EREDSYS_EREDSYS_LOTTERY_FREE_ENUM.index = 116
EREDSYS_EREDSYS_LOTTERY_FREE_ENUM.number = 10732
EREDSYS_EREDSYS_ACCUM_DEPOSIT_ENUM.name = "EREDSYS_ACCUM_DEPOSIT"
EREDSYS_EREDSYS_ACCUM_DEPOSIT_ENUM.index = 117
EREDSYS_EREDSYS_ACCUM_DEPOSIT_ENUM.number = 10733
EREDSYS_EREDSYS_BOLI_GOLD_ENUM.name = "EREDSYS_BOLI_GOLD"
EREDSYS_EREDSYS_BOLI_GOLD_ENUM.index = 118
EREDSYS_EREDSYS_BOLI_GOLD_ENUM.number = 10734
EREDSYS_EREDSYS_NEW_TOPIC_ENUM.name = "EREDSYS_NEW_TOPIC"
EREDSYS_EREDSYS_NEW_TOPIC_ENUM.index = 119
EREDSYS_EREDSYS_NEW_TOPIC_ENUM.number = 10735
EREDSYS_EREDSYS_NEW_TOPIC_REWARD_ENUM.name = "EREDSYS_NEW_TOPIC_REWARD"
EREDSYS_EREDSYS_NEW_TOPIC_REWARD_ENUM.index = 120
EREDSYS_EREDSYS_NEW_TOPIC_REWARD_ENUM.number = 10737
EREDSYS_EREDSYS_PROFESSION_BRANCH_ENUM.name = "EREDSYS_PROFESSION_BRANCH"
EREDSYS_EREDSYS_PROFESSION_BRANCH_ENUM.index = 121
EREDSYS_EREDSYS_PROFESSION_BRANCH_ENUM.number = 10738
EREDSYS_EREDSYS_GIFT_TIME_LIMIT_ENUM.name = "EREDSYS_GIFT_TIME_LIMIT"
EREDSYS_EREDSYS_GIFT_TIME_LIMIT_ENUM.index = 122
EREDSYS_EREDSYS_GIFT_TIME_LIMIT_ENUM.number = 10739
EREDSYS_EREDSYS_HEROSHOP_ENUM.name = "EREDSYS_HEROSHOP"
EREDSYS_EREDSYS_HEROSHOP_ENUM.index = 123
EREDSYS_EREDSYS_HEROSHOP_ENUM.number = 10740
EREDSYS_EREDSYS_NOVICE_CHARGE_ENUM.name = "EREDSYS_NOVICE_CHARGE"
EREDSYS_EREDSYS_NOVICE_CHARGE_ENUM.index = 124
EREDSYS_EREDSYS_NOVICE_CHARGE_ENUM.number = 10741
EREDSYS_EREDSYS_ANNIVERSARY_LIVE_ENUM.name = "EREDSYS_ANNIVERSARY_LIVE"
EREDSYS_EREDSYS_ANNIVERSARY_LIVE_ENUM.index = 125
EREDSYS_EREDSYS_ANNIVERSARY_LIVE_ENUM.number = 10742
EREDSYS_EREDSYS_ACT_BP_ENUM.name = "EREDSYS_ACT_BP"
EREDSYS_EREDSYS_ACT_BP_ENUM.index = 126
EREDSYS_EREDSYS_ACT_BP_ENUM.number = 10744
EREDSYS_EREDSYS_HERO_GROWTH_QUEST_ENUM.name = "EREDSYS_HERO_GROWTH_QUEST"
EREDSYS_EREDSYS_HERO_GROWTH_QUEST_ENUM.index = 127
EREDSYS_EREDSYS_HERO_GROWTH_QUEST_ENUM.number = 10745
EREDSYS_EREDSYS_HERO_STORY_QUEST_ENUM.name = "EREDSYS_HERO_STORY_QUEST"
EREDSYS_EREDSYS_HERO_STORY_QUEST_ENUM.index = 128
EREDSYS_EREDSYS_HERO_STORY_QUEST_ENUM.number = 10746
EREDSYS_EREDSYS_GLOBAL_ACT_REWARD_ENUM.name = "EREDSYS_GLOBAL_ACT_REWARD"
EREDSYS_EREDSYS_GLOBAL_ACT_REWARD_ENUM.index = 129
EREDSYS_EREDSYS_GLOBAL_ACT_REWARD_ENUM.number = 10752
EREDSYS_EREDSYS_EVENT_ACT_REWARD_ENUM.name = "EREDSYS_EVENT_ACT_REWARD"
EREDSYS_EREDSYS_EVENT_ACT_REWARD_ENUM.index = 130
EREDSYS_EREDSYS_EVENT_ACT_REWARD_ENUM.number = 10753
EREDSYS_EREDSYS_HOME_GIFT_BOX_ENUM.name = "EREDSYS_HOME_GIFT_BOX"
EREDSYS_EREDSYS_HOME_GIFT_BOX_ENUM.index = 131
EREDSYS_EREDSYS_HOME_GIFT_BOX_ENUM.number = 10758
EREDSYS_EREDSYS_NEW_SERVER_CHALLENGE_ENUM.name = "EREDSYS_NEW_SERVER_CHALLENGE"
EREDSYS_EREDSYS_NEW_SERVER_CHALLENGE_ENUM.index = 132
EREDSYS_EREDSYS_NEW_SERVER_CHALLENGE_ENUM.number = 10759
EREDSYS_EREDSYS_PRESTIGE_SYSTEM_REWARD_ENUM.name = "EREDSYS_PRESTIGE_SYSTEM_REWARD"
EREDSYS_EREDSYS_PRESTIGE_SYSTEM_REWARD_ENUM.index = 133
EREDSYS_EREDSYS_PRESTIGE_SYSTEM_REWARD_ENUM.number = 10760
EREDSYS_EREDSYS_NEW_YEAR_MEMORY_ENUM.name = "EREDSYS_NEW_YEAR_MEMORY"
EREDSYS_EREDSYS_NEW_YEAR_MEMORY_ENUM.index = 134
EREDSYS_EREDSYS_NEW_YEAR_MEMORY_ENUM.number = 10762
EREDSYS_EREDSYS_MISSION_REWARD_ENUM.name = "EREDSYS_MISSION_REWARD"
EREDSYS_EREDSYS_MISSION_REWARD_ENUM.index = 135
EREDSYS_EREDSYS_MISSION_REWARD_ENUM.number = 10766
EREDSYS_EREDSYS_MAX_ENUM.name = "EREDSYS_MAX"
EREDSYS_EREDSYS_MAX_ENUM.index = 136
EREDSYS_EREDSYS_MAX_ENUM.number = 10767
EREDSYS.name = "ERedSys"
EREDSYS.full_name = ".Cmd.ERedSys"
EREDSYS.values = {
  EREDSYS_EREDSYS_MIN_ENUM,
  EREDSYS_EREDSYS_ADD_POINT_ENUM,
  EREDSYS_EREDSYS_NEW_PROFESSION_ENUM,
  EREDSYS_EREDSYS_PROFESSION_UP_ENUM,
  EREDSYS_EREDSYS_ROLE_IMG_ENUM,
  EREDSYS_EREDSYS_MONSTER_IMG_ENUM,
  EREDSYS_EREDSYS_PHOTOFRAME_ENUM,
  EREDSYS_EREDSYS_SKILL_POINT_ENUM,
  EREDSYS_EREDSYS_FOURTH_SKILL_POINT_ENUM,
  EREDSYS_EREDSYS_TEAMAPPLY_ENUM,
  EREDSYS_EREDSYS_MANUAL_MONSTER_ENUM,
  EREDSYS_EREDSYS_MANUAL_HEAD_ENUM,
  EREDSYS_EREDSYS_MANUAL_FACE_ENUM,
  EREDSYS_EREDSYS_MANUAL_BACK_ENUM,
  EREDSYS_EREDSYS_MANUAL_TAIL_ENUM,
  EREDSYS_EREDSYS_MANUAL_CARD_WEAPON_ENUM,
  EREDSYS_EREDSYS_MANUAL_CARD_ASSISTANT_ENUM,
  EREDSYS_EREDSYS_MANUAL_CARD_ARMOUR_ENUM,
  EREDSYS_EREDSYS_MANUAL_CARD_ROBE_ENUM,
  EREDSYS_EREDSYS_MANUAL_CARD_SHOES_ENUM,
  EREDSYS_EREDSYS_MANUAL_CARD_ACCESSORY_ENUM,
  EREDSYS_EREDSYS_MANUAL_CARD_HEAD_ENUM,
  EREDSYS_EREDSYS_MANUAL_NPC_ENUM,
  EREDSYS_EREDSYS_MANUAL_MOUNT_ENUM,
  EREDSYS_EREDSYS_SOCIAL_FRIEND_APPLY_ENUM,
  EREDSYS_EREDSYS_MANUAL_MONTHCARD_ENUM,
  EREDSYS_EREDSYS_MANUAL_NEWTAIL_ENUM,
  EREDSYS_EREDSYS_MANUAL_COLLECTION_ENUM,
  EREDSYS_EREDSYS_MANUAL_FOOD_ENUM,
  EREDSYS_EREDSYS_GUILD_APPLY_ENUM,
  EREDSYS_EREDSYS_GUILD_CHALLENGE_ADD_ENUM,
  EREDSYS_EREDSYS_GUILD_CHALLENGE_REWARD_ENUM,
  EREDSYS_EREDSYS_GUILD_ICON_ENUM,
  EREDSYS_EREDSYS_PUZZLE_ENUM,
  EREDSYS_EREDSYS_PRIVATE_CHAT_ENUM,
  EREDSYS_EREDSYS_MONSTER_PORTRAIT_ENUM,
  EREDSYS_EREDSYS_PORTRAIT_FRAME_ENUM,
  EREDSYS_EREDSYS_BACKGROUND_FRAME_ENUM,
  EREDSYS_EREDSYS_CHAT_FRAME_ENUM,
  EREDSYS_EREDSYS_TRADE_RECORD_ENUM,
  EREDSYS_EREDSYS_PET_ADVENTURE_ENUM,
  EREDSYS_EREDSYS_TUTOR_TUTOR_UNLOCK_ENUM,
  EREDSYS_EREDSYS_TUTOR_STUDENT_UNLOCK_ENUM,
  EREDSYS_EREDSYS_TUTOR_APPLY_ENUM,
  EREDSYS_EREDSYS_TUTOR_TASK_ENUM,
  EREDSYS_EREDSYS_TUTOR_GROW_REWARD_ENUM,
  EREDSYS_EREDSYS_TUTOR_BOX_ENUM,
  EREDSYS_EREDSYS_WALLET_ENUM,
  EREDSYS_EREDSYS_WALLET_TYPE_PAGE_ENUM,
  EREDSYS_EREDSYS_MANUAL_PRONTERA_ENUM,
  EREDSYS_EREDSYS_MANUAL_GEFFEN_ENUM,
  EREDSYS_EREDSYS_MANUAL_MOROCC_ENUM,
  EREDSYS_EREDSYS_MANUAL_PAYON_ENUM,
  EREDSYS_EREDSYS_MANUAL_GLAST_ENUM,
  EREDSYS_EREDSYS_PACK_TEMP_ENUM,
  EREDSYS_EREDSYS_AUCTION_RECORD_ENUM,
  EREDSYS_EREDSYS_PEAK_LEVEL_ENUM,
  EREDSYS_EREDSYS_BEING_BODY_ENUM,
  EREDSYS_EREDSYS_FUNCTION_OPENING_ENUM,
  EREDSYS_EREDSYS_SERVANT_RECOMMNED_ENUM,
  EREDSYS_EREDSYS_SERVANT_GROWTH_ENUM,
  EREDSYS_EREDSYS_SERVANT_GROWTH_STEP_ENUM,
  EREDSYS_EREDSYS_SERVANT_GROWTH_EP_ENUM,
  EREDSYS_EREDSYS_SERVANT_GROWTH_TIME_ENUM,
  EREDSYS_EREDSYS_SERVANT_RECOMMNED_DAY_ENUM,
  EREDSYS_EREDSYS_SERVANT_RECOMMNED_WEEK_ENUM,
  EREDSYS_EREDSYS_SERVANT_RECOMMNED_FOREVER_ENUM,
  EREDSYS_EREDSYS_SERVANT_RECOMMNED_SHORTCUT_ENUM,
  EREDSYS_EREDSYS_DEAD_BOSS_ENUM,
  EREDSYS_EREDSYS_SIGNIN_DAY_ENUM,
  EREDSYS_EREDSYS_SIGNIN_ACTIVITY_ENUM,
  EREDSYS_EREDSYS_ACT_HITPOLLY_QUEST_ENUM,
  EREDSYS_EREDSYS_PAY_SIGN_BUY_ENUM,
  EREDSYS_EREDSYS_PAY_SIGN_REWARD_ENUM,
  EREDSYS_EREDSYS_GROUPON_LOGIN_ENUM,
  EREDSYS_EREDSYS_GROUPON_PROGRESS_ENUM,
  EREDSYS_EREDSYS_QUESTPUZZLE_CANLOCK_ENUM,
  EREDSYS_EREDSYS_NOVICE_TARGET_ENUM,
  EREDSYS_EREDSYS_MANOR_PARTNER_STORY_ENUM,
  EREDSYS_EREDSYS_SECRET_ENLIGHT_ENUM,
  EREDSYS_EREDSYS_MANUAL_GOAL_ENUM,
  EREDSYS_EREDSYS_MINIRO_DICE_ENUM,
  EREDSYS_EREDSYS_NOVICE_NOTEBOOK_ENUM,
  EREDSYS_EREDSYS_SHOP_BUY_NOTIFY_ENUM,
  EREDSYS_EREDSYS_DISNEY_GUIDE_ENUM,
  EREDSYS_EREDSYS_FAVORITE_REWARD_ENUM,
  EREDSYS_EREDSYS_QUESTIONNAIRE_LOGIN_ENUM,
  EREDSYS_EREDSYS_DYNAMIC_UPDATE_ENUM,
  EREDSYS_EREDSYS_GLOBAL_DONATIONACTIVITY_ENUM,
  EREDSYS_EREDSYS_FAMILY_REWARD_ENUM,
  EREDSYS_EREDSYS_USERINVITE_INVITE_LOGIN_ENUM,
  EREDSYS_EREDSYS_USERINVITE_RECALL_LOGIN_ENUM,
  EREDSYS_EREDSYS_USERRETURN_QUEST_AWARD_ENUM,
  EREDSYS_EREDSYS_USERRETURN_LOGIN_AWARD_ENUM,
  EREDSYS_EREDSYS_SIGNACTIVITY_NOVICE_ENUM,
  EREDSYS_EREDSYS_SIGNACTIVITY_NORMAL_ENUM,
  EREDSYS_EREDSYS_NOVICE_BP_ENUM,
  EREDSYS_EREDSYS_TECHTREE_PRODUCE_ENUM,
  EREDSYS_EREDSYS_PVERAID_ENTRANCE_ENUM,
  EREDSYS_EREDSYS_GUILD_ASSEMBLY_AWARD_ENUM,
  EREDSYS_EREDSYS_GUILD_ASSEMBLY_ACTIVITY_NTF_ENUM,
  EREDSYS_EREDSYS_TECHTREE_LEVEL_AWARD_ENUM,
  EREDSYS_EREDSYS_PVERAID_ACHIEVE_ENUM,
  EREDSYS_EREDSYS_RETURNINVITE_AWARD_ENUM,
  EREDSYS_EREDSYS_LOTTERY_BANNER_ENUM,
  EREDSYS_EREDSYS_LOTTERY_ACTIVITY_ENUM,
  EREDSYS_EREDSYS_STRENGTH_ACCUMULATE_REWARD_ENUM,
  EREDSYS_EREDSYS_FIRST_DEPOSIT_ENUM,
  EREDSYS_EREDSYS_SERVANT_CHALLENGE_ENUM,
  EREDSYS_EREDSYS_BATTLE_FUND_ENUM,
  EREDSYS_EREDSYS_NEWBIETECHTREE_LEVEL_AWARD_ENUM,
  EREDSYS_EREDSYS_GLOBAL_RECOMMEND_ENUM,
  EREDSYS_EREDSYS_GLOBAL_NEWPARTNER_ENUM,
  EREDSYS_EREDSYS_RETURN_BP_ENUM,
  EREDSYS_EREDSYS_QUESTHERO_ENUM,
  EREDSYS_EREDSYS_LOTTERY_DAILY_REWARD_ENUM,
  EREDSYS_EREDSYS_LOTTERY_FREE_ENUM,
  EREDSYS_EREDSYS_ACCUM_DEPOSIT_ENUM,
  EREDSYS_EREDSYS_BOLI_GOLD_ENUM,
  EREDSYS_EREDSYS_NEW_TOPIC_ENUM,
  EREDSYS_EREDSYS_NEW_TOPIC_REWARD_ENUM,
  EREDSYS_EREDSYS_PROFESSION_BRANCH_ENUM,
  EREDSYS_EREDSYS_GIFT_TIME_LIMIT_ENUM,
  EREDSYS_EREDSYS_HEROSHOP_ENUM,
  EREDSYS_EREDSYS_NOVICE_CHARGE_ENUM,
  EREDSYS_EREDSYS_ANNIVERSARY_LIVE_ENUM,
  EREDSYS_EREDSYS_ACT_BP_ENUM,
  EREDSYS_EREDSYS_HERO_GROWTH_QUEST_ENUM,
  EREDSYS_EREDSYS_HERO_STORY_QUEST_ENUM,
  EREDSYS_EREDSYS_GLOBAL_ACT_REWARD_ENUM,
  EREDSYS_EREDSYS_EVENT_ACT_REWARD_ENUM,
  EREDSYS_EREDSYS_HOME_GIFT_BOX_ENUM,
  EREDSYS_EREDSYS_NEW_SERVER_CHALLENGE_ENUM,
  EREDSYS_EREDSYS_PRESTIGE_SYSTEM_REWARD_ENUM,
  EREDSYS_EREDSYS_NEW_YEAR_MEMORY_ENUM,
  EREDSYS_EREDSYS_MISSION_REWARD_ENUM,
  EREDSYS_EREDSYS_MAX_ENUM
}
ETIPOPT_ETIPOPT_MIN_ENUM.name = "ETIPOPT_MIN"
ETIPOPT_ETIPOPT_MIN_ENUM.index = 0
ETIPOPT_ETIPOPT_MIN_ENUM.number = 0
ETIPOPT_ETIPOPT_UPDATE_ENUM.name = "ETIPOPT_UPDATE"
ETIPOPT_ETIPOPT_UPDATE_ENUM.index = 1
ETIPOPT_ETIPOPT_UPDATE_ENUM.number = 1
ETIPOPT_ETIPOPT_DELETE_ENUM.name = "ETIPOPT_DELETE"
ETIPOPT_ETIPOPT_DELETE_ENUM.index = 2
ETIPOPT_ETIPOPT_DELETE_ENUM.number = 2
ETIPOPT.name = "ETipOpt"
ETIPOPT.full_name = ".Cmd.ETipOpt"
ETIPOPT.values = {
  ETIPOPT_ETIPOPT_MIN_ENUM,
  ETIPOPT_ETIPOPT_UPDATE_ENUM,
  ETIPOPT_ETIPOPT_DELETE_ENUM
}
ETIPITEMOPT_ETIPITEMOPT_ADD_ENUM.name = "ETIPITEMOPT_ADD"
ETIPITEMOPT_ETIPITEMOPT_ADD_ENUM.index = 0
ETIPITEMOPT_ETIPITEMOPT_ADD_ENUM.number = 1
ETIPITEMOPT_ETIPITEMOPT_DELETE_ENUM.name = "ETIPITEMOPT_DELETE"
ETIPITEMOPT_ETIPITEMOPT_DELETE_ENUM.index = 1
ETIPITEMOPT_ETIPITEMOPT_DELETE_ENUM.number = 2
ETIPITEMOPT.name = "ETipItemOpt"
ETIPITEMOPT.full_name = ".Cmd.ETipItemOpt"
ETIPITEMOPT.values = {
  ETIPITEMOPT_ETIPITEMOPT_ADD_ENUM,
  ETIPITEMOPT_ETIPITEMOPT_DELETE_ENUM
}
REDTIP_REDSYS_FIELD.name = "redsys"
REDTIP_REDSYS_FIELD.full_name = ".Cmd.RedTip.redsys"
REDTIP_REDSYS_FIELD.number = 1
REDTIP_REDSYS_FIELD.index = 0
REDTIP_REDSYS_FIELD.label = 1
REDTIP_REDSYS_FIELD.has_default_value = true
REDTIP_REDSYS_FIELD.default_value = 0
REDTIP_REDSYS_FIELD.enum_type = EREDSYS
REDTIP_REDSYS_FIELD.type = 14
REDTIP_REDSYS_FIELD.cpp_type = 8
REDTIP_OPTITEM_FIELD.name = "optItem"
REDTIP_OPTITEM_FIELD.full_name = ".Cmd.RedTip.optItem"
REDTIP_OPTITEM_FIELD.number = 2
REDTIP_OPTITEM_FIELD.index = 1
REDTIP_OPTITEM_FIELD.label = 1
REDTIP_OPTITEM_FIELD.has_default_value = true
REDTIP_OPTITEM_FIELD.default_value = 1
REDTIP_OPTITEM_FIELD.enum_type = ETIPITEMOPT
REDTIP_OPTITEM_FIELD.type = 14
REDTIP_OPTITEM_FIELD.cpp_type = 8
REDTIP_TIPID_FIELD.name = "tipid"
REDTIP_TIPID_FIELD.full_name = ".Cmd.RedTip.tipid"
REDTIP_TIPID_FIELD.number = 3
REDTIP_TIPID_FIELD.index = 2
REDTIP_TIPID_FIELD.label = 3
REDTIP_TIPID_FIELD.has_default_value = false
REDTIP_TIPID_FIELD.default_value = {}
REDTIP_TIPID_FIELD.type = 4
REDTIP_TIPID_FIELD.cpp_type = 4
REDTIP.name = "RedTip"
REDTIP.full_name = ".Cmd.RedTip"
REDTIP.nested_types = {}
REDTIP.enum_types = {}
REDTIP.fields = {
  REDTIP_REDSYS_FIELD,
  REDTIP_OPTITEM_FIELD,
  REDTIP_TIPID_FIELD
}
REDTIP.is_extendable = false
REDTIP.extensions = {}
GAMETIPCMD_CMD_FIELD.name = "cmd"
GAMETIPCMD_CMD_FIELD.full_name = ".Cmd.GameTipCmd.cmd"
GAMETIPCMD_CMD_FIELD.number = 1
GAMETIPCMD_CMD_FIELD.index = 0
GAMETIPCMD_CMD_FIELD.label = 1
GAMETIPCMD_CMD_FIELD.has_default_value = true
GAMETIPCMD_CMD_FIELD.default_value = 18
GAMETIPCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
GAMETIPCMD_CMD_FIELD.type = 14
GAMETIPCMD_CMD_FIELD.cpp_type = 8
GAMETIPCMD_PARAM_FIELD.name = "param"
GAMETIPCMD_PARAM_FIELD.full_name = ".Cmd.GameTipCmd.param"
GAMETIPCMD_PARAM_FIELD.number = 2
GAMETIPCMD_PARAM_FIELD.index = 1
GAMETIPCMD_PARAM_FIELD.label = 1
GAMETIPCMD_PARAM_FIELD.has_default_value = true
GAMETIPCMD_PARAM_FIELD.default_value = 1
GAMETIPCMD_PARAM_FIELD.enum_type = TIPPARAM
GAMETIPCMD_PARAM_FIELD.type = 14
GAMETIPCMD_PARAM_FIELD.cpp_type = 8
GAMETIPCMD_OPT_FIELD.name = "opt"
GAMETIPCMD_OPT_FIELD.full_name = ".Cmd.GameTipCmd.opt"
GAMETIPCMD_OPT_FIELD.number = 3
GAMETIPCMD_OPT_FIELD.index = 2
GAMETIPCMD_OPT_FIELD.label = 1
GAMETIPCMD_OPT_FIELD.has_default_value = true
GAMETIPCMD_OPT_FIELD.default_value = 0
GAMETIPCMD_OPT_FIELD.enum_type = ETIPOPT
GAMETIPCMD_OPT_FIELD.type = 14
GAMETIPCMD_OPT_FIELD.cpp_type = 8
GAMETIPCMD_REDTIP_FIELD.name = "redtip"
GAMETIPCMD_REDTIP_FIELD.full_name = ".Cmd.GameTipCmd.redtip"
GAMETIPCMD_REDTIP_FIELD.number = 4
GAMETIPCMD_REDTIP_FIELD.index = 3
GAMETIPCMD_REDTIP_FIELD.label = 3
GAMETIPCMD_REDTIP_FIELD.has_default_value = false
GAMETIPCMD_REDTIP_FIELD.default_value = {}
GAMETIPCMD_REDTIP_FIELD.message_type = REDTIP
GAMETIPCMD_REDTIP_FIELD.type = 11
GAMETIPCMD_REDTIP_FIELD.cpp_type = 10
GAMETIPCMD.name = "GameTipCmd"
GAMETIPCMD.full_name = ".Cmd.GameTipCmd"
GAMETIPCMD.nested_types = {}
GAMETIPCMD.enum_types = {}
GAMETIPCMD.fields = {
  GAMETIPCMD_CMD_FIELD,
  GAMETIPCMD_PARAM_FIELD,
  GAMETIPCMD_OPT_FIELD,
  GAMETIPCMD_REDTIP_FIELD
}
GAMETIPCMD.is_extendable = false
GAMETIPCMD.extensions = {}
BROWSEREDTIPCMD_CMD_FIELD.name = "cmd"
BROWSEREDTIPCMD_CMD_FIELD.full_name = ".Cmd.BrowseRedTipCmd.cmd"
BROWSEREDTIPCMD_CMD_FIELD.number = 1
BROWSEREDTIPCMD_CMD_FIELD.index = 0
BROWSEREDTIPCMD_CMD_FIELD.label = 1
BROWSEREDTIPCMD_CMD_FIELD.has_default_value = true
BROWSEREDTIPCMD_CMD_FIELD.default_value = 18
BROWSEREDTIPCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
BROWSEREDTIPCMD_CMD_FIELD.type = 14
BROWSEREDTIPCMD_CMD_FIELD.cpp_type = 8
BROWSEREDTIPCMD_PARAM_FIELD.name = "param"
BROWSEREDTIPCMD_PARAM_FIELD.full_name = ".Cmd.BrowseRedTipCmd.param"
BROWSEREDTIPCMD_PARAM_FIELD.number = 2
BROWSEREDTIPCMD_PARAM_FIELD.index = 1
BROWSEREDTIPCMD_PARAM_FIELD.label = 1
BROWSEREDTIPCMD_PARAM_FIELD.has_default_value = true
BROWSEREDTIPCMD_PARAM_FIELD.default_value = 2
BROWSEREDTIPCMD_PARAM_FIELD.enum_type = TIPPARAM
BROWSEREDTIPCMD_PARAM_FIELD.type = 14
BROWSEREDTIPCMD_PARAM_FIELD.cpp_type = 8
BROWSEREDTIPCMD_RED_FIELD.name = "red"
BROWSEREDTIPCMD_RED_FIELD.full_name = ".Cmd.BrowseRedTipCmd.red"
BROWSEREDTIPCMD_RED_FIELD.number = 3
BROWSEREDTIPCMD_RED_FIELD.index = 2
BROWSEREDTIPCMD_RED_FIELD.label = 1
BROWSEREDTIPCMD_RED_FIELD.has_default_value = true
BROWSEREDTIPCMD_RED_FIELD.default_value = 0
BROWSEREDTIPCMD_RED_FIELD.enum_type = EREDSYS
BROWSEREDTIPCMD_RED_FIELD.type = 14
BROWSEREDTIPCMD_RED_FIELD.cpp_type = 8
BROWSEREDTIPCMD_TIPID_FIELD.name = "tipid"
BROWSEREDTIPCMD_TIPID_FIELD.full_name = ".Cmd.BrowseRedTipCmd.tipid"
BROWSEREDTIPCMD_TIPID_FIELD.number = 4
BROWSEREDTIPCMD_TIPID_FIELD.index = 3
BROWSEREDTIPCMD_TIPID_FIELD.label = 1
BROWSEREDTIPCMD_TIPID_FIELD.has_default_value = true
BROWSEREDTIPCMD_TIPID_FIELD.default_value = 0
BROWSEREDTIPCMD_TIPID_FIELD.type = 4
BROWSEREDTIPCMD_TIPID_FIELD.cpp_type = 4
BROWSEREDTIPCMD.name = "BrowseRedTipCmd"
BROWSEREDTIPCMD.full_name = ".Cmd.BrowseRedTipCmd"
BROWSEREDTIPCMD.nested_types = {}
BROWSEREDTIPCMD.enum_types = {}
BROWSEREDTIPCMD.fields = {
  BROWSEREDTIPCMD_CMD_FIELD,
  BROWSEREDTIPCMD_PARAM_FIELD,
  BROWSEREDTIPCMD_RED_FIELD,
  BROWSEREDTIPCMD_TIPID_FIELD
}
BROWSEREDTIPCMD.is_extendable = false
BROWSEREDTIPCMD.extensions = {}
ADDREDTIP_CMD_FIELD.name = "cmd"
ADDREDTIP_CMD_FIELD.full_name = ".Cmd.AddRedTip.cmd"
ADDREDTIP_CMD_FIELD.number = 1
ADDREDTIP_CMD_FIELD.index = 0
ADDREDTIP_CMD_FIELD.label = 1
ADDREDTIP_CMD_FIELD.has_default_value = true
ADDREDTIP_CMD_FIELD.default_value = 18
ADDREDTIP_CMD_FIELD.enum_type = XCMD_PB_COMMAND
ADDREDTIP_CMD_FIELD.type = 14
ADDREDTIP_CMD_FIELD.cpp_type = 8
ADDREDTIP_PARAM_FIELD.name = "param"
ADDREDTIP_PARAM_FIELD.full_name = ".Cmd.AddRedTip.param"
ADDREDTIP_PARAM_FIELD.number = 2
ADDREDTIP_PARAM_FIELD.index = 1
ADDREDTIP_PARAM_FIELD.label = 1
ADDREDTIP_PARAM_FIELD.has_default_value = true
ADDREDTIP_PARAM_FIELD.default_value = 3
ADDREDTIP_PARAM_FIELD.enum_type = TIPPARAM
ADDREDTIP_PARAM_FIELD.type = 14
ADDREDTIP_PARAM_FIELD.cpp_type = 8
ADDREDTIP_RED_FIELD.name = "red"
ADDREDTIP_RED_FIELD.full_name = ".Cmd.AddRedTip.red"
ADDREDTIP_RED_FIELD.number = 3
ADDREDTIP_RED_FIELD.index = 2
ADDREDTIP_RED_FIELD.label = 1
ADDREDTIP_RED_FIELD.has_default_value = true
ADDREDTIP_RED_FIELD.default_value = 0
ADDREDTIP_RED_FIELD.enum_type = EREDSYS
ADDREDTIP_RED_FIELD.type = 14
ADDREDTIP_RED_FIELD.cpp_type = 8
ADDREDTIP_TIPID_FIELD.name = "tipid"
ADDREDTIP_TIPID_FIELD.full_name = ".Cmd.AddRedTip.tipid"
ADDREDTIP_TIPID_FIELD.number = 4
ADDREDTIP_TIPID_FIELD.index = 3
ADDREDTIP_TIPID_FIELD.label = 1
ADDREDTIP_TIPID_FIELD.has_default_value = true
ADDREDTIP_TIPID_FIELD.default_value = 0
ADDREDTIP_TIPID_FIELD.type = 4
ADDREDTIP_TIPID_FIELD.cpp_type = 4
ADDREDTIP.name = "AddRedTip"
ADDREDTIP.full_name = ".Cmd.AddRedTip"
ADDREDTIP.nested_types = {}
ADDREDTIP.enum_types = {}
ADDREDTIP.fields = {
  ADDREDTIP_CMD_FIELD,
  ADDREDTIP_PARAM_FIELD,
  ADDREDTIP_RED_FIELD,
  ADDREDTIP_TIPID_FIELD
}
ADDREDTIP.is_extendable = false
ADDREDTIP.extensions = {}
AddRedTip = protobuf.Message(ADDREDTIP)
BrowseRedTipCmd = protobuf.Message(BROWSEREDTIPCMD)
EREDSYS_ACCUM_DEPOSIT = 10733
EREDSYS_ACT_BP = 10744
EREDSYS_ACT_HITPOLLY_QUEST = 702
EREDSYS_ADD_POINT = 1
EREDSYS_ANNIVERSARY_LIVE = 10742
EREDSYS_AUCTION_RECORD = 84
EREDSYS_BACKGROUND_FRAME = 53
EREDSYS_BATTLE_FUND = 10723
EREDSYS_BEING_BODY = 300
EREDSYS_BOLI_GOLD = 10734
EREDSYS_CHAT_FRAME = 54
EREDSYS_DEAD_BOSS = 600
EREDSYS_DISNEY_GUIDE = 10601
EREDSYS_DYNAMIC_UPDATE = 10605
EREDSYS_EVENT_ACT_REWARD = 10753
EREDSYS_FAMILY_REWARD = 10607
EREDSYS_FAVORITE_REWARD = 10602
EREDSYS_FIRST_DEPOSIT = 10721
EREDSYS_FOURTH_SKILL_POINT = 8
EREDSYS_FUNCTION_OPENING = 310
EREDSYS_GIFT_TIME_LIMIT = 10739
EREDSYS_GLOBAL_ACT_REWARD = 10752
EREDSYS_GLOBAL_DONATIONACTIVITY = 10606
EREDSYS_GLOBAL_NEWPARTNER = 10726
EREDSYS_GLOBAL_RECOMMEND = 10725
EREDSYS_GROUPON_LOGIN = 705
EREDSYS_GROUPON_PROGRESS = 706
EREDSYS_GUILD_APPLY = 40
EREDSYS_GUILD_ASSEMBLY_ACTIVITY_NTF = 10714
EREDSYS_GUILD_ASSEMBLY_AWARD = 10713
EREDSYS_GUILD_CHALLENGE_ADD = 41
EREDSYS_GUILD_CHALLENGE_REWARD = 42
EREDSYS_GUILD_ICON = 43
EREDSYS_HEROSHOP = 10740
EREDSYS_HERO_GROWTH_QUEST = 10745
EREDSYS_HERO_STORY_QUEST = 10746
EREDSYS_HOME_GIFT_BOX = 10758
EREDSYS_LOTTERY_ACTIVITY = 10719
EREDSYS_LOTTERY_BANNER = 10718
EREDSYS_LOTTERY_DAILY_REWARD = 10731
EREDSYS_LOTTERY_FREE = 10732
EREDSYS_MANOR_PARTNER_STORY = 709
EREDSYS_MANUAL_BACK = 23
EREDSYS_MANUAL_CARD_ACCESSORY = 30
EREDSYS_MANUAL_CARD_ARMOUR = 27
EREDSYS_MANUAL_CARD_ASSISTANT = 26
EREDSYS_MANUAL_CARD_HEAD = 31
EREDSYS_MANUAL_CARD_ROBE = 28
EREDSYS_MANUAL_CARD_SHOES = 29
EREDSYS_MANUAL_CARD_WEAPON = 25
EREDSYS_MANUAL_COLLECTION = 37
EREDSYS_MANUAL_FACE = 22
EREDSYS_MANUAL_FOOD = 38
EREDSYS_MANUAL_GEFFEN = 102
EREDSYS_MANUAL_GLAST = 105
EREDSYS_MANUAL_GOAL = 10100
EREDSYS_MANUAL_HEAD = 21
EREDSYS_MANUAL_MONSTER = 20
EREDSYS_MANUAL_MONTHCARD = 35
EREDSYS_MANUAL_MOROCC = 103
EREDSYS_MANUAL_MOUNT = 33
EREDSYS_MANUAL_NEWTAIL = 36
EREDSYS_MANUAL_NPC = 32
EREDSYS_MANUAL_PAYON = 104
EREDSYS_MANUAL_PRONTERA = 101
EREDSYS_MANUAL_TAIL = 24
EREDSYS_MAX = 10767
EREDSYS_MIN = 0
EREDSYS_MINIRO_DICE = 10400
EREDSYS_MISSION_REWARD = 10766
EREDSYS_MONSTER_IMG = 5
EREDSYS_MONSTER_PORTRAIT = 51
EREDSYS_NEWBIETECHTREE_LEVEL_AWARD = 10724
EREDSYS_NEW_PROFESSION = 2
EREDSYS_NEW_SERVER_CHALLENGE = 10759
EREDSYS_NEW_TOPIC = 10735
EREDSYS_NEW_TOPIC_REWARD = 10737
EREDSYS_NEW_YEAR_MEMORY = 10762
EREDSYS_NOVICE_BP = 10700
EREDSYS_NOVICE_CHARGE = 10741
EREDSYS_NOVICE_NOTEBOOK = 10410
EREDSYS_NOVICE_TARGET = 708
EREDSYS_PACK_TEMP = 106
EREDSYS_PAY_SIGN_BUY = 703
EREDSYS_PAY_SIGN_REWARD = 704
EREDSYS_PEAK_LEVEL = 132
EREDSYS_PET_ADVENTURE = 70
EREDSYS_PHOTOFRAME = 6
EREDSYS_PORTRAIT_FRAME = 52
EREDSYS_PRESTIGE_SYSTEM_REWARD = 10760
EREDSYS_PRIVATE_CHAT = 50
EREDSYS_PROFESSION_BRANCH = 10738
EREDSYS_PROFESSION_UP = 3
EREDSYS_PUZZLE = 45
EREDSYS_PVERAID_ACHIEVE = 10716
EREDSYS_PVERAID_ENTRANCE = 10712
EREDSYS_QUESTHERO = 10730
EREDSYS_QUESTIONNAIRE_LOGIN = 10604
EREDSYS_QUESTPUZZLE_CANLOCK = 707
EREDSYS_RETURNINVITE_AWARD = 10717
EREDSYS_RETURN_BP = 10728
EREDSYS_ROLE_IMG = 4
EREDSYS_SECRET_ENLIGHT = 710
EREDSYS_SERVANT_CHALLENGE = 10722
EREDSYS_SERVANT_GROWTH = 401
EREDSYS_SERVANT_GROWTH_EP = 403
EREDSYS_SERVANT_GROWTH_STEP = 402
EREDSYS_SERVANT_GROWTH_TIME = 404
EREDSYS_SERVANT_RECOMMNED = 400
EREDSYS_SERVANT_RECOMMNED_DAY = 410
EREDSYS_SERVANT_RECOMMNED_FOREVER = 412
EREDSYS_SERVANT_RECOMMNED_SHORTCUT = 413
EREDSYS_SERVANT_RECOMMNED_WEEK = 411
EREDSYS_SHOP_BUY_NOTIFY = 10600
EREDSYS_SIGNACTIVITY_NORMAL = 10616
EREDSYS_SIGNACTIVITY_NOVICE = 10615
EREDSYS_SIGNIN_ACTIVITY = 701
EREDSYS_SIGNIN_DAY = 700
EREDSYS_SKILL_POINT = 7
EREDSYS_SOCIAL_FRIEND_APPLY = 34
EREDSYS_STRENGTH_ACCUMULATE_REWARD = 10720
EREDSYS_TEAMAPPLY = 19
EREDSYS_TECHTREE_LEVEL_AWARD = 10715
EREDSYS_TECHTREE_PRODUCE = 10711
EREDSYS_TRADE_RECORD = 60
EREDSYS_TUTOR_APPLY = 82
EREDSYS_TUTOR_BOX = 86
EREDSYS_TUTOR_GROW_REWARD = 85
EREDSYS_TUTOR_STUDENT_UNLOCK = 81
EREDSYS_TUTOR_TASK = 83
EREDSYS_TUTOR_TUTOR_UNLOCK = 80
EREDSYS_USERINVITE_INVITE_LOGIN = 10608
EREDSYS_USERINVITE_RECALL_LOGIN = 10609
EREDSYS_USERRETURN_LOGIN_AWARD = 10612
EREDSYS_USERRETURN_QUEST_AWARD = 10610
EREDSYS_WALLET = 87
EREDSYS_WALLET_TYPE_PAGE = 88
ETIPITEMOPT_ADD = 1
ETIPITEMOPT_DELETE = 2
ETIPOPT_DELETE = 2
ETIPOPT_MIN = 0
ETIPOPT_UPDATE = 1
GameTipCmd = protobuf.Message(GAMETIPCMD)
RedTip = protobuf.Message(REDTIP)
TIPPARAM_ADDREDTIP = 3
TIPPARAM_BROWSE = 2
TIPPARAM_MAX = 4
TIPPARAM_RED = 1
