local protobuf = protobuf
autoImport("xCmd_pb")
local xCmd_pb = xCmd_pb
autoImport("ProtoCommon_pb")
local ProtoCommon_pb = ProtoCommon_pb
module("TeamGroupRaid_pb")
TEAMGROUPAIDPARAM = protobuf.EnumDescriptor()
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_INVITE_RAID_ENUM = protobuf.EnumValueDescriptor()
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_REPLY_RAID_ENUM = protobuf.EnumValueDescriptor()
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_ENTER_RAID_ENUM = protobuf.EnumValueDescriptor()
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_JOIN_RAID_ENUM = protobuf.EnumValueDescriptor()
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_QUERY_RAID_STATUS_ENUM = protobuf.EnumValueDescriptor()
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_ENTER_NEXT_RAID_ENUM = protobuf.EnumValueDescriptor()
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_INVITE_RAID_CONFIRM_ENUM = protobuf.EnumValueDescriptor()
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_REPLY_RAID_CONFIRM_ENUM = protobuf.EnumValueDescriptor()
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_QUERY_USER_KILLINFO_ENUM = protobuf.EnumValueDescriptor()
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_QUERY_GUILD_KILLINFO_ENUM = protobuf.EnumValueDescriptor()
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_QUERY_USER_SHOWDATA_ENUM = protobuf.EnumValueDescriptor()
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_CREATE_RAID_TOSCENE_ENUM = protobuf.EnumValueDescriptor()
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_JOIN_RAID_TOSCENE_ENUM = protobuf.EnumValueDescriptor()
EGROUPRAIDKILLTYPE = protobuf.EnumDescriptor()
EGROUPRAIDKILLTYPE_EGROUPRAIDKILL_MIN_ENUM = protobuf.EnumValueDescriptor()
EGROUPRAIDKILLTYPE_EGROUPRAIDKILL_NORMAL_ENUM = protobuf.EnumValueDescriptor()
EGROUPRAIDKILLTYPE_EGROUPRAIDKILL_GUILD_ENUM = protobuf.EnumValueDescriptor()
EGROUPRAIDKILLTYPE_EGROUPRAIDKILL_MAX_ENUM = protobuf.EnumValueDescriptor()
EUPDATEGROUPKILLACTION = protobuf.EnumDescriptor()
EUPDATEGROUPKILLACTION_EUPDATEGROUPKILL_MIN_ENUM = protobuf.EnumValueDescriptor()
EUPDATEGROUPKILLACTION_EUPDATEGROUPKILL_SCENE_TO_SESSION_ENUM = protobuf.EnumValueDescriptor()
EUPDATEGROUPKILLACTION_EUPDATEGROUPKILL_SESSION_TO_GLOBAL_ENUM = protobuf.EnumValueDescriptor()
EUPDATEGROUPKILLACTION_EUPDATEGROUPKILL_TO_SCENE_ENUM = protobuf.EnumValueDescriptor()
INVITEGROUPJOINRAIDTEAMCMD = protobuf.Descriptor()
INVITEGROUPJOINRAIDTEAMCMD_CMD_FIELD = protobuf.FieldDescriptor()
INVITEGROUPJOINRAIDTEAMCMD_PARAM_FIELD = protobuf.FieldDescriptor()
INVITEGROUPJOINRAIDTEAMCMD_ISCANCEL_FIELD = protobuf.FieldDescriptor()
INVITEGROUPJOINRAIDTEAMCMD_DIFFICULTY_FIELD = protobuf.FieldDescriptor()
INVITEGROUPJOINRAIDTEAMCMD_ENTRANCEID_FIELD = protobuf.FieldDescriptor()
INVITEGROUPJOINRAIDTEAMCMD_LEFTTIME_FIELD = protobuf.FieldDescriptor()
REPLYGROUPJOINRAIDTEAMCMD = protobuf.Descriptor()
REPLYGROUPJOINRAIDTEAMCMD_CMD_FIELD = protobuf.FieldDescriptor()
REPLYGROUPJOINRAIDTEAMCMD_PARAM_FIELD = protobuf.FieldDescriptor()
REPLYGROUPJOINRAIDTEAMCMD_REPLY_FIELD = protobuf.FieldDescriptor()
REPLYGROUPJOINRAIDTEAMCMD_CHARID_FIELD = protobuf.FieldDescriptor()
OPENGROUPRAIDTEAMCMD = protobuf.Descriptor()
OPENGROUPRAIDTEAMCMD_CMD_FIELD = protobuf.FieldDescriptor()
OPENGROUPRAIDTEAMCMD_PARAM_FIELD = protobuf.FieldDescriptor()
JOINGROUPRAIDTEAMCMD = protobuf.Descriptor()
JOINGROUPRAIDTEAMCMD_CMD_FIELD = protobuf.FieldDescriptor()
JOINGROUPRAIDTEAMCMD_PARAM_FIELD = protobuf.FieldDescriptor()
JOINGROUPRAIDTEAMCMD_DIFFICULTY_FIELD = protobuf.FieldDescriptor()
QUERYGROUPRAIDSTATUSCMD = protobuf.Descriptor()
QUERYGROUPRAIDSTATUSCMD_CMD_FIELD = protobuf.FieldDescriptor()
QUERYGROUPRAIDSTATUSCMD_PARAM_FIELD = protobuf.FieldDescriptor()
QUERYGROUPRAIDSTATUSCMD_OPEN_FIELD = protobuf.FieldDescriptor()
QUERYGROUPRAIDSTATUSCMD_CANJOIN_FIELD = protobuf.FieldDescriptor()
CREATEGROUPRAIDTEAMCMD = protobuf.Descriptor()
CREATEGROUPRAIDTEAMCMD_CMD_FIELD = protobuf.FieldDescriptor()
CREATEGROUPRAIDTEAMCMD_PARAM_FIELD = protobuf.FieldDescriptor()
CREATEGROUPRAIDTEAMCMD_DIFFICULTY_FIELD = protobuf.FieldDescriptor()
CREATEGROUPRAIDTEAMCMD_ZONEID_FIELD = protobuf.FieldDescriptor()
CREATEGROUPRAIDTEAMCMD_RAIDID_FIELD = protobuf.FieldDescriptor()
GOTOGROUPRAIDTEAMCMD = protobuf.Descriptor()
GOTOGROUPRAIDTEAMCMD_CMD_FIELD = protobuf.FieldDescriptor()
GOTOGROUPRAIDTEAMCMD_PARAM_FIELD = protobuf.FieldDescriptor()
GOTOGROUPRAIDTEAMCMD_ZONEID_FIELD = protobuf.FieldDescriptor()
GOTOGROUPRAIDTEAMCMD_RAIDID_FIELD = protobuf.FieldDescriptor()
ENTERNEXTRAIDGROUPCMD = protobuf.Descriptor()
ENTERNEXTRAIDGROUPCMD_CMD_FIELD = protobuf.FieldDescriptor()
ENTERNEXTRAIDGROUPCMD_PARAM_FIELD = protobuf.FieldDescriptor()
INVITECONFIRMRAIDTEAMGROUPCMD = protobuf.Descriptor()
INVITECONFIRMRAIDTEAMGROUPCMD_CMD_FIELD = protobuf.FieldDescriptor()
INVITECONFIRMRAIDTEAMGROUPCMD_PARAM_FIELD = protobuf.FieldDescriptor()
INVITECONFIRMRAIDTEAMGROUPCMD_CANCEL_FIELD = protobuf.FieldDescriptor()
REPLYCONFIRMRAIDTEAMGROUPCMD = protobuf.Descriptor()
REPLYCONFIRMRAIDTEAMGROUPCMD_CMD_FIELD = protobuf.FieldDescriptor()
REPLYCONFIRMRAIDTEAMGROUPCMD_PARAM_FIELD = protobuf.FieldDescriptor()
REPLYCONFIRMRAIDTEAMGROUPCMD_REPLY_FIELD = protobuf.FieldDescriptor()
REPLYCONFIRMRAIDTEAMGROUPCMD_CHARID_FIELD = protobuf.FieldDescriptor()
GROUPRAIDKILLUSERINFO = protobuf.Descriptor()
GROUPRAIDKILLUSERINFO_CHARID_FIELD = protobuf.FieldDescriptor()
GROUPRAIDKILLUSERINFO_PROFESSION_FIELD = protobuf.FieldDescriptor()
GROUPRAIDKILLUSERINFO_LEVEL_FIELD = protobuf.FieldDescriptor()
GROUPRAIDKILLUSERINFO_NAME_FIELD = protobuf.FieldDescriptor()
GROUPRAIDKILLUSERINFO_PORTRAIT_FIELD = protobuf.FieldDescriptor()
GROUPRAIDKILLUSERINFO_GUILDID_FIELD = protobuf.FieldDescriptor()
GROUPRAIDKILLUSERINFO_GUILDNAME_FIELD = protobuf.FieldDescriptor()
GROUPRAIDKILLGUILDINFO = protobuf.Descriptor()
GROUPRAIDKILLGUILDINFO_GUILDID_FIELD = protobuf.FieldDescriptor()
GROUPRAIDKILLGUILDINFO_GUILDNAME_FIELD = protobuf.FieldDescriptor()
GROUPRAIDKILLGUILDINFO_GUILDPORTRAIT_FIELD = protobuf.FieldDescriptor()
GROUPRAIDKILLGUILDINFO_RANK_FIELD = protobuf.FieldDescriptor()
GROUPRAIDKILLGUILDINFO_TIME_FIELD = protobuf.FieldDescriptor()
GROUPRAIDKILLINFO = protobuf.Descriptor()
GROUPRAIDKILLINFO_RAID_FIELD = protobuf.FieldDescriptor()
GROUPRAIDKILLINFO_TIME_FIELD = protobuf.FieldDescriptor()
GROUPRAIDKILLINFO_USERS_FIELD = protobuf.FieldDescriptor()
GROUPRAIDKILLINFO_GUILDS_FIELD = protobuf.FieldDescriptor()
QUERYGROUPRAIDKILLUSERINFO = protobuf.Descriptor()
QUERYGROUPRAIDKILLUSERINFO_CMD_FIELD = protobuf.FieldDescriptor()
QUERYGROUPRAIDKILLUSERINFO_PARAM_FIELD = protobuf.FieldDescriptor()
QUERYGROUPRAIDKILLUSERINFO_RAID_KEYS_FIELD = protobuf.FieldDescriptor()
QUERYGROUPRAIDKILLUSERINFO_INFOS_FIELD = protobuf.FieldDescriptor()
QUERYGROUPRAIDKILLGUILDINFO = protobuf.Descriptor()
QUERYGROUPRAIDKILLGUILDINFO_CMD_FIELD = protobuf.FieldDescriptor()
QUERYGROUPRAIDKILLGUILDINFO_PARAM_FIELD = protobuf.FieldDescriptor()
QUERYGROUPRAIDKILLGUILDINFO_RAID_KEYS_FIELD = protobuf.FieldDescriptor()
QUERYGROUPRAIDKILLGUILDINFO_INFOS_FIELD = protobuf.FieldDescriptor()
GROUPRAIDKILLUSERSHOWDATA = protobuf.Descriptor()
GROUPRAIDKILLUSERSHOWDATA_CHARID_FIELD = protobuf.FieldDescriptor()
GROUPRAIDKILLUSERSHOWDATA_NAME_FIELD = protobuf.FieldDescriptor()
GROUPRAIDKILLUSERSHOWDATA_LEVEL_FIELD = protobuf.FieldDescriptor()
GROUPRAIDKILLUSERSHOWDATA_PROFESSION_FIELD = protobuf.FieldDescriptor()
GROUPRAIDKILLUSERSHOWDATA_GUILDNAME_FIELD = protobuf.FieldDescriptor()
GROUPRAIDKILLUSERSHOWDATA_PORTRAIT_FIELD = protobuf.FieldDescriptor()
QUERYGROUPRAIDKILLUSERSHOWDATA = protobuf.Descriptor()
QUERYGROUPRAIDKILLUSERSHOWDATA_CMD_FIELD = protobuf.FieldDescriptor()
QUERYGROUPRAIDKILLUSERSHOWDATA_PARAM_FIELD = protobuf.FieldDescriptor()
QUERYGROUPRAIDKILLUSERSHOWDATA_CHARID_FIELD = protobuf.FieldDescriptor()
QUERYGROUPRAIDKILLUSERSHOWDATA_SHOWDATA_FIELD = protobuf.FieldDescriptor()
GROUPRAIDKILLRECORDDATA = protobuf.Descriptor()
GROUPRAIDKILLRECORDDATA_RAID_FIELD = protobuf.FieldDescriptor()
GROUPRAIDKILLRECORDDATA_TIME_FIELD = protobuf.FieldDescriptor()
GROUPRAIDKILLRECORDDATA_USERS_FIELD = protobuf.FieldDescriptor()
GROUPRAIDKILLRECORDDATA_GUILD_FIELD = protobuf.FieldDescriptor()
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_INVITE_RAID_ENUM.name = "TEAMGROUPPARAM_INVITE_RAID"
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_INVITE_RAID_ENUM.index = 0
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_INVITE_RAID_ENUM.number = 1
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_REPLY_RAID_ENUM.name = "TEAMGROUPPARAM_REPLY_RAID"
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_REPLY_RAID_ENUM.index = 1
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_REPLY_RAID_ENUM.number = 2
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_ENTER_RAID_ENUM.name = "TEAMGROUPPARAM_ENTER_RAID"
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_ENTER_RAID_ENUM.index = 2
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_ENTER_RAID_ENUM.number = 3
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_JOIN_RAID_ENUM.name = "TEAMGROUPPARAM_JOIN_RAID"
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_JOIN_RAID_ENUM.index = 3
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_JOIN_RAID_ENUM.number = 4
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_QUERY_RAID_STATUS_ENUM.name = "TEAMGROUPPARAM_QUERY_RAID_STATUS"
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_QUERY_RAID_STATUS_ENUM.index = 4
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_QUERY_RAID_STATUS_ENUM.number = 5
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_ENTER_NEXT_RAID_ENUM.name = "TEAMGROUPPARAM_ENTER_NEXT_RAID"
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_ENTER_NEXT_RAID_ENUM.index = 5
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_ENTER_NEXT_RAID_ENUM.number = 6
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_INVITE_RAID_CONFIRM_ENUM.name = "TEAMGROUPPARAM_INVITE_RAID_CONFIRM"
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_INVITE_RAID_CONFIRM_ENUM.index = 6
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_INVITE_RAID_CONFIRM_ENUM.number = 7
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_REPLY_RAID_CONFIRM_ENUM.name = "TEAMGROUPPARAM_REPLY_RAID_CONFIRM"
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_REPLY_RAID_CONFIRM_ENUM.index = 7
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_REPLY_RAID_CONFIRM_ENUM.number = 8
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_QUERY_USER_KILLINFO_ENUM.name = "TEAMGROUPPARAM_QUERY_USER_KILLINFO"
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_QUERY_USER_KILLINFO_ENUM.index = 8
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_QUERY_USER_KILLINFO_ENUM.number = 9
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_QUERY_GUILD_KILLINFO_ENUM.name = "TEAMGROUPPARAM_QUERY_GUILD_KILLINFO"
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_QUERY_GUILD_KILLINFO_ENUM.index = 9
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_QUERY_GUILD_KILLINFO_ENUM.number = 10
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_QUERY_USER_SHOWDATA_ENUM.name = "TEAMGROUPPARAM_QUERY_USER_SHOWDATA"
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_QUERY_USER_SHOWDATA_ENUM.index = 10
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_QUERY_USER_SHOWDATA_ENUM.number = 11
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_CREATE_RAID_TOSCENE_ENUM.name = "TEAMGROUPPARAM_CREATE_RAID_TOSCENE"
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_CREATE_RAID_TOSCENE_ENUM.index = 11
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_CREATE_RAID_TOSCENE_ENUM.number = 20
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_JOIN_RAID_TOSCENE_ENUM.name = "TEAMGROUPPARAM_JOIN_RAID_TOSCENE"
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_JOIN_RAID_TOSCENE_ENUM.index = 12
TEAMGROUPAIDPARAM_TEAMGROUPPARAM_JOIN_RAID_TOSCENE_ENUM.number = 21
TEAMGROUPAIDPARAM.name = "TeamGroupaidParam"
TEAMGROUPAIDPARAM.full_name = ".Cmd.TeamGroupaidParam"
TEAMGROUPAIDPARAM.values = {
  TEAMGROUPAIDPARAM_TEAMGROUPPARAM_INVITE_RAID_ENUM,
  TEAMGROUPAIDPARAM_TEAMGROUPPARAM_REPLY_RAID_ENUM,
  TEAMGROUPAIDPARAM_TEAMGROUPPARAM_ENTER_RAID_ENUM,
  TEAMGROUPAIDPARAM_TEAMGROUPPARAM_JOIN_RAID_ENUM,
  TEAMGROUPAIDPARAM_TEAMGROUPPARAM_QUERY_RAID_STATUS_ENUM,
  TEAMGROUPAIDPARAM_TEAMGROUPPARAM_ENTER_NEXT_RAID_ENUM,
  TEAMGROUPAIDPARAM_TEAMGROUPPARAM_INVITE_RAID_CONFIRM_ENUM,
  TEAMGROUPAIDPARAM_TEAMGROUPPARAM_REPLY_RAID_CONFIRM_ENUM,
  TEAMGROUPAIDPARAM_TEAMGROUPPARAM_QUERY_USER_KILLINFO_ENUM,
  TEAMGROUPAIDPARAM_TEAMGROUPPARAM_QUERY_GUILD_KILLINFO_ENUM,
  TEAMGROUPAIDPARAM_TEAMGROUPPARAM_QUERY_USER_SHOWDATA_ENUM,
  TEAMGROUPAIDPARAM_TEAMGROUPPARAM_CREATE_RAID_TOSCENE_ENUM,
  TEAMGROUPAIDPARAM_TEAMGROUPPARAM_JOIN_RAID_TOSCENE_ENUM
}
EGROUPRAIDKILLTYPE_EGROUPRAIDKILL_MIN_ENUM.name = "EGROUPRAIDKILL_MIN"
EGROUPRAIDKILLTYPE_EGROUPRAIDKILL_MIN_ENUM.index = 0
EGROUPRAIDKILLTYPE_EGROUPRAIDKILL_MIN_ENUM.number = 0
EGROUPRAIDKILLTYPE_EGROUPRAIDKILL_NORMAL_ENUM.name = "EGROUPRAIDKILL_NORMAL"
EGROUPRAIDKILLTYPE_EGROUPRAIDKILL_NORMAL_ENUM.index = 1
EGROUPRAIDKILLTYPE_EGROUPRAIDKILL_NORMAL_ENUM.number = 1
EGROUPRAIDKILLTYPE_EGROUPRAIDKILL_GUILD_ENUM.name = "EGROUPRAIDKILL_GUILD"
EGROUPRAIDKILLTYPE_EGROUPRAIDKILL_GUILD_ENUM.index = 2
EGROUPRAIDKILLTYPE_EGROUPRAIDKILL_GUILD_ENUM.number = 2
EGROUPRAIDKILLTYPE_EGROUPRAIDKILL_MAX_ENUM.name = "EGROUPRAIDKILL_MAX"
EGROUPRAIDKILLTYPE_EGROUPRAIDKILL_MAX_ENUM.index = 3
EGROUPRAIDKILLTYPE_EGROUPRAIDKILL_MAX_ENUM.number = 3
EGROUPRAIDKILLTYPE.name = "EGroupRaidKillType"
EGROUPRAIDKILLTYPE.full_name = ".Cmd.EGroupRaidKillType"
EGROUPRAIDKILLTYPE.values = {
  EGROUPRAIDKILLTYPE_EGROUPRAIDKILL_MIN_ENUM,
  EGROUPRAIDKILLTYPE_EGROUPRAIDKILL_NORMAL_ENUM,
  EGROUPRAIDKILLTYPE_EGROUPRAIDKILL_GUILD_ENUM,
  EGROUPRAIDKILLTYPE_EGROUPRAIDKILL_MAX_ENUM
}
EUPDATEGROUPKILLACTION_EUPDATEGROUPKILL_MIN_ENUM.name = "EUPDATEGROUPKILL_MIN"
EUPDATEGROUPKILLACTION_EUPDATEGROUPKILL_MIN_ENUM.index = 0
EUPDATEGROUPKILLACTION_EUPDATEGROUPKILL_MIN_ENUM.number = 0
EUPDATEGROUPKILLACTION_EUPDATEGROUPKILL_SCENE_TO_SESSION_ENUM.name = "EUPDATEGROUPKILL_SCENE_TO_SESSION"
EUPDATEGROUPKILLACTION_EUPDATEGROUPKILL_SCENE_TO_SESSION_ENUM.index = 1
EUPDATEGROUPKILLACTION_EUPDATEGROUPKILL_SCENE_TO_SESSION_ENUM.number = 1
EUPDATEGROUPKILLACTION_EUPDATEGROUPKILL_SESSION_TO_GLOBAL_ENUM.name = "EUPDATEGROUPKILL_SESSION_TO_GLOBAL"
EUPDATEGROUPKILLACTION_EUPDATEGROUPKILL_SESSION_TO_GLOBAL_ENUM.index = 2
EUPDATEGROUPKILLACTION_EUPDATEGROUPKILL_SESSION_TO_GLOBAL_ENUM.number = 2
EUPDATEGROUPKILLACTION_EUPDATEGROUPKILL_TO_SCENE_ENUM.name = "EUPDATEGROUPKILL_TO_SCENE"
EUPDATEGROUPKILLACTION_EUPDATEGROUPKILL_TO_SCENE_ENUM.index = 3
EUPDATEGROUPKILLACTION_EUPDATEGROUPKILL_TO_SCENE_ENUM.number = 3
EUPDATEGROUPKILLACTION.name = "EUpdateGroupKillAction"
EUPDATEGROUPKILLACTION.full_name = ".Cmd.EUpdateGroupKillAction"
EUPDATEGROUPKILLACTION.values = {
  EUPDATEGROUPKILLACTION_EUPDATEGROUPKILL_MIN_ENUM,
  EUPDATEGROUPKILLACTION_EUPDATEGROUPKILL_SCENE_TO_SESSION_ENUM,
  EUPDATEGROUPKILLACTION_EUPDATEGROUPKILL_SESSION_TO_GLOBAL_ENUM,
  EUPDATEGROUPKILLACTION_EUPDATEGROUPKILL_TO_SCENE_ENUM
}
INVITEGROUPJOINRAIDTEAMCMD_CMD_FIELD.name = "cmd"
INVITEGROUPJOINRAIDTEAMCMD_CMD_FIELD.full_name = ".Cmd.InviteGroupJoinRaidTeamCmd.cmd"
INVITEGROUPJOINRAIDTEAMCMD_CMD_FIELD.number = 1
INVITEGROUPJOINRAIDTEAMCMD_CMD_FIELD.index = 0
INVITEGROUPJOINRAIDTEAMCMD_CMD_FIELD.label = 1
INVITEGROUPJOINRAIDTEAMCMD_CMD_FIELD.has_default_value = true
INVITEGROUPJOINRAIDTEAMCMD_CMD_FIELD.default_value = 69
INVITEGROUPJOINRAIDTEAMCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
INVITEGROUPJOINRAIDTEAMCMD_CMD_FIELD.type = 14
INVITEGROUPJOINRAIDTEAMCMD_CMD_FIELD.cpp_type = 8
INVITEGROUPJOINRAIDTEAMCMD_PARAM_FIELD.name = "param"
INVITEGROUPJOINRAIDTEAMCMD_PARAM_FIELD.full_name = ".Cmd.InviteGroupJoinRaidTeamCmd.param"
INVITEGROUPJOINRAIDTEAMCMD_PARAM_FIELD.number = 2
INVITEGROUPJOINRAIDTEAMCMD_PARAM_FIELD.index = 1
INVITEGROUPJOINRAIDTEAMCMD_PARAM_FIELD.label = 1
INVITEGROUPJOINRAIDTEAMCMD_PARAM_FIELD.has_default_value = true
INVITEGROUPJOINRAIDTEAMCMD_PARAM_FIELD.default_value = 1
INVITEGROUPJOINRAIDTEAMCMD_PARAM_FIELD.enum_type = TEAMGROUPAIDPARAM
INVITEGROUPJOINRAIDTEAMCMD_PARAM_FIELD.type = 14
INVITEGROUPJOINRAIDTEAMCMD_PARAM_FIELD.cpp_type = 8
INVITEGROUPJOINRAIDTEAMCMD_ISCANCEL_FIELD.name = "iscancel"
INVITEGROUPJOINRAIDTEAMCMD_ISCANCEL_FIELD.full_name = ".Cmd.InviteGroupJoinRaidTeamCmd.iscancel"
INVITEGROUPJOINRAIDTEAMCMD_ISCANCEL_FIELD.number = 3
INVITEGROUPJOINRAIDTEAMCMD_ISCANCEL_FIELD.index = 2
INVITEGROUPJOINRAIDTEAMCMD_ISCANCEL_FIELD.label = 1
INVITEGROUPJOINRAIDTEAMCMD_ISCANCEL_FIELD.has_default_value = true
INVITEGROUPJOINRAIDTEAMCMD_ISCANCEL_FIELD.default_value = false
INVITEGROUPJOINRAIDTEAMCMD_ISCANCEL_FIELD.type = 8
INVITEGROUPJOINRAIDTEAMCMD_ISCANCEL_FIELD.cpp_type = 7
INVITEGROUPJOINRAIDTEAMCMD_DIFFICULTY_FIELD.name = "difficulty"
INVITEGROUPJOINRAIDTEAMCMD_DIFFICULTY_FIELD.full_name = ".Cmd.InviteGroupJoinRaidTeamCmd.difficulty"
INVITEGROUPJOINRAIDTEAMCMD_DIFFICULTY_FIELD.number = 4
INVITEGROUPJOINRAIDTEAMCMD_DIFFICULTY_FIELD.index = 3
INVITEGROUPJOINRAIDTEAMCMD_DIFFICULTY_FIELD.label = 1
INVITEGROUPJOINRAIDTEAMCMD_DIFFICULTY_FIELD.has_default_value = true
INVITEGROUPJOINRAIDTEAMCMD_DIFFICULTY_FIELD.default_value = 1
INVITEGROUPJOINRAIDTEAMCMD_DIFFICULTY_FIELD.type = 13
INVITEGROUPJOINRAIDTEAMCMD_DIFFICULTY_FIELD.cpp_type = 3
INVITEGROUPJOINRAIDTEAMCMD_ENTRANCEID_FIELD.name = "entranceid"
INVITEGROUPJOINRAIDTEAMCMD_ENTRANCEID_FIELD.full_name = ".Cmd.InviteGroupJoinRaidTeamCmd.entranceid"
INVITEGROUPJOINRAIDTEAMCMD_ENTRANCEID_FIELD.number = 5
INVITEGROUPJOINRAIDTEAMCMD_ENTRANCEID_FIELD.index = 4
INVITEGROUPJOINRAIDTEAMCMD_ENTRANCEID_FIELD.label = 1
INVITEGROUPJOINRAIDTEAMCMD_ENTRANCEID_FIELD.has_default_value = false
INVITEGROUPJOINRAIDTEAMCMD_ENTRANCEID_FIELD.default_value = 0
INVITEGROUPJOINRAIDTEAMCMD_ENTRANCEID_FIELD.type = 13
INVITEGROUPJOINRAIDTEAMCMD_ENTRANCEID_FIELD.cpp_type = 3
INVITEGROUPJOINRAIDTEAMCMD_LEFTTIME_FIELD.name = "lefttime"
INVITEGROUPJOINRAIDTEAMCMD_LEFTTIME_FIELD.full_name = ".Cmd.InviteGroupJoinRaidTeamCmd.lefttime"
INVITEGROUPJOINRAIDTEAMCMD_LEFTTIME_FIELD.number = 6
INVITEGROUPJOINRAIDTEAMCMD_LEFTTIME_FIELD.index = 5
INVITEGROUPJOINRAIDTEAMCMD_LEFTTIME_FIELD.label = 1
INVITEGROUPJOINRAIDTEAMCMD_LEFTTIME_FIELD.has_default_value = false
INVITEGROUPJOINRAIDTEAMCMD_LEFTTIME_FIELD.default_value = 0
INVITEGROUPJOINRAIDTEAMCMD_LEFTTIME_FIELD.type = 13
INVITEGROUPJOINRAIDTEAMCMD_LEFTTIME_FIELD.cpp_type = 3
INVITEGROUPJOINRAIDTEAMCMD.name = "InviteGroupJoinRaidTeamCmd"
INVITEGROUPJOINRAIDTEAMCMD.full_name = ".Cmd.InviteGroupJoinRaidTeamCmd"
INVITEGROUPJOINRAIDTEAMCMD.nested_types = {}
INVITEGROUPJOINRAIDTEAMCMD.enum_types = {}
INVITEGROUPJOINRAIDTEAMCMD.fields = {
  INVITEGROUPJOINRAIDTEAMCMD_CMD_FIELD,
  INVITEGROUPJOINRAIDTEAMCMD_PARAM_FIELD,
  INVITEGROUPJOINRAIDTEAMCMD_ISCANCEL_FIELD,
  INVITEGROUPJOINRAIDTEAMCMD_DIFFICULTY_FIELD,
  INVITEGROUPJOINRAIDTEAMCMD_ENTRANCEID_FIELD,
  INVITEGROUPJOINRAIDTEAMCMD_LEFTTIME_FIELD
}
INVITEGROUPJOINRAIDTEAMCMD.is_extendable = false
INVITEGROUPJOINRAIDTEAMCMD.extensions = {}
REPLYGROUPJOINRAIDTEAMCMD_CMD_FIELD.name = "cmd"
REPLYGROUPJOINRAIDTEAMCMD_CMD_FIELD.full_name = ".Cmd.ReplyGroupJoinRaidTeamCmd.cmd"
REPLYGROUPJOINRAIDTEAMCMD_CMD_FIELD.number = 1
REPLYGROUPJOINRAIDTEAMCMD_CMD_FIELD.index = 0
REPLYGROUPJOINRAIDTEAMCMD_CMD_FIELD.label = 1
REPLYGROUPJOINRAIDTEAMCMD_CMD_FIELD.has_default_value = true
REPLYGROUPJOINRAIDTEAMCMD_CMD_FIELD.default_value = 69
REPLYGROUPJOINRAIDTEAMCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
REPLYGROUPJOINRAIDTEAMCMD_CMD_FIELD.type = 14
REPLYGROUPJOINRAIDTEAMCMD_CMD_FIELD.cpp_type = 8
REPLYGROUPJOINRAIDTEAMCMD_PARAM_FIELD.name = "param"
REPLYGROUPJOINRAIDTEAMCMD_PARAM_FIELD.full_name = ".Cmd.ReplyGroupJoinRaidTeamCmd.param"
REPLYGROUPJOINRAIDTEAMCMD_PARAM_FIELD.number = 2
REPLYGROUPJOINRAIDTEAMCMD_PARAM_FIELD.index = 1
REPLYGROUPJOINRAIDTEAMCMD_PARAM_FIELD.label = 1
REPLYGROUPJOINRAIDTEAMCMD_PARAM_FIELD.has_default_value = true
REPLYGROUPJOINRAIDTEAMCMD_PARAM_FIELD.default_value = 2
REPLYGROUPJOINRAIDTEAMCMD_PARAM_FIELD.enum_type = TEAMGROUPAIDPARAM
REPLYGROUPJOINRAIDTEAMCMD_PARAM_FIELD.type = 14
REPLYGROUPJOINRAIDTEAMCMD_PARAM_FIELD.cpp_type = 8
REPLYGROUPJOINRAIDTEAMCMD_REPLY_FIELD.name = "reply"
REPLYGROUPJOINRAIDTEAMCMD_REPLY_FIELD.full_name = ".Cmd.ReplyGroupJoinRaidTeamCmd.reply"
REPLYGROUPJOINRAIDTEAMCMD_REPLY_FIELD.number = 3
REPLYGROUPJOINRAIDTEAMCMD_REPLY_FIELD.index = 2
REPLYGROUPJOINRAIDTEAMCMD_REPLY_FIELD.label = 1
REPLYGROUPJOINRAIDTEAMCMD_REPLY_FIELD.has_default_value = true
REPLYGROUPJOINRAIDTEAMCMD_REPLY_FIELD.default_value = false
REPLYGROUPJOINRAIDTEAMCMD_REPLY_FIELD.type = 8
REPLYGROUPJOINRAIDTEAMCMD_REPLY_FIELD.cpp_type = 7
REPLYGROUPJOINRAIDTEAMCMD_CHARID_FIELD.name = "charid"
REPLYGROUPJOINRAIDTEAMCMD_CHARID_FIELD.full_name = ".Cmd.ReplyGroupJoinRaidTeamCmd.charid"
REPLYGROUPJOINRAIDTEAMCMD_CHARID_FIELD.number = 4
REPLYGROUPJOINRAIDTEAMCMD_CHARID_FIELD.index = 3
REPLYGROUPJOINRAIDTEAMCMD_CHARID_FIELD.label = 1
REPLYGROUPJOINRAIDTEAMCMD_CHARID_FIELD.has_default_value = true
REPLYGROUPJOINRAIDTEAMCMD_CHARID_FIELD.default_value = 0
REPLYGROUPJOINRAIDTEAMCMD_CHARID_FIELD.type = 4
REPLYGROUPJOINRAIDTEAMCMD_CHARID_FIELD.cpp_type = 4
REPLYGROUPJOINRAIDTEAMCMD.name = "ReplyGroupJoinRaidTeamCmd"
REPLYGROUPJOINRAIDTEAMCMD.full_name = ".Cmd.ReplyGroupJoinRaidTeamCmd"
REPLYGROUPJOINRAIDTEAMCMD.nested_types = {}
REPLYGROUPJOINRAIDTEAMCMD.enum_types = {}
REPLYGROUPJOINRAIDTEAMCMD.fields = {
  REPLYGROUPJOINRAIDTEAMCMD_CMD_FIELD,
  REPLYGROUPJOINRAIDTEAMCMD_PARAM_FIELD,
  REPLYGROUPJOINRAIDTEAMCMD_REPLY_FIELD,
  REPLYGROUPJOINRAIDTEAMCMD_CHARID_FIELD
}
REPLYGROUPJOINRAIDTEAMCMD.is_extendable = false
REPLYGROUPJOINRAIDTEAMCMD.extensions = {}
OPENGROUPRAIDTEAMCMD_CMD_FIELD.name = "cmd"
OPENGROUPRAIDTEAMCMD_CMD_FIELD.full_name = ".Cmd.OpenGroupRaidTeamCmd.cmd"
OPENGROUPRAIDTEAMCMD_CMD_FIELD.number = 1
OPENGROUPRAIDTEAMCMD_CMD_FIELD.index = 0
OPENGROUPRAIDTEAMCMD_CMD_FIELD.label = 1
OPENGROUPRAIDTEAMCMD_CMD_FIELD.has_default_value = true
OPENGROUPRAIDTEAMCMD_CMD_FIELD.default_value = 69
OPENGROUPRAIDTEAMCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
OPENGROUPRAIDTEAMCMD_CMD_FIELD.type = 14
OPENGROUPRAIDTEAMCMD_CMD_FIELD.cpp_type = 8
OPENGROUPRAIDTEAMCMD_PARAM_FIELD.name = "param"
OPENGROUPRAIDTEAMCMD_PARAM_FIELD.full_name = ".Cmd.OpenGroupRaidTeamCmd.param"
OPENGROUPRAIDTEAMCMD_PARAM_FIELD.number = 2
OPENGROUPRAIDTEAMCMD_PARAM_FIELD.index = 1
OPENGROUPRAIDTEAMCMD_PARAM_FIELD.label = 1
OPENGROUPRAIDTEAMCMD_PARAM_FIELD.has_default_value = true
OPENGROUPRAIDTEAMCMD_PARAM_FIELD.default_value = 3
OPENGROUPRAIDTEAMCMD_PARAM_FIELD.enum_type = TEAMGROUPAIDPARAM
OPENGROUPRAIDTEAMCMD_PARAM_FIELD.type = 14
OPENGROUPRAIDTEAMCMD_PARAM_FIELD.cpp_type = 8
OPENGROUPRAIDTEAMCMD.name = "OpenGroupRaidTeamCmd"
OPENGROUPRAIDTEAMCMD.full_name = ".Cmd.OpenGroupRaidTeamCmd"
OPENGROUPRAIDTEAMCMD.nested_types = {}
OPENGROUPRAIDTEAMCMD.enum_types = {}
OPENGROUPRAIDTEAMCMD.fields = {
  OPENGROUPRAIDTEAMCMD_CMD_FIELD,
  OPENGROUPRAIDTEAMCMD_PARAM_FIELD
}
OPENGROUPRAIDTEAMCMD.is_extendable = false
OPENGROUPRAIDTEAMCMD.extensions = {}
JOINGROUPRAIDTEAMCMD_CMD_FIELD.name = "cmd"
JOINGROUPRAIDTEAMCMD_CMD_FIELD.full_name = ".Cmd.JoinGroupRaidTeamCmd.cmd"
JOINGROUPRAIDTEAMCMD_CMD_FIELD.number = 1
JOINGROUPRAIDTEAMCMD_CMD_FIELD.index = 0
JOINGROUPRAIDTEAMCMD_CMD_FIELD.label = 1
JOINGROUPRAIDTEAMCMD_CMD_FIELD.has_default_value = true
JOINGROUPRAIDTEAMCMD_CMD_FIELD.default_value = 69
JOINGROUPRAIDTEAMCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
JOINGROUPRAIDTEAMCMD_CMD_FIELD.type = 14
JOINGROUPRAIDTEAMCMD_CMD_FIELD.cpp_type = 8
JOINGROUPRAIDTEAMCMD_PARAM_FIELD.name = "param"
JOINGROUPRAIDTEAMCMD_PARAM_FIELD.full_name = ".Cmd.JoinGroupRaidTeamCmd.param"
JOINGROUPRAIDTEAMCMD_PARAM_FIELD.number = 2
JOINGROUPRAIDTEAMCMD_PARAM_FIELD.index = 1
JOINGROUPRAIDTEAMCMD_PARAM_FIELD.label = 1
JOINGROUPRAIDTEAMCMD_PARAM_FIELD.has_default_value = true
JOINGROUPRAIDTEAMCMD_PARAM_FIELD.default_value = 4
JOINGROUPRAIDTEAMCMD_PARAM_FIELD.enum_type = TEAMGROUPAIDPARAM
JOINGROUPRAIDTEAMCMD_PARAM_FIELD.type = 14
JOINGROUPRAIDTEAMCMD_PARAM_FIELD.cpp_type = 8
JOINGROUPRAIDTEAMCMD_DIFFICULTY_FIELD.name = "difficulty"
JOINGROUPRAIDTEAMCMD_DIFFICULTY_FIELD.full_name = ".Cmd.JoinGroupRaidTeamCmd.difficulty"
JOINGROUPRAIDTEAMCMD_DIFFICULTY_FIELD.number = 3
JOINGROUPRAIDTEAMCMD_DIFFICULTY_FIELD.index = 2
JOINGROUPRAIDTEAMCMD_DIFFICULTY_FIELD.label = 1
JOINGROUPRAIDTEAMCMD_DIFFICULTY_FIELD.has_default_value = false
JOINGROUPRAIDTEAMCMD_DIFFICULTY_FIELD.default_value = 0
JOINGROUPRAIDTEAMCMD_DIFFICULTY_FIELD.type = 13
JOINGROUPRAIDTEAMCMD_DIFFICULTY_FIELD.cpp_type = 3
JOINGROUPRAIDTEAMCMD.name = "JoinGroupRaidTeamCmd"
JOINGROUPRAIDTEAMCMD.full_name = ".Cmd.JoinGroupRaidTeamCmd"
JOINGROUPRAIDTEAMCMD.nested_types = {}
JOINGROUPRAIDTEAMCMD.enum_types = {}
JOINGROUPRAIDTEAMCMD.fields = {
  JOINGROUPRAIDTEAMCMD_CMD_FIELD,
  JOINGROUPRAIDTEAMCMD_PARAM_FIELD,
  JOINGROUPRAIDTEAMCMD_DIFFICULTY_FIELD
}
JOINGROUPRAIDTEAMCMD.is_extendable = false
JOINGROUPRAIDTEAMCMD.extensions = {}
QUERYGROUPRAIDSTATUSCMD_CMD_FIELD.name = "cmd"
QUERYGROUPRAIDSTATUSCMD_CMD_FIELD.full_name = ".Cmd.QueryGroupRaidStatusCmd.cmd"
QUERYGROUPRAIDSTATUSCMD_CMD_FIELD.number = 1
QUERYGROUPRAIDSTATUSCMD_CMD_FIELD.index = 0
QUERYGROUPRAIDSTATUSCMD_CMD_FIELD.label = 1
QUERYGROUPRAIDSTATUSCMD_CMD_FIELD.has_default_value = true
QUERYGROUPRAIDSTATUSCMD_CMD_FIELD.default_value = 69
QUERYGROUPRAIDSTATUSCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
QUERYGROUPRAIDSTATUSCMD_CMD_FIELD.type = 14
QUERYGROUPRAIDSTATUSCMD_CMD_FIELD.cpp_type = 8
QUERYGROUPRAIDSTATUSCMD_PARAM_FIELD.name = "param"
QUERYGROUPRAIDSTATUSCMD_PARAM_FIELD.full_name = ".Cmd.QueryGroupRaidStatusCmd.param"
QUERYGROUPRAIDSTATUSCMD_PARAM_FIELD.number = 2
QUERYGROUPRAIDSTATUSCMD_PARAM_FIELD.index = 1
QUERYGROUPRAIDSTATUSCMD_PARAM_FIELD.label = 1
QUERYGROUPRAIDSTATUSCMD_PARAM_FIELD.has_default_value = true
QUERYGROUPRAIDSTATUSCMD_PARAM_FIELD.default_value = 5
QUERYGROUPRAIDSTATUSCMD_PARAM_FIELD.enum_type = TEAMGROUPAIDPARAM
QUERYGROUPRAIDSTATUSCMD_PARAM_FIELD.type = 14
QUERYGROUPRAIDSTATUSCMD_PARAM_FIELD.cpp_type = 8
QUERYGROUPRAIDSTATUSCMD_OPEN_FIELD.name = "open"
QUERYGROUPRAIDSTATUSCMD_OPEN_FIELD.full_name = ".Cmd.QueryGroupRaidStatusCmd.open"
QUERYGROUPRAIDSTATUSCMD_OPEN_FIELD.number = 3
QUERYGROUPRAIDSTATUSCMD_OPEN_FIELD.index = 2
QUERYGROUPRAIDSTATUSCMD_OPEN_FIELD.label = 1
QUERYGROUPRAIDSTATUSCMD_OPEN_FIELD.has_default_value = true
QUERYGROUPRAIDSTATUSCMD_OPEN_FIELD.default_value = false
QUERYGROUPRAIDSTATUSCMD_OPEN_FIELD.type = 8
QUERYGROUPRAIDSTATUSCMD_OPEN_FIELD.cpp_type = 7
QUERYGROUPRAIDSTATUSCMD_CANJOIN_FIELD.name = "canjoin"
QUERYGROUPRAIDSTATUSCMD_CANJOIN_FIELD.full_name = ".Cmd.QueryGroupRaidStatusCmd.canjoin"
QUERYGROUPRAIDSTATUSCMD_CANJOIN_FIELD.number = 4
QUERYGROUPRAIDSTATUSCMD_CANJOIN_FIELD.index = 3
QUERYGROUPRAIDSTATUSCMD_CANJOIN_FIELD.label = 1
QUERYGROUPRAIDSTATUSCMD_CANJOIN_FIELD.has_default_value = true
QUERYGROUPRAIDSTATUSCMD_CANJOIN_FIELD.default_value = false
QUERYGROUPRAIDSTATUSCMD_CANJOIN_FIELD.type = 8
QUERYGROUPRAIDSTATUSCMD_CANJOIN_FIELD.cpp_type = 7
QUERYGROUPRAIDSTATUSCMD.name = "QueryGroupRaidStatusCmd"
QUERYGROUPRAIDSTATUSCMD.full_name = ".Cmd.QueryGroupRaidStatusCmd"
QUERYGROUPRAIDSTATUSCMD.nested_types = {}
QUERYGROUPRAIDSTATUSCMD.enum_types = {}
QUERYGROUPRAIDSTATUSCMD.fields = {
  QUERYGROUPRAIDSTATUSCMD_CMD_FIELD,
  QUERYGROUPRAIDSTATUSCMD_PARAM_FIELD,
  QUERYGROUPRAIDSTATUSCMD_OPEN_FIELD,
  QUERYGROUPRAIDSTATUSCMD_CANJOIN_FIELD
}
QUERYGROUPRAIDSTATUSCMD.is_extendable = false
QUERYGROUPRAIDSTATUSCMD.extensions = {}
CREATEGROUPRAIDTEAMCMD_CMD_FIELD.name = "cmd"
CREATEGROUPRAIDTEAMCMD_CMD_FIELD.full_name = ".Cmd.CreateGroupRaidTeamCmd.cmd"
CREATEGROUPRAIDTEAMCMD_CMD_FIELD.number = 1
CREATEGROUPRAIDTEAMCMD_CMD_FIELD.index = 0
CREATEGROUPRAIDTEAMCMD_CMD_FIELD.label = 1
CREATEGROUPRAIDTEAMCMD_CMD_FIELD.has_default_value = true
CREATEGROUPRAIDTEAMCMD_CMD_FIELD.default_value = 69
CREATEGROUPRAIDTEAMCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
CREATEGROUPRAIDTEAMCMD_CMD_FIELD.type = 14
CREATEGROUPRAIDTEAMCMD_CMD_FIELD.cpp_type = 8
CREATEGROUPRAIDTEAMCMD_PARAM_FIELD.name = "param"
CREATEGROUPRAIDTEAMCMD_PARAM_FIELD.full_name = ".Cmd.CreateGroupRaidTeamCmd.param"
CREATEGROUPRAIDTEAMCMD_PARAM_FIELD.number = 2
CREATEGROUPRAIDTEAMCMD_PARAM_FIELD.index = 1
CREATEGROUPRAIDTEAMCMD_PARAM_FIELD.label = 1
CREATEGROUPRAIDTEAMCMD_PARAM_FIELD.has_default_value = true
CREATEGROUPRAIDTEAMCMD_PARAM_FIELD.default_value = 20
CREATEGROUPRAIDTEAMCMD_PARAM_FIELD.enum_type = TEAMGROUPAIDPARAM
CREATEGROUPRAIDTEAMCMD_PARAM_FIELD.type = 14
CREATEGROUPRAIDTEAMCMD_PARAM_FIELD.cpp_type = 8
CREATEGROUPRAIDTEAMCMD_DIFFICULTY_FIELD.name = "difficulty"
CREATEGROUPRAIDTEAMCMD_DIFFICULTY_FIELD.full_name = ".Cmd.CreateGroupRaidTeamCmd.difficulty"
CREATEGROUPRAIDTEAMCMD_DIFFICULTY_FIELD.number = 3
CREATEGROUPRAIDTEAMCMD_DIFFICULTY_FIELD.index = 2
CREATEGROUPRAIDTEAMCMD_DIFFICULTY_FIELD.label = 1
CREATEGROUPRAIDTEAMCMD_DIFFICULTY_FIELD.has_default_value = true
CREATEGROUPRAIDTEAMCMD_DIFFICULTY_FIELD.default_value = 0
CREATEGROUPRAIDTEAMCMD_DIFFICULTY_FIELD.type = 13
CREATEGROUPRAIDTEAMCMD_DIFFICULTY_FIELD.cpp_type = 3
CREATEGROUPRAIDTEAMCMD_ZONEID_FIELD.name = "zoneid"
CREATEGROUPRAIDTEAMCMD_ZONEID_FIELD.full_name = ".Cmd.CreateGroupRaidTeamCmd.zoneid"
CREATEGROUPRAIDTEAMCMD_ZONEID_FIELD.number = 4
CREATEGROUPRAIDTEAMCMD_ZONEID_FIELD.index = 3
CREATEGROUPRAIDTEAMCMD_ZONEID_FIELD.label = 1
CREATEGROUPRAIDTEAMCMD_ZONEID_FIELD.has_default_value = true
CREATEGROUPRAIDTEAMCMD_ZONEID_FIELD.default_value = 0
CREATEGROUPRAIDTEAMCMD_ZONEID_FIELD.type = 13
CREATEGROUPRAIDTEAMCMD_ZONEID_FIELD.cpp_type = 3
CREATEGROUPRAIDTEAMCMD_RAIDID_FIELD.name = "raidid"
CREATEGROUPRAIDTEAMCMD_RAIDID_FIELD.full_name = ".Cmd.CreateGroupRaidTeamCmd.raidid"
CREATEGROUPRAIDTEAMCMD_RAIDID_FIELD.number = 5
CREATEGROUPRAIDTEAMCMD_RAIDID_FIELD.index = 4
CREATEGROUPRAIDTEAMCMD_RAIDID_FIELD.label = 1
CREATEGROUPRAIDTEAMCMD_RAIDID_FIELD.has_default_value = true
CREATEGROUPRAIDTEAMCMD_RAIDID_FIELD.default_value = 0
CREATEGROUPRAIDTEAMCMD_RAIDID_FIELD.type = 13
CREATEGROUPRAIDTEAMCMD_RAIDID_FIELD.cpp_type = 3
CREATEGROUPRAIDTEAMCMD.name = "CreateGroupRaidTeamCmd"
CREATEGROUPRAIDTEAMCMD.full_name = ".Cmd.CreateGroupRaidTeamCmd"
CREATEGROUPRAIDTEAMCMD.nested_types = {}
CREATEGROUPRAIDTEAMCMD.enum_types = {}
CREATEGROUPRAIDTEAMCMD.fields = {
  CREATEGROUPRAIDTEAMCMD_CMD_FIELD,
  CREATEGROUPRAIDTEAMCMD_PARAM_FIELD,
  CREATEGROUPRAIDTEAMCMD_DIFFICULTY_FIELD,
  CREATEGROUPRAIDTEAMCMD_ZONEID_FIELD,
  CREATEGROUPRAIDTEAMCMD_RAIDID_FIELD
}
CREATEGROUPRAIDTEAMCMD.is_extendable = false
CREATEGROUPRAIDTEAMCMD.extensions = {}
GOTOGROUPRAIDTEAMCMD_CMD_FIELD.name = "cmd"
GOTOGROUPRAIDTEAMCMD_CMD_FIELD.full_name = ".Cmd.GoToGroupRaidTeamCmd.cmd"
GOTOGROUPRAIDTEAMCMD_CMD_FIELD.number = 1
GOTOGROUPRAIDTEAMCMD_CMD_FIELD.index = 0
GOTOGROUPRAIDTEAMCMD_CMD_FIELD.label = 1
GOTOGROUPRAIDTEAMCMD_CMD_FIELD.has_default_value = true
GOTOGROUPRAIDTEAMCMD_CMD_FIELD.default_value = 69
GOTOGROUPRAIDTEAMCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
GOTOGROUPRAIDTEAMCMD_CMD_FIELD.type = 14
GOTOGROUPRAIDTEAMCMD_CMD_FIELD.cpp_type = 8
GOTOGROUPRAIDTEAMCMD_PARAM_FIELD.name = "param"
GOTOGROUPRAIDTEAMCMD_PARAM_FIELD.full_name = ".Cmd.GoToGroupRaidTeamCmd.param"
GOTOGROUPRAIDTEAMCMD_PARAM_FIELD.number = 2
GOTOGROUPRAIDTEAMCMD_PARAM_FIELD.index = 1
GOTOGROUPRAIDTEAMCMD_PARAM_FIELD.label = 1
GOTOGROUPRAIDTEAMCMD_PARAM_FIELD.has_default_value = true
GOTOGROUPRAIDTEAMCMD_PARAM_FIELD.default_value = 21
GOTOGROUPRAIDTEAMCMD_PARAM_FIELD.enum_type = TEAMGROUPAIDPARAM
GOTOGROUPRAIDTEAMCMD_PARAM_FIELD.type = 14
GOTOGROUPRAIDTEAMCMD_PARAM_FIELD.cpp_type = 8
GOTOGROUPRAIDTEAMCMD_ZONEID_FIELD.name = "zoneid"
GOTOGROUPRAIDTEAMCMD_ZONEID_FIELD.full_name = ".Cmd.GoToGroupRaidTeamCmd.zoneid"
GOTOGROUPRAIDTEAMCMD_ZONEID_FIELD.number = 3
GOTOGROUPRAIDTEAMCMD_ZONEID_FIELD.index = 2
GOTOGROUPRAIDTEAMCMD_ZONEID_FIELD.label = 2
GOTOGROUPRAIDTEAMCMD_ZONEID_FIELD.has_default_value = false
GOTOGROUPRAIDTEAMCMD_ZONEID_FIELD.default_value = 0
GOTOGROUPRAIDTEAMCMD_ZONEID_FIELD.type = 13
GOTOGROUPRAIDTEAMCMD_ZONEID_FIELD.cpp_type = 3
GOTOGROUPRAIDTEAMCMD_RAIDID_FIELD.name = "raidid"
GOTOGROUPRAIDTEAMCMD_RAIDID_FIELD.full_name = ".Cmd.GoToGroupRaidTeamCmd.raidid"
GOTOGROUPRAIDTEAMCMD_RAIDID_FIELD.number = 4
GOTOGROUPRAIDTEAMCMD_RAIDID_FIELD.index = 3
GOTOGROUPRAIDTEAMCMD_RAIDID_FIELD.label = 2
GOTOGROUPRAIDTEAMCMD_RAIDID_FIELD.has_default_value = false
GOTOGROUPRAIDTEAMCMD_RAIDID_FIELD.default_value = 0
GOTOGROUPRAIDTEAMCMD_RAIDID_FIELD.type = 13
GOTOGROUPRAIDTEAMCMD_RAIDID_FIELD.cpp_type = 3
GOTOGROUPRAIDTEAMCMD.name = "GoToGroupRaidTeamCmd"
GOTOGROUPRAIDTEAMCMD.full_name = ".Cmd.GoToGroupRaidTeamCmd"
GOTOGROUPRAIDTEAMCMD.nested_types = {}
GOTOGROUPRAIDTEAMCMD.enum_types = {}
GOTOGROUPRAIDTEAMCMD.fields = {
  GOTOGROUPRAIDTEAMCMD_CMD_FIELD,
  GOTOGROUPRAIDTEAMCMD_PARAM_FIELD,
  GOTOGROUPRAIDTEAMCMD_ZONEID_FIELD,
  GOTOGROUPRAIDTEAMCMD_RAIDID_FIELD
}
GOTOGROUPRAIDTEAMCMD.is_extendable = false
GOTOGROUPRAIDTEAMCMD.extensions = {}
ENTERNEXTRAIDGROUPCMD_CMD_FIELD.name = "cmd"
ENTERNEXTRAIDGROUPCMD_CMD_FIELD.full_name = ".Cmd.EnterNextRaidGroupCmd.cmd"
ENTERNEXTRAIDGROUPCMD_CMD_FIELD.number = 1
ENTERNEXTRAIDGROUPCMD_CMD_FIELD.index = 0
ENTERNEXTRAIDGROUPCMD_CMD_FIELD.label = 1
ENTERNEXTRAIDGROUPCMD_CMD_FIELD.has_default_value = true
ENTERNEXTRAIDGROUPCMD_CMD_FIELD.default_value = 69
ENTERNEXTRAIDGROUPCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
ENTERNEXTRAIDGROUPCMD_CMD_FIELD.type = 14
ENTERNEXTRAIDGROUPCMD_CMD_FIELD.cpp_type = 8
ENTERNEXTRAIDGROUPCMD_PARAM_FIELD.name = "param"
ENTERNEXTRAIDGROUPCMD_PARAM_FIELD.full_name = ".Cmd.EnterNextRaidGroupCmd.param"
ENTERNEXTRAIDGROUPCMD_PARAM_FIELD.number = 2
ENTERNEXTRAIDGROUPCMD_PARAM_FIELD.index = 1
ENTERNEXTRAIDGROUPCMD_PARAM_FIELD.label = 1
ENTERNEXTRAIDGROUPCMD_PARAM_FIELD.has_default_value = true
ENTERNEXTRAIDGROUPCMD_PARAM_FIELD.default_value = 6
ENTERNEXTRAIDGROUPCMD_PARAM_FIELD.enum_type = TEAMGROUPAIDPARAM
ENTERNEXTRAIDGROUPCMD_PARAM_FIELD.type = 14
ENTERNEXTRAIDGROUPCMD_PARAM_FIELD.cpp_type = 8
ENTERNEXTRAIDGROUPCMD.name = "EnterNextRaidGroupCmd"
ENTERNEXTRAIDGROUPCMD.full_name = ".Cmd.EnterNextRaidGroupCmd"
ENTERNEXTRAIDGROUPCMD.nested_types = {}
ENTERNEXTRAIDGROUPCMD.enum_types = {}
ENTERNEXTRAIDGROUPCMD.fields = {
  ENTERNEXTRAIDGROUPCMD_CMD_FIELD,
  ENTERNEXTRAIDGROUPCMD_PARAM_FIELD
}
ENTERNEXTRAIDGROUPCMD.is_extendable = false
ENTERNEXTRAIDGROUPCMD.extensions = {}
INVITECONFIRMRAIDTEAMGROUPCMD_CMD_FIELD.name = "cmd"
INVITECONFIRMRAIDTEAMGROUPCMD_CMD_FIELD.full_name = ".Cmd.InviteConfirmRaidTeamGroupCmd.cmd"
INVITECONFIRMRAIDTEAMGROUPCMD_CMD_FIELD.number = 1
INVITECONFIRMRAIDTEAMGROUPCMD_CMD_FIELD.index = 0
INVITECONFIRMRAIDTEAMGROUPCMD_CMD_FIELD.label = 1
INVITECONFIRMRAIDTEAMGROUPCMD_CMD_FIELD.has_default_value = true
INVITECONFIRMRAIDTEAMGROUPCMD_CMD_FIELD.default_value = 69
INVITECONFIRMRAIDTEAMGROUPCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
INVITECONFIRMRAIDTEAMGROUPCMD_CMD_FIELD.type = 14
INVITECONFIRMRAIDTEAMGROUPCMD_CMD_FIELD.cpp_type = 8
INVITECONFIRMRAIDTEAMGROUPCMD_PARAM_FIELD.name = "param"
INVITECONFIRMRAIDTEAMGROUPCMD_PARAM_FIELD.full_name = ".Cmd.InviteConfirmRaidTeamGroupCmd.param"
INVITECONFIRMRAIDTEAMGROUPCMD_PARAM_FIELD.number = 2
INVITECONFIRMRAIDTEAMGROUPCMD_PARAM_FIELD.index = 1
INVITECONFIRMRAIDTEAMGROUPCMD_PARAM_FIELD.label = 1
INVITECONFIRMRAIDTEAMGROUPCMD_PARAM_FIELD.has_default_value = true
INVITECONFIRMRAIDTEAMGROUPCMD_PARAM_FIELD.default_value = 7
INVITECONFIRMRAIDTEAMGROUPCMD_PARAM_FIELD.enum_type = TEAMGROUPAIDPARAM
INVITECONFIRMRAIDTEAMGROUPCMD_PARAM_FIELD.type = 14
INVITECONFIRMRAIDTEAMGROUPCMD_PARAM_FIELD.cpp_type = 8
INVITECONFIRMRAIDTEAMGROUPCMD_CANCEL_FIELD.name = "cancel"
INVITECONFIRMRAIDTEAMGROUPCMD_CANCEL_FIELD.full_name = ".Cmd.InviteConfirmRaidTeamGroupCmd.cancel"
INVITECONFIRMRAIDTEAMGROUPCMD_CANCEL_FIELD.number = 3
INVITECONFIRMRAIDTEAMGROUPCMD_CANCEL_FIELD.index = 2
INVITECONFIRMRAIDTEAMGROUPCMD_CANCEL_FIELD.label = 1
INVITECONFIRMRAIDTEAMGROUPCMD_CANCEL_FIELD.has_default_value = true
INVITECONFIRMRAIDTEAMGROUPCMD_CANCEL_FIELD.default_value = false
INVITECONFIRMRAIDTEAMGROUPCMD_CANCEL_FIELD.type = 8
INVITECONFIRMRAIDTEAMGROUPCMD_CANCEL_FIELD.cpp_type = 7
INVITECONFIRMRAIDTEAMGROUPCMD.name = "InviteConfirmRaidTeamGroupCmd"
INVITECONFIRMRAIDTEAMGROUPCMD.full_name = ".Cmd.InviteConfirmRaidTeamGroupCmd"
INVITECONFIRMRAIDTEAMGROUPCMD.nested_types = {}
INVITECONFIRMRAIDTEAMGROUPCMD.enum_types = {}
INVITECONFIRMRAIDTEAMGROUPCMD.fields = {
  INVITECONFIRMRAIDTEAMGROUPCMD_CMD_FIELD,
  INVITECONFIRMRAIDTEAMGROUPCMD_PARAM_FIELD,
  INVITECONFIRMRAIDTEAMGROUPCMD_CANCEL_FIELD
}
INVITECONFIRMRAIDTEAMGROUPCMD.is_extendable = false
INVITECONFIRMRAIDTEAMGROUPCMD.extensions = {}
REPLYCONFIRMRAIDTEAMGROUPCMD_CMD_FIELD.name = "cmd"
REPLYCONFIRMRAIDTEAMGROUPCMD_CMD_FIELD.full_name = ".Cmd.ReplyConfirmRaidTeamGroupCmd.cmd"
REPLYCONFIRMRAIDTEAMGROUPCMD_CMD_FIELD.number = 1
REPLYCONFIRMRAIDTEAMGROUPCMD_CMD_FIELD.index = 0
REPLYCONFIRMRAIDTEAMGROUPCMD_CMD_FIELD.label = 1
REPLYCONFIRMRAIDTEAMGROUPCMD_CMD_FIELD.has_default_value = true
REPLYCONFIRMRAIDTEAMGROUPCMD_CMD_FIELD.default_value = 69
REPLYCONFIRMRAIDTEAMGROUPCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
REPLYCONFIRMRAIDTEAMGROUPCMD_CMD_FIELD.type = 14
REPLYCONFIRMRAIDTEAMGROUPCMD_CMD_FIELD.cpp_type = 8
REPLYCONFIRMRAIDTEAMGROUPCMD_PARAM_FIELD.name = "param"
REPLYCONFIRMRAIDTEAMGROUPCMD_PARAM_FIELD.full_name = ".Cmd.ReplyConfirmRaidTeamGroupCmd.param"
REPLYCONFIRMRAIDTEAMGROUPCMD_PARAM_FIELD.number = 2
REPLYCONFIRMRAIDTEAMGROUPCMD_PARAM_FIELD.index = 1
REPLYCONFIRMRAIDTEAMGROUPCMD_PARAM_FIELD.label = 1
REPLYCONFIRMRAIDTEAMGROUPCMD_PARAM_FIELD.has_default_value = true
REPLYCONFIRMRAIDTEAMGROUPCMD_PARAM_FIELD.default_value = 8
REPLYCONFIRMRAIDTEAMGROUPCMD_PARAM_FIELD.enum_type = TEAMGROUPAIDPARAM
REPLYCONFIRMRAIDTEAMGROUPCMD_PARAM_FIELD.type = 14
REPLYCONFIRMRAIDTEAMGROUPCMD_PARAM_FIELD.cpp_type = 8
REPLYCONFIRMRAIDTEAMGROUPCMD_REPLY_FIELD.name = "reply"
REPLYCONFIRMRAIDTEAMGROUPCMD_REPLY_FIELD.full_name = ".Cmd.ReplyConfirmRaidTeamGroupCmd.reply"
REPLYCONFIRMRAIDTEAMGROUPCMD_REPLY_FIELD.number = 3
REPLYCONFIRMRAIDTEAMGROUPCMD_REPLY_FIELD.index = 2
REPLYCONFIRMRAIDTEAMGROUPCMD_REPLY_FIELD.label = 1
REPLYCONFIRMRAIDTEAMGROUPCMD_REPLY_FIELD.has_default_value = true
REPLYCONFIRMRAIDTEAMGROUPCMD_REPLY_FIELD.default_value = false
REPLYCONFIRMRAIDTEAMGROUPCMD_REPLY_FIELD.type = 8
REPLYCONFIRMRAIDTEAMGROUPCMD_REPLY_FIELD.cpp_type = 7
REPLYCONFIRMRAIDTEAMGROUPCMD_CHARID_FIELD.name = "charid"
REPLYCONFIRMRAIDTEAMGROUPCMD_CHARID_FIELD.full_name = ".Cmd.ReplyConfirmRaidTeamGroupCmd.charid"
REPLYCONFIRMRAIDTEAMGROUPCMD_CHARID_FIELD.number = 4
REPLYCONFIRMRAIDTEAMGROUPCMD_CHARID_FIELD.index = 3
REPLYCONFIRMRAIDTEAMGROUPCMD_CHARID_FIELD.label = 1
REPLYCONFIRMRAIDTEAMGROUPCMD_CHARID_FIELD.has_default_value = true
REPLYCONFIRMRAIDTEAMGROUPCMD_CHARID_FIELD.default_value = 0
REPLYCONFIRMRAIDTEAMGROUPCMD_CHARID_FIELD.type = 4
REPLYCONFIRMRAIDTEAMGROUPCMD_CHARID_FIELD.cpp_type = 4
REPLYCONFIRMRAIDTEAMGROUPCMD.name = "ReplyConfirmRaidTeamGroupCmd"
REPLYCONFIRMRAIDTEAMGROUPCMD.full_name = ".Cmd.ReplyConfirmRaidTeamGroupCmd"
REPLYCONFIRMRAIDTEAMGROUPCMD.nested_types = {}
REPLYCONFIRMRAIDTEAMGROUPCMD.enum_types = {}
REPLYCONFIRMRAIDTEAMGROUPCMD.fields = {
  REPLYCONFIRMRAIDTEAMGROUPCMD_CMD_FIELD,
  REPLYCONFIRMRAIDTEAMGROUPCMD_PARAM_FIELD,
  REPLYCONFIRMRAIDTEAMGROUPCMD_REPLY_FIELD,
  REPLYCONFIRMRAIDTEAMGROUPCMD_CHARID_FIELD
}
REPLYCONFIRMRAIDTEAMGROUPCMD.is_extendable = false
REPLYCONFIRMRAIDTEAMGROUPCMD.extensions = {}
GROUPRAIDKILLUSERINFO_CHARID_FIELD.name = "charid"
GROUPRAIDKILLUSERINFO_CHARID_FIELD.full_name = ".Cmd.GroupRaidKillUserInfo.charid"
GROUPRAIDKILLUSERINFO_CHARID_FIELD.number = 1
GROUPRAIDKILLUSERINFO_CHARID_FIELD.index = 0
GROUPRAIDKILLUSERINFO_CHARID_FIELD.label = 1
GROUPRAIDKILLUSERINFO_CHARID_FIELD.has_default_value = true
GROUPRAIDKILLUSERINFO_CHARID_FIELD.default_value = 0
GROUPRAIDKILLUSERINFO_CHARID_FIELD.type = 4
GROUPRAIDKILLUSERINFO_CHARID_FIELD.cpp_type = 4
GROUPRAIDKILLUSERINFO_PROFESSION_FIELD.name = "profession"
GROUPRAIDKILLUSERINFO_PROFESSION_FIELD.full_name = ".Cmd.GroupRaidKillUserInfo.profession"
GROUPRAIDKILLUSERINFO_PROFESSION_FIELD.number = 2
GROUPRAIDKILLUSERINFO_PROFESSION_FIELD.index = 1
GROUPRAIDKILLUSERINFO_PROFESSION_FIELD.label = 1
GROUPRAIDKILLUSERINFO_PROFESSION_FIELD.has_default_value = true
GROUPRAIDKILLUSERINFO_PROFESSION_FIELD.default_value = 0
GROUPRAIDKILLUSERINFO_PROFESSION_FIELD.enum_type = PROTOCOMMON_PB_EPROFESSION
GROUPRAIDKILLUSERINFO_PROFESSION_FIELD.type = 14
GROUPRAIDKILLUSERINFO_PROFESSION_FIELD.cpp_type = 8
GROUPRAIDKILLUSERINFO_LEVEL_FIELD.name = "level"
GROUPRAIDKILLUSERINFO_LEVEL_FIELD.full_name = ".Cmd.GroupRaidKillUserInfo.level"
GROUPRAIDKILLUSERINFO_LEVEL_FIELD.number = 3
GROUPRAIDKILLUSERINFO_LEVEL_FIELD.index = 2
GROUPRAIDKILLUSERINFO_LEVEL_FIELD.label = 1
GROUPRAIDKILLUSERINFO_LEVEL_FIELD.has_default_value = true
GROUPRAIDKILLUSERINFO_LEVEL_FIELD.default_value = 0
GROUPRAIDKILLUSERINFO_LEVEL_FIELD.type = 13
GROUPRAIDKILLUSERINFO_LEVEL_FIELD.cpp_type = 3
GROUPRAIDKILLUSERINFO_NAME_FIELD.name = "name"
GROUPRAIDKILLUSERINFO_NAME_FIELD.full_name = ".Cmd.GroupRaidKillUserInfo.name"
GROUPRAIDKILLUSERINFO_NAME_FIELD.number = 4
GROUPRAIDKILLUSERINFO_NAME_FIELD.index = 3
GROUPRAIDKILLUSERINFO_NAME_FIELD.label = 1
GROUPRAIDKILLUSERINFO_NAME_FIELD.has_default_value = false
GROUPRAIDKILLUSERINFO_NAME_FIELD.default_value = ""
GROUPRAIDKILLUSERINFO_NAME_FIELD.type = 9
GROUPRAIDKILLUSERINFO_NAME_FIELD.cpp_type = 9
GROUPRAIDKILLUSERINFO_PORTRAIT_FIELD.name = "portrait"
GROUPRAIDKILLUSERINFO_PORTRAIT_FIELD.full_name = ".Cmd.GroupRaidKillUserInfo.portrait"
GROUPRAIDKILLUSERINFO_PORTRAIT_FIELD.number = 5
GROUPRAIDKILLUSERINFO_PORTRAIT_FIELD.index = 4
GROUPRAIDKILLUSERINFO_PORTRAIT_FIELD.label = 1
GROUPRAIDKILLUSERINFO_PORTRAIT_FIELD.has_default_value = false
GROUPRAIDKILLUSERINFO_PORTRAIT_FIELD.default_value = nil
GROUPRAIDKILLUSERINFO_PORTRAIT_FIELD.message_type = ProtoCommon_pb.USERPORTRAITDATA
GROUPRAIDKILLUSERINFO_PORTRAIT_FIELD.type = 11
GROUPRAIDKILLUSERINFO_PORTRAIT_FIELD.cpp_type = 10
GROUPRAIDKILLUSERINFO_GUILDID_FIELD.name = "guildid"
GROUPRAIDKILLUSERINFO_GUILDID_FIELD.full_name = ".Cmd.GroupRaidKillUserInfo.guildid"
GROUPRAIDKILLUSERINFO_GUILDID_FIELD.number = 6
GROUPRAIDKILLUSERINFO_GUILDID_FIELD.index = 5
GROUPRAIDKILLUSERINFO_GUILDID_FIELD.label = 1
GROUPRAIDKILLUSERINFO_GUILDID_FIELD.has_default_value = true
GROUPRAIDKILLUSERINFO_GUILDID_FIELD.default_value = 0
GROUPRAIDKILLUSERINFO_GUILDID_FIELD.type = 4
GROUPRAIDKILLUSERINFO_GUILDID_FIELD.cpp_type = 4
GROUPRAIDKILLUSERINFO_GUILDNAME_FIELD.name = "guildname"
GROUPRAIDKILLUSERINFO_GUILDNAME_FIELD.full_name = ".Cmd.GroupRaidKillUserInfo.guildname"
GROUPRAIDKILLUSERINFO_GUILDNAME_FIELD.number = 7
GROUPRAIDKILLUSERINFO_GUILDNAME_FIELD.index = 6
GROUPRAIDKILLUSERINFO_GUILDNAME_FIELD.label = 1
GROUPRAIDKILLUSERINFO_GUILDNAME_FIELD.has_default_value = false
GROUPRAIDKILLUSERINFO_GUILDNAME_FIELD.default_value = ""
GROUPRAIDKILLUSERINFO_GUILDNAME_FIELD.type = 9
GROUPRAIDKILLUSERINFO_GUILDNAME_FIELD.cpp_type = 9
GROUPRAIDKILLUSERINFO.name = "GroupRaidKillUserInfo"
GROUPRAIDKILLUSERINFO.full_name = ".Cmd.GroupRaidKillUserInfo"
GROUPRAIDKILLUSERINFO.nested_types = {}
GROUPRAIDKILLUSERINFO.enum_types = {}
GROUPRAIDKILLUSERINFO.fields = {
  GROUPRAIDKILLUSERINFO_CHARID_FIELD,
  GROUPRAIDKILLUSERINFO_PROFESSION_FIELD,
  GROUPRAIDKILLUSERINFO_LEVEL_FIELD,
  GROUPRAIDKILLUSERINFO_NAME_FIELD,
  GROUPRAIDKILLUSERINFO_PORTRAIT_FIELD,
  GROUPRAIDKILLUSERINFO_GUILDID_FIELD,
  GROUPRAIDKILLUSERINFO_GUILDNAME_FIELD
}
GROUPRAIDKILLUSERINFO.is_extendable = false
GROUPRAIDKILLUSERINFO.extensions = {}
GROUPRAIDKILLGUILDINFO_GUILDID_FIELD.name = "guildid"
GROUPRAIDKILLGUILDINFO_GUILDID_FIELD.full_name = ".Cmd.GroupRaidKillGuildInfo.guildid"
GROUPRAIDKILLGUILDINFO_GUILDID_FIELD.number = 1
GROUPRAIDKILLGUILDINFO_GUILDID_FIELD.index = 0
GROUPRAIDKILLGUILDINFO_GUILDID_FIELD.label = 1
GROUPRAIDKILLGUILDINFO_GUILDID_FIELD.has_default_value = true
GROUPRAIDKILLGUILDINFO_GUILDID_FIELD.default_value = 0
GROUPRAIDKILLGUILDINFO_GUILDID_FIELD.type = 4
GROUPRAIDKILLGUILDINFO_GUILDID_FIELD.cpp_type = 4
GROUPRAIDKILLGUILDINFO_GUILDNAME_FIELD.name = "guildname"
GROUPRAIDKILLGUILDINFO_GUILDNAME_FIELD.full_name = ".Cmd.GroupRaidKillGuildInfo.guildname"
GROUPRAIDKILLGUILDINFO_GUILDNAME_FIELD.number = 2
GROUPRAIDKILLGUILDINFO_GUILDNAME_FIELD.index = 1
GROUPRAIDKILLGUILDINFO_GUILDNAME_FIELD.label = 1
GROUPRAIDKILLGUILDINFO_GUILDNAME_FIELD.has_default_value = false
GROUPRAIDKILLGUILDINFO_GUILDNAME_FIELD.default_value = ""
GROUPRAIDKILLGUILDINFO_GUILDNAME_FIELD.type = 9
GROUPRAIDKILLGUILDINFO_GUILDNAME_FIELD.cpp_type = 9
GROUPRAIDKILLGUILDINFO_GUILDPORTRAIT_FIELD.name = "guildportrait"
GROUPRAIDKILLGUILDINFO_GUILDPORTRAIT_FIELD.full_name = ".Cmd.GroupRaidKillGuildInfo.guildportrait"
GROUPRAIDKILLGUILDINFO_GUILDPORTRAIT_FIELD.number = 3
GROUPRAIDKILLGUILDINFO_GUILDPORTRAIT_FIELD.index = 2
GROUPRAIDKILLGUILDINFO_GUILDPORTRAIT_FIELD.label = 1
GROUPRAIDKILLGUILDINFO_GUILDPORTRAIT_FIELD.has_default_value = false
GROUPRAIDKILLGUILDINFO_GUILDPORTRAIT_FIELD.default_value = ""
GROUPRAIDKILLGUILDINFO_GUILDPORTRAIT_FIELD.type = 9
GROUPRAIDKILLGUILDINFO_GUILDPORTRAIT_FIELD.cpp_type = 9
GROUPRAIDKILLGUILDINFO_RANK_FIELD.name = "rank"
GROUPRAIDKILLGUILDINFO_RANK_FIELD.full_name = ".Cmd.GroupRaidKillGuildInfo.rank"
GROUPRAIDKILLGUILDINFO_RANK_FIELD.number = 4
GROUPRAIDKILLGUILDINFO_RANK_FIELD.index = 3
GROUPRAIDKILLGUILDINFO_RANK_FIELD.label = 1
GROUPRAIDKILLGUILDINFO_RANK_FIELD.has_default_value = true
GROUPRAIDKILLGUILDINFO_RANK_FIELD.default_value = 0
GROUPRAIDKILLGUILDINFO_RANK_FIELD.type = 13
GROUPRAIDKILLGUILDINFO_RANK_FIELD.cpp_type = 3
GROUPRAIDKILLGUILDINFO_TIME_FIELD.name = "time"
GROUPRAIDKILLGUILDINFO_TIME_FIELD.full_name = ".Cmd.GroupRaidKillGuildInfo.time"
GROUPRAIDKILLGUILDINFO_TIME_FIELD.number = 5
GROUPRAIDKILLGUILDINFO_TIME_FIELD.index = 4
GROUPRAIDKILLGUILDINFO_TIME_FIELD.label = 1
GROUPRAIDKILLGUILDINFO_TIME_FIELD.has_default_value = true
GROUPRAIDKILLGUILDINFO_TIME_FIELD.default_value = 0
GROUPRAIDKILLGUILDINFO_TIME_FIELD.type = 13
GROUPRAIDKILLGUILDINFO_TIME_FIELD.cpp_type = 3
GROUPRAIDKILLGUILDINFO.name = "GroupRaidKillGuildInfo"
GROUPRAIDKILLGUILDINFO.full_name = ".Cmd.GroupRaidKillGuildInfo"
GROUPRAIDKILLGUILDINFO.nested_types = {}
GROUPRAIDKILLGUILDINFO.enum_types = {}
GROUPRAIDKILLGUILDINFO.fields = {
  GROUPRAIDKILLGUILDINFO_GUILDID_FIELD,
  GROUPRAIDKILLGUILDINFO_GUILDNAME_FIELD,
  GROUPRAIDKILLGUILDINFO_GUILDPORTRAIT_FIELD,
  GROUPRAIDKILLGUILDINFO_RANK_FIELD,
  GROUPRAIDKILLGUILDINFO_TIME_FIELD
}
GROUPRAIDKILLGUILDINFO.is_extendable = false
GROUPRAIDKILLGUILDINFO.extensions = {}
GROUPRAIDKILLINFO_RAID_FIELD.name = "raid"
GROUPRAIDKILLINFO_RAID_FIELD.full_name = ".Cmd.GroupRaidKillInfo.raid"
GROUPRAIDKILLINFO_RAID_FIELD.number = 1
GROUPRAIDKILLINFO_RAID_FIELD.index = 0
GROUPRAIDKILLINFO_RAID_FIELD.label = 1
GROUPRAIDKILLINFO_RAID_FIELD.has_default_value = true
GROUPRAIDKILLINFO_RAID_FIELD.default_value = 0
GROUPRAIDKILLINFO_RAID_FIELD.type = 4
GROUPRAIDKILLINFO_RAID_FIELD.cpp_type = 4
GROUPRAIDKILLINFO_TIME_FIELD.name = "time"
GROUPRAIDKILLINFO_TIME_FIELD.full_name = ".Cmd.GroupRaidKillInfo.time"
GROUPRAIDKILLINFO_TIME_FIELD.number = 2
GROUPRAIDKILLINFO_TIME_FIELD.index = 1
GROUPRAIDKILLINFO_TIME_FIELD.label = 1
GROUPRAIDKILLINFO_TIME_FIELD.has_default_value = true
GROUPRAIDKILLINFO_TIME_FIELD.default_value = 0
GROUPRAIDKILLINFO_TIME_FIELD.type = 13
GROUPRAIDKILLINFO_TIME_FIELD.cpp_type = 3
GROUPRAIDKILLINFO_USERS_FIELD.name = "users"
GROUPRAIDKILLINFO_USERS_FIELD.full_name = ".Cmd.GroupRaidKillInfo.users"
GROUPRAIDKILLINFO_USERS_FIELD.number = 3
GROUPRAIDKILLINFO_USERS_FIELD.index = 2
GROUPRAIDKILLINFO_USERS_FIELD.label = 3
GROUPRAIDKILLINFO_USERS_FIELD.has_default_value = false
GROUPRAIDKILLINFO_USERS_FIELD.default_value = {}
GROUPRAIDKILLINFO_USERS_FIELD.message_type = GROUPRAIDKILLUSERINFO
GROUPRAIDKILLINFO_USERS_FIELD.type = 11
GROUPRAIDKILLINFO_USERS_FIELD.cpp_type = 10
GROUPRAIDKILLINFO_GUILDS_FIELD.name = "guilds"
GROUPRAIDKILLINFO_GUILDS_FIELD.full_name = ".Cmd.GroupRaidKillInfo.guilds"
GROUPRAIDKILLINFO_GUILDS_FIELD.number = 4
GROUPRAIDKILLINFO_GUILDS_FIELD.index = 3
GROUPRAIDKILLINFO_GUILDS_FIELD.label = 3
GROUPRAIDKILLINFO_GUILDS_FIELD.has_default_value = false
GROUPRAIDKILLINFO_GUILDS_FIELD.default_value = {}
GROUPRAIDKILLINFO_GUILDS_FIELD.message_type = GROUPRAIDKILLGUILDINFO
GROUPRAIDKILLINFO_GUILDS_FIELD.type = 11
GROUPRAIDKILLINFO_GUILDS_FIELD.cpp_type = 10
GROUPRAIDKILLINFO.name = "GroupRaidKillInfo"
GROUPRAIDKILLINFO.full_name = ".Cmd.GroupRaidKillInfo"
GROUPRAIDKILLINFO.nested_types = {}
GROUPRAIDKILLINFO.enum_types = {}
GROUPRAIDKILLINFO.fields = {
  GROUPRAIDKILLINFO_RAID_FIELD,
  GROUPRAIDKILLINFO_TIME_FIELD,
  GROUPRAIDKILLINFO_USERS_FIELD,
  GROUPRAIDKILLINFO_GUILDS_FIELD
}
GROUPRAIDKILLINFO.is_extendable = false
GROUPRAIDKILLINFO.extensions = {}
QUERYGROUPRAIDKILLUSERINFO_CMD_FIELD.name = "cmd"
QUERYGROUPRAIDKILLUSERINFO_CMD_FIELD.full_name = ".Cmd.QueryGroupRaidKillUserInfo.cmd"
QUERYGROUPRAIDKILLUSERINFO_CMD_FIELD.number = 1
QUERYGROUPRAIDKILLUSERINFO_CMD_FIELD.index = 0
QUERYGROUPRAIDKILLUSERINFO_CMD_FIELD.label = 1
QUERYGROUPRAIDKILLUSERINFO_CMD_FIELD.has_default_value = true
QUERYGROUPRAIDKILLUSERINFO_CMD_FIELD.default_value = 69
QUERYGROUPRAIDKILLUSERINFO_CMD_FIELD.enum_type = XCMD_PB_COMMAND
QUERYGROUPRAIDKILLUSERINFO_CMD_FIELD.type = 14
QUERYGROUPRAIDKILLUSERINFO_CMD_FIELD.cpp_type = 8
QUERYGROUPRAIDKILLUSERINFO_PARAM_FIELD.name = "param"
QUERYGROUPRAIDKILLUSERINFO_PARAM_FIELD.full_name = ".Cmd.QueryGroupRaidKillUserInfo.param"
QUERYGROUPRAIDKILLUSERINFO_PARAM_FIELD.number = 2
QUERYGROUPRAIDKILLUSERINFO_PARAM_FIELD.index = 1
QUERYGROUPRAIDKILLUSERINFO_PARAM_FIELD.label = 1
QUERYGROUPRAIDKILLUSERINFO_PARAM_FIELD.has_default_value = true
QUERYGROUPRAIDKILLUSERINFO_PARAM_FIELD.default_value = 9
QUERYGROUPRAIDKILLUSERINFO_PARAM_FIELD.enum_type = TEAMGROUPAIDPARAM
QUERYGROUPRAIDKILLUSERINFO_PARAM_FIELD.type = 14
QUERYGROUPRAIDKILLUSERINFO_PARAM_FIELD.cpp_type = 8
QUERYGROUPRAIDKILLUSERINFO_RAID_KEYS_FIELD.name = "raid_keys"
QUERYGROUPRAIDKILLUSERINFO_RAID_KEYS_FIELD.full_name = ".Cmd.QueryGroupRaidKillUserInfo.raid_keys"
QUERYGROUPRAIDKILLUSERINFO_RAID_KEYS_FIELD.number = 3
QUERYGROUPRAIDKILLUSERINFO_RAID_KEYS_FIELD.index = 2
QUERYGROUPRAIDKILLUSERINFO_RAID_KEYS_FIELD.label = 3
QUERYGROUPRAIDKILLUSERINFO_RAID_KEYS_FIELD.has_default_value = false
QUERYGROUPRAIDKILLUSERINFO_RAID_KEYS_FIELD.default_value = {}
QUERYGROUPRAIDKILLUSERINFO_RAID_KEYS_FIELD.type = 4
QUERYGROUPRAIDKILLUSERINFO_RAID_KEYS_FIELD.cpp_type = 4
QUERYGROUPRAIDKILLUSERINFO_INFOS_FIELD.name = "infos"
QUERYGROUPRAIDKILLUSERINFO_INFOS_FIELD.full_name = ".Cmd.QueryGroupRaidKillUserInfo.infos"
QUERYGROUPRAIDKILLUSERINFO_INFOS_FIELD.number = 4
QUERYGROUPRAIDKILLUSERINFO_INFOS_FIELD.index = 3
QUERYGROUPRAIDKILLUSERINFO_INFOS_FIELD.label = 3
QUERYGROUPRAIDKILLUSERINFO_INFOS_FIELD.has_default_value = false
QUERYGROUPRAIDKILLUSERINFO_INFOS_FIELD.default_value = {}
QUERYGROUPRAIDKILLUSERINFO_INFOS_FIELD.message_type = GROUPRAIDKILLINFO
QUERYGROUPRAIDKILLUSERINFO_INFOS_FIELD.type = 11
QUERYGROUPRAIDKILLUSERINFO_INFOS_FIELD.cpp_type = 10
QUERYGROUPRAIDKILLUSERINFO.name = "QueryGroupRaidKillUserInfo"
QUERYGROUPRAIDKILLUSERINFO.full_name = ".Cmd.QueryGroupRaidKillUserInfo"
QUERYGROUPRAIDKILLUSERINFO.nested_types = {}
QUERYGROUPRAIDKILLUSERINFO.enum_types = {}
QUERYGROUPRAIDKILLUSERINFO.fields = {
  QUERYGROUPRAIDKILLUSERINFO_CMD_FIELD,
  QUERYGROUPRAIDKILLUSERINFO_PARAM_FIELD,
  QUERYGROUPRAIDKILLUSERINFO_RAID_KEYS_FIELD,
  QUERYGROUPRAIDKILLUSERINFO_INFOS_FIELD
}
QUERYGROUPRAIDKILLUSERINFO.is_extendable = false
QUERYGROUPRAIDKILLUSERINFO.extensions = {}
QUERYGROUPRAIDKILLGUILDINFO_CMD_FIELD.name = "cmd"
QUERYGROUPRAIDKILLGUILDINFO_CMD_FIELD.full_name = ".Cmd.QueryGroupRaidKillGuildInfo.cmd"
QUERYGROUPRAIDKILLGUILDINFO_CMD_FIELD.number = 1
QUERYGROUPRAIDKILLGUILDINFO_CMD_FIELD.index = 0
QUERYGROUPRAIDKILLGUILDINFO_CMD_FIELD.label = 1
QUERYGROUPRAIDKILLGUILDINFO_CMD_FIELD.has_default_value = true
QUERYGROUPRAIDKILLGUILDINFO_CMD_FIELD.default_value = 69
QUERYGROUPRAIDKILLGUILDINFO_CMD_FIELD.enum_type = XCMD_PB_COMMAND
QUERYGROUPRAIDKILLGUILDINFO_CMD_FIELD.type = 14
QUERYGROUPRAIDKILLGUILDINFO_CMD_FIELD.cpp_type = 8
QUERYGROUPRAIDKILLGUILDINFO_PARAM_FIELD.name = "param"
QUERYGROUPRAIDKILLGUILDINFO_PARAM_FIELD.full_name = ".Cmd.QueryGroupRaidKillGuildInfo.param"
QUERYGROUPRAIDKILLGUILDINFO_PARAM_FIELD.number = 2
QUERYGROUPRAIDKILLGUILDINFO_PARAM_FIELD.index = 1
QUERYGROUPRAIDKILLGUILDINFO_PARAM_FIELD.label = 1
QUERYGROUPRAIDKILLGUILDINFO_PARAM_FIELD.has_default_value = true
QUERYGROUPRAIDKILLGUILDINFO_PARAM_FIELD.default_value = 10
QUERYGROUPRAIDKILLGUILDINFO_PARAM_FIELD.enum_type = TEAMGROUPAIDPARAM
QUERYGROUPRAIDKILLGUILDINFO_PARAM_FIELD.type = 14
QUERYGROUPRAIDKILLGUILDINFO_PARAM_FIELD.cpp_type = 8
QUERYGROUPRAIDKILLGUILDINFO_RAID_KEYS_FIELD.name = "raid_keys"
QUERYGROUPRAIDKILLGUILDINFO_RAID_KEYS_FIELD.full_name = ".Cmd.QueryGroupRaidKillGuildInfo.raid_keys"
QUERYGROUPRAIDKILLGUILDINFO_RAID_KEYS_FIELD.number = 3
QUERYGROUPRAIDKILLGUILDINFO_RAID_KEYS_FIELD.index = 2
QUERYGROUPRAIDKILLGUILDINFO_RAID_KEYS_FIELD.label = 3
QUERYGROUPRAIDKILLGUILDINFO_RAID_KEYS_FIELD.has_default_value = false
QUERYGROUPRAIDKILLGUILDINFO_RAID_KEYS_FIELD.default_value = {}
QUERYGROUPRAIDKILLGUILDINFO_RAID_KEYS_FIELD.type = 4
QUERYGROUPRAIDKILLGUILDINFO_RAID_KEYS_FIELD.cpp_type = 4
QUERYGROUPRAIDKILLGUILDINFO_INFOS_FIELD.name = "infos"
QUERYGROUPRAIDKILLGUILDINFO_INFOS_FIELD.full_name = ".Cmd.QueryGroupRaidKillGuildInfo.infos"
QUERYGROUPRAIDKILLGUILDINFO_INFOS_FIELD.number = 4
QUERYGROUPRAIDKILLGUILDINFO_INFOS_FIELD.index = 3
QUERYGROUPRAIDKILLGUILDINFO_INFOS_FIELD.label = 3
QUERYGROUPRAIDKILLGUILDINFO_INFOS_FIELD.has_default_value = false
QUERYGROUPRAIDKILLGUILDINFO_INFOS_FIELD.default_value = {}
QUERYGROUPRAIDKILLGUILDINFO_INFOS_FIELD.message_type = GROUPRAIDKILLINFO
QUERYGROUPRAIDKILLGUILDINFO_INFOS_FIELD.type = 11
QUERYGROUPRAIDKILLGUILDINFO_INFOS_FIELD.cpp_type = 10
QUERYGROUPRAIDKILLGUILDINFO.name = "QueryGroupRaidKillGuildInfo"
QUERYGROUPRAIDKILLGUILDINFO.full_name = ".Cmd.QueryGroupRaidKillGuildInfo"
QUERYGROUPRAIDKILLGUILDINFO.nested_types = {}
QUERYGROUPRAIDKILLGUILDINFO.enum_types = {}
QUERYGROUPRAIDKILLGUILDINFO.fields = {
  QUERYGROUPRAIDKILLGUILDINFO_CMD_FIELD,
  QUERYGROUPRAIDKILLGUILDINFO_PARAM_FIELD,
  QUERYGROUPRAIDKILLGUILDINFO_RAID_KEYS_FIELD,
  QUERYGROUPRAIDKILLGUILDINFO_INFOS_FIELD
}
QUERYGROUPRAIDKILLGUILDINFO.is_extendable = false
QUERYGROUPRAIDKILLGUILDINFO.extensions = {}
GROUPRAIDKILLUSERSHOWDATA_CHARID_FIELD.name = "charid"
GROUPRAIDKILLUSERSHOWDATA_CHARID_FIELD.full_name = ".Cmd.GroupRaidKillUserShowData.charid"
GROUPRAIDKILLUSERSHOWDATA_CHARID_FIELD.number = 1
GROUPRAIDKILLUSERSHOWDATA_CHARID_FIELD.index = 0
GROUPRAIDKILLUSERSHOWDATA_CHARID_FIELD.label = 1
GROUPRAIDKILLUSERSHOWDATA_CHARID_FIELD.has_default_value = false
GROUPRAIDKILLUSERSHOWDATA_CHARID_FIELD.default_value = 0
GROUPRAIDKILLUSERSHOWDATA_CHARID_FIELD.type = 4
GROUPRAIDKILLUSERSHOWDATA_CHARID_FIELD.cpp_type = 4
GROUPRAIDKILLUSERSHOWDATA_NAME_FIELD.name = "name"
GROUPRAIDKILLUSERSHOWDATA_NAME_FIELD.full_name = ".Cmd.GroupRaidKillUserShowData.name"
GROUPRAIDKILLUSERSHOWDATA_NAME_FIELD.number = 2
GROUPRAIDKILLUSERSHOWDATA_NAME_FIELD.index = 1
GROUPRAIDKILLUSERSHOWDATA_NAME_FIELD.label = 1
GROUPRAIDKILLUSERSHOWDATA_NAME_FIELD.has_default_value = false
GROUPRAIDKILLUSERSHOWDATA_NAME_FIELD.default_value = ""
GROUPRAIDKILLUSERSHOWDATA_NAME_FIELD.type = 9
GROUPRAIDKILLUSERSHOWDATA_NAME_FIELD.cpp_type = 9
GROUPRAIDKILLUSERSHOWDATA_LEVEL_FIELD.name = "level"
GROUPRAIDKILLUSERSHOWDATA_LEVEL_FIELD.full_name = ".Cmd.GroupRaidKillUserShowData.level"
GROUPRAIDKILLUSERSHOWDATA_LEVEL_FIELD.number = 3
GROUPRAIDKILLUSERSHOWDATA_LEVEL_FIELD.index = 2
GROUPRAIDKILLUSERSHOWDATA_LEVEL_FIELD.label = 1
GROUPRAIDKILLUSERSHOWDATA_LEVEL_FIELD.has_default_value = false
GROUPRAIDKILLUSERSHOWDATA_LEVEL_FIELD.default_value = 0
GROUPRAIDKILLUSERSHOWDATA_LEVEL_FIELD.type = 13
GROUPRAIDKILLUSERSHOWDATA_LEVEL_FIELD.cpp_type = 3
GROUPRAIDKILLUSERSHOWDATA_PROFESSION_FIELD.name = "profession"
GROUPRAIDKILLUSERSHOWDATA_PROFESSION_FIELD.full_name = ".Cmd.GroupRaidKillUserShowData.profession"
GROUPRAIDKILLUSERSHOWDATA_PROFESSION_FIELD.number = 4
GROUPRAIDKILLUSERSHOWDATA_PROFESSION_FIELD.index = 3
GROUPRAIDKILLUSERSHOWDATA_PROFESSION_FIELD.label = 1
GROUPRAIDKILLUSERSHOWDATA_PROFESSION_FIELD.has_default_value = false
GROUPRAIDKILLUSERSHOWDATA_PROFESSION_FIELD.default_value = nil
GROUPRAIDKILLUSERSHOWDATA_PROFESSION_FIELD.enum_type = PROTOCOMMON_PB_EPROFESSION
GROUPRAIDKILLUSERSHOWDATA_PROFESSION_FIELD.type = 14
GROUPRAIDKILLUSERSHOWDATA_PROFESSION_FIELD.cpp_type = 8
GROUPRAIDKILLUSERSHOWDATA_GUILDNAME_FIELD.name = "guildname"
GROUPRAIDKILLUSERSHOWDATA_GUILDNAME_FIELD.full_name = ".Cmd.GroupRaidKillUserShowData.guildname"
GROUPRAIDKILLUSERSHOWDATA_GUILDNAME_FIELD.number = 5
GROUPRAIDKILLUSERSHOWDATA_GUILDNAME_FIELD.index = 4
GROUPRAIDKILLUSERSHOWDATA_GUILDNAME_FIELD.label = 1
GROUPRAIDKILLUSERSHOWDATA_GUILDNAME_FIELD.has_default_value = false
GROUPRAIDKILLUSERSHOWDATA_GUILDNAME_FIELD.default_value = ""
GROUPRAIDKILLUSERSHOWDATA_GUILDNAME_FIELD.type = 9
GROUPRAIDKILLUSERSHOWDATA_GUILDNAME_FIELD.cpp_type = 9
GROUPRAIDKILLUSERSHOWDATA_PORTRAIT_FIELD.name = "portrait"
GROUPRAIDKILLUSERSHOWDATA_PORTRAIT_FIELD.full_name = ".Cmd.GroupRaidKillUserShowData.portrait"
GROUPRAIDKILLUSERSHOWDATA_PORTRAIT_FIELD.number = 6
GROUPRAIDKILLUSERSHOWDATA_PORTRAIT_FIELD.index = 5
GROUPRAIDKILLUSERSHOWDATA_PORTRAIT_FIELD.label = 1
GROUPRAIDKILLUSERSHOWDATA_PORTRAIT_FIELD.has_default_value = false
GROUPRAIDKILLUSERSHOWDATA_PORTRAIT_FIELD.default_value = nil
GROUPRAIDKILLUSERSHOWDATA_PORTRAIT_FIELD.message_type = ProtoCommon_pb.USERPORTRAITDATA
GROUPRAIDKILLUSERSHOWDATA_PORTRAIT_FIELD.type = 11
GROUPRAIDKILLUSERSHOWDATA_PORTRAIT_FIELD.cpp_type = 10
GROUPRAIDKILLUSERSHOWDATA.name = "GroupRaidKillUserShowData"
GROUPRAIDKILLUSERSHOWDATA.full_name = ".Cmd.GroupRaidKillUserShowData"
GROUPRAIDKILLUSERSHOWDATA.nested_types = {}
GROUPRAIDKILLUSERSHOWDATA.enum_types = {}
GROUPRAIDKILLUSERSHOWDATA.fields = {
  GROUPRAIDKILLUSERSHOWDATA_CHARID_FIELD,
  GROUPRAIDKILLUSERSHOWDATA_NAME_FIELD,
  GROUPRAIDKILLUSERSHOWDATA_LEVEL_FIELD,
  GROUPRAIDKILLUSERSHOWDATA_PROFESSION_FIELD,
  GROUPRAIDKILLUSERSHOWDATA_GUILDNAME_FIELD,
  GROUPRAIDKILLUSERSHOWDATA_PORTRAIT_FIELD
}
GROUPRAIDKILLUSERSHOWDATA.is_extendable = false
GROUPRAIDKILLUSERSHOWDATA.extensions = {}
QUERYGROUPRAIDKILLUSERSHOWDATA_CMD_FIELD.name = "cmd"
QUERYGROUPRAIDKILLUSERSHOWDATA_CMD_FIELD.full_name = ".Cmd.QueryGroupRaidKillUserShowData.cmd"
QUERYGROUPRAIDKILLUSERSHOWDATA_CMD_FIELD.number = 1
QUERYGROUPRAIDKILLUSERSHOWDATA_CMD_FIELD.index = 0
QUERYGROUPRAIDKILLUSERSHOWDATA_CMD_FIELD.label = 1
QUERYGROUPRAIDKILLUSERSHOWDATA_CMD_FIELD.has_default_value = true
QUERYGROUPRAIDKILLUSERSHOWDATA_CMD_FIELD.default_value = 69
QUERYGROUPRAIDKILLUSERSHOWDATA_CMD_FIELD.enum_type = XCMD_PB_COMMAND
QUERYGROUPRAIDKILLUSERSHOWDATA_CMD_FIELD.type = 14
QUERYGROUPRAIDKILLUSERSHOWDATA_CMD_FIELD.cpp_type = 8
QUERYGROUPRAIDKILLUSERSHOWDATA_PARAM_FIELD.name = "param"
QUERYGROUPRAIDKILLUSERSHOWDATA_PARAM_FIELD.full_name = ".Cmd.QueryGroupRaidKillUserShowData.param"
QUERYGROUPRAIDKILLUSERSHOWDATA_PARAM_FIELD.number = 2
QUERYGROUPRAIDKILLUSERSHOWDATA_PARAM_FIELD.index = 1
QUERYGROUPRAIDKILLUSERSHOWDATA_PARAM_FIELD.label = 1
QUERYGROUPRAIDKILLUSERSHOWDATA_PARAM_FIELD.has_default_value = true
QUERYGROUPRAIDKILLUSERSHOWDATA_PARAM_FIELD.default_value = 11
QUERYGROUPRAIDKILLUSERSHOWDATA_PARAM_FIELD.enum_type = TEAMGROUPAIDPARAM
QUERYGROUPRAIDKILLUSERSHOWDATA_PARAM_FIELD.type = 14
QUERYGROUPRAIDKILLUSERSHOWDATA_PARAM_FIELD.cpp_type = 8
QUERYGROUPRAIDKILLUSERSHOWDATA_CHARID_FIELD.name = "charid"
QUERYGROUPRAIDKILLUSERSHOWDATA_CHARID_FIELD.full_name = ".Cmd.QueryGroupRaidKillUserShowData.charid"
QUERYGROUPRAIDKILLUSERSHOWDATA_CHARID_FIELD.number = 3
QUERYGROUPRAIDKILLUSERSHOWDATA_CHARID_FIELD.index = 2
QUERYGROUPRAIDKILLUSERSHOWDATA_CHARID_FIELD.label = 2
QUERYGROUPRAIDKILLUSERSHOWDATA_CHARID_FIELD.has_default_value = false
QUERYGROUPRAIDKILLUSERSHOWDATA_CHARID_FIELD.default_value = 0
QUERYGROUPRAIDKILLUSERSHOWDATA_CHARID_FIELD.type = 4
QUERYGROUPRAIDKILLUSERSHOWDATA_CHARID_FIELD.cpp_type = 4
QUERYGROUPRAIDKILLUSERSHOWDATA_SHOWDATA_FIELD.name = "showdata"
QUERYGROUPRAIDKILLUSERSHOWDATA_SHOWDATA_FIELD.full_name = ".Cmd.QueryGroupRaidKillUserShowData.showdata"
QUERYGROUPRAIDKILLUSERSHOWDATA_SHOWDATA_FIELD.number = 4
QUERYGROUPRAIDKILLUSERSHOWDATA_SHOWDATA_FIELD.index = 3
QUERYGROUPRAIDKILLUSERSHOWDATA_SHOWDATA_FIELD.label = 1
QUERYGROUPRAIDKILLUSERSHOWDATA_SHOWDATA_FIELD.has_default_value = false
QUERYGROUPRAIDKILLUSERSHOWDATA_SHOWDATA_FIELD.default_value = nil
QUERYGROUPRAIDKILLUSERSHOWDATA_SHOWDATA_FIELD.message_type = GROUPRAIDKILLUSERSHOWDATA
QUERYGROUPRAIDKILLUSERSHOWDATA_SHOWDATA_FIELD.type = 11
QUERYGROUPRAIDKILLUSERSHOWDATA_SHOWDATA_FIELD.cpp_type = 10
QUERYGROUPRAIDKILLUSERSHOWDATA.name = "QueryGroupRaidKillUserShowData"
QUERYGROUPRAIDKILLUSERSHOWDATA.full_name = ".Cmd.QueryGroupRaidKillUserShowData"
QUERYGROUPRAIDKILLUSERSHOWDATA.nested_types = {}
QUERYGROUPRAIDKILLUSERSHOWDATA.enum_types = {}
QUERYGROUPRAIDKILLUSERSHOWDATA.fields = {
  QUERYGROUPRAIDKILLUSERSHOWDATA_CMD_FIELD,
  QUERYGROUPRAIDKILLUSERSHOWDATA_PARAM_FIELD,
  QUERYGROUPRAIDKILLUSERSHOWDATA_CHARID_FIELD,
  QUERYGROUPRAIDKILLUSERSHOWDATA_SHOWDATA_FIELD
}
QUERYGROUPRAIDKILLUSERSHOWDATA.is_extendable = false
QUERYGROUPRAIDKILLUSERSHOWDATA.extensions = {}
GROUPRAIDKILLRECORDDATA_RAID_FIELD.name = "raid"
GROUPRAIDKILLRECORDDATA_RAID_FIELD.full_name = ".Cmd.GroupRaidKillRecordData.raid"
GROUPRAIDKILLRECORDDATA_RAID_FIELD.number = 1
GROUPRAIDKILLRECORDDATA_RAID_FIELD.index = 0
GROUPRAIDKILLRECORDDATA_RAID_FIELD.label = 1
GROUPRAIDKILLRECORDDATA_RAID_FIELD.has_default_value = true
GROUPRAIDKILLRECORDDATA_RAID_FIELD.default_value = 0
GROUPRAIDKILLRECORDDATA_RAID_FIELD.type = 13
GROUPRAIDKILLRECORDDATA_RAID_FIELD.cpp_type = 3
GROUPRAIDKILLRECORDDATA_TIME_FIELD.name = "time"
GROUPRAIDKILLRECORDDATA_TIME_FIELD.full_name = ".Cmd.GroupRaidKillRecordData.time"
GROUPRAIDKILLRECORDDATA_TIME_FIELD.number = 2
GROUPRAIDKILLRECORDDATA_TIME_FIELD.index = 1
GROUPRAIDKILLRECORDDATA_TIME_FIELD.label = 1
GROUPRAIDKILLRECORDDATA_TIME_FIELD.has_default_value = true
GROUPRAIDKILLRECORDDATA_TIME_FIELD.default_value = 0
GROUPRAIDKILLRECORDDATA_TIME_FIELD.type = 13
GROUPRAIDKILLRECORDDATA_TIME_FIELD.cpp_type = 3
GROUPRAIDKILLRECORDDATA_USERS_FIELD.name = "users"
GROUPRAIDKILLRECORDDATA_USERS_FIELD.full_name = ".Cmd.GroupRaidKillRecordData.users"
GROUPRAIDKILLRECORDDATA_USERS_FIELD.number = 3
GROUPRAIDKILLRECORDDATA_USERS_FIELD.index = 2
GROUPRAIDKILLRECORDDATA_USERS_FIELD.label = 3
GROUPRAIDKILLRECORDDATA_USERS_FIELD.has_default_value = false
GROUPRAIDKILLRECORDDATA_USERS_FIELD.default_value = {}
GROUPRAIDKILLRECORDDATA_USERS_FIELD.message_type = GROUPRAIDKILLUSERINFO
GROUPRAIDKILLRECORDDATA_USERS_FIELD.type = 11
GROUPRAIDKILLRECORDDATA_USERS_FIELD.cpp_type = 10
GROUPRAIDKILLRECORDDATA_GUILD_FIELD.name = "guild"
GROUPRAIDKILLRECORDDATA_GUILD_FIELD.full_name = ".Cmd.GroupRaidKillRecordData.guild"
GROUPRAIDKILLRECORDDATA_GUILD_FIELD.number = 4
GROUPRAIDKILLRECORDDATA_GUILD_FIELD.index = 3
GROUPRAIDKILLRECORDDATA_GUILD_FIELD.label = 1
GROUPRAIDKILLRECORDDATA_GUILD_FIELD.has_default_value = false
GROUPRAIDKILLRECORDDATA_GUILD_FIELD.default_value = nil
GROUPRAIDKILLRECORDDATA_GUILD_FIELD.message_type = GROUPRAIDKILLGUILDINFO
GROUPRAIDKILLRECORDDATA_GUILD_FIELD.type = 11
GROUPRAIDKILLRECORDDATA_GUILD_FIELD.cpp_type = 10
GROUPRAIDKILLRECORDDATA.name = "GroupRaidKillRecordData"
GROUPRAIDKILLRECORDDATA.full_name = ".Cmd.GroupRaidKillRecordData"
GROUPRAIDKILLRECORDDATA.nested_types = {}
GROUPRAIDKILLRECORDDATA.enum_types = {}
GROUPRAIDKILLRECORDDATA.fields = {
  GROUPRAIDKILLRECORDDATA_RAID_FIELD,
  GROUPRAIDKILLRECORDDATA_TIME_FIELD,
  GROUPRAIDKILLRECORDDATA_USERS_FIELD,
  GROUPRAIDKILLRECORDDATA_GUILD_FIELD
}
GROUPRAIDKILLRECORDDATA.is_extendable = false
GROUPRAIDKILLRECORDDATA.extensions = {}
CreateGroupRaidTeamCmd = protobuf.Message(CREATEGROUPRAIDTEAMCMD)
EGROUPRAIDKILL_GUILD = 2
EGROUPRAIDKILL_MAX = 3
EGROUPRAIDKILL_MIN = 0
EGROUPRAIDKILL_NORMAL = 1
EUPDATEGROUPKILL_MIN = 0
EUPDATEGROUPKILL_SCENE_TO_SESSION = 1
EUPDATEGROUPKILL_SESSION_TO_GLOBAL = 2
EUPDATEGROUPKILL_TO_SCENE = 3
EnterNextRaidGroupCmd = protobuf.Message(ENTERNEXTRAIDGROUPCMD)
GoToGroupRaidTeamCmd = protobuf.Message(GOTOGROUPRAIDTEAMCMD)
GroupRaidKillGuildInfo = protobuf.Message(GROUPRAIDKILLGUILDINFO)
GroupRaidKillInfo = protobuf.Message(GROUPRAIDKILLINFO)
GroupRaidKillRecordData = protobuf.Message(GROUPRAIDKILLRECORDDATA)
GroupRaidKillUserInfo = protobuf.Message(GROUPRAIDKILLUSERINFO)
GroupRaidKillUserShowData = protobuf.Message(GROUPRAIDKILLUSERSHOWDATA)
InviteConfirmRaidTeamGroupCmd = protobuf.Message(INVITECONFIRMRAIDTEAMGROUPCMD)
InviteGroupJoinRaidTeamCmd = protobuf.Message(INVITEGROUPJOINRAIDTEAMCMD)
JoinGroupRaidTeamCmd = protobuf.Message(JOINGROUPRAIDTEAMCMD)
OpenGroupRaidTeamCmd = protobuf.Message(OPENGROUPRAIDTEAMCMD)
QueryGroupRaidKillGuildInfo = protobuf.Message(QUERYGROUPRAIDKILLGUILDINFO)
QueryGroupRaidKillUserInfo = protobuf.Message(QUERYGROUPRAIDKILLUSERINFO)
QueryGroupRaidKillUserShowData = protobuf.Message(QUERYGROUPRAIDKILLUSERSHOWDATA)
QueryGroupRaidStatusCmd = protobuf.Message(QUERYGROUPRAIDSTATUSCMD)
ReplyConfirmRaidTeamGroupCmd = protobuf.Message(REPLYCONFIRMRAIDTEAMGROUPCMD)
ReplyGroupJoinRaidTeamCmd = protobuf.Message(REPLYGROUPJOINRAIDTEAMCMD)
TEAMGROUPPARAM_CREATE_RAID_TOSCENE = 20
TEAMGROUPPARAM_ENTER_NEXT_RAID = 6
TEAMGROUPPARAM_ENTER_RAID = 3
TEAMGROUPPARAM_INVITE_RAID = 1
TEAMGROUPPARAM_INVITE_RAID_CONFIRM = 7
TEAMGROUPPARAM_JOIN_RAID = 4
TEAMGROUPPARAM_JOIN_RAID_TOSCENE = 21
TEAMGROUPPARAM_QUERY_GUILD_KILLINFO = 10
TEAMGROUPPARAM_QUERY_RAID_STATUS = 5
TEAMGROUPPARAM_QUERY_USER_KILLINFO = 9
TEAMGROUPPARAM_QUERY_USER_SHOWDATA = 11
TEAMGROUPPARAM_REPLY_RAID = 2
TEAMGROUPPARAM_REPLY_RAID_CONFIRM = 8
