local protobuf = protobuf
autoImport("xCmd_pb")
local xCmd_pb = xCmd_pb
autoImport("FuBenCmd_pb")
local FuBenCmd_pb = FuBenCmd_pb
autoImport("MatchCCmd_pb")
local MatchCCmd_pb = MatchCCmd_pb
module("TeamRaidCmd_pb")
TEAMRAIDPARAM = protobuf.EnumDescriptor()
TEAMRAIDPARAM_TEAMRAIDPARAM_INVITE_ENUM = protobuf.EnumValueDescriptor()
TEAMRAIDPARAM_TEAMRAIDPARAM_REPLY_ENUM = protobuf.EnumValueDescriptor()
TEAMRAIDPARAM_TEAMRAIDPARAM_ENTER_ENUM = protobuf.EnumValueDescriptor()
TEAMRAIDPARAM_TEAMRAIDPARAM_ALTMANSHOW_ENUM = protobuf.EnumValueDescriptor()
TEAMRAIDPARAM_TEAMRAIDPARAM_IMAGE_CREATE_ENUM = protobuf.EnumValueDescriptor()
TEAMRAIDPARAM_TEAMRAIDPARAM_INVITE_MATCH_ENUM = protobuf.EnumValueDescriptor()
TEAMRAIDPARAM_TEAMRAIDPARAM_REPLY_MATCH_ENUM = protobuf.EnumValueDescriptor()
TEAMRAIDPARAM_TEAMRAIDPARAM_COMODO_TEAM_RAID_CREATE_ENUM = protobuf.EnumValueDescriptor()
TEAMRAIDPARAM_TEAMRAIDPARAM_GUILD_TEAM_RAID_CREATE_ENUM = protobuf.EnumValueDescriptor()
TEAMRAIDINVITECMD = protobuf.Descriptor()
TEAMRAIDINVITECMD_CMD_FIELD = protobuf.FieldDescriptor()
TEAMRAIDINVITECMD_PARAM_FIELD = protobuf.FieldDescriptor()
TEAMRAIDINVITECMD_ISCANCEL_FIELD = protobuf.FieldDescriptor()
TEAMRAIDINVITECMD_RAID_TYPE_FIELD = protobuf.FieldDescriptor()
TEAMRAIDINVITECMD_DIFFICULTY_FIELD = protobuf.FieldDescriptor()
TEAMRAIDINVITECMD_ENTRANCEID_FIELD = protobuf.FieldDescriptor()
TEAMRAIDINVITECMD_LEFTTIME_FIELD = protobuf.FieldDescriptor()
TEAMRAIDINVITECMD_OUT_RAID_FIELD = protobuf.FieldDescriptor()
TEAMRAIDREPLYCMD = protobuf.Descriptor()
TEAMRAIDREPLYCMD_CMD_FIELD = protobuf.FieldDescriptor()
TEAMRAIDREPLYCMD_PARAM_FIELD = protobuf.FieldDescriptor()
TEAMRAIDREPLYCMD_REPLY_FIELD = protobuf.FieldDescriptor()
TEAMRAIDREPLYCMD_CHARID_FIELD = protobuf.FieldDescriptor()
TEAMRAIDREPLYCMD_RAID_TYPE_FIELD = protobuf.FieldDescriptor()
TEAMRAIDENTERCMD = protobuf.Descriptor()
TEAMRAIDENTERCMD_CMD_FIELD = protobuf.FieldDescriptor()
TEAMRAIDENTERCMD_PARAM_FIELD = protobuf.FieldDescriptor()
TEAMRAIDENTERCMD_RAID_TYPE_FIELD = protobuf.FieldDescriptor()
TEAMRAIDENTERCMD_USERID_FIELD = protobuf.FieldDescriptor()
TEAMRAIDENTERCMD_ZONEID_FIELD = protobuf.FieldDescriptor()
TEAMRAIDENTERCMD_TIME_FIELD = protobuf.FieldDescriptor()
TEAMRAIDENTERCMD_SIGN_FIELD = protobuf.FieldDescriptor()
TEAMRAIDENTERCMD_DIFFICULTY_FIELD = protobuf.FieldDescriptor()
TEAMRAIDENTERCMD_BOSSID_FIELD = protobuf.FieldDescriptor()
TEAMRAIDALTMANSHOWCMD = protobuf.Descriptor()
TEAMRAIDALTMANSHOWCMD_CMD_FIELD = protobuf.FieldDescriptor()
TEAMRAIDALTMANSHOWCMD_PARAM_FIELD = protobuf.FieldDescriptor()
TEAMRAIDALTMANSHOWCMD_LEFTTIME_FIELD = protobuf.FieldDescriptor()
TEAMRAIDALTMANSHOWCMD_KILLCOUNT_FIELD = protobuf.FieldDescriptor()
TEAMRAIDALTMANSHOWCMD_SELFKILL_FIELD = protobuf.FieldDescriptor()
TEAMRAIDIMAGECREATECMD = protobuf.Descriptor()
TEAMRAIDIMAGECREATECMD_CMD_FIELD = protobuf.FieldDescriptor()
TEAMRAIDIMAGECREATECMD_PARAM_FIELD = protobuf.FieldDescriptor()
TEAMRAIDIMAGECREATECMD_ACTIVITYID_FIELD = protobuf.FieldDescriptor()
TEAMRAIDIMAGECREATECMD_RAIDID_FIELD = protobuf.FieldDescriptor()
TEAMPVPINVITEMATCHCMD = protobuf.Descriptor()
TEAMPVPINVITEMATCHCMD_CMD_FIELD = protobuf.FieldDescriptor()
TEAMPVPINVITEMATCHCMD_PARAM_FIELD = protobuf.FieldDescriptor()
TEAMPVPINVITEMATCHCMD_PVPTYPE_FIELD = protobuf.FieldDescriptor()
TEAMPVPINVITEMATCHCMD_ISCANCEL_FIELD = protobuf.FieldDescriptor()
TEAMPVPINVITEMATCHCMD_CHARID_FIELD = protobuf.FieldDescriptor()
TEAMPVPREPLYMATCHCMD = protobuf.Descriptor()
TEAMPVPREPLYMATCHCMD_CMD_FIELD = protobuf.FieldDescriptor()
TEAMPVPREPLYMATCHCMD_PARAM_FIELD = protobuf.FieldDescriptor()
TEAMPVPREPLYMATCHCMD_PVPTYPE_FIELD = protobuf.FieldDescriptor()
TEAMPVPREPLYMATCHCMD_CHARID_FIELD = protobuf.FieldDescriptor()
TEAMPVPREPLYMATCHCMD_AGREE_FIELD = protobuf.FieldDescriptor()
COMODOTEAMRAIDCREATECMD = protobuf.Descriptor()
COMODOTEAMRAIDCREATECMD_CMD_FIELD = protobuf.FieldDescriptor()
COMODOTEAMRAIDCREATECMD_PARAM_FIELD = protobuf.FieldDescriptor()
COMODOTEAMRAIDCREATECMD_DIFFICULTY_FIELD = protobuf.FieldDescriptor()
GUILDTEAMRAIDCREATECMD = protobuf.Descriptor()
GUILDTEAMRAIDCREATECMD_CMD_FIELD = protobuf.FieldDescriptor()
GUILDTEAMRAIDCREATECMD_PARAM_FIELD = protobuf.FieldDescriptor()
GUILDTEAMRAIDCREATECMD_DIFFICULTY_FIELD = protobuf.FieldDescriptor()
TEAMRAIDPARAM_TEAMRAIDPARAM_INVITE_ENUM.name = "TEAMRAIDPARAM_INVITE"
TEAMRAIDPARAM_TEAMRAIDPARAM_INVITE_ENUM.index = 0
TEAMRAIDPARAM_TEAMRAIDPARAM_INVITE_ENUM.number = 1
TEAMRAIDPARAM_TEAMRAIDPARAM_REPLY_ENUM.name = "TEAMRAIDPARAM_REPLY"
TEAMRAIDPARAM_TEAMRAIDPARAM_REPLY_ENUM.index = 1
TEAMRAIDPARAM_TEAMRAIDPARAM_REPLY_ENUM.number = 2
TEAMRAIDPARAM_TEAMRAIDPARAM_ENTER_ENUM.name = "TEAMRAIDPARAM_ENTER"
TEAMRAIDPARAM_TEAMRAIDPARAM_ENTER_ENUM.index = 2
TEAMRAIDPARAM_TEAMRAIDPARAM_ENTER_ENUM.number = 3
TEAMRAIDPARAM_TEAMRAIDPARAM_ALTMANSHOW_ENUM.name = "TEAMRAIDPARAM_ALTMANSHOW"
TEAMRAIDPARAM_TEAMRAIDPARAM_ALTMANSHOW_ENUM.index = 3
TEAMRAIDPARAM_TEAMRAIDPARAM_ALTMANSHOW_ENUM.number = 4
TEAMRAIDPARAM_TEAMRAIDPARAM_IMAGE_CREATE_ENUM.name = "TEAMRAIDPARAM_IMAGE_CREATE"
TEAMRAIDPARAM_TEAMRAIDPARAM_IMAGE_CREATE_ENUM.index = 4
TEAMRAIDPARAM_TEAMRAIDPARAM_IMAGE_CREATE_ENUM.number = 6
TEAMRAIDPARAM_TEAMRAIDPARAM_INVITE_MATCH_ENUM.name = "TEAMRAIDPARAM_INVITE_MATCH"
TEAMRAIDPARAM_TEAMRAIDPARAM_INVITE_MATCH_ENUM.index = 5
TEAMRAIDPARAM_TEAMRAIDPARAM_INVITE_MATCH_ENUM.number = 7
TEAMRAIDPARAM_TEAMRAIDPARAM_REPLY_MATCH_ENUM.name = "TEAMRAIDPARAM_REPLY_MATCH"
TEAMRAIDPARAM_TEAMRAIDPARAM_REPLY_MATCH_ENUM.index = 6
TEAMRAIDPARAM_TEAMRAIDPARAM_REPLY_MATCH_ENUM.number = 8
TEAMRAIDPARAM_TEAMRAIDPARAM_COMODO_TEAM_RAID_CREATE_ENUM.name = "TEAMRAIDPARAM_COMODO_TEAM_RAID_CREATE"
TEAMRAIDPARAM_TEAMRAIDPARAM_COMODO_TEAM_RAID_CREATE_ENUM.index = 7
TEAMRAIDPARAM_TEAMRAIDPARAM_COMODO_TEAM_RAID_CREATE_ENUM.number = 9
TEAMRAIDPARAM_TEAMRAIDPARAM_GUILD_TEAM_RAID_CREATE_ENUM.name = "TEAMRAIDPARAM_GUILD_TEAM_RAID_CREATE"
TEAMRAIDPARAM_TEAMRAIDPARAM_GUILD_TEAM_RAID_CREATE_ENUM.index = 8
TEAMRAIDPARAM_TEAMRAIDPARAM_GUILD_TEAM_RAID_CREATE_ENUM.number = 11
TEAMRAIDPARAM.name = "TeamRaidParam"
TEAMRAIDPARAM.full_name = ".Cmd.TeamRaidParam"
TEAMRAIDPARAM.values = {
  TEAMRAIDPARAM_TEAMRAIDPARAM_INVITE_ENUM,
  TEAMRAIDPARAM_TEAMRAIDPARAM_REPLY_ENUM,
  TEAMRAIDPARAM_TEAMRAIDPARAM_ENTER_ENUM,
  TEAMRAIDPARAM_TEAMRAIDPARAM_ALTMANSHOW_ENUM,
  TEAMRAIDPARAM_TEAMRAIDPARAM_IMAGE_CREATE_ENUM,
  TEAMRAIDPARAM_TEAMRAIDPARAM_INVITE_MATCH_ENUM,
  TEAMRAIDPARAM_TEAMRAIDPARAM_REPLY_MATCH_ENUM,
  TEAMRAIDPARAM_TEAMRAIDPARAM_COMODO_TEAM_RAID_CREATE_ENUM,
  TEAMRAIDPARAM_TEAMRAIDPARAM_GUILD_TEAM_RAID_CREATE_ENUM
}
TEAMRAIDINVITECMD_CMD_FIELD.name = "cmd"
TEAMRAIDINVITECMD_CMD_FIELD.full_name = ".Cmd.TeamRaidInviteCmd.cmd"
TEAMRAIDINVITECMD_CMD_FIELD.number = 1
TEAMRAIDINVITECMD_CMD_FIELD.index = 0
TEAMRAIDINVITECMD_CMD_FIELD.label = 1
TEAMRAIDINVITECMD_CMD_FIELD.has_default_value = true
TEAMRAIDINVITECMD_CMD_FIELD.default_value = 67
TEAMRAIDINVITECMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
TEAMRAIDINVITECMD_CMD_FIELD.type = 14
TEAMRAIDINVITECMD_CMD_FIELD.cpp_type = 8
TEAMRAIDINVITECMD_PARAM_FIELD.name = "param"
TEAMRAIDINVITECMD_PARAM_FIELD.full_name = ".Cmd.TeamRaidInviteCmd.param"
TEAMRAIDINVITECMD_PARAM_FIELD.number = 2
TEAMRAIDINVITECMD_PARAM_FIELD.index = 1
TEAMRAIDINVITECMD_PARAM_FIELD.label = 1
TEAMRAIDINVITECMD_PARAM_FIELD.has_default_value = true
TEAMRAIDINVITECMD_PARAM_FIELD.default_value = 1
TEAMRAIDINVITECMD_PARAM_FIELD.enum_type = TEAMRAIDPARAM
TEAMRAIDINVITECMD_PARAM_FIELD.type = 14
TEAMRAIDINVITECMD_PARAM_FIELD.cpp_type = 8
TEAMRAIDINVITECMD_ISCANCEL_FIELD.name = "iscancel"
TEAMRAIDINVITECMD_ISCANCEL_FIELD.full_name = ".Cmd.TeamRaidInviteCmd.iscancel"
TEAMRAIDINVITECMD_ISCANCEL_FIELD.number = 3
TEAMRAIDINVITECMD_ISCANCEL_FIELD.index = 2
TEAMRAIDINVITECMD_ISCANCEL_FIELD.label = 1
TEAMRAIDINVITECMD_ISCANCEL_FIELD.has_default_value = true
TEAMRAIDINVITECMD_ISCANCEL_FIELD.default_value = false
TEAMRAIDINVITECMD_ISCANCEL_FIELD.type = 8
TEAMRAIDINVITECMD_ISCANCEL_FIELD.cpp_type = 7
TEAMRAIDINVITECMD_RAID_TYPE_FIELD.name = "raid_type"
TEAMRAIDINVITECMD_RAID_TYPE_FIELD.full_name = ".Cmd.TeamRaidInviteCmd.raid_type"
TEAMRAIDINVITECMD_RAID_TYPE_FIELD.number = 4
TEAMRAIDINVITECMD_RAID_TYPE_FIELD.index = 3
TEAMRAIDINVITECMD_RAID_TYPE_FIELD.label = 1
TEAMRAIDINVITECMD_RAID_TYPE_FIELD.has_default_value = true
TEAMRAIDINVITECMD_RAID_TYPE_FIELD.default_value = 0
TEAMRAIDINVITECMD_RAID_TYPE_FIELD.enum_type = FUBENCMD_PB_ERAIDTYPE
TEAMRAIDINVITECMD_RAID_TYPE_FIELD.type = 14
TEAMRAIDINVITECMD_RAID_TYPE_FIELD.cpp_type = 8
TEAMRAIDINVITECMD_DIFFICULTY_FIELD.name = "difficulty"
TEAMRAIDINVITECMD_DIFFICULTY_FIELD.full_name = ".Cmd.TeamRaidInviteCmd.difficulty"
TEAMRAIDINVITECMD_DIFFICULTY_FIELD.number = 5
TEAMRAIDINVITECMD_DIFFICULTY_FIELD.index = 4
TEAMRAIDINVITECMD_DIFFICULTY_FIELD.label = 1
TEAMRAIDINVITECMD_DIFFICULTY_FIELD.has_default_value = false
TEAMRAIDINVITECMD_DIFFICULTY_FIELD.default_value = 0
TEAMRAIDINVITECMD_DIFFICULTY_FIELD.type = 13
TEAMRAIDINVITECMD_DIFFICULTY_FIELD.cpp_type = 3
TEAMRAIDINVITECMD_ENTRANCEID_FIELD.name = "entranceid"
TEAMRAIDINVITECMD_ENTRANCEID_FIELD.full_name = ".Cmd.TeamRaidInviteCmd.entranceid"
TEAMRAIDINVITECMD_ENTRANCEID_FIELD.number = 6
TEAMRAIDINVITECMD_ENTRANCEID_FIELD.index = 5
TEAMRAIDINVITECMD_ENTRANCEID_FIELD.label = 1
TEAMRAIDINVITECMD_ENTRANCEID_FIELD.has_default_value = false
TEAMRAIDINVITECMD_ENTRANCEID_FIELD.default_value = 0
TEAMRAIDINVITECMD_ENTRANCEID_FIELD.type = 13
TEAMRAIDINVITECMD_ENTRANCEID_FIELD.cpp_type = 3
TEAMRAIDINVITECMD_LEFTTIME_FIELD.name = "lefttime"
TEAMRAIDINVITECMD_LEFTTIME_FIELD.full_name = ".Cmd.TeamRaidInviteCmd.lefttime"
TEAMRAIDINVITECMD_LEFTTIME_FIELD.number = 7
TEAMRAIDINVITECMD_LEFTTIME_FIELD.index = 6
TEAMRAIDINVITECMD_LEFTTIME_FIELD.label = 1
TEAMRAIDINVITECMD_LEFTTIME_FIELD.has_default_value = false
TEAMRAIDINVITECMD_LEFTTIME_FIELD.default_value = 0
TEAMRAIDINVITECMD_LEFTTIME_FIELD.type = 13
TEAMRAIDINVITECMD_LEFTTIME_FIELD.cpp_type = 3
TEAMRAIDINVITECMD_OUT_RAID_FIELD.name = "out_raid"
TEAMRAIDINVITECMD_OUT_RAID_FIELD.full_name = ".Cmd.TeamRaidInviteCmd.out_raid"
TEAMRAIDINVITECMD_OUT_RAID_FIELD.number = 8
TEAMRAIDINVITECMD_OUT_RAID_FIELD.index = 7
TEAMRAIDINVITECMD_OUT_RAID_FIELD.label = 1
TEAMRAIDINVITECMD_OUT_RAID_FIELD.has_default_value = false
TEAMRAIDINVITECMD_OUT_RAID_FIELD.default_value = false
TEAMRAIDINVITECMD_OUT_RAID_FIELD.type = 8
TEAMRAIDINVITECMD_OUT_RAID_FIELD.cpp_type = 7
TEAMRAIDINVITECMD.name = "TeamRaidInviteCmd"
TEAMRAIDINVITECMD.full_name = ".Cmd.TeamRaidInviteCmd"
TEAMRAIDINVITECMD.nested_types = {}
TEAMRAIDINVITECMD.enum_types = {}
TEAMRAIDINVITECMD.fields = {
  TEAMRAIDINVITECMD_CMD_FIELD,
  TEAMRAIDINVITECMD_PARAM_FIELD,
  TEAMRAIDINVITECMD_ISCANCEL_FIELD,
  TEAMRAIDINVITECMD_RAID_TYPE_FIELD,
  TEAMRAIDINVITECMD_DIFFICULTY_FIELD,
  TEAMRAIDINVITECMD_ENTRANCEID_FIELD,
  TEAMRAIDINVITECMD_LEFTTIME_FIELD,
  TEAMRAIDINVITECMD_OUT_RAID_FIELD
}
TEAMRAIDINVITECMD.is_extendable = false
TEAMRAIDINVITECMD.extensions = {}
TEAMRAIDREPLYCMD_CMD_FIELD.name = "cmd"
TEAMRAIDREPLYCMD_CMD_FIELD.full_name = ".Cmd.TeamRaidReplyCmd.cmd"
TEAMRAIDREPLYCMD_CMD_FIELD.number = 1
TEAMRAIDREPLYCMD_CMD_FIELD.index = 0
TEAMRAIDREPLYCMD_CMD_FIELD.label = 1
TEAMRAIDREPLYCMD_CMD_FIELD.has_default_value = true
TEAMRAIDREPLYCMD_CMD_FIELD.default_value = 67
TEAMRAIDREPLYCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
TEAMRAIDREPLYCMD_CMD_FIELD.type = 14
TEAMRAIDREPLYCMD_CMD_FIELD.cpp_type = 8
TEAMRAIDREPLYCMD_PARAM_FIELD.name = "param"
TEAMRAIDREPLYCMD_PARAM_FIELD.full_name = ".Cmd.TeamRaidReplyCmd.param"
TEAMRAIDREPLYCMD_PARAM_FIELD.number = 2
TEAMRAIDREPLYCMD_PARAM_FIELD.index = 1
TEAMRAIDREPLYCMD_PARAM_FIELD.label = 1
TEAMRAIDREPLYCMD_PARAM_FIELD.has_default_value = true
TEAMRAIDREPLYCMD_PARAM_FIELD.default_value = 2
TEAMRAIDREPLYCMD_PARAM_FIELD.enum_type = TEAMRAIDPARAM
TEAMRAIDREPLYCMD_PARAM_FIELD.type = 14
TEAMRAIDREPLYCMD_PARAM_FIELD.cpp_type = 8
TEAMRAIDREPLYCMD_REPLY_FIELD.name = "reply"
TEAMRAIDREPLYCMD_REPLY_FIELD.full_name = ".Cmd.TeamRaidReplyCmd.reply"
TEAMRAIDREPLYCMD_REPLY_FIELD.number = 3
TEAMRAIDREPLYCMD_REPLY_FIELD.index = 2
TEAMRAIDREPLYCMD_REPLY_FIELD.label = 1
TEAMRAIDREPLYCMD_REPLY_FIELD.has_default_value = true
TEAMRAIDREPLYCMD_REPLY_FIELD.default_value = false
TEAMRAIDREPLYCMD_REPLY_FIELD.type = 8
TEAMRAIDREPLYCMD_REPLY_FIELD.cpp_type = 7
TEAMRAIDREPLYCMD_CHARID_FIELD.name = "charid"
TEAMRAIDREPLYCMD_CHARID_FIELD.full_name = ".Cmd.TeamRaidReplyCmd.charid"
TEAMRAIDREPLYCMD_CHARID_FIELD.number = 4
TEAMRAIDREPLYCMD_CHARID_FIELD.index = 3
TEAMRAIDREPLYCMD_CHARID_FIELD.label = 1
TEAMRAIDREPLYCMD_CHARID_FIELD.has_default_value = true
TEAMRAIDREPLYCMD_CHARID_FIELD.default_value = 0
TEAMRAIDREPLYCMD_CHARID_FIELD.type = 4
TEAMRAIDREPLYCMD_CHARID_FIELD.cpp_type = 4
TEAMRAIDREPLYCMD_RAID_TYPE_FIELD.name = "raid_type"
TEAMRAIDREPLYCMD_RAID_TYPE_FIELD.full_name = ".Cmd.TeamRaidReplyCmd.raid_type"
TEAMRAIDREPLYCMD_RAID_TYPE_FIELD.number = 5
TEAMRAIDREPLYCMD_RAID_TYPE_FIELD.index = 4
TEAMRAIDREPLYCMD_RAID_TYPE_FIELD.label = 1
TEAMRAIDREPLYCMD_RAID_TYPE_FIELD.has_default_value = true
TEAMRAIDREPLYCMD_RAID_TYPE_FIELD.default_value = 0
TEAMRAIDREPLYCMD_RAID_TYPE_FIELD.enum_type = FUBENCMD_PB_ERAIDTYPE
TEAMRAIDREPLYCMD_RAID_TYPE_FIELD.type = 14
TEAMRAIDREPLYCMD_RAID_TYPE_FIELD.cpp_type = 8
TEAMRAIDREPLYCMD.name = "TeamRaidReplyCmd"
TEAMRAIDREPLYCMD.full_name = ".Cmd.TeamRaidReplyCmd"
TEAMRAIDREPLYCMD.nested_types = {}
TEAMRAIDREPLYCMD.enum_types = {}
TEAMRAIDREPLYCMD.fields = {
  TEAMRAIDREPLYCMD_CMD_FIELD,
  TEAMRAIDREPLYCMD_PARAM_FIELD,
  TEAMRAIDREPLYCMD_REPLY_FIELD,
  TEAMRAIDREPLYCMD_CHARID_FIELD,
  TEAMRAIDREPLYCMD_RAID_TYPE_FIELD
}
TEAMRAIDREPLYCMD.is_extendable = false
TEAMRAIDREPLYCMD.extensions = {}
TEAMRAIDENTERCMD_CMD_FIELD.name = "cmd"
TEAMRAIDENTERCMD_CMD_FIELD.full_name = ".Cmd.TeamRaidEnterCmd.cmd"
TEAMRAIDENTERCMD_CMD_FIELD.number = 1
TEAMRAIDENTERCMD_CMD_FIELD.index = 0
TEAMRAIDENTERCMD_CMD_FIELD.label = 1
TEAMRAIDENTERCMD_CMD_FIELD.has_default_value = true
TEAMRAIDENTERCMD_CMD_FIELD.default_value = 67
TEAMRAIDENTERCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
TEAMRAIDENTERCMD_CMD_FIELD.type = 14
TEAMRAIDENTERCMD_CMD_FIELD.cpp_type = 8
TEAMRAIDENTERCMD_PARAM_FIELD.name = "param"
TEAMRAIDENTERCMD_PARAM_FIELD.full_name = ".Cmd.TeamRaidEnterCmd.param"
TEAMRAIDENTERCMD_PARAM_FIELD.number = 2
TEAMRAIDENTERCMD_PARAM_FIELD.index = 1
TEAMRAIDENTERCMD_PARAM_FIELD.label = 1
TEAMRAIDENTERCMD_PARAM_FIELD.has_default_value = true
TEAMRAIDENTERCMD_PARAM_FIELD.default_value = 3
TEAMRAIDENTERCMD_PARAM_FIELD.enum_type = TEAMRAIDPARAM
TEAMRAIDENTERCMD_PARAM_FIELD.type = 14
TEAMRAIDENTERCMD_PARAM_FIELD.cpp_type = 8
TEAMRAIDENTERCMD_RAID_TYPE_FIELD.name = "raid_type"
TEAMRAIDENTERCMD_RAID_TYPE_FIELD.full_name = ".Cmd.TeamRaidEnterCmd.raid_type"
TEAMRAIDENTERCMD_RAID_TYPE_FIELD.number = 3
TEAMRAIDENTERCMD_RAID_TYPE_FIELD.index = 2
TEAMRAIDENTERCMD_RAID_TYPE_FIELD.label = 1
TEAMRAIDENTERCMD_RAID_TYPE_FIELD.has_default_value = true
TEAMRAIDENTERCMD_RAID_TYPE_FIELD.default_value = 0
TEAMRAIDENTERCMD_RAID_TYPE_FIELD.enum_type = FUBENCMD_PB_ERAIDTYPE
TEAMRAIDENTERCMD_RAID_TYPE_FIELD.type = 14
TEAMRAIDENTERCMD_RAID_TYPE_FIELD.cpp_type = 8
TEAMRAIDENTERCMD_USERID_FIELD.name = "userid"
TEAMRAIDENTERCMD_USERID_FIELD.full_name = ".Cmd.TeamRaidEnterCmd.userid"
TEAMRAIDENTERCMD_USERID_FIELD.number = 4
TEAMRAIDENTERCMD_USERID_FIELD.index = 3
TEAMRAIDENTERCMD_USERID_FIELD.label = 1
TEAMRAIDENTERCMD_USERID_FIELD.has_default_value = true
TEAMRAIDENTERCMD_USERID_FIELD.default_value = 0
TEAMRAIDENTERCMD_USERID_FIELD.type = 4
TEAMRAIDENTERCMD_USERID_FIELD.cpp_type = 4
TEAMRAIDENTERCMD_ZONEID_FIELD.name = "zoneid"
TEAMRAIDENTERCMD_ZONEID_FIELD.full_name = ".Cmd.TeamRaidEnterCmd.zoneid"
TEAMRAIDENTERCMD_ZONEID_FIELD.number = 5
TEAMRAIDENTERCMD_ZONEID_FIELD.index = 4
TEAMRAIDENTERCMD_ZONEID_FIELD.label = 1
TEAMRAIDENTERCMD_ZONEID_FIELD.has_default_value = true
TEAMRAIDENTERCMD_ZONEID_FIELD.default_value = 0
TEAMRAIDENTERCMD_ZONEID_FIELD.type = 13
TEAMRAIDENTERCMD_ZONEID_FIELD.cpp_type = 3
TEAMRAIDENTERCMD_TIME_FIELD.name = "time"
TEAMRAIDENTERCMD_TIME_FIELD.full_name = ".Cmd.TeamRaidEnterCmd.time"
TEAMRAIDENTERCMD_TIME_FIELD.number = 6
TEAMRAIDENTERCMD_TIME_FIELD.index = 5
TEAMRAIDENTERCMD_TIME_FIELD.label = 1
TEAMRAIDENTERCMD_TIME_FIELD.has_default_value = true
TEAMRAIDENTERCMD_TIME_FIELD.default_value = 0
TEAMRAIDENTERCMD_TIME_FIELD.type = 13
TEAMRAIDENTERCMD_TIME_FIELD.cpp_type = 3
TEAMRAIDENTERCMD_SIGN_FIELD.name = "sign"
TEAMRAIDENTERCMD_SIGN_FIELD.full_name = ".Cmd.TeamRaidEnterCmd.sign"
TEAMRAIDENTERCMD_SIGN_FIELD.number = 7
TEAMRAIDENTERCMD_SIGN_FIELD.index = 6
TEAMRAIDENTERCMD_SIGN_FIELD.label = 1
TEAMRAIDENTERCMD_SIGN_FIELD.has_default_value = false
TEAMRAIDENTERCMD_SIGN_FIELD.default_value = ""
TEAMRAIDENTERCMD_SIGN_FIELD.type = 9
TEAMRAIDENTERCMD_SIGN_FIELD.cpp_type = 9
TEAMRAIDENTERCMD_DIFFICULTY_FIELD.name = "difficulty"
TEAMRAIDENTERCMD_DIFFICULTY_FIELD.full_name = ".Cmd.TeamRaidEnterCmd.difficulty"
TEAMRAIDENTERCMD_DIFFICULTY_FIELD.number = 8
TEAMRAIDENTERCMD_DIFFICULTY_FIELD.index = 7
TEAMRAIDENTERCMD_DIFFICULTY_FIELD.label = 1
TEAMRAIDENTERCMD_DIFFICULTY_FIELD.has_default_value = false
TEAMRAIDENTERCMD_DIFFICULTY_FIELD.default_value = 0
TEAMRAIDENTERCMD_DIFFICULTY_FIELD.type = 13
TEAMRAIDENTERCMD_DIFFICULTY_FIELD.cpp_type = 3
TEAMRAIDENTERCMD_BOSSID_FIELD.name = "bossid"
TEAMRAIDENTERCMD_BOSSID_FIELD.full_name = ".Cmd.TeamRaidEnterCmd.bossid"
TEAMRAIDENTERCMD_BOSSID_FIELD.number = 9
TEAMRAIDENTERCMD_BOSSID_FIELD.index = 8
TEAMRAIDENTERCMD_BOSSID_FIELD.label = 1
TEAMRAIDENTERCMD_BOSSID_FIELD.has_default_value = false
TEAMRAIDENTERCMD_BOSSID_FIELD.default_value = 0
TEAMRAIDENTERCMD_BOSSID_FIELD.type = 13
TEAMRAIDENTERCMD_BOSSID_FIELD.cpp_type = 3
TEAMRAIDENTERCMD.name = "TeamRaidEnterCmd"
TEAMRAIDENTERCMD.full_name = ".Cmd.TeamRaidEnterCmd"
TEAMRAIDENTERCMD.nested_types = {}
TEAMRAIDENTERCMD.enum_types = {}
TEAMRAIDENTERCMD.fields = {
  TEAMRAIDENTERCMD_CMD_FIELD,
  TEAMRAIDENTERCMD_PARAM_FIELD,
  TEAMRAIDENTERCMD_RAID_TYPE_FIELD,
  TEAMRAIDENTERCMD_USERID_FIELD,
  TEAMRAIDENTERCMD_ZONEID_FIELD,
  TEAMRAIDENTERCMD_TIME_FIELD,
  TEAMRAIDENTERCMD_SIGN_FIELD,
  TEAMRAIDENTERCMD_DIFFICULTY_FIELD,
  TEAMRAIDENTERCMD_BOSSID_FIELD
}
TEAMRAIDENTERCMD.is_extendable = false
TEAMRAIDENTERCMD.extensions = {}
TEAMRAIDALTMANSHOWCMD_CMD_FIELD.name = "cmd"
TEAMRAIDALTMANSHOWCMD_CMD_FIELD.full_name = ".Cmd.TeamRaidAltmanShowCmd.cmd"
TEAMRAIDALTMANSHOWCMD_CMD_FIELD.number = 1
TEAMRAIDALTMANSHOWCMD_CMD_FIELD.index = 0
TEAMRAIDALTMANSHOWCMD_CMD_FIELD.label = 1
TEAMRAIDALTMANSHOWCMD_CMD_FIELD.has_default_value = true
TEAMRAIDALTMANSHOWCMD_CMD_FIELD.default_value = 67
TEAMRAIDALTMANSHOWCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
TEAMRAIDALTMANSHOWCMD_CMD_FIELD.type = 14
TEAMRAIDALTMANSHOWCMD_CMD_FIELD.cpp_type = 8
TEAMRAIDALTMANSHOWCMD_PARAM_FIELD.name = "param"
TEAMRAIDALTMANSHOWCMD_PARAM_FIELD.full_name = ".Cmd.TeamRaidAltmanShowCmd.param"
TEAMRAIDALTMANSHOWCMD_PARAM_FIELD.number = 2
TEAMRAIDALTMANSHOWCMD_PARAM_FIELD.index = 1
TEAMRAIDALTMANSHOWCMD_PARAM_FIELD.label = 1
TEAMRAIDALTMANSHOWCMD_PARAM_FIELD.has_default_value = true
TEAMRAIDALTMANSHOWCMD_PARAM_FIELD.default_value = 4
TEAMRAIDALTMANSHOWCMD_PARAM_FIELD.enum_type = TEAMRAIDPARAM
TEAMRAIDALTMANSHOWCMD_PARAM_FIELD.type = 14
TEAMRAIDALTMANSHOWCMD_PARAM_FIELD.cpp_type = 8
TEAMRAIDALTMANSHOWCMD_LEFTTIME_FIELD.name = "lefttime"
TEAMRAIDALTMANSHOWCMD_LEFTTIME_FIELD.full_name = ".Cmd.TeamRaidAltmanShowCmd.lefttime"
TEAMRAIDALTMANSHOWCMD_LEFTTIME_FIELD.number = 3
TEAMRAIDALTMANSHOWCMD_LEFTTIME_FIELD.index = 2
TEAMRAIDALTMANSHOWCMD_LEFTTIME_FIELD.label = 1
TEAMRAIDALTMANSHOWCMD_LEFTTIME_FIELD.has_default_value = true
TEAMRAIDALTMANSHOWCMD_LEFTTIME_FIELD.default_value = 0
TEAMRAIDALTMANSHOWCMD_LEFTTIME_FIELD.type = 13
TEAMRAIDALTMANSHOWCMD_LEFTTIME_FIELD.cpp_type = 3
TEAMRAIDALTMANSHOWCMD_KILLCOUNT_FIELD.name = "killcount"
TEAMRAIDALTMANSHOWCMD_KILLCOUNT_FIELD.full_name = ".Cmd.TeamRaidAltmanShowCmd.killcount"
TEAMRAIDALTMANSHOWCMD_KILLCOUNT_FIELD.number = 4
TEAMRAIDALTMANSHOWCMD_KILLCOUNT_FIELD.index = 3
TEAMRAIDALTMANSHOWCMD_KILLCOUNT_FIELD.label = 1
TEAMRAIDALTMANSHOWCMD_KILLCOUNT_FIELD.has_default_value = true
TEAMRAIDALTMANSHOWCMD_KILLCOUNT_FIELD.default_value = 0
TEAMRAIDALTMANSHOWCMD_KILLCOUNT_FIELD.type = 13
TEAMRAIDALTMANSHOWCMD_KILLCOUNT_FIELD.cpp_type = 3
TEAMRAIDALTMANSHOWCMD_SELFKILL_FIELD.name = "selfkill"
TEAMRAIDALTMANSHOWCMD_SELFKILL_FIELD.full_name = ".Cmd.TeamRaidAltmanShowCmd.selfkill"
TEAMRAIDALTMANSHOWCMD_SELFKILL_FIELD.number = 5
TEAMRAIDALTMANSHOWCMD_SELFKILL_FIELD.index = 4
TEAMRAIDALTMANSHOWCMD_SELFKILL_FIELD.label = 1
TEAMRAIDALTMANSHOWCMD_SELFKILL_FIELD.has_default_value = true
TEAMRAIDALTMANSHOWCMD_SELFKILL_FIELD.default_value = 0
TEAMRAIDALTMANSHOWCMD_SELFKILL_FIELD.type = 13
TEAMRAIDALTMANSHOWCMD_SELFKILL_FIELD.cpp_type = 3
TEAMRAIDALTMANSHOWCMD.name = "TeamRaidAltmanShowCmd"
TEAMRAIDALTMANSHOWCMD.full_name = ".Cmd.TeamRaidAltmanShowCmd"
TEAMRAIDALTMANSHOWCMD.nested_types = {}
TEAMRAIDALTMANSHOWCMD.enum_types = {}
TEAMRAIDALTMANSHOWCMD.fields = {
  TEAMRAIDALTMANSHOWCMD_CMD_FIELD,
  TEAMRAIDALTMANSHOWCMD_PARAM_FIELD,
  TEAMRAIDALTMANSHOWCMD_LEFTTIME_FIELD,
  TEAMRAIDALTMANSHOWCMD_KILLCOUNT_FIELD,
  TEAMRAIDALTMANSHOWCMD_SELFKILL_FIELD
}
TEAMRAIDALTMANSHOWCMD.is_extendable = false
TEAMRAIDALTMANSHOWCMD.extensions = {}
TEAMRAIDIMAGECREATECMD_CMD_FIELD.name = "cmd"
TEAMRAIDIMAGECREATECMD_CMD_FIELD.full_name = ".Cmd.TeamRaidImageCreateCmd.cmd"
TEAMRAIDIMAGECREATECMD_CMD_FIELD.number = 1
TEAMRAIDIMAGECREATECMD_CMD_FIELD.index = 0
TEAMRAIDIMAGECREATECMD_CMD_FIELD.label = 1
TEAMRAIDIMAGECREATECMD_CMD_FIELD.has_default_value = true
TEAMRAIDIMAGECREATECMD_CMD_FIELD.default_value = 67
TEAMRAIDIMAGECREATECMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
TEAMRAIDIMAGECREATECMD_CMD_FIELD.type = 14
TEAMRAIDIMAGECREATECMD_CMD_FIELD.cpp_type = 8
TEAMRAIDIMAGECREATECMD_PARAM_FIELD.name = "param"
TEAMRAIDIMAGECREATECMD_PARAM_FIELD.full_name = ".Cmd.TeamRaidImageCreateCmd.param"
TEAMRAIDIMAGECREATECMD_PARAM_FIELD.number = 2
TEAMRAIDIMAGECREATECMD_PARAM_FIELD.index = 1
TEAMRAIDIMAGECREATECMD_PARAM_FIELD.label = 1
TEAMRAIDIMAGECREATECMD_PARAM_FIELD.has_default_value = true
TEAMRAIDIMAGECREATECMD_PARAM_FIELD.default_value = 6
TEAMRAIDIMAGECREATECMD_PARAM_FIELD.enum_type = TEAMRAIDPARAM
TEAMRAIDIMAGECREATECMD_PARAM_FIELD.type = 14
TEAMRAIDIMAGECREATECMD_PARAM_FIELD.cpp_type = 8
TEAMRAIDIMAGECREATECMD_ACTIVITYID_FIELD.name = "activityid"
TEAMRAIDIMAGECREATECMD_ACTIVITYID_FIELD.full_name = ".Cmd.TeamRaidImageCreateCmd.activityid"
TEAMRAIDIMAGECREATECMD_ACTIVITYID_FIELD.number = 3
TEAMRAIDIMAGECREATECMD_ACTIVITYID_FIELD.index = 2
TEAMRAIDIMAGECREATECMD_ACTIVITYID_FIELD.label = 1
TEAMRAIDIMAGECREATECMD_ACTIVITYID_FIELD.has_default_value = true
TEAMRAIDIMAGECREATECMD_ACTIVITYID_FIELD.default_value = 0
TEAMRAIDIMAGECREATECMD_ACTIVITYID_FIELD.type = 13
TEAMRAIDIMAGECREATECMD_ACTIVITYID_FIELD.cpp_type = 3
TEAMRAIDIMAGECREATECMD_RAIDID_FIELD.name = "raidid"
TEAMRAIDIMAGECREATECMD_RAIDID_FIELD.full_name = ".Cmd.TeamRaidImageCreateCmd.raidid"
TEAMRAIDIMAGECREATECMD_RAIDID_FIELD.number = 4
TEAMRAIDIMAGECREATECMD_RAIDID_FIELD.index = 3
TEAMRAIDIMAGECREATECMD_RAIDID_FIELD.label = 1
TEAMRAIDIMAGECREATECMD_RAIDID_FIELD.has_default_value = true
TEAMRAIDIMAGECREATECMD_RAIDID_FIELD.default_value = 0
TEAMRAIDIMAGECREATECMD_RAIDID_FIELD.type = 13
TEAMRAIDIMAGECREATECMD_RAIDID_FIELD.cpp_type = 3
TEAMRAIDIMAGECREATECMD.name = "TeamRaidImageCreateCmd"
TEAMRAIDIMAGECREATECMD.full_name = ".Cmd.TeamRaidImageCreateCmd"
TEAMRAIDIMAGECREATECMD.nested_types = {}
TEAMRAIDIMAGECREATECMD.enum_types = {}
TEAMRAIDIMAGECREATECMD.fields = {
  TEAMRAIDIMAGECREATECMD_CMD_FIELD,
  TEAMRAIDIMAGECREATECMD_PARAM_FIELD,
  TEAMRAIDIMAGECREATECMD_ACTIVITYID_FIELD,
  TEAMRAIDIMAGECREATECMD_RAIDID_FIELD
}
TEAMRAIDIMAGECREATECMD.is_extendable = false
TEAMRAIDIMAGECREATECMD.extensions = {}
TEAMPVPINVITEMATCHCMD_CMD_FIELD.name = "cmd"
TEAMPVPINVITEMATCHCMD_CMD_FIELD.full_name = ".Cmd.TeamPvpInviteMatchCmd.cmd"
TEAMPVPINVITEMATCHCMD_CMD_FIELD.number = 1
TEAMPVPINVITEMATCHCMD_CMD_FIELD.index = 0
TEAMPVPINVITEMATCHCMD_CMD_FIELD.label = 1
TEAMPVPINVITEMATCHCMD_CMD_FIELD.has_default_value = true
TEAMPVPINVITEMATCHCMD_CMD_FIELD.default_value = 67
TEAMPVPINVITEMATCHCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
TEAMPVPINVITEMATCHCMD_CMD_FIELD.type = 14
TEAMPVPINVITEMATCHCMD_CMD_FIELD.cpp_type = 8
TEAMPVPINVITEMATCHCMD_PARAM_FIELD.name = "param"
TEAMPVPINVITEMATCHCMD_PARAM_FIELD.full_name = ".Cmd.TeamPvpInviteMatchCmd.param"
TEAMPVPINVITEMATCHCMD_PARAM_FIELD.number = 2
TEAMPVPINVITEMATCHCMD_PARAM_FIELD.index = 1
TEAMPVPINVITEMATCHCMD_PARAM_FIELD.label = 1
TEAMPVPINVITEMATCHCMD_PARAM_FIELD.has_default_value = true
TEAMPVPINVITEMATCHCMD_PARAM_FIELD.default_value = 7
TEAMPVPINVITEMATCHCMD_PARAM_FIELD.enum_type = TEAMRAIDPARAM
TEAMPVPINVITEMATCHCMD_PARAM_FIELD.type = 14
TEAMPVPINVITEMATCHCMD_PARAM_FIELD.cpp_type = 8
TEAMPVPINVITEMATCHCMD_PVPTYPE_FIELD.name = "pvptype"
TEAMPVPINVITEMATCHCMD_PVPTYPE_FIELD.full_name = ".Cmd.TeamPvpInviteMatchCmd.pvptype"
TEAMPVPINVITEMATCHCMD_PVPTYPE_FIELD.number = 3
TEAMPVPINVITEMATCHCMD_PVPTYPE_FIELD.index = 2
TEAMPVPINVITEMATCHCMD_PVPTYPE_FIELD.label = 1
TEAMPVPINVITEMATCHCMD_PVPTYPE_FIELD.has_default_value = false
TEAMPVPINVITEMATCHCMD_PVPTYPE_FIELD.default_value = nil
TEAMPVPINVITEMATCHCMD_PVPTYPE_FIELD.enum_type = MATCHCCMD_PB_EPVPTYPE
TEAMPVPINVITEMATCHCMD_PVPTYPE_FIELD.type = 14
TEAMPVPINVITEMATCHCMD_PVPTYPE_FIELD.cpp_type = 8
TEAMPVPINVITEMATCHCMD_ISCANCEL_FIELD.name = "iscancel"
TEAMPVPINVITEMATCHCMD_ISCANCEL_FIELD.full_name = ".Cmd.TeamPvpInviteMatchCmd.iscancel"
TEAMPVPINVITEMATCHCMD_ISCANCEL_FIELD.number = 4
TEAMPVPINVITEMATCHCMD_ISCANCEL_FIELD.index = 3
TEAMPVPINVITEMATCHCMD_ISCANCEL_FIELD.label = 1
TEAMPVPINVITEMATCHCMD_ISCANCEL_FIELD.has_default_value = false
TEAMPVPINVITEMATCHCMD_ISCANCEL_FIELD.default_value = false
TEAMPVPINVITEMATCHCMD_ISCANCEL_FIELD.type = 8
TEAMPVPINVITEMATCHCMD_ISCANCEL_FIELD.cpp_type = 7
TEAMPVPINVITEMATCHCMD_CHARID_FIELD.name = "charid"
TEAMPVPINVITEMATCHCMD_CHARID_FIELD.full_name = ".Cmd.TeamPvpInviteMatchCmd.charid"
TEAMPVPINVITEMATCHCMD_CHARID_FIELD.number = 5
TEAMPVPINVITEMATCHCMD_CHARID_FIELD.index = 4
TEAMPVPINVITEMATCHCMD_CHARID_FIELD.label = 1
TEAMPVPINVITEMATCHCMD_CHARID_FIELD.has_default_value = false
TEAMPVPINVITEMATCHCMD_CHARID_FIELD.default_value = 0
TEAMPVPINVITEMATCHCMD_CHARID_FIELD.type = 4
TEAMPVPINVITEMATCHCMD_CHARID_FIELD.cpp_type = 4
TEAMPVPINVITEMATCHCMD.name = "TeamPvpInviteMatchCmd"
TEAMPVPINVITEMATCHCMD.full_name = ".Cmd.TeamPvpInviteMatchCmd"
TEAMPVPINVITEMATCHCMD.nested_types = {}
TEAMPVPINVITEMATCHCMD.enum_types = {}
TEAMPVPINVITEMATCHCMD.fields = {
  TEAMPVPINVITEMATCHCMD_CMD_FIELD,
  TEAMPVPINVITEMATCHCMD_PARAM_FIELD,
  TEAMPVPINVITEMATCHCMD_PVPTYPE_FIELD,
  TEAMPVPINVITEMATCHCMD_ISCANCEL_FIELD,
  TEAMPVPINVITEMATCHCMD_CHARID_FIELD
}
TEAMPVPINVITEMATCHCMD.is_extendable = false
TEAMPVPINVITEMATCHCMD.extensions = {}
TEAMPVPREPLYMATCHCMD_CMD_FIELD.name = "cmd"
TEAMPVPREPLYMATCHCMD_CMD_FIELD.full_name = ".Cmd.TeamPvpReplyMatchCmd.cmd"
TEAMPVPREPLYMATCHCMD_CMD_FIELD.number = 1
TEAMPVPREPLYMATCHCMD_CMD_FIELD.index = 0
TEAMPVPREPLYMATCHCMD_CMD_FIELD.label = 1
TEAMPVPREPLYMATCHCMD_CMD_FIELD.has_default_value = true
TEAMPVPREPLYMATCHCMD_CMD_FIELD.default_value = 67
TEAMPVPREPLYMATCHCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
TEAMPVPREPLYMATCHCMD_CMD_FIELD.type = 14
TEAMPVPREPLYMATCHCMD_CMD_FIELD.cpp_type = 8
TEAMPVPREPLYMATCHCMD_PARAM_FIELD.name = "param"
TEAMPVPREPLYMATCHCMD_PARAM_FIELD.full_name = ".Cmd.TeamPvpReplyMatchCmd.param"
TEAMPVPREPLYMATCHCMD_PARAM_FIELD.number = 2
TEAMPVPREPLYMATCHCMD_PARAM_FIELD.index = 1
TEAMPVPREPLYMATCHCMD_PARAM_FIELD.label = 1
TEAMPVPREPLYMATCHCMD_PARAM_FIELD.has_default_value = true
TEAMPVPREPLYMATCHCMD_PARAM_FIELD.default_value = 8
TEAMPVPREPLYMATCHCMD_PARAM_FIELD.enum_type = TEAMRAIDPARAM
TEAMPVPREPLYMATCHCMD_PARAM_FIELD.type = 14
TEAMPVPREPLYMATCHCMD_PARAM_FIELD.cpp_type = 8
TEAMPVPREPLYMATCHCMD_PVPTYPE_FIELD.name = "pvptype"
TEAMPVPREPLYMATCHCMD_PVPTYPE_FIELD.full_name = ".Cmd.TeamPvpReplyMatchCmd.pvptype"
TEAMPVPREPLYMATCHCMD_PVPTYPE_FIELD.number = 3
TEAMPVPREPLYMATCHCMD_PVPTYPE_FIELD.index = 2
TEAMPVPREPLYMATCHCMD_PVPTYPE_FIELD.label = 1
TEAMPVPREPLYMATCHCMD_PVPTYPE_FIELD.has_default_value = false
TEAMPVPREPLYMATCHCMD_PVPTYPE_FIELD.default_value = nil
TEAMPVPREPLYMATCHCMD_PVPTYPE_FIELD.enum_type = MATCHCCMD_PB_EPVPTYPE
TEAMPVPREPLYMATCHCMD_PVPTYPE_FIELD.type = 14
TEAMPVPREPLYMATCHCMD_PVPTYPE_FIELD.cpp_type = 8
TEAMPVPREPLYMATCHCMD_CHARID_FIELD.name = "charid"
TEAMPVPREPLYMATCHCMD_CHARID_FIELD.full_name = ".Cmd.TeamPvpReplyMatchCmd.charid"
TEAMPVPREPLYMATCHCMD_CHARID_FIELD.number = 4
TEAMPVPREPLYMATCHCMD_CHARID_FIELD.index = 3
TEAMPVPREPLYMATCHCMD_CHARID_FIELD.label = 1
TEAMPVPREPLYMATCHCMD_CHARID_FIELD.has_default_value = false
TEAMPVPREPLYMATCHCMD_CHARID_FIELD.default_value = 0
TEAMPVPREPLYMATCHCMD_CHARID_FIELD.type = 4
TEAMPVPREPLYMATCHCMD_CHARID_FIELD.cpp_type = 4
TEAMPVPREPLYMATCHCMD_AGREE_FIELD.name = "agree"
TEAMPVPREPLYMATCHCMD_AGREE_FIELD.full_name = ".Cmd.TeamPvpReplyMatchCmd.agree"
TEAMPVPREPLYMATCHCMD_AGREE_FIELD.number = 5
TEAMPVPREPLYMATCHCMD_AGREE_FIELD.index = 4
TEAMPVPREPLYMATCHCMD_AGREE_FIELD.label = 1
TEAMPVPREPLYMATCHCMD_AGREE_FIELD.has_default_value = false
TEAMPVPREPLYMATCHCMD_AGREE_FIELD.default_value = false
TEAMPVPREPLYMATCHCMD_AGREE_FIELD.type = 8
TEAMPVPREPLYMATCHCMD_AGREE_FIELD.cpp_type = 7
TEAMPVPREPLYMATCHCMD.name = "TeamPvpReplyMatchCmd"
TEAMPVPREPLYMATCHCMD.full_name = ".Cmd.TeamPvpReplyMatchCmd"
TEAMPVPREPLYMATCHCMD.nested_types = {}
TEAMPVPREPLYMATCHCMD.enum_types = {}
TEAMPVPREPLYMATCHCMD.fields = {
  TEAMPVPREPLYMATCHCMD_CMD_FIELD,
  TEAMPVPREPLYMATCHCMD_PARAM_FIELD,
  TEAMPVPREPLYMATCHCMD_PVPTYPE_FIELD,
  TEAMPVPREPLYMATCHCMD_CHARID_FIELD,
  TEAMPVPREPLYMATCHCMD_AGREE_FIELD
}
TEAMPVPREPLYMATCHCMD.is_extendable = false
TEAMPVPREPLYMATCHCMD.extensions = {}
COMODOTEAMRAIDCREATECMD_CMD_FIELD.name = "cmd"
COMODOTEAMRAIDCREATECMD_CMD_FIELD.full_name = ".Cmd.ComodoTeamRaidCreateCmd.cmd"
COMODOTEAMRAIDCREATECMD_CMD_FIELD.number = 1
COMODOTEAMRAIDCREATECMD_CMD_FIELD.index = 0
COMODOTEAMRAIDCREATECMD_CMD_FIELD.label = 1
COMODOTEAMRAIDCREATECMD_CMD_FIELD.has_default_value = true
COMODOTEAMRAIDCREATECMD_CMD_FIELD.default_value = 67
COMODOTEAMRAIDCREATECMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
COMODOTEAMRAIDCREATECMD_CMD_FIELD.type = 14
COMODOTEAMRAIDCREATECMD_CMD_FIELD.cpp_type = 8
COMODOTEAMRAIDCREATECMD_PARAM_FIELD.name = "param"
COMODOTEAMRAIDCREATECMD_PARAM_FIELD.full_name = ".Cmd.ComodoTeamRaidCreateCmd.param"
COMODOTEAMRAIDCREATECMD_PARAM_FIELD.number = 2
COMODOTEAMRAIDCREATECMD_PARAM_FIELD.index = 1
COMODOTEAMRAIDCREATECMD_PARAM_FIELD.label = 1
COMODOTEAMRAIDCREATECMD_PARAM_FIELD.has_default_value = true
COMODOTEAMRAIDCREATECMD_PARAM_FIELD.default_value = 9
COMODOTEAMRAIDCREATECMD_PARAM_FIELD.enum_type = TEAMRAIDPARAM
COMODOTEAMRAIDCREATECMD_PARAM_FIELD.type = 14
COMODOTEAMRAIDCREATECMD_PARAM_FIELD.cpp_type = 8
COMODOTEAMRAIDCREATECMD_DIFFICULTY_FIELD.name = "difficulty"
COMODOTEAMRAIDCREATECMD_DIFFICULTY_FIELD.full_name = ".Cmd.ComodoTeamRaidCreateCmd.difficulty"
COMODOTEAMRAIDCREATECMD_DIFFICULTY_FIELD.number = 3
COMODOTEAMRAIDCREATECMD_DIFFICULTY_FIELD.index = 2
COMODOTEAMRAIDCREATECMD_DIFFICULTY_FIELD.label = 1
COMODOTEAMRAIDCREATECMD_DIFFICULTY_FIELD.has_default_value = false
COMODOTEAMRAIDCREATECMD_DIFFICULTY_FIELD.default_value = 0
COMODOTEAMRAIDCREATECMD_DIFFICULTY_FIELD.type = 13
COMODOTEAMRAIDCREATECMD_DIFFICULTY_FIELD.cpp_type = 3
COMODOTEAMRAIDCREATECMD.name = "ComodoTeamRaidCreateCmd"
COMODOTEAMRAIDCREATECMD.full_name = ".Cmd.ComodoTeamRaidCreateCmd"
COMODOTEAMRAIDCREATECMD.nested_types = {}
COMODOTEAMRAIDCREATECMD.enum_types = {}
COMODOTEAMRAIDCREATECMD.fields = {
  COMODOTEAMRAIDCREATECMD_CMD_FIELD,
  COMODOTEAMRAIDCREATECMD_PARAM_FIELD,
  COMODOTEAMRAIDCREATECMD_DIFFICULTY_FIELD
}
COMODOTEAMRAIDCREATECMD.is_extendable = false
COMODOTEAMRAIDCREATECMD.extensions = {}
GUILDTEAMRAIDCREATECMD_CMD_FIELD.name = "cmd"
GUILDTEAMRAIDCREATECMD_CMD_FIELD.full_name = ".Cmd.GuildTeamRaidCreateCmd.cmd"
GUILDTEAMRAIDCREATECMD_CMD_FIELD.number = 1
GUILDTEAMRAIDCREATECMD_CMD_FIELD.index = 0
GUILDTEAMRAIDCREATECMD_CMD_FIELD.label = 1
GUILDTEAMRAIDCREATECMD_CMD_FIELD.has_default_value = true
GUILDTEAMRAIDCREATECMD_CMD_FIELD.default_value = 67
GUILDTEAMRAIDCREATECMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
GUILDTEAMRAIDCREATECMD_CMD_FIELD.type = 14
GUILDTEAMRAIDCREATECMD_CMD_FIELD.cpp_type = 8
GUILDTEAMRAIDCREATECMD_PARAM_FIELD.name = "param"
GUILDTEAMRAIDCREATECMD_PARAM_FIELD.full_name = ".Cmd.GuildTeamRaidCreateCmd.param"
GUILDTEAMRAIDCREATECMD_PARAM_FIELD.number = 2
GUILDTEAMRAIDCREATECMD_PARAM_FIELD.index = 1
GUILDTEAMRAIDCREATECMD_PARAM_FIELD.label = 1
GUILDTEAMRAIDCREATECMD_PARAM_FIELD.has_default_value = true
GUILDTEAMRAIDCREATECMD_PARAM_FIELD.default_value = 11
GUILDTEAMRAIDCREATECMD_PARAM_FIELD.enum_type = TEAMRAIDPARAM
GUILDTEAMRAIDCREATECMD_PARAM_FIELD.type = 14
GUILDTEAMRAIDCREATECMD_PARAM_FIELD.cpp_type = 8
GUILDTEAMRAIDCREATECMD_DIFFICULTY_FIELD.name = "difficulty"
GUILDTEAMRAIDCREATECMD_DIFFICULTY_FIELD.full_name = ".Cmd.GuildTeamRaidCreateCmd.difficulty"
GUILDTEAMRAIDCREATECMD_DIFFICULTY_FIELD.number = 3
GUILDTEAMRAIDCREATECMD_DIFFICULTY_FIELD.index = 2
GUILDTEAMRAIDCREATECMD_DIFFICULTY_FIELD.label = 1
GUILDTEAMRAIDCREATECMD_DIFFICULTY_FIELD.has_default_value = false
GUILDTEAMRAIDCREATECMD_DIFFICULTY_FIELD.default_value = 0
GUILDTEAMRAIDCREATECMD_DIFFICULTY_FIELD.type = 13
GUILDTEAMRAIDCREATECMD_DIFFICULTY_FIELD.cpp_type = 3
GUILDTEAMRAIDCREATECMD.name = "GuildTeamRaidCreateCmd"
GUILDTEAMRAIDCREATECMD.full_name = ".Cmd.GuildTeamRaidCreateCmd"
GUILDTEAMRAIDCREATECMD.nested_types = {}
GUILDTEAMRAIDCREATECMD.enum_types = {}
GUILDTEAMRAIDCREATECMD.fields = {
  GUILDTEAMRAIDCREATECMD_CMD_FIELD,
  GUILDTEAMRAIDCREATECMD_PARAM_FIELD,
  GUILDTEAMRAIDCREATECMD_DIFFICULTY_FIELD
}
GUILDTEAMRAIDCREATECMD.is_extendable = false
GUILDTEAMRAIDCREATECMD.extensions = {}
ComodoTeamRaidCreateCmd = protobuf.Message(COMODOTEAMRAIDCREATECMD)
GuildTeamRaidCreateCmd = protobuf.Message(GUILDTEAMRAIDCREATECMD)
TEAMRAIDPARAM_ALTMANSHOW = 4
TEAMRAIDPARAM_COMODO_TEAM_RAID_CREATE = 9
TEAMRAIDPARAM_ENTER = 3
TEAMRAIDPARAM_GUILD_TEAM_RAID_CREATE = 11
TEAMRAIDPARAM_IMAGE_CREATE = 6
TEAMRAIDPARAM_INVITE = 1
TEAMRAIDPARAM_INVITE_MATCH = 7
TEAMRAIDPARAM_REPLY = 2
TEAMRAIDPARAM_REPLY_MATCH = 8
TeamPvpInviteMatchCmd = protobuf.Message(TEAMPVPINVITEMATCHCMD)
TeamPvpReplyMatchCmd = protobuf.Message(TEAMPVPREPLYMATCHCMD)
TeamRaidAltmanShowCmd = protobuf.Message(TEAMRAIDALTMANSHOWCMD)
TeamRaidEnterCmd = protobuf.Message(TEAMRAIDENTERCMD)
TeamRaidImageCreateCmd = protobuf.Message(TEAMRAIDIMAGECREATECMD)
TeamRaidInviteCmd = protobuf.Message(TEAMRAIDINVITECMD)
TeamRaidReplyCmd = protobuf.Message(TEAMRAIDREPLYCMD)
