local protobuf = protobuf
autoImport("xCmd_pb")
local xCmd_pb = xCmd_pb
autoImport("ProtoCommon_pb")
local ProtoCommon_pb = ProtoCommon_pb
module("TechTreeCmd_pb")
TECHTREEPARAM = protobuf.EnumDescriptor()
TECHTREEPARAM_TECHTREEPARAM_UNLOCK_ENUM = protobuf.EnumValueDescriptor()
TECHTREEPARAM_TECHTREEPARAM_SYNCINFO_ENUM = protobuf.EnumValueDescriptor()
TECHTREEPARAM_TECHTREEPARAM_TOY_UNLOCK_ENUM = protobuf.EnumValueDescriptor()
TECHTREEPARAM_TECHTREEPARAM_TOY_SYNCINFO_ENUM = protobuf.EnumValueDescriptor()
TECHTREEPARAM_TECHTREEPARAM_MAKE_TOY_ENUM = protobuf.EnumValueDescriptor()
TECHTREEPARAM_TECHTREEPARAM_TOY_TRANS_POS_ENUM = protobuf.EnumValueDescriptor()
TECHTREEPARAM_TECHTREEPARAM_GET_LEVEL_AWARD_ENUM = protobuf.EnumValueDescriptor()
TECHTREEPARAM_TECHTREEPARAM_PRODUCE_COLLECT_ENUM = protobuf.EnumValueDescriptor()
TECHTREEPARAM_TECHTREEPARAM_PRODUCE_INFO_ENUM = protobuf.EnumValueDescriptor()
TECHTREEPARAM_TECHTREEPARAM_INJECT_ENUM = protobuf.EnumValueDescriptor()
TECHTREEPARAM_TECHTREEPARAM_INJECT_INFO_ENUM = protobuf.EnumValueDescriptor()
TECHTREELEVELQUSETSTATE = protobuf.EnumDescriptor()
TECHTREELEVELQUSETSTATE_TECHTREE_LEVEL_STATE_NONE_ENUM = protobuf.EnumValueDescriptor()
TECHTREELEVELQUSETSTATE_TECHTREE_LEVEL_STATE_UNLOCK_ENUM = protobuf.EnumValueDescriptor()
TECHTREELEVELQUSETSTATE_TECHTREE_LEVEL_STATE_INPROCESS_ENUM = protobuf.EnumValueDescriptor()
TECHTREELEVELQUSETSTATE_TECHTREE_LEVEL_STATE_COMPLETE_ENUM = protobuf.EnumValueDescriptor()
TECHTREELEAFINFO = protobuf.Descriptor()
TECHTREELEAFINFO_LEAFID_FIELD = protobuf.FieldDescriptor()
TECHTREELEAFINFO_LEVEL_FIELD = protobuf.FieldDescriptor()
TECHTREEUNLOCKLEAFCMD = protobuf.Descriptor()
TECHTREEUNLOCKLEAFCMD_CMD_FIELD = protobuf.FieldDescriptor()
TECHTREEUNLOCKLEAFCMD_PARAM_FIELD = protobuf.FieldDescriptor()
TECHTREEUNLOCKLEAFCMD_LEAF_FIELD = protobuf.FieldDescriptor()
TECHTREEUNLOCKLEAFCMD_TREEID_FIELD = protobuf.FieldDescriptor()
TECHTREEUNLOCKLEAFCMD_NODEINFO_FIELD = protobuf.FieldDescriptor()
TECHTREELEVELNODEINFO = protobuf.Descriptor()
TECHTREELEVELNODEINFO_ID_FIELD = protobuf.FieldDescriptor()
TECHTREELEVELNODEINFO_AWARDED_FIELD = protobuf.FieldDescriptor()
TECHTREELEVELNODEINFO_QUESTSTATE_FIELD = protobuf.FieldDescriptor()
TECHTREEINFO = protobuf.Descriptor()
TECHTREEINFO_TREEID_FIELD = protobuf.FieldDescriptor()
TECHTREEINFO_LEAFNODE_FIELD = protobuf.FieldDescriptor()
TECHTREEINFO_NODEINFO_FIELD = protobuf.FieldDescriptor()
TECHTREESYNCLEAFCMD = protobuf.Descriptor()
TECHTREESYNCLEAFCMD_CMD_FIELD = protobuf.FieldDescriptor()
TECHTREESYNCLEAFCMD_PARAM_FIELD = protobuf.FieldDescriptor()
TECHTREESYNCLEAFCMD_LEAVES_FIELD = protobuf.FieldDescriptor()
TECHTREESYNCLEAFCMD_TREEINFO_FIELD = protobuf.FieldDescriptor()
ADDTOYDRAWINGCMD = protobuf.Descriptor()
ADDTOYDRAWINGCMD_CMD_FIELD = protobuf.FieldDescriptor()
ADDTOYDRAWINGCMD_PARAM_FIELD = protobuf.FieldDescriptor()
ADDTOYDRAWINGCMD_DRAWINGID_FIELD = protobuf.FieldDescriptor()
SYNCTOYDRAWINGCMD = protobuf.Descriptor()
SYNCTOYDRAWINGCMD_CMD_FIELD = protobuf.FieldDescriptor()
SYNCTOYDRAWINGCMD_PARAM_FIELD = protobuf.FieldDescriptor()
SYNCTOYDRAWINGCMD_DRAWINGS_FIELD = protobuf.FieldDescriptor()
TECHTREEMAKETOYCMD = protobuf.Descriptor()
TECHTREEMAKETOYCMD_CMD_FIELD = protobuf.FieldDescriptor()
TECHTREEMAKETOYCMD_PARAM_FIELD = protobuf.FieldDescriptor()
TECHTREEMAKETOYCMD_DRAWINGID_FIELD = protobuf.FieldDescriptor()
TECHTREEMAKETOYCMD_COUNT_FIELD = protobuf.FieldDescriptor()
TOYTRANSSETPOSCMD = protobuf.Descriptor()
TOYTRANSSETPOSCMD_CMD_FIELD = protobuf.FieldDescriptor()
TOYTRANSSETPOSCMD_PARAM_FIELD = protobuf.FieldDescriptor()
TOYTRANSSETPOSCMD_POS_FIELD = protobuf.FieldDescriptor()
TECHTREELEVELAWARDCMD = protobuf.Descriptor()
TECHTREELEVELAWARDCMD_CMD_FIELD = protobuf.FieldDescriptor()
TECHTREELEVELAWARDCMD_PARAM_FIELD = protobuf.FieldDescriptor()
TECHTREELEVELAWARDCMD_TREEID_FIELD = protobuf.FieldDescriptor()
TECHTREELEVELAWARDCMD_LEVELNODE_FIELD = protobuf.FieldDescriptor()
TECHTREEPRODUCECOLLECTCMD = protobuf.Descriptor()
TECHTREEPRODUCECOLLECTCMD_CMD_FIELD = protobuf.FieldDescriptor()
TECHTREEPRODUCECOLLECTCMD_PARAM_FIELD = protobuf.FieldDescriptor()
TECHTREEPRODUCECOLLECTCMD_SUCCESS_FIELD = protobuf.FieldDescriptor()
TECHTREEPRODECINFOCMD = protobuf.Descriptor()
TECHTREEPRODECINFOCMD_CMD_FIELD = protobuf.FieldDescriptor()
TECHTREEPRODECINFOCMD_PARAM_FIELD = protobuf.FieldDescriptor()
TECHTREEPRODECINFOCMD_PRODUCENUM_FIELD = protobuf.FieldDescriptor()
TECHTREEPRODECINFOCMD_PRODUCEUPPERLIMIT_FIELD = protobuf.FieldDescriptor()
TECHTREEPRODECINFOCMD_PRODECESPEED_FIELD = protobuf.FieldDescriptor()
TECHTREEPRODECINFOCMD_FIRSTOPEN_FIELD = protobuf.FieldDescriptor()
TECHTREEINJECTCMD = protobuf.Descriptor()
TECHTREEINJECTCMD_CMD_FIELD = protobuf.FieldDescriptor()
TECHTREEINJECTCMD_PARAM_FIELD = protobuf.FieldDescriptor()
TECHTREEINJECTCMD_TREEID_FIELD = protobuf.FieldDescriptor()
TECHTREEINJECTCMD_LEAFNODE_FIELD = protobuf.FieldDescriptor()
TECHTREEINJECTCMD_INJECT_NUM_FIELD = protobuf.FieldDescriptor()
TECHTREEINJECTINFOCMD = protobuf.Descriptor()
TECHTREEINJECTINFOCMD_CMD_FIELD = protobuf.FieldDescriptor()
TECHTREEINJECTINFOCMD_PARAM_FIELD = protobuf.FieldDescriptor()
TECHTREEINJECTINFOCMD_TREEID_FIELD = protobuf.FieldDescriptor()
TECHTREEINJECTINFOCMD_LEAFNODE_FIELD = protobuf.FieldDescriptor()
TECHTREEINJECTINFOCMD_INJECTED_NUM_FIELD = protobuf.FieldDescriptor()
TECHTREEINJECTINFOCMD_IS_FIRST_OPEN_FIELD = protobuf.FieldDescriptor()
TECHTREEPARAM_TECHTREEPARAM_UNLOCK_ENUM.name = "TECHTREEPARAM_UNLOCK"
TECHTREEPARAM_TECHTREEPARAM_UNLOCK_ENUM.index = 0
TECHTREEPARAM_TECHTREEPARAM_UNLOCK_ENUM.number = 1
TECHTREEPARAM_TECHTREEPARAM_SYNCINFO_ENUM.name = "TECHTREEPARAM_SYNCINFO"
TECHTREEPARAM_TECHTREEPARAM_SYNCINFO_ENUM.index = 1
TECHTREEPARAM_TECHTREEPARAM_SYNCINFO_ENUM.number = 2
TECHTREEPARAM_TECHTREEPARAM_TOY_UNLOCK_ENUM.name = "TECHTREEPARAM_TOY_UNLOCK"
TECHTREEPARAM_TECHTREEPARAM_TOY_UNLOCK_ENUM.index = 2
TECHTREEPARAM_TECHTREEPARAM_TOY_UNLOCK_ENUM.number = 3
TECHTREEPARAM_TECHTREEPARAM_TOY_SYNCINFO_ENUM.name = "TECHTREEPARAM_TOY_SYNCINFO"
TECHTREEPARAM_TECHTREEPARAM_TOY_SYNCINFO_ENUM.index = 3
TECHTREEPARAM_TECHTREEPARAM_TOY_SYNCINFO_ENUM.number = 4
TECHTREEPARAM_TECHTREEPARAM_MAKE_TOY_ENUM.name = "TECHTREEPARAM_MAKE_TOY"
TECHTREEPARAM_TECHTREEPARAM_MAKE_TOY_ENUM.index = 4
TECHTREEPARAM_TECHTREEPARAM_MAKE_TOY_ENUM.number = 5
TECHTREEPARAM_TECHTREEPARAM_TOY_TRANS_POS_ENUM.name = "TECHTREEPARAM_TOY_TRANS_POS"
TECHTREEPARAM_TECHTREEPARAM_TOY_TRANS_POS_ENUM.index = 5
TECHTREEPARAM_TECHTREEPARAM_TOY_TRANS_POS_ENUM.number = 6
TECHTREEPARAM_TECHTREEPARAM_GET_LEVEL_AWARD_ENUM.name = "TECHTREEPARAM_GET_LEVEL_AWARD"
TECHTREEPARAM_TECHTREEPARAM_GET_LEVEL_AWARD_ENUM.index = 6
TECHTREEPARAM_TECHTREEPARAM_GET_LEVEL_AWARD_ENUM.number = 7
TECHTREEPARAM_TECHTREEPARAM_PRODUCE_COLLECT_ENUM.name = "TECHTREEPARAM_PRODUCE_COLLECT"
TECHTREEPARAM_TECHTREEPARAM_PRODUCE_COLLECT_ENUM.index = 7
TECHTREEPARAM_TECHTREEPARAM_PRODUCE_COLLECT_ENUM.number = 8
TECHTREEPARAM_TECHTREEPARAM_PRODUCE_INFO_ENUM.name = "TECHTREEPARAM_PRODUCE_INFO"
TECHTREEPARAM_TECHTREEPARAM_PRODUCE_INFO_ENUM.index = 8
TECHTREEPARAM_TECHTREEPARAM_PRODUCE_INFO_ENUM.number = 9
TECHTREEPARAM_TECHTREEPARAM_INJECT_ENUM.name = "TECHTREEPARAM_INJECT"
TECHTREEPARAM_TECHTREEPARAM_INJECT_ENUM.index = 9
TECHTREEPARAM_TECHTREEPARAM_INJECT_ENUM.number = 10
TECHTREEPARAM_TECHTREEPARAM_INJECT_INFO_ENUM.name = "TECHTREEPARAM_INJECT_INFO"
TECHTREEPARAM_TECHTREEPARAM_INJECT_INFO_ENUM.index = 10
TECHTREEPARAM_TECHTREEPARAM_INJECT_INFO_ENUM.number = 11
TECHTREEPARAM.name = "TechTreeParam"
TECHTREEPARAM.full_name = ".Cmd.TechTreeParam"
TECHTREEPARAM.values = {
  TECHTREEPARAM_TECHTREEPARAM_UNLOCK_ENUM,
  TECHTREEPARAM_TECHTREEPARAM_SYNCINFO_ENUM,
  TECHTREEPARAM_TECHTREEPARAM_TOY_UNLOCK_ENUM,
  TECHTREEPARAM_TECHTREEPARAM_TOY_SYNCINFO_ENUM,
  TECHTREEPARAM_TECHTREEPARAM_MAKE_TOY_ENUM,
  TECHTREEPARAM_TECHTREEPARAM_TOY_TRANS_POS_ENUM,
  TECHTREEPARAM_TECHTREEPARAM_GET_LEVEL_AWARD_ENUM,
  TECHTREEPARAM_TECHTREEPARAM_PRODUCE_COLLECT_ENUM,
  TECHTREEPARAM_TECHTREEPARAM_PRODUCE_INFO_ENUM,
  TECHTREEPARAM_TECHTREEPARAM_INJECT_ENUM,
  TECHTREEPARAM_TECHTREEPARAM_INJECT_INFO_ENUM
}
TECHTREELEVELQUSETSTATE_TECHTREE_LEVEL_STATE_NONE_ENUM.name = "TECHTREE_LEVEL_STATE_NONE"
TECHTREELEVELQUSETSTATE_TECHTREE_LEVEL_STATE_NONE_ENUM.index = 0
TECHTREELEVELQUSETSTATE_TECHTREE_LEVEL_STATE_NONE_ENUM.number = 0
TECHTREELEVELQUSETSTATE_TECHTREE_LEVEL_STATE_UNLOCK_ENUM.name = "TECHTREE_LEVEL_STATE_UNLOCK"
TECHTREELEVELQUSETSTATE_TECHTREE_LEVEL_STATE_UNLOCK_ENUM.index = 1
TECHTREELEVELQUSETSTATE_TECHTREE_LEVEL_STATE_UNLOCK_ENUM.number = 1
TECHTREELEVELQUSETSTATE_TECHTREE_LEVEL_STATE_INPROCESS_ENUM.name = "TECHTREE_LEVEL_STATE_INPROCESS"
TECHTREELEVELQUSETSTATE_TECHTREE_LEVEL_STATE_INPROCESS_ENUM.index = 2
TECHTREELEVELQUSETSTATE_TECHTREE_LEVEL_STATE_INPROCESS_ENUM.number = 2
TECHTREELEVELQUSETSTATE_TECHTREE_LEVEL_STATE_COMPLETE_ENUM.name = "TECHTREE_LEVEL_STATE_COMPLETE"
TECHTREELEVELQUSETSTATE_TECHTREE_LEVEL_STATE_COMPLETE_ENUM.index = 3
TECHTREELEVELQUSETSTATE_TECHTREE_LEVEL_STATE_COMPLETE_ENUM.number = 3
TECHTREELEVELQUSETSTATE.name = "TechTreeLeveLQusetState"
TECHTREELEVELQUSETSTATE.full_name = ".Cmd.TechTreeLeveLQusetState"
TECHTREELEVELQUSETSTATE.values = {
  TECHTREELEVELQUSETSTATE_TECHTREE_LEVEL_STATE_NONE_ENUM,
  TECHTREELEVELQUSETSTATE_TECHTREE_LEVEL_STATE_UNLOCK_ENUM,
  TECHTREELEVELQUSETSTATE_TECHTREE_LEVEL_STATE_INPROCESS_ENUM,
  TECHTREELEVELQUSETSTATE_TECHTREE_LEVEL_STATE_COMPLETE_ENUM
}
TECHTREELEAFINFO_LEAFID_FIELD.name = "leafid"
TECHTREELEAFINFO_LEAFID_FIELD.full_name = ".Cmd.TechTreeLeafInfo.leafid"
TECHTREELEAFINFO_LEAFID_FIELD.number = 1
TECHTREELEAFINFO_LEAFID_FIELD.index = 0
TECHTREELEAFINFO_LEAFID_FIELD.label = 1
TECHTREELEAFINFO_LEAFID_FIELD.has_default_value = true
TECHTREELEAFINFO_LEAFID_FIELD.default_value = 0
TECHTREELEAFINFO_LEAFID_FIELD.type = 13
TECHTREELEAFINFO_LEAFID_FIELD.cpp_type = 3
TECHTREELEAFINFO_LEVEL_FIELD.name = "level"
TECHTREELEAFINFO_LEVEL_FIELD.full_name = ".Cmd.TechTreeLeafInfo.level"
TECHTREELEAFINFO_LEVEL_FIELD.number = 2
TECHTREELEAFINFO_LEVEL_FIELD.index = 1
TECHTREELEAFINFO_LEVEL_FIELD.label = 1
TECHTREELEAFINFO_LEVEL_FIELD.has_default_value = true
TECHTREELEAFINFO_LEVEL_FIELD.default_value = 0
TECHTREELEAFINFO_LEVEL_FIELD.type = 13
TECHTREELEAFINFO_LEVEL_FIELD.cpp_type = 3
TECHTREELEAFINFO.name = "TechTreeLeafInfo"
TECHTREELEAFINFO.full_name = ".Cmd.TechTreeLeafInfo"
TECHTREELEAFINFO.nested_types = {}
TECHTREELEAFINFO.enum_types = {}
TECHTREELEAFINFO.fields = {
  TECHTREELEAFINFO_LEAFID_FIELD,
  TECHTREELEAFINFO_LEVEL_FIELD
}
TECHTREELEAFINFO.is_extendable = false
TECHTREELEAFINFO.extensions = {}
TECHTREEUNLOCKLEAFCMD_CMD_FIELD.name = "cmd"
TECHTREEUNLOCKLEAFCMD_CMD_FIELD.full_name = ".Cmd.TechTreeUnlockLeafCmd.cmd"
TECHTREEUNLOCKLEAFCMD_CMD_FIELD.number = 1
TECHTREEUNLOCKLEAFCMD_CMD_FIELD.index = 0
TECHTREEUNLOCKLEAFCMD_CMD_FIELD.label = 1
TECHTREEUNLOCKLEAFCMD_CMD_FIELD.has_default_value = true
TECHTREEUNLOCKLEAFCMD_CMD_FIELD.default_value = 73
TECHTREEUNLOCKLEAFCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
TECHTREEUNLOCKLEAFCMD_CMD_FIELD.type = 14
TECHTREEUNLOCKLEAFCMD_CMD_FIELD.cpp_type = 8
TECHTREEUNLOCKLEAFCMD_PARAM_FIELD.name = "param"
TECHTREEUNLOCKLEAFCMD_PARAM_FIELD.full_name = ".Cmd.TechTreeUnlockLeafCmd.param"
TECHTREEUNLOCKLEAFCMD_PARAM_FIELD.number = 2
TECHTREEUNLOCKLEAFCMD_PARAM_FIELD.index = 1
TECHTREEUNLOCKLEAFCMD_PARAM_FIELD.label = 1
TECHTREEUNLOCKLEAFCMD_PARAM_FIELD.has_default_value = true
TECHTREEUNLOCKLEAFCMD_PARAM_FIELD.default_value = 1
TECHTREEUNLOCKLEAFCMD_PARAM_FIELD.enum_type = TECHTREEPARAM
TECHTREEUNLOCKLEAFCMD_PARAM_FIELD.type = 14
TECHTREEUNLOCKLEAFCMD_PARAM_FIELD.cpp_type = 8
TECHTREEUNLOCKLEAFCMD_LEAF_FIELD.name = "leaf"
TECHTREEUNLOCKLEAFCMD_LEAF_FIELD.full_name = ".Cmd.TechTreeUnlockLeafCmd.leaf"
TECHTREEUNLOCKLEAFCMD_LEAF_FIELD.number = 4
TECHTREEUNLOCKLEAFCMD_LEAF_FIELD.index = 2
TECHTREEUNLOCKLEAFCMD_LEAF_FIELD.label = 1
TECHTREEUNLOCKLEAFCMD_LEAF_FIELD.has_default_value = false
TECHTREEUNLOCKLEAFCMD_LEAF_FIELD.default_value = nil
TECHTREEUNLOCKLEAFCMD_LEAF_FIELD.message_type = TECHTREELEAFINFO
TECHTREEUNLOCKLEAFCMD_LEAF_FIELD.type = 11
TECHTREEUNLOCKLEAFCMD_LEAF_FIELD.cpp_type = 10
TECHTREEUNLOCKLEAFCMD_TREEID_FIELD.name = "treeid"
TECHTREEUNLOCKLEAFCMD_TREEID_FIELD.full_name = ".Cmd.TechTreeUnlockLeafCmd.treeid"
TECHTREEUNLOCKLEAFCMD_TREEID_FIELD.number = 5
TECHTREEUNLOCKLEAFCMD_TREEID_FIELD.index = 3
TECHTREEUNLOCKLEAFCMD_TREEID_FIELD.label = 1
TECHTREEUNLOCKLEAFCMD_TREEID_FIELD.has_default_value = false
TECHTREEUNLOCKLEAFCMD_TREEID_FIELD.default_value = 0
TECHTREEUNLOCKLEAFCMD_TREEID_FIELD.type = 13
TECHTREEUNLOCKLEAFCMD_TREEID_FIELD.cpp_type = 3
TECHTREEUNLOCKLEAFCMD_NODEINFO_FIELD.name = "nodeinfo"
TECHTREEUNLOCKLEAFCMD_NODEINFO_FIELD.full_name = ".Cmd.TechTreeUnlockLeafCmd.nodeinfo"
TECHTREEUNLOCKLEAFCMD_NODEINFO_FIELD.number = 6
TECHTREEUNLOCKLEAFCMD_NODEINFO_FIELD.index = 4
TECHTREEUNLOCKLEAFCMD_NODEINFO_FIELD.label = 3
TECHTREEUNLOCKLEAFCMD_NODEINFO_FIELD.has_default_value = false
TECHTREEUNLOCKLEAFCMD_NODEINFO_FIELD.default_value = {}
TECHTREEUNLOCKLEAFCMD_NODEINFO_FIELD.message_type = _TECHTREELEVELNODEINFO
TECHTREEUNLOCKLEAFCMD_NODEINFO_FIELD.type = 11
TECHTREEUNLOCKLEAFCMD_NODEINFO_FIELD.cpp_type = 10
TECHTREEUNLOCKLEAFCMD.name = "TechTreeUnlockLeafCmd"
TECHTREEUNLOCKLEAFCMD.full_name = ".Cmd.TechTreeUnlockLeafCmd"
TECHTREEUNLOCKLEAFCMD.nested_types = {}
TECHTREEUNLOCKLEAFCMD.enum_types = {}
TECHTREEUNLOCKLEAFCMD.fields = {
  TECHTREEUNLOCKLEAFCMD_CMD_FIELD,
  TECHTREEUNLOCKLEAFCMD_PARAM_FIELD,
  TECHTREEUNLOCKLEAFCMD_LEAF_FIELD,
  TECHTREEUNLOCKLEAFCMD_TREEID_FIELD,
  TECHTREEUNLOCKLEAFCMD_NODEINFO_FIELD
}
TECHTREEUNLOCKLEAFCMD.is_extendable = false
TECHTREEUNLOCKLEAFCMD.extensions = {}
TECHTREELEVELNODEINFO_ID_FIELD.name = "id"
TECHTREELEVELNODEINFO_ID_FIELD.full_name = ".Cmd.TechTreeLevelNodeInfo.id"
TECHTREELEVELNODEINFO_ID_FIELD.number = 1
TECHTREELEVELNODEINFO_ID_FIELD.index = 0
TECHTREELEVELNODEINFO_ID_FIELD.label = 1
TECHTREELEVELNODEINFO_ID_FIELD.has_default_value = false
TECHTREELEVELNODEINFO_ID_FIELD.default_value = 0
TECHTREELEVELNODEINFO_ID_FIELD.type = 13
TECHTREELEVELNODEINFO_ID_FIELD.cpp_type = 3
TECHTREELEVELNODEINFO_AWARDED_FIELD.name = "awarded"
TECHTREELEVELNODEINFO_AWARDED_FIELD.full_name = ".Cmd.TechTreeLevelNodeInfo.awarded"
TECHTREELEVELNODEINFO_AWARDED_FIELD.number = 2
TECHTREELEVELNODEINFO_AWARDED_FIELD.index = 1
TECHTREELEVELNODEINFO_AWARDED_FIELD.label = 1
TECHTREELEVELNODEINFO_AWARDED_FIELD.has_default_value = false
TECHTREELEVELNODEINFO_AWARDED_FIELD.default_value = false
TECHTREELEVELNODEINFO_AWARDED_FIELD.type = 8
TECHTREELEVELNODEINFO_AWARDED_FIELD.cpp_type = 7
TECHTREELEVELNODEINFO_QUESTSTATE_FIELD.name = "queststate"
TECHTREELEVELNODEINFO_QUESTSTATE_FIELD.full_name = ".Cmd.TechTreeLevelNodeInfo.queststate"
TECHTREELEVELNODEINFO_QUESTSTATE_FIELD.number = 3
TECHTREELEVELNODEINFO_QUESTSTATE_FIELD.index = 2
TECHTREELEVELNODEINFO_QUESTSTATE_FIELD.label = 1
TECHTREELEVELNODEINFO_QUESTSTATE_FIELD.has_default_value = false
TECHTREELEVELNODEINFO_QUESTSTATE_FIELD.default_value = nil
TECHTREELEVELNODEINFO_QUESTSTATE_FIELD.enum_type = TECHTREELEVELQUSETSTATE
TECHTREELEVELNODEINFO_QUESTSTATE_FIELD.type = 14
TECHTREELEVELNODEINFO_QUESTSTATE_FIELD.cpp_type = 8
TECHTREELEVELNODEINFO.name = "TechTreeLevelNodeInfo"
TECHTREELEVELNODEINFO.full_name = ".Cmd.TechTreeLevelNodeInfo"
TECHTREELEVELNODEINFO.nested_types = {}
TECHTREELEVELNODEINFO.enum_types = {}
TECHTREELEVELNODEINFO.fields = {
  TECHTREELEVELNODEINFO_ID_FIELD,
  TECHTREELEVELNODEINFO_AWARDED_FIELD,
  TECHTREELEVELNODEINFO_QUESTSTATE_FIELD
}
TECHTREELEVELNODEINFO.is_extendable = false
TECHTREELEVELNODEINFO.extensions = {}
TECHTREEINFO_TREEID_FIELD.name = "treeid"
TECHTREEINFO_TREEID_FIELD.full_name = ".Cmd.TechTreeInfo.treeid"
TECHTREEINFO_TREEID_FIELD.number = 1
TECHTREEINFO_TREEID_FIELD.index = 0
TECHTREEINFO_TREEID_FIELD.label = 1
TECHTREEINFO_TREEID_FIELD.has_default_value = false
TECHTREEINFO_TREEID_FIELD.default_value = 0
TECHTREEINFO_TREEID_FIELD.type = 13
TECHTREEINFO_TREEID_FIELD.cpp_type = 3
TECHTREEINFO_LEAFNODE_FIELD.name = "leafnode"
TECHTREEINFO_LEAFNODE_FIELD.full_name = ".Cmd.TechTreeInfo.leafnode"
TECHTREEINFO_LEAFNODE_FIELD.number = 2
TECHTREEINFO_LEAFNODE_FIELD.index = 1
TECHTREEINFO_LEAFNODE_FIELD.label = 3
TECHTREEINFO_LEAFNODE_FIELD.has_default_value = false
TECHTREEINFO_LEAFNODE_FIELD.default_value = {}
TECHTREEINFO_LEAFNODE_FIELD.type = 13
TECHTREEINFO_LEAFNODE_FIELD.cpp_type = 3
TECHTREEINFO_NODEINFO_FIELD.name = "nodeinfo"
TECHTREEINFO_NODEINFO_FIELD.full_name = ".Cmd.TechTreeInfo.nodeinfo"
TECHTREEINFO_NODEINFO_FIELD.number = 3
TECHTREEINFO_NODEINFO_FIELD.index = 2
TECHTREEINFO_NODEINFO_FIELD.label = 3
TECHTREEINFO_NODEINFO_FIELD.has_default_value = false
TECHTREEINFO_NODEINFO_FIELD.default_value = {}
TECHTREEINFO_NODEINFO_FIELD.message_type = TECHTREELEVELNODEINFO
TECHTREEINFO_NODEINFO_FIELD.type = 11
TECHTREEINFO_NODEINFO_FIELD.cpp_type = 10
TECHTREEINFO.name = "TechTreeInfo"
TECHTREEINFO.full_name = ".Cmd.TechTreeInfo"
TECHTREEINFO.nested_types = {}
TECHTREEINFO.enum_types = {}
TECHTREEINFO.fields = {
  TECHTREEINFO_TREEID_FIELD,
  TECHTREEINFO_LEAFNODE_FIELD,
  TECHTREEINFO_NODEINFO_FIELD
}
TECHTREEINFO.is_extendable = false
TECHTREEINFO.extensions = {}
TECHTREESYNCLEAFCMD_CMD_FIELD.name = "cmd"
TECHTREESYNCLEAFCMD_CMD_FIELD.full_name = ".Cmd.TechTreeSyncLeafCmd.cmd"
TECHTREESYNCLEAFCMD_CMD_FIELD.number = 1
TECHTREESYNCLEAFCMD_CMD_FIELD.index = 0
TECHTREESYNCLEAFCMD_CMD_FIELD.label = 1
TECHTREESYNCLEAFCMD_CMD_FIELD.has_default_value = true
TECHTREESYNCLEAFCMD_CMD_FIELD.default_value = 73
TECHTREESYNCLEAFCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
TECHTREESYNCLEAFCMD_CMD_FIELD.type = 14
TECHTREESYNCLEAFCMD_CMD_FIELD.cpp_type = 8
TECHTREESYNCLEAFCMD_PARAM_FIELD.name = "param"
TECHTREESYNCLEAFCMD_PARAM_FIELD.full_name = ".Cmd.TechTreeSyncLeafCmd.param"
TECHTREESYNCLEAFCMD_PARAM_FIELD.number = 2
TECHTREESYNCLEAFCMD_PARAM_FIELD.index = 1
TECHTREESYNCLEAFCMD_PARAM_FIELD.label = 1
TECHTREESYNCLEAFCMD_PARAM_FIELD.has_default_value = true
TECHTREESYNCLEAFCMD_PARAM_FIELD.default_value = 2
TECHTREESYNCLEAFCMD_PARAM_FIELD.enum_type = TECHTREEPARAM
TECHTREESYNCLEAFCMD_PARAM_FIELD.type = 14
TECHTREESYNCLEAFCMD_PARAM_FIELD.cpp_type = 8
TECHTREESYNCLEAFCMD_LEAVES_FIELD.name = "leaves"
TECHTREESYNCLEAFCMD_LEAVES_FIELD.full_name = ".Cmd.TechTreeSyncLeafCmd.leaves"
TECHTREESYNCLEAFCMD_LEAVES_FIELD.number = 3
TECHTREESYNCLEAFCMD_LEAVES_FIELD.index = 2
TECHTREESYNCLEAFCMD_LEAVES_FIELD.label = 3
TECHTREESYNCLEAFCMD_LEAVES_FIELD.has_default_value = false
TECHTREESYNCLEAFCMD_LEAVES_FIELD.default_value = {}
TECHTREESYNCLEAFCMD_LEAVES_FIELD.message_type = TECHTREELEAFINFO
TECHTREESYNCLEAFCMD_LEAVES_FIELD.type = 11
TECHTREESYNCLEAFCMD_LEAVES_FIELD.cpp_type = 10
TECHTREESYNCLEAFCMD_TREEINFO_FIELD.name = "treeinfo"
TECHTREESYNCLEAFCMD_TREEINFO_FIELD.full_name = ".Cmd.TechTreeSyncLeafCmd.treeinfo"
TECHTREESYNCLEAFCMD_TREEINFO_FIELD.number = 4
TECHTREESYNCLEAFCMD_TREEINFO_FIELD.index = 3
TECHTREESYNCLEAFCMD_TREEINFO_FIELD.label = 3
TECHTREESYNCLEAFCMD_TREEINFO_FIELD.has_default_value = false
TECHTREESYNCLEAFCMD_TREEINFO_FIELD.default_value = {}
TECHTREESYNCLEAFCMD_TREEINFO_FIELD.message_type = TECHTREEINFO
TECHTREESYNCLEAFCMD_TREEINFO_FIELD.type = 11
TECHTREESYNCLEAFCMD_TREEINFO_FIELD.cpp_type = 10
TECHTREESYNCLEAFCMD.name = "TechTreeSyncLeafCmd"
TECHTREESYNCLEAFCMD.full_name = ".Cmd.TechTreeSyncLeafCmd"
TECHTREESYNCLEAFCMD.nested_types = {}
TECHTREESYNCLEAFCMD.enum_types = {}
TECHTREESYNCLEAFCMD.fields = {
  TECHTREESYNCLEAFCMD_CMD_FIELD,
  TECHTREESYNCLEAFCMD_PARAM_FIELD,
  TECHTREESYNCLEAFCMD_LEAVES_FIELD,
  TECHTREESYNCLEAFCMD_TREEINFO_FIELD
}
TECHTREESYNCLEAFCMD.is_extendable = false
TECHTREESYNCLEAFCMD.extensions = {}
ADDTOYDRAWINGCMD_CMD_FIELD.name = "cmd"
ADDTOYDRAWINGCMD_CMD_FIELD.full_name = ".Cmd.AddToyDrawingCmd.cmd"
ADDTOYDRAWINGCMD_CMD_FIELD.number = 1
ADDTOYDRAWINGCMD_CMD_FIELD.index = 0
ADDTOYDRAWINGCMD_CMD_FIELD.label = 1
ADDTOYDRAWINGCMD_CMD_FIELD.has_default_value = true
ADDTOYDRAWINGCMD_CMD_FIELD.default_value = 73
ADDTOYDRAWINGCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
ADDTOYDRAWINGCMD_CMD_FIELD.type = 14
ADDTOYDRAWINGCMD_CMD_FIELD.cpp_type = 8
ADDTOYDRAWINGCMD_PARAM_FIELD.name = "param"
ADDTOYDRAWINGCMD_PARAM_FIELD.full_name = ".Cmd.AddToyDrawingCmd.param"
ADDTOYDRAWINGCMD_PARAM_FIELD.number = 2
ADDTOYDRAWINGCMD_PARAM_FIELD.index = 1
ADDTOYDRAWINGCMD_PARAM_FIELD.label = 1
ADDTOYDRAWINGCMD_PARAM_FIELD.has_default_value = true
ADDTOYDRAWINGCMD_PARAM_FIELD.default_value = 3
ADDTOYDRAWINGCMD_PARAM_FIELD.enum_type = TECHTREEPARAM
ADDTOYDRAWINGCMD_PARAM_FIELD.type = 14
ADDTOYDRAWINGCMD_PARAM_FIELD.cpp_type = 8
ADDTOYDRAWINGCMD_DRAWINGID_FIELD.name = "drawingid"
ADDTOYDRAWINGCMD_DRAWINGID_FIELD.full_name = ".Cmd.AddToyDrawingCmd.drawingid"
ADDTOYDRAWINGCMD_DRAWINGID_FIELD.number = 3
ADDTOYDRAWINGCMD_DRAWINGID_FIELD.index = 2
ADDTOYDRAWINGCMD_DRAWINGID_FIELD.label = 1
ADDTOYDRAWINGCMD_DRAWINGID_FIELD.has_default_value = true
ADDTOYDRAWINGCMD_DRAWINGID_FIELD.default_value = 0
ADDTOYDRAWINGCMD_DRAWINGID_FIELD.type = 13
ADDTOYDRAWINGCMD_DRAWINGID_FIELD.cpp_type = 3
ADDTOYDRAWINGCMD.name = "AddToyDrawingCmd"
ADDTOYDRAWINGCMD.full_name = ".Cmd.AddToyDrawingCmd"
ADDTOYDRAWINGCMD.nested_types = {}
ADDTOYDRAWINGCMD.enum_types = {}
ADDTOYDRAWINGCMD.fields = {
  ADDTOYDRAWINGCMD_CMD_FIELD,
  ADDTOYDRAWINGCMD_PARAM_FIELD,
  ADDTOYDRAWINGCMD_DRAWINGID_FIELD
}
ADDTOYDRAWINGCMD.is_extendable = false
ADDTOYDRAWINGCMD.extensions = {}
SYNCTOYDRAWINGCMD_CMD_FIELD.name = "cmd"
SYNCTOYDRAWINGCMD_CMD_FIELD.full_name = ".Cmd.SyncToyDrawingCmd.cmd"
SYNCTOYDRAWINGCMD_CMD_FIELD.number = 1
SYNCTOYDRAWINGCMD_CMD_FIELD.index = 0
SYNCTOYDRAWINGCMD_CMD_FIELD.label = 1
SYNCTOYDRAWINGCMD_CMD_FIELD.has_default_value = true
SYNCTOYDRAWINGCMD_CMD_FIELD.default_value = 73
SYNCTOYDRAWINGCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
SYNCTOYDRAWINGCMD_CMD_FIELD.type = 14
SYNCTOYDRAWINGCMD_CMD_FIELD.cpp_type = 8
SYNCTOYDRAWINGCMD_PARAM_FIELD.name = "param"
SYNCTOYDRAWINGCMD_PARAM_FIELD.full_name = ".Cmd.SyncToyDrawingCmd.param"
SYNCTOYDRAWINGCMD_PARAM_FIELD.number = 2
SYNCTOYDRAWINGCMD_PARAM_FIELD.index = 1
SYNCTOYDRAWINGCMD_PARAM_FIELD.label = 1
SYNCTOYDRAWINGCMD_PARAM_FIELD.has_default_value = true
SYNCTOYDRAWINGCMD_PARAM_FIELD.default_value = 4
SYNCTOYDRAWINGCMD_PARAM_FIELD.enum_type = TECHTREEPARAM
SYNCTOYDRAWINGCMD_PARAM_FIELD.type = 14
SYNCTOYDRAWINGCMD_PARAM_FIELD.cpp_type = 8
SYNCTOYDRAWINGCMD_DRAWINGS_FIELD.name = "drawings"
SYNCTOYDRAWINGCMD_DRAWINGS_FIELD.full_name = ".Cmd.SyncToyDrawingCmd.drawings"
SYNCTOYDRAWINGCMD_DRAWINGS_FIELD.number = 4
SYNCTOYDRAWINGCMD_DRAWINGS_FIELD.index = 2
SYNCTOYDRAWINGCMD_DRAWINGS_FIELD.label = 3
SYNCTOYDRAWINGCMD_DRAWINGS_FIELD.has_default_value = false
SYNCTOYDRAWINGCMD_DRAWINGS_FIELD.default_value = {}
SYNCTOYDRAWINGCMD_DRAWINGS_FIELD.type = 13
SYNCTOYDRAWINGCMD_DRAWINGS_FIELD.cpp_type = 3
SYNCTOYDRAWINGCMD.name = "SyncToyDrawingCmd"
SYNCTOYDRAWINGCMD.full_name = ".Cmd.SyncToyDrawingCmd"
SYNCTOYDRAWINGCMD.nested_types = {}
SYNCTOYDRAWINGCMD.enum_types = {}
SYNCTOYDRAWINGCMD.fields = {
  SYNCTOYDRAWINGCMD_CMD_FIELD,
  SYNCTOYDRAWINGCMD_PARAM_FIELD,
  SYNCTOYDRAWINGCMD_DRAWINGS_FIELD
}
SYNCTOYDRAWINGCMD.is_extendable = false
SYNCTOYDRAWINGCMD.extensions = {}
TECHTREEMAKETOYCMD_CMD_FIELD.name = "cmd"
TECHTREEMAKETOYCMD_CMD_FIELD.full_name = ".Cmd.TechTreeMakeToyCmd.cmd"
TECHTREEMAKETOYCMD_CMD_FIELD.number = 1
TECHTREEMAKETOYCMD_CMD_FIELD.index = 0
TECHTREEMAKETOYCMD_CMD_FIELD.label = 1
TECHTREEMAKETOYCMD_CMD_FIELD.has_default_value = true
TECHTREEMAKETOYCMD_CMD_FIELD.default_value = 73
TECHTREEMAKETOYCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
TECHTREEMAKETOYCMD_CMD_FIELD.type = 14
TECHTREEMAKETOYCMD_CMD_FIELD.cpp_type = 8
TECHTREEMAKETOYCMD_PARAM_FIELD.name = "param"
TECHTREEMAKETOYCMD_PARAM_FIELD.full_name = ".Cmd.TechTreeMakeToyCmd.param"
TECHTREEMAKETOYCMD_PARAM_FIELD.number = 2
TECHTREEMAKETOYCMD_PARAM_FIELD.index = 1
TECHTREEMAKETOYCMD_PARAM_FIELD.label = 1
TECHTREEMAKETOYCMD_PARAM_FIELD.has_default_value = true
TECHTREEMAKETOYCMD_PARAM_FIELD.default_value = 5
TECHTREEMAKETOYCMD_PARAM_FIELD.enum_type = TECHTREEPARAM
TECHTREEMAKETOYCMD_PARAM_FIELD.type = 14
TECHTREEMAKETOYCMD_PARAM_FIELD.cpp_type = 8
TECHTREEMAKETOYCMD_DRAWINGID_FIELD.name = "drawingid"
TECHTREEMAKETOYCMD_DRAWINGID_FIELD.full_name = ".Cmd.TechTreeMakeToyCmd.drawingid"
TECHTREEMAKETOYCMD_DRAWINGID_FIELD.number = 3
TECHTREEMAKETOYCMD_DRAWINGID_FIELD.index = 2
TECHTREEMAKETOYCMD_DRAWINGID_FIELD.label = 1
TECHTREEMAKETOYCMD_DRAWINGID_FIELD.has_default_value = true
TECHTREEMAKETOYCMD_DRAWINGID_FIELD.default_value = 0
TECHTREEMAKETOYCMD_DRAWINGID_FIELD.type = 13
TECHTREEMAKETOYCMD_DRAWINGID_FIELD.cpp_type = 3
TECHTREEMAKETOYCMD_COUNT_FIELD.name = "count"
TECHTREEMAKETOYCMD_COUNT_FIELD.full_name = ".Cmd.TechTreeMakeToyCmd.count"
TECHTREEMAKETOYCMD_COUNT_FIELD.number = 4
TECHTREEMAKETOYCMD_COUNT_FIELD.index = 3
TECHTREEMAKETOYCMD_COUNT_FIELD.label = 1
TECHTREEMAKETOYCMD_COUNT_FIELD.has_default_value = true
TECHTREEMAKETOYCMD_COUNT_FIELD.default_value = 0
TECHTREEMAKETOYCMD_COUNT_FIELD.type = 13
TECHTREEMAKETOYCMD_COUNT_FIELD.cpp_type = 3
TECHTREEMAKETOYCMD.name = "TechTreeMakeToyCmd"
TECHTREEMAKETOYCMD.full_name = ".Cmd.TechTreeMakeToyCmd"
TECHTREEMAKETOYCMD.nested_types = {}
TECHTREEMAKETOYCMD.enum_types = {}
TECHTREEMAKETOYCMD.fields = {
  TECHTREEMAKETOYCMD_CMD_FIELD,
  TECHTREEMAKETOYCMD_PARAM_FIELD,
  TECHTREEMAKETOYCMD_DRAWINGID_FIELD,
  TECHTREEMAKETOYCMD_COUNT_FIELD
}
TECHTREEMAKETOYCMD.is_extendable = false
TECHTREEMAKETOYCMD.extensions = {}
TOYTRANSSETPOSCMD_CMD_FIELD.name = "cmd"
TOYTRANSSETPOSCMD_CMD_FIELD.full_name = ".Cmd.ToyTransSetPosCmd.cmd"
TOYTRANSSETPOSCMD_CMD_FIELD.number = 1
TOYTRANSSETPOSCMD_CMD_FIELD.index = 0
TOYTRANSSETPOSCMD_CMD_FIELD.label = 1
TOYTRANSSETPOSCMD_CMD_FIELD.has_default_value = true
TOYTRANSSETPOSCMD_CMD_FIELD.default_value = 73
TOYTRANSSETPOSCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
TOYTRANSSETPOSCMD_CMD_FIELD.type = 14
TOYTRANSSETPOSCMD_CMD_FIELD.cpp_type = 8
TOYTRANSSETPOSCMD_PARAM_FIELD.name = "param"
TOYTRANSSETPOSCMD_PARAM_FIELD.full_name = ".Cmd.ToyTransSetPosCmd.param"
TOYTRANSSETPOSCMD_PARAM_FIELD.number = 2
TOYTRANSSETPOSCMD_PARAM_FIELD.index = 1
TOYTRANSSETPOSCMD_PARAM_FIELD.label = 1
TOYTRANSSETPOSCMD_PARAM_FIELD.has_default_value = true
TOYTRANSSETPOSCMD_PARAM_FIELD.default_value = 6
TOYTRANSSETPOSCMD_PARAM_FIELD.enum_type = TECHTREEPARAM
TOYTRANSSETPOSCMD_PARAM_FIELD.type = 14
TOYTRANSSETPOSCMD_PARAM_FIELD.cpp_type = 8
TOYTRANSSETPOSCMD_POS_FIELD.name = "pos"
TOYTRANSSETPOSCMD_POS_FIELD.full_name = ".Cmd.ToyTransSetPosCmd.pos"
TOYTRANSSETPOSCMD_POS_FIELD.number = 3
TOYTRANSSETPOSCMD_POS_FIELD.index = 2
TOYTRANSSETPOSCMD_POS_FIELD.label = 1
TOYTRANSSETPOSCMD_POS_FIELD.has_default_value = false
TOYTRANSSETPOSCMD_POS_FIELD.default_value = nil
TOYTRANSSETPOSCMD_POS_FIELD.message_type = ProtoCommon_pb.SCENEPOS
TOYTRANSSETPOSCMD_POS_FIELD.type = 11
TOYTRANSSETPOSCMD_POS_FIELD.cpp_type = 10
TOYTRANSSETPOSCMD.name = "ToyTransSetPosCmd"
TOYTRANSSETPOSCMD.full_name = ".Cmd.ToyTransSetPosCmd"
TOYTRANSSETPOSCMD.nested_types = {}
TOYTRANSSETPOSCMD.enum_types = {}
TOYTRANSSETPOSCMD.fields = {
  TOYTRANSSETPOSCMD_CMD_FIELD,
  TOYTRANSSETPOSCMD_PARAM_FIELD,
  TOYTRANSSETPOSCMD_POS_FIELD
}
TOYTRANSSETPOSCMD.is_extendable = false
TOYTRANSSETPOSCMD.extensions = {}
TECHTREELEVELAWARDCMD_CMD_FIELD.name = "cmd"
TECHTREELEVELAWARDCMD_CMD_FIELD.full_name = ".Cmd.TechTreeLevelAwardCmd.cmd"
TECHTREELEVELAWARDCMD_CMD_FIELD.number = 1
TECHTREELEVELAWARDCMD_CMD_FIELD.index = 0
TECHTREELEVELAWARDCMD_CMD_FIELD.label = 1
TECHTREELEVELAWARDCMD_CMD_FIELD.has_default_value = true
TECHTREELEVELAWARDCMD_CMD_FIELD.default_value = 73
TECHTREELEVELAWARDCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
TECHTREELEVELAWARDCMD_CMD_FIELD.type = 14
TECHTREELEVELAWARDCMD_CMD_FIELD.cpp_type = 8
TECHTREELEVELAWARDCMD_PARAM_FIELD.name = "param"
TECHTREELEVELAWARDCMD_PARAM_FIELD.full_name = ".Cmd.TechTreeLevelAwardCmd.param"
TECHTREELEVELAWARDCMD_PARAM_FIELD.number = 2
TECHTREELEVELAWARDCMD_PARAM_FIELD.index = 1
TECHTREELEVELAWARDCMD_PARAM_FIELD.label = 1
TECHTREELEVELAWARDCMD_PARAM_FIELD.has_default_value = true
TECHTREELEVELAWARDCMD_PARAM_FIELD.default_value = 7
TECHTREELEVELAWARDCMD_PARAM_FIELD.enum_type = TECHTREEPARAM
TECHTREELEVELAWARDCMD_PARAM_FIELD.type = 14
TECHTREELEVELAWARDCMD_PARAM_FIELD.cpp_type = 8
TECHTREELEVELAWARDCMD_TREEID_FIELD.name = "treeid"
TECHTREELEVELAWARDCMD_TREEID_FIELD.full_name = ".Cmd.TechTreeLevelAwardCmd.treeid"
TECHTREELEVELAWARDCMD_TREEID_FIELD.number = 3
TECHTREELEVELAWARDCMD_TREEID_FIELD.index = 2
TECHTREELEVELAWARDCMD_TREEID_FIELD.label = 1
TECHTREELEVELAWARDCMD_TREEID_FIELD.has_default_value = false
TECHTREELEVELAWARDCMD_TREEID_FIELD.default_value = 0
TECHTREELEVELAWARDCMD_TREEID_FIELD.type = 13
TECHTREELEVELAWARDCMD_TREEID_FIELD.cpp_type = 3
TECHTREELEVELAWARDCMD_LEVELNODE_FIELD.name = "levelnode"
TECHTREELEVELAWARDCMD_LEVELNODE_FIELD.full_name = ".Cmd.TechTreeLevelAwardCmd.levelnode"
TECHTREELEVELAWARDCMD_LEVELNODE_FIELD.number = 4
TECHTREELEVELAWARDCMD_LEVELNODE_FIELD.index = 3
TECHTREELEVELAWARDCMD_LEVELNODE_FIELD.label = 3
TECHTREELEVELAWARDCMD_LEVELNODE_FIELD.has_default_value = false
TECHTREELEVELAWARDCMD_LEVELNODE_FIELD.default_value = {}
TECHTREELEVELAWARDCMD_LEVELNODE_FIELD.type = 13
TECHTREELEVELAWARDCMD_LEVELNODE_FIELD.cpp_type = 3
TECHTREELEVELAWARDCMD.name = "TechTreeLevelAwardCmd"
TECHTREELEVELAWARDCMD.full_name = ".Cmd.TechTreeLevelAwardCmd"
TECHTREELEVELAWARDCMD.nested_types = {}
TECHTREELEVELAWARDCMD.enum_types = {}
TECHTREELEVELAWARDCMD.fields = {
  TECHTREELEVELAWARDCMD_CMD_FIELD,
  TECHTREELEVELAWARDCMD_PARAM_FIELD,
  TECHTREELEVELAWARDCMD_TREEID_FIELD,
  TECHTREELEVELAWARDCMD_LEVELNODE_FIELD
}
TECHTREELEVELAWARDCMD.is_extendable = false
TECHTREELEVELAWARDCMD.extensions = {}
TECHTREEPRODUCECOLLECTCMD_CMD_FIELD.name = "cmd"
TECHTREEPRODUCECOLLECTCMD_CMD_FIELD.full_name = ".Cmd.TechTreeProduceCollectCmd.cmd"
TECHTREEPRODUCECOLLECTCMD_CMD_FIELD.number = 1
TECHTREEPRODUCECOLLECTCMD_CMD_FIELD.index = 0
TECHTREEPRODUCECOLLECTCMD_CMD_FIELD.label = 1
TECHTREEPRODUCECOLLECTCMD_CMD_FIELD.has_default_value = true
TECHTREEPRODUCECOLLECTCMD_CMD_FIELD.default_value = 73
TECHTREEPRODUCECOLLECTCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
TECHTREEPRODUCECOLLECTCMD_CMD_FIELD.type = 14
TECHTREEPRODUCECOLLECTCMD_CMD_FIELD.cpp_type = 8
TECHTREEPRODUCECOLLECTCMD_PARAM_FIELD.name = "param"
TECHTREEPRODUCECOLLECTCMD_PARAM_FIELD.full_name = ".Cmd.TechTreeProduceCollectCmd.param"
TECHTREEPRODUCECOLLECTCMD_PARAM_FIELD.number = 2
TECHTREEPRODUCECOLLECTCMD_PARAM_FIELD.index = 1
TECHTREEPRODUCECOLLECTCMD_PARAM_FIELD.label = 1
TECHTREEPRODUCECOLLECTCMD_PARAM_FIELD.has_default_value = true
TECHTREEPRODUCECOLLECTCMD_PARAM_FIELD.default_value = 8
TECHTREEPRODUCECOLLECTCMD_PARAM_FIELD.enum_type = TECHTREEPARAM
TECHTREEPRODUCECOLLECTCMD_PARAM_FIELD.type = 14
TECHTREEPRODUCECOLLECTCMD_PARAM_FIELD.cpp_type = 8
TECHTREEPRODUCECOLLECTCMD_SUCCESS_FIELD.name = "success"
TECHTREEPRODUCECOLLECTCMD_SUCCESS_FIELD.full_name = ".Cmd.TechTreeProduceCollectCmd.success"
TECHTREEPRODUCECOLLECTCMD_SUCCESS_FIELD.number = 3
TECHTREEPRODUCECOLLECTCMD_SUCCESS_FIELD.index = 2
TECHTREEPRODUCECOLLECTCMD_SUCCESS_FIELD.label = 1
TECHTREEPRODUCECOLLECTCMD_SUCCESS_FIELD.has_default_value = false
TECHTREEPRODUCECOLLECTCMD_SUCCESS_FIELD.default_value = false
TECHTREEPRODUCECOLLECTCMD_SUCCESS_FIELD.type = 8
TECHTREEPRODUCECOLLECTCMD_SUCCESS_FIELD.cpp_type = 7
TECHTREEPRODUCECOLLECTCMD.name = "TechTreeProduceCollectCmd"
TECHTREEPRODUCECOLLECTCMD.full_name = ".Cmd.TechTreeProduceCollectCmd"
TECHTREEPRODUCECOLLECTCMD.nested_types = {}
TECHTREEPRODUCECOLLECTCMD.enum_types = {}
TECHTREEPRODUCECOLLECTCMD.fields = {
  TECHTREEPRODUCECOLLECTCMD_CMD_FIELD,
  TECHTREEPRODUCECOLLECTCMD_PARAM_FIELD,
  TECHTREEPRODUCECOLLECTCMD_SUCCESS_FIELD
}
TECHTREEPRODUCECOLLECTCMD.is_extendable = false
TECHTREEPRODUCECOLLECTCMD.extensions = {}
TECHTREEPRODECINFOCMD_CMD_FIELD.name = "cmd"
TECHTREEPRODECINFOCMD_CMD_FIELD.full_name = ".Cmd.TechTreeProdecInfoCmd.cmd"
TECHTREEPRODECINFOCMD_CMD_FIELD.number = 1
TECHTREEPRODECINFOCMD_CMD_FIELD.index = 0
TECHTREEPRODECINFOCMD_CMD_FIELD.label = 1
TECHTREEPRODECINFOCMD_CMD_FIELD.has_default_value = true
TECHTREEPRODECINFOCMD_CMD_FIELD.default_value = 73
TECHTREEPRODECINFOCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
TECHTREEPRODECINFOCMD_CMD_FIELD.type = 14
TECHTREEPRODECINFOCMD_CMD_FIELD.cpp_type = 8
TECHTREEPRODECINFOCMD_PARAM_FIELD.name = "param"
TECHTREEPRODECINFOCMD_PARAM_FIELD.full_name = ".Cmd.TechTreeProdecInfoCmd.param"
TECHTREEPRODECINFOCMD_PARAM_FIELD.number = 2
TECHTREEPRODECINFOCMD_PARAM_FIELD.index = 1
TECHTREEPRODECINFOCMD_PARAM_FIELD.label = 1
TECHTREEPRODECINFOCMD_PARAM_FIELD.has_default_value = true
TECHTREEPRODECINFOCMD_PARAM_FIELD.default_value = 9
TECHTREEPRODECINFOCMD_PARAM_FIELD.enum_type = TECHTREEPARAM
TECHTREEPRODECINFOCMD_PARAM_FIELD.type = 14
TECHTREEPRODECINFOCMD_PARAM_FIELD.cpp_type = 8
TECHTREEPRODECINFOCMD_PRODUCENUM_FIELD.name = "producenum"
TECHTREEPRODECINFOCMD_PRODUCENUM_FIELD.full_name = ".Cmd.TechTreeProdecInfoCmd.producenum"
TECHTREEPRODECINFOCMD_PRODUCENUM_FIELD.number = 3
TECHTREEPRODECINFOCMD_PRODUCENUM_FIELD.index = 2
TECHTREEPRODECINFOCMD_PRODUCENUM_FIELD.label = 1
TECHTREEPRODECINFOCMD_PRODUCENUM_FIELD.has_default_value = false
TECHTREEPRODECINFOCMD_PRODUCENUM_FIELD.default_value = 0
TECHTREEPRODECINFOCMD_PRODUCENUM_FIELD.type = 13
TECHTREEPRODECINFOCMD_PRODUCENUM_FIELD.cpp_type = 3
TECHTREEPRODECINFOCMD_PRODUCEUPPERLIMIT_FIELD.name = "produceupperlimit"
TECHTREEPRODECINFOCMD_PRODUCEUPPERLIMIT_FIELD.full_name = ".Cmd.TechTreeProdecInfoCmd.produceupperlimit"
TECHTREEPRODECINFOCMD_PRODUCEUPPERLIMIT_FIELD.number = 4
TECHTREEPRODECINFOCMD_PRODUCEUPPERLIMIT_FIELD.index = 3
TECHTREEPRODECINFOCMD_PRODUCEUPPERLIMIT_FIELD.label = 1
TECHTREEPRODECINFOCMD_PRODUCEUPPERLIMIT_FIELD.has_default_value = false
TECHTREEPRODECINFOCMD_PRODUCEUPPERLIMIT_FIELD.default_value = 0
TECHTREEPRODECINFOCMD_PRODUCEUPPERLIMIT_FIELD.type = 13
TECHTREEPRODECINFOCMD_PRODUCEUPPERLIMIT_FIELD.cpp_type = 3
TECHTREEPRODECINFOCMD_PRODECESPEED_FIELD.name = "prodecespeed"
TECHTREEPRODECINFOCMD_PRODECESPEED_FIELD.full_name = ".Cmd.TechTreeProdecInfoCmd.prodecespeed"
TECHTREEPRODECINFOCMD_PRODECESPEED_FIELD.number = 5
TECHTREEPRODECINFOCMD_PRODECESPEED_FIELD.index = 4
TECHTREEPRODECINFOCMD_PRODECESPEED_FIELD.label = 1
TECHTREEPRODECINFOCMD_PRODECESPEED_FIELD.has_default_value = false
TECHTREEPRODECINFOCMD_PRODECESPEED_FIELD.default_value = 0
TECHTREEPRODECINFOCMD_PRODECESPEED_FIELD.type = 13
TECHTREEPRODECINFOCMD_PRODECESPEED_FIELD.cpp_type = 3
TECHTREEPRODECINFOCMD_FIRSTOPEN_FIELD.name = "firstopen"
TECHTREEPRODECINFOCMD_FIRSTOPEN_FIELD.full_name = ".Cmd.TechTreeProdecInfoCmd.firstopen"
TECHTREEPRODECINFOCMD_FIRSTOPEN_FIELD.number = 6
TECHTREEPRODECINFOCMD_FIRSTOPEN_FIELD.index = 5
TECHTREEPRODECINFOCMD_FIRSTOPEN_FIELD.label = 1
TECHTREEPRODECINFOCMD_FIRSTOPEN_FIELD.has_default_value = false
TECHTREEPRODECINFOCMD_FIRSTOPEN_FIELD.default_value = false
TECHTREEPRODECINFOCMD_FIRSTOPEN_FIELD.type = 8
TECHTREEPRODECINFOCMD_FIRSTOPEN_FIELD.cpp_type = 7
TECHTREEPRODECINFOCMD.name = "TechTreeProdecInfoCmd"
TECHTREEPRODECINFOCMD.full_name = ".Cmd.TechTreeProdecInfoCmd"
TECHTREEPRODECINFOCMD.nested_types = {}
TECHTREEPRODECINFOCMD.enum_types = {}
TECHTREEPRODECINFOCMD.fields = {
  TECHTREEPRODECINFOCMD_CMD_FIELD,
  TECHTREEPRODECINFOCMD_PARAM_FIELD,
  TECHTREEPRODECINFOCMD_PRODUCENUM_FIELD,
  TECHTREEPRODECINFOCMD_PRODUCEUPPERLIMIT_FIELD,
  TECHTREEPRODECINFOCMD_PRODECESPEED_FIELD,
  TECHTREEPRODECINFOCMD_FIRSTOPEN_FIELD
}
TECHTREEPRODECINFOCMD.is_extendable = false
TECHTREEPRODECINFOCMD.extensions = {}
TECHTREEINJECTCMD_CMD_FIELD.name = "cmd"
TECHTREEINJECTCMD_CMD_FIELD.full_name = ".Cmd.TechTreeInjectCmd.cmd"
TECHTREEINJECTCMD_CMD_FIELD.number = 1
TECHTREEINJECTCMD_CMD_FIELD.index = 0
TECHTREEINJECTCMD_CMD_FIELD.label = 1
TECHTREEINJECTCMD_CMD_FIELD.has_default_value = true
TECHTREEINJECTCMD_CMD_FIELD.default_value = 73
TECHTREEINJECTCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
TECHTREEINJECTCMD_CMD_FIELD.type = 14
TECHTREEINJECTCMD_CMD_FIELD.cpp_type = 8
TECHTREEINJECTCMD_PARAM_FIELD.name = "param"
TECHTREEINJECTCMD_PARAM_FIELD.full_name = ".Cmd.TechTreeInjectCmd.param"
TECHTREEINJECTCMD_PARAM_FIELD.number = 2
TECHTREEINJECTCMD_PARAM_FIELD.index = 1
TECHTREEINJECTCMD_PARAM_FIELD.label = 1
TECHTREEINJECTCMD_PARAM_FIELD.has_default_value = true
TECHTREEINJECTCMD_PARAM_FIELD.default_value = 10
TECHTREEINJECTCMD_PARAM_FIELD.enum_type = TECHTREEPARAM
TECHTREEINJECTCMD_PARAM_FIELD.type = 14
TECHTREEINJECTCMD_PARAM_FIELD.cpp_type = 8
TECHTREEINJECTCMD_TREEID_FIELD.name = "treeid"
TECHTREEINJECTCMD_TREEID_FIELD.full_name = ".Cmd.TechTreeInjectCmd.treeid"
TECHTREEINJECTCMD_TREEID_FIELD.number = 3
TECHTREEINJECTCMD_TREEID_FIELD.index = 2
TECHTREEINJECTCMD_TREEID_FIELD.label = 1
TECHTREEINJECTCMD_TREEID_FIELD.has_default_value = false
TECHTREEINJECTCMD_TREEID_FIELD.default_value = 0
TECHTREEINJECTCMD_TREEID_FIELD.type = 13
TECHTREEINJECTCMD_TREEID_FIELD.cpp_type = 3
TECHTREEINJECTCMD_LEAFNODE_FIELD.name = "leafnode"
TECHTREEINJECTCMD_LEAFNODE_FIELD.full_name = ".Cmd.TechTreeInjectCmd.leafnode"
TECHTREEINJECTCMD_LEAFNODE_FIELD.number = 4
TECHTREEINJECTCMD_LEAFNODE_FIELD.index = 3
TECHTREEINJECTCMD_LEAFNODE_FIELD.label = 1
TECHTREEINJECTCMD_LEAFNODE_FIELD.has_default_value = false
TECHTREEINJECTCMD_LEAFNODE_FIELD.default_value = 0
TECHTREEINJECTCMD_LEAFNODE_FIELD.type = 13
TECHTREEINJECTCMD_LEAFNODE_FIELD.cpp_type = 3
TECHTREEINJECTCMD_INJECT_NUM_FIELD.name = "inject_num"
TECHTREEINJECTCMD_INJECT_NUM_FIELD.full_name = ".Cmd.TechTreeInjectCmd.inject_num"
TECHTREEINJECTCMD_INJECT_NUM_FIELD.number = 5
TECHTREEINJECTCMD_INJECT_NUM_FIELD.index = 4
TECHTREEINJECTCMD_INJECT_NUM_FIELD.label = 1
TECHTREEINJECTCMD_INJECT_NUM_FIELD.has_default_value = false
TECHTREEINJECTCMD_INJECT_NUM_FIELD.default_value = 0
TECHTREEINJECTCMD_INJECT_NUM_FIELD.type = 13
TECHTREEINJECTCMD_INJECT_NUM_FIELD.cpp_type = 3
TECHTREEINJECTCMD.name = "TechTreeInjectCmd"
TECHTREEINJECTCMD.full_name = ".Cmd.TechTreeInjectCmd"
TECHTREEINJECTCMD.nested_types = {}
TECHTREEINJECTCMD.enum_types = {}
TECHTREEINJECTCMD.fields = {
  TECHTREEINJECTCMD_CMD_FIELD,
  TECHTREEINJECTCMD_PARAM_FIELD,
  TECHTREEINJECTCMD_TREEID_FIELD,
  TECHTREEINJECTCMD_LEAFNODE_FIELD,
  TECHTREEINJECTCMD_INJECT_NUM_FIELD
}
TECHTREEINJECTCMD.is_extendable = false
TECHTREEINJECTCMD.extensions = {}
TECHTREEINJECTINFOCMD_CMD_FIELD.name = "cmd"
TECHTREEINJECTINFOCMD_CMD_FIELD.full_name = ".Cmd.TechTreeInjectInfoCmd.cmd"
TECHTREEINJECTINFOCMD_CMD_FIELD.number = 1
TECHTREEINJECTINFOCMD_CMD_FIELD.index = 0
TECHTREEINJECTINFOCMD_CMD_FIELD.label = 1
TECHTREEINJECTINFOCMD_CMD_FIELD.has_default_value = true
TECHTREEINJECTINFOCMD_CMD_FIELD.default_value = 73
TECHTREEINJECTINFOCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
TECHTREEINJECTINFOCMD_CMD_FIELD.type = 14
TECHTREEINJECTINFOCMD_CMD_FIELD.cpp_type = 8
TECHTREEINJECTINFOCMD_PARAM_FIELD.name = "param"
TECHTREEINJECTINFOCMD_PARAM_FIELD.full_name = ".Cmd.TechTreeInjectInfoCmd.param"
TECHTREEINJECTINFOCMD_PARAM_FIELD.number = 2
TECHTREEINJECTINFOCMD_PARAM_FIELD.index = 1
TECHTREEINJECTINFOCMD_PARAM_FIELD.label = 1
TECHTREEINJECTINFOCMD_PARAM_FIELD.has_default_value = true
TECHTREEINJECTINFOCMD_PARAM_FIELD.default_value = 11
TECHTREEINJECTINFOCMD_PARAM_FIELD.enum_type = TECHTREEPARAM
TECHTREEINJECTINFOCMD_PARAM_FIELD.type = 14
TECHTREEINJECTINFOCMD_PARAM_FIELD.cpp_type = 8
TECHTREEINJECTINFOCMD_TREEID_FIELD.name = "treeid"
TECHTREEINJECTINFOCMD_TREEID_FIELD.full_name = ".Cmd.TechTreeInjectInfoCmd.treeid"
TECHTREEINJECTINFOCMD_TREEID_FIELD.number = 3
TECHTREEINJECTINFOCMD_TREEID_FIELD.index = 2
TECHTREEINJECTINFOCMD_TREEID_FIELD.label = 1
TECHTREEINJECTINFOCMD_TREEID_FIELD.has_default_value = false
TECHTREEINJECTINFOCMD_TREEID_FIELD.default_value = 0
TECHTREEINJECTINFOCMD_TREEID_FIELD.type = 13
TECHTREEINJECTINFOCMD_TREEID_FIELD.cpp_type = 3
TECHTREEINJECTINFOCMD_LEAFNODE_FIELD.name = "leafnode"
TECHTREEINJECTINFOCMD_LEAFNODE_FIELD.full_name = ".Cmd.TechTreeInjectInfoCmd.leafnode"
TECHTREEINJECTINFOCMD_LEAFNODE_FIELD.number = 4
TECHTREEINJECTINFOCMD_LEAFNODE_FIELD.index = 3
TECHTREEINJECTINFOCMD_LEAFNODE_FIELD.label = 1
TECHTREEINJECTINFOCMD_LEAFNODE_FIELD.has_default_value = false
TECHTREEINJECTINFOCMD_LEAFNODE_FIELD.default_value = 0
TECHTREEINJECTINFOCMD_LEAFNODE_FIELD.type = 13
TECHTREEINJECTINFOCMD_LEAFNODE_FIELD.cpp_type = 3
TECHTREEINJECTINFOCMD_INJECTED_NUM_FIELD.name = "injected_num"
TECHTREEINJECTINFOCMD_INJECTED_NUM_FIELD.full_name = ".Cmd.TechTreeInjectInfoCmd.injected_num"
TECHTREEINJECTINFOCMD_INJECTED_NUM_FIELD.number = 5
TECHTREEINJECTINFOCMD_INJECTED_NUM_FIELD.index = 4
TECHTREEINJECTINFOCMD_INJECTED_NUM_FIELD.label = 1
TECHTREEINJECTINFOCMD_INJECTED_NUM_FIELD.has_default_value = false
TECHTREEINJECTINFOCMD_INJECTED_NUM_FIELD.default_value = 0
TECHTREEINJECTINFOCMD_INJECTED_NUM_FIELD.type = 13
TECHTREEINJECTINFOCMD_INJECTED_NUM_FIELD.cpp_type = 3
TECHTREEINJECTINFOCMD_IS_FIRST_OPEN_FIELD.name = "is_first_open"
TECHTREEINJECTINFOCMD_IS_FIRST_OPEN_FIELD.full_name = ".Cmd.TechTreeInjectInfoCmd.is_first_open"
TECHTREEINJECTINFOCMD_IS_FIRST_OPEN_FIELD.number = 6
TECHTREEINJECTINFOCMD_IS_FIRST_OPEN_FIELD.index = 5
TECHTREEINJECTINFOCMD_IS_FIRST_OPEN_FIELD.label = 1
TECHTREEINJECTINFOCMD_IS_FIRST_OPEN_FIELD.has_default_value = true
TECHTREEINJECTINFOCMD_IS_FIRST_OPEN_FIELD.default_value = false
TECHTREEINJECTINFOCMD_IS_FIRST_OPEN_FIELD.type = 8
TECHTREEINJECTINFOCMD_IS_FIRST_OPEN_FIELD.cpp_type = 7
TECHTREEINJECTINFOCMD.name = "TechTreeInjectInfoCmd"
TECHTREEINJECTINFOCMD.full_name = ".Cmd.TechTreeInjectInfoCmd"
TECHTREEINJECTINFOCMD.nested_types = {}
TECHTREEINJECTINFOCMD.enum_types = {}
TECHTREEINJECTINFOCMD.fields = {
  TECHTREEINJECTINFOCMD_CMD_FIELD,
  TECHTREEINJECTINFOCMD_PARAM_FIELD,
  TECHTREEINJECTINFOCMD_TREEID_FIELD,
  TECHTREEINJECTINFOCMD_LEAFNODE_FIELD,
  TECHTREEINJECTINFOCMD_INJECTED_NUM_FIELD,
  TECHTREEINJECTINFOCMD_IS_FIRST_OPEN_FIELD
}
TECHTREEINJECTINFOCMD.is_extendable = false
TECHTREEINJECTINFOCMD.extensions = {}
AddToyDrawingCmd = protobuf.Message(ADDTOYDRAWINGCMD)
SyncToyDrawingCmd = protobuf.Message(SYNCTOYDRAWINGCMD)
TECHTREEPARAM_GET_LEVEL_AWARD = 7
TECHTREEPARAM_INJECT = 10
TECHTREEPARAM_INJECT_INFO = 11
TECHTREEPARAM_MAKE_TOY = 5
TECHTREEPARAM_PRODUCE_COLLECT = 8
TECHTREEPARAM_PRODUCE_INFO = 9
TECHTREEPARAM_SYNCINFO = 2
TECHTREEPARAM_TOY_SYNCINFO = 4
TECHTREEPARAM_TOY_TRANS_POS = 6
TECHTREEPARAM_TOY_UNLOCK = 3
TECHTREEPARAM_UNLOCK = 1
TECHTREE_LEVEL_STATE_COMPLETE = 3
TECHTREE_LEVEL_STATE_INPROCESS = 2
TECHTREE_LEVEL_STATE_NONE = 0
TECHTREE_LEVEL_STATE_UNLOCK = 1
TechTreeInfo = protobuf.Message(TECHTREEINFO)
TechTreeInjectCmd = protobuf.Message(TECHTREEINJECTCMD)
TechTreeInjectInfoCmd = protobuf.Message(TECHTREEINJECTINFOCMD)
TechTreeLeafInfo = protobuf.Message(TECHTREELEAFINFO)
TechTreeLevelAwardCmd = protobuf.Message(TECHTREELEVELAWARDCMD)
TechTreeLevelNodeInfo = protobuf.Message(TECHTREELEVELNODEINFO)
TechTreeMakeToyCmd = protobuf.Message(TECHTREEMAKETOYCMD)
TechTreeProdecInfoCmd = protobuf.Message(TECHTREEPRODECINFOCMD)
TechTreeProduceCollectCmd = protobuf.Message(TECHTREEPRODUCECOLLECTCMD)
TechTreeSyncLeafCmd = protobuf.Message(TECHTREESYNCLEAFCMD)
TechTreeUnlockLeafCmd = protobuf.Message(TECHTREEUNLOCKLEAFCMD)
ToyTransSetPosCmd = protobuf.Message(TOYTRANSSETPOSCMD)
