local protobuf = protobuf
autoImport("xCmd_pb")
local xCmd_pb = xCmd_pb
autoImport("SceneItem_pb")
local SceneItem_pb = SceneItem_pb
autoImport("ProtoCommon_pb")
local ProtoCommon_pb = ProtoCommon_pb
autoImport("SceneUser2_pb")
local SceneUser2_pb = SceneUser2_pb
module("UserAfkCmd_pb")
USERAFKCMDPARAM = protobuf.EnumDescriptor()
USERAFKCMDPARAM_USER_AFKCMD_REQ_AFK_ENUM = protobuf.EnumValueDescriptor()
USERAFKCMDPARAM_USER_AFKCMD_RET_AFK_ENUM = protobuf.EnumValueDescriptor()
USERAFKCMDPARAM_USER_AFKCMD_SYNC_STATINFO_ENUM = protobuf.EnumValueDescriptor()
EAFKSTATUS = protobuf.EnumDescriptor()
EAFKSTATUS_EAFKSTATUS_OPEN_ENUM = protobuf.EnumValueDescriptor()
EAFKSTATUS_EAFKSTATUS_TIMEOUT_EXIT_ENUM = protobuf.EnumValueDescriptor()
EAFKSTATUS_EAFKSTATUS_NOBATTLE_EXIT_ENUM = protobuf.EnumValueDescriptor()
EAFKSTATUS_EAFKSTATUS_RESTART_EXIT_ENUM = protobuf.EnumValueDescriptor()
REQAFKUSERAFKCMD = protobuf.Descriptor()
REQAFKUSERAFKCMD_CMD_FIELD = protobuf.FieldDescriptor()
REQAFKUSERAFKCMD_PARAM_FIELD = protobuf.FieldDescriptor()
REQAFKUSERAFKCMD_TIMELEN_FIELD = protobuf.FieldDescriptor()
REQAFKUSERAFKCMD_INPLACE_FIELD = protobuf.FieldDescriptor()
REQAFKUSERAFKCMD_PROTECT_TEAM_FIELD = protobuf.FieldDescriptor()
REQAFKUSERAFKCMD_MONSTERIDS_FIELD = protobuf.FieldDescriptor()
RETAFKUSERAFKCMD = protobuf.Descriptor()
RETAFKUSERAFKCMD_CMD_FIELD = protobuf.FieldDescriptor()
RETAFKUSERAFKCMD_PARAM_FIELD = protobuf.FieldDescriptor()
RETAFKUSERAFKCMD_RET_FIELD = protobuf.FieldDescriptor()
MONEYDATA = protobuf.Descriptor()
MONEYDATA_ETYPE_FIELD = protobuf.FieldDescriptor()
MONEYDATA_VALUE_FIELD = protobuf.FieldDescriptor()
AFKKILLINFO = protobuf.Descriptor()
AFKKILLINFO_MONSTERID_FIELD = protobuf.FieldDescriptor()
AFKKILLINFO_COUNT_FIELD = protobuf.FieldDescriptor()
BATTLETIMEDATA = protobuf.Descriptor()
BATTLETIMEDATA_TOTALTIME_FIELD = protobuf.FieldDescriptor()
BATTLETIMEDATA_USEDTIME_FIELD = protobuf.FieldDescriptor()
BATTLETIMEDATA_ESTATUS_FIELD = protobuf.FieldDescriptor()
USERAFKSTATDATA = protobuf.Descriptor()
USERAFKSTATDATA_BASEEXP_FIELD = protobuf.FieldDescriptor()
USERAFKSTATDATA_JOBEXP_FIELD = protobuf.FieldDescriptor()
USERAFKSTATDATA_ITEMS_FIELD = protobuf.FieldDescriptor()
USERAFKSTATDATA_MONEYS_FIELD = protobuf.FieldDescriptor()
USERAFKSTATDATA_EXTRA_ZENY_FIELD = protobuf.FieldDescriptor()
USERAFKSTATDATA_EXTRA_BASE_FIELD = protobuf.FieldDescriptor()
USERAFKSTATDATA_EXTRA_JOB_FIELD = protobuf.FieldDescriptor()
USERAFKSTATDATA_EXTRA_TIME_FIELD = protobuf.FieldDescriptor()
USERAFKSTATDATA_KILLINFO_FIELD = protobuf.FieldDescriptor()
USERAFKSTATDATA_BE_KILLINFO_FIELD = protobuf.FieldDescriptor()
USERAFKSTATDATA_BATTLE_TIME_FIELD = protobuf.FieldDescriptor()
USERAFKSTATDATA_ESTATUS_FIELD = protobuf.FieldDescriptor()
USERAFKSTATDATA_TIMELEN_FIELD = protobuf.FieldDescriptor()
USERAFKSTATDATA_KILL_COUNT_FIELD = protobuf.FieldDescriptor()
USERAFKSTATDATA_LEFT_AFK_COUNT_FIELD = protobuf.FieldDescriptor()
SYNCSTATINFOAFKCMD = protobuf.Descriptor()
SYNCSTATINFOAFKCMD_CMD_FIELD = protobuf.FieldDescriptor()
SYNCSTATINFOAFKCMD_PARAM_FIELD = protobuf.FieldDescriptor()
SYNCSTATINFOAFKCMD_STATDATA_FIELD = protobuf.FieldDescriptor()
USERAFKCMDPARAM_USER_AFKCMD_REQ_AFK_ENUM.name = "USER_AFKCMD_REQ_AFK"
USERAFKCMDPARAM_USER_AFKCMD_REQ_AFK_ENUM.index = 0
USERAFKCMDPARAM_USER_AFKCMD_REQ_AFK_ENUM.number = 1
USERAFKCMDPARAM_USER_AFKCMD_RET_AFK_ENUM.name = "USER_AFKCMD_RET_AFK"
USERAFKCMDPARAM_USER_AFKCMD_RET_AFK_ENUM.index = 1
USERAFKCMDPARAM_USER_AFKCMD_RET_AFK_ENUM.number = 2
USERAFKCMDPARAM_USER_AFKCMD_SYNC_STATINFO_ENUM.name = "USER_AFKCMD_SYNC_STATINFO"
USERAFKCMDPARAM_USER_AFKCMD_SYNC_STATINFO_ENUM.index = 2
USERAFKCMDPARAM_USER_AFKCMD_SYNC_STATINFO_ENUM.number = 3
USERAFKCMDPARAM.name = "UserAfkCmdParam"
USERAFKCMDPARAM.full_name = ".Cmd.UserAfkCmdParam"
USERAFKCMDPARAM.values = {
  USERAFKCMDPARAM_USER_AFKCMD_REQ_AFK_ENUM,
  USERAFKCMDPARAM_USER_AFKCMD_RET_AFK_ENUM,
  USERAFKCMDPARAM_USER_AFKCMD_SYNC_STATINFO_ENUM
}
EAFKSTATUS_EAFKSTATUS_OPEN_ENUM.name = "EAFKSTATUS_OPEN"
EAFKSTATUS_EAFKSTATUS_OPEN_ENUM.index = 0
EAFKSTATUS_EAFKSTATUS_OPEN_ENUM.number = 0
EAFKSTATUS_EAFKSTATUS_TIMEOUT_EXIT_ENUM.name = "EAFKSTATUS_TIMEOUT_EXIT"
EAFKSTATUS_EAFKSTATUS_TIMEOUT_EXIT_ENUM.index = 1
EAFKSTATUS_EAFKSTATUS_TIMEOUT_EXIT_ENUM.number = 1
EAFKSTATUS_EAFKSTATUS_NOBATTLE_EXIT_ENUM.name = "EAFKSTATUS_NOBATTLE_EXIT"
EAFKSTATUS_EAFKSTATUS_NOBATTLE_EXIT_ENUM.index = 2
EAFKSTATUS_EAFKSTATUS_NOBATTLE_EXIT_ENUM.number = 2
EAFKSTATUS_EAFKSTATUS_RESTART_EXIT_ENUM.name = "EAFKSTATUS_RESTART_EXIT"
EAFKSTATUS_EAFKSTATUS_RESTART_EXIT_ENUM.index = 3
EAFKSTATUS_EAFKSTATUS_RESTART_EXIT_ENUM.number = 3
EAFKSTATUS.name = "EAfkStatus"
EAFKSTATUS.full_name = ".Cmd.EAfkStatus"
EAFKSTATUS.values = {
  EAFKSTATUS_EAFKSTATUS_OPEN_ENUM,
  EAFKSTATUS_EAFKSTATUS_TIMEOUT_EXIT_ENUM,
  EAFKSTATUS_EAFKSTATUS_NOBATTLE_EXIT_ENUM,
  EAFKSTATUS_EAFKSTATUS_RESTART_EXIT_ENUM
}
REQAFKUSERAFKCMD_CMD_FIELD.name = "cmd"
REQAFKUSERAFKCMD_CMD_FIELD.full_name = ".Cmd.ReqAfkUserAfkCmd.cmd"
REQAFKUSERAFKCMD_CMD_FIELD.number = 1
REQAFKUSERAFKCMD_CMD_FIELD.index = 0
REQAFKUSERAFKCMD_CMD_FIELD.label = 1
REQAFKUSERAFKCMD_CMD_FIELD.has_default_value = true
REQAFKUSERAFKCMD_CMD_FIELD.default_value = 74
REQAFKUSERAFKCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
REQAFKUSERAFKCMD_CMD_FIELD.type = 14
REQAFKUSERAFKCMD_CMD_FIELD.cpp_type = 8
REQAFKUSERAFKCMD_PARAM_FIELD.name = "param"
REQAFKUSERAFKCMD_PARAM_FIELD.full_name = ".Cmd.ReqAfkUserAfkCmd.param"
REQAFKUSERAFKCMD_PARAM_FIELD.number = 2
REQAFKUSERAFKCMD_PARAM_FIELD.index = 1
REQAFKUSERAFKCMD_PARAM_FIELD.label = 1
REQAFKUSERAFKCMD_PARAM_FIELD.has_default_value = true
REQAFKUSERAFKCMD_PARAM_FIELD.default_value = 1
REQAFKUSERAFKCMD_PARAM_FIELD.enum_type = USERAFKCMDPARAM
REQAFKUSERAFKCMD_PARAM_FIELD.type = 14
REQAFKUSERAFKCMD_PARAM_FIELD.cpp_type = 8
REQAFKUSERAFKCMD_TIMELEN_FIELD.name = "timelen"
REQAFKUSERAFKCMD_TIMELEN_FIELD.full_name = ".Cmd.ReqAfkUserAfkCmd.timelen"
REQAFKUSERAFKCMD_TIMELEN_FIELD.number = 3
REQAFKUSERAFKCMD_TIMELEN_FIELD.index = 2
REQAFKUSERAFKCMD_TIMELEN_FIELD.label = 1
REQAFKUSERAFKCMD_TIMELEN_FIELD.has_default_value = false
REQAFKUSERAFKCMD_TIMELEN_FIELD.default_value = 0
REQAFKUSERAFKCMD_TIMELEN_FIELD.type = 13
REQAFKUSERAFKCMD_TIMELEN_FIELD.cpp_type = 3
REQAFKUSERAFKCMD_INPLACE_FIELD.name = "inplace"
REQAFKUSERAFKCMD_INPLACE_FIELD.full_name = ".Cmd.ReqAfkUserAfkCmd.inplace"
REQAFKUSERAFKCMD_INPLACE_FIELD.number = 4
REQAFKUSERAFKCMD_INPLACE_FIELD.index = 3
REQAFKUSERAFKCMD_INPLACE_FIELD.label = 1
REQAFKUSERAFKCMD_INPLACE_FIELD.has_default_value = false
REQAFKUSERAFKCMD_INPLACE_FIELD.default_value = false
REQAFKUSERAFKCMD_INPLACE_FIELD.type = 8
REQAFKUSERAFKCMD_INPLACE_FIELD.cpp_type = 7
REQAFKUSERAFKCMD_PROTECT_TEAM_FIELD.name = "protect_team"
REQAFKUSERAFKCMD_PROTECT_TEAM_FIELD.full_name = ".Cmd.ReqAfkUserAfkCmd.protect_team"
REQAFKUSERAFKCMD_PROTECT_TEAM_FIELD.number = 5
REQAFKUSERAFKCMD_PROTECT_TEAM_FIELD.index = 4
REQAFKUSERAFKCMD_PROTECT_TEAM_FIELD.label = 1
REQAFKUSERAFKCMD_PROTECT_TEAM_FIELD.has_default_value = false
REQAFKUSERAFKCMD_PROTECT_TEAM_FIELD.default_value = false
REQAFKUSERAFKCMD_PROTECT_TEAM_FIELD.type = 8
REQAFKUSERAFKCMD_PROTECT_TEAM_FIELD.cpp_type = 7
REQAFKUSERAFKCMD_MONSTERIDS_FIELD.name = "monsterids"
REQAFKUSERAFKCMD_MONSTERIDS_FIELD.full_name = ".Cmd.ReqAfkUserAfkCmd.monsterids"
REQAFKUSERAFKCMD_MONSTERIDS_FIELD.number = 6
REQAFKUSERAFKCMD_MONSTERIDS_FIELD.index = 5
REQAFKUSERAFKCMD_MONSTERIDS_FIELD.label = 3
REQAFKUSERAFKCMD_MONSTERIDS_FIELD.has_default_value = false
REQAFKUSERAFKCMD_MONSTERIDS_FIELD.default_value = {}
REQAFKUSERAFKCMD_MONSTERIDS_FIELD.type = 13
REQAFKUSERAFKCMD_MONSTERIDS_FIELD.cpp_type = 3
REQAFKUSERAFKCMD.name = "ReqAfkUserAfkCmd"
REQAFKUSERAFKCMD.full_name = ".Cmd.ReqAfkUserAfkCmd"
REQAFKUSERAFKCMD.nested_types = {}
REQAFKUSERAFKCMD.enum_types = {}
REQAFKUSERAFKCMD.fields = {
  REQAFKUSERAFKCMD_CMD_FIELD,
  REQAFKUSERAFKCMD_PARAM_FIELD,
  REQAFKUSERAFKCMD_TIMELEN_FIELD,
  REQAFKUSERAFKCMD_INPLACE_FIELD,
  REQAFKUSERAFKCMD_PROTECT_TEAM_FIELD,
  REQAFKUSERAFKCMD_MONSTERIDS_FIELD
}
REQAFKUSERAFKCMD.is_extendable = false
REQAFKUSERAFKCMD.extensions = {}
RETAFKUSERAFKCMD_CMD_FIELD.name = "cmd"
RETAFKUSERAFKCMD_CMD_FIELD.full_name = ".Cmd.RetAfkUserAfkCmd.cmd"
RETAFKUSERAFKCMD_CMD_FIELD.number = 1
RETAFKUSERAFKCMD_CMD_FIELD.index = 0
RETAFKUSERAFKCMD_CMD_FIELD.label = 1
RETAFKUSERAFKCMD_CMD_FIELD.has_default_value = true
RETAFKUSERAFKCMD_CMD_FIELD.default_value = 74
RETAFKUSERAFKCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
RETAFKUSERAFKCMD_CMD_FIELD.type = 14
RETAFKUSERAFKCMD_CMD_FIELD.cpp_type = 8
RETAFKUSERAFKCMD_PARAM_FIELD.name = "param"
RETAFKUSERAFKCMD_PARAM_FIELD.full_name = ".Cmd.RetAfkUserAfkCmd.param"
RETAFKUSERAFKCMD_PARAM_FIELD.number = 2
RETAFKUSERAFKCMD_PARAM_FIELD.index = 1
RETAFKUSERAFKCMD_PARAM_FIELD.label = 1
RETAFKUSERAFKCMD_PARAM_FIELD.has_default_value = true
RETAFKUSERAFKCMD_PARAM_FIELD.default_value = 2
RETAFKUSERAFKCMD_PARAM_FIELD.enum_type = USERAFKCMDPARAM
RETAFKUSERAFKCMD_PARAM_FIELD.type = 14
RETAFKUSERAFKCMD_PARAM_FIELD.cpp_type = 8
RETAFKUSERAFKCMD_RET_FIELD.name = "ret"
RETAFKUSERAFKCMD_RET_FIELD.full_name = ".Cmd.RetAfkUserAfkCmd.ret"
RETAFKUSERAFKCMD_RET_FIELD.number = 3
RETAFKUSERAFKCMD_RET_FIELD.index = 2
RETAFKUSERAFKCMD_RET_FIELD.label = 1
RETAFKUSERAFKCMD_RET_FIELD.has_default_value = false
RETAFKUSERAFKCMD_RET_FIELD.default_value = false
RETAFKUSERAFKCMD_RET_FIELD.type = 8
RETAFKUSERAFKCMD_RET_FIELD.cpp_type = 7
RETAFKUSERAFKCMD.name = "RetAfkUserAfkCmd"
RETAFKUSERAFKCMD.full_name = ".Cmd.RetAfkUserAfkCmd"
RETAFKUSERAFKCMD.nested_types = {}
RETAFKUSERAFKCMD.enum_types = {}
RETAFKUSERAFKCMD.fields = {
  RETAFKUSERAFKCMD_CMD_FIELD,
  RETAFKUSERAFKCMD_PARAM_FIELD,
  RETAFKUSERAFKCMD_RET_FIELD
}
RETAFKUSERAFKCMD.is_extendable = false
RETAFKUSERAFKCMD.extensions = {}
MONEYDATA_ETYPE_FIELD.name = "etype"
MONEYDATA_ETYPE_FIELD.full_name = ".Cmd.MoneyData.etype"
MONEYDATA_ETYPE_FIELD.number = 1
MONEYDATA_ETYPE_FIELD.index = 0
MONEYDATA_ETYPE_FIELD.label = 1
MONEYDATA_ETYPE_FIELD.has_default_value = false
MONEYDATA_ETYPE_FIELD.default_value = nil
MONEYDATA_ETYPE_FIELD.enum_type = PROTOCOMMON_PB_EMONEYTYPE
MONEYDATA_ETYPE_FIELD.type = 14
MONEYDATA_ETYPE_FIELD.cpp_type = 8
MONEYDATA_VALUE_FIELD.name = "value"
MONEYDATA_VALUE_FIELD.full_name = ".Cmd.MoneyData.value"
MONEYDATA_VALUE_FIELD.number = 2
MONEYDATA_VALUE_FIELD.index = 1
MONEYDATA_VALUE_FIELD.label = 1
MONEYDATA_VALUE_FIELD.has_default_value = false
MONEYDATA_VALUE_FIELD.default_value = 0
MONEYDATA_VALUE_FIELD.type = 13
MONEYDATA_VALUE_FIELD.cpp_type = 3
MONEYDATA.name = "MoneyData"
MONEYDATA.full_name = ".Cmd.MoneyData"
MONEYDATA.nested_types = {}
MONEYDATA.enum_types = {}
MONEYDATA.fields = {
  MONEYDATA_ETYPE_FIELD,
  MONEYDATA_VALUE_FIELD
}
MONEYDATA.is_extendable = false
MONEYDATA.extensions = {}
AFKKILLINFO_MONSTERID_FIELD.name = "monsterid"
AFKKILLINFO_MONSTERID_FIELD.full_name = ".Cmd.AfkKillInfo.monsterid"
AFKKILLINFO_MONSTERID_FIELD.number = 1
AFKKILLINFO_MONSTERID_FIELD.index = 0
AFKKILLINFO_MONSTERID_FIELD.label = 1
AFKKILLINFO_MONSTERID_FIELD.has_default_value = false
AFKKILLINFO_MONSTERID_FIELD.default_value = 0
AFKKILLINFO_MONSTERID_FIELD.type = 13
AFKKILLINFO_MONSTERID_FIELD.cpp_type = 3
AFKKILLINFO_COUNT_FIELD.name = "count"
AFKKILLINFO_COUNT_FIELD.full_name = ".Cmd.AfkKillInfo.count"
AFKKILLINFO_COUNT_FIELD.number = 2
AFKKILLINFO_COUNT_FIELD.index = 1
AFKKILLINFO_COUNT_FIELD.label = 1
AFKKILLINFO_COUNT_FIELD.has_default_value = false
AFKKILLINFO_COUNT_FIELD.default_value = 0
AFKKILLINFO_COUNT_FIELD.type = 13
AFKKILLINFO_COUNT_FIELD.cpp_type = 3
AFKKILLINFO.name = "AfkKillInfo"
AFKKILLINFO.full_name = ".Cmd.AfkKillInfo"
AFKKILLINFO.nested_types = {}
AFKKILLINFO.enum_types = {}
AFKKILLINFO.fields = {
  AFKKILLINFO_MONSTERID_FIELD,
  AFKKILLINFO_COUNT_FIELD
}
AFKKILLINFO.is_extendable = false
AFKKILLINFO.extensions = {}
BATTLETIMEDATA_TOTALTIME_FIELD.name = "totaltime"
BATTLETIMEDATA_TOTALTIME_FIELD.full_name = ".Cmd.BattleTimeData.totaltime"
BATTLETIMEDATA_TOTALTIME_FIELD.number = 1
BATTLETIMEDATA_TOTALTIME_FIELD.index = 0
BATTLETIMEDATA_TOTALTIME_FIELD.label = 1
BATTLETIMEDATA_TOTALTIME_FIELD.has_default_value = false
BATTLETIMEDATA_TOTALTIME_FIELD.default_value = 0
BATTLETIMEDATA_TOTALTIME_FIELD.type = 13
BATTLETIMEDATA_TOTALTIME_FIELD.cpp_type = 3
BATTLETIMEDATA_USEDTIME_FIELD.name = "usedtime"
BATTLETIMEDATA_USEDTIME_FIELD.full_name = ".Cmd.BattleTimeData.usedtime"
BATTLETIMEDATA_USEDTIME_FIELD.number = 2
BATTLETIMEDATA_USEDTIME_FIELD.index = 1
BATTLETIMEDATA_USEDTIME_FIELD.label = 1
BATTLETIMEDATA_USEDTIME_FIELD.has_default_value = false
BATTLETIMEDATA_USEDTIME_FIELD.default_value = 0
BATTLETIMEDATA_USEDTIME_FIELD.type = 13
BATTLETIMEDATA_USEDTIME_FIELD.cpp_type = 3
BATTLETIMEDATA_ESTATUS_FIELD.name = "estatus"
BATTLETIMEDATA_ESTATUS_FIELD.full_name = ".Cmd.BattleTimeData.estatus"
BATTLETIMEDATA_ESTATUS_FIELD.number = 3
BATTLETIMEDATA_ESTATUS_FIELD.index = 2
BATTLETIMEDATA_ESTATUS_FIELD.label = 1
BATTLETIMEDATA_ESTATUS_FIELD.has_default_value = false
BATTLETIMEDATA_ESTATUS_FIELD.default_value = nil
BATTLETIMEDATA_ESTATUS_FIELD.enum_type = SCENEUSER2_PB_EBATTLESTATUS
BATTLETIMEDATA_ESTATUS_FIELD.type = 14
BATTLETIMEDATA_ESTATUS_FIELD.cpp_type = 8
BATTLETIMEDATA.name = "BattleTimeData"
BATTLETIMEDATA.full_name = ".Cmd.BattleTimeData"
BATTLETIMEDATA.nested_types = {}
BATTLETIMEDATA.enum_types = {}
BATTLETIMEDATA.fields = {
  BATTLETIMEDATA_TOTALTIME_FIELD,
  BATTLETIMEDATA_USEDTIME_FIELD,
  BATTLETIMEDATA_ESTATUS_FIELD
}
BATTLETIMEDATA.is_extendable = false
BATTLETIMEDATA.extensions = {}
USERAFKSTATDATA_BASEEXP_FIELD.name = "baseexp"
USERAFKSTATDATA_BASEEXP_FIELD.full_name = ".Cmd.UserAfkStatData.baseexp"
USERAFKSTATDATA_BASEEXP_FIELD.number = 1
USERAFKSTATDATA_BASEEXP_FIELD.index = 0
USERAFKSTATDATA_BASEEXP_FIELD.label = 1
USERAFKSTATDATA_BASEEXP_FIELD.has_default_value = false
USERAFKSTATDATA_BASEEXP_FIELD.default_value = 0
USERAFKSTATDATA_BASEEXP_FIELD.type = 5
USERAFKSTATDATA_BASEEXP_FIELD.cpp_type = 1
USERAFKSTATDATA_JOBEXP_FIELD.name = "jobexp"
USERAFKSTATDATA_JOBEXP_FIELD.full_name = ".Cmd.UserAfkStatData.jobexp"
USERAFKSTATDATA_JOBEXP_FIELD.number = 2
USERAFKSTATDATA_JOBEXP_FIELD.index = 1
USERAFKSTATDATA_JOBEXP_FIELD.label = 1
USERAFKSTATDATA_JOBEXP_FIELD.has_default_value = false
USERAFKSTATDATA_JOBEXP_FIELD.default_value = 0
USERAFKSTATDATA_JOBEXP_FIELD.type = 5
USERAFKSTATDATA_JOBEXP_FIELD.cpp_type = 1
USERAFKSTATDATA_ITEMS_FIELD.name = "items"
USERAFKSTATDATA_ITEMS_FIELD.full_name = ".Cmd.UserAfkStatData.items"
USERAFKSTATDATA_ITEMS_FIELD.number = 3
USERAFKSTATDATA_ITEMS_FIELD.index = 2
USERAFKSTATDATA_ITEMS_FIELD.label = 3
USERAFKSTATDATA_ITEMS_FIELD.has_default_value = false
USERAFKSTATDATA_ITEMS_FIELD.default_value = {}
USERAFKSTATDATA_ITEMS_FIELD.message_type = SceneItem_pb.ITEMINFO
USERAFKSTATDATA_ITEMS_FIELD.type = 11
USERAFKSTATDATA_ITEMS_FIELD.cpp_type = 10
USERAFKSTATDATA_MONEYS_FIELD.name = "moneys"
USERAFKSTATDATA_MONEYS_FIELD.full_name = ".Cmd.UserAfkStatData.moneys"
USERAFKSTATDATA_MONEYS_FIELD.number = 4
USERAFKSTATDATA_MONEYS_FIELD.index = 3
USERAFKSTATDATA_MONEYS_FIELD.label = 3
USERAFKSTATDATA_MONEYS_FIELD.has_default_value = false
USERAFKSTATDATA_MONEYS_FIELD.default_value = {}
USERAFKSTATDATA_MONEYS_FIELD.message_type = MONEYDATA
USERAFKSTATDATA_MONEYS_FIELD.type = 11
USERAFKSTATDATA_MONEYS_FIELD.cpp_type = 10
USERAFKSTATDATA_EXTRA_ZENY_FIELD.name = "extra_zeny"
USERAFKSTATDATA_EXTRA_ZENY_FIELD.full_name = ".Cmd.UserAfkStatData.extra_zeny"
USERAFKSTATDATA_EXTRA_ZENY_FIELD.number = 5
USERAFKSTATDATA_EXTRA_ZENY_FIELD.index = 4
USERAFKSTATDATA_EXTRA_ZENY_FIELD.label = 1
USERAFKSTATDATA_EXTRA_ZENY_FIELD.has_default_value = false
USERAFKSTATDATA_EXTRA_ZENY_FIELD.default_value = 0
USERAFKSTATDATA_EXTRA_ZENY_FIELD.type = 13
USERAFKSTATDATA_EXTRA_ZENY_FIELD.cpp_type = 3
USERAFKSTATDATA_EXTRA_BASE_FIELD.name = "extra_base"
USERAFKSTATDATA_EXTRA_BASE_FIELD.full_name = ".Cmd.UserAfkStatData.extra_base"
USERAFKSTATDATA_EXTRA_BASE_FIELD.number = 6
USERAFKSTATDATA_EXTRA_BASE_FIELD.index = 5
USERAFKSTATDATA_EXTRA_BASE_FIELD.label = 1
USERAFKSTATDATA_EXTRA_BASE_FIELD.has_default_value = false
USERAFKSTATDATA_EXTRA_BASE_FIELD.default_value = 0
USERAFKSTATDATA_EXTRA_BASE_FIELD.type = 13
USERAFKSTATDATA_EXTRA_BASE_FIELD.cpp_type = 3
USERAFKSTATDATA_EXTRA_JOB_FIELD.name = "extra_job"
USERAFKSTATDATA_EXTRA_JOB_FIELD.full_name = ".Cmd.UserAfkStatData.extra_job"
USERAFKSTATDATA_EXTRA_JOB_FIELD.number = 7
USERAFKSTATDATA_EXTRA_JOB_FIELD.index = 6
USERAFKSTATDATA_EXTRA_JOB_FIELD.label = 1
USERAFKSTATDATA_EXTRA_JOB_FIELD.has_default_value = false
USERAFKSTATDATA_EXTRA_JOB_FIELD.default_value = 0
USERAFKSTATDATA_EXTRA_JOB_FIELD.type = 13
USERAFKSTATDATA_EXTRA_JOB_FIELD.cpp_type = 3
USERAFKSTATDATA_EXTRA_TIME_FIELD.name = "extra_time"
USERAFKSTATDATA_EXTRA_TIME_FIELD.full_name = ".Cmd.UserAfkStatData.extra_time"
USERAFKSTATDATA_EXTRA_TIME_FIELD.number = 8
USERAFKSTATDATA_EXTRA_TIME_FIELD.index = 7
USERAFKSTATDATA_EXTRA_TIME_FIELD.label = 1
USERAFKSTATDATA_EXTRA_TIME_FIELD.has_default_value = false
USERAFKSTATDATA_EXTRA_TIME_FIELD.default_value = 0
USERAFKSTATDATA_EXTRA_TIME_FIELD.type = 13
USERAFKSTATDATA_EXTRA_TIME_FIELD.cpp_type = 3
USERAFKSTATDATA_KILLINFO_FIELD.name = "killinfo"
USERAFKSTATDATA_KILLINFO_FIELD.full_name = ".Cmd.UserAfkStatData.killinfo"
USERAFKSTATDATA_KILLINFO_FIELD.number = 9
USERAFKSTATDATA_KILLINFO_FIELD.index = 8
USERAFKSTATDATA_KILLINFO_FIELD.label = 3
USERAFKSTATDATA_KILLINFO_FIELD.has_default_value = false
USERAFKSTATDATA_KILLINFO_FIELD.default_value = {}
USERAFKSTATDATA_KILLINFO_FIELD.message_type = AFKKILLINFO
USERAFKSTATDATA_KILLINFO_FIELD.type = 11
USERAFKSTATDATA_KILLINFO_FIELD.cpp_type = 10
USERAFKSTATDATA_BE_KILLINFO_FIELD.name = "be_killinfo"
USERAFKSTATDATA_BE_KILLINFO_FIELD.full_name = ".Cmd.UserAfkStatData.be_killinfo"
USERAFKSTATDATA_BE_KILLINFO_FIELD.number = 10
USERAFKSTATDATA_BE_KILLINFO_FIELD.index = 9
USERAFKSTATDATA_BE_KILLINFO_FIELD.label = 3
USERAFKSTATDATA_BE_KILLINFO_FIELD.has_default_value = false
USERAFKSTATDATA_BE_KILLINFO_FIELD.default_value = {}
USERAFKSTATDATA_BE_KILLINFO_FIELD.message_type = AFKKILLINFO
USERAFKSTATDATA_BE_KILLINFO_FIELD.type = 11
USERAFKSTATDATA_BE_KILLINFO_FIELD.cpp_type = 10
USERAFKSTATDATA_BATTLE_TIME_FIELD.name = "battle_time"
USERAFKSTATDATA_BATTLE_TIME_FIELD.full_name = ".Cmd.UserAfkStatData.battle_time"
USERAFKSTATDATA_BATTLE_TIME_FIELD.number = 11
USERAFKSTATDATA_BATTLE_TIME_FIELD.index = 10
USERAFKSTATDATA_BATTLE_TIME_FIELD.label = 1
USERAFKSTATDATA_BATTLE_TIME_FIELD.has_default_value = false
USERAFKSTATDATA_BATTLE_TIME_FIELD.default_value = nil
USERAFKSTATDATA_BATTLE_TIME_FIELD.message_type = BATTLETIMEDATA
USERAFKSTATDATA_BATTLE_TIME_FIELD.type = 11
USERAFKSTATDATA_BATTLE_TIME_FIELD.cpp_type = 10
USERAFKSTATDATA_ESTATUS_FIELD.name = "estatus"
USERAFKSTATDATA_ESTATUS_FIELD.full_name = ".Cmd.UserAfkStatData.estatus"
USERAFKSTATDATA_ESTATUS_FIELD.number = 12
USERAFKSTATDATA_ESTATUS_FIELD.index = 11
USERAFKSTATDATA_ESTATUS_FIELD.label = 1
USERAFKSTATDATA_ESTATUS_FIELD.has_default_value = false
USERAFKSTATDATA_ESTATUS_FIELD.default_value = nil
USERAFKSTATDATA_ESTATUS_FIELD.enum_type = EAFKSTATUS
USERAFKSTATDATA_ESTATUS_FIELD.type = 14
USERAFKSTATDATA_ESTATUS_FIELD.cpp_type = 8
USERAFKSTATDATA_TIMELEN_FIELD.name = "timelen"
USERAFKSTATDATA_TIMELEN_FIELD.full_name = ".Cmd.UserAfkStatData.timelen"
USERAFKSTATDATA_TIMELEN_FIELD.number = 13
USERAFKSTATDATA_TIMELEN_FIELD.index = 12
USERAFKSTATDATA_TIMELEN_FIELD.label = 1
USERAFKSTATDATA_TIMELEN_FIELD.has_default_value = false
USERAFKSTATDATA_TIMELEN_FIELD.default_value = 0
USERAFKSTATDATA_TIMELEN_FIELD.type = 13
USERAFKSTATDATA_TIMELEN_FIELD.cpp_type = 3
USERAFKSTATDATA_KILL_COUNT_FIELD.name = "kill_count"
USERAFKSTATDATA_KILL_COUNT_FIELD.full_name = ".Cmd.UserAfkStatData.kill_count"
USERAFKSTATDATA_KILL_COUNT_FIELD.number = 14
USERAFKSTATDATA_KILL_COUNT_FIELD.index = 13
USERAFKSTATDATA_KILL_COUNT_FIELD.label = 1
USERAFKSTATDATA_KILL_COUNT_FIELD.has_default_value = false
USERAFKSTATDATA_KILL_COUNT_FIELD.default_value = 0
USERAFKSTATDATA_KILL_COUNT_FIELD.type = 13
USERAFKSTATDATA_KILL_COUNT_FIELD.cpp_type = 3
USERAFKSTATDATA_LEFT_AFK_COUNT_FIELD.name = "left_afk_count"
USERAFKSTATDATA_LEFT_AFK_COUNT_FIELD.full_name = ".Cmd.UserAfkStatData.left_afk_count"
USERAFKSTATDATA_LEFT_AFK_COUNT_FIELD.number = 15
USERAFKSTATDATA_LEFT_AFK_COUNT_FIELD.index = 14
USERAFKSTATDATA_LEFT_AFK_COUNT_FIELD.label = 1
USERAFKSTATDATA_LEFT_AFK_COUNT_FIELD.has_default_value = false
USERAFKSTATDATA_LEFT_AFK_COUNT_FIELD.default_value = 0
USERAFKSTATDATA_LEFT_AFK_COUNT_FIELD.type = 13
USERAFKSTATDATA_LEFT_AFK_COUNT_FIELD.cpp_type = 3
USERAFKSTATDATA.name = "UserAfkStatData"
USERAFKSTATDATA.full_name = ".Cmd.UserAfkStatData"
USERAFKSTATDATA.nested_types = {}
USERAFKSTATDATA.enum_types = {}
USERAFKSTATDATA.fields = {
  USERAFKSTATDATA_BASEEXP_FIELD,
  USERAFKSTATDATA_JOBEXP_FIELD,
  USERAFKSTATDATA_ITEMS_FIELD,
  USERAFKSTATDATA_MONEYS_FIELD,
  USERAFKSTATDATA_EXTRA_ZENY_FIELD,
  USERAFKSTATDATA_EXTRA_BASE_FIELD,
  USERAFKSTATDATA_EXTRA_JOB_FIELD,
  USERAFKSTATDATA_EXTRA_TIME_FIELD,
  USERAFKSTATDATA_KILLINFO_FIELD,
  USERAFKSTATDATA_BE_KILLINFO_FIELD,
  USERAFKSTATDATA_BATTLE_TIME_FIELD,
  USERAFKSTATDATA_ESTATUS_FIELD,
  USERAFKSTATDATA_TIMELEN_FIELD,
  USERAFKSTATDATA_KILL_COUNT_FIELD,
  USERAFKSTATDATA_LEFT_AFK_COUNT_FIELD
}
USERAFKSTATDATA.is_extendable = false
USERAFKSTATDATA.extensions = {}
SYNCSTATINFOAFKCMD_CMD_FIELD.name = "cmd"
SYNCSTATINFOAFKCMD_CMD_FIELD.full_name = ".Cmd.SyncStatInfoAfkCmd.cmd"
SYNCSTATINFOAFKCMD_CMD_FIELD.number = 1
SYNCSTATINFOAFKCMD_CMD_FIELD.index = 0
SYNCSTATINFOAFKCMD_CMD_FIELD.label = 1
SYNCSTATINFOAFKCMD_CMD_FIELD.has_default_value = true
SYNCSTATINFOAFKCMD_CMD_FIELD.default_value = 74
SYNCSTATINFOAFKCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
SYNCSTATINFOAFKCMD_CMD_FIELD.type = 14
SYNCSTATINFOAFKCMD_CMD_FIELD.cpp_type = 8
SYNCSTATINFOAFKCMD_PARAM_FIELD.name = "param"
SYNCSTATINFOAFKCMD_PARAM_FIELD.full_name = ".Cmd.SyncStatInfoAfkCmd.param"
SYNCSTATINFOAFKCMD_PARAM_FIELD.number = 2
SYNCSTATINFOAFKCMD_PARAM_FIELD.index = 1
SYNCSTATINFOAFKCMD_PARAM_FIELD.label = 1
SYNCSTATINFOAFKCMD_PARAM_FIELD.has_default_value = true
SYNCSTATINFOAFKCMD_PARAM_FIELD.default_value = 3
SYNCSTATINFOAFKCMD_PARAM_FIELD.enum_type = USERAFKCMDPARAM
SYNCSTATINFOAFKCMD_PARAM_FIELD.type = 14
SYNCSTATINFOAFKCMD_PARAM_FIELD.cpp_type = 8
SYNCSTATINFOAFKCMD_STATDATA_FIELD.name = "statdata"
SYNCSTATINFOAFKCMD_STATDATA_FIELD.full_name = ".Cmd.SyncStatInfoAfkCmd.statdata"
SYNCSTATINFOAFKCMD_STATDATA_FIELD.number = 3
SYNCSTATINFOAFKCMD_STATDATA_FIELD.index = 2
SYNCSTATINFOAFKCMD_STATDATA_FIELD.label = 1
SYNCSTATINFOAFKCMD_STATDATA_FIELD.has_default_value = false
SYNCSTATINFOAFKCMD_STATDATA_FIELD.default_value = nil
SYNCSTATINFOAFKCMD_STATDATA_FIELD.message_type = USERAFKSTATDATA
SYNCSTATINFOAFKCMD_STATDATA_FIELD.type = 11
SYNCSTATINFOAFKCMD_STATDATA_FIELD.cpp_type = 10
SYNCSTATINFOAFKCMD.name = "SyncStatInfoAfkCmd"
SYNCSTATINFOAFKCMD.full_name = ".Cmd.SyncStatInfoAfkCmd"
SYNCSTATINFOAFKCMD.nested_types = {}
SYNCSTATINFOAFKCMD.enum_types = {}
SYNCSTATINFOAFKCMD.fields = {
  SYNCSTATINFOAFKCMD_CMD_FIELD,
  SYNCSTATINFOAFKCMD_PARAM_FIELD,
  SYNCSTATINFOAFKCMD_STATDATA_FIELD
}
SYNCSTATINFOAFKCMD.is_extendable = false
SYNCSTATINFOAFKCMD.extensions = {}
AfkKillInfo = protobuf.Message(AFKKILLINFO)
BattleTimeData = protobuf.Message(BATTLETIMEDATA)
EAFKSTATUS_NOBATTLE_EXIT = 2
EAFKSTATUS_OPEN = 0
EAFKSTATUS_RESTART_EXIT = 3
EAFKSTATUS_TIMEOUT_EXIT = 1
MoneyData = protobuf.Message(MONEYDATA)
ReqAfkUserAfkCmd = protobuf.Message(REQAFKUSERAFKCMD)
RetAfkUserAfkCmd = protobuf.Message(RETAFKUSERAFKCMD)
SyncStatInfoAfkCmd = protobuf.Message(SYNCSTATINFOAFKCMD)
USER_AFKCMD_REQ_AFK = 1
USER_AFKCMD_RET_AFK = 2
USER_AFKCMD_SYNC_STATINFO = 3
UserAfkStatData = protobuf.Message(USERAFKSTATDATA)
