local protobuf = protobuf
module("xCmd_pb")
COMMAND = protobuf.EnumDescriptor()
COMMAND_LOGIN_USER_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_ERROR_USER_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_SCENE_USER_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_SCENE_USER_ITEM_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_SCENE_USER_SKILL_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_SCENE_USER_QUEST_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_SCENE_USER2_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_SCENE_USER_PET_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_FUBEN_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_SCENE_USER_MAP_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_SCENE_USER_MOUNT_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_SCENE_BOSS_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_SCENE_USER_CARRIER_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_SCENE_USER_ACHIEVE_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_SCENE_USER_TIP_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_SCENE_USER_CHATROOM_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_INFINITE_TOWER_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_SCENE_USER_SEAL_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_SCENE_USER_INTER_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_SCENE_USER_MANUAL_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_SCENE_USER_CHAT_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_USER_EVENT_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_SCENE_USER_TRADE_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_SCENE_USER_AUGURY_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_SCENE_USER_ASTROLABE_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_SCENE_USER_FOOD_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_SCENE_USER_PHOTO_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_SCENE_USER_TUTOR_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_SCENE_USER_BEING_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_SESSION_USER_GUILD_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_SESSION_USER_TEAM_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_SESSION_USER_SHOP_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_SESSION_USER_WEATHER_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_SESSION_USER_MAIL_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_SESSION_USER_SOCIALITY_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_RECORD_USER_TRADE_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_DOJO_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_CHAT_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_ACTIVITY_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_MATCHC_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_SESSION_USER_AUTHORIZE_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_AUCTIONC_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_ACTIVITY_EVENT_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_WEDDINGC_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_PVE_CARD_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_TEAM_RAID_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_PUZZLE_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_TEAM_GROUP_RAID_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_HOMEC_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_ROGUELIKE_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_ROGUELIKE_PROTOSCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_TECHTREE_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_USER_AFK_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_RAID_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_NOVICE_BATTLE_PASS_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_QUEUE_ENTER_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_SESSION_OVERSEAS_TW_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_SCENE_OVERSEAS_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_SCENE_USER3_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_MESSC_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_CLIENT_CMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_MAX_USER_CMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_RECORD_DATA_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_TRADE_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_SESSION_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_GMTOOLS_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_LOG_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_GATE_SUPER_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_REGION_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_STAT_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_SOCIAL_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_TEAM_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_GUILD_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_GZONE_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_MATCHS_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_AUCTIONS_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_WEDDINGS_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_GTEAM_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_BOSSS_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_INTERACT_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_CARRIERS_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_HOMES_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_MONITOR_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_CHATS_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_BATTLEPASS_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_MINIGAME_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_REWARD_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_USERSHOW_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_ACTHITPOLLY_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_QUESTS_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_MINIGAMES_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_ACTMINIRO_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_RAIDS_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_NOVICE_NOTEBOOK_ENUM = protobuf.EnumValueDescriptor()
COMMAND_DISNEY_ACTIVITY_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_SCENE_USER_MANOR_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_FAMILY_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_SERVANT_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_MESSS_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_MAILS_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_BRANCHS_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_REG_CMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_GATEWAY_CMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_GLOBAL_ACTIVITY_CMD_ENUM = protobuf.EnumValueDescriptor()
COMMAND_SYSTEM_PROTOCMD_ENUM = protobuf.EnumValueDescriptor()
NONCE = protobuf.Descriptor()
NONCE_TIMESTAMP_FIELD = protobuf.FieldDescriptor()
NONCE_INDEX_FIELD = protobuf.FieldDescriptor()
NONCE_SIGN_FIELD = protobuf.FieldDescriptor()
COMMAND_LOGIN_USER_PROTOCMD_ENUM.name = "LOGIN_USER_PROTOCMD"
COMMAND_LOGIN_USER_PROTOCMD_ENUM.index = 0
COMMAND_LOGIN_USER_PROTOCMD_ENUM.number = 1
COMMAND_ERROR_USER_PROTOCMD_ENUM.name = "ERROR_USER_PROTOCMD"
COMMAND_ERROR_USER_PROTOCMD_ENUM.index = 1
COMMAND_ERROR_USER_PROTOCMD_ENUM.number = 2
COMMAND_SCENE_USER_PROTOCMD_ENUM.name = "SCENE_USER_PROTOCMD"
COMMAND_SCENE_USER_PROTOCMD_ENUM.index = 2
COMMAND_SCENE_USER_PROTOCMD_ENUM.number = 5
COMMAND_SCENE_USER_ITEM_PROTOCMD_ENUM.name = "SCENE_USER_ITEM_PROTOCMD"
COMMAND_SCENE_USER_ITEM_PROTOCMD_ENUM.index = 3
COMMAND_SCENE_USER_ITEM_PROTOCMD_ENUM.number = 6
COMMAND_SCENE_USER_SKILL_PROTOCMD_ENUM.name = "SCENE_USER_SKILL_PROTOCMD"
COMMAND_SCENE_USER_SKILL_PROTOCMD_ENUM.index = 4
COMMAND_SCENE_USER_SKILL_PROTOCMD_ENUM.number = 7
COMMAND_SCENE_USER_QUEST_PROTOCMD_ENUM.name = "SCENE_USER_QUEST_PROTOCMD"
COMMAND_SCENE_USER_QUEST_PROTOCMD_ENUM.index = 5
COMMAND_SCENE_USER_QUEST_PROTOCMD_ENUM.number = 8
COMMAND_SCENE_USER2_PROTOCMD_ENUM.name = "SCENE_USER2_PROTOCMD"
COMMAND_SCENE_USER2_PROTOCMD_ENUM.index = 6
COMMAND_SCENE_USER2_PROTOCMD_ENUM.number = 9
COMMAND_SCENE_USER_PET_PROTOCMD_ENUM.name = "SCENE_USER_PET_PROTOCMD"
COMMAND_SCENE_USER_PET_PROTOCMD_ENUM.index = 7
COMMAND_SCENE_USER_PET_PROTOCMD_ENUM.number = 10
COMMAND_FUBEN_PROTOCMD_ENUM.name = "FUBEN_PROTOCMD"
COMMAND_FUBEN_PROTOCMD_ENUM.index = 8
COMMAND_FUBEN_PROTOCMD_ENUM.number = 11
COMMAND_SCENE_USER_MAP_PROTOCMD_ENUM.name = "SCENE_USER_MAP_PROTOCMD"
COMMAND_SCENE_USER_MAP_PROTOCMD_ENUM.index = 9
COMMAND_SCENE_USER_MAP_PROTOCMD_ENUM.number = 12
COMMAND_SCENE_USER_MOUNT_PROTOCMD_ENUM.name = "SCENE_USER_MOUNT_PROTOCMD"
COMMAND_SCENE_USER_MOUNT_PROTOCMD_ENUM.index = 10
COMMAND_SCENE_USER_MOUNT_PROTOCMD_ENUM.number = 13
COMMAND_SCENE_BOSS_PROTOCMD_ENUM.name = "SCENE_BOSS_PROTOCMD"
COMMAND_SCENE_BOSS_PROTOCMD_ENUM.index = 11
COMMAND_SCENE_BOSS_PROTOCMD_ENUM.number = 15
COMMAND_SCENE_USER_CARRIER_PROTOCMD_ENUM.name = "SCENE_USER_CARRIER_PROTOCMD"
COMMAND_SCENE_USER_CARRIER_PROTOCMD_ENUM.index = 12
COMMAND_SCENE_USER_CARRIER_PROTOCMD_ENUM.number = 16
COMMAND_SCENE_USER_ACHIEVE_PROTOCMD_ENUM.name = "SCENE_USER_ACHIEVE_PROTOCMD"
COMMAND_SCENE_USER_ACHIEVE_PROTOCMD_ENUM.index = 13
COMMAND_SCENE_USER_ACHIEVE_PROTOCMD_ENUM.number = 17
COMMAND_SCENE_USER_TIP_PROTOCMD_ENUM.name = "SCENE_USER_TIP_PROTOCMD"
COMMAND_SCENE_USER_TIP_PROTOCMD_ENUM.index = 14
COMMAND_SCENE_USER_TIP_PROTOCMD_ENUM.number = 18
COMMAND_SCENE_USER_CHATROOM_PROTOCMD_ENUM.name = "SCENE_USER_CHATROOM_PROTOCMD"
COMMAND_SCENE_USER_CHATROOM_PROTOCMD_ENUM.index = 15
COMMAND_SCENE_USER_CHATROOM_PROTOCMD_ENUM.number = 19
COMMAND_INFINITE_TOWER_PROTOCMD_ENUM.name = "INFINITE_TOWER_PROTOCMD"
COMMAND_INFINITE_TOWER_PROTOCMD_ENUM.index = 16
COMMAND_INFINITE_TOWER_PROTOCMD_ENUM.number = 20
COMMAND_SCENE_USER_SEAL_PROTOCMD_ENUM.name = "SCENE_USER_SEAL_PROTOCMD"
COMMAND_SCENE_USER_SEAL_PROTOCMD_ENUM.index = 17
COMMAND_SCENE_USER_SEAL_PROTOCMD_ENUM.number = 21
COMMAND_SCENE_USER_INTER_PROTOCMD_ENUM.name = "SCENE_USER_INTER_PROTOCMD"
COMMAND_SCENE_USER_INTER_PROTOCMD_ENUM.index = 18
COMMAND_SCENE_USER_INTER_PROTOCMD_ENUM.number = 22
COMMAND_SCENE_USER_MANUAL_PROTOCMD_ENUM.name = "SCENE_USER_MANUAL_PROTOCMD"
COMMAND_SCENE_USER_MANUAL_PROTOCMD_ENUM.index = 19
COMMAND_SCENE_USER_MANUAL_PROTOCMD_ENUM.number = 23
COMMAND_SCENE_USER_CHAT_PROTOCMD_ENUM.name = "SCENE_USER_CHAT_PROTOCMD"
COMMAND_SCENE_USER_CHAT_PROTOCMD_ENUM.index = 20
COMMAND_SCENE_USER_CHAT_PROTOCMD_ENUM.number = 24
COMMAND_USER_EVENT_PROTOCMD_ENUM.name = "USER_EVENT_PROTOCMD"
COMMAND_USER_EVENT_PROTOCMD_ENUM.index = 21
COMMAND_USER_EVENT_PROTOCMD_ENUM.number = 25
COMMAND_SCENE_USER_TRADE_PROTOCMD_ENUM.name = "SCENE_USER_TRADE_PROTOCMD"
COMMAND_SCENE_USER_TRADE_PROTOCMD_ENUM.index = 22
COMMAND_SCENE_USER_TRADE_PROTOCMD_ENUM.number = 26
COMMAND_SCENE_USER_AUGURY_PROTOCMD_ENUM.name = "SCENE_USER_AUGURY_PROTOCMD"
COMMAND_SCENE_USER_AUGURY_PROTOCMD_ENUM.index = 23
COMMAND_SCENE_USER_AUGURY_PROTOCMD_ENUM.number = 27
COMMAND_SCENE_USER_ASTROLABE_PROTOCMD_ENUM.name = "SCENE_USER_ASTROLABE_PROTOCMD"
COMMAND_SCENE_USER_ASTROLABE_PROTOCMD_ENUM.index = 24
COMMAND_SCENE_USER_ASTROLABE_PROTOCMD_ENUM.number = 28
COMMAND_SCENE_USER_FOOD_PROTOCMD_ENUM.name = "SCENE_USER_FOOD_PROTOCMD"
COMMAND_SCENE_USER_FOOD_PROTOCMD_ENUM.index = 25
COMMAND_SCENE_USER_FOOD_PROTOCMD_ENUM.number = 29
COMMAND_SCENE_USER_PHOTO_PROTOCMD_ENUM.name = "SCENE_USER_PHOTO_PROTOCMD"
COMMAND_SCENE_USER_PHOTO_PROTOCMD_ENUM.index = 26
COMMAND_SCENE_USER_PHOTO_PROTOCMD_ENUM.number = 30
COMMAND_SCENE_USER_TUTOR_PROTOCMD_ENUM.name = "SCENE_USER_TUTOR_PROTOCMD"
COMMAND_SCENE_USER_TUTOR_PROTOCMD_ENUM.index = 27
COMMAND_SCENE_USER_TUTOR_PROTOCMD_ENUM.number = 31
COMMAND_SCENE_USER_BEING_PROTOCMD_ENUM.name = "SCENE_USER_BEING_PROTOCMD"
COMMAND_SCENE_USER_BEING_PROTOCMD_ENUM.index = 28
COMMAND_SCENE_USER_BEING_PROTOCMD_ENUM.number = 32
COMMAND_SESSION_USER_GUILD_PROTOCMD_ENUM.name = "SESSION_USER_GUILD_PROTOCMD"
COMMAND_SESSION_USER_GUILD_PROTOCMD_ENUM.index = 29
COMMAND_SESSION_USER_GUILD_PROTOCMD_ENUM.number = 50
COMMAND_SESSION_USER_TEAM_PROTOCMD_ENUM.name = "SESSION_USER_TEAM_PROTOCMD"
COMMAND_SESSION_USER_TEAM_PROTOCMD_ENUM.index = 30
COMMAND_SESSION_USER_TEAM_PROTOCMD_ENUM.number = 51
COMMAND_SESSION_USER_SHOP_PROTOCMD_ENUM.name = "SESSION_USER_SHOP_PROTOCMD"
COMMAND_SESSION_USER_SHOP_PROTOCMD_ENUM.index = 31
COMMAND_SESSION_USER_SHOP_PROTOCMD_ENUM.number = 52
COMMAND_SESSION_USER_WEATHER_PROTOCMD_ENUM.name = "SESSION_USER_WEATHER_PROTOCMD"
COMMAND_SESSION_USER_WEATHER_PROTOCMD_ENUM.index = 32
COMMAND_SESSION_USER_WEATHER_PROTOCMD_ENUM.number = 53
COMMAND_SESSION_USER_MAIL_PROTOCMD_ENUM.name = "SESSION_USER_MAIL_PROTOCMD"
COMMAND_SESSION_USER_MAIL_PROTOCMD_ENUM.index = 33
COMMAND_SESSION_USER_MAIL_PROTOCMD_ENUM.number = 55
COMMAND_SESSION_USER_SOCIALITY_PROTOCMD_ENUM.name = "SESSION_USER_SOCIALITY_PROTOCMD"
COMMAND_SESSION_USER_SOCIALITY_PROTOCMD_ENUM.index = 34
COMMAND_SESSION_USER_SOCIALITY_PROTOCMD_ENUM.number = 56
COMMAND_RECORD_USER_TRADE_PROTOCMD_ENUM.name = "RECORD_USER_TRADE_PROTOCMD"
COMMAND_RECORD_USER_TRADE_PROTOCMD_ENUM.index = 35
COMMAND_RECORD_USER_TRADE_PROTOCMD_ENUM.number = 57
COMMAND_DOJO_PROTOCMD_ENUM.name = "DOJO_PROTOCMD"
COMMAND_DOJO_PROTOCMD_ENUM.index = 36
COMMAND_DOJO_PROTOCMD_ENUM.number = 58
COMMAND_CHAT_PROTOCMD_ENUM.name = "CHAT_PROTOCMD"
COMMAND_CHAT_PROTOCMD_ENUM.index = 37
COMMAND_CHAT_PROTOCMD_ENUM.number = 59
COMMAND_ACTIVITY_PROTOCMD_ENUM.name = "ACTIVITY_PROTOCMD"
COMMAND_ACTIVITY_PROTOCMD_ENUM.index = 38
COMMAND_ACTIVITY_PROTOCMD_ENUM.number = 60
COMMAND_MATCHC_PROTOCMD_ENUM.name = "MATCHC_PROTOCMD"
COMMAND_MATCHC_PROTOCMD_ENUM.index = 39
COMMAND_MATCHC_PROTOCMD_ENUM.number = 61
COMMAND_SESSION_USER_AUTHORIZE_PROTOCMD_ENUM.name = "SESSION_USER_AUTHORIZE_PROTOCMD"
COMMAND_SESSION_USER_AUTHORIZE_PROTOCMD_ENUM.index = 40
COMMAND_SESSION_USER_AUTHORIZE_PROTOCMD_ENUM.number = 62
COMMAND_AUCTIONC_PROTOCMD_ENUM.name = "AUCTIONC_PROTOCMD"
COMMAND_AUCTIONC_PROTOCMD_ENUM.index = 41
COMMAND_AUCTIONC_PROTOCMD_ENUM.number = 63
COMMAND_ACTIVITY_EVENT_PROTOCMD_ENUM.name = "ACTIVITY_EVENT_PROTOCMD"
COMMAND_ACTIVITY_EVENT_PROTOCMD_ENUM.index = 42
COMMAND_ACTIVITY_EVENT_PROTOCMD_ENUM.number = 64
COMMAND_WEDDINGC_PROTOCMD_ENUM.name = "WEDDINGC_PROTOCMD"
COMMAND_WEDDINGC_PROTOCMD_ENUM.index = 43
COMMAND_WEDDINGC_PROTOCMD_ENUM.number = 65
COMMAND_PVE_CARD_PROTOCMD_ENUM.name = "PVE_CARD_PROTOCMD"
COMMAND_PVE_CARD_PROTOCMD_ENUM.index = 44
COMMAND_PVE_CARD_PROTOCMD_ENUM.number = 66
COMMAND_TEAM_RAID_PROTOCMD_ENUM.name = "TEAM_RAID_PROTOCMD"
COMMAND_TEAM_RAID_PROTOCMD_ENUM.index = 45
COMMAND_TEAM_RAID_PROTOCMD_ENUM.number = 67
COMMAND_PUZZLE_PROTOCMD_ENUM.name = "PUZZLE_PROTOCMD"
COMMAND_PUZZLE_PROTOCMD_ENUM.index = 46
COMMAND_PUZZLE_PROTOCMD_ENUM.number = 68
COMMAND_TEAM_GROUP_RAID_PROTOCMD_ENUM.name = "TEAM_GROUP_RAID_PROTOCMD"
COMMAND_TEAM_GROUP_RAID_PROTOCMD_ENUM.index = 47
COMMAND_TEAM_GROUP_RAID_PROTOCMD_ENUM.number = 69
COMMAND_HOMEC_PROTOCMD_ENUM.name = "HOMEC_PROTOCMD"
COMMAND_HOMEC_PROTOCMD_ENUM.index = 48
COMMAND_HOMEC_PROTOCMD_ENUM.number = 70
COMMAND_ROGUELIKE_PROTOCMD_ENUM.name = "ROGUELIKE_PROTOCMD"
COMMAND_ROGUELIKE_PROTOCMD_ENUM.index = 49
COMMAND_ROGUELIKE_PROTOCMD_ENUM.number = 71
COMMAND_ROGUELIKE_PROTOSCMD_ENUM.name = "ROGUELIKE_PROTOSCMD"
COMMAND_ROGUELIKE_PROTOSCMD_ENUM.index = 50
COMMAND_ROGUELIKE_PROTOSCMD_ENUM.number = 72
COMMAND_TECHTREE_PROTOCMD_ENUM.name = "TECHTREE_PROTOCMD"
COMMAND_TECHTREE_PROTOCMD_ENUM.index = 51
COMMAND_TECHTREE_PROTOCMD_ENUM.number = 73
COMMAND_USER_AFK_PROTOCMD_ENUM.name = "USER_AFK_PROTOCMD"
COMMAND_USER_AFK_PROTOCMD_ENUM.index = 52
COMMAND_USER_AFK_PROTOCMD_ENUM.number = 74
COMMAND_RAID_PROTOCMD_ENUM.name = "RAID_PROTOCMD"
COMMAND_RAID_PROTOCMD_ENUM.index = 53
COMMAND_RAID_PROTOCMD_ENUM.number = 76
COMMAND_NOVICE_BATTLE_PASS_PROTOCMD_ENUM.name = "NOVICE_BATTLE_PASS_PROTOCMD"
COMMAND_NOVICE_BATTLE_PASS_PROTOCMD_ENUM.index = 54
COMMAND_NOVICE_BATTLE_PASS_PROTOCMD_ENUM.number = 77
COMMAND_QUEUE_ENTER_PROTOCMD_ENUM.name = "QUEUE_ENTER_PROTOCMD"
COMMAND_QUEUE_ENTER_PROTOCMD_ENUM.index = 55
COMMAND_QUEUE_ENTER_PROTOCMD_ENUM.number = 78
COMMAND_SESSION_OVERSEAS_TW_PROTOCMD_ENUM.name = "SESSION_OVERSEAS_TW_PROTOCMD"
COMMAND_SESSION_OVERSEAS_TW_PROTOCMD_ENUM.index = 56
COMMAND_SESSION_OVERSEAS_TW_PROTOCMD_ENUM.number = 80
COMMAND_SCENE_OVERSEAS_PROTOCMD_ENUM.name = "SCENE_OVERSEAS_PROTOCMD"
COMMAND_SCENE_OVERSEAS_PROTOCMD_ENUM.index = 57
COMMAND_SCENE_OVERSEAS_PROTOCMD_ENUM.number = 81
COMMAND_SCENE_USER3_PROTOCMD_ENUM.name = "SCENE_USER3_PROTOCMD"
COMMAND_SCENE_USER3_PROTOCMD_ENUM.index = 58
COMMAND_SCENE_USER3_PROTOCMD_ENUM.number = 82
COMMAND_MESSC_PROTOCMD_ENUM.name = "MESSC_PROTOCMD"
COMMAND_MESSC_PROTOCMD_ENUM.index = 59
COMMAND_MESSC_PROTOCMD_ENUM.number = 83
COMMAND_CLIENT_CMD_ENUM.name = "CLIENT_CMD"
COMMAND_CLIENT_CMD_ENUM.index = 60
COMMAND_CLIENT_CMD_ENUM.number = 99
COMMAND_MAX_USER_CMD_ENUM.name = "MAX_USER_CMD"
COMMAND_MAX_USER_CMD_ENUM.index = 61
COMMAND_MAX_USER_CMD_ENUM.number = 100
COMMAND_RECORD_DATA_PROTOCMD_ENUM.name = "RECORD_DATA_PROTOCMD"
COMMAND_RECORD_DATA_PROTOCMD_ENUM.index = 62
COMMAND_RECORD_DATA_PROTOCMD_ENUM.number = 200
COMMAND_TRADE_PROTOCMD_ENUM.name = "TRADE_PROTOCMD"
COMMAND_TRADE_PROTOCMD_ENUM.index = 63
COMMAND_TRADE_PROTOCMD_ENUM.number = 201
COMMAND_SESSION_PROTOCMD_ENUM.name = "SESSION_PROTOCMD"
COMMAND_SESSION_PROTOCMD_ENUM.index = 64
COMMAND_SESSION_PROTOCMD_ENUM.number = 202
COMMAND_GMTOOLS_PROTOCMD_ENUM.name = "GMTOOLS_PROTOCMD"
COMMAND_GMTOOLS_PROTOCMD_ENUM.index = 65
COMMAND_GMTOOLS_PROTOCMD_ENUM.number = 203
COMMAND_LOG_PROTOCMD_ENUM.name = "LOG_PROTOCMD"
COMMAND_LOG_PROTOCMD_ENUM.index = 66
COMMAND_LOG_PROTOCMD_ENUM.number = 204
COMMAND_GATE_SUPER_PROTOCMD_ENUM.name = "GATE_SUPER_PROTOCMD"
COMMAND_GATE_SUPER_PROTOCMD_ENUM.index = 67
COMMAND_GATE_SUPER_PROTOCMD_ENUM.number = 205
COMMAND_REGION_PROTOCMD_ENUM.name = "REGION_PROTOCMD"
COMMAND_REGION_PROTOCMD_ENUM.index = 68
COMMAND_REGION_PROTOCMD_ENUM.number = 206
COMMAND_STAT_PROTOCMD_ENUM.name = "STAT_PROTOCMD"
COMMAND_STAT_PROTOCMD_ENUM.index = 69
COMMAND_STAT_PROTOCMD_ENUM.number = 207
COMMAND_SOCIAL_PROTOCMD_ENUM.name = "SOCIAL_PROTOCMD"
COMMAND_SOCIAL_PROTOCMD_ENUM.index = 70
COMMAND_SOCIAL_PROTOCMD_ENUM.number = 208
COMMAND_TEAM_PROTOCMD_ENUM.name = "TEAM_PROTOCMD"
COMMAND_TEAM_PROTOCMD_ENUM.index = 71
COMMAND_TEAM_PROTOCMD_ENUM.number = 209
COMMAND_GUILD_PROTOCMD_ENUM.name = "GUILD_PROTOCMD"
COMMAND_GUILD_PROTOCMD_ENUM.index = 72
COMMAND_GUILD_PROTOCMD_ENUM.number = 210
COMMAND_GZONE_PROTOCMD_ENUM.name = "GZONE_PROTOCMD"
COMMAND_GZONE_PROTOCMD_ENUM.index = 73
COMMAND_GZONE_PROTOCMD_ENUM.number = 211
COMMAND_MATCHS_PROTOCMD_ENUM.name = "MATCHS_PROTOCMD"
COMMAND_MATCHS_PROTOCMD_ENUM.index = 74
COMMAND_MATCHS_PROTOCMD_ENUM.number = 212
COMMAND_AUCTIONS_PROTOCMD_ENUM.name = "AUCTIONS_PROTOCMD"
COMMAND_AUCTIONS_PROTOCMD_ENUM.index = 75
COMMAND_AUCTIONS_PROTOCMD_ENUM.number = 213
COMMAND_WEDDINGS_PROTOCMD_ENUM.name = "WEDDINGS_PROTOCMD"
COMMAND_WEDDINGS_PROTOCMD_ENUM.index = 76
COMMAND_WEDDINGS_PROTOCMD_ENUM.number = 214
COMMAND_GTEAM_PROTOCMD_ENUM.name = "GTEAM_PROTOCMD"
COMMAND_GTEAM_PROTOCMD_ENUM.index = 77
COMMAND_GTEAM_PROTOCMD_ENUM.number = 215
COMMAND_BOSSS_PROTOCMD_ENUM.name = "BOSSS_PROTOCMD"
COMMAND_BOSSS_PROTOCMD_ENUM.index = 78
COMMAND_BOSSS_PROTOCMD_ENUM.number = 216
COMMAND_INTERACT_PROTOCMD_ENUM.name = "INTERACT_PROTOCMD"
COMMAND_INTERACT_PROTOCMD_ENUM.index = 79
COMMAND_INTERACT_PROTOCMD_ENUM.number = 217
COMMAND_CARRIERS_PROTOCMD_ENUM.name = "CARRIERS_PROTOCMD"
COMMAND_CARRIERS_PROTOCMD_ENUM.index = 80
COMMAND_CARRIERS_PROTOCMD_ENUM.number = 218
COMMAND_HOMES_PROTOCMD_ENUM.name = "HOMES_PROTOCMD"
COMMAND_HOMES_PROTOCMD_ENUM.index = 81
COMMAND_HOMES_PROTOCMD_ENUM.number = 219
COMMAND_MONITOR_PROTOCMD_ENUM.name = "MONITOR_PROTOCMD"
COMMAND_MONITOR_PROTOCMD_ENUM.index = 82
COMMAND_MONITOR_PROTOCMD_ENUM.number = 220
COMMAND_CHATS_PROTOCMD_ENUM.name = "CHATS_PROTOCMD"
COMMAND_CHATS_PROTOCMD_ENUM.index = 83
COMMAND_CHATS_PROTOCMD_ENUM.number = 221
COMMAND_BATTLEPASS_PROTOCMD_ENUM.name = "BATTLEPASS_PROTOCMD"
COMMAND_BATTLEPASS_PROTOCMD_ENUM.index = 84
COMMAND_BATTLEPASS_PROTOCMD_ENUM.number = 222
COMMAND_MINIGAME_PROTOCMD_ENUM.name = "MINIGAME_PROTOCMD"
COMMAND_MINIGAME_PROTOCMD_ENUM.index = 85
COMMAND_MINIGAME_PROTOCMD_ENUM.number = 223
COMMAND_REWARD_PROTOCMD_ENUM.name = "REWARD_PROTOCMD"
COMMAND_REWARD_PROTOCMD_ENUM.index = 86
COMMAND_REWARD_PROTOCMD_ENUM.number = 224
COMMAND_USERSHOW_PROTOCMD_ENUM.name = "USERSHOW_PROTOCMD"
COMMAND_USERSHOW_PROTOCMD_ENUM.index = 87
COMMAND_USERSHOW_PROTOCMD_ENUM.number = 225
COMMAND_ACTHITPOLLY_PROTOCMD_ENUM.name = "ACTHITPOLLY_PROTOCMD"
COMMAND_ACTHITPOLLY_PROTOCMD_ENUM.index = 88
COMMAND_ACTHITPOLLY_PROTOCMD_ENUM.number = 226
COMMAND_QUESTS_PROTOCMD_ENUM.name = "QUESTS_PROTOCMD"
COMMAND_QUESTS_PROTOCMD_ENUM.index = 89
COMMAND_QUESTS_PROTOCMD_ENUM.number = 227
COMMAND_MINIGAMES_PROTOCMD_ENUM.name = "MINIGAMES_PROTOCMD"
COMMAND_MINIGAMES_PROTOCMD_ENUM.index = 90
COMMAND_MINIGAMES_PROTOCMD_ENUM.number = 228
COMMAND_ACTMINIRO_PROTOCMD_ENUM.name = "ACTMINIRO_PROTOCMD"
COMMAND_ACTMINIRO_PROTOCMD_ENUM.index = 91
COMMAND_ACTMINIRO_PROTOCMD_ENUM.number = 229
COMMAND_RAIDS_PROTOCMD_ENUM.name = "RAIDS_PROTOCMD"
COMMAND_RAIDS_PROTOCMD_ENUM.index = 92
COMMAND_RAIDS_PROTOCMD_ENUM.number = 230
COMMAND_NOVICE_NOTEBOOK_ENUM.name = "NOVICE_NOTEBOOK"
COMMAND_NOVICE_NOTEBOOK_ENUM.index = 93
COMMAND_NOVICE_NOTEBOOK_ENUM.number = 231
COMMAND_DISNEY_ACTIVITY_PROTOCMD_ENUM.name = "DISNEY_ACTIVITY_PROTOCMD"
COMMAND_DISNEY_ACTIVITY_PROTOCMD_ENUM.index = 94
COMMAND_DISNEY_ACTIVITY_PROTOCMD_ENUM.number = 232
COMMAND_SCENE_USER_MANOR_PROTOCMD_ENUM.name = "SCENE_USER_MANOR_PROTOCMD"
COMMAND_SCENE_USER_MANOR_PROTOCMD_ENUM.index = 95
COMMAND_SCENE_USER_MANOR_PROTOCMD_ENUM.number = 233
COMMAND_FAMILY_PROTOCMD_ENUM.name = "FAMILY_PROTOCMD"
COMMAND_FAMILY_PROTOCMD_ENUM.index = 96
COMMAND_FAMILY_PROTOCMD_ENUM.number = 234
COMMAND_SERVANT_PROTOCMD_ENUM.name = "SERVANT_PROTOCMD"
COMMAND_SERVANT_PROTOCMD_ENUM.index = 97
COMMAND_SERVANT_PROTOCMD_ENUM.number = 235
COMMAND_MESSS_PROTOCMD_ENUM.name = "MESSS_PROTOCMD"
COMMAND_MESSS_PROTOCMD_ENUM.index = 98
COMMAND_MESSS_PROTOCMD_ENUM.number = 236
COMMAND_MAILS_PROTOCMD_ENUM.name = "MAILS_PROTOCMD"
COMMAND_MAILS_PROTOCMD_ENUM.index = 99
COMMAND_MAILS_PROTOCMD_ENUM.number = 237
COMMAND_BRANCHS_PROTOCMD_ENUM.name = "BRANCHS_PROTOCMD"
COMMAND_BRANCHS_PROTOCMD_ENUM.index = 100
COMMAND_BRANCHS_PROTOCMD_ENUM.number = 238
COMMAND_REG_CMD_ENUM.name = "REG_CMD"
COMMAND_REG_CMD_ENUM.index = 101
COMMAND_REG_CMD_ENUM.number = 253
COMMAND_GATEWAY_CMD_ENUM.name = "GATEWAY_CMD"
COMMAND_GATEWAY_CMD_ENUM.index = 102
COMMAND_GATEWAY_CMD_ENUM.number = 250
COMMAND_GLOBAL_ACTIVITY_CMD_ENUM.name = "GLOBAL_ACTIVITY_CMD"
COMMAND_GLOBAL_ACTIVITY_CMD_ENUM.index = 103
COMMAND_GLOBAL_ACTIVITY_CMD_ENUM.number = 251
COMMAND_SYSTEM_PROTOCMD_ENUM.name = "SYSTEM_PROTOCMD"
COMMAND_SYSTEM_PROTOCMD_ENUM.index = 104
COMMAND_SYSTEM_PROTOCMD_ENUM.number = 255
COMMAND.name = "Command"
COMMAND.full_name = ".Cmd.Command"
COMMAND.values = {
  COMMAND_LOGIN_USER_PROTOCMD_ENUM,
  COMMAND_ERROR_USER_PROTOCMD_ENUM,
  COMMAND_SCENE_USER_PROTOCMD_ENUM,
  COMMAND_SCENE_USER_ITEM_PROTOCMD_ENUM,
  COMMAND_SCENE_USER_SKILL_PROTOCMD_ENUM,
  COMMAND_SCENE_USER_QUEST_PROTOCMD_ENUM,
  COMMAND_SCENE_USER2_PROTOCMD_ENUM,
  COMMAND_SCENE_USER_PET_PROTOCMD_ENUM,
  COMMAND_FUBEN_PROTOCMD_ENUM,
  COMMAND_SCENE_USER_MAP_PROTOCMD_ENUM,
  COMMAND_SCENE_USER_MOUNT_PROTOCMD_ENUM,
  COMMAND_SCENE_BOSS_PROTOCMD_ENUM,
  COMMAND_SCENE_USER_CARRIER_PROTOCMD_ENUM,
  COMMAND_SCENE_USER_ACHIEVE_PROTOCMD_ENUM,
  COMMAND_SCENE_USER_TIP_PROTOCMD_ENUM,
  COMMAND_SCENE_USER_CHATROOM_PROTOCMD_ENUM,
  COMMAND_INFINITE_TOWER_PROTOCMD_ENUM,
  COMMAND_SCENE_USER_SEAL_PROTOCMD_ENUM,
  COMMAND_SCENE_USER_INTER_PROTOCMD_ENUM,
  COMMAND_SCENE_USER_MANUAL_PROTOCMD_ENUM,
  COMMAND_SCENE_USER_CHAT_PROTOCMD_ENUM,
  COMMAND_USER_EVENT_PROTOCMD_ENUM,
  COMMAND_SCENE_USER_TRADE_PROTOCMD_ENUM,
  COMMAND_SCENE_USER_AUGURY_PROTOCMD_ENUM,
  COMMAND_SCENE_USER_ASTROLABE_PROTOCMD_ENUM,
  COMMAND_SCENE_USER_FOOD_PROTOCMD_ENUM,
  COMMAND_SCENE_USER_PHOTO_PROTOCMD_ENUM,
  COMMAND_SCENE_USER_TUTOR_PROTOCMD_ENUM,
  COMMAND_SCENE_USER_BEING_PROTOCMD_ENUM,
  COMMAND_SESSION_USER_GUILD_PROTOCMD_ENUM,
  COMMAND_SESSION_USER_TEAM_PROTOCMD_ENUM,
  COMMAND_SESSION_USER_SHOP_PROTOCMD_ENUM,
  COMMAND_SESSION_USER_WEATHER_PROTOCMD_ENUM,
  COMMAND_SESSION_USER_MAIL_PROTOCMD_ENUM,
  COMMAND_SESSION_USER_SOCIALITY_PROTOCMD_ENUM,
  COMMAND_RECORD_USER_TRADE_PROTOCMD_ENUM,
  COMMAND_DOJO_PROTOCMD_ENUM,
  COMMAND_CHAT_PROTOCMD_ENUM,
  COMMAND_ACTIVITY_PROTOCMD_ENUM,
  COMMAND_MATCHC_PROTOCMD_ENUM,
  COMMAND_SESSION_USER_AUTHORIZE_PROTOCMD_ENUM,
  COMMAND_AUCTIONC_PROTOCMD_ENUM,
  COMMAND_ACTIVITY_EVENT_PROTOCMD_ENUM,
  COMMAND_WEDDINGC_PROTOCMD_ENUM,
  COMMAND_PVE_CARD_PROTOCMD_ENUM,
  COMMAND_TEAM_RAID_PROTOCMD_ENUM,
  COMMAND_PUZZLE_PROTOCMD_ENUM,
  COMMAND_TEAM_GROUP_RAID_PROTOCMD_ENUM,
  COMMAND_HOMEC_PROTOCMD_ENUM,
  COMMAND_ROGUELIKE_PROTOCMD_ENUM,
  COMMAND_ROGUELIKE_PROTOSCMD_ENUM,
  COMMAND_TECHTREE_PROTOCMD_ENUM,
  COMMAND_USER_AFK_PROTOCMD_ENUM,
  COMMAND_RAID_PROTOCMD_ENUM,
  COMMAND_NOVICE_BATTLE_PASS_PROTOCMD_ENUM,
  COMMAND_QUEUE_ENTER_PROTOCMD_ENUM,
  COMMAND_SESSION_OVERSEAS_TW_PROTOCMD_ENUM,
  COMMAND_SCENE_OVERSEAS_PROTOCMD_ENUM,
  COMMAND_SCENE_USER3_PROTOCMD_ENUM,
  COMMAND_MESSC_PROTOCMD_ENUM,
  COMMAND_CLIENT_CMD_ENUM,
  COMMAND_MAX_USER_CMD_ENUM,
  COMMAND_RECORD_DATA_PROTOCMD_ENUM,
  COMMAND_TRADE_PROTOCMD_ENUM,
  COMMAND_SESSION_PROTOCMD_ENUM,
  COMMAND_GMTOOLS_PROTOCMD_ENUM,
  COMMAND_LOG_PROTOCMD_ENUM,
  COMMAND_GATE_SUPER_PROTOCMD_ENUM,
  COMMAND_REGION_PROTOCMD_ENUM,
  COMMAND_STAT_PROTOCMD_ENUM,
  COMMAND_SOCIAL_PROTOCMD_ENUM,
  COMMAND_TEAM_PROTOCMD_ENUM,
  COMMAND_GUILD_PROTOCMD_ENUM,
  COMMAND_GZONE_PROTOCMD_ENUM,
  COMMAND_MATCHS_PROTOCMD_ENUM,
  COMMAND_AUCTIONS_PROTOCMD_ENUM,
  COMMAND_WEDDINGS_PROTOCMD_ENUM,
  COMMAND_GTEAM_PROTOCMD_ENUM,
  COMMAND_BOSSS_PROTOCMD_ENUM,
  COMMAND_INTERACT_PROTOCMD_ENUM,
  COMMAND_CARRIERS_PROTOCMD_ENUM,
  COMMAND_HOMES_PROTOCMD_ENUM,
  COMMAND_MONITOR_PROTOCMD_ENUM,
  COMMAND_CHATS_PROTOCMD_ENUM,
  COMMAND_BATTLEPASS_PROTOCMD_ENUM,
  COMMAND_MINIGAME_PROTOCMD_ENUM,
  COMMAND_REWARD_PROTOCMD_ENUM,
  COMMAND_USERSHOW_PROTOCMD_ENUM,
  COMMAND_ACTHITPOLLY_PROTOCMD_ENUM,
  COMMAND_QUESTS_PROTOCMD_ENUM,
  COMMAND_MINIGAMES_PROTOCMD_ENUM,
  COMMAND_ACTMINIRO_PROTOCMD_ENUM,
  COMMAND_RAIDS_PROTOCMD_ENUM,
  COMMAND_NOVICE_NOTEBOOK_ENUM,
  COMMAND_DISNEY_ACTIVITY_PROTOCMD_ENUM,
  COMMAND_SCENE_USER_MANOR_PROTOCMD_ENUM,
  COMMAND_FAMILY_PROTOCMD_ENUM,
  COMMAND_SERVANT_PROTOCMD_ENUM,
  COMMAND_MESSS_PROTOCMD_ENUM,
  COMMAND_MAILS_PROTOCMD_ENUM,
  COMMAND_BRANCHS_PROTOCMD_ENUM,
  COMMAND_REG_CMD_ENUM,
  COMMAND_GATEWAY_CMD_ENUM,
  COMMAND_GLOBAL_ACTIVITY_CMD_ENUM,
  COMMAND_SYSTEM_PROTOCMD_ENUM
}
NONCE_TIMESTAMP_FIELD.name = "timestamp"
NONCE_TIMESTAMP_FIELD.full_name = ".Cmd.Nonce.timestamp"
NONCE_TIMESTAMP_FIELD.number = 1
NONCE_TIMESTAMP_FIELD.index = 0
NONCE_TIMESTAMP_FIELD.label = 1
NONCE_TIMESTAMP_FIELD.has_default_value = false
NONCE_TIMESTAMP_FIELD.default_value = 0
NONCE_TIMESTAMP_FIELD.type = 13
NONCE_TIMESTAMP_FIELD.cpp_type = 3
NONCE_INDEX_FIELD.name = "index"
NONCE_INDEX_FIELD.full_name = ".Cmd.Nonce.index"
NONCE_INDEX_FIELD.number = 2
NONCE_INDEX_FIELD.index = 1
NONCE_INDEX_FIELD.label = 1
NONCE_INDEX_FIELD.has_default_value = false
NONCE_INDEX_FIELD.default_value = 0
NONCE_INDEX_FIELD.type = 13
NONCE_INDEX_FIELD.cpp_type = 3
NONCE_SIGN_FIELD.name = "sign"
NONCE_SIGN_FIELD.full_name = ".Cmd.Nonce.sign"
NONCE_SIGN_FIELD.number = 3
NONCE_SIGN_FIELD.index = 2
NONCE_SIGN_FIELD.label = 1
NONCE_SIGN_FIELD.has_default_value = false
NONCE_SIGN_FIELD.default_value = ""
NONCE_SIGN_FIELD.type = 9
NONCE_SIGN_FIELD.cpp_type = 9
NONCE.name = "Nonce"
NONCE.full_name = ".Cmd.Nonce"
NONCE.nested_types = {}
NONCE.enum_types = {}
NONCE.fields = {
  NONCE_TIMESTAMP_FIELD,
  NONCE_INDEX_FIELD,
  NONCE_SIGN_FIELD
}
NONCE.is_extendable = false
NONCE.extensions = {}
ACTHITPOLLY_PROTOCMD = 226
ACTIVITY_EVENT_PROTOCMD = 64
ACTIVITY_PROTOCMD = 60
ACTMINIRO_PROTOCMD = 229
AUCTIONC_PROTOCMD = 63
AUCTIONS_PROTOCMD = 213
BATTLEPASS_PROTOCMD = 222
BOSSS_PROTOCMD = 216
BRANCHS_PROTOCMD = 238
CARRIERS_PROTOCMD = 218
CHATS_PROTOCMD = 221
CHAT_PROTOCMD = 59
CLIENT_CMD = 99
DISNEY_ACTIVITY_PROTOCMD = 232
DOJO_PROTOCMD = 58
ERROR_USER_PROTOCMD = 2
FAMILY_PROTOCMD = 234
FUBEN_PROTOCMD = 11
GATEWAY_CMD = 250
GATE_SUPER_PROTOCMD = 205
GLOBAL_ACTIVITY_CMD = 251
GMTOOLS_PROTOCMD = 203
GTEAM_PROTOCMD = 215
GUILD_PROTOCMD = 210
GZONE_PROTOCMD = 211
HOMEC_PROTOCMD = 70
HOMES_PROTOCMD = 219
INFINITE_TOWER_PROTOCMD = 20
INTERACT_PROTOCMD = 217
LOGIN_USER_PROTOCMD = 1
LOG_PROTOCMD = 204
MAILS_PROTOCMD = 237
MATCHC_PROTOCMD = 61
MATCHS_PROTOCMD = 212
MAX_USER_CMD = 100
MESSC_PROTOCMD = 83
MESSS_PROTOCMD = 236
MINIGAMES_PROTOCMD = 228
MINIGAME_PROTOCMD = 223
MONITOR_PROTOCMD = 220
NOVICE_BATTLE_PASS_PROTOCMD = 77
NOVICE_NOTEBOOK = 231
Nonce = protobuf.Message(NONCE)
PUZZLE_PROTOCMD = 68
PVE_CARD_PROTOCMD = 66
QUESTS_PROTOCMD = 227
QUEUE_ENTER_PROTOCMD = 78
RAIDS_PROTOCMD = 230
RAID_PROTOCMD = 76
RECORD_DATA_PROTOCMD = 200
RECORD_USER_TRADE_PROTOCMD = 57
REGION_PROTOCMD = 206
REG_CMD = 253
REWARD_PROTOCMD = 224
ROGUELIKE_PROTOCMD = 71
ROGUELIKE_PROTOSCMD = 72
SCENE_BOSS_PROTOCMD = 15
SCENE_OVERSEAS_PROTOCMD = 81
SCENE_USER2_PROTOCMD = 9
SCENE_USER3_PROTOCMD = 82
SCENE_USER_ACHIEVE_PROTOCMD = 17
SCENE_USER_ASTROLABE_PROTOCMD = 28
SCENE_USER_AUGURY_PROTOCMD = 27
SCENE_USER_BEING_PROTOCMD = 32
SCENE_USER_CARRIER_PROTOCMD = 16
SCENE_USER_CHATROOM_PROTOCMD = 19
SCENE_USER_CHAT_PROTOCMD = 24
SCENE_USER_FOOD_PROTOCMD = 29
SCENE_USER_INTER_PROTOCMD = 22
SCENE_USER_ITEM_PROTOCMD = 6
SCENE_USER_MANOR_PROTOCMD = 233
SCENE_USER_MANUAL_PROTOCMD = 23
SCENE_USER_MAP_PROTOCMD = 12
SCENE_USER_MOUNT_PROTOCMD = 13
SCENE_USER_PET_PROTOCMD = 10
SCENE_USER_PHOTO_PROTOCMD = 30
SCENE_USER_PROTOCMD = 5
SCENE_USER_QUEST_PROTOCMD = 8
SCENE_USER_SEAL_PROTOCMD = 21
SCENE_USER_SKILL_PROTOCMD = 7
SCENE_USER_TIP_PROTOCMD = 18
SCENE_USER_TRADE_PROTOCMD = 26
SCENE_USER_TUTOR_PROTOCMD = 31
SERVANT_PROTOCMD = 235
SESSION_OVERSEAS_TW_PROTOCMD = 80
SESSION_PROTOCMD = 202
SESSION_USER_AUTHORIZE_PROTOCMD = 62
SESSION_USER_GUILD_PROTOCMD = 50
SESSION_USER_MAIL_PROTOCMD = 55
SESSION_USER_SHOP_PROTOCMD = 52
SESSION_USER_SOCIALITY_PROTOCMD = 56
SESSION_USER_TEAM_PROTOCMD = 51
SESSION_USER_WEATHER_PROTOCMD = 53
SOCIAL_PROTOCMD = 208
STAT_PROTOCMD = 207
SYSTEM_PROTOCMD = 255
TEAM_GROUP_RAID_PROTOCMD = 69
TEAM_PROTOCMD = 209
TEAM_RAID_PROTOCMD = 67
TECHTREE_PROTOCMD = 73
TRADE_PROTOCMD = 201
USERSHOW_PROTOCMD = 225
USER_AFK_PROTOCMD = 74
USER_EVENT_PROTOCMD = 25
WEDDINGC_PROTOCMD = 65
WEDDINGS_PROTOCMD = 214
