Table_NoviceTarget_t = {
  GM = {
    {
      {
        egg_friendlv = 10,
        id = 900139,
        num = 1,
        type = "additem"
      }
    }
  },
  Goto = {
    {8016},
    {1005},
    {65},
    {8},
    {8036},
    {8064},
    {8057},
    {2056},
    {8068},
    {83, 8069},
    {8070},
    {8077},
    {8073},
    {5049},
    {8065},
    {2065},
    {2001},
    {8074},
    {4130},
    {8066},
    {2004},
    {730},
    {8021},
    {3080, 8071},
    {2083},
    {2081},
    {2084},
    {5031},
    {8067},
    {8072},
    {3091},
    {3015},
    {27},
    {34},
    {11},
    {2080},
    {2085},
    {8012},
    {20},
    {8115},
    {8010},
    {80},
    {34, 48},
    {1008},
    {62},
    {8022},
    {1010},
    {2086},
    {48, 34},
    {4129},
    {2087},
    {8011},
    {8035},
    {2068},
    {5039},
    {8076},
    {8025},
    {8075},
    {7012},
    {2091},
    {8179}
  },
  Param = {
    {
      quest_id = {22010012}
    },
    {quest_group = 30009},
    {
      quest_id = {206830001}
    },
    {
      map = {125},
      monster = {10268}
    },
    {
      quest_id = {
        20960001,
        21060012,
        21000001,
        20950001,
        21010006,
        21090005,
        21110001,
        21070001,
        22000001,
        20990001,
        21120007,
        20940002,
        21080001,
        20970002,
        20980001,
        22240007,
        22040001,
        22280001,
        22330001,
        22410001,
        22480099
      }
    },
    {
      quest_id = {700030001, 700070001}
    },
    {
      quest_id = {1001060001}
    },
    {
      quest_id = {206850001}
    },
    {
      quest_id = {1001060011}
    },
    {type = 56},
    {
      map = {125},
      monster = {10269}
    },
    {
      quest_id = {1001060002}
    },
    {type = 58},
    {
      map = {125},
      monster = {10271}
    },
    {achieve_id = 1601042},
    {
      quest_id = {300680001}
    },
    {achieve_id = 1601071},
    {
      index = 2,
      raid_type = {34}
    },
    {adventure_type = 1},
    {use_item = 5832},
    {adventure_type = 2},
    {achieve_id = 1602021},
    {
      map = {125},
      monster = {10270}
    },
    {
      quest_id = {399160001}
    },
    {adventure_type = 22},
    {
      equip_pos = {
        1,
        2,
        3,
        4,
        5,
        6,
        8,
        9,
        10,
        11,
        12
      }
    },
    {
      map = {102, 125}
    },
    {
      quest_id = {390010001}
    },
    {
      quest_id = {399190001}
    },
    {achieve_id = 1601021},
    {achieve_id = 1204048},
    {adventure_type = 11},
    {
      quest_id = {206910005}
    },
    {prestige_id = 6},
    {achieve_id = 1204033},
    {
      raid_id = {64608}
    },
    {
      quest_id = {690020006}
    },
    {achieve_id = 1601051},
    {
      quest_id = {390020001}
    },
    {
      quest_id = {300670001}
    },
    {
      quest_id = {600930002}
    },
    {adventure_type = 18},
    {achieve_id = 1205031},
    {adventure_type = 6},
    {
      quest_id = {398020001}
    },
    {prestige_id = 7},
    {pet_level = 100, pet_likablity = 5},
    {
      quest_id = {390030007}
    },
    {menu_id = 9005},
    {
      quest_id = {398990001}
    },
    {
      quest_id = {1001090002}
    },
    {
      raid_type = {
        35,
        36,
        38,
        40
      }
    },
    {
      lv = 45,
      pos = {7}
    },
    {
      lv = 4,
      pos = {7}
    },
    {
      quest_id = {210820003}
    },
    {
      lv = 30,
      pos = {5, 6}
    },
    {type = 70},
    {
      lv = 4,
      pos = {1}
    },
    {
      quest_id = {210830003}
    },
    {type = 1},
    {
      quest_id = {210840003}
    },
    {pet_level = 120},
    {difficulty = 1},
    {
      lv = 90,
      pos = {7}
    },
    {lv = 4},
    {pet_likablity = 10},
    {
      raid_type = {35}
    },
    {raidid = 7082},
    {
      quest_id = {210860002}
    },
    {
      lv = 90,
      pos = {5, 6}
    },
    {manual_type = 1},
    {
      lv = 130,
      pos = {7}
    },
    {
      pos = {
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12
      }
    },
    {manual_type = 2},
    {raidid = 7085},
    {
      raid_type = {36}
    },
    {min_quality = 2},
    {lv = 6},
    {difficulty = 2},
    {groupid = 14},
    {lv = 130},
    {
      quest_id = {210890009}
    },
    {lv = 5},
    {
      raid_type = {38}
    },
    {groupid = 15},
    {lv = 8},
    {min_quality = 3},
    {groupid = 16},
    {difficulty = 4},
    {raidid = 7060}
  },
  Reward = {
    {9230021, 4638},
    {9220012},
    {9220013},
    {9220014},
    {4637},
    {9220015},
    {9220016},
    {9220017},
    {9220018},
    {9220021},
    {9220022},
    {9220023},
    {9220220},
    {9220024},
    {9220025},
    {9220026},
    {9220027},
    {9220028},
    {9220029},
    {9220031},
    {9220032},
    {9220033},
    {9220034},
    {9220035},
    {9220036},
    {9220037},
    {9220038},
    {9230021},
    {9220042},
    {9220043},
    {9220044},
    {9220045},
    {9220046},
    {9220047},
    {9220048},
    {9220052},
    {9220053},
    {9220054},
    {9220055},
    {9220056},
    {9220057},
    {9220058},
    {9220062},
    {9220063},
    {9220064},
    {9220065},
    {9220066},
    {9220067},
    {9230022},
    {9220072},
    {9220073},
    {9220074},
    {9220075},
    {9220076},
    {9220077},
    {9220082},
    {9220083},
    {9220084},
    {9220085},
    {9220092},
    {9220093},
    {9220094},
    {9220095},
    {9220096},
    {9220102},
    {9220103},
    {9220104},
    {9220105},
    {9220112},
    {9220113},
    {9220114},
    {9220115},
    {9220116},
    {9220122},
    {9220123},
    {9220124},
    {9220125},
    {9220132},
    {9220133},
    {9220134},
    {9220135},
    {9220136},
    {9220142},
    {9220143},
    {9220144},
    {9220145},
    {9220152},
    {9220153},
    {9220154},
    {9220155},
    {9220162},
    {9220163},
    {9220164},
    {9220165},
    {9220166},
    {9220172},
    {9220173},
    {9220174},
    {9220182},
    {9220183},
    {9220184},
    {9220185},
    {9220192},
    {9220193},
    {9220194},
    {9220195},
    {9220202},
    {9220203},
    {9220204},
    {9220205},
    {9220212},
    {9220213},
    {9220214},
    {9220215},
    {9230200},
    {9230201},
    {9230202},
    {9230203},
    {9230204},
    {9230205},
    {9230206},
    {9230207},
    {9230208},
    {9230209},
    {9230210},
    {9230211},
    {9230212},
    {9230213},
    {9230214},
    {9230215},
    {9230216},
    {9230217},
    {9230218},
    {9230219},
    {9230220},
    {9230221},
    {9230222},
    {9230223},
    {9230224},
    {9230225},
    {9230226},
    {9230227},
    {9230228},
    {9230229},
    {9230230},
    {9230231},
    {9230232},
    {9230233},
    {9230234},
    {9230235},
    {9230236},
    {9230237},
    {9230238},
    {9230239},
    {9230240},
    {9230241},
    {9230242},
    {9230243},
    {9230244},
    {9230245},
    {9230246},
    {9230247},
    {9230248},
    {9230249},
    {9230250},
    {9230251},
    {9230252},
    {9230253},
    {9230254},
    {9230255},
    {9230256},
    {9230257},
    {9230258},
    {9230259},
    {9230260},
    {9230261},
    {9230262},
    {9230263},
    {9230264},
    {9230265},
    {9230266},
    {9230267},
    {9230268},
    {9230269},
    {9230270},
    {9230271},
    {9230272},
    {9230273},
    {9230274},
    {9230275},
    {9230276},
    {9230277},
    {9230278},
    {9230279},
    {9230280},
    {9230281},
    {9230282},
    {9230283},
    {9230284},
    {9230285},
    {9230286},
    {9230287},
    {9230288},
    {9230289},
    {9230290},
    {9230291},
    {9230292},
    {9230293},
    {9230294},
    {9230295},
    {9230296},
    {9230297},
    {9230298},
    {9230299},
    {9230300},
    {9230301},
    {9230302},
    {9230303},
    {9230304},
    {9230305},
    {9230306},
    {9230307}
  }
}
Table_NoviceTarget = {
  [1] = {
    Day = 1,
    TargetType = 1,
    Reward = Table_NoviceTarget_t.Reward[1],
    Icon = "Sign_in_80",
    IconScale = 0.9,
    Title = "欢迎来到米德加尔特",
    Practical = 5,
    Difficult = 1,
    Frequency = 5
  },
  [2] = {
    id = 2,
    Day = 1,
    Sort = 2,
    Param = Table_NoviceTarget_t.Param[1],
    Reward = Table_NoviceTarget_t.Reward[2],
    Icon = "reincarnation",
    IconScale = 0.9,
    Title = "英雄的赞歌",
    SubTitle = "完成转生任务",
    Description = "转生任务为起源转职的必要前置任务。转生过程中，冒险者将快速回顾过往版本中的核心剧情和战斗。完成转生任务后，可获得专属头像框。",
    Frequency = 1,
    Goto = Table_NoviceTarget_t.Goto[1]
  },
  [3] = {
    id = 3,
    Day = 1,
    Sort = 3,
    TargetType = 67,
    Desc = "num",
    Reward = Table_NoviceTarget_t.Reward[3],
    Icon = "Housekeeper",
    IconScale = 0.85,
    Title = "全能执事",
    SubTitle = "成功雇佣任意一名执事",
    Description = "雇佣执事的冒险者可以从主界面上方打开「执事」界面，查看日常和周常任务的发布、各个等级的卡普拉冒险录奖励、周常副本进度统计、活动日历、各职业装备推荐、交易所中涨跌幅显著的物品等。",
    Practical = 5,
    Difficult = 1,
    Frequency = 5,
    Goto = Table_NoviceTarget_t.Goto[2]
  },
  [4] = {
    id = 4,
    Day = 1,
    Sort = 4,
    TargetType = 52,
    Desc = "mercenarycat_count",
    Reward = Table_NoviceTarget_t.Reward[4],
    Icon = "MercenaryCat",
    Title = "佣兵传说",
    SubTitle = "成功雇佣一只佣兵猫",
    Description = "佣兵猫是可以陪伴你一起冒险的重要伙伴，支付zeny即可雇佣和续约。佣兵猫能够为雇主提供抵挡攻击、贡献输出、提供治疗在内的多种服务，根据自己的需求选择合适的佣兵伙伴吧！",
    Difficult = 2,
    Frequency = 4,
    Goto = Table_NoviceTarget_t.Goto[3]
  },
  [5] = {
    id = 5,
    Day = 1,
    Sort = 5,
    TargetType = 68,
    Param = Table_NoviceTarget_t.Param[2],
    TargetNum = 1,
    Reward = Table_NoviceTarget_t.Reward[5],
    Icon = "Cookroom_1",
    Title = "暖暖身子",
    SubTitle = "去料理商人处试吃暖身料理一次",
    Description = "使用暖身料理或者功效更强大的暖心料理能极大地提升冒险者的野外生存能力，作为一个有经验的冒险者，决不允许自己的背包内缺少这些物品。\n除了在料理商店购买外，每天还可以在料理商人处免费领取一份暖身料理，听说购买限定特典的冒险者还有独特优惠！",
    Difficult = 1,
    Goto = Table_NoviceTarget_t.Goto[4]
  },
  [6] = {
    id = 6,
    Day = 1,
    Sort = 6,
    Param = Table_NoviceTarget_t.Param[3],
    Reward = Table_NoviceTarget_t.Reward[6],
    Icon = "Map",
    IconScale = 0.9,
    Title = "命运之风",
    SubTitle = "抵达龙之城洛阳",
    Description = "完成任务「命运之风」后抵达远方的龙之城洛阳，解锁冒险新篇章。",
    Practical = 3,
    Difficult = 2,
    Frequency = 2,
    Goto = Table_NoviceTarget_t.Goto[5]
  },
  [8] = {
    id = 8,
    Day = 1,
    Sort = 8,
    TargetType = 5,
    Desc = "kill_count",
    Param = Table_NoviceTarget_t.Param[4],
    TargetNum = 30,
    Reward = Table_NoviceTarget_t.Reward[7],
    IconScale = 0.9,
    Title = "风息之野",
    SubTitle = "击杀风息之野的枫之森灵%s/30只",
    Description = "在野外挂机与自己等级强度相匹配的魔物，是冒险者快速升级获得经验、材料的方式之一，准备充分后使用自动战斗来一场酣畅淋漓的战斗吧！",
    Practical = 3,
    Goto = Table_NoviceTarget_t.Goto[6]
  },
  [9] = {
    id = 9,
    Day = 1,
    Sort = 9,
    TargetType = 8,
    Desc = "tower_layer",
    TargetNum = 3,
    Reward = Table_NoviceTarget_t.Reward[8],
    Icon = "Dungeon",
    SubTitle = "完成3层勇者试炼塔",
    Description = "勇者试炼塔是冒险者个人专属的试炼之地，与守门人对话后，你将被传送进由魔法创造的虚拟空间与魔物战斗。完成3层后即可获得奖励。",
    Practical = 3,
    Goto = Table_NoviceTarget_t.Goto[7]
  },
  [10] = {
    id = 10,
    Day = 1,
    Sort = 10,
    TargetType = 7,
    Reward = Table_NoviceTarget_t.Reward[9],
    Icon = "Guild",
    Title = "冒险大家庭",
    SubTitle = "成功加入一个公会",
    Description = "点击右上角「更多」按钮，在公会界面选择一个公会递交申请，并且成功加入。在公会中你可以认识更多伙伴，解锁更多功能和游戏资源。",
    Difficult = 1,
    Goto = Table_NoviceTarget_t.Goto[8]
  },
  [11] = {
    id = 11,
    Day = 2,
    TargetType = 1,
    Reward = Table_NoviceTarget_t.Reward[10],
    Icon = "Sign_in_80",
    IconScale = 0.9,
    Title = "欢迎来到米德加尔特",
    Practical = 5,
    Difficult = 1,
    Frequency = 5
  },
  [12] = {
    id = 12,
    Day = 2,
    Sort = 2,
    Param = Table_NoviceTarget_t.Param[5],
    PreID = 2,
    Reward = Table_NoviceTarget_t.Reward[11],
    Icon = "changeprofession",
    IconScale = 0.9,
    Title = "起源转职",
    SubTitle = "角色完成起源转职任务",
    Description = "完成前置任务「黑夜将至」后，前往「普隆德拉」与诺恩·薇对话开始转职任务。\n完成角色起源转职后，你将解锁更强大的职业技能，并获得职业专属外观。",
    Frequency = 1,
    Goto = Table_NoviceTarget_t.Goto[9]
  },
  [13] = {
    id = 13,
    Day = 2,
    Sort = 3,
    Param = Table_NoviceTarget_t.Param[6],
    Reward = Table_NoviceTarget_t.Reward[12],
    GM = Table_NoviceTarget_t.GM[1],
    Icon = "child",
    Title = "最初的陪伴",
    SubTitle = "完成宠物捕捉任务",
    Description = "前往「普隆德拉南门」与宠物协会会长-阿格尼斯对话开始宠物捕获任务。\n使用「七彩贝壳」购买相应捕捉道具，对魔物使用即可将其捕捉为宠物。\nTips：多兰族冒险者需要前往「罗扎纳」与宠物协会-尼克斯·布蕾对话开始任务喵(=ﾟωﾟ)ﾉ",
    Practical = 3,
    Difficult = 2,
    Goto = Table_NoviceTarget_t.Goto[10]
  },
  [14] = {
    id = 14,
    Day = 2,
    Sort = 4,
    Param = Table_NoviceTarget_t.Param[7],
    PreID = 6,
    Reward = Table_NoviceTarget_t.Reward[13],
    IconScale = 0.9,
    Title = "城外异动",
    SubTitle = "完成荒境主线任务：城外异动",
    Description = "前往洛阳城外「花街」地图，接取荒境主线任务「城外异动」并完成。",
    Practical = 3,
    Difficult = 2,
    Frequency = 2,
    Goto = Table_NoviceTarget_t.Goto[11]
  },
  [15] = {
    id = 15,
    Day = 2,
    Sort = 5,
    Param = Table_NoviceTarget_t.Param[8],
    Reward = Table_NoviceTarget_t.Reward[14],
    IconScale = 0.9,
    Title = "端坐云霄",
    SubTitle = "完成洛阳主线任务：端坐云霄上",
    Description = "完成洛阳主线任务：端坐云霄上。",
    Practical = 3,
    Frequency = 1,
    Goto = Table_NoviceTarget_t.Goto[12]
  },
  [16] = {
    id = 16,
    Day = 3,
    Sort = 3,
    Param = Table_NoviceTarget_t.Param[9],
    PreID = 23,
    Reward = Table_NoviceTarget_t.Reward[15],
    IconScale = 0.9,
    Title = "铭刻时光的古战场",
    SubTitle = "解锁2个荒境地图的传送器",
    Description = "依次完成荒境主线任务「前奏准备」「唤灵祭典」「隐匿之音」后解锁2个荒境传送器。",
    Practical = 3,
    Difficult = 2,
    Frequency = 2,
    Goto = Table_NoviceTarget_t.Goto[13]
  },
  [17] = {
    id = 17,
    Day = 2,
    Sort = 7,
    TargetType = 18,
    Param = Table_NoviceTarget_t.Param[10],
    TargetNum = 4,
    Reward = Table_NoviceTarget_t.Reward[16],
    Icon = "icon_1",
    Title = "荒境冒险",
    SubTitle = "完成荒境冒险任务%s/4个",
    Description = "尝试完成4个荒境冒险任务，可获得每日最终奖励，这是起源转职技能加点材料“时光流沙”的主要产出之一。",
    Practical = 3,
    Goto = Table_NoviceTarget_t.Goto[14]
  },
  [18] = {
    id = 18,
    Day = 2,
    Sort = 8,
    TargetType = 5,
    Desc = "kill_count",
    Param = Table_NoviceTarget_t.Param[11],
    TargetNum = 50,
    Reward = Table_NoviceTarget_t.Reward[17],
    IconScale = 0.9,
    Title = "风息猎手",
    SubTitle = "击杀风息之野荒野克瑞米%s/50只",
    Description = "在野外挂机与自己等级强度相匹配的魔物，是冒险者快速升级获得经验、材料的方式之一，准备充分后使用自动战斗来一场酣畅淋漓的战斗吧！",
    Practical = 3,
    Goto = Table_NoviceTarget_t.Goto[15]
  },
  [19] = {
    id = 19,
    Day = 2,
    Sort = 9,
    TargetType = 8,
    Desc = "tower_layer",
    TargetNum = 6,
    Reward = Table_NoviceTarget_t.Reward[18],
    Icon = "Dungeon",
    SubTitle = "完成6层勇者试炼塔",
    Description = "勇者试炼塔是冒险者个人专属的试炼之地，与守门人对话后，你将被传送进由魔法创造的虚拟空间与魔物战斗。完成6层后即可获得奖励。",
    Practical = 3,
    Goto = Table_NoviceTarget_t.Goto[7]
  },
  [20] = {
    id = 20,
    Day = 2,
    Sort = 10,
    TargetType = 14,
    Desc = "friend_count",
    Reward = Table_NoviceTarget_t.Reward[19],
    Icon = "Book",
    Title = "冒险伙伴",
    SubTitle = "成功添加一次好友",
    Description = "通过点击右上角「更多」按钮，选中好友界面，可输入玩家id或名字添加好友；或接受已经收到的好友申请。",
    Difficult = 1,
    Goto = Table_NoviceTarget_t.Goto[16]
  },
  [21] = {
    id = 21,
    Day = 3,
    TargetType = 1,
    Reward = Table_NoviceTarget_t.Reward[20],
    Icon = "Sign_in_80",
    IconScale = 0.9,
    Title = "欢迎来到米德加尔特",
    Practical = 5,
    Difficult = 1,
    Frequency = 5
  },
  [22] = {
    id = 22,
    Day = 3,
    Sort = 2,
    TargetType = 15,
    Desc = "skill_count",
    PreID = 12,
    Reward = Table_NoviceTarget_t.Reward[21],
    Icon = "Skill",
    Title = "起源之力",
    SubTitle = "升级一级四转的技能树",
    Description = "打开「更多」中的「技能」界面，选择上方「起源技能」页签，即可使用「时之流沙」强化四转职业技能。",
    Difficult = 2,
    Goto = Table_NoviceTarget_t.Goto[17]
  },
  [23] = {
    id = 23,
    Day = 2,
    Sort = 6,
    Param = Table_NoviceTarget_t.Param[12],
    PreID = 14,
    Reward = Table_NoviceTarget_t.Reward[22],
    Icon = "huangjingshenshu1",
    IconScale = 0.9,
    Title = "神树之灵",
    SubTitle = "荒境神树解锁",
    Description = "完成荒境主线任务「意外横生」后，即可解锁荒境「神树之灵」。",
    Goto = Table_NoviceTarget_t.Goto[18]
  },
  [24] = {
    id = 24,
    Day = 3,
    Sort = 4,
    TargetType = 16,
    Desc = "techtree_count",
    TargetNum = 1,
    PreID = 23,
    Reward = Table_NoviceTarget_t.Reward[23],
    Icon = "huangjingshenshu2",
    IconScale = 0.9,
    Title = "神树的庇护",
    SubTitle = "激活1点神树之灵",
    Description = "在荒境「神树之灵」界面上，尝试激活任意1个节点。\n所需材料可通过击杀荒境魔物获得。",
    Goto = Table_NoviceTarget_t.Goto[19]
  },
  [25] = {
    id = 25,
    Day = 3,
    Sort = 5,
    TargetType = 18,
    Param = Table_NoviceTarget_t.Param[10],
    TargetNum = 8,
    Reward = Table_NoviceTarget_t.Reward[24],
    Icon = "icon_1",
    IconScale = 1.1,
    Title = "荒境冒险",
    SubTitle = "完成荒境冒险任务%s/8个",
    Description = "尝试完成4个荒境冒险任务，可获得每日最终奖励，这是起源转职技能加点材料“时光流沙”的主要产出之一。",
    Practical = 3,
    Goto = Table_NoviceTarget_t.Goto[14]
  },
  [26] = {
    id = 26,
    Day = 3,
    Sort = 6,
    TargetType = 18,
    Param = Table_NoviceTarget_t.Param[13],
    Reward = Table_NoviceTarget_t.Reward[25],
    Icon = "Mall_gift",
    IconScale = 0.85,
    Title = "荒境的宝藏",
    SubTitle = "拾取一次随机宝箱",
    Description = "荒境地图中隐藏着随机宝箱，发现它们可以获得大量奖励。",
    Practical = 2,
    Difficult = 2,
    Frequency = 2,
    Goto = Table_NoviceTarget_t.Goto[14]
  },
  [27] = {
    id = 27,
    Day = 3,
    Sort = 7,
    TargetType = 5,
    Desc = "kill_count",
    Param = Table_NoviceTarget_t.Param[14],
    TargetNum = 50,
    Reward = Table_NoviceTarget_t.Reward[26],
    IconScale = 0.9,
    Title = "风息猎手",
    SubTitle = "击杀风息之野荒野之鼠%s/50只",
    Description = "在野外挂机与自己等级强度相匹配的魔物，是冒险者快速升级获得经验、材料的方式之一，准备充分后使用自动战斗来一场酣畅淋漓的战斗吧！",
    Practical = 3,
    Goto = Table_NoviceTarget_t.Goto[20]
  },
  [28] = {
    id = 28,
    Day = 3,
    Sort = 8,
    TargetType = 8,
    Desc = "tower_layer",
    TargetNum = 9,
    Reward = Table_NoviceTarget_t.Reward[27],
    Icon = "Dungeon",
    SubTitle = "完成9层勇者试炼塔",
    Description = "勇者试炼塔是冒险者个人专属的试炼之地，与守门人对话后，你将被传送进由魔法创造的虚拟空间与魔物战斗。完成9层后即可获得奖励。",
    Practical = 3,
    Goto = Table_NoviceTarget_t.Goto[7]
  },
  [29] = {
    id = 29,
    TargetType = 1,
    Reward = Table_NoviceTarget_t.Reward[28],
    Icon = "Sign_in_80",
    IconScale = 0.9,
    Title = "欢迎来到米德加尔特",
    Practical = 5,
    Difficult = 1,
    Frequency = 5
  },
  [30] = {
    id = 30,
    Sort = 2,
    TargetType = 6,
    Desc = "strengthen_count",
    Param = Table_NoviceTarget_t.Param[15],
    TargetNum = 0,
    Reward = Table_NoviceTarget_t.Reward[29],
    Icon = "strengthen1",
    Title = "强化就是力量",
    SubTitle = "强化你的任意装备栏50次",
    Description = "通过背包强化页面或者寻找铁匠忽克连对某个装备栏进行强化，强化装备栏可提升角色基础攻击和防御，强化等级上限跟随角色等级提升而提高。",
    Practical = 5,
    Difficult = 2,
    Frequency = 4,
    Goto = Table_NoviceTarget_t.Goto[21]
  },
  [31] = {
    id = 31,
    Sort = 3,
    Param = Table_NoviceTarget_t.Param[16],
    Reward = Table_NoviceTarget_t.Reward[30],
    Icon = "refine_2",
    IconScale = 1.15,
    Title = "装备的奥秘",
    SubTitle = "与薇莉·多拉贡了解一下装备升级",
    Description = "消耗zeny和材料可以对装备进行升级，获得主属性提升，装备升级是冒险家提升个人能力的不二之选。",
    Practical = 3,
    Difficult = 2,
    Frequency = 2,
    Goto = Table_NoviceTarget_t.Goto[22]
  },
  [32] = {
    id = 32,
    Sort = 4,
    TargetType = 6,
    Param = Table_NoviceTarget_t.Param[17],
    PreID = 31,
    Reward = Table_NoviceTarget_t.Reward[30],
    Icon = "refine_2",
    IconScale = 1.15,
    Title = "装备的奥秘",
    SubTitle = "完成一次装备的升级",
    Description = "在「包包」中选择任意一件「英灵信标」系列装备，在道具详情界面中点击图标右侧的「升级」按钮，尝试消耗Zeny和材料将它升级。",
    Practical = 3,
    Difficult = 2,
    Frequency = 2,
    Goto = Table_NoviceTarget_t.Goto[23]
  },
  [33] = {
    id = 33,
    Sort = 5,
    TargetType = 26,
    Desc = "count",
    Param = Table_NoviceTarget_t.Param[18],
    Reward = Table_NoviceTarget_t.Reward[31],
    Icon = "mowuyanjiusuo",
    IconScale = 0.9,
    Title = "生态调查",
    SubTitle = "完成一次魔物研究所的材料模式",
    Description = "与主城的魔物学者对话，接取生态调查任务进入副本，完成后可获得大量经验和材料。",
    Practical = 3,
    Goto = Table_NoviceTarget_t.Goto[24]
  },
  [34] = {
    id = 34,
    Sort = 6,
    TargetType = 23,
    Desc = "battlepass_level",
    TargetNum = 3,
    PreID = 3,
    Reward = Table_NoviceTarget_t.Reward[32],
    Icon = "MaleAssistant",
    IconScale = 0.85,
    Title = "卡普拉冒险录",
    SubTitle = "卡普拉冒险录等级提升至%s/3级",
    Description = "完成执事日常和周常任务，是获得卡普拉冒险录经验的唯二途径。\n冒险者通过提升卡普拉冒险录等级可以获得丰厚的奖励，还可以前往卡普拉冒险录商店兑换心仪的物品哦~",
    Practical = 2,
    Frequency = 2,
    Goto = Table_NoviceTarget_t.Goto[25]
  },
  [35] = {
    id = 35,
    Sort = 7,
    TargetType = 5,
    Desc = "kill_count",
    TargetNum = 300,
    Reward = Table_NoviceTarget_t.Reward[33],
    IconScale = 0.9,
    Title = "魔物猎手",
    SubTitle = "累计击杀%s/300只魔物",
    Description = "击杀魔物是冒险者的重要任务，每斩杀一只都是您积攒的功勋。完成一定数额即可获得经验奖励。",
    Practical = 3,
    Goto = Table_NoviceTarget_t.Goto[20]
  },
  [36] = {
    id = 36,
    Sort = 8,
    TargetType = 18,
    Param = Table_NoviceTarget_t.Param[10],
    TargetNum = 12,
    Reward = Table_NoviceTarget_t.Reward[34],
    Icon = "icon_1",
    IconScale = 1.1,
    Title = "荒境冒险",
    SubTitle = "完成荒境冒险任务%s/12个",
    Description = "尝试完成4个荒境冒险任务，可获得每日最终奖励，这是起源转职技能加点材料“时光流沙”的主要产出之一。",
    Practical = 3,
    Goto = Table_NoviceTarget_t.Goto[14]
  },
  [37] = {
    id = 37,
    Sort = 9,
    TargetType = 8,
    Desc = "tower_layer",
    TargetNum = 12,
    Reward = Table_NoviceTarget_t.Reward[35],
    Icon = "Dungeon",
    SubTitle = "完成12层勇者试炼塔",
    Description = "勇者试炼塔是冒险者个人专属的试炼之地，与守门人对话后，你将被传送进由魔法创造的虚拟空间与魔物战斗。完成12层后即可获得奖励。",
    Practical = 3,
    Goto = Table_NoviceTarget_t.Goto[7]
  },
  [38] = {
    id = 38,
    Day = 5,
    TargetType = 1,
    Reward = Table_NoviceTarget_t.Reward[28],
    Icon = "Sign_in_80",
    IconScale = 0.9,
    Title = "欢迎来到米德加尔特",
    Practical = 5,
    Difficult = 1,
    Frequency = 5
  },
  [39] = {
    id = 39,
    Day = 5,
    Sort = 2,
    TargetType = 20,
    Desc = "photo_count",
    Reward = Table_NoviceTarget_t.Reward[36],
    Icon = "photo",
    IconScale = 0.9,
    Title = "记录时光",
    SubTitle = "使用照相机拍摄一张照片",
    Description = "使用[照相机]即可进入摄影模式，你可以调整角色和镜头视角、选择喜欢的表情动作、加上美美的滤镜，留下自己和好友在米德加尔特大陆冒险的精彩瞬间。",
    Practical = 3,
    Difficult = 1,
    Goto = Table_NoviceTarget_t.Goto[26]
  },
  [40] = {
    id = 40,
    Day = 5,
    Sort = 3,
    TargetType = 21,
    Desc = "type",
    Param = Table_NoviceTarget_t.Param[19],
    Reward = Table_NoviceTarget_t.Reward[37],
    Icon = "item_45001",
    IconScale = 1.15,
    Title = "收藏家",
    SubTitle = "解锁冒险手册的头饰一次",
    Description = "将制作的新头饰在「冒险手册」中解锁即可获得大量冒险经验。\n将不需要装备的头饰存入「冒险手册」，不仅能节省背包空间，还能获得永久的角色属性提升。",
    Practical = 3,
    Difficult = 2,
    Frequency = 2,
    Message = "打开「更多」中的「冒险手册」查看~"
  },
  [41] = {
    id = 41,
    Day = 5,
    Sort = 4,
    TargetType = 54,
    Reward = Table_NoviceTarget_t.Reward[38],
    Icon = "teamfight",
    IconScale = 0.9,
    Title = "一起冒险吧",
    SubTitle = "组建你的队伍",
    Description = "从主界面上方打开「队伍」界面后创建队伍成为队长，也可以选择副本发布队伍或加入他人的队伍，亦可以选择自动匹配。\n冒险者作为队长时，可以邀请伙伴或佣兵猫加入队伍。",
    Difficult = 1,
    Frequency = 4,
    Message = "点击主界面上方的「队伍」按钮后可以「创建队伍」~"
  },
  [42] = {
    id = 42,
    Day = 5,
    Sort = 5,
    TargetType = 19,
    PreID = 3,
    Reward = Table_NoviceTarget_t.Reward[39],
    Icon = "cracks",
    Title = "异界冒险",
    SubTitle = "修复副本裂隙一次",
    Description = "打开「执事」界面后，点击「修复裂隙」右方的「GO」按钮即可打开「裂隙副本」界面。\n创建队伍后，选择一个裂隙副本，带上你的伙伴们一起去挑战它吧~\nTips：每个裂隙副本初次通关后都会解锁它的快速完成功能。",
    Difficult = 4,
    Frequency = 4,
    Goto = Table_NoviceTarget_t.Goto[25]
  },
  [43] = {
    id = 43,
    Day = 5,
    Sort = 6,
    TargetType = 24,
    Param = Table_NoviceTarget_t.Param[20],
    TargetNum = 1,
    Reward = Table_NoviceTarget_t.Reward[40],
    Icon = "item_5832",
    IconScale = 0.9,
    Title = "事半功倍",
    SubTitle = "使用坠星陨铁一次",
    Description = "练级太慢不要慌，坠星陨铁帮你忙。\n打开「包包」使用「坠星陨铁」后，野外战斗将加速消耗4倍战斗时长，获得4倍经验和掉落，30分钟内持续有效。",
    Difficult = 1,
    Frequency = 4,
    Goto = Table_NoviceTarget_t.Goto[23]
  },
  [44] = {
    id = 44,
    Day = 5,
    Sort = 7,
    TargetType = 25,
    Desc = "battle_time",
    TargetNum = 150,
    Reward = Table_NoviceTarget_t.Reward[41],
    Icon = "jingpilijie",
    IconScale = 0.9,
    Title = "酣畅淋漓",
    SubTitle = "花费你的当日剩余疲劳",
    Description = "当日战斗满150分钟即可完成此项任务，pvp不计入战斗时长。如果队友和自己处于同一张地图，则战斗时长共享至本地图所有队员。",
    Practical = 3,
    Difficult = 1,
    Goto = Table_NoviceTarget_t.Goto[27]
  },
  [45] = {
    id = 45,
    Day = 5,
    Sort = 8,
    TargetType = 8,
    Desc = "tower_layer",
    TargetNum = 15,
    Reward = Table_NoviceTarget_t.Reward[42],
    Icon = "Dungeon",
    SubTitle = "完成15层勇者试炼塔",
    Description = "勇者试炼塔是冒险者个人专属的试炼之地，与守门人对话后，你将被传送进由魔法创造的虚拟空间与魔物战斗。完成15层后即可获得奖励。",
    Practical = 3,
    Goto = Table_NoviceTarget_t.Goto[7]
  },
  [46] = {
    id = 46,
    Day = 6,
    TargetType = 1,
    Reward = Table_NoviceTarget_t.Reward[28],
    Icon = "Sign_in_80",
    IconScale = 0.9,
    Title = "欢迎来到米德加尔特",
    Practical = 5,
    Difficult = 1,
    Frequency = 5
  },
  [47] = {
    id = 47,
    Day = 6,
    Sort = 3,
    TargetType = 18,
    Param = Table_NoviceTarget_t.Param[10],
    TargetNum = 16,
    Reward = Table_NoviceTarget_t.Reward[43],
    Icon = "icon_1",
    IconScale = 1.1,
    Title = "荒境冒险",
    SubTitle = "完成荒境冒险任务%s/16个",
    Description = "完成4个荒境冒险任务，获得每日最终奖励。",
    Practical = 3,
    Goto = Table_NoviceTarget_t.Goto[14]
  },
  [48] = {
    id = 48,
    Day = 6,
    Sort = 4,
    TargetType = 16,
    Desc = "techtree_count",
    TargetNum = 3,
    PreID = 24,
    Reward = Table_NoviceTarget_t.Reward[44],
    Icon = "huangjingshenshu2",
    Title = "神树的庇护",
    SubTitle = "累计激活%s/3点神树之灵",
    Description = "在荒境「神树之灵」界面上，尝试激活任意3个节点。\n所需材料可通过击杀荒境魔物获得。",
    Goto = Table_NoviceTarget_t.Goto[19]
  },
  [49] = {
    id = 49,
    Day = 6,
    Sort = 5,
    TargetType = 21,
    Param = Table_NoviceTarget_t.Param[21],
    Reward = Table_NoviceTarget_t.Reward[45],
    Icon = "cardunlock",
    Title = "天哪！是卡片！",
    SubTitle = "解锁卡片一次",
    Description = "通过击杀魔物，有概率获取它的卡片，此后打开「更多」中的「冒险手册」卡片页签即可将它解锁。",
    Practical = 3,
    Difficult = 2,
    Frequency = 2,
    Message = "获得卡片，并在冒险手册的卡片页签下解锁它。"
  },
  [50] = {
    id = 50,
    Day = 6,
    Sort = 2,
    TargetType = 6,
    Desc = "endless_layer",
    Param = Table_NoviceTarget_t.Param[22],
    Reward = Table_NoviceTarget_t.Reward[46],
    Icon = "Dungeon",
    Title = "超越极限",
    SubTitle = "完成恩德勒斯塔20层",
    Description = "攀登恩德勒斯塔是勇气的证明，在塔中冒险者可击杀大量mvp和mini怪物，收获经验、材料和装备。爬塔层数越高，收获奖励越多。",
    Difficult = 4,
    Goto = Table_NoviceTarget_t.Goto[28]
  },
  [51] = {
    id = 51,
    Day = 6,
    Sort = 6,
    TargetType = 5,
    Desc = "kill_count",
    Param = Table_NoviceTarget_t.Param[23],
    TargetNum = 50,
    Reward = Table_NoviceTarget_t.Reward[47],
    IconScale = 0.9,
    Title = "风息猎手",
    SubTitle = "击杀风息之野荒野食人花%s/50只",
    Description = "在野外挂机与自己等级强度相匹配的魔物，是冒险者快速升级获得经验、材料的方式之一，准备充分后使用自动战斗来一场酣畅淋漓的战斗吧！",
    Practical = 3,
    Goto = Table_NoviceTarget_t.Goto[29]
  },
  [52] = {
    id = 52,
    Day = 6,
    Sort = 7,
    TargetType = 8,
    Desc = "tower_layer",
    TargetNum = 18,
    Reward = Table_NoviceTarget_t.Reward[48],
    Icon = "Dungeon",
    SubTitle = "完成18层勇者试炼塔",
    Description = "勇者试炼塔是冒险者个人专属的试炼之地，与守门人对话后，你将被传送进由魔法创造的虚拟空间与魔物战斗。完成18层后即可获得奖励。",
    Practical = 3,
    Goto = Table_NoviceTarget_t.Goto[7]
  },
  [53] = {
    id = 53,
    Day = 7,
    TargetType = 1,
    Reward = Table_NoviceTarget_t.Reward[49],
    Icon = "Sign_in_80",
    IconScale = 0.9,
    Title = "欢迎来到米德加尔特",
    Practical = 5,
    Difficult = 1,
    Frequency = 5
  },
  [54] = {
    id = 54,
    Day = 7,
    Sort = 2,
    Param = Table_NoviceTarget_t.Param[24],
    Reward = Table_NoviceTarget_t.Reward[50],
    Icon = "homeliy",
    IconScale = 0.9,
    Title = "我的家园",
    SubTitle = "完成家园引导任务",
    Description = "通过普隆德拉的菲露特接取任务，打造属于自己的温馨家园。",
    Practical = 3,
    Frequency = 2,
    Goto = Table_NoviceTarget_t.Goto[30]
  },
  [55] = {
    id = 55,
    Day = 7,
    Sort = 3,
    TargetType = 21,
    Param = Table_NoviceTarget_t.Param[25],
    PreID = 54,
    Reward = Table_NoviceTarget_t.Reward[51],
    Icon = "sewing_s",
    IconScale = 0.8,
    Title = "崭新的家具",
    SubTitle = "解锁冒险手册的任一个家具",
    Description = "想要获得家具吗？准备好素材，从家具商人处购买图纸就可以开始制作啦。",
    Practical = 3,
    Frequency = 2,
    Goto = Table_NoviceTarget_t.Goto[31]
  },
  [56] = {
    id = 56,
    Day = 7,
    Sort = 4,
    TargetType = 55,
    PreID = 54,
    Reward = Table_NoviceTarget_t.Reward[52],
    Icon = "homeliy",
    IconScale = 0.9,
    Title = "秘密藏宝箱",
    SubTitle = "使用家园仓库存储物品一次",
    Description = "进入家园与你的专属女仆戴莉拉对话进入建造模式，成功建造储物柜后，即可点击储物柜使用家园仓库存储物品。",
    Practical = 3,
    Difficult = 1,
    Frequency = 2,
    Message = "建造储物柜后，即可以使用家园仓库存储物品。"
  },
  [57] = {
    id = 57,
    Day = 7,
    Sort = 5,
    TargetType = 22,
    Param = Table_NoviceTarget_t.Param[26],
    Reward = Table_NoviceTarget_t.Reward[53],
    Icon = "equip_Details",
    Title = "无懈可击",
    SubTitle = "每个部位均有装备穿戴",
    Description = "装备具有各种属性，能够大幅提升你的战斗力，一件都不要少哦。",
    Difficult = 1,
    Frequency = 2,
    Goto = Table_NoviceTarget_t.Goto[23]
  },
  [58] = {
    id = 58,
    Day = 7,
    Sort = 6,
    TargetType = 5,
    Desc = "kill_count",
    Param = Table_NoviceTarget_t.Param[27],
    TargetNum = 500,
    Reward = Table_NoviceTarget_t.Reward[54],
    IconScale = 0.9,
    Title = "魔物猎手",
    SubTitle = "在指定区域击杀%s/500只魔物",
    Description = "击杀荒境或风息之野地图内魔物达到500只。",
    Practical = 3,
    Goto = Table_NoviceTarget_t.Goto[29]
  },
  [59] = {
    id = 59,
    Day = 7,
    Sort = 7,
    TargetType = 8,
    Desc = "tower_layer",
    TargetNum = 21,
    Reward = Table_NoviceTarget_t.Reward[55],
    Icon = "Dungeon",
    SubTitle = "完成21层勇者试炼塔",
    Description = "勇者试炼塔是冒险者个人专属的试炼之地，与守门人对话后，你将被传送入由魔法创造的虚拟空间与魔物战斗。完成21层后即可获得奖励。",
    Practical = 3,
    Goto = Table_NoviceTarget_t.Goto[7]
  },
  [60] = {
    id = 60,
    Day = 8,
    TargetType = 1,
    Reward = Table_NoviceTarget_t.Reward[28],
    Icon = "Sign_in_80",
    IconScale = 0.9,
    Title = "欢迎来到米德加尔特",
    Practical = 5,
    Difficult = 1,
    Frequency = 5
  },
  [61] = {
    id = 61,
    Day = 8,
    Sort = 2,
    Param = Table_NoviceTarget_t.Param[28],
    Reward = Table_NoviceTarget_t.Reward[56],
    Icon = "forever",
    IconScale = 0.85,
    Title = "新手冒险家",
    SubTitle = "获得冒险者称号「勘察员」",
    Description = "冒险等级达到5级后，即可前往「普隆德拉」寻找冒险者公会会长「卡卡罗」进行冒险者称号「勘察员」进阶任务。\n冒险者称号进阶，会给冒险者提供大幅度的属性提升，并解锁新的冒险技能。Tips：打开「更多」中的「冒险手册」即可查看当前冒险等级。通过解锁头饰、卡片、家具，或是完成成就等均可获得冒险经验。",
    Practical = 3,
    Frequency = 1,
    Goto = Table_NoviceTarget_t.Goto[32]
  },
  [62] = {
    id = 62,
    Day = 8,
    Sort = 3,
    TargetType = 30,
    Desc = "adventureskill_count",
    Reward = Table_NoviceTarget_t.Reward[57],
    Icon = "Guild_Dojo",
    IconScale = 0.85,
    Title = "冒险心得",
    SubTitle = "购买一次冒险技能",
    Description = "您可以通过普隆德拉的冒险技能导师学习更多冒险技能，这些技能会使您的冒险生活更加便利。",
    Practical = 3,
    Difficult = 2,
    Goto = Table_NoviceTarget_t.Goto[33]
  },
  [63] = {
    id = 63,
    Day = 8,
    Sort = 4,
    Param = Table_NoviceTarget_t.Param[29],
    Reward = Table_NoviceTarget_t.Reward[58],
    Icon = "exchange",
    Title = "了解交易所",
    SubTitle = "与B格猫星人了解一下交易所功能",
    Description = "交易所是米德加尔特大陆最安全快捷的交易平台之一，与交易所职员对话，了解关于交易所的更多信息。",
    Difficult = 1,
    Frequency = 4,
    Goto = Table_NoviceTarget_t.Goto[34]
  },
  [64] = {
    id = 64,
    Day = 8,
    Sort = 5,
    TargetType = 16,
    Desc = "techtree_count",
    TargetNum = 6,
    PreID = 48,
    Reward = Table_NoviceTarget_t.Reward[59],
    Icon = "huangjingshenshu2",
    Title = "神树的庇护",
    SubTitle = "累计激活%s/6点神树之灵",
    Description = "在荒境「神树之灵」界面上，尝试激活任意6个节点。\n所需材料可通过击杀荒境魔物获得。",
    Goto = Table_NoviceTarget_t.Goto[19]
  },
  [65] = {
    id = 65,
    Day = 9,
    TargetType = 1,
    Reward = Table_NoviceTarget_t.Reward[28],
    Icon = "Sign_in_80",
    IconScale = 0.9,
    Title = "欢迎来到米德加尔特",
    Practical = 5,
    Difficult = 1,
    Frequency = 5
  },
  [66] = {
    id = 66,
    Day = 9,
    Sort = 2,
    TargetType = 28,
    Desc = "num",
    TargetNum = 2,
    PreID = 3,
    Reward = Table_NoviceTarget_t.Reward[60],
    Icon = "Housekeeper",
    IconScale = 0.9,
    Title = "第二位执事",
    SubTitle = "执事解锁的人数达到2位",
    Description = "完成个人助理任务后，即可解锁第二位执事。不同的执事能够为你开放不同的执事商店，请根据自身需求选择合适的执事吧。",
    Practical = 5,
    Difficult = 1,
    Frequency = 5,
    Goto = Table_NoviceTarget_t.Goto[2]
  },
  [67] = {
    id = 67,
    Day = 9,
    Sort = 3,
    TargetType = 23,
    Desc = "battlepass_level",
    TargetNum = 10,
    PreID = 34,
    Reward = Table_NoviceTarget_t.Reward[61],
    Icon = "MaleAssistant",
    IconScale = 0.9,
    Title = "卡普拉冒险录",
    SubTitle = "卡普拉冒险录等级提升至%s/10级",
    Description = "完成执事日常和周常任务，是获得卡普拉冒险录经验的唯二途径。\n冒险者通过提升卡普拉冒险录等级可以获得丰厚的奖励，还可以前往卡普拉冒险录商店兑换心仪的物品哦~",
    Practical = 2,
    Frequency = 2,
    Goto = Table_NoviceTarget_t.Goto[25]
  },
  [68] = {
    id = 68,
    Day = 9,
    Sort = 4,
    TargetType = 6,
    Param = Table_NoviceTarget_t.Param[30],
    Reward = Table_NoviceTarget_t.Reward[62],
    Icon = "refine_2",
    IconScale = 1.15,
    Title = "精炼之道",
    SubTitle = "精炼你的武器一次",
    Description = "装备可在铁匠忽克连处进行精炼。提升精炼等级能够提升装备攻击或伤害减免属性，达到特定精炼等级后还会触发装备特效。",
    Difficult = 2,
    Goto = Table_NoviceTarget_t.Goto[35]
  },
  [69] = {
    id = 69,
    Day = 9,
    Sort = 5,
    TargetType = 6,
    Param = Table_NoviceTarget_t.Param[31],
    PreID = 13,
    Reward = Table_NoviceTarget_t.Reward[63],
    Icon = "item_5682",
    Title = "宠物探险队",
    SubTitle = "使用你的宠物冒险并领取奖励",
    Description = "打开「包包」并使用道具「不思议宠物袋」，在第一页「宠物冒险」中选择一个地区，派遣宠物去冒险吧~\nTips：派遣宠物冒险会消耗冒险者的战斗时长，但无视掉落衰减及经验衰减。冒险结束后可获取相应奖励。",
    Practical = 3,
    Difficult = 2,
    Goto = Table_NoviceTarget_t.Goto[36]
  },
  [70] = {
    id = 70,
    Day = 9,
    Sort = 6,
    TargetType = 8,
    Desc = "tower_layer",
    TargetNum = 25,
    Reward = Table_NoviceTarget_t.Reward[64],
    Icon = "Dungeon",
    SubTitle = "完成25层勇者试炼塔",
    Description = "勇者试炼塔是冒险者个人专属的试炼之地，与守门人对话后，你将被传送入由魔法创造的虚拟空间与魔物战斗。完成25层后即可获得奖励。",
    Practical = 3,
    Goto = Table_NoviceTarget_t.Goto[7]
  },
  [71] = {
    id = 71,
    Day = 10,
    TargetType = 1,
    Reward = Table_NoviceTarget_t.Reward[28],
    Icon = "Sign_in_80",
    IconScale = 0.9,
    Title = "欢迎来到米德加尔特",
    Practical = 5,
    Difficult = 1,
    Frequency = 5
  },
  [72] = {
    id = 72,
    Day = 10,
    Sort = 2,
    TargetType = 33,
    TargetNum = 3,
    PreID = 54,
    Reward = Table_NoviceTarget_t.Reward[65],
    Icon = "sewing_s",
    IconScale = 0.8,
    Title = "家装大师",
    SubTitle = "家园评分达到3级",
    Description = "打开「更多」中的「家园」界面即可查看当前的家园等级。\n通过装扮家园，将其评分提升至3级。\n提高各区域声望，可从声望商店购买更多家具和图纸。",
    Practical = 2,
    Frequency = 2,
    Goto = Table_NoviceTarget_t.Goto[37]
  },
  [73] = {
    id = 73,
    Day = 10,
    Sort = 3,
    TargetType = 21,
    Param = Table_NoviceTarget_t.Param[32],
    Reward = Table_NoviceTarget_t.Reward[66],
    Icon = "photo",
    IconScale = 0.9,
    Title = "收藏美好",
    SubTitle = "冒险手册中解锁1个景点",
    Description = "「小地图」中的「照相机」标记处即为景点，前往景点处并拍摄到「照相」界面中的绿色照相机后就拍摄景点成功了。\n在「更多」中的「冒险手册」景点页签里可以将它解锁。一起成为摄影大师吧！",
    Practical = 3,
    Difficult = 1,
    Message = "找找小地图中的照相机标记吧~"
  },
  [74] = {
    id = 74,
    Day = 10,
    Sort = 4,
    TargetType = 66,
    Reward = Table_NoviceTarget_t.Reward[67],
    IconScale = 0.9,
    Title = "我是热心肠",
    SubTitle = "完成一条辛格拉万事箱的任务",
    Description = "「辛格拉万事箱」每日会下发两条委托任务，完成后会获得区域声望等奖励哦~\nTips：当每次完成「辛格拉万事箱」中的一系列委托，都会额外获得一个特殊的头饰。",
    Practical = 3,
    Goto = Table_NoviceTarget_t.Goto[38]
  },
  [75] = {
    id = 75,
    Day = 10,
    Sort = 5,
    TargetType = 15,
    Desc = "skill_count",
    TargetNum = 5,
    PreID = 12,
    Reward = Table_NoviceTarget_t.Reward[68],
    Icon = "Skill",
    Title = "起源之力",
    SubTitle = "四转技能点消耗达到%s/5点",
    Description = "打开「更多」中的「技能」界面，选择上方「起源技能」页签，即可使用「时之流沙」强化四转职业技能。",
    Difficult = 2,
    Goto = Table_NoviceTarget_t.Goto[17]
  },
  [76] = {
    id = 76,
    Day = 11,
    TargetType = 1,
    Reward = Table_NoviceTarget_t.Reward[28],
    Icon = "Sign_in_80",
    IconScale = 0.9,
    Title = "欢迎来到米德加尔特",
    Practical = 5,
    Difficult = 1,
    Frequency = 5
  },
  [77] = {
    id = 77,
    Day = 11,
    Sort = 5,
    TargetType = 35,
    Reward = Table_NoviceTarget_t.Reward[69],
    Icon = "Waste_Stove",
    IconScale = 1.1,
    Title = "废品回收",
    SubTitle = "分解一次装备",
    Description = "不需要的装备可以通过魔力铁炉消耗Zeny进行分解，分解装备后会返还一些Zeny和辉光金属。\n辉光金属在装备升级时可能会用上哦~",
    Practical = 3,
    Difficult = 1,
    Frequency = 2,
    Goto = Table_NoviceTarget_t.Goto[39]
  },
  [78] = {
    id = 78,
    Day = 11,
    Sort = 2,
    TargetType = 29,
    TargetNum = 10,
    Reward = Table_NoviceTarget_t.Reward[70],
    Icon = "forever",
    IconScale = 0.85,
    Title = "冒险之星",
    SubTitle = "冒险等级达到%s/10级",
    Description = "打开「更多」中的「冒险手册」即可查看当前冒险等级。通过解锁头饰、卡片、家具，或是完成成就等均可获得冒险经验。",
    Practical = 3,
    Difficult = 2,
    Message = "打开「更多」中的「冒险手册」查看~"
  },
  [79] = {
    id = 79,
    Day = 11,
    Sort = 3,
    TargetType = 16,
    Desc = "techtree_count",
    TargetNum = 10,
    PreID = 64,
    Reward = Table_NoviceTarget_t.Reward[71],
    Icon = "huangjingshenshu2",
    Title = "神树的庇护",
    SubTitle = "累计激活%s/10点神树之灵",
    Description = "在荒境「神树之灵」界面上，尝试激活任意10个节点。\n所需材料可通过击杀荒境魔物获得。",
    Goto = Table_NoviceTarget_t.Goto[19]
  },
  [80] = {
    id = 80,
    Day = 11,
    Sort = 4,
    Param = Table_NoviceTarget_t.Param[33],
    PreID = 6,
    Reward = Table_NoviceTarget_t.Reward[72],
    IconScale = 0.9,
    Title = "入乡随俗",
    SubTitle = "完成洛阳主线任务：烟纱里的舞",
    Description = "完成洛阳主线任务：烟纱里的舞。",
    Practical = 3,
    Frequency = 1,
    Goto = Table_NoviceTarget_t.Goto[40]
  },
  [81] = {
    id = 81,
    Day = 11,
    Sort = 6,
    TargetType = 8,
    Desc = "tower_layer",
    TargetNum = 30,
    Reward = Table_NoviceTarget_t.Reward[73],
    Icon = "Dungeon",
    SubTitle = "完成30层勇者试炼塔",
    Description = "勇者试炼塔是冒险者个人专属的试炼之地，与守门人对话后，你将被传送入由魔法创造的虚拟空间与魔物战斗。完成30层后即可获得奖励。",
    Practical = 3,
    Goto = Table_NoviceTarget_t.Goto[7]
  },
  [82] = {
    id = 82,
    Day = 12,
    TargetType = 1,
    Reward = Table_NoviceTarget_t.Reward[28],
    Icon = "Sign_in_80",
    IconScale = 0.9,
    Title = "欢迎来到米德加尔特",
    Practical = 5,
    Difficult = 1,
    Frequency = 5
  },
  [83] = {
    id = 83,
    Day = 12,
    Sort = 2,
    TargetType = 36,
    Desc = "prestige_level",
    Param = Table_NoviceTarget_t.Param[34],
    TargetNum = 5,
    Reward = Table_NoviceTarget_t.Reward[74],
    Icon = "Homecamp",
    IconScale = 0.9,
    Title = "蜚声荒境",
    SubTitle = "荒境的声望商店等级达到5级",
    Description = "完成「洛阳」区域的冒险任务，可提升荒境巡守队声望，声望商店将解锁更多家具与图纸。",
    Practical = 3,
    Goto = Table_NoviceTarget_t.Goto[41]
  },
  [84] = {
    id = 84,
    Day = 12,
    Sort = 3,
    TargetType = 37,
    Desc = "gashapon_count",
    Reward = Table_NoviceTarget_t.Reward[75],
    Icon = "Lotterybody_B",
    Title = "“血统”检测",
    SubTitle = "扭蛋机扭过一次",
    Description = "使用扭蛋机抽取道具吧。无论装备、外观、饰品还是坐骑，只要你够欧都可以扭到哦。",
    Practical = 3,
    Difficult = 1,
    Frequency = 2,
    Goto = Table_NoviceTarget_t.Goto[42]
  },
  [85] = {
    id = 85,
    Day = 12,
    Sort = 4,
    TargetType = 48,
    Desc = "beauty_count",
    Reward = Table_NoviceTarget_t.Reward[76],
    Icon = "equipment_enchant1",
    Title = "人靠衣装",
    SubTitle = "使用幻化功能成功幻化一次",
    Description = "从「包包」界面最左侧的「幻化」按钮处即可进入幻化界面，穿搭出最帅气/可爱的自己吧~\nTips：在「冒险手册」中存入武器、时装、头饰、坐骑等后，才可以将自己的外观幻化成它们的样子。",
    Practical = 2,
    Difficult = 1,
    Frequency = 2,
    Goto = Table_NoviceTarget_t.Goto[23]
  },
  [86] = {
    id = 86,
    Day = 12,
    Sort = 5,
    TargetType = 25,
    Desc = "battle_time",
    TargetNum = 150,
    Reward = Table_NoviceTarget_t.Reward[77],
    Icon = "jingpilijie",
    Title = "酣畅淋漓",
    SubTitle = "花费你的当日剩余疲劳",
    Description = "当日战斗满150分钟即可完成此项任务，pvp不计入战斗时长。如果队友和自己处于同一张地图，则战斗时长共享至本地图所有队员。",
    Practical = 3,
    Difficult = 1,
    Goto = Table_NoviceTarget_t.Goto[27]
  },
  [87] = {
    id = 87,
    Day = 13,
    TargetType = 1,
    Reward = Table_NoviceTarget_t.Reward[28],
    Icon = "Sign_in_80",
    IconScale = 0.9,
    Title = "欢迎来到米德加尔特",
    Practical = 5,
    Difficult = 1,
    Frequency = 5
  },
  [88] = {
    id = 88,
    Day = 13,
    Sort = 2,
    TargetType = 39,
    PreID = 13,
    Reward = Table_NoviceTarget_t.Reward[78],
    Icon = "item_5682",
    IconScale = 0.9,
    Title = "孩子长大了",
    SubTitle = "派遣你的宠物前往打工并领取奖励",
    Description = "打开「包包」并使用道具「不思议宠物袋」，在第三页「宠物打工」中尝试派遣闲置的宠物进入不同场所打工吧~\nTips：不同的打工场所将给予不同的打工奖励，打工场所可通过获得更高级的冒险者称号、提升自身烹饪等级、购买限定特典等方式解锁。",
    Difficult = 1,
    Frequency = 4,
    Goto = Table_NoviceTarget_t.Goto[36]
  },
  [89] = {
    id = 89,
    Day = 13,
    Sort = 3,
    TargetType = 6,
    Param = Table_NoviceTarget_t.Param[35],
    PreID = 13,
    Reward = Table_NoviceTarget_t.Reward[79],
    Icon = "child",
    Title = "爱的证明",
    SubTitle = "赠送宠物10次礼物",
    Description = "从主界面上的「宠物头像」处点击「赠礼」即可将其喜好物品赠与宠物，提高宠物的好感度。\n点击「查看」即可在宠物详情界面中查看宠物的属性、技能、外观等信息。\nTips：只有未经融合的宠物才有喜好物品~",
    Practical = 3,
    Difficult = 2,
    Frequency = 2,
    Message = "从「宠物头像」处点击「赠礼」吧~"
  },
  [90] = {
    id = 90,
    Day = 13,
    Sort = 4,
    TargetType = 25,
    Desc = "battle_time",
    TargetNum = 150,
    Reward = Table_NoviceTarget_t.Reward[80],
    Icon = "jingpilijie",
    Title = "酣畅淋漓",
    SubTitle = "花费你的当日剩余疲劳",
    Description = "当日战斗满150分钟即可完成此项任务，pvp不计入战斗时长。如果队友和自己处于同一张地图，则战斗时长共享至本地图所有队员。",
    Practical = 3,
    Difficult = 1,
    Goto = Table_NoviceTarget_t.Goto[27]
  },
  [91] = {
    id = 91,
    Day = 13,
    Sort = 5,
    TargetType = 58,
    Reward = Table_NoviceTarget_t.Reward[81],
    Icon = "exchange",
    IconScale = 0.9,
    Title = "买买买",
    SubTitle = "从交易所购买一次物品",
    Description = "交易所是ro世界超安全超快捷的交易平台，你可以使用zeny购买所需的商品。",
    Difficult = 1,
    Frequency = 4,
    Goto = Table_NoviceTarget_t.Goto[43]
  },
  [92] = {
    id = 92,
    Day = 13,
    Sort = 6,
    TargetType = 8,
    Desc = "tower_layer",
    TargetNum = 35,
    Reward = Table_NoviceTarget_t.Reward[82],
    Icon = "Dungeon",
    SubTitle = "完成35层勇者试炼塔",
    Description = "勇者试炼塔是冒险者个人专属的试炼之地，与守门人对话后，你将被传送入由魔法创造的虚拟空间与魔物战斗。完成35层后即可获得奖励。",
    Practical = 3,
    Goto = Table_NoviceTarget_t.Goto[7]
  },
  [93] = {
    id = 93,
    Day = 14,
    TargetType = 1,
    Reward = Table_NoviceTarget_t.Reward[28],
    Icon = "Sign_in_80",
    IconScale = 0.9,
    Title = "欢迎来到米德加尔特",
    Practical = 5,
    Difficult = 1,
    Frequency = 5
  },
  [94] = {
    id = 94,
    Day = 14,
    Sort = 2,
    TargetType = 32,
    Desc = "count",
    Param = Table_NoviceTarget_t.Param[36],
    Reward = Table_NoviceTarget_t.Reward[83],
    Icon = "cardraid",
    Title = "幻想马戏团",
    SubTitle = "进入神谕副本一次",
    Description = "与普隆德拉的幻象马戏团成员对话，或直接从队伍界面进入神谕副本。挑战成功可获得镶嵌用的卡片。",
    Practical = 3,
    Difficult = 4,
    Frequency = 2,
    Goto = Table_NoviceTarget_t.Goto[44]
  },
  [95] = {
    id = 95,
    Day = 14,
    Sort = 3,
    Param = Table_NoviceTarget_t.Param[37],
    Reward = Table_NoviceTarget_t.Reward[84],
    Icon = "equipment_enchant1",
    Title = "附魔的奥秘",
    SubTitle = "解锁附魔功能",
    Description = "与吉芬的猫小友对话，了解并解锁附魔功能。",
    Practical = 3,
    Goto = Table_NoviceTarget_t.Goto[45]
  },
  [96] = {
    id = 96,
    Day = 14,
    Sort = 4,
    TargetType = 6,
    Desc = "enchant_count",
    Param = Table_NoviceTarget_t.Param[38],
    PreID = 95,
    Reward = Table_NoviceTarget_t.Reward[85],
    Icon = "equipment_enchant1",
    Title = "开始附魔吧",
    SubTitle = "任意装备附魔一次",
    Description = "消耗莫拉硬币，在吉芬的猫小友处附魔任意装备。",
    Practical = 3,
    Goto = Table_NoviceTarget_t.Goto[45]
  },
  [97] = {
    id = 97,
    Day = 14,
    Sort = 5,
    TargetType = 39,
    Desc = "petwork_count",
    PreID = 13,
    Reward = Table_NoviceTarget_t.Reward[86],
    Icon = "item_5682",
    Title = "劳动最光荣",
    SubTitle = "领取你的宠物打工奖励一次",
    Description = "打开「包包」并使用道具「不思议宠物袋」，在第三页「宠物打工」中领取宠物们的打工奖励吧~\nTips：不同的打工场所将给予不同的打工奖励，打工场所可通过获得更高级的冒险者称号、提升自身烹饪等级、购买限定特典等方式解锁。",
    Difficult = 1,
    Frequency = 4,
    Goto = Table_NoviceTarget_t.Goto[36]
  },
  [98] = {
    id = 98,
    Day = 15,
    TargetType = 1,
    Reward = Table_NoviceTarget_t.Reward[28],
    Icon = "Sign_in_80",
    IconScale = 0.9,
    Title = "欢迎来到米德加尔特",
    Practical = 5,
    Difficult = 1,
    Frequency = 5
  },
  [99] = {
    id = 99,
    Day = 15,
    Sort = 2,
    Param = Table_NoviceTarget_t.Param[39],
    PreID = 78,
    Reward = Table_NoviceTarget_t.Reward[87],
    Icon = "forever",
    IconScale = 0.8,
    Title = "入门冒险家",
    SubTitle = "成为F级冒险家",
    Description = "冒险等级达到10级后，即可前往「普隆德拉」寻找冒险者公会会长「卡卡罗」进行冒险者称号「F级冒险家」进阶任务。\n冒险者称号进阶，会给冒险者提供大幅度的属性提升，并解锁新的冒险技能。Tips：打开「更多」中的「冒险手册」即可查看当前冒险等级。通过解锁头饰、卡片、家具，或是完成成就等均可获得冒险经验，",
    Practical = 3,
    Difficult = 4,
    Frequency = 1,
    Goto = Table_NoviceTarget_t.Goto[32]
  },
  [100] = {
    id = 100,
    Day = 15,
    Sort = 3,
    TargetType = 30,
    Desc = "adventureskill_count",
    TargetNum = 5,
    Reward = Table_NoviceTarget_t.Reward[88],
    Icon = "Skill",
    Title = "冒险笔记",
    SubTitle = "共学会%s/5个冒险技能",
    Description = "拜访普隆德拉城中的冒险公会会长，习得5个冒险技能。",
    Practical = 3,
    Difficult = 2,
    Goto = Table_NoviceTarget_t.Goto[33]
  },
  [101] = {
    id = 101,
    Day = 15,
    Sort = 4,
    Param = Table_NoviceTarget_t.Param[40],
    Reward = Table_NoviceTarget_t.Reward[89],
    IconScale = 0.9,
    Title = "参加活动吧",
    SubTitle = "与美羽了解一下活动玩法吧",
    Description = "每周固定时间都会有一些刺激又好玩的活动等待着大家的游玩哦~冒险家可以通过“执事”功能页签中的活动日历查看每日活动，游戏设置中还有预约提醒的功能哦~",
    Practical = 2,
    Difficult = 1,
    Frequency = 2,
    Goto = Table_NoviceTarget_t.Goto[46]
  },
  [102] = {
    id = 102,
    Day = 15,
    Sort = 5,
    TargetType = 16,
    Desc = "techtree_count",
    TargetNum = 15,
    PreID = 79,
    Reward = Table_NoviceTarget_t.Reward[90],
    Icon = "huangjingshenshu2",
    Title = "神树的庇护",
    SubTitle = "累计激活%s/15点神树之灵",
    Description = "在荒境「神树之灵」界面上，尝试激活任意15个节点。\n所需材料可通过击杀荒境魔物获得。",
    Goto = Table_NoviceTarget_t.Goto[19]
  },
  [103] = {
    id = 103,
    Day = 16,
    TargetType = 59,
    Reward = Table_NoviceTarget_t.Reward[91],
    Icon = "RiskBook",
    Title = "集卡爱好者",
    SubTitle = "存入你的卡片一次",
    Description = "打开「更多」中的「冒险手册」卡片页签，选择一张右下角有蓝色存入角标的卡片，将它存入到「冒险手册」里可获得对应的永久属性提升~",
    Practical = 3,
    Difficult = 2,
    Frequency = 2,
    Message = "打开「更多」中的「冒险手册」查看~"
  },
  [104] = {
    id = 104,
    Day = 16,
    Sort = 2,
    Param = Table_NoviceTarget_t.Param[41],
    Reward = Table_NoviceTarget_t.Reward[92],
    Icon = "Cuisine",
    Title = "品尝人生",
    SubTitle = "完成任务美食的诱惑",
    Description = "与普隆德拉的摩德纳对话，进入料理协会，寻找资深料理师碧莎完成“初心料理师”认证，即可解锁料理功能。",
    Practical = 3,
    Difficult = 2,
    Goto = Table_NoviceTarget_t.Goto[47]
  },
  [105] = {
    id = 105,
    Day = 16,
    Sort = 3,
    TargetType = 21,
    Desc = "cook_count",
    Param = Table_NoviceTarget_t.Param[42],
    PreID = 104,
    Reward = Table_NoviceTarget_t.Reward[93],
    Icon = "item_550002",
    Title = "对自己好一点",
    SubTitle = "冒险手册解锁任意料理",
    Description = "打开「包包」并使用道具「初心料理书」制作料理后，在「冒险手册」料理页签中解锁它~",
    Practical = 3,
    Difficult = 2,
    Goto = Table_NoviceTarget_t.Goto[48]
  },
  [106] = {
    id = 106,
    Day = 16,
    Sort = 4,
    TargetType = 6,
    Param = Table_NoviceTarget_t.Param[43],
    Reward = Table_NoviceTarget_t.Reward[94],
    Icon = "item_5047",
    Title = "我开动了",
    SubTitle = "品尝一份美味的料理",
    Description = "在「包包」中打开「料理包包」并选择一份料理享用，能够在一段时间内提升角色属性。\n冒险之前，记得吃饭哦。",
    Practical = 3,
    Difficult = 2,
    Message = "在「包包」中找到「料理包包」中的料理并享用它吧~"
  },
  [107] = {
    id = 107,
    Day = 16,
    Sort = 5,
    TargetType = 8,
    Desc = "tower_layer",
    TargetNum = 40,
    Reward = Table_NoviceTarget_t.Reward[95],
    Icon = "Dungeon",
    SubTitle = "完成40层勇者试炼塔",
    Description = "勇者试炼塔是冒险者个人专属的试炼之地，与守门人对话后，你将被传送进由魔法创造的虚拟空间与魔物战斗。完成40层后即可获得奖励。",
    Practical = 3,
    Goto = Table_NoviceTarget_t.Goto[7]
  },
  [108] = {
    id = 108,
    Day = 17,
    TargetType = 43,
    Desc = "exchange_count",
    Reward = Table_NoviceTarget_t.Reward[96],
    Icon = "exchange",
    IconScale = 0.9,
    Title = "赚钱小能手",
    SubTitle = "上架一次交易所物品",
    Description = "在交易所上架你不需要的材料、道具或装备，物品价格可能随着市场交易情况波动。收到出售成功的消息后，不要忘记从交易所领取收入。",
    Difficult = 1,
    Frequency = 4,
    Goto = Table_NoviceTarget_t.Goto[49]
  },
  [109] = {
    id = 109,
    Day = 17,
    Sort = 2,
    TargetType = 42,
    Desc = "dailytask_count",
    TargetNum = 60,
    PreID = 3,
    Reward = Table_NoviceTarget_t.Reward[97],
    Icon = "Housekeeper",
    IconScale = 0.9,
    Title = "活跃冒险者",
    SubTitle = "至今共完成执事任务%s/60个",
    Description = "冒险者完成过的执事日常或周常任务都会被记录下来，累计完成60个时即可完成该目标。",
    Goto = Table_NoviceTarget_t.Goto[25]
  },
  [110] = {
    id = 110,
    Day = 17,
    Sort = 3,
    TargetType = 44,
    Desc = "cardset_count",
    Reward = Table_NoviceTarget_t.Reward[98],
    Icon = "strengthen1",
    Title = "装备的奥秘",
    SubTitle = "在你的装备上镶嵌一次卡片吧",
    Description = "打开「包包」并选择一件装备图标右下角处显示有卡槽的装备，点击「插卡」按钮，即可将卡片镶嵌至装备上。\n不同卡片具有不同效果，在有卡槽的装备上插入卡片能够进一步提升角色的战斗力。\n通过装备打洞，你可以开放装备上未打洞的卡槽，但往往需要消耗同款装备及Zeny。",
    Difficult = 2,
    Frequency = 2,
    Message = "在「包包」中找到一件有卡槽的装备插卡吧~"
  },
  [111] = {
    id = 111,
    Day = 18,
    TargetType = 21,
    Desc = "monstertype_count",
    Param = Table_NoviceTarget_t.Param[44],
    TargetNum = 25,
    Reward = Table_NoviceTarget_t.Reward[99],
    Icon = "RiskBook",
    Title = "魔物终结者",
    SubTitle = "冒险手册一共解锁%s/25种魔物",
    Description = "使用冒险手册，在魔物图鉴中累计解锁25种魔物。",
    Practical = 1,
    Difficult = 2,
    Frequency = 2,
    Message = "打开「更多」中的「冒险手册」查看~"
  },
  [112] = {
    id = 112,
    Day = 18,
    Sort = 2,
    Param = Table_NoviceTarget_t.Param[45],
    Reward = Table_NoviceTarget_t.Reward[100],
    Icon = "charge",
    Title = "装备升级",
    SubTitle = "解锁装备升级功能",
    Description = "与「艾尔帕兰」的菲妮娅对话，了解「装备升级」功能。",
    Practical = 3,
    Difficult = 2,
    Goto = Table_NoviceTarget_t.Goto[50]
  },
  [113] = {
    id = 113,
    Day = 18,
    Sort = 3,
    TargetType = 64,
    Reward = Table_NoviceTarget_t.Reward[101],
    Icon = "titlename",
    Title = "我是传说",
    SubTitle = "获得并装备你的称号",
    Description = "点击角色头像展开个人信息界面，选择一个已经获得的称号装备上。称号能为角色提供属性加成。",
    Practical = 2,
    Difficult = 2,
    Frequency = 2,
    Goto = Table_NoviceTarget_t.Goto[51]
  },
  [114] = {
    id = 114,
    Day = 18,
    Sort = 4,
    TargetType = 36,
    Desc = "prestige_level",
    Param = Table_NoviceTarget_t.Param[46],
    TargetNum = 5,
    Reward = Table_NoviceTarget_t.Reward[102],
    Icon = "Homecamp",
    IconScale = 0.9,
    Title = "眷恋洛阳",
    SubTitle = "洛阳声望商店等级达到5级",
    Description = "完成洛阳辛格拉万事箱任务，可提升影枫司声望，声望商店将解锁更多家具与图纸。",
    Practical = 3,
    Goto = Table_NoviceTarget_t.Goto[52]
  },
  [115] = {
    id = 115,
    Day = 19,
    TargetType = 47,
    Desc = "pet_level，pet_likablity",
    Param = Table_NoviceTarget_t.Param[47],
    PreID = 13,
    Reward = Table_NoviceTarget_t.Reward[103],
    Icon = "child",
    Title = "宠物情缘",
    SubTitle = "宠物等级达到100，好感度达到10",
    Description = "提升宠物等级和好感度，能够解锁更多宠物冒险地图，并在宠物打工过程中更高效地获得奖励哦。",
    Practical = 3,
    Difficult = 4,
    Goto = Table_NoviceTarget_t.Goto[36]
  },
  [116] = {
    id = 116,
    Day = 19,
    Sort = 2,
    TargetType = 50,
    PreID = 54,
    Reward = Table_NoviceTarget_t.Reward[104],
    Icon = "child",
    Title = "快乐时光",
    SubTitle = "使用宠物房功能寄养一只宠物",
    Description = "在家园中布置家具「萌爪小窝」后，即可开启宠物寄养功能。寄养过程中，宠物的经验与好感度将自动增长。",
    Practical = 3,
    Difficult = 2,
    Frequency = 2,
    Message = "制作并放置家具「萌爪小窝」到家园吧~"
  },
  [117] = {
    id = 117,
    Day = 19,
    Sort = 3,
    TargetType = 61,
    PreID = 13,
    Reward = Table_NoviceTarget_t.Reward[105],
    Icon = "pet_equip_3",
    Title = "派对时间",
    SubTitle = "装扮一次宠物头饰",
    Description = "点击宠物头像，查看宠物信息。在宠物装扮界面为宠物佩戴头饰。",
    Practical = 2,
    Difficult = 2,
    Frequency = 2,
    Message = "点击宠物头像并查看~"
  },
  [118] = {
    id = 118,
    Day = 19,
    Sort = 4,
    TargetType = 49,
    Desc = "bless_count",
    Reward = Table_NoviceTarget_t.Reward[106],
    Icon = "blessing_4",
    Title = "女神祝福",
    SubTitle = "使用公会女神祝福一次",
    Description = "开启祈祷晶片包可以获得攻击晶片、防御晶片和元素晶片。通过与公会内的瓦尔基里对话，可获得角色属性提升。",
    Difficult = 2,
    Goto = Table_NoviceTarget_t.Goto[53]
  },
  [119] = {
    id = 119,
    Day = 20,
    Param = Table_NoviceTarget_t.Param[48],
    PreID = 99,
    Reward = Table_NoviceTarget_t.Reward[107],
    Icon = "forever",
    IconScale = 0.8,
    Title = "冒险家进阶",
    SubTitle = "成为E级冒险家",
    Description = "冒险等级达到15级后，即可前往「普隆德拉」寻找冒险者公会会长「卡卡罗」进行冒险者称号「E级冒险家」进阶任务。\n冒险者称号进阶，会给冒险者提供大幅度的属性提升，并解锁新的冒险技能。Tips：打开「更多」中的「冒险手册」即可查看当前冒险等级。通过解锁头饰、卡片、家具，或是完成成就等均可获得冒险经验，",
    Practical = 3,
    Difficult = 4,
    Frequency = 1,
    Goto = Table_NoviceTarget_t.Goto[32]
  },
  [120] = {
    id = 120,
    Day = 20,
    Sort = 2,
    TargetType = 3,
    Param = Table_NoviceTarget_t.Param[49],
    PreID = 119,
    Reward = Table_NoviceTarget_t.Reward[108],
    Icon = "Skill",
    Title = "冒险语录",
    SubTitle = "学习冒险技能时空断裂",
    Description = "与普隆德拉的卡卡罗对话，习得冒险技能：时空断裂，获得「伊米尔记事簿」。",
    Difficult = 2,
    Goto = Table_NoviceTarget_t.Goto[33]
  },
  [121] = {
    id = 121,
    Day = 20,
    Sort = 3,
    TargetType = 62,
    PreID = 120,
    Reward = Table_NoviceTarget_t.Reward[109],
    Icon = "item_5544",
    Title = "时空断点",
    SubTitle = "使用伊米尔记事簿存储一次",
    Description = "打开「包包」并使用道具「伊米尔的记事簿」，可储存角色目前的全部状态，包含但不限于职业、属性、装备、技能、幻化等。\n在需要的时候可以点击「读取」按钮，恢复至储存的状态。",
    Difficult = 2,
    Goto = Table_NoviceTarget_t.Goto[54]
  },
  [122] = {
    id = 122,
    Day = 20,
    Sort = 4,
    TargetType = 65,
    Desc = "count",
    Reward = Table_NoviceTarget_t.Reward[110],
    Icon = "Dungeon",
    Title = "遗迹探险",
    SubTitle = "进入遗迹并击杀MVP/Mini一次",
    Description = "与公会中的英灵军需官特莫里斯对话，进入公会副本击杀稀有魔物，获得经验和奖励。",
    Difficult = 4,
    Goto = Table_NoviceTarget_t.Goto[55]
  },
  [123] = {
    id = 123,
    Day = 21,
    Param = Table_NoviceTarget_t.Param[50],
    Reward = Table_NoviceTarget_t.Reward[111],
    Icon = "strengthen1",
    Title = "符文的抉择",
    SubTitle = "符文功能解锁",
    Description = "前往「朱诺」通过飞空艇管理员「卡索斯」传送至「达纳托斯之塔」，完成任务「符文的力量」，解锁符文功能。",
    Goto = Table_NoviceTarget_t.Goto[56]
  },
  [124] = {
    id = 124,
    Day = 21,
    Sort = 2,
    TargetType = 51,
    PreID = 123,
    Reward = Table_NoviceTarget_t.Reward[112],
    Icon = "strengthen1",
    Title = "符文的力量",
    SubTitle = "镶嵌一次符文",
    Description = "打开「包包」并使用道具「符文之匣」，可以在其中镶嵌技能符文，并通过镶嵌满足要求的属性符文来激活技能符文，从而达到强化职业技能的作用。",
    Goto = Table_NoviceTarget_t.Goto[57]
  },
  [125] = {
    id = 125,
    Day = 21,
    Sort = 3,
    Param = Table_NoviceTarget_t.Param[51],
    PreID = 16,
    Reward = Table_NoviceTarget_t.Reward[113],
    Icon = "huangjingshenshu2",
    Title = "神树的庇护",
    SubTitle = "升级荒境神树之灵至最终阶段",
    Description = "完成全部荒境主线任务即可将荒境「神树之灵」升级至最终阶段。",
    Goto = Table_NoviceTarget_t.Goto[58]
  },
  [126] = {
    id = 126,
    Day = 21,
    Sort = 4,
    TargetType = 26,
    Desc = "count",
    Param = Table_NoviceTarget_t.Param[52],
    Reward = Table_NoviceTarget_t.Reward[114],
    Icon = "Dungeon",
    Title = "至高荣光",
    SubTitle = "完成一次达纳托斯之塔",
    Description = "冒险者需以组成团队的方式进入达纳托斯之塔，通关后可以获得头饰、宠物和坐骑。",
    Difficult = 4,
    Goto = Table_NoviceTarget_t.Goto[59]
  },
  [127] = {
    id = 127,
    Day = 1,
    TargetType = 69,
    Param = Table_NoviceTarget_t.Param[53],
    Reward = Table_NoviceTarget_t.Reward[115],
    Icon = "ForgeSuccess",
    Title = "强化就是力量",
    SubTitle = "武器栏强化等级达到45及以上",
    Description = "通过背包强化页面或者寻找铁匠忽克连对某个装备栏进行强化，强化装备栏可提升角色基础攻击和防御，强化等级上限跟随角色等级提升而提高。",
    Practical = 5,
    Difficult = 2,
    Frequency = 4,
    GuideId = 301500001
  },
  [128] = {
    id = 128,
    Day = 1,
    Sort = 2,
    Param = Table_NoviceTarget_t.Param[6],
    Reward = Table_NoviceTarget_t.Reward[116],
    GM = Table_NoviceTarget_t.GM[1],
    Icon = "Pet",
    Title = "最初的陪伴",
    SubTitle = "完成宠物捕捉任务",
    Description = "前往「普隆德拉南门」与宠物协会会长-阿格尼斯对话开始宠物捕获任务。\n使用「七彩贝壳」购买相应捕捉道具，对魔物使用即可将其捕捉为宠物。\nTips：多兰族冒险者需要前往「罗扎纳」与宠物协会-尼克斯·布蕾对话开始任务喵(=ﾟωﾟ)ﾉ",
    Practical = 3,
    Difficult = 2,
    Goto = Table_NoviceTarget_t.Goto[10]
  },
  [129] = {
    id = 129,
    Day = 1,
    Sort = 3,
    TargetType = 71,
    Param = Table_NoviceTarget_t.Param[54],
    Reward = Table_NoviceTarget_t.Reward[117],
    Icon = "refine_2",
    IconScale = 1.15,
    Title = "精炼之道",
    SubTitle = "精炼你装备的武器至+4及以上",
    Description = "装备可在铁匠忽克连处进行精炼。提升精炼等级能够提升装备攻击或伤害减免属性，达到特定精炼等级后还会触发装备特效。",
    Difficult = 2,
    Goto = Table_NoviceTarget_t.Goto[35]
  },
  [130] = {
    id = 130,
    Day = 1,
    Sort = 4,
    TargetType = 52,
    Desc = "mercenarycat_count",
    TargetNum = 2,
    Reward = Table_NoviceTarget_t.Reward[118],
    Icon = "MercenaryCat",
    Title = "佣兵传说",
    SubTitle = "至少成功雇佣两只佣兵猫",
    Description = "佣兵猫是可以陪伴你一起冒险的重要伙伴，支付zeny即可雇佣和续约。佣兵猫能够为雇主提供抵挡攻击、贡献输出、提供治疗在内的多种服务，根据自己的需求选择合适的佣兵伙伴吧！",
    Difficult = 2,
    Frequency = 4,
    Goto = Table_NoviceTarget_t.Goto[3]
  },
  [131] = {
    id = 131,
    Day = 1,
    Sort = 5,
    Param = Table_NoviceTarget_t.Param[55],
    Reward = Table_NoviceTarget_t.Reward[119],
    Icon = "reincarnation",
    IconScale = 1.1,
    Title = "荒境之谜",
    SubTitle = "完成荒境主线·神秘的笛音",
    Description = "完成荒境主线·神秘的笛音",
    Frequency = 1,
    Goto = Table_NoviceTarget_t.Goto[14]
  },
  [132] = {
    id = 132,
    Day = 1,
    Sort = 6,
    TargetType = 7,
    Reward = Table_NoviceTarget_t.Reward[120],
    Icon = "Guild",
    Title = "冒险大家庭",
    SubTitle = "成功加入一个公会",
    Description = "点击右上角「更多」按钮，在公会界面选择一个公会递交申请，并且成功加入。在公会中你可以认识更多伙伴，解锁更多功能和游戏资源。",
    Difficult = 1,
    GuideId = 301520001
  },
  [133] = {
    id = 133,
    Day = 1,
    Sort = 7,
    TargetType = 8,
    Desc = "tower_layer",
    TargetNum = 3,
    Reward = Table_NoviceTarget_t.Reward[121],
    Icon = "Arena",
    SubTitle = "完成%s/3层勇者试炼塔",
    Description = "勇者试炼塔是冒险者个人专属的试炼之地，与守门人对话后，你将被传送进由魔法创造的虚拟空间与魔物战斗。",
    Practical = 3,
    Goto = Table_NoviceTarget_t.Goto[7]
  },
  [134] = {
    id = 134,
    Day = 1,
    Sort = 8,
    TargetType = 27,
    TargetNum = 30,
    Reward = Table_NoviceTarget_t.Reward[122],
    Icon = "calendar_statistics_icon_09",
    IconScale = 0.9,
    Title = "超越极限",
    SubTitle = "完成恩德勒斯塔%s/30层",
    Description = "攀登恩德勒斯塔是勇气的证明，在塔中冒险者可击杀大量mvp和mini怪物，收获经验、材料和装备。爬塔层数越高，收获奖励越多。",
    Difficult = 4,
    GuideId = 301550001
  },
  [135] = {
    id = 135,
    Day = 2,
    TargetType = 69,
    Param = Table_NoviceTarget_t.Param[56],
    Reward = Table_NoviceTarget_t.Reward[123],
    Icon = "ForgeSuccess",
    Title = "强化就是力量",
    SubTitle = "两件饰品栏强化等级均达到30及以上",
    Description = "通过背包强化页面或者寻找铁匠忽克连对某个装备栏进行强化，强化装备栏可提升角色基础攻击和防御，强化等级上限跟随角色等级提升而提高。",
    Practical = 5,
    Difficult = 2,
    Frequency = 4,
    GuideId = 301510001
  },
  [136] = {
    id = 136,
    Day = 2,
    Sort = 2,
    TargetType = 18,
    Param = Table_NoviceTarget_t.Param[57],
    TargetNum = 8,
    Reward = Table_NoviceTarget_t.Reward[124],
    IconScale = 0.9,
    Title = "荒境冒险",
    SubTitle = "累积完成荒境冒险任务%s/8个",
    Description = "尝试完成4个荒境冒险任务，可获得每日最终奖励，这是起源转职技能加点材料“时光流沙”的主要产出之一。",
    Practical = 3,
    Goto = Table_NoviceTarget_t.Goto[14]
  },
  [137] = {
    id = 137,
    Day = 2,
    Sort = 3,
    Param = Table_NoviceTarget_t.Param[5],
    Reward = Table_NoviceTarget_t.Reward[125],
    Icon = "changeprofession",
    Title = "起源转职",
    SubTitle = "角色完成起源转职任务",
    Description = "完成前置任务「黑夜将至」后，前往「普隆德拉」与诺恩·薇对话开始转职任务。\n完成角色起源转职后，你将解锁更强大的职业技能，并获得职业专属外观。",
    Frequency = 1,
    Goto = Table_NoviceTarget_t.Goto[9]
  },
  [138] = {
    id = 138,
    Day = 2,
    Sort = 4,
    TargetType = 15,
    Desc = "skill_count",
    TargetNum = 5,
    PreID = 137,
    Reward = Table_NoviceTarget_t.Reward[126],
    Icon = "Skill",
    Title = "起源之力",
    SubTitle = "升级%s/5次四转的技能树",
    Description = "打开「更多」中的「技能」界面，选择上方「起源技能」页签，即可使用「时之流沙」强化四转职业技能。",
    Difficult = 2,
    GuideId = 301530001
  },
  [139] = {
    id = 139,
    Day = 2,
    Sort = 5,
    TargetType = 71,
    Param = Table_NoviceTarget_t.Param[58],
    Reward = Table_NoviceTarget_t.Reward[127],
    Icon = "refine_2",
    IconScale = 1.15,
    Title = "精炼之道",
    SubTitle = "精炼你装备的副手至+4及以上",
    Description = "装备可在铁匠忽克连处进行精炼。提升精炼等级能够提升装备攻击或伤害减免属性，达到特定精炼等级后还会触发装备特效。",
    Difficult = 2,
    Goto = Table_NoviceTarget_t.Goto[35]
  },
  [140] = {
    id = 140,
    Day = 2,
    Sort = 6,
    Param = Table_NoviceTarget_t.Param[59],
    Reward = Table_NoviceTarget_t.Reward[128],
    Icon = "reincarnation",
    IconScale = 0.9,
    Title = "荒境之谜",
    SubTitle = "完成荒境主线·将逝的灵魂",
    Description = "完成荒境主线·将逝的灵魂",
    Frequency = 1,
    Goto = Table_NoviceTarget_t.Goto[14]
  },
  [141] = {
    id = 141,
    Day = 2,
    Sort = 7,
    TargetType = 76,
    TargetNum = 10,
    Reward = Table_NoviceTarget_t.Reward[129],
    Icon = "Rune",
    IconScale = 0.9,
    Title = "神碑的启示",
    SubTitle = "激活特殊卢恩符文达%s/10个以上",
    Description = "在背包中找到并使用「阿萨神碑」即可开启神碑界面，消耗贡献点亮其中任意一个符文均可为自身属性提供少量增长，其中部分符文还需消耗金质勋章，这些特殊卢恩符文可以增强已有技能或带来相对更强的增益，记得优先升级哦！",
    Frequency = 1,
    GuideId = 301540001
  },
  [142] = {
    id = 142,
    Day = 2,
    Sort = 8,
    TargetType = 49,
    Desc = "bless_count",
    Param = Table_NoviceTarget_t.Param[60],
    TargetNum = 1,
    Reward = Table_NoviceTarget_t.Reward[130],
    Icon = "blessing_4",
    Title = "女神祈祷",
    SubTitle = "使用公会女神祈祷%s/1次",
    Description = "与公会内的瓦尔基里对话，选择「祈祷」后挑选适合自己的属性，消耗贡献升级即可获得角色属性提升。",
    Difficult = 2,
    Goto = Table_NoviceTarget_t.Goto[53]
  },
  [143] = {
    id = 143,
    Day = 2,
    Sort = 9,
    TargetType = 86,
    TargetNum = 5,
    Reward = Table_NoviceTarget_t.Reward[131],
    Icon = "headwear",
    IconScale = 1.1,
    Title = "保卫蛋糕！",
    SubTitle = "参与蛋糕保卫战并防守住%s/5波",
    Description = "完成蛋糕保卫战可以收集「白雪棉花糖」和「星星草莓」，二者收集到一定数量后即可在蛋糕商店中兑换各式图纸，是头饰与卡片的重要来源之一哦~",
    Practical = 3,
    GuideId = 301560001
  },
  [144] = {
    id = 144,
    Day = 2,
    Sort = 10,
    TargetType = 8,
    Desc = "tower_layer",
    TargetNum = 6,
    Reward = Table_NoviceTarget_t.Reward[132],
    Icon = "Arena",
    SubTitle = "完成%s/6层勇者试炼塔",
    Description = "勇者试炼塔是冒险者个人专属的试炼之地，与守门人对话后，你将被传送进由魔法创造的虚拟空间与魔物战斗。",
    Practical = 3,
    Goto = Table_NoviceTarget_t.Goto[7]
  },
  [145] = {
    id = 145,
    Day = 3,
    TargetType = 80,
    TargetNum = 124,
    Reward = Table_NoviceTarget_t.Reward[133],
    Icon = "forever",
    IconScale = 0.8,
    Title = "英雄的赞歌",
    SubTitle = "Base等级大于等于%s/124",
    Description = "提升Base等级是最基础的强化方式，也是解锁诸多功能和副本的前提，紧跟主线、挑战副本均是积攒Base经验的好方法。",
    Frequency = 1,
    Message = "多多挑战副本，参与活动等方式均可以快速积攒经验值"
  },
  [146] = {
    id = 146,
    Day = 3,
    Sort = 2,
    Param = Table_NoviceTarget_t.Param[61],
    Reward = Table_NoviceTarget_t.Reward[134],
    Icon = "reincarnation",
    IconScale = 0.9,
    Title = "荒境之谜",
    SubTitle = "完成荒境主线·涌动的恶意",
    Description = "完成荒境主线·涌动的恶意",
    Frequency = 1,
    Goto = Table_NoviceTarget_t.Goto[14]
  },
  [147] = {
    id = 147,
    Day = 3,
    Sort = 3,
    TargetType = 89,
    Desc = "techtree_count",
    TargetNum = 6,
    Reward = Table_NoviceTarget_t.Reward[135],
    Icon = "huangjingshenshu2",
    IconScale = 0.9,
    Title = "神树的庇护",
    SubTitle = "至少激活%s/6点神树之灵",
    Description = "在荒境「神树之灵」界面上，尝试激活任意1个节点。\n所需材料可通过完成荒境冒险任务或击杀荒境魔物获得。",
    Goto = Table_NoviceTarget_t.Goto[19]
  },
  [148] = {
    id = 148,
    Day = 3,
    Sort = 4,
    Param = Table_NoviceTarget_t.Param[37],
    Reward = Table_NoviceTarget_t.Reward[136],
    Icon = "equipment_enchant1",
    Title = "附魔奥秘",
    SubTitle = "解锁附魔功能",
    Description = "与吉芬的「猫小友」对话，选择「附魔！」了解并解锁附魔功能。",
    Practical = 3,
    Goto = Table_NoviceTarget_t.Goto[45]
  },
  [149] = {
    id = 149,
    Day = 3,
    Sort = 5,
    TargetType = 38,
    TargetNum = 6,
    PreID = 148,
    Reward = Table_NoviceTarget_t.Reward[136],
    Icon = "equipment_enchant1",
    Title = "附魔奥秘",
    SubTitle = "任意装备附魔%s/6次",
    Description = "在吉芬的猫小友处消耗莫拉硬币即可附魔任意装备，更有机会获取稀有附魔属性哦",
    Practical = 3,
    Goto = Table_NoviceTarget_t.Goto[45]
  },
  [150] = {
    id = 150,
    Day = 3,
    Sort = 6,
    TargetType = 76,
    TargetNum = 15,
    Reward = Table_NoviceTarget_t.Reward[137],
    Icon = "Rune",
    IconScale = 0.9,
    Title = "神碑的启示",
    SubTitle = "激活特殊卢恩符文达%s/15个以上",
    Description = "在背包中找到并使用「阿萨神碑」即可开启神碑界面，消耗贡献点亮其中任意一个符文均可为自身属性提供少量增长，其中部分符文还需消耗金质勋章，这些特殊卢恩符文可以增强已有技能或带来相对更强的增益，记得优先升级哦！",
    Frequency = 1,
    GuideId = 301540001
  },
  [151] = {
    id = 151,
    Day = 3,
    Sort = 7,
    TargetType = 49,
    Desc = "bless_count",
    Param = Table_NoviceTarget_t.Param[60],
    TargetNum = 110,
    Reward = Table_NoviceTarget_t.Reward[138],
    Icon = "blessing_4",
    Title = "女神祈祷",
    SubTitle = "使用公会女神祈祷%s/110次",
    Description = "与公会内的瓦尔基里对话，选择「祈祷」后挑选适合自己的属性，消耗贡献升级即可获得角色属性提升。",
    Difficult = 2,
    Goto = Table_NoviceTarget_t.Goto[53]
  },
  [152] = {
    id = 152,
    Day = 3,
    Sort = 8,
    TargetType = 75,
    TargetNum = 1,
    Reward = Table_NoviceTarget_t.Reward[139],
    Icon = "equipment_drill1",
    Title = "魔卡勇者",
    SubTitle = "装备%s/1个及以上插有卡片的装备",
    Description = "打开背包并选择一件装备图标右下角处显示有卡槽的装备，点击「插卡」按钮，即可将卡片镶嵌至装备上。\n不同卡片具有不同效果，在有卡槽的装备上插入卡片能够进一步提升角色的战斗力。\n通过装备打洞，你可以开放装备上未打洞的卡槽，但往往需要消耗同款装备及Zeny。",
    Difficult = 2,
    Frequency = 2,
    Message = "在「包包」中找到一件有卡槽的装备插卡吧~"
  },
  [153] = {
    id = 153,
    Day = 3,
    Sort = 9,
    TargetType = 47,
    Desc = "pet_level，pet_likablity",
    Param = Table_NoviceTarget_t.Param[62],
    Reward = Table_NoviceTarget_t.Reward[140],
    Icon = "Pet",
    Title = "宠物情缘",
    SubTitle = "至少一只宠物等级达到120及以上",
    Description = "提升宠物的等级，能够解锁更多宠物冒险地图，并且提升宠物的存活能力。",
    Practical = 3,
    Difficult = 4,
    Message = "带领宠物一起战斗，或者喂食宠物经验药水均可以快速提升宠物等级"
  },
  [154] = {
    id = 154,
    Day = 3,
    Sort = 10,
    TargetType = 90,
    Param = Table_NoviceTarget_t.Param[63],
    TargetNum = 1,
    Reward = Table_NoviceTarget_t.Reward[141],
    Icon = "cardraid",
    Title = "幻想马戏团",
    SubTitle = "通关神谕副本初心难度一次",
    Description = "与普隆德拉的幻象马戏团成员对话，或直接从队伍界面进入神谕副本。挑战成功可获得镶嵌用的卡片。",
    Practical = 3,
    Difficult = 4,
    Frequency = 2,
    GuideId = 301570001
  },
  [155] = {
    id = 155,
    Day = 3,
    Sort = 11,
    TargetType = 8,
    Desc = "tower_layer",
    TargetNum = 9,
    Reward = Table_NoviceTarget_t.Reward[142],
    Icon = "Arena",
    SubTitle = "完成%s/9层勇者试炼塔",
    Description = "勇者试炼塔是冒险者个人专属的试炼之地，与守门人对话后，你将被传送进由魔法创造的虚拟空间与魔物战斗。完成3层后即可获得奖励。",
    Practical = 3,
    Goto = Table_NoviceTarget_t.Goto[7]
  },
  [156] = {
    id = 156,
    Day = 3,
    Sort = 12,
    TargetType = 27,
    TargetNum = 50,
    Reward = Table_NoviceTarget_t.Reward[143],
    Icon = "calendar_statistics_icon_09",
    IconScale = 0.9,
    Title = "超越极限",
    SubTitle = "完成恩德勒斯塔%s/50层",
    Description = "攀登恩德勒斯塔是勇气的证明，在塔中冒险者可击杀大量mvp和mini怪物，收获经验、材料和装备。爬塔层数越高，收获奖励越多。",
    Difficult = 4,
    GuideId = 301550001
  },
  [157] = {
    id = 157,
    TargetType = 69,
    Param = Table_NoviceTarget_t.Param[64],
    Reward = Table_NoviceTarget_t.Reward[144],
    Icon = "ForgeSuccess",
    Title = "强化就是力量",
    SubTitle = "武器栏强化等级达到90及以上",
    Description = "通过背包强化页面或者寻找铁匠忽克连对某个装备栏进行强化，强化装备栏可提升角色基础攻击和防御，强化等级上限跟随角色等级提升而提高。",
    Practical = 5,
    Difficult = 2,
    Frequency = 4,
    GuideId = 301500001
  },
  [158] = {
    id = 158,
    Sort = 2,
    TargetType = 15,
    Desc = "skill_count",
    TargetNum = 15,
    Reward = Table_NoviceTarget_t.Reward[145],
    Icon = "Skill",
    Title = "起源之力",
    SubTitle = "升级%s/15次四转的技能树",
    Description = "打开「更多」中的「技能」界面，选择上方「起源技能」页签，即可使用「时之流沙」强化四转职业技能。",
    Difficult = 2,
    GuideId = 301530001
  },
  [159] = {
    id = 159,
    Sort = 3,
    TargetType = 72,
    Param = Table_NoviceTarget_t.Param[65],
    TargetNum = 5,
    Reward = Table_NoviceTarget_t.Reward[146],
    Icon = "refine_2",
    IconScale = 1.15,
    Title = "精炼之道",
    SubTitle = "至少穿着%s/5件精炼至+4的装备",
    Description = "装备可在铁匠忽克连处进行精炼。提升精炼等级能够提升装备攻击或伤害减免属性，达到特定精炼等级后还会触发装备特效。",
    Difficult = 2,
    Goto = Table_NoviceTarget_t.Goto[35]
  },
  [160] = {
    id = 160,
    Sort = 4,
    Param = Table_NoviceTarget_t.Param[50],
    Reward = Table_NoviceTarget_t.Reward[147],
    Icon = "RuneM",
    Title = "符文大师",
    SubTitle = "解锁符文功能",
    Description = "前往「朱诺」通过飞空艇管理员「卡索斯」传送至「达纳托斯之塔」，完成任务「符文的力量」，解锁符文功能。",
    Goto = Table_NoviceTarget_t.Goto[56]
  },
  [161] = {
    id = 161,
    Sort = 5,
    TargetType = 77,
    TargetNum = 4,
    PreID = 160,
    Reward = Table_NoviceTarget_t.Reward[147],
    Icon = "RuneM",
    Title = "符文大师",
    SubTitle = "镶嵌至少%s/4个符文",
    Description = "打开背包并使用道具「符文之匣」，可以在其中镶嵌技能符文，并通过镶嵌满足要求的属性符文来激活技能符文，从而达到强化职业技能的作用。",
    GuideId = 301650001
  },
  [162] = {
    id = 162,
    Sort = 6,
    TargetType = 38,
    TargetNum = 12,
    Reward = Table_NoviceTarget_t.Reward[148],
    Icon = "equipment_enchant1",
    Title = "附魔奥秘",
    SubTitle = "任意装备附魔%s/12次",
    Description = "在吉芬的猫小友处消耗莫拉硬币即可附魔任意装备，更有机会获取稀有附魔属性哦",
    Practical = 3,
    Goto = Table_NoviceTarget_t.Goto[45]
  },
  [163] = {
    id = 163,
    Sort = 7,
    TargetType = 76,
    TargetNum = 25,
    Reward = Table_NoviceTarget_t.Reward[149],
    Icon = "Rune",
    IconScale = 0.9,
    Title = "神碑的启示",
    SubTitle = "激活特殊卢恩符文达%s/25个以上",
    Description = "在背包中找到并使用「阿萨神碑」即可开启神碑界面，消耗贡献点亮其中任意一个符文均可为自身属性提供少量增长，其中部分符文还需消耗金质勋章，这些特殊卢恩符文可以增强已有技能或带来相对更强的增益，记得优先升级哦！",
    Frequency = 1,
    GuideId = 301540001
  },
  [164] = {
    id = 164,
    Sort = 8,
    TargetType = 18,
    Param = Table_NoviceTarget_t.Param[57],
    TargetNum = 15,
    Reward = Table_NoviceTarget_t.Reward[150],
    IconScale = 0.9,
    Title = "荒境冒险",
    SubTitle = "累积完成荒境冒险任务%s/15个",
    Description = "尝试完成4个荒境冒险任务，可获得每日最终奖励，这是起源转职技能加点材料“时光流沙”的主要产出之一。",
    Practical = 3,
    Goto = Table_NoviceTarget_t.Goto[14]
  },
  [165] = {
    id = 165,
    Sort = 9,
    TargetType = 47,
    Desc = "pet_level，pet_likablity",
    Param = Table_NoviceTarget_t.Param[66],
    Reward = Table_NoviceTarget_t.Reward[151],
    Icon = "Pet",
    Title = "宠物情缘",
    SubTitle = "至少一只宠物好感度达到10以上",
    Description = "提升宠物好感度，使得宠物打工过程中可以更高效地获得奖励，并且多只好感度满级的宠物可以合成更高级的宠物。",
    Practical = 3,
    Difficult = 4,
    Message = "赠送宠物喜爱的宠物材料可以快速提升宠物的好感度，宠物材料可以通过交易所或消耗「七彩贝壳」购买"
  },
  [166] = {
    id = 166,
    Sort = 10,
    TargetType = 26,
    Param = Table_NoviceTarget_t.Param[67],
    Reward = Table_NoviceTarget_t.Reward[152],
    Icon = "calendar_statistics_icon_13",
    IconScale = 0.85,
    Title = "至高荣光",
    SubTitle = "通关达纳托斯之塔第一层",
    Description = "冒险者需以组成团队的方式进入达纳托斯之塔，达纳托斯之塔共分为四层，每层奖励单独结算。击杀第一层Boss女武神·拉斯格瑞丝即可完成该挑战",
    Difficult = 4,
    GuideId = 301580001
  },
  [167] = {
    id = 167,
    Sort = 11,
    TargetType = 8,
    Desc = "tower_layer",
    TargetNum = 15,
    Reward = Table_NoviceTarget_t.Reward[153],
    Icon = "Arena",
    SubTitle = "完成%s/15层勇者试炼塔",
    Description = "勇者试炼塔是冒险者个人专属的试炼之地，与守门人对话后，你将被传送进由魔法创造的虚拟空间与魔物战斗。",
    Practical = 3,
    Goto = Table_NoviceTarget_t.Goto[7]
  },
  [168] = {
    id = 168,
    Sort = 12,
    TargetType = 83,
    Param = Table_NoviceTarget_t.Param[68],
    Reward = Table_NoviceTarget_t.Reward[154],
    Icon = "raidbgicon_liexi06",
    IconScale = 0.85,
    Title = "护卫神树",
    SubTitle = "通关副本「神树守卫战」·冒险难度",
    Description = "在副本入口中找到对应关卡，选择挑战即可进入副本。如果有难度的话，可以与其他冒险者组队再试试哦~",
    Practical = 3,
    Difficult = 1,
    GuideId = 301600001
  },
  [169] = {
    id = 169,
    Day = 5,
    TargetType = 80,
    TargetNum = 130,
    Reward = Table_NoviceTarget_t.Reward[155],
    Icon = "forever",
    IconScale = 0.8,
    Title = "英雄的赞歌",
    SubTitle = "Base等级大于等于%s/130",
    Description = "提升Base等级是最基础的强化方式，也是解锁诸多功能和副本的前提，紧跟主线、挑战副本均是积攒Base经验的好方法。",
    Frequency = 1,
    Message = "多多挑战副本，参与活动等方式均可以快速积攒经验值"
  },
  [170] = {
    id = 170,
    Day = 5,
    Sort = 2,
    Param = Table_NoviceTarget_t.Param[69],
    Reward = Table_NoviceTarget_t.Reward[156],
    Icon = "reincarnation",
    IconScale = 0.9,
    Title = "荒境之谜",
    SubTitle = "完成荒境主线·失落的真相",
    Description = "完成荒境主线·失落的真相",
    Frequency = 1,
    Goto = Table_NoviceTarget_t.Goto[14]
  },
  [171] = {
    id = 171,
    Day = 5,
    Sort = 3,
    TargetType = 18,
    Param = Table_NoviceTarget_t.Param[57],
    TargetNum = 25,
    Reward = Table_NoviceTarget_t.Reward[157],
    IconScale = 0.9,
    Title = "荒境冒险",
    SubTitle = "累积完成荒境冒险任务%s/25个",
    Description = "尝试完成4个荒境冒险任务，可获得每日最终奖励，这是起源转职技能加点材料“时光流沙”的主要产出之一。",
    Practical = 3,
    Goto = Table_NoviceTarget_t.Goto[14]
  },
  [172] = {
    id = 172,
    Day = 5,
    Sort = 4,
    TargetType = 69,
    Param = Table_NoviceTarget_t.Param[70],
    Reward = Table_NoviceTarget_t.Reward[158],
    Icon = "ForgeSuccess",
    Title = "强化就是力量",
    SubTitle = "两件饰品栏强化等级均达到90以上",
    Description = "通过背包强化页面或者寻找铁匠忽克连对某个装备栏进行强化，强化装备栏可提升角色基础攻击和防御，强化等级上限跟随角色等级提升而提高。",
    Practical = 5,
    Difficult = 2,
    Frequency = 4,
    GuideId = 301510001
  },
  [173] = {
    id = 173,
    Day = 5,
    Sort = 5,
    TargetType = 81,
    Param = Table_NoviceTarget_t.Param[71],
    TargetNum = 15,
    Reward = Table_NoviceTarget_t.Reward[159],
    Icon = "ChNewYear",
    Title = "大收藏家",
    SubTitle = "存入的头饰数量达%s/15件以上",
    Description = "打开背包并选择任意一件头饰，点击道具详情界面中右上角的存入符号，即可将头饰存入进冒险手册中。存入的头饰即可以从冒险手册中再取出，也可以在幻化界面中用于幻化。\n头饰存入后可以获得对应的存入属性，也是提升自身属性的重要途径之一。",
    Message = "头饰可以通过完成蛋糕保卫战、交易所购买制作或微笑小姐商店购买制作等多种途径获取哦"
  },
  [174] = {
    id = 174,
    Day = 5,
    Sort = 6,
    TargetType = 72,
    Param = Table_NoviceTarget_t.Param[65],
    TargetNum = 7,
    Reward = Table_NoviceTarget_t.Reward[160],
    Icon = "refine_2",
    IconScale = 1.15,
    Title = "精炼之道",
    SubTitle = "至少穿着%s/7件精炼至+4的装备",
    Description = "装备可在铁匠忽克连处进行精炼。提升精炼等级能够提升装备攻击或伤害减免属性，达到特定精炼等级后还会触发装备特效。",
    Difficult = 2,
    Goto = Table_NoviceTarget_t.Goto[35]
  },
  [175] = {
    id = 175,
    Day = 5,
    Sort = 7,
    TargetType = 75,
    TargetNum = 2,
    Reward = Table_NoviceTarget_t.Reward[161],
    Icon = "equipment_drill1",
    Title = "魔卡勇者",
    SubTitle = "装备%s/2个及以上插有卡片的装备",
    Description = "打开背包并选择一件装备图标右下角处显示有卡槽的装备，点击「插卡」按钮，即可将卡片镶嵌至装备上。\n不同卡片具有不同效果，在有卡槽的装备上插入卡片能够进一步提升角色的战斗力。\n通过装备打洞，你可以开放装备上未打洞的卡槽，但往往需要消耗同款装备及Zeny。",
    Difficult = 2,
    Frequency = 2,
    Message = "在「包包」中找到一件有卡槽的装备插卡吧~"
  },
  [176] = {
    id = 176,
    Day = 5,
    Sort = 8,
    TargetType = 77,
    TargetNum = 7,
    Reward = Table_NoviceTarget_t.Reward[162],
    Icon = "RuneM",
    Title = "符文大师",
    SubTitle = "镶嵌至少%s/7个符文",
    Description = "打开背包并使用道具「符文之匣」，可以在其中镶嵌技能符文，并通过镶嵌满足要求的属性符文来激活技能符文，从而达到强化职业技能的作用。",
    GuideId = 301650001
  },
  [177] = {
    id = 177,
    Day = 5,
    Sort = 9,
    TargetType = 8,
    Desc = "tower_layer",
    TargetNum = 20,
    Reward = Table_NoviceTarget_t.Reward[163],
    Icon = "Arena",
    SubTitle = "完成%s/20层勇者试炼塔",
    Description = "勇者试炼塔是冒险者个人专属的试炼之地，与守门人对话后，你将被传送进由魔法创造的虚拟空间与魔物战斗。",
    Practical = 3,
    Goto = Table_NoviceTarget_t.Goto[7]
  },
  [178] = {
    id = 178,
    Day = 5,
    Sort = 10,
    TargetType = 27,
    TargetNum = 70,
    Reward = Table_NoviceTarget_t.Reward[164],
    Icon = "calendar_statistics_icon_09",
    IconScale = 0.9,
    Title = "超越极限",
    SubTitle = "完成恩德勒斯塔%s/70层",
    Description = "攀登恩德勒斯塔是勇气的证明，在塔中冒险者可击杀大量mvp和mini怪物，收获经验、材料和装备。爬塔层数越高，收获奖励越多。",
    Difficult = 4,
    GuideId = 301550001
  },
  [179] = {
    id = 179,
    Day = 5,
    Sort = 11,
    TargetType = 87,
    TargetNum = 1,
    Reward = Table_NoviceTarget_t.Reward[165],
    Icon = "calendar_statistics_icon_14",
    Title = "炼狱斗士",
    SubTitle = "亡者副本中参与击杀%s/1个Boss以上",
    Description = "在副本入口中找到「尼夫海姆炼狱」，选择挑战即可进入副本。如果有难度的话，可以与其他冒险者组队再试试哦~",
    Difficult = 4,
    GuideId = 301590001
  },
  [180] = {
    id = 180,
    Day = 5,
    Sort = 12,
    TargetType = 86,
    TargetNum = 10,
    Reward = Table_NoviceTarget_t.Reward[166],
    Icon = "headwear",
    IconScale = 0.9,
    Title = "保卫蛋糕！",
    SubTitle = "参与蛋糕保卫战并防守住%s/10波以上",
    Description = "完成蛋糕保卫战可以收集「白雪棉花糖」和「星星草莓」，二者收集到一定数量后即可在蛋糕商店中兑换各式图纸，是头饰与卡片的重要来源之一哦~",
    Practical = 3,
    GuideId = 301560001
  },
  [181] = {
    id = 181,
    Day = 6,
    TargetType = 69,
    Param = Table_NoviceTarget_t.Param[72],
    Reward = Table_NoviceTarget_t.Reward[167],
    Icon = "ForgeSuccess",
    Title = "强化就是力量",
    SubTitle = "武器栏强化等级达到130及以上",
    Description = "通过背包强化页面或者寻找铁匠忽克连对某个装备栏进行强化，强化装备栏可提升角色基础攻击和防御，强化等级上限跟随角色等级提升而提高。",
    Practical = 5,
    Difficult = 2,
    Frequency = 4,
    GuideId = 301500001
  },
  [182] = {
    id = 182,
    Day = 6,
    Sort = 2,
    TargetType = 15,
    Desc = "skill_count",
    TargetNum = 30,
    Reward = Table_NoviceTarget_t.Reward[168],
    Icon = "Skill",
    Title = "起源之力",
    SubTitle = "升级%s/30次四转的技能树",
    Description = "打开「更多」中的「技能」界面，选择上方「起源技能」页签，即可使用「时之流沙」强化四转职业技能。",
    Difficult = 2,
    GuideId = 301530001
  },
  [183] = {
    id = 183,
    Day = 6,
    Sort = 3,
    TargetType = 73,
    Param = Table_NoviceTarget_t.Param[73],
    Reward = Table_NoviceTarget_t.Reward[169],
    Icon = "equipment_enchant1",
    Title = "魔法满身",
    SubTitle = "装备12个拥有附魔属性的装备",
    Description = "在吉芬的猫小友处消耗莫拉硬币即可附魔任意装备，更有机会获取稀有附魔属性哦",
    Practical = 3,
    Goto = Table_NoviceTarget_t.Goto[45]
  },
  [184] = {
    id = 184,
    Day = 6,
    Sort = 4,
    TargetType = 76,
    TargetNum = 35,
    Reward = Table_NoviceTarget_t.Reward[170],
    Icon = "Rune",
    IconScale = 0.9,
    Title = "神碑的启示",
    SubTitle = "激活特殊卢恩符文达%s/35个以上",
    Description = "在背包中找到并使用「阿萨神碑」即可开启神碑界面，消耗贡献点亮其中任意一个符文均可为自身属性提供少量增长，其中部分符文还需消耗金质勋章，这些特殊卢恩符文可以增强已有技能或带来相对更强的增益，记得优先升级哦！",
    Frequency = 1,
    GuideId = 301540001
  },
  [185] = {
    id = 185,
    Day = 6,
    Sort = 5,
    TargetType = 49,
    Desc = "bless_count",
    Param = Table_NoviceTarget_t.Param[60],
    TargetNum = 150,
    Reward = Table_NoviceTarget_t.Reward[171],
    Icon = "blessing_4",
    Title = "女神祈祷",
    SubTitle = "使用公会女神祈祷%s/150次",
    Description = "与公会内的瓦尔基里对话，选择「祈祷」后挑选适合自己的属性，消耗贡献升级即可获得角色属性提升。",
    Difficult = 2,
    Goto = Table_NoviceTarget_t.Goto[53]
  },
  [186] = {
    id = 186,
    Day = 6,
    Sort = 6,
    TargetType = 89,
    Desc = "techtree_count",
    TargetNum = 14,
    Reward = Table_NoviceTarget_t.Reward[172],
    Icon = "huangjingshenshu2",
    IconScale = 0.9,
    Title = "神树的庇护",
    SubTitle = "至少激活%s/14点神树之灵",
    Description = "在荒境「神树之灵」界面上，尝试激活任意1个节点。\n所需材料可通过完成荒境冒险任务或击杀荒境魔物获得。",
    Goto = Table_NoviceTarget_t.Goto[19]
  },
  [187] = {
    id = 187,
    Day = 6,
    Sort = 7,
    TargetType = 81,
    Param = Table_NoviceTarget_t.Param[74],
    TargetNum = 10,
    Reward = Table_NoviceTarget_t.Reward[173],
    Icon = "item_3667",
    Title = "大收藏家",
    SubTitle = "存入的卡片数量达%s/10件以上",
    Description = "打开背包并选择任意一张卡片，点击道具详情界面中右上角的存入符号，即可将卡片存入进冒险手册中，存入的卡片还可以从冒险手册中再取出。\n卡片存入后可以获得对应的存入属性，也是提升自身属性的重要途径之一。",
    Message = "卡片可以通过完成蛋糕保卫战、交易所购买、野外挂机或每周通关神谕副本等多种途径获取哦"
  },
  [188] = {
    id = 188,
    Day = 6,
    Sort = 8,
    TargetType = 83,
    Param = Table_NoviceTarget_t.Param[75],
    Reward = Table_NoviceTarget_t.Reward[174],
    Icon = "raidbgicon_liexi07",
    IconScale = 0.85,
    Title = "无惧恶灵",
    SubTitle = "通关副本「再见，故友！」·冒险难度",
    Description = "在副本入口中找到对应关卡，选择挑战即可进入副本。如果有难度的话，可以与其他冒险者组队再试试哦~",
    Practical = 3,
    Difficult = 1,
    GuideId = 301610001
  },
  [189] = {
    id = 189,
    Day = 6,
    Sort = 9,
    TargetType = 88,
    TargetNum = 10,
    Reward = Table_NoviceTarget_t.Reward[175],
    Icon = "act_pve",
    Title = "秘境探险家",
    SubTitle = "无限回廊通过%s/10层以上",
    Description = "在副本入口中找到「无限回廊」，选择挑战即可进入副本。通关无限回廊可以积攒「勇者圣徽」，用以兑换「起源之书」、「萃光结晶」等稀有道具。如果有难度的话，可以与其他冒险者组队再试试哦~",
    Practical = 2,
    Difficult = 2,
    Frequency = 2,
    GuideId = 301620001
  },
  [190] = {
    id = 190,
    Day = 6,
    Sort = 10,
    TargetType = 8,
    Desc = "tower_layer",
    TargetNum = 25,
    Reward = Table_NoviceTarget_t.Reward[176],
    Icon = "Arena",
    SubTitle = "完成%s/25层勇者试炼塔",
    Description = "勇者试炼塔是冒险者个人专属的试炼之地，与守门人对话后，你将被传送进由魔法创造的虚拟空间与魔物战斗。",
    Practical = 3,
    Goto = Table_NoviceTarget_t.Goto[7]
  },
  [191] = {
    id = 191,
    Day = 6,
    Sort = 11,
    TargetType = 26,
    Param = Table_NoviceTarget_t.Param[76],
    Reward = Table_NoviceTarget_t.Reward[177],
    Icon = "calendar_statistics_icon_13",
    IconScale = 0.85,
    Title = "奥术震荡",
    SubTitle = "通关达纳托斯之塔第二层",
    Description = "冒险者需以组成团队的方式进入达纳托斯之塔，达纳托斯之塔共分为四层，每层奖励单独结算。击杀第二层Boss奥术魔方即可完成该挑战",
    Difficult = 4,
    GuideId = 301580001
  },
  [192] = {
    id = 192,
    Day = 7,
    TargetType = 15,
    Desc = "skill_count",
    TargetNum = 40,
    Reward = Table_NoviceTarget_t.Reward[178],
    Icon = "Skill",
    Title = "起源之力",
    SubTitle = "升级%s/40次四转的技能树",
    Description = "打开「更多」中的「技能」界面，选择上方「起源技能」页签，即可使用「时之流沙」强化四转职业技能。",
    Difficult = 2,
    Goto = Table_NoviceTarget_t.Goto[60],
    GuideId = 301530001
  },
  [193] = {
    id = 193,
    Day = 7,
    Sort = 2,
    TargetType = 18,
    Param = Table_NoviceTarget_t.Param[57],
    TargetNum = 40,
    Reward = Table_NoviceTarget_t.Reward[179],
    IconScale = 0.9,
    Title = "荒境冒险",
    SubTitle = "累积完成荒境冒险任务%s/40个",
    Description = "尝试完成4个荒境冒险任务，可获得每日最终奖励，这是起源转职技能加点材料“时光流沙”的主要产出之一。",
    Practical = 3,
    Goto = Table_NoviceTarget_t.Goto[14]
  },
  [194] = {
    id = 194,
    Day = 7,
    Sort = 3,
    TargetType = 79,
    Param = Table_NoviceTarget_t.Param[77],
    TargetNum = 2,
    Reward = Table_NoviceTarget_t.Reward[180],
    Icon = "RuneM",
    Title = "符文大师",
    SubTitle = "镶嵌至少%s/2个A级以上的技能符文",
    Description = "打开背包并使用道具「符文之匣」，可以在其中镶嵌技能符文，并通过镶嵌满足要求的属性符文来激活技能符文，从而达到强化职业技能的作用。",
    GuideId = 301650001
  },
  [195] = {
    id = 195,
    Day = 7,
    Sort = 4,
    TargetType = 92,
    TargetNum = 1,
    Reward = Table_NoviceTarget_t.Reward[181],
    Icon = "RuneM",
    Title = "符文大师",
    SubTitle = "激活至少%s/1个技能符文",
    Description = "打开背包并使用道具「符文之匣」，可以在其中镶嵌技能符文，并通过镶嵌满足要求的属性符文来激活技能符文，从而达到强化职业技能的作用。",
    GuideId = 301650001
  },
  [196] = {
    id = 196,
    Day = 7,
    Sort = 5,
    TargetType = 75,
    TargetNum = 3,
    Reward = Table_NoviceTarget_t.Reward[182],
    Icon = "equipment_drill1",
    Title = "魔卡勇者",
    SubTitle = "装备%s/3个及以上插有卡片的装备",
    Description = "打开背包并选择一件装备图标右下角处显示有卡槽的装备，点击「插卡」按钮，即可将卡片镶嵌至装备上。\n不同卡片具有不同效果，在有卡槽的装备上插入卡片能够进一步提升角色的战斗力。\n通过装备打洞，你可以开放装备上未打洞的卡槽，但往往需要消耗同款装备及Zeny。",
    Difficult = 2,
    Frequency = 2,
    Message = "在「包包」中找到一件有卡槽的装备插卡吧~"
  },
  [197] = {
    id = 197,
    Day = 7,
    Sort = 6,
    TargetType = 72,
    Param = Table_NoviceTarget_t.Param[78],
    TargetNum = 3,
    Reward = Table_NoviceTarget_t.Reward[183],
    Icon = "refine_2",
    IconScale = 1.15,
    Title = "精炼之道",
    SubTitle = "至少穿着%s/3件精炼至+6的装备",
    Description = "装备可在铁匠忽克连处进行精炼。提升精炼等级能够提升装备攻击或伤害减免属性，达到特定精炼等级后还会触发装备特效。",
    Difficult = 2,
    Goto = Table_NoviceTarget_t.Goto[35]
  },
  [198] = {
    id = 198,
    Day = 7,
    Sort = 7,
    TargetType = 80,
    TargetNum = 138,
    Reward = Table_NoviceTarget_t.Reward[184],
    Icon = "forever",
    IconScale = 0.8,
    Title = "英雄的赞歌",
    SubTitle = "Base等级大于等于%s/138",
    Description = "提升Base等级是最基础的强化方式，也是解锁诸多功能和副本的前提，紧跟主线、挑战副本均是积攒Base经验的好方法。",
    Frequency = 1,
    Message = "多多挑战副本，参与活动等方式均可以快速积攒经验值"
  },
  [199] = {
    id = 199,
    Day = 7,
    Sort = 8,
    TargetType = 27,
    TargetNum = 85,
    Reward = Table_NoviceTarget_t.Reward[185],
    Icon = "calendar_statistics_icon_09",
    IconScale = 0.9,
    Title = "超越极限",
    SubTitle = "完成恩德勒斯塔%s/85层",
    Description = "攀登恩德勒斯塔是勇气的证明，在塔中冒险者可击杀大量mvp和mini怪物，收获经验、材料和装备。爬塔层数越高，收获奖励越多。",
    Difficult = 4,
    GuideId = 301550001
  },
  [200] = {
    id = 200,
    Day = 7,
    Sort = 9,
    TargetType = 90,
    Param = Table_NoviceTarget_t.Param[79],
    TargetNum = 1,
    Reward = Table_NoviceTarget_t.Reward[186],
    Icon = "cardraid",
    Title = "幻想马戏团",
    SubTitle = "通关神谕副本冒险难度一次",
    Description = "与普隆德拉的幻象马戏团成员对话，或直接从队伍界面进入神谕副本。挑战成功可获得镶嵌用的卡片。",
    Practical = 3,
    Difficult = 4,
    Frequency = 2,
    GuideId = 301570001
  },
  [201] = {
    id = 201,
    Day = 7,
    Sort = 10,
    TargetType = 84,
    Param = Table_NoviceTarget_t.Param[80],
    TargetNum = 3,
    Reward = Table_NoviceTarget_t.Reward[187],
    Icon = "raidbgicon_liexi06",
    IconScale = 0.85,
    Title = "神树守卫者",
    SubTitle = "达成副本「神树守卫战」三星成就",
    Description = "在副本入口中找到对应关卡，选择挑战即可进入副本。如果有难度的话，可以与其他冒险者组队再试试哦~",
    Practical = 3,
    Difficult = 1,
    GuideId = 301630001
  },
  [202] = {
    id = 202,
    Day = 7,
    Sort = 11,
    TargetType = 8,
    Desc = "tower_layer",
    TargetNum = 30,
    Reward = Table_NoviceTarget_t.Reward[188],
    Icon = "Arena",
    SubTitle = "完成%s/30层勇者试炼塔",
    Description = "勇者试炼塔是冒险者个人专属的试炼之地，与守门人对话后，你将被传送进由魔法创造的虚拟空间与魔物战斗。",
    Practical = 3,
    Goto = Table_NoviceTarget_t.Goto[7]
  },
  [203] = {
    id = 203,
    Day = 8,
    TargetType = 70,
    Param = Table_NoviceTarget_t.Param[81],
    TargetNum = 3,
    Reward = Table_NoviceTarget_t.Reward[189],
    Icon = "ForgeSuccess",
    Title = "强化就是力量",
    SubTitle = "至少3个装备栏强化等级达130及以上",
    Description = "通过背包强化页面或者寻找铁匠忽克连对某个装备栏进行强化，强化装备栏可提升角色基础攻击和防御，强化等级上限跟随角色等级提升而提高。",
    Practical = 5,
    Difficult = 2,
    Frequency = 4,
    GuideId = 301510001
  },
  [204] = {
    id = 204,
    Day = 8,
    Sort = 2,
    TargetType = 76,
    TargetNum = 45,
    Reward = Table_NoviceTarget_t.Reward[190],
    Icon = "Rune",
    IconScale = 0.9,
    Title = "神碑的启示",
    SubTitle = "激活特殊卢恩符文达%s/45个以上",
    Description = "在背包中找到并使用「阿萨神碑」即可开启神碑界面，消耗贡献点亮其中任意一个符文均可为自身属性提供少量增长，其中部分符文还需消耗金质勋章，这些特殊卢恩符文可以增强已有技能或带来相对更强的增益，记得优先升级哦！",
    Frequency = 1,
    GuideId = 301540001
  },
  [205] = {
    id = 205,
    Day = 8,
    Sort = 3,
    TargetType = 49,
    Desc = "bless_count",
    Param = Table_NoviceTarget_t.Param[60],
    TargetNum = 250,
    Reward = Table_NoviceTarget_t.Reward[191],
    Icon = "blessing_4",
    Title = "女神祈祷",
    SubTitle = "使用公会女神祈祷%s/250次",
    Description = "与公会内的瓦尔基里对话，选择「祈祷」后挑选适合自己的属性，消耗贡献升级即可获得角色属性提升。",
    Difficult = 2,
    Goto = Table_NoviceTarget_t.Goto[53]
  },
  [206] = {
    id = 206,
    Day = 8,
    Sort = 4,
    TargetType = 81,
    Param = Table_NoviceTarget_t.Param[71],
    TargetNum = 20,
    Reward = Table_NoviceTarget_t.Reward[192],
    Icon = "ChNewYear",
    Title = "大收藏家",
    SubTitle = "存入的头饰数量达%s/20件以上",
    Description = "打开背包并选择任意一件头饰，点击道具详情界面中右上角的存入符号，即可将头饰存入进冒险手册中。存入的头饰即可以从冒险手册中再取出，也可以在幻化界面中用于幻化。\n头饰存入后可以获得对应的存入属性，也是提升自身属性的重要途径之一。",
    Message = "头饰可以通过完成蛋糕保卫战、交易所购买制作或微笑小姐商店购买制作等多种途径获取哦"
  },
  [207] = {
    id = 207,
    Day = 8,
    Sort = 5,
    TargetType = 38,
    TargetNum = 30,
    Reward = Table_NoviceTarget_t.Reward[193],
    Icon = "equipment_enchant1",
    Title = "附魔奥秘",
    SubTitle = "任意装备附魔%s/30次",
    Description = "在吉芬的猫小友处消耗莫拉硬币即可附魔任意装备，更有机会获取稀有附魔属性哦",
    Practical = 3,
    Goto = Table_NoviceTarget_t.Goto[45]
  },
  [208] = {
    id = 208,
    Day = 8,
    Sort = 6,
    TargetType = 89,
    Desc = "techtree_count",
    TargetNum = 18,
    Reward = Table_NoviceTarget_t.Reward[194],
    Icon = "huangjingshenshu2",
    IconScale = 0.9,
    Title = "神树的庇护",
    SubTitle = "至少激活%s/18点神树之灵",
    Description = "在荒境「神树之灵」界面上，尝试激活任意1个节点。\n所需材料可通过完成荒境冒险任务或击杀荒境魔物获得。",
    Goto = Table_NoviceTarget_t.Goto[19]
  },
  [209] = {
    id = 209,
    Day = 8,
    Sort = 7,
    Param = Table_NoviceTarget_t.Param[82],
    Reward = Table_NoviceTarget_t.Reward[195],
    Icon = "reincarnation",
    IconScale = 0.9,
    Title = "荒境之谜",
    SubTitle = "完成荒境主线·溯逆的时光",
    Description = "完成荒境主线·溯逆的时光",
    Frequency = 1,
    Goto = Table_NoviceTarget_t.Goto[14]
  },
  [210] = {
    id = 210,
    Day = 8,
    Sort = 8,
    TargetType = 72,
    Param = Table_NoviceTarget_t.Param[78],
    TargetNum = 5,
    Reward = Table_NoviceTarget_t.Reward[196],
    Icon = "refine_2",
    IconScale = 1.15,
    Title = "精炼之道",
    SubTitle = "至少穿着%s/5件精炼至+6的装备",
    Description = "装备可在铁匠忽克连处进行精炼。提升精炼等级能够提升装备攻击或伤害减免属性，达到特定精炼等级后还会触发装备特效。",
    Difficult = 2,
    Goto = Table_NoviceTarget_t.Goto[35]
  },
  [211] = {
    id = 211,
    Day = 8,
    Sort = 9,
    TargetType = 65,
    Desc = "count",
    TargetNum = 5,
    Reward = Table_NoviceTarget_t.Reward[197],
    Icon = "Dungeon",
    Title = "遗迹探险",
    SubTitle = "进入遗迹并至少击杀MVP/Mini%s/5次",
    Description = "与公会中的英灵军需官特莫里斯对话，进入公会副本击杀稀有魔物，获得经验和奖励。需要在一周内累计击杀5只不同的Mini或Mvp才能完成此任务，否则下周进度就会重置哦！",
    Difficult = 4,
    Goto = Table_NoviceTarget_t.Goto[61]
  },
  [212] = {
    id = 212,
    Day = 8,
    Sort = 10,
    TargetType = 87,
    TargetNum = 3,
    Reward = Table_NoviceTarget_t.Reward[198],
    Icon = "calendar_statistics_icon_14",
    Title = "炼狱斗士",
    SubTitle = "亡者副本中参与击杀%s/3个Boss以上",
    Description = "在副本入口中找到「尼夫海姆炼狱」，选择挑战即可进入副本。如果有难度的话，可以与其他冒险者组队再试试哦~",
    Difficult = 4,
    GuideId = 301590001
  },
  [213] = {
    id = 213,
    Day = 8,
    Sort = 11,
    TargetType = 88,
    TargetNum = 20,
    Reward = Table_NoviceTarget_t.Reward[199],
    Icon = "act_pve",
    Title = "秘境探险家",
    SubTitle = "无限回廊通过%s/20层以上",
    Description = "在副本入口中找到「无限回廊」，选择挑战即可进入副本。通关无限回廊可以积攒「勇者圣徽」，用以兑换「起源之书」、「萃光结晶」等稀有道具。如果有难度的话，可以与其他冒险者组队再试试哦~",
    Practical = 2,
    Difficult = 2,
    Frequency = 2,
    GuideId = 301620001
  },
  [214] = {
    id = 214,
    Day = 9,
    TargetType = 72,
    Param = Table_NoviceTarget_t.Param[78],
    TargetNum = 7,
    Reward = Table_NoviceTarget_t.Reward[200],
    Icon = "refine_2",
    IconScale = 1.15,
    Title = "精炼之道",
    SubTitle = "至少穿着%s/7件精炼至+6的装备",
    Description = "装备可在铁匠忽克连处进行精炼。提升精炼等级能够提升装备攻击或伤害减免属性，达到特定精炼等级后还会触发装备特效。",
    Difficult = 2,
    Goto = Table_NoviceTarget_t.Goto[35]
  },
  [215] = {
    id = 215,
    Day = 9,
    Sort = 2,
    TargetType = 15,
    Desc = "skill_count",
    TargetNum = 60,
    Reward = Table_NoviceTarget_t.Reward[201],
    Icon = "Skill",
    Title = "起源之力",
    SubTitle = "升级%s/60次四转的技能树",
    Description = "打开「更多」中的「技能」界面，选择上方「起源技能」页签，即可使用「时之流沙」强化四转职业技能。",
    Difficult = 2,
    GuideId = 301530001
  },
  [216] = {
    id = 216,
    Day = 9,
    Sort = 3,
    TargetType = 75,
    TargetNum = 5,
    Reward = Table_NoviceTarget_t.Reward[202],
    Icon = "equipment_drill1",
    Title = "魔卡勇者",
    SubTitle = "装备%s/5个及以上插有卡片的装备",
    Description = "打开背包并选择一件装备图标右下角处显示有卡槽的装备，点击「插卡」按钮，即可将卡片镶嵌至装备上。\n不同卡片具有不同效果，在有卡槽的装备上插入卡片能够进一步提升角色的战斗力。\n通过装备打洞，你可以开放装备上未打洞的卡槽，但往往需要消耗同款装备及Zeny。",
    Difficult = 2,
    Frequency = 2,
    Message = "在「包包」中找到一件有卡槽的装备插卡吧~"
  },
  [217] = {
    id = 217,
    Day = 9,
    Sort = 4,
    TargetType = 81,
    Param = Table_NoviceTarget_t.Param[74],
    TargetNum = 20,
    Reward = Table_NoviceTarget_t.Reward[203],
    Icon = "item_3667",
    Title = "大收藏家",
    SubTitle = "存入的卡片数量达%s/20件以上",
    Description = "打开背包并选择任意一张卡片，点击道具详情界面中右上角的存入符号，即可将卡片存入进冒险手册中，存入的卡片还可以从冒险手册中再取出。\n卡片存入后可以获得对应的存入属性，也是提升自身属性的重要途径之一。",
    Message = "卡片可以通过完成蛋糕保卫战、交易所购买、野外挂机或每周通关神谕副本等多种途径获取哦"
  },
  [218] = {
    id = 218,
    Day = 9,
    Sort = 5,
    TargetType = 92,
    TargetNum = 3,
    Reward = Table_NoviceTarget_t.Reward[204],
    Icon = "RuneM",
    Title = "符文大师",
    SubTitle = "激活至少%s/3个技能符文",
    Description = "打开背包并使用道具「符文之匣」，可以在其中镶嵌技能符文，并通过镶嵌满足要求的属性符文来激活技能符文，从而达到强化职业技能的作用。",
    GuideId = 301650001
  },
  [219] = {
    id = 219,
    Day = 9,
    Sort = 6,
    TargetType = 78,
    Param = Table_NoviceTarget_t.Param[83],
    TargetNum = 2,
    Reward = Table_NoviceTarget_t.Reward[205],
    Icon = "RuneM",
    Title = "符文大师",
    SubTitle = "镶嵌至少%s/2个lv.5以上的属性符文",
    Description = "打开背包并使用道具「符文之匣」，可以在其中镶嵌技能符文，并通过镶嵌满足要求的属性符文来激活技能符文，从而达到强化职业技能的作用。",
    GuideId = 301650001
  },
  [220] = {
    id = 220,
    Day = 9,
    Sort = 7,
    TargetType = 89,
    Desc = "techtree_count",
    TargetNum = 25,
    Reward = Table_NoviceTarget_t.Reward[206],
    Icon = "huangjingshenshu2",
    IconScale = 0.9,
    Title = "神树的庇护",
    SubTitle = "至少激活%s/25点神树之灵",
    Description = "在荒境「神树之灵」界面上，尝试激活任意1个节点。\n所需材料可通过完成荒境冒险任务或击杀荒境魔物获得。",
    Goto = Table_NoviceTarget_t.Goto[19]
  },
  [221] = {
    id = 221,
    Day = 9,
    Sort = 8,
    TargetType = 26,
    Param = Table_NoviceTarget_t.Param[84],
    Reward = Table_NoviceTarget_t.Reward[207],
    Icon = "calendar_statistics_icon_13",
    IconScale = 0.85,
    Title = "绝望中的希望",
    SubTitle = "通关达纳托斯之塔第三层",
    Description = "冒险者需以组成团队的方式进入达纳托斯之塔，达纳托斯之塔共分为四层，每层奖励单独结算。击杀第三层Boss悲哀聚合体和苦恼聚合体即可完成该挑战",
    Difficult = 4,
    GuideId = 301580001
  },
  [222] = {
    id = 222,
    Day = 9,
    Sort = 9,
    TargetType = 8,
    Desc = "tower_layer",
    TargetNum = 40,
    Reward = Table_NoviceTarget_t.Reward[208],
    Icon = "Arena",
    SubTitle = "完成%s/40层勇者试炼塔",
    Description = "勇者试炼塔是冒险者个人专属的试炼之地，与守门人对话后，你将被传送进由魔法创造的虚拟空间与魔物战斗。",
    Practical = 3,
    Goto = Table_NoviceTarget_t.Goto[7]
  },
  [223] = {
    id = 223,
    Day = 9,
    Sort = 10,
    TargetType = 84,
    Param = Table_NoviceTarget_t.Param[85],
    TargetNum = 3,
    Reward = Table_NoviceTarget_t.Reward[209],
    Icon = "raidbgicon_liexi07",
    IconScale = 0.85,
    Title = "恶灵猎人",
    SubTitle = "达成副本「再见，故友！」三星成就",
    Description = "在副本入口中找到对应关卡，选择挑战即可进入副本。如果有难度的话，可以与其他冒险者组队再试试哦~",
    Practical = 3,
    Difficult = 1,
    GuideId = 301660001
  },
  [224] = {
    id = 224,
    Day = 9,
    Sort = 11,
    TargetType = 27,
    TargetNum = 100,
    Reward = Table_NoviceTarget_t.Reward[210],
    Icon = "calendar_statistics_icon_09",
    IconScale = 0.9,
    Title = "超越极限",
    SubTitle = "完成恩德勒斯塔%s/100层",
    Description = "攀登恩德勒斯塔是勇气的证明，在塔中冒险者可击杀大量mvp和mini怪物，收获经验、材料和装备。爬塔层数越高，收获奖励越多。",
    Difficult = 4,
    GuideId = 301550001
  },
  [225] = {
    id = 225,
    Day = 10,
    TargetType = 15,
    Desc = "skill_count",
    TargetNum = 70,
    Reward = Table_NoviceTarget_t.Reward[211],
    Icon = "Skill",
    Title = "起源之力",
    SubTitle = "升级%s/70次四转的技能树",
    Description = "打开「更多」中的「技能」界面，选择上方「起源技能」页签，即可使用「时之流沙」强化四转职业技能。",
    Difficult = 2,
    GuideId = 301530001
  },
  [226] = {
    id = 226,
    Day = 10,
    Sort = 2,
    TargetType = 89,
    Desc = "techtree_count",
    TargetNum = 30,
    Reward = Table_NoviceTarget_t.Reward[212],
    Icon = "huangjingshenshu2",
    IconScale = 0.9,
    Title = "神树的庇护",
    SubTitle = "至少激活%s/30点神树之灵",
    Description = "在荒境「神树之灵」界面上，尝试激活任意1个节点。\n所需材料可通过完成荒境冒险任务或击杀荒境魔物获得。",
    Goto = Table_NoviceTarget_t.Goto[19]
  },
  [227] = {
    id = 227,
    Day = 10,
    Sort = 3,
    TargetType = 72,
    Param = Table_NoviceTarget_t.Param[86],
    TargetNum = 2,
    Reward = Table_NoviceTarget_t.Reward[213],
    Icon = "refine_2",
    IconScale = 1.15,
    Title = "精炼之道",
    SubTitle = "至少穿着%s/2件精炼至+8的装备",
    Description = "装备可在铁匠忽克连处进行精炼。提升精炼等级能够提升装备攻击或伤害减免属性，达到特定精炼等级后还会触发装备特效。",
    Difficult = 2,
    Goto = Table_NoviceTarget_t.Goto[35]
  },
  [228] = {
    id = 228,
    Day = 10,
    Sort = 4,
    TargetType = 79,
    Param = Table_NoviceTarget_t.Param[87],
    TargetNum = 2,
    Reward = Table_NoviceTarget_t.Reward[214],
    Icon = "RuneM",
    Title = "符文大师",
    SubTitle = "镶嵌至少%s/2个S级以上的技能符文",
    Description = "打开背包并使用道具「符文之匣」，可以在其中镶嵌技能符文，并通过镶嵌满足要求的属性符文来激活技能符文，从而达到强化职业技能的作用。",
    GuideId = 301650001
  },
  [229] = {
    id = 229,
    Day = 10,
    Sort = 5,
    TargetType = 80,
    TargetNum = 153,
    Reward = Table_NoviceTarget_t.Reward[215],
    Icon = "forever",
    IconScale = 0.8,
    Title = "英雄的赞歌",
    SubTitle = "Base等级大于等于%s/153",
    Description = "提升Base等级是最基础的强化方式，也是解锁诸多功能和副本的前提，紧跟主线、挑战副本均是积攒Base经验的好方法。",
    Frequency = 1,
    Message = "多多挑战副本，参与活动等方式均可以快速积攒经验值"
  },
  [230] = {
    id = 230,
    Day = 10,
    Sort = 6,
    TargetType = 76,
    TargetNum = 60,
    Reward = Table_NoviceTarget_t.Reward[216],
    Icon = "Rune",
    IconScale = 0.9,
    Title = "神碑的启示",
    SubTitle = "激活特殊卢恩符文达%s/60个以上",
    Description = "在背包中找到并使用「阿萨神碑」即可开启神碑界面，消耗贡献点亮其中任意一个符文均可为自身属性提供少量增长，其中部分符文还需消耗金质勋章，这些特殊卢恩符文可以增强已有技能或带来相对更强的增益，记得优先升级哦！",
    Frequency = 1,
    GuideId = 301540001
  },
  [231] = {
    id = 231,
    Day = 10,
    Sort = 7,
    TargetType = 81,
    Param = Table_NoviceTarget_t.Param[71],
    TargetNum = 25,
    Reward = Table_NoviceTarget_t.Reward[217],
    Icon = "ChNewYear",
    Title = "大收藏家",
    SubTitle = "存入的头饰数量达%s/25件以上",
    Description = "打开背包并选择任意一件头饰，点击道具详情界面中右上角的存入符号，即可将头饰存入进冒险手册中。存入的头饰即可以从冒险手册中再取出，也可以在幻化界面中用于幻化。\n头饰存入后可以获得对应的存入属性，也是提升自身属性的重要途径之一。",
    Message = "头饰可以通过完成蛋糕保卫战、交易所购买制作或微笑小姐商店购买制作等多种途径获取哦"
  },
  [232] = {
    id = 232,
    Day = 10,
    Sort = 8,
    TargetType = 38,
    TargetNum = 50,
    Reward = Table_NoviceTarget_t.Reward[218],
    Icon = "equipment_enchant1",
    Title = "附魔奥秘",
    SubTitle = "任意装备附魔%s/50次",
    Description = "在吉芬的猫小友处消耗莫拉硬币即可附魔任意装备，更有机会获取稀有附魔属性哦",
    Practical = 3,
    Goto = Table_NoviceTarget_t.Goto[45]
  },
  [233] = {
    id = 233,
    Day = 10,
    Sort = 9,
    TargetType = 84,
    Param = Table_NoviceTarget_t.Param[88],
    TargetNum = 3,
    Reward = Table_NoviceTarget_t.Reward[219],
    Icon = "raidbgicon_liexi08",
    IconScale = 0.85,
    Title = "无情的毕尤杀手",
    SubTitle = "达成副本「彼岸的决战」三星成就",
    Description = "在副本入口中找到对应关卡，选择挑战即可进入副本。如果有难度的话，可以与其他冒险者组队再试试哦~",
    Practical = 3,
    Difficult = 1,
    GuideId = 301640001
  },
  [234] = {
    id = 234,
    Day = 10,
    Sort = 10,
    TargetType = 90,
    Param = Table_NoviceTarget_t.Param[89],
    TargetNum = 1,
    Reward = Table_NoviceTarget_t.Reward[220],
    Icon = "cardraid",
    Title = "幻想马戏团",
    SubTitle = "通关神谕副本地狱难度一次",
    Description = "与普隆德拉的幻象马戏团成员对话，或直接从队伍界面进入神谕副本。挑战成功可获得镶嵌用的卡片。",
    Practical = 3,
    Difficult = 4,
    Frequency = 2,
    GuideId = 301540001
  },
  [235] = {
    id = 235,
    Day = 10,
    Sort = 11,
    TargetType = 88,
    TargetNum = 30,
    Reward = Table_NoviceTarget_t.Reward[221],
    Icon = "act_pve",
    Title = "秘境探险家",
    SubTitle = "无限回廊通过%s/30层以上",
    Description = "在副本入口中找到「无限回廊」，选择挑战即可进入副本。通关无限回廊可以积攒「勇者圣徽」，用以兑换「起源之书」、「萃光结晶」等稀有道具。如果有难度的话，可以与其他冒险者组队再试试哦~",
    Practical = 2,
    Difficult = 2,
    Frequency = 2,
    GuideId = 301620001
  },
  [236] = {
    id = 236,
    Day = 10,
    Sort = 12,
    TargetType = 83,
    Param = Table_NoviceTarget_t.Param[90],
    Reward = Table_NoviceTarget_t.Reward[222],
    Icon = "calendar_statistics_icon_15",
    IconScale = 0.9,
    Title = "冒险的起点",
    SubTitle = "通关一次初心难度波纳佩博物岛",
    Description = "在副本入口中找到对应关卡，选择挑战即可进入副本。如果有难度的话，可以与其他冒险者组队再试试哦~",
    Practical = 3,
    Difficult = 1,
    GuideId = 301670001
  }
}
local cell_mt = {
  __index = {
    Day = 4,
    Desc = "",
    Description = "保持签到好习惯，每天上线领奖励。",
    Difficult = 3,
    Frequency = 3,
    GM = _EmptyTable,
    Goto = _EmptyTable,
    Icon = "Quest",
    Message = "",
    Param = _EmptyTable,
    Practical = 4,
    Reward = _EmptyTable,
    Sort = 1,
    SubTitle = "今日登录一次",
    TargetType = 2,
    Title = "勇闯试炼塔",
    Version = 1,
    id = 1
  }
}
for _, d in pairs(Table_NoviceTarget) do
  setmetatable(d, cell_mt)
end
