Table_Recommend = {
  [1] = {
    id = 1,
    Icon = "Wanted",
    Name = "任务委托板",
    Title = "完成委托看板任务3次",
    PageType = {2, 3},
    Sort = 30,
    Reward = 9234001,
    Favorability = 60,
    Recycle = 1,
    Progress = "%s/3",
    Finish = "wanted_quest_day",
    Del = "",
    Del_Params = _EmptyTable,
    GotoMode = {1},
    Difficulty = 0,
    ServerID = _EmptyTable,
    InDoublePool = 1
  },
  [2] = {
    id = 2,
    Icon = "MapRaid",
    Name = "修复裂隙",
    Title = "完成裂隙挑战1次",
    PageType = {2, 3},
    Sort = 31,
    Reward = 9234002,
    Favorability = 60,
    Recycle = 1,
    Progress = "%s/1",
    Finish = "crack_raid",
    Del = "",
    Del_Params = _EmptyTable,
    GotoMode = {8201},
    Difficulty = 0,
    ServerID = _EmptyTable,
    InDoublePool = 1
  },
  [4] = {
    id = 4,
    Icon = "equipupgrade",
    Name = "装备强化",
    Title = "强化任意装备部位1次",
    PageType = {3},
    Sort = 32,
    Favorability = 60,
    Recycle = 1,
    Progress = "%s/1",
    Finish = "equip_strength",
    Del = "strength_full",
    Del_Params = _EmptyTable,
    GotoMode = {2095},
    Difficulty = 0,
    ServerID = _EmptyTable,
    InDoublePool = 1
  },
  [5] = {
    id = 5,
    Icon = "petrisk",
    Name = "宠物打工",
    Title = "领取宠物打工的奖励1次",
    PageType = {3},
    Sort = 33,
    Reward = 9234005,
    Favorability = 60,
    Recycle = 1,
    Progress = "%s/1",
    Finish = "petwork",
    Del = "",
    Del_Params = _EmptyTable,
    GotoMode = {2080},
    Difficulty = 0,
    ServerID = _EmptyTable,
    InDoublePool = 1
  },
  [6] = {
    id = 6,
    Icon = "Guild",
    Name = "公会捐赠",
    Title = "为你的公会做出贡献1次",
    PageType = {5},
    Sort = 34,
    Favorability = 60,
    Recycle = 1,
    Progress = "%s/1",
    Finish = "guild_donate",
    Del = "",
    Del_Params = _EmptyTable,
    GotoMode = {3018},
    Difficulty = 0,
    ServerID = _EmptyTable,
    InDoublePool = 1
  },
  [7] = {
    id = 7,
    Icon = "blessing_4",
    Name = "公会祈祷",
    Title = "通过公会祈祷强化自身能力1次",
    PageType = {2, 5},
    Sort = 35,
    Favorability = 60,
    Recycle = 1,
    Progress = "%s/1",
    Finish = "guild_pray_daily",
    Del = "guild_pray_full",
    Del_Params = _EmptyTable,
    GotoMode = {500},
    Difficulty = 0,
    ServerID = _EmptyTable,
    InDoublePool = 1
  },
  [9] = {
    id = 9,
    Icon = "Sign_in_80",
    Name = "欢迎回来",
    Title = "今天登录一次游戏",
    PageType = {9},
    Sort = 1,
    Reward = 9234117,
    Favorability = 60,
    Recycle = 1,
    Progress = "%s/1",
    Finish = "dailyplaytime",
    Del = "",
    Del_Params = _EmptyTable,
    GotoMode = _EmptyTable,
    Difficulty = 0,
    ServerID = _EmptyTable
  },
  [10] = {
    id = 10,
    Icon = "Activities",
    Name = "魔物驱逐挑战",
    Title = "累计击败魔物500次",
    PageType = {
      2,
      3,
      6
    },
    Sort = 2,
    Reward = 139900,
    Recycle = 1,
    Progress = "%s/%s",
    Finish = "fightcount",
    Del = "",
    Del_Params = _EmptyTable,
    GotoMode = _EmptyTable,
    Difficulty = 0,
    ServerID = _EmptyTable,
    GroupID = 1
  },
  [11] = {
    id = 11,
    Icon = "Activities",
    Name = "魔物驱逐挑战",
    Title = "累计击败魔物500次",
    PageType = {
      2,
      3,
      6
    },
    Sort = 3,
    Reward = 139900,
    Recycle = 1,
    Progress = "%s/%s",
    Finish = "fightcount",
    Del = "",
    Del_Params = _EmptyTable,
    GotoMode = _EmptyTable,
    Difficulty = 0,
    ServerID = _EmptyTable,
    GroupID = 1
  },
  [12] = {
    id = 12,
    Icon = "Activities",
    Name = "魔物驱逐挑战",
    Title = "累计击败魔物500次",
    PageType = {
      2,
      3,
      6
    },
    Sort = 4,
    Reward = 139900,
    Recycle = 1,
    Progress = "%s/%s",
    Finish = "fightcount",
    Del = "",
    Del_Params = _EmptyTable,
    GotoMode = _EmptyTable,
    Difficulty = 0,
    ServerID = _EmptyTable,
    GroupID = 1
  },
  [13] = {
    id = 13,
    Icon = "Activities",
    Name = "魔物驱逐挑战",
    Title = "累计击败魔物500次",
    PageType = {
      2,
      3,
      6
    },
    Sort = 5,
    Reward = 139900,
    Recycle = 1,
    Progress = "%s/%s",
    Finish = "fightcount",
    Del = "",
    Del_Params = _EmptyTable,
    GotoMode = _EmptyTable,
    Difficulty = 0,
    ServerID = _EmptyTable,
    GroupID = 1
  },
  [14] = {
    id = 14,
    Icon = "Activities",
    Name = "魔物驱逐挑战",
    Title = "累计击败魔物500次",
    PageType = {
      2,
      3,
      6
    },
    Sort = 6,
    Reward = 139901,
    Recycle = 1,
    Progress = "%s/%s",
    Finish = "fightcount",
    Del = "",
    Del_Params = _EmptyTable,
    GotoMode = _EmptyTable,
    Difficulty = 0,
    ServerID = _EmptyTable,
    GroupID = 1
  },
  [15] = {
    id = 15,
    Icon = "Activities",
    Name = "魔物驱逐挑战",
    Title = "累计击败魔物500次",
    PageType = {
      2,
      3,
      6
    },
    Sort = 7,
    Reward = 139900,
    Recycle = 1,
    Progress = "%s/%s",
    Finish = "fightcount",
    Del = "",
    Del_Params = _EmptyTable,
    GotoMode = _EmptyTable,
    Difficulty = 0,
    ServerID = _EmptyTable,
    GroupID = 1
  },
  [16] = {
    id = 16,
    Icon = "Activities",
    Name = "魔物驱逐挑战",
    Title = "累计击败魔物500次",
    PageType = {
      2,
      3,
      6
    },
    Sort = 8,
    Reward = 139900,
    Recycle = 1,
    Progress = "%s/%s",
    Finish = "fightcount",
    Del = "",
    Del_Params = _EmptyTable,
    GotoMode = _EmptyTable,
    Difficulty = 0,
    ServerID = _EmptyTable,
    GroupID = 1
  },
  [17] = {
    id = 17,
    Icon = "Activities",
    Name = "魔物驱逐挑战",
    Title = "累计击败魔物500次",
    PageType = {
      2,
      3,
      6
    },
    Sort = 9,
    Reward = 139900,
    Recycle = 1,
    Progress = "%s/%s",
    Finish = "fightcount",
    Del = "",
    Del_Params = _EmptyTable,
    GotoMode = _EmptyTable,
    Difficulty = 0,
    ServerID = _EmptyTable,
    GroupID = 1
  },
  [18] = {
    id = 18,
    Icon = "Activities",
    Name = "魔物驱逐挑战",
    Title = "累计击败魔物500次",
    PageType = {
      2,
      3,
      6
    },
    Sort = 10,
    Reward = 139900,
    Recycle = 1,
    Progress = "%s/%s",
    Finish = "fightcount",
    Del = "",
    Del_Params = _EmptyTable,
    GotoMode = _EmptyTable,
    Difficulty = 0,
    ServerID = _EmptyTable,
    GroupID = 1
  },
  [19] = {
    id = 19,
    Icon = "Activities",
    Name = "魔物驱逐挑战",
    Title = "累计击败魔物500次",
    PageType = {
      2,
      3,
      6
    },
    Sort = 11,
    Reward = 139901,
    Recycle = 1,
    Progress = "%s/%s",
    Finish = "fightcount",
    Del = "",
    Del_Params = _EmptyTable,
    GotoMode = _EmptyTable,
    Difficulty = 0,
    ServerID = _EmptyTable,
    GroupID = 1
  },
  [20] = {
    id = 20,
    Icon = "Activities",
    Name = "魔物驱逐挑战",
    Title = "累计击败魔物500次",
    PageType = {
      2,
      3,
      6
    },
    Sort = 12,
    Reward = 139900,
    Recycle = 1,
    Progress = "%s/%s",
    Finish = "fightcount",
    Del = "",
    Del_Params = _EmptyTable,
    GotoMode = _EmptyTable,
    Difficulty = 0,
    ServerID = _EmptyTable,
    GroupID = 1
  },
  [21] = {
    id = 21,
    Icon = "Activities",
    Name = "魔物驱逐挑战",
    Title = "累计击败魔物500次",
    PageType = {
      2,
      3,
      6
    },
    Sort = 13,
    Reward = 139900,
    Recycle = 1,
    Progress = "%s/%s",
    Finish = "fightcount",
    Del = "",
    Del_Params = _EmptyTable,
    GotoMode = _EmptyTable,
    Difficulty = 0,
    ServerID = _EmptyTable,
    GroupID = 1
  },
  [22] = {
    id = 22,
    Icon = "Activities",
    Name = "魔物驱逐挑战",
    Title = "累计击败魔物500次",
    PageType = {
      2,
      3,
      6
    },
    Sort = 14,
    Reward = 139900,
    Recycle = 1,
    Progress = "%s/%s",
    Finish = "fightcount",
    Del = "",
    Del_Params = _EmptyTable,
    GotoMode = _EmptyTable,
    Difficulty = 0,
    ServerID = _EmptyTable,
    GroupID = 1
  },
  [23] = {
    id = 23,
    Icon = "Activities",
    Name = "魔物驱逐挑战",
    Title = "累计击败魔物500次",
    PageType = {
      2,
      3,
      6
    },
    Sort = 15,
    Reward = 139900,
    Recycle = 1,
    Progress = "%s/%s",
    Finish = "fightcount",
    Del = "",
    Del_Params = _EmptyTable,
    GotoMode = _EmptyTable,
    Difficulty = 0,
    ServerID = _EmptyTable,
    GroupID = 1
  },
  [24] = {
    id = 24,
    Icon = "Activities",
    Name = "魔物驱逐挑战",
    Title = "累计击败魔物500次",
    PageType = {
      2,
      3,
      6
    },
    Sort = 16,
    Reward = 139901,
    Recycle = 1,
    Progress = "%s/%s",
    Finish = "fightcount",
    Del = "",
    Del_Params = _EmptyTable,
    GotoMode = _EmptyTable,
    Difficulty = 0,
    ServerID = _EmptyTable,
    GroupID = 1
  },
  [25] = {
    id = 25,
    Icon = "Activities",
    Name = "魔物驱逐挑战",
    Title = "累计击败魔物500次",
    PageType = {
      2,
      3,
      6
    },
    Sort = 17,
    Reward = 139900,
    Recycle = 1,
    Progress = "%s/%s",
    Finish = "fightcount",
    Del = "",
    Del_Params = _EmptyTable,
    GotoMode = _EmptyTable,
    Difficulty = 0,
    ServerID = _EmptyTable,
    GroupID = 1
  },
  [26] = {
    id = 26,
    Icon = "Activities",
    Name = "魔物驱逐挑战",
    Title = "累计击败魔物500次",
    PageType = {
      2,
      3,
      6
    },
    Sort = 18,
    Reward = 139900,
    Recycle = 1,
    Progress = "%s/%s",
    Finish = "fightcount",
    Del = "",
    Del_Params = _EmptyTable,
    GotoMode = _EmptyTable,
    Difficulty = 0,
    ServerID = _EmptyTable,
    GroupID = 1
  },
  [27] = {
    id = 27,
    Icon = "Activities",
    Name = "魔物驱逐挑战",
    Title = "累计击败魔物500次",
    PageType = {
      2,
      3,
      6
    },
    Sort = 19,
    Reward = 139900,
    Recycle = 1,
    Progress = "%s/%s",
    Finish = "fightcount",
    Del = "",
    Del_Params = _EmptyTable,
    GotoMode = _EmptyTable,
    Difficulty = 0,
    ServerID = _EmptyTable,
    GroupID = 1
  },
  [28] = {
    id = 28,
    Icon = "Activities",
    Name = "魔物驱逐挑战",
    Title = "累计击败魔物500次",
    PageType = {
      2,
      3,
      6
    },
    Sort = 20,
    Reward = 139900,
    Recycle = 1,
    Progress = "%s/%s",
    Finish = "fightcount",
    Del = "",
    Del_Params = _EmptyTable,
    GotoMode = _EmptyTable,
    Difficulty = 0,
    ServerID = _EmptyTable,
    GroupID = 1
  },
  [29] = {
    id = 29,
    Icon = "Activities",
    Name = "魔物驱逐挑战",
    Title = "累计击败魔物500次",
    PageType = {
      2,
      3,
      6
    },
    Sort = 21,
    Reward = 139901,
    Recycle = 1,
    Progress = "%s/%s",
    Finish = "fightcount",
    Del = "",
    Del_Params = _EmptyTable,
    GotoMode = _EmptyTable,
    Difficulty = 0,
    ServerID = _EmptyTable,
    GroupID = 1
  },
  [112] = {
    id = 112,
    Icon = "DispatchArea_03",
    Name = "博物岛/迷踪岛",
    Title = "通关任意难度的博物岛或迷踪岛1次",
    PageType = {5, 6},
    Sort = 3,
    Reward = 9234111,
    Favorability = 120,
    Recycle = 2,
    Progress = "%s/1",
    Finish = "comodo_or_seven_royal",
    Del = "",
    Del_Params = _EmptyTable,
    GotoMode = {8202},
    Difficulty = 0,
    ServerID = _EmptyTable,
    CardExtraReward = 70000028,
    InDoublePool = 1
  },
  [113] = {
    id = 113,
    Icon = "endlessT",
    Name = "恩德勒斯塔",
    Title = "通关恩德勒斯塔副本中任意10层",
    PageType = {5, 6},
    Sort = 4,
    Favorability = 120,
    Recycle = 2,
    Progress = "%s/1",
    Finish = "pve_raid_pass",
    Del = "",
    Del_Params = _EmptyTable,
    GotoMode = {8193},
    Difficulty = 0,
    ServerID = _EmptyTable,
    InDoublePool = 1
  },
  [114] = {
    id = 114,
    Icon = "headwear",
    Name = "蛋糕保卫战",
    Title = "通关任意难度的蛋糕保卫战1次",
    PageType = {5, 6},
    Sort = 5,
    Reward = 9234113,
    Favorability = 120,
    Recycle = 2,
    Progress = "%s/1",
    Finish = "pve_raid_pass",
    Del = "",
    Del_Params = _EmptyTable,
    GotoMode = {8192},
    Difficulty = 0,
    ServerID = _EmptyTable,
    InDoublePool = 1
  },
  [115] = {
    id = 115,
    Icon = "oracle",
    Name = "神谕副本",
    Title = "通关任意难度的神谕副本1次",
    PageType = {5, 6},
    Sort = 6,
    Reward = 9234116,
    Favorability = 120,
    Recycle = 2,
    Progress = "%s/1",
    Finish = "pve_card",
    Del = "",
    Del_Params = _EmptyTable,
    GotoMode = {8194},
    Difficulty = 0,
    ServerID = _EmptyTable,
    CardExtraReward = 61000171,
    InDoublePool = 1
  },
  [117] = {
    id = 117,
    Icon = "Dungeon",
    Name = "瓦尔哈拉遗迹",
    Title = "在瓦尔哈拉遗迹中击杀MVP/Mini达到3个",
    PageType = {5, 6},
    Sort = 8,
    Reward = 9234102,
    Favorability = 120,
    Recycle = 2,
    Progress = "%s/5",
    Finish = "guild_fuben",
    Del = "",
    Del_Params = _EmptyTable,
    GotoMode = {3019},
    Difficulty = 0,
    ServerID = _EmptyTable,
    InDoublePool = 1
  },
  [118] = {
    id = 118,
    Icon = "ThanatosT",
    Name = "达纳托斯之塔",
    Title = "通关任意难度的达纳托斯之塔1次",
    PageType = {5, 6},
    Sort = 9,
    Reward = 9234115,
    Favorability = 120,
    Recycle = 2,
    Progress = "%s/1",
    Finish = "thanatos_raid",
    Del = "",
    Del_Params = _EmptyTable,
    GotoMode = {8198},
    Difficulty = 0,
    ServerID = _EmptyTable,
    CardExtraReward = 70000027,
    InDoublePool = 1
  },
  [120] = {
    id = 120,
    Icon = "raidbgicon_mvp01",
    Name = "混沌入侵",
    Title = "通关任意难度的混沌入侵副本1次",
    PageType = {5, 6},
    Sort = 11,
    Reward = 9234113,
    Favorability = 120,
    Recycle = 2,
    Progress = "%s/1",
    Finish = "boss_scene_pass",
    Del = "",
    Del_Params = _EmptyTable,
    GotoMode = {8254},
    Difficulty = 0,
    ServerID = _EmptyTable,
    CardExtraReward = 70000026,
    InDoublePool = 1
  },
  [130] = {
    id = 130,
    Icon = "Guild",
    Name = "公会战",
    Title = "在GVG中获得的击杀与助攻之和超过10次",
    PageType = {5, 6},
    Sort = 14,
    Favorability = 120,
    Recycle = 2,
    Progress = "%s/10",
    Finish = "gvg_kill_and_assist",
    Del = "",
    Del_Params = _EmptyTable,
    GotoMode = {2056},
    Difficulty = 0,
    ServerID = _EmptyTable
  },
  [131] = {
    id = 131,
    Icon = "Activities",
    Name = "MVP",
    Title = "击杀1只任意等级的野外MVP",
    PageType = {5, 6},
    Sort = 15,
    Favorability = 120,
    Recycle = 2,
    Progress = "%s/1",
    Finish = "join_kill_mvp",
    Del = "",
    Del_Params = _EmptyTable,
    GotoMode = {2003},
    Difficulty = 0,
    ServerID = _EmptyTable
  },
  [2001] = {
    id = 2001,
    Icon = "Wanted",
    Name = "任务委托板",
    Title = "完成委托看板任务3次",
    PageType = {2, 3},
    Reward = 9234201,
    Favorability = 120,
    Recycle = 6,
    Progress = "%s/3",
    Finish = "wanted_quest_day",
    Del = "",
    Del_Params = _EmptyTable,
    GotoMode = {1},
    Difficulty = 0,
    ServerID = _EmptyTable
  },
  [2002] = {
    id = 2002,
    Icon = "MapRaid",
    Name = "修复裂隙",
    Title = "完成裂隙挑战1次",
    PageType = {2, 3},
    Reward = 9234207,
    Favorability = 120,
    Recycle = 6,
    Progress = "%s/1",
    Finish = "crack_raid",
    Del = "",
    Del_Params = _EmptyTable,
    GotoMode = {8201},
    Difficulty = 0,
    ServerID = _EmptyTable
  },
  [2004] = {
    id = 2004,
    Icon = "equipupgrade",
    Name = "装备强化",
    Title = "强化任意装备部位1次",
    PageType = {3},
    Favorability = 120,
    Recycle = 6,
    Progress = "%s/1",
    Finish = "equip_strength",
    Del = "strength_full",
    Del_Params = _EmptyTable,
    GotoMode = {2095},
    Difficulty = 0,
    ServerID = _EmptyTable
  },
  [2005] = {
    id = 2005,
    Icon = "petrisk",
    Name = "宠物打工",
    Title = "领取宠物打工的奖励1次",
    PageType = {3},
    Reward = 9234201,
    Favorability = 120,
    Recycle = 6,
    Progress = "%s/1",
    Finish = "petwork",
    Del = "",
    Del_Params = _EmptyTable,
    GotoMode = {2080},
    Difficulty = 0,
    ServerID = _EmptyTable
  },
  [2006] = {
    id = 2006,
    Icon = "Guild",
    Name = "公会捐赠",
    Title = "为你的公会做出贡献1次",
    PageType = {5},
    Favorability = 120,
    Recycle = 6,
    Progress = "%s/1",
    Finish = "guild_donate",
    Del = "",
    Del_Params = _EmptyTable,
    GotoMode = {3018},
    Difficulty = 0,
    ServerID = _EmptyTable
  },
  [2007] = {
    id = 2007,
    Icon = "blessing_4",
    Name = "公会祈祷",
    Title = "通过公会祈祷强化自身能力1次",
    PageType = {2, 5},
    Favorability = 120,
    Recycle = 6,
    Progress = "%s/1",
    Finish = "guild_pray_daily",
    Del = "guild_pray_full",
    Del_Params = _EmptyTable,
    GotoMode = {500},
    Difficulty = 0,
    ServerID = _EmptyTable
  },
  [2112] = {
    id = 2112,
    Icon = "DispatchArea_03",
    Name = "博物岛/迷踪岛",
    Title = "通关任意难度的博物岛或迷踪岛1次",
    PageType = {5, 6},
    Reward = 9234212,
    Favorability = 240,
    Recycle = 9,
    Progress = "%s/1",
    Finish = "comodo_or_seven_royal",
    Del = "",
    Del_Params = _EmptyTable,
    GotoMode = {8202},
    Difficulty = 0,
    ServerID = _EmptyTable
  },
  [2113] = {
    id = 2113,
    Icon = "endlessT",
    Name = "恩德勒斯塔",
    Title = "通关任意难度的恩德勒斯塔1次",
    PageType = {5, 6},
    Favorability = 240,
    Recycle = 9,
    Progress = "%s/1",
    Finish = "pve_raid_pass",
    Del = "",
    Del_Params = _EmptyTable,
    GotoMode = {8193},
    Difficulty = 0,
    ServerID = _EmptyTable
  },
  [2115] = {
    id = 2115,
    Icon = "oracle",
    Name = "神谕副本",
    Title = "通关任意难度的神谕副本1次",
    PageType = {5, 6},
    Reward = 9234215,
    Favorability = 240,
    Recycle = 9,
    Progress = "%s/1",
    Finish = "pve_card",
    Del = "",
    Del_Params = _EmptyTable,
    GotoMode = {8194},
    Difficulty = 0,
    ServerID = _EmptyTable
  }
}
Table_Recommend_fields = {
  "id",
  "Icon",
  "Name",
  "Title",
  "PageType",
  "Sort",
  "Reward",
  "Favorability",
  "Recycle",
  "Progress",
  "Finish",
  "Del",
  "Del_Params",
  "NeedDel",
  "GotoMode",
  "Difficulty",
  "ServerID",
  "BattlePassExp",
  "FuncState",
  "CardExtraReward",
  "GroupID",
  "InDoublePool"
}
return Table_Recommend
