Table_HairStyle_t = {
  AvatarColor = {
    {
      1166949631,
      3173591551,
      1128620031,
      3083331071,
      2926173951,
      4287970303,
      2104613119,
      1951476735,
      4288003071,
      1927112191,
      4282791167,
      2086164735,
      3587899391,
      3636330495,
      4290136319,
      2194014207,
      2757904383,
      4053511423
    }
  },
  PaintColor = {
    {
      1234192383,
      3963962879,
      1094469631,
      2526985215,
      2673386495,
      4085592319,
      1566615807,
      1598497791
    }
  }
}
Table_HairStyle = {
  [1] = {
    ItemID = 46001,
    Icon = "Hair23_Male",
    HairFront = "Hair_front_823",
    DefaultColor = 1,
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 1,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 6
  },
  [2] = {
    id = 2,
    ItemID = 46002,
    Icon = "Hair2_Male",
    HairFront = "Hair_front_802",
    HairBack = "Hair_front_802_back",
    DefaultColor = 6,
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 1,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 6
  },
  [3] = {
    id = 3,
    ItemID = 46003,
    Icon = "Hair5_Male",
    HairFront = "Hair_front_805",
    HairBack = "Hair_back_805",
    DefaultColor = 8,
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 1,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 2
  },
  [4] = {
    id = 4,
    ItemID = 46004,
    Icon = "Hair4_Male",
    HairFront = "Hair_front_804",
    HairBack = "Hair_back_804",
    DefaultColor = 3,
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 1,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 3
  },
  [5] = {
    id = 5,
    ItemID = 46005,
    Icon = "Hair15_Male",
    HairFront = "Hair_front_815",
    HairBack = "Hair_back_815",
    DefaultColor = 1,
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 1,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 6
  },
  [6] = {
    id = 6,
    ItemID = 46006,
    Icon = "Hair6_Male",
    HairFront = "Hair_front_806",
    HairBack = "Hair_back_806",
    DefaultColor = 4,
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 1,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 4
  },
  [7] = {
    id = 7,
    ItemID = 46007,
    Icon = "Hair12_Male",
    HairFront = "Hair_front_812",
    HairBack = "Hair_back_812",
    DefaultColor = 1,
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 1,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 1
  },
  [8] = {
    id = 8,
    ItemID = 46008,
    Icon = "Hair8_Male",
    HairFront = "Hair_front_808",
    HairBack = "Hair_back_808",
    DefaultColor = 5,
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 1,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 8
  },
  [9] = {
    id = 9,
    ItemID = 46009,
    Icon = "Hair1_Male",
    HairFront = "Hair_front_801",
    HairBack = "Hair_back_801",
    DefaultColor = 5,
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 1,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 5
  },
  [10] = {
    id = 10,
    ItemID = 46010,
    Icon = "Hair7_Male",
    HairFront = "Hair_front_807",
    HairBack = "Hair_back_807",
    DefaultColor = 2,
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 1,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 2
  },
  [11] = {
    id = 11,
    ItemID = 46011,
    Icon = "Hair9_Female",
    HairFront = "Hair_front_909",
    HairBack = "Hair_back_909",
    DefaultColor = 8,
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 2
  },
  [12] = {
    id = 12,
    ItemID = 46012,
    Icon = "Hair2_Female",
    HairFront = "Hair_front_902",
    HairBack = "Hair_back_902",
    DefaultColor = 2,
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 7
  },
  [13] = {
    id = 13,
    ItemID = 46013,
    Icon = "Hair3_Female",
    HairFront = "Hair_front_903",
    HairBack = "Hair_back_903",
    DefaultColor = 8,
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 8
  },
  [14] = {
    id = 14,
    ItemID = 46014,
    Icon = "Hair4_Female",
    HairFront = "Hair_front_904",
    HairBack = "Hair_back_904",
    DefaultColor = 7,
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 6
  },
  [15] = {
    id = 15,
    ItemID = 46015,
    Icon = "Hair5_Female",
    HairFront = "Hair_front_905",
    HairBack = "Hair_back_905",
    DefaultColor = 6,
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 6
  },
  [16] = {
    id = 16,
    ItemID = 46016,
    Icon = "Hair6_Female",
    HairFront = "Hair_front_906",
    HairBack = "Hair_back_906",
    DefaultColor = 7,
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 5
  },
  [17] = {
    id = 17,
    ItemID = 46017,
    Icon = "Hair7_Female",
    HairFront = "Hair_front_907",
    HairBack = "Hair_back_907",
    DefaultColor = 1,
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 2
  },
  [18] = {
    id = 18,
    ItemID = 46018,
    Icon = "Hair8_Female",
    HairFront = "Hair_front_908",
    HairBack = "Hair_back_908",
    DefaultColor = 8,
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 8
  },
  [19] = {
    id = 19,
    ItemID = 46019,
    Icon = "Hair10_Female",
    HairFront = "Hair_front_910",
    HairBack = "Hair_front_910",
    DefaultColor = 1,
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 1
  },
  [20] = {
    id = 20,
    ItemID = 46020,
    Icon = "Hair31_Female",
    HairFront = "Hair_front_931",
    HairBack = "Hair_back_931",
    DefaultColor = 1,
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 1
  },
  [21] = {
    id = 21,
    ItemID = 46021,
    Icon = "Hair24_Male",
    HairFront = "Hair_front_824",
    HairBack = "Hair_back_824",
    DefaultColor = 6,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 1,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 6
  },
  [22] = {
    id = 22,
    ItemID = 46022,
    Icon = "Hair25_Male",
    HairFront = "Hair_front_825",
    HairBack = "Hair_back_825",
    DefaultColor = 8,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 1,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 8
  },
  [23] = {
    id = 23,
    ItemID = 46023,
    Icon = "Hair26_Male",
    HairFront = "Hair_front_826",
    HairBack = "Hair_back_826",
    DefaultColor = 2,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 1,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 2
  },
  [24] = {
    id = 24,
    ItemID = 46024,
    Icon = "Hair31_Male",
    HairFront = "Hair_front_837",
    HairBack = "Hair_back_837",
    DefaultColor = 5,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 1,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 5
  },
  [25] = {
    id = 25,
    ItemID = 46035,
    Icon = "Hair27_Male",
    HairFront = "Hair_front_827",
    HairBack = "Hair_back_827",
    DefaultColor = 1,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 1,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 1
  },
  [26] = {
    id = 26,
    ItemID = 46036,
    Icon = "Hair28_Male",
    HairFront = "Hair_front_828",
    HairBack = "Hair_back_828",
    DefaultColor = 1,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 1,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 1
  },
  [27] = {
    id = 27,
    Icon = "Hair14_Male",
    HairFront = "Hair_front_814",
    DefaultColor = 1,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 1,
    IsPro = 1,
    Race = 1,
    DefaultIconColor = 1
  },
  [28] = {
    id = 28,
    Icon = "Hair13_Male",
    HairFront = "Hair_front_813",
    DefaultColor = 1,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 1,
    IsPro = 1,
    Race = 1,
    DefaultIconColor = 1
  },
  [29] = {
    id = 29,
    ItemID = 46060,
    Icon = "Hair29_Male",
    HairFront = "Hair_front_829",
    DefaultColor = 1,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 1,
    IsPro = 1,
    Race = 1,
    DefaultIconColor = 1
  },
  [30] = {
    id = 30,
    Icon = "Hair30_Male",
    HairFront = "Hair_front_830",
    DefaultColor = 1,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 1,
    IsPro = 1,
    Race = 1,
    DefaultIconColor = 1
  },
  [31] = {
    id = 31,
    ItemID = 46031,
    Icon = "Hair23_Female",
    HairFront = "Hair_front_923",
    HairBack = "Hair_back_923",
    DefaultColor = 3,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 3
  },
  [32] = {
    id = 32,
    ItemID = 46032,
    Icon = "Hair24_Female",
    HairFront = "Hair_front_924",
    HairBack = "Hair_back_924",
    DefaultColor = 2,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 2
  },
  [33] = {
    id = 33,
    ItemID = 46033,
    Icon = "Hair25_Female",
    HairFront = "Hair_front_925",
    HairBack = "Hair_back_925",
    DefaultColor = 4,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 4
  },
  [34] = {
    id = 34,
    ItemID = 46034,
    Icon = "Hair26_Female",
    HairFront = "Hair_front_926",
    HairBack = "Hair_back_926",
    DefaultColor = 9,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 2
  },
  [35] = {
    id = 35,
    ItemID = 46037,
    Icon = "Hair27_Female",
    HairFront = "Hair_front_927",
    HairBack = "Hair_back_927",
    DefaultColor = 1,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 1
  },
  [36] = {
    id = 36,
    ItemID = 46038,
    Icon = "Hair28_Female",
    HairFront = "Hair_front_928",
    HairBack = "Hair_back_928",
    DefaultColor = 1,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 1
  },
  [37] = {
    id = 37,
    Icon = "Hair15_Female",
    HairFront = "Hair_front_915",
    HairBack = "Hair_back_915",
    DefaultColor = 1,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    Race = 1,
    DefaultIconColor = 1
  },
  [38] = {
    id = 38,
    Icon = "Hair18_Female",
    HairFront = "Hair_front_918",
    HairBack = "Hair_back_918",
    DefaultColor = 1,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    Race = 1,
    DefaultIconColor = 1
  },
  [39] = {
    id = 39,
    ItemID = 46061,
    Icon = "Hair29_Female",
    HairFront = "Hair_front_929",
    DefaultColor = 1,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    Race = 1,
    DefaultIconColor = 1
  },
  [40] = {
    id = 40,
    Icon = "Hair30_Female",
    HairFront = "Hair_front_930",
    DefaultColor = 1,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    Race = 1,
    DefaultIconColor = 1
  },
  [41] = {
    id = 41,
    ItemID = 46041,
    Icon = "Hair41_Male",
    HairFront = "Hair_front_841",
    DefaultColor = 3,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 1,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 6
  },
  [42] = {
    id = 42,
    ItemID = 46042,
    Icon = "Hair42_Male",
    HairFront = "Hair_front_842",
    DefaultColor = 6,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 1,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 6
  },
  [43] = {
    id = 43,
    Icon = "Hair43_Male",
    HairFront = "Hair_front_843",
    PaintColor = Table_HairStyle_t.PaintColor[1],
    Race = 1
  },
  [44] = {
    id = 44,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    Race = 1
  },
  [45] = {
    id = 45,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    Race = 1
  },
  [46] = {
    id = 46,
    Icon = "Hair46_Male",
    DefaultColor = 1,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    Race = 1,
    DefaultIconColor = 1
  },
  [47] = {
    id = 47,
    Icon = "Hair47_Male",
    DefaultColor = 1,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    Race = 1,
    DefaultIconColor = 1
  },
  [48] = {
    id = 48,
    Icon = "Hair48_Male",
    DefaultColor = 1,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    Race = 1,
    DefaultIconColor = 1
  },
  [49] = {
    id = 49,
    Icon = "Hair49_Male",
    DefaultColor = 1,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    Race = 1,
    DefaultIconColor = 1
  },
  [50] = {
    id = 50,
    Icon = "Hair50_Male",
    DefaultColor = 1,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    Race = 1,
    DefaultIconColor = 1
  },
  [51] = {
    id = 51,
    ItemID = 46051,
    Icon = "Hair51_Female",
    HairFront = "Hair_front_951",
    HairBack = "Hair_back_951",
    DefaultColor = 2,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 2
  },
  [52] = {
    id = 52,
    ItemID = 46052,
    Icon = "Hair52_Female",
    HairFront = "Hair_front_952",
    HairBack = "Hair_back_952",
    DefaultColor = 6,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 6
  },
  [53] = {
    id = 53,
    ItemID = 46053,
    Icon = "Hair53_Female",
    HairFront = "Hair_front_953",
    HairBack = "Hair_back_953",
    DefaultColor = 6,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 6
  },
  [54] = {
    id = 54,
    ItemID = 46054,
    Icon = "Hair54_Female",
    HairFront = "Hair_front_954",
    HairBack = "Hair_back_954",
    DefaultColor = 5,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 5
  },
  [55] = {
    id = 55,
    ItemID = 46055,
    Icon = "Hair55_Female",
    HairFront = "Hair_front_955",
    HairBack = "Hair_back_955",
    DefaultColor = 3,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 6
  },
  [56] = {
    id = 56,
    ItemID = 46056,
    Icon = "Hair56_Female",
    HairFront = "Hair_front_956",
    HairBack = "Hair_back_956",
    DefaultColor = 2,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 2
  },
  [57] = {
    id = 57,
    ItemID = 46057,
    Icon = "Hair57_Female",
    HairFront = "Hair_front_957",
    HairBack = "Hair_back_957",
    DefaultColor = 7,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 7
  },
  [58] = {
    id = 58,
    ItemID = 46058,
    Icon = "Hair58_Female",
    HairFront = "Hair_front_958",
    HairBack = "Hair_back_958",
    DefaultColor = 6,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 6
  },
  [59] = {
    id = 59,
    ItemID = 46065,
    Icon = "Hair64_Female",
    HairFront = "Hair_front_964",
    HairBack = "Hair_back_964",
    DefaultColor = 5,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 6
  },
  [60] = {
    id = 60,
    ItemID = 46066,
    Icon = "Hair65_Female",
    HairFront = "Hair_front_965",
    HairBack = "Hair_back_965",
    DefaultColor = 8,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 6
  },
  [61] = {
    id = 61,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    Race = 1
  },
  [62] = {
    id = 62,
    ItemID = 46062,
    Icon = "Hair61_Male",
    HairFront = "Hair_front_961",
    HairBack = "Hair_back_961",
    DefaultColor = 2,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 1,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 6
  },
  [63] = {
    id = 63,
    ItemID = 46063,
    Icon = "Hair62_Male",
    HairFront = "Hair_front_962",
    HairBack = "Hair_back_962",
    DefaultColor = 7,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 1,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 6
  },
  [64] = {
    id = 64,
    ItemID = 46064,
    Icon = "Hair63_Male",
    HairFront = "Hair_front_963",
    HairBack = "Hair_back_963",
    DefaultColor = 6,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 1,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 6
  },
  [65] = {
    id = 65,
    ItemID = 46069,
    Icon = "Hair64_Male",
    HairFront = "Hair_front_65",
    HairBack = "Hair_back_65",
    DefaultColor = 6,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 1,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 3
  },
  [66] = {
    id = 66,
    ItemID = 46071,
    Icon = "Hair65_Male",
    HairFront = "Hair_front_66",
    HairBack = "Hair_back_67",
    DefaultColor = 3,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 1,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 3
  },
  [67] = {
    id = 67,
    ItemID = 46073,
    Icon = "Hair66_Male",
    HairFront = "Hair_front_67",
    DefaultColor = 8,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 1,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 3
  },
  [68] = {
    id = 68,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    Race = 1
  },
  [69] = {
    id = 69,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    Race = 1
  },
  [70] = {
    id = 70,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    Race = 1
  },
  [71] = {
    id = 71,
    ItemID = 46067,
    Icon = "Hair66_Female",
    HairFront = "Hair_front_966",
    HairBack = "Hair_back_966",
    DefaultColor = 4,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 4
  },
  [72] = {
    id = 72,
    ItemID = 46068,
    Icon = "Hair67_Female",
    HairFront = "Hair_front_967",
    HairBack = "Hair_back_967",
    DefaultColor = 6,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    DefaultIconColor = 6
  },
  [73] = {
    id = 73,
    Icon = "Hair73_Female",
    HairFront = "Hair_front_973",
    HairBack = "Hair_back_973",
    PaintColor = Table_HairStyle_t.PaintColor[1],
    Race = 1
  },
  [74] = {
    id = 74,
    ItemID = 46070,
    Icon = "Hair69_Female",
    HairFront = "Hair_front_74",
    HairBack = "Hair_back_74",
    DefaultColor = 6,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 6
  },
  [75] = {
    id = 75,
    ItemID = 46074,
    Icon = "Hair70_Female",
    HairFront = "Hair_front_75",
    HairBack = "Hair_back_75",
    DefaultColor = 1,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 6
  },
  [76] = {
    id = 76,
    ItemID = 46072,
    Icon = "Hair71_Female",
    HairFront = "Hair_front_76",
    HairBack = "Hair_back_76",
    DefaultColor = 2,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    DefaultIconColor = 2
  },
  [77] = {
    id = 77,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    Race = 1
  },
  [78] = {
    id = 78,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    Race = 1
  },
  [79] = {
    id = 79,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    Race = 1
  },
  [80] = {
    id = 80,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    Race = 1
  },
  [82] = {
    id = 82,
    ItemID = 46081,
    Icon = "Hair1_Cat_Female",
    HairFront = "Hair_front_Cat_82",
    HairBack = "Hair_back_Cat_82",
    DefaultColor = 2,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    OnSale = 1,
    Race = 2,
    DefaultIconColor = 6
  },
  [83] = {
    id = 83,
    ItemID = 46082,
    Icon = "Hair2_Cat_Female",
    HairFront = "Hair_front_Cat_83",
    HairBack = "Hair_back_Cat_83",
    DefaultColor = 4,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    OnSale = 1,
    Race = 2,
    DefaultIconColor = 9
  },
  [84] = {
    id = 84,
    ItemID = 46083,
    Icon = "Hair3_Cat_Female",
    HairFront = "Hair_front_Cat_84",
    HairBack = "Hair_back_Cat_84",
    DefaultColor = 6,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    OnSale = 1,
    Race = 2,
    DefaultIconColor = 2
  },
  [85] = {
    id = 85,
    ItemID = 46084,
    Icon = "Hair4_Cat_Female",
    HairFront = "Hair_front_Cat_85",
    HairBack = "Hair_back_Cat_85",
    DefaultColor = 8,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    OnSale = 1,
    Race = 2,
    DefaultIconColor = 2
  },
  [86] = {
    id = 86,
    ItemID = 46085,
    Icon = "Hair5_Cat_Female",
    HairFront = "Hair_front_Cat_86",
    HairBack = "Hair_back_Cat_86",
    DefaultColor = 1,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    OnSale = 1,
    Race = 2,
    DefaultIconColor = 8
  },
  [87] = {
    id = 87,
    ItemID = 46086,
    Icon = "Hair6_Cat_Female",
    HairFront = "Hair_front_Cat_87",
    HairBack = "Hair_back_Cat_87",
    DefaultColor = 5,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    OnSale = 1,
    Race = 2,
    DefaultIconColor = 5
  },
  [88] = {
    id = 88,
    ItemID = 46087,
    Icon = "Hair7_Cat_Female",
    HairFront = "Hair_front_Cat_88",
    HairBack = "Hair_back_Cat_88",
    DefaultColor = 6,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    Race = 2,
    DefaultIconColor = 6
  },
  [89] = {
    id = 89,
    ItemID = 46088,
    Icon = "Hair8_Cat_Female",
    HairFront = "Hair_front_Cat_89",
    HairBack = "Hair_back_Cat_89",
    DefaultColor = 5,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    Race = 2,
    DefaultIconColor = 5
  },
  [90] = {
    id = 90,
    ItemID = 46089,
    Icon = "Hair9_Cat_Female",
    HairFront = "Hair_front_Cat_90",
    HairBack = "Hair_back_Cat_90",
    DefaultColor = 3,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    Race = 2,
    DefaultIconColor = 3
  },
  [91] = {
    id = 91,
    ItemID = 46090,
    Icon = "Hair10_Cat_Female",
    HairFront = "Hair_front_Cat_91",
    HairBack = "Hair_back_Cat_91",
    DefaultColor = 2,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    Race = 2,
    DefaultIconColor = 2
  },
  [92] = {
    id = 92,
    ItemID = 46091,
    Icon = "Hair1_Cat_Male",
    HairFront = "Hair_front_Cat_92",
    HairBack = "Hair_back_Cat_92",
    DefaultColor = 7,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 1,
    IsPro = 1,
    OnSale = 1,
    Race = 2,
    DefaultIconColor = 6
  },
  [93] = {
    id = 93,
    ItemID = 46092,
    Icon = "Hair2_Cat_Male",
    HairFront = "Hair_front_Cat_93",
    HairBack = "Hair_back_Cat_93",
    DefaultColor = 6,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 1,
    IsPro = 1,
    OnSale = 1,
    Race = 2,
    DefaultIconColor = 7
  },
  [94] = {
    id = 94,
    ItemID = 46093,
    Icon = "Hair3_Cat_Male",
    HairFront = "Hair_front_Cat_94",
    HairBack = "Hair_back_Cat_94",
    DefaultColor = 1,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 1,
    IsPro = 1,
    OnSale = 1,
    Race = 2,
    DefaultIconColor = 8
  },
  [95] = {
    id = 95,
    ItemID = 46094,
    Icon = "Hair4_Cat_Male",
    HairFront = "Hair_front_Cat_95",
    HairBack = "Hair_back_Cat_95",
    DefaultColor = 1,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 1,
    IsPro = 1,
    OnSale = 1,
    Race = 2,
    DefaultIconColor = 2
  },
  [96] = {
    id = 96,
    ItemID = 46095,
    Icon = "Hair5_Cat_Male",
    HairFront = "Hair_front_Cat_96",
    HairBack = "Hair_back_Cat_96",
    DefaultColor = 1,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 1,
    IsPro = 1,
    OnSale = 1,
    Race = 2,
    DefaultIconColor = 1
  },
  [97] = {
    id = 97,
    ItemID = 46096,
    Icon = "Hair6_Cat_Male",
    HairFront = "Hair_front_Cat_97",
    HairBack = "Hair_back_Cat_97",
    DefaultColor = 6,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 1,
    IsPro = 1,
    OnSale = 1,
    Race = 2,
    DefaultIconColor = 1
  },
  [98] = {
    id = 98,
    ItemID = 46097,
    Icon = "Hair7_Cat_Male",
    HairFront = "Hair_front_Cat_98",
    HairBack = "Hair_back_Cat_98",
    DefaultColor = 3,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 1,
    IsPro = 1,
    Race = 2,
    DefaultIconColor = 3
  },
  [99] = {
    id = 99,
    ItemID = 46098,
    Icon = "Hair8_Cat_Male",
    HairFront = "Hair_front_Cat_99",
    HairBack = "Hair_back_Cat_99",
    DefaultColor = 8,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 1,
    IsPro = 1,
    Race = 2,
    DefaultIconColor = 8
  },
  [100] = {
    id = 100,
    ItemID = 46099,
    Icon = "Hair9_Cat_Male",
    HairFront = "Hair_front_Cat_100",
    HairBack = "Hair_back_Cat_100",
    DefaultColor = 2,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 1,
    IsPro = 1,
    Race = 2,
    DefaultIconColor = 2
  },
  [101] = {
    id = 101,
    ItemID = 46100,
    Icon = "Hair10_Cat_Male",
    HairFront = "Hair_front_Cat_101",
    HairBack = "Hair_back_Cat_101",
    DefaultColor = 3,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 1,
    IsPro = 1,
    Race = 2,
    DefaultIconColor = 3
  },
  [110] = {
    id = 110,
    Icon = "Hair7_Cat_Male",
    Sex = 1,
    Race = 2
  },
  [111] = {
    id = 111,
    Icon = "Hair8_Cat_Male",
    Sex = 1,
    Race = 2
  },
  [112] = {
    id = 112,
    Icon = "Hair9_Cat_Male",
    Sex = 1,
    Race = 2
  },
  [113] = {
    id = 113,
    Icon = "Hair8_Cat_Female",
    Sex = 2,
    Race = 2
  },
  [114] = {
    id = 114,
    Icon = "Hair9_Cat_Female",
    Sex = 2,
    Race = 2
  },
  [115] = {
    id = 115,
    Icon = "Hair10_Cat_Female",
    Sex = 2,
    Race = 2
  },
  [116] = {
    id = 116,
    Icon = "Hair11_Cat_Female",
    HairFront = "Hair_front_Cat_116",
    HairBack = "Hair_back_Cat_116",
    Sex = 2,
    Race = 2
  },
  [117] = {
    id = 117,
    HairFront = "Fang_hair_M_3002578",
    HairBack = "Fang_hair_M_3002578_back",
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 1,
    IsPro = 1,
    Race = 1,
    Feature = 1
  },
  [118] = {
    id = 118,
    HairFront = "Hair_front_118",
    HairBack = "Hair_front_118_back",
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    Race = 1,
    Feature = 1
  },
  [119] = {
    id = 119,
    HairFront = "Fang_hair_M_3002578",
    HairBack = "Fang_hair_M_3002578_back",
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 1,
    IsPro = 1,
    Race = 2,
    Feature = 1
  },
  [120] = {
    id = 120,
    HairFront = "Hair_front_Cat_120",
    HairBack = "Hair_front_Cat_120_back",
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    Race = 2,
    Feature = 1
  },
  [121] = {
    id = 121,
    ItemID = 3002578,
    Icon = "item_3002578",
    HairFront = "Fang_hair_M_3002578",
    HairBack = "Fang_hair_M_3002578_back",
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 1,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Feature = 1
  },
  [122] = {
    id = 122,
    ItemID = 3002579,
    Icon = "item_3002579",
    HairFront = "Long_hair_F_3002579",
    HairBack = "Long_hair_F_3002579_back",
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Feature = 1
  },
  [123] = {
    id = 123,
    ItemID = 3003054,
    Icon = "item_3002578",
    HairFront = "Fang_hair_M_3002578",
    HairBack = "Fang_hair_M_3002578_back",
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 1,
    IsPro = 1,
    OnSale = 1,
    Race = 2,
    Feature = 1
  },
  [124] = {
    id = 124,
    ItemID = 3003055,
    Icon = "item_3002579",
    HairFront = "Long_hair_F_3002579",
    HairBack = "Long_hair_F_3002579_back",
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    OnSale = 1,
    Race = 2,
    Feature = 1
  },
  [127] = {
    id = 127,
    ItemID = 46101,
    Icon = "item_46101",
    HairFront = "hr_m_001_46101",
    HairBack = "hr_m_001_46101_back",
    DefaultColor = 2,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 1,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    DefaultIconColor = 2
  },
  [128] = {
    id = 128,
    ItemID = 46102,
    Icon = "item_46102",
    HairFront = "hr_f_001_46102",
    HairBack = "hr_f_001_46102_back",
    DefaultColor = 2,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    DefaultIconColor = 2
  },
  [129] = {
    id = 129,
    ItemID = 46103,
    Icon = "item_46103",
    HairFront = "hr_dm_001_46103",
    HairBack = "hr_dm_001_46103_back",
    DefaultColor = 2,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 1,
    IsPro = 1,
    OnSale = 1,
    Race = 2,
    DefaultIconColor = 2
  },
  [130] = {
    id = 130,
    ItemID = 46104,
    Icon = "item_46104",
    HairFront = "hr_df_001_46104",
    HairBack = "hr_df_001_46104_back",
    DefaultColor = 2,
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    OnSale = 1,
    Race = 2,
    DefaultIconColor = 2
  },
  [995] = {
    id = 995,
    HairFront = "Hair_front_Cat_995",
    Race = 2
  },
  [996] = {
    id = 996,
    HairFront = "Hair_front_Cat_996",
    HairBack = "Hair_back_Cat_996",
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    Race = 2
  },
  [997] = {
    id = 997,
    HairFront = "Hair_front_Cat_997",
    HairBack = "Hair_back_Cat_997",
    PaintColor = Table_HairStyle_t.PaintColor[1],
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 1,
    IsPro = 1,
    Race = 2
  },
  [998] = {
    id = 998,
    Icon = "hair_1",
    HairFront = "Hair_front_998",
    DefaultColor = 1,
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 1,
    IsPro = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 1
  },
  [999] = {
    id = 999,
    Icon = "hair_1",
    HairFront = "Hair_front_999",
    HairBack = "Hair_back_999",
    DefaultColor = 5,
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    Race = 1,
    Version = 1,
    DefaultIconColor = 5
  },
  [1001] = {
    id = 1001,
    Icon = "hair_1",
    HairFront = "Hair_front_91M",
    HairAdornment = "s",
    DefaultColor = 4,
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 1,
    IsPro = 1,
    Race = 1,
    DefaultIconColor = 4
  },
  [1002] = {
    id = 1002,
    Icon = "hair_1",
    HairFront = "Hair_front_92W",
    DefaultColor = 3,
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    Race = 1,
    DefaultIconColor = 3
  },
  [1003] = {
    id = 1003,
    Icon = "hair_1",
    HairFront = "Hair_front_92G",
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    Race = 1
  },
  [1004] = {
    id = 1004,
    Icon = "hair_1",
    HairFront = "Hair_front_91B",
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 1,
    IsPro = 1,
    Race = 1
  },
  [1008] = {
    id = 1008,
    Icon = "hair_1",
    HairFront = "Hair_front_92G",
    DefaultColor = 5,
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    Race = 1,
    DefaultIconColor = 5
  },
  [1012] = {
    id = 1012,
    Icon = "hair_1",
    HairFront = "Hair_front_91F",
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 1,
    IsPro = 1,
    Race = 1
  },
  [1013] = {
    id = 1013,
    Icon = "hair_1",
    HairFront = "Hair_front_92S",
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    Race = 1
  },
  [1014] = {
    id = 1014,
    Icon = "hair_1",
    HairFront = "Hair_front_91E",
    DefaultColor = 1,
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 1,
    IsPro = 1,
    Race = 1,
    DefaultIconColor = 1
  },
  [1015] = {
    id = 1015,
    Icon = "hair_1",
    HairFront = "Hair_front_92C",
    DefaultColor = 2,
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    Race = 1,
    DefaultIconColor = 2
  },
  [1016] = {
    id = 1016,
    Icon = "hair_1",
    HairFront = "Hair_front_92",
    DefaultColor = 6,
    Sex = 2,
    IsPro = 1,
    Race = 1,
    DefaultIconColor = 6
  },
  [1020] = {
    id = 1020,
    Icon = "hair_1",
    HairFront = "Hair_front_92Rachel",
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 2,
    IsPro = 1,
    Race = 1
  },
  [1024] = {
    id = 1024,
    Icon = "hair_1",
    HairFront = "Hair_front_91L",
    AvatarColor = Table_HairStyle_t.AvatarColor[1],
    Sex = 1,
    IsPro = 1,
    Race = 1
  },
  [1073] = {
    id = 1073,
    Icon = "hair_1",
    HairFront = "Hair_front_92E",
    Sex = 2,
    IsPro = 1,
    Race = 1
  },
  [1087] = {
    id = 1087,
    Icon = "hair_1",
    HairFront = "MissSmile_front_92mile",
    DefaultColor = 3,
    Sex = 2,
    IsPro = 1,
    Race = 1,
    DefaultIconColor = 3
  },
  [1088] = {
    id = 1088,
    Icon = "hair_1",
    HairFront = "Hair_front_92G",
    DefaultColor = 3,
    Sex = 2,
    IsPro = 1,
    Race = 1,
    DefaultIconColor = 3
  },
  [1091] = {
    id = 1091,
    Icon = "hair_1",
    HairFront = "Hair_front_9Eden",
    IsPro = 1,
    Race = 1
  },
  [1100] = {
    id = 1100,
    Icon = "hair_1",
    HairFront = "Hair_front_9Man2",
    DefaultColor = 3,
    IsPro = 1,
    Race = 1,
    DefaultIconColor = 3
  },
  [1101] = {
    id = 1101,
    Icon = "hair_1",
    HairFront = "Hair_front_9Woman2",
    DefaultColor = 2,
    IsPro = 1,
    Race = 1,
    DefaultIconColor = 2
  },
  [1102] = {
    id = 1102,
    Icon = "hair_1",
    HairFront = "Hair_front_9Man3",
    DefaultColor = 3,
    IsPro = 1,
    Race = 1,
    DefaultIconColor = 3
  },
  [1103] = {
    id = 1103,
    Icon = "hair_1",
    HairFront = "Hair_front_9M",
    DefaultColor = 3,
    IsPro = 1,
    Race = 1,
    DefaultIconColor = 3
  },
  [1104] = {
    id = 1104,
    HairFront = "Hair_front_9C",
    Race = 1
  },
  [1105] = {
    id = 1105,
    HairFront = "Hair_front_9C",
    Race = 1
  },
  [1106] = {
    id = 1106,
    Icon = "hair_1",
    Race = 1
  },
  [1362] = {
    id = 1362,
    Icon = "hair_1",
    HairFront = "Hair_front_9ka",
    Race = 1
  },
  [1363] = {
    id = 1363,
    Icon = "hair_1",
    HairFront = "Hair_front_9ma",
    Race = 1
  },
  [1364] = {id = 1364, Race = 1},
  [1365] = {id = 1365, Race = 1},
  [1366] = {id = 1366, Race = 1},
  [1367] = {id = 1367, Race = 1},
  [1368] = {id = 1368, Race = 1},
  [1369] = {id = 1369, Race = 1},
  [1370] = {id = 1370, Race = 1},
  [1371] = {id = 1371, Race = 1},
  [1372] = {id = 1372, Race = 1},
  [1373] = {id = 1373, Race = 1},
  [1374] = {id = 1374, Race = 1},
  [1375] = {id = 1375, Race = 1},
  [1376] = {id = 1376, Race = 1},
  [1377] = {id = 1377, Race = 1},
  [1378] = {id = 1378, Race = 1},
  [1379] = {id = 1379, Race = 1},
  [1380] = {id = 1380, Race = 1},
  [1381] = {id = 1381, Race = 1},
  [1382] = {id = 1382, Race = 1},
  [1383] = {id = 1383, Race = 1},
  [1384] = {id = 1384, Race = 1},
  [1386] = {id = 1386, Race = 1},
  [1388] = {id = 1388, Race = 1},
  [1390] = {id = 1390, Race = 1},
  [1391] = {
    id = 1391,
    HairFront = "Nile_pope_Hair_front",
    HairBack = "Nile_pope_Hair_back",
    Race = 1
  },
  [1392] = {id = 1392, Race = 1},
  [1393] = {id = 1393, Race = 1},
  [1394] = {id = 1394, Race = 1},
  [1395] = {id = 1395, Race = 1},
  [1396] = {id = 1396},
  [1397] = {id = 1397},
  [1399] = {id = 1399},
  [1401] = {id = 1401},
  [1402] = {id = 1402},
  [1407] = {id = 1407},
  [1408] = {id = 1408},
  [1409] = {id = 1409},
  [1410] = {id = 1410},
  [1411] = {id = 1411},
  [1412] = {
    id = 1412,
    ItemID = 3002575,
    Icon = "item_3002575",
    HairFront = "Gourry_hair_3002575",
    HairBack = "Gourry_hair_3002575_back",
    Sex = 1,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Feature = 3
  },
  [1413] = {
    id = 1413,
    ItemID = 3002576,
    Icon = "item_3002576",
    HairFront = "Lina_hair_3002576",
    HairBack = "Lina_hair_3002576_back",
    Sex = 2,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Feature = 3
  },
  [1414] = {
    id = 1414,
    ItemID = 3002582,
    Icon = "item_3002577",
    HairFront = "Naga_hair_3002577",
    HairBack = "Naga_hair_3002577_back",
    Sex = 2,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Feature = 3
  },
  [1415] = {
    id = 1415,
    ItemID = 3002580,
    Icon = "item_3002580",
    HairFront = "Xelloss_hair_3002580",
    HairBack = "Xelloss_hair_3002580_back",
    Sex = 1,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Feature = 2
  },
  [1416] = {
    id = 1416,
    ItemID = 3002581,
    Icon = "item_3002581",
    HairFront = "Zelgadiss_hair_3002581",
    HairBack = "Zelgadiss_hair_3002581_back",
    Sex = 1,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Feature = 2
  },
  [1417] = {
    id = 1417,
    ItemID = 3002577,
    Icon = "item_3002582",
    HairFront = "Ameria_hair_3002582",
    HairBack = "Ameria_hair_3002582_back",
    Sex = 2,
    IsPro = 1,
    OnSale = 1,
    Race = 1,
    Feature = 2
  },
  [1418] = {
    id = 1418,
    ItemID = 3003051,
    Icon = "item_3002575",
    HairFront = "Gourry_hair_3002575",
    HairBack = "Gourry_hair_3002575_back",
    Sex = 1,
    IsPro = 1,
    OnSale = 1,
    Race = 2,
    Feature = 3
  },
  [1419] = {
    id = 1419,
    ItemID = 3003052,
    Icon = "item_3002576",
    HairFront = "Lina_hair_3002576",
    HairBack = "Lina_hair_3002576_back",
    Sex = 2,
    IsPro = 1,
    OnSale = 1,
    Race = 2,
    Feature = 3
  },
  [1420] = {
    id = 1420,
    ItemID = 3003058,
    Icon = "item_3002577",
    HairFront = "Naga_hair_3002577",
    HairBack = "Naga_hair_3002577_back",
    Sex = 2,
    IsPro = 1,
    OnSale = 1,
    Race = 2,
    Feature = 3
  },
  [1421] = {
    id = 1421,
    ItemID = 3003056,
    Icon = "item_3002580",
    HairFront = "Xelloss_hair_3002580",
    HairBack = "Xelloss_hair_3002580_back",
    Sex = 1,
    IsPro = 1,
    OnSale = 1,
    Race = 2,
    Feature = 2
  },
  [1422] = {
    id = 1422,
    ItemID = 3003057,
    Icon = "item_3002581",
    HairFront = "Zelgadiss_hair_3002581",
    HairBack = "Zelgadiss_hair_3002581_back",
    Sex = 1,
    IsPro = 1,
    OnSale = 1,
    Race = 2,
    Feature = 2
  },
  [1423] = {
    id = 1423,
    ItemID = 3003053,
    Icon = "item_3002582",
    HairFront = "Ameria_hair_3002582",
    HairBack = "Ameria_hair_3002582_back",
    Sex = 2,
    IsPro = 1,
    OnSale = 1,
    Race = 2,
    Feature = 2
  },
  [1424] = {id = 1424},
  [1425] = {id = 1425},
  [1426] = {id = 1426},
  [1427] = {id = 1427},
  [1428] = {id = 1428},
  [1429] = {id = 1429},
  [1430] = {id = 1430},
  [1431] = {id = 1431},
  [1432] = {id = 1432},
  [1435] = {
    id = 1435,
    Icon = "hair_1",
    HairFront = "Hair_front_91E"
  },
  [1436] = {id = 1436},
  [1437] = {id = 1437},
  [1438] = {id = 1438},
  [1439] = {id = 1439},
  [1440] = {id = 1440},
  [1441] = {id = 1441},
  [1442] = {id = 1442},
  [1443] = {id = 1443},
  [1444] = {id = 1444},
  [1445] = {id = 1445},
  [1679] = {
    id = 1679,
    Icon = "hair_1",
    HairFront = "Hair_front_9",
    DefaultColor = 6,
    IsPro = 1,
    Race = 1,
    DefaultIconColor = 6
  },
  [1680] = {
    id = 1680,
    Icon = "hair_1",
    HairFront = "Hair_front_9",
    DefaultColor = 5,
    IsPro = 1,
    Race = 1,
    DefaultIconColor = 5
  },
  [1681] = {
    id = 1681,
    Icon = "hair_1",
    HairFront = "Hair_front_9",
    DefaultColor = 5,
    IsPro = 1,
    Race = 1,
    DefaultIconColor = 5
  },
  [1688] = {id = 1688, Race = 1},
  [1689] = {id = 1689, Race = 1},
  [1693] = {
    id = 1693,
    HairFront = "Hair_front_sailor",
    HairBack = "Hair_back_sailor",
    Race = 1,
    Feature = 1
  },
  [2002] = {
    id = 2002,
    Icon = "hair_1",
    HairFront = "Hair_front_92W",
    Sex = 2,
    IsPro = 1,
    Race = 1
  },
  [10182] = {
    id = 10182,
    Icon = "Hair2_Male",
    Race = 1
  },
  [10183] = {
    id = 10183,
    Icon = "Hair26_Female",
    Race = 1
  },
  [10184] = {
    id = 10184,
    Icon = "Hair27_Female",
    Race = 1
  },
  [10185] = {
    id = 10185,
    Icon = "Hair7_Female",
    Race = 1
  },
  [10186] = {
    id = 10186,
    Icon = "Hair42_Male",
    Race = 1
  },
  [10187] = {
    id = 10187,
    Icon = "Hair1_Male",
    Race = 1
  },
  [20031] = {
    id = 20031,
    Icon = "Hair8_Female",
    Race = 1
  },
  [30051] = {
    id = 30051,
    Icon = "Hair4_Female",
    Race = 1
  },
  [30052] = {
    id = 30052,
    Icon = "Hair4_Female_6d",
    Race = 1
  },
  [30053] = {
    id = 30053,
    Icon = "Hair51_Female_d",
    Race = 1
  },
  [30054] = {id = 30054, Race = 1},
  [294453] = {id = 294453}
}
local cell_mt = {
  __index = {
    AvatarColor = _EmptyTable,
    HairAdornment = "",
    HairBack = "",
    HairFront = "",
    Icon = "",
    PaintColor = _EmptyTable,
    id = 1
  }
}
for _, d in pairs(Table_HairStyle) do
  setmetatable(d, cell_mt)
end
