Table_FuncState = {
  [16] = {
    id = 16,
    Type = "monengguanzhu",
    Param = _EmptyTable,
    TimeID = 132,
    ServerID = {
      1,
      2,
      3,
      4,
      5,
      6
    },
    NpcFunction = _EmptyTable,
    NpcID = _EmptyTable,
    QuestID = _EmptyTable,
    ShopItemID = _EmptyTable,
    ItemID = {
      62570,
      62571,
      62572,
      62573
    },
    MapID = _EmptyTable,
    MenuID = _EmptyTable
  },
  [17] = {
    id = 17,
    Type = "polly",
    Param = _EmptyTable,
    TimeID = 101,
    ServerID = {1},
    NpcFunction = _EmptyTable,
    NpcID = {1708},
    QuestID = _EmptyTable,
    ShopItemID = _EmptyTable,
    ItemID = _EmptyTable,
    MapID = _EmptyTable,
    MenuID = _EmptyTable
  },
  [120] = {
    id = 120,
    Type = "rollcoin",
    Param = _EmptyTable,
    TimeID = 101,
    ServerID = {1},
    NpcFunction = _EmptyTable,
    NpcID = _EmptyTable,
    QuestID = _EmptyTable,
    ShopItemID = {
      92690,
      201320,
      1932867,
      1934827
    },
    ItemID = {5690},
    MapID = _EmptyTable,
    MenuID = _EmptyTable
  },
  [122] = {
    id = 122,
    Type = "dojo",
    Param = _EmptyTable,
    TimeID = 101,
    ServerID = {1},
    NpcFunction = _EmptyTable,
    NpcID = {1604},
    QuestID = _EmptyTable,
    ShopItemID = _EmptyTable,
    ItemID = _EmptyTable,
    MapID = _EmptyTable,
    MenuID = _EmptyTable
  },
  [160] = {
    id = 160,
    Type = "",
    Param = _EmptyTable,
    TimeID = 101,
    ServerID = {1},
    NpcFunction = _EmptyTable,
    NpcID = _EmptyTable,
    QuestID = _EmptyTable,
    ShopItemID = _EmptyTable,
    ItemID = _EmptyTable,
    MapID = _EmptyTable,
    MenuID = _EmptyTable
  },
  [161] = {
    id = 161,
    Type = "",
    Param = _EmptyTable,
    TimeID = 101,
    ServerID = {1},
    NpcFunction = _EmptyTable,
    NpcID = _EmptyTable,
    QuestID = {},
    ShopItemID = _EmptyTable,
    ItemID = _EmptyTable,
    MapID = _EmptyTable,
    MenuID = _EmptyTable
  },
  [169] = {
    id = 169,
    Type = "trade_preorder",
    Param = _EmptyTable,
    TimeID = 130,
    ServerID = {
      1,
      2,
      3,
      4,
      5,
      6
    },
    NpcFunction = _EmptyTable,
    NpcID = _EmptyTable,
    QuestID = _EmptyTable,
    ShopItemID = _EmptyTable,
    ItemID = _EmptyTable,
    MapID = _EmptyTable,
    MenuID = _EmptyTable
  },
  [1000] = {
    id = 1000,
    Type = "personal_artifact_forbidden",
    Param = _EmptyTable,
    TimeID = 101,
    ServerID = {1},
    NpcFunction = {3303, 11015},
    NpcID = {816440},
    QuestID = _EmptyTable,
    ShopItemID = _EmptyTable,
    ItemID = _EmptyTable,
    MapID = _EmptyTable,
    MenuID = {10016}
  },
  [1001] = {
    id = 1001,
    Type = "extraction_forbidden",
    Param = _EmptyTable,
    TimeID = 101,
    ServerID = {1},
    NpcFunction = _EmptyTable,
    NpcID = _EmptyTable,
    QuestID = {399950001},
    ShopItemID = _EmptyTable,
    ItemID = _EmptyTable,
    MapID = _EmptyTable,
    MenuID = {10004}
  },
  [1002] = {
    id = 1002,
    Type = "vice_equip_forbidden",
    Param = {
      1,
      2,
      3,
      4,
      5,
      6
    },
    TimeID = 101,
    ServerID = {1},
    NpcFunction = _EmptyTable,
    NpcID = _EmptyTable,
    QuestID = _EmptyTable,
    ShopItemID = _EmptyTable,
    ItemID = _EmptyTable,
    MapID = _EmptyTable,
    MenuID = {
      19068,
      19069,
      19070
    }
  },
  [1003] = {
    id = 1003,
    Type = "lottery_forbidden",
    Param = {
      1,
      5,
      6,
      7,
      9,
      10,
      11,
      12,
      13,
      31,
      32
    },
    TimeID = 101,
    ServerID = {1},
    NpcFunction = {
      2200,
      2201,
      2203,
      2205,
      10126,
      11016
    },
    NpcID = {
      1695,
      1696,
      1697,
      5106,
      827816,
      827817,
      827818,
      827819,
      827820,
      827821,
      827822,
      827823,
      827824
    },
    QuestID = _EmptyTable,
    ShopItemID = _EmptyTable,
    ItemID = _EmptyTable,
    MapID = _EmptyTable,
    MenuID = _EmptyTable
  },
  [1005] = {
    id = 1005,
    Type = "gem_forbidden",
    Param = {
      14,
      15,
      21
    },
    TimeID = 101,
    ServerID = {1},
    NpcFunction = {
      10026,
      10027,
      10028,
      10033,
      10037,
      3248,
      11014
    },
    NpcID = {806039, 806040},
    QuestID = {398990001, 398990001},
    ShopItemID = _EmptyTable,
    ItemID = _EmptyTable,
    MapID = _EmptyTable,
    MenuID = {6210}
  },
  [1007] = {
    id = 1007,
    Type = "enchant_transfer_forbidden",
    Param = _EmptyTable,
    TimeID = 101,
    ServerID = {1},
    NpcFunction = _EmptyTable,
    NpcID = _EmptyTable,
    QuestID = _EmptyTable,
    ShopItemID = _EmptyTable,
    ItemID = _EmptyTable,
    MapID = _EmptyTable,
    MenuID = _EmptyTable
  },
  [1008] = {
    id = 1008,
    Type = "recover_shadow_equip_forbidden",
    Param = _EmptyTable,
    TimeID = 101,
    ServerID = {1},
    NpcFunction = {11020},
    NpcID = _EmptyTable,
    QuestID = {1006540002},
    ShopItemID = _EmptyTable,
    ItemID = _EmptyTable,
    MapID = _EmptyTable,
    MenuID = _EmptyTable
  },
  [1009] = {
    id = 1009,
    Type = "equip_compose_forbidden",
    Param = _EmptyTable,
    TimeID = 175,
    ServerID = {1},
    NpcFunction = _EmptyTable,
    NpcID = _EmptyTable,
    QuestID = _EmptyTable,
    ShopItemID = _EmptyTable,
    ItemID = {
      40359,
      140359,
      40055,
      140055,
      40360,
      140360,
      40059,
      140059,
      40057,
      140057,
      40361,
      140361,
      40058,
      140058,
      41254,
      141254,
      41255,
      141255,
      41256,
      141256,
      41257,
      141257,
      40660,
      140660,
      40661,
      140661,
      40662,
      140662,
      40766,
      140766,
      40944,
      140944,
      40945,
      140945,
      41258,
      141258,
      40767,
      140767,
      62540,
      162540,
      62541,
      162541,
      62542,
      162542,
      41867,
      141867,
      41868,
      141868,
      41869,
      141869,
      41870,
      141870,
      40663,
      140663,
      41565,
      141565,
      41568,
      141568,
      41566,
      141566,
      41567,
      141567,
      41871,
      141871,
      40066,
      140066,
      40671,
      140671,
      63440,
      163440,
      62840,
      162840,
      63140,
      163140,
      63444,
      163444,
      63144,
      163144,
      62844,
      162844,
      40676,
      140676,
      62551,
      162551
    },
    MapID = _EmptyTable,
    MenuID = _EmptyTable
  },
  [1010] = {
    id = 1010,
    Type = "pray_forbidden",
    Param = {4, 5},
    TimeID = 101,
    ServerID = {1},
    NpcFunction = {4039, 4044},
    NpcID = _EmptyTable,
    QuestID = _EmptyTable,
    ShopItemID = _EmptyTable,
    ItemID = _EmptyTable,
    MapID = _EmptyTable,
    MenuID = {18204, 18207}
  },
  [1012] = {
    id = 1012,
    Type = "tutor_system_forbidden",
    Param = _EmptyTable,
    TimeID = 101,
    ServerID = {1},
    NpcFunction = {3255},
    NpcID = {
      6769,
      6770,
      6773
    },
    QuestID = {391010001},
    ShopItemID = _EmptyTable,
    ItemID = _EmptyTable,
    MapID = _EmptyTable,
    MenuID = {9000, 9001}
  },
  [1013] = {
    id = 1013,
    Type = "deadboss_forbidden",
    Param = _EmptyTable,
    TimeID = 101,
    ServerID = {1},
    NpcFunction = _EmptyTable,
    NpcID = _EmptyTable,
    QuestID = {398000003},
    ShopItemID = _EmptyTable,
    ItemID = _EmptyTable,
    MapID = _EmptyTable,
    MenuID = {6101}
  },
  [1014] = {
    id = 1014,
    Type = "triple_pvp",
    Param = _EmptyTable,
    TimeID = 101,
    ServerID = {1},
    NpcFunction = _EmptyTable,
    NpcID = _EmptyTable,
    QuestID = _EmptyTable,
    ShopItemID = _EmptyTable,
    ItemID = _EmptyTable,
    MapID = _EmptyTable,
    MenuID = _EmptyTable
  },
  [1015] = {
    id = 1015,
    Type = "ancient_equip_forbidden",
    Param = _EmptyTable,
    TimeID = 101,
    ServerID = {1},
    NpcFunction = _EmptyTable,
    NpcID = _EmptyTable,
    QuestID = _EmptyTable,
    ShopItemID = _EmptyTable,
    ItemID = _EmptyTable,
    MapID = _EmptyTable,
    MenuID = _EmptyTable
  },
  [1016] = {
    id = 1016,
    Type = "exchange_type_forbidden",
    Param = {47},
    TimeID = 101,
    ServerID = {1},
    NpcFunction = _EmptyTable,
    NpcID = _EmptyTable,
    QuestID = _EmptyTable,
    ShopItemID = _EmptyTable,
    ItemID = _EmptyTable,
    MapID = _EmptyTable,
    MenuID = _EmptyTable
  },
  [1017] = {
    id = 1017,
    Type = "tutor_class_forbidden",
    Param = _EmptyTable,
    TimeID = 101,
    ServerID = {1},
    NpcFunction = _EmptyTable,
    NpcID = {
      816309,
      821769,
      803262,
      813150,
      826553
    },
    QuestID = _EmptyTable,
    ShopItemID = _EmptyTable,
    ItemID = _EmptyTable,
    MapID = _EmptyTable,
    MenuID = _EmptyTable
  },
  [1018] = {
    id = 1018,
    Type = "TwelvePvp",
    Param = _EmptyTable,
    TimeID = 101,
    ServerID = {1},
    NpcFunction = _EmptyTable,
    NpcID = _EmptyTable,
    QuestID = {207640001},
    ShopItemID = _EmptyTable,
    ItemID = _EmptyTable,
    MapID = _EmptyTable,
    MenuID = _EmptyTable
  },
  [1019] = {
    id = 1019,
    Type = "battletime_music",
    Param = _EmptyTable,
    TimeID = 101,
    ServerID = {1},
    NpcFunction = _EmptyTable,
    NpcID = _EmptyTable,
    QuestID = _EmptyTable,
    ShopItemID = _EmptyTable,
    ItemID = _EmptyTable,
    MapID = _EmptyTable,
    MenuID = _EmptyTable
  },
  [1020] = {
    id = 1020,
    Type = "Auction",
    Param = _EmptyTable,
    TimeID = 101,
    ServerID = {1},
    NpcFunction = _EmptyTable,
    NpcID = {6647},
    QuestID = _EmptyTable,
    ShopItemID = _EmptyTable,
    ItemID = _EmptyTable,
    MapID = _EmptyTable,
    MenuID = _EmptyTable
  },
  [1021] = {
    id = 1021,
    Type = "mvpbattle",
    Param = _EmptyTable,
    TimeID = 102,
    ServerID = {1},
    NpcFunction = _EmptyTable,
    NpcID = {7900},
    QuestID = _EmptyTable,
    ShopItemID = _EmptyTable,
    ItemID = _EmptyTable,
    MapID = _EmptyTable,
    MenuID = _EmptyTable
  },
  [1022] = {
    id = 1022,
    Type = "adventureOneClick_forbidden",
    Param = _EmptyTable,
    TimeID = 101,
    ServerID = {1},
    NpcFunction = _EmptyTable,
    NpcID = _EmptyTable,
    QuestID = _EmptyTable,
    ShopItemID = _EmptyTable,
    ItemID = _EmptyTable,
    MapID = _EmptyTable,
    MenuID = _EmptyTable
  },
  [1023] = {
    id = 1023,
    Type = "monengguanzhu_novice_npc",
    Param = _EmptyTable,
    TimeID = 101,
    ServerID = {1},
    NpcFunction = _EmptyTable,
    NpcID = {
      4865,
      826609,
      805185,
      4864
    },
    QuestID = _EmptyTable,
    ShopItemID = _EmptyTable,
    ItemID = _EmptyTable,
    MapID = _EmptyTable,
    MenuID = _EmptyTable
  },
  [152] = {
    id = 152,
    Type = "interact_npc",
    Param = {808454},
    TimeID = 113,
    ServerID = {
      1,
      2,
      3,
      4,
      5,
      6
    },
    NpcFunction = _EmptyTable,
    NpcID = _EmptyTable,
    QuestID = _EmptyTable,
    ShopItemID = _EmptyTable,
    ItemID = _EmptyTable,
    MapID = _EmptyTable,
    MenuID = _EmptyTable
  },
  [153] = {
    id = 153,
    Type = "interact_npc",
    Param = {808455},
    TimeID = 113,
    ServerID = {
      1,
      2,
      3,
      4,
      5,
      6
    },
    NpcFunction = _EmptyTable,
    NpcID = _EmptyTable,
    QuestID = _EmptyTable,
    ShopItemID = _EmptyTable,
    ItemID = _EmptyTable,
    MapID = _EmptyTable,
    MenuID = _EmptyTable
  },
  [154] = {
    id = 154,
    Type = "interact_npc",
    Param = {808456},
    TimeID = 113,
    ServerID = {
      1,
      2,
      3,
      4,
      5,
      6
    },
    NpcFunction = _EmptyTable,
    NpcID = _EmptyTable,
    QuestID = _EmptyTable,
    ShopItemID = _EmptyTable,
    ItemID = _EmptyTable,
    MapID = _EmptyTable,
    MenuID = _EmptyTable
  },
  [155] = {
    id = 155,
    Type = "interact_npc",
    Param = {808457},
    TimeID = 113,
    ServerID = {
      1,
      2,
      3,
      4,
      5,
      6
    },
    NpcFunction = _EmptyTable,
    NpcID = _EmptyTable,
    QuestID = _EmptyTable,
    ShopItemID = _EmptyTable,
    ItemID = _EmptyTable,
    MapID = _EmptyTable,
    MenuID = _EmptyTable
  },
  [174] = {
    id = 174,
    Type = "report_forbidden",
    Param = _EmptyTable,
    TimeID = 174,
    ServerID = {1},
    NpcFunction = _EmptyTable,
    NpcID = _EmptyTable,
    QuestID = _EmptyTable,
    ShopItemID = _EmptyTable,
    ItemID = _EmptyTable,
    MapID = _EmptyTable,
    MenuID = _EmptyTable
  }
}
Table_FuncState_fields = {
  "id",
  "Type",
  "Param",
  "TimeID",
  "ServerID",
  "NpcFunction",
  "NpcID",
  "QuestID",
  "ShopItemID",
  "ItemID",
  "MapID",
  "MenuID"
}
return Table_FuncState
