ACTHIYPOLLYPARAM = {
  ACTHIYPOLLYPARAM_QUERY_HITPOLLY_LIST = 1,
  ACTHIYPOLLYPARAM_HIT_POLLY = 2,
  ACTHIYPOLLYPARAM_SYNC_ACT = 3,
  ACTHIYPOLLYPARAM_SUBMIT_QUEST = 4,
  ACTHIYPOLLYPARAM_QUEST_NTF = 5
}
EACTHITPOLLYQUESTSTATUS = {
  EACCHITPOLLY_QUEST_NOT_OPEN = 0,
  EACCHITPOLLY_QUEST_ON = 1,
  EACCHITPOLLY_QUEST_SUBMITABLE = 2,
  EACCHITPOLLY_QUEST_FINISH = 3
}
ActHitPolly_pb = {
  ACTHIYPOLLYPARAM_QUERY_HITPOLLY_LIST = 1,
  ACTHIYPOLLYPARAM_HIT_POLLY = 2,
  ACTHIYPOLLYPARAM_SYNC_ACT = 3,
  ACTHIYPOLLYPARAM_SUBMIT_QUEST = 4,
  ACTHIYPOLLYPARAM_QUEST_NTF = 5,
  EACCHITPOLLY_QUEST_NOT_OPEN = 0,
  EACCHITPOLLY_QUEST_ON = 1,
  EACCHITPOLLY_QUEST_SUBMITABLE = 2,
  EACCHITPOLLY_QUEST_FINISH = 3
}
