ACTMINIROPARAM = {
  ACTMINIROPARAM_OPENPAGE = 1,
  ACTMINIROPARAM_CAST_DICE = 2,
  ACTMINIROPARAM_GET_ONEKEY = 3,
  ACTMINIROPARAM_FREEDICE_SYNC = 4,
  ACTMINIROPARAM_EVENT_FAQS = 5,
  ACTMINIROPARAM_CHECK_CIRCLEREWARD = 6
}
EACTMINIRODICETYPE = {EACTMINIRODICETYPE_NORMAL = 1, EACTMINIRODICETYPE_ASSIGN = 2}
ActMiniRoCmd_pb = {
  ACTMINIROPARAM_OPENPAGE = 1,
  ACTMINIROPARAM_CAST_DICE = 2,
  ACTMINIROPARAM_GET_ONEKEY = 3,
  ACTMINIROPARAM_FREEDICE_SYNC = 4,
  ACTMINIROPARAM_EVENT_FAQS = 5,
  ACTMINIROPARAM_CHECK_CIRCLEREWARD = 6,
  EACTMINIRODICETYPE_NORMAL = 1,
  EACTMINIRODICETYPE_ASSIGN = 2
}
