ASTROLABEPARAM = {
  ASTROLABEPARAM_QUERY = 1,
  ASTROLABEPARAM_ACTIVATE_STAR = 2,
  ASTROLABEPARAM_QUERY_RESET = 3,
  ASTROLABEPARAM_RESET = 4,
  ASTROLABEPARAM_PLAN_SAVE = 5
}
EASTROLABETYPE = {
  EASTROLABETYPE_MIN = 0,
  EASTROLABETYPE_PROFESSION = 1,
  EASTROLABETYPE_PLAN = 100,
  EASTROLABETYPE_MAX = 101
}
AstrolabeCmd_pb = {
  ASTROLABEPARAM_QUERY = 1,
  ASTROLABEPARAM_ACTIVATE_STAR = 2,
  ASTROLABEPARAM_QUERY_RESET = 3,
  ASTROLABEPARAM_RESET = 4,
  ASTROLABEPARAM_PLAN_SAVE = 5,
  EASTROLABETYPE_MIN = 0,
  EASTROLABETYPE_PROFESSION = 1,
  EASTROLABETYPE_PLAN = 100,
  EASTROLABETYPE_MAX = 101
}
