EBATTLEPASSPARAM = {
  BATTLEPASS_GET_REWAD = 1,
  BATTLEPASS_UPDATE_REWARD = 2,
  BATTLEPASS_BUY_LEVEL = 3,
  BATTLEPASS_BUY_ADVANCE = 4,
  BATTLEPASS_SYNC_INFO = 5,
  BATTLEPASS_QUEST_INFO = 6
}
BattlePass_pb = {
  BATTLEPASS_GET_REWAD = 1,
  BATTLEPASS_UPDATE_REWARD = 2,
  BATTLEPASS_BUY_LEVEL = 3,
  BATTLEPASS_BUY_ADVANCE = 4,
  BATTLEPASS_SYNC_INFO = 5,
  BATTLEPASS_QUEST_INFO = 6
}
