DOJOPARAM = {
  EDOJOPARAM_DOJO_PRIVATE_INFO = 1,
  EDOJOPARAM_DOJO_PUBLIC_INFO = 2,
  EDOJOPARAM_INVITE = 3,
  EDOJOPARAM_REPLY = 4,
  EDOJOPARAM_ENTERDOJO = 5,
  EDOJOPARAM_ADD_MSG = 6,
  EDOJOPARAM_PANEL_OPER = 7,
  EDOJOPARAM_SPONSOR = 9,
  EDOJOPARAM_QUERYSTATE = 10,
  EDOJOPARAM_REWARD = 11
}
EDOJOREPLY = {EDOJOREPLY_AGREE = 1, EDOJOREPLY_DISAGREE = 2}
DOJOSTATE = {
  DOJOSTATE_NONE = 0,
  DOJOSTATE_SPONSORED = 1,
  DOJOSTATE_OPENED = 2,
  DOJOSTATE_ERROR = 3
}
EPASSTYPE = {
  EPASSTYPE_FIRST = 1,
  EPASSTYPE_HELP = 2,
  EPASSTYPE_NORMAL = 3
}
Dojo_pb = {
  EDOJOPARAM_DOJO_PRIVATE_INFO = 1,
  EDOJOPARAM_DOJO_PUBLIC_INFO = 2,
  EDOJOPARAM_INVITE = 3,
  EDOJOPARAM_REPLY = 4,
  EDOJOPARAM_ENTERDOJO = 5,
  EDOJOPARAM_ADD_MSG = 6,
  EDOJOPARAM_PANEL_OPER = 7,
  EDOJOPARAM_SPONSOR = 9,
  EDOJOPARAM_QUERYSTATE = 10,
  EDOJOPARAM_REWARD = 11,
  EDOJOREPLY_AGREE = 1,
  EDOJOREPLY_DISAGREE = 2,
  DOJOSTATE_NONE = 0,
  DOJOSTATE_SPONSORED = 1,
  DOJOSTATE_OPENED = 2,
  DOJOSTATE_ERROR = 3,
  EPASSTYPE_FIRST = 1,
  EPASSTYPE_HELP = 2,
  EPASSTYPE_NORMAL = 3
}
