FAMILYPARAM = {
  FAMILYPARAM_CLUE_DATA_NTF = 1,
  FAMILYPARAM_CLUE_UNLOCK = 2,
  FAMILYPARAM_CLUE_REWARD = 3
}
EFAMILYCLUESTATE = {
  EFAMILYCLUE_STATE_INIT = 0,
  EFAMILYCLUE_STATE_UNLOCK = 1,
  EFAMILYCLUE_STATE_REWARD = 2
}
FamilyCmd_pb = {
  FAMILYPARAM_CLUE_DATA_NTF = 1,
  FAMILYPARAM_CLUE_UNLOCK = 2,
  FAMILYPARAM_CLUE_REWARD = 3,
  EFAMILYCLUE_STATE_INIT = 0,
  EFAMILYCLUE_STATE_UNLOCK = 1,
  EFAMILYCLUE_STATE_REWARD = 2
}
