GOALPARAM = {
  GOALPARAM_QUERY_LIST = 1,
  GOALPARAM_UPDATE_ITEM = 2,
  GOALPARAM_UPDATE_GROUP = 3,
  GOALPARAM_UPDATE_SCORE = 4,
  GOALPARAM_GET_GROUP_REWARD = 5,
  GOALPARAM_GET_ITEM_SCORE = 6,
  GOALPARAM_GET_SCORE_REWARD = 7
}
EGOALSTATUS = {
  EGOALSTATUS_MIN = 0,
  EGOALSTATUS_ACTIVE = 1,
  EGOALSTATUS_FINISH = 2,
  EGOALSTATUS_MAX = 3
}
GoalCmd_pb = {
  GOALPARAM_QUERY_LIST = 1,
  GOALPARAM_UPDATE_ITEM = 2,
  GOALPARAM_UPDATE_GROUP = 3,
  GOALPARAM_UPDATE_SCORE = 4,
  GOALPARAM_GET_GROUP_REWARD = 5,
  GOALPARAM_GET_ITEM_SCORE = 6,
  GOALPARAM_GET_SCORE_REWARD = 7,
  EGOALSTATUS_MIN = 0,
  EGOALSTATUS_ACTIVE = 1,
  EGOALSTATUS_FINISH = 2,
  EGOALSTATUS_MAX = 3
}
