TOWERPARAM = {
  ETOWERPARAM_TEAMTOWERINFO = 1,
  ETOWERPARAM_TEAMTOWERSUMMARY = 2,
  ETOWERPARAM_INVITE = 3,
  ETOWERPARAM_REPLY = 4,
  ETOWERPARAM_ENTERTOWER = 5,
  ETOWERPARAM_USERTOWERINFO = 7,
  ETOWERPARAM_LAYER_SYNC = 8,
  ETOWERPARAM_NEW_EVERLAYER = 9,
  ETOWERPARAM_TOWERINFO = 10,
  ETOWERPARAM_LAUNCH = 11
}
ETOWERREPLY = {ETOWERREPLY_AGREE = 1, ETOWERREPLY_DISAGREE = 2}
InfiniteTower_pb = {
  ETOWERPARAM_TEAMTOWERINFO = 1,
  ETOWERPARAM_TEAMTOWERSUMMARY = 2,
  ETOWERPARAM_INVITE = 3,
  ETOWERPARAM_REPLY = 4,
  ETOWERPARAM_ENTERTOWER = 5,
  ETOWERPARAM_USERTOWERINFO = 7,
  ETOWERPARAM_LAYER_SYNC = 8,
  ETOWERPARAM_NEW_EVERLAYER = 9,
  ETOWERPARAM_TOWERINFO = 10,
  ETOWERPARAM_LAUNCH = 11,
  ETOWERREPLY_AGREE = 1,
  ETOWERREPLY_DISAGREE = 2
}
