INTERACTPARAM = {
  INTERPARAM_ADD_MOUNT = 1,
  INTERPARAM_DEL_MOUNT = 2,
  INTERPARAM_CONFIRM_MOUNT = 3,
  INTERPARAM_CANCEL_MOUNT = 4,
  INTERPARAM_ADD_MOVE_MOUNT = 5,
  INTERPARAM_DEL_MOVE_MOUNT = 6,
  INTERPARAM_CONFIRM_MOVE_MOUNT = 7,
  INTERPARAM_CANCEL_MOVE_MOUNT = 8,
  INTERPARAM_SYNC_TRAIN_STATUS = 9,
  INTERPARAM_UPDATE_TRAIN_STATE = 10,
  INTERPARAM_UPDATE_POS = 11,
  INTERPARAM_TRAIN_ACTION = 12
}
ETRAINMOVESTATE = {
  ETRAIN_MIN = 0,
  ETRAIN_STOP_OPEN = 1,
  ETRAIN_STOP_CLOSE = 2,
  ETRAIN_MOVE = 3
}
InteractCmd_pb = {
  INTERPARAM_ADD_MOUNT = 1,
  INTERPARAM_DEL_MOUNT = 2,
  INTERPARAM_CONFIRM_MOUNT = 3,
  INTERPARAM_CANCEL_MOUNT = 4,
  INTERPARAM_ADD_MOVE_MOUNT = 5,
  INTERPARAM_DEL_MOVE_MOUNT = 6,
  INTERPARAM_CONFIRM_MOVE_MOUNT = 7,
  INTERPARAM_CANCEL_MOVE_MOUNT = 8,
  INTERPARAM_SYNC_TRAIN_STATUS = 9,
  INTERPARAM_UPDATE_TRAIN_STATE = 10,
  INTERPARAM_UPDATE_POS = 11,
  INTERPARAM_TRAIN_ACTION = 12,
  ETRAIN_MIN = 0,
  ETRAIN_STOP_OPEN = 1,
  ETRAIN_STOP_CLOSE = 2,
  ETRAIN_MOVE = 3
}
