MESSCPARAM = {
  MESSCPARAM_CHOOSE_NEW_PROFESSION = 1,
  MESSCPARAM_INVITER_SEND_LOVE_CONFESSION = 2,
  MESSCPARAM_INVITEE_RECEIVE_LOVE_CONFESSION = 3,
  MESSCPARAM_INVITEE_PROCESS_LOVE_CONFESSION = 4,
  MESSCPARAM_INVITER_RECEIVE_LOVE_CONFESSION = 5,
  MESSCPARAM_FINGER_GUESS_LOVE_CONFESSION = 6,
  MESSCPARAM_FINGER_LOSE_LOVE_CONFESSION = 7,
  MESSCPARAM_INVITER_RESULT_LOVE_CONFESSION = 8,
  SYNC_MAPSTEP_FOREVER_REWARD_INFO = 9,
  BALANCE_MODE_CHOOSE = 10,
  SET_PIPPI_STATE = 11
}
FINGERGUESSITEM = {
  FINGER_GUESS_MIN = 0,
  FINGER_GUESS_ROCK = 1,
  FINGER_GUESS_SCISSORS = 2,
  FINGER_GUESS_PAPER = 3,
  FINGER_GUESS_RANDOM = 4
}
EPIPPISTATE = {
  EPIPPISTATE_LIVE_SHOW = 0,
  EPIPPISTATE_LIVE_HIDE = 1,
  EPIPPISTATE_DIE_SHOW = 2,
  EPIPPISTATE_DIE_HIDE = 3
}
MessCCmd_pb = {
  MESSCPARAM_CHOOSE_NEW_PROFESSION = 1,
  MESSCPARAM_INVITER_SEND_LOVE_CONFESSION = 2,
  MESSCPARAM_INVITEE_RECEIVE_LOVE_CONFESSION = 3,
  MESSCPARAM_INVITEE_PROCESS_LOVE_CONFESSION = 4,
  MESSCPARAM_INVITER_RECEIVE_LOVE_CONFESSION = 5,
  MESSCPARAM_FINGER_GUESS_LOVE_CONFESSION = 6,
  MESSCPARAM_FINGER_LOSE_LOVE_CONFESSION = 7,
  MESSCPARAM_INVITER_RESULT_LOVE_CONFESSION = 8,
  SYNC_MAPSTEP_FOREVER_REWARD_INFO = 9,
  BALANCE_MODE_CHOOSE = 10,
  SET_PIPPI_STATE = 11,
  FINGER_GUESS_MIN = 0,
  FINGER_GUESS_ROCK = 1,
  FINGER_GUESS_SCISSORS = 2,
  FINGER_GUESS_PAPER = 3,
  FINGER_GUESS_RANDOM = 4,
  EPIPPISTATE_LIVE_SHOW = 0,
  EPIPPISTATE_LIVE_HIDE = 1,
  EPIPPISTATE_DIE_SHOW = 2,
  EPIPPISTATE_DIE_HIDE = 3
}
