NOVICENOTEBOOKPARAM = {
  NOVICE_NOTEBOOK_INFO = 1,
  NOVICE_NOTEBOOK_COVER_OPEN = 2,
  NOVICE_NOTEBOOK_READ_PAGE = 3,
  NOVICE_NOTEBOOK_RECEIVE_AWARD = 4,
  NOVICE_NOTEBOOK_LAST_POS = 5
}
NOVICENOTEBOOKCHAPTERTAGSTATE = {
  NOVICE_NOTEBOOK_CHAPTER_TAG_STATE_OPEN = 1,
  NOVICE_NOTEBOOK_CHAPTER_TAG_STATE_CLOSE = 2,
  NOVICE_NOTEBOOK_CHAPTER_TAG_STATE_DISABLE = 3
}
NOVICENOTEBOOKREWARDSTATE = {
  NOVICE_NOTEBOOK_CHAPTER_REWARD_STATE_NOT_AVAILABLE = 1,
  NOVICE_NOTEBOOK_CHAPTER_REWARD_STATE_AVAILABLE = 2,
  NOVICE_NOTEBOOK_CHAPTER_REWARD_STATE_RECEIVED = 3
}
NoviceNotebook_pb = {
  NOVICE_NOTEBOOK_INFO = 1,
  NOVICE_NOTEBOOK_COVER_OPEN = 2,
  NOVICE_NOTEBOOK_READ_PAGE = 3,
  NOVICE_NOTEBOOK_RECEIVE_AWARD = 4,
  NOVICE_NOTEBOOK_LAST_POS = 5,
  NOVICE_NOTEBOOK_CHAPTER_TAG_STATE_OPEN = 1,
  NOVICE_NOTEBOOK_CHAPTER_TAG_STATE_CLOSE = 2,
  NOVICE_NOTEBOOK_CHAPTER_TAG_STATE_DISABLE = 3,
  NOVICE_NOTEBOOK_CHAPTER_REWARD_STATE_NOT_AVAILABLE = 1,
  NOVICE_NOTEBOOK_CHAPTER_REWARD_STATE_AVAILABLE = 2,
  NOVICE_NOTEBOOK_CHAPTER_REWARD_STATE_RECEIVED = 3
}
