NOVICEBPPARAM = {
  NOVICEBPPARAM_TARGET_UPDATE = 1,
  NOVICEBPPARAM_REWARD_UPDATE = 2,
  NOVICEBPPARAM_TARGET_GET = 3,
  NOVICEBPPARAM_BUY_LEVEL = 4,
  NOVICEBPPARAM_CHALLENGE_UPDATE = 5,
  NOVICEBPPARAM_RETURN_TARGET_UPDATE = 6,
  NOVICEBPPARAM_RETURN_REWARD_UPDATE = 7,
  NOVICEBPPARAM_RETURN_TARGET_REWARD_GET = 8,
  NOVICEBPPARAM_RETURN_REWARD_GET = 9,
  NOVICEBPPARAM_RETURN_BP_BUY_LEVEL = 10
}
NoviceBattlePass_pb = {
  NOVICEBPPARAM_TARGET_UPDATE = 1,
  NOVICEBPPARAM_REWARD_UPDATE = 2,
  NOVICEBPPARAM_TARGET_GET = 3,
  NOVICEBPPARAM_BUY_LEVEL = 4,
  NOVICEBPPARAM_CHALLENGE_UPDATE = 5,
  NOVICEBPPARAM_RETURN_TARGET_UPDATE = 6,
  NOVICEBPPARAM_RETURN_REWARD_UPDATE = 7,
  NOVICEBPPARAM_RETURN_TARGET_REWARD_GET = 8,
  NOVICEBPPARAM_RETURN_REWARD_GET = 9,
  NOVICEBPPARAM_RETURN_BP_BUY_LEVEL = 10
}
