OVERSEASTAIWANPARAM = {
  TAIWAN_FACEBOOK_LIKE_TOTAL_PROGRESS_CMD = 1,
  TAIWAN_FACEBOOK_LIKE_USER_REDEEM_CMD = 2,
  TAIWAN_FACEBOOK_SHARE_PROGRESS_CMD = 10,
  TAIWAN_FACEBOOK_SHARE_REDEEM_CMD = 11,
  TAIWAN_RANK_LISA_CMD = 21,
  TAIWAN_MAGIC_LIZI_CMD = 99
}
OVERSEASSCENEPARAM = {
  OVERSEAS_PHOTO_UPLOAD_CMD = 1,
  OVERSEAS_PHOTO_PREFIX_CMD = 2,
  OVERSEAS_CHARGE_LIMIT_GET_CHARGE_CMD = 11,
  OVERSEAS_GOE_ITEM_ADD_CMD = 21,
  OVERSEAS_GOE_ITEM_USE_CMD = 22,
  OVERSEAS_GOE_PURCHASE_CMD = 23,
  OVERSEAS_FIREBASE_NOTIFY_UPDATE = 24
}
OVERSEASGOEITEMADDTYPE = {ENUM_GOE_ITEM_ADD_TYPE_LOTTERY = 1}
OVERSEASGOEITEMUSETYPE = {ENUM_GOE_ITEM_USE_TYPE_LOTTERY = 1}
OVERSEASPHOTOGALLERYTYPE = {
  ENUM_GALLERY_TYPE_MIN = 0,
  ENUM_GALLERY_TYPE_SCENERY = 1,
  ENUM_GALLERY_TYPE_PHOTO = 2,
  ENUM_GALLERY_TYPE_GUILDICON = 3,
  ENUM_GALLERY_TYPE_WEDDING = 4,
  ENUM_GALLERY_TYPE_MAX = 5
}
TAIWANFBLIKEUSERREDEEMERROR = {
  TAIWAN_FACEBOOK_LIKE_USER_REDEEM_ERROR_NO_ERROR = 0,
  TAIWAN_FACEBOOK_LIKE_USER_REDEEM_ERROR_NOT_UNLOCKED = 1,
  TAIWAN_FACEBOOK_LIKE_USER_REDEEM_ERROR_USER_REDEEMED = 2
}
TAIWANFACEBOOKSHAREREDEEMERROR = {TAIWAN_FACEBOOK_SHARE_REDEEM_SUCCESS = 0, TAIWAN_FACEBOOK_SHARE_REDEEM_ERROR_SHARED = 1}
OverseasTaiwanCmd_pb = {
  TAIWAN_FACEBOOK_LIKE_TOTAL_PROGRESS_CMD = 1,
  TAIWAN_FACEBOOK_LIKE_USER_REDEEM_CMD = 2,
  TAIWAN_FACEBOOK_SHARE_PROGRESS_CMD = 10,
  TAIWAN_FACEBOOK_SHARE_REDEEM_CMD = 11,
  TAIWAN_RANK_LISA_CMD = 21,
  TAIWAN_MAGIC_LIZI_CMD = 99,
  OVERSEAS_PHOTO_UPLOAD_CMD = 1,
  OVERSEAS_PHOTO_PREFIX_CMD = 2,
  OVERSEAS_CHARGE_LIMIT_GET_CHARGE_CMD = 11,
  OVERSEAS_GOE_ITEM_ADD_CMD = 21,
  OVERSEAS_GOE_ITEM_USE_CMD = 22,
  OVERSEAS_GOE_PURCHASE_CMD = 23,
  OVERSEAS_FIREBASE_NOTIFY_UPDATE = 24,
  ENUM_GOE_ITEM_ADD_TYPE_LOTTERY = 1,
  ENUM_GOE_ITEM_USE_TYPE_LOTTERY = 1,
  ENUM_GALLERY_TYPE_MIN = 0,
  ENUM_GALLERY_TYPE_SCENERY = 1,
  ENUM_GALLERY_TYPE_PHOTO = 2,
  ENUM_GALLERY_TYPE_GUILDICON = 3,
  ENUM_GALLERY_TYPE_WEDDING = 4,
  ENUM_GALLERY_TYPE_MAX = 5,
  TAIWAN_FACEBOOK_LIKE_USER_REDEEM_ERROR_NO_ERROR = 0,
  TAIWAN_FACEBOOK_LIKE_USER_REDEEM_ERROR_NOT_UNLOCKED = 1,
  TAIWAN_FACEBOOK_LIKE_USER_REDEEM_ERROR_USER_REDEEMED = 2,
  TAIWAN_FACEBOOK_SHARE_REDEEM_SUCCESS = 0,
  TAIWAN_FACEBOOK_SHARE_REDEEM_ERROR_SHARED = 1
}
