PUZZLEPARAM = {
  PUZZLEPARAM_QUERYACTLIST = 1,
  PUZZLEPARAM_ITEMNTF = 3,
  PUZZLEPARAM_ACTIVIEPUZZLE = 4
}
EPUZZLESTATE = {
  EPUZZLESTATE_MIN = 0,
  EPUZZLESTATE_UNACTIVE = 1,
  EPUZZLESTATE_CANACTIVE = 2,
  EPUZZLESTATE_ACTIVE = 3,
  EPUZZLESTATE_MAX = 4
}
PuzzleCmd_pb = {
  PUZZLEPARAM_QUERYACTLIST = 1,
  PUZZLEPARAM_ITEMNTF = 3,
  PUZZLEPARAM_ACTIVIEPUZZLE = 4,
  EPUZZLESTATE_MIN = 0,
  EPUZZLESTATE_UNACTIVE = 1,
  EPUZZLESTATE_CANACTIVE = 2,
  EPUZZLESTATE_ACTIVE = 3,
  EPUZZLESTATE_MAX = 4
}
