EPVECARDPARAM = {
  EPVE_INVITE_TEAM_CMD = 1,
  EPVE_REPLY_TEAM_CMD = 2,
  EPVE_ENTER_RAID_CMD = 3,
  EPVE_QUERY_ALL_CARD_CMD = 4,
  EPVE_SELECT_CARD_CMD = 5,
  EPVE_SELECTED_CARD_CMD = 6,
  EPVE_UPDATE_CARD_CMD = 7,
  EPVE_BEGIN_FIRE_CMD = 8,
  EPVE_FINISH_CARD_CMD = 9,
  EPVE_PLAY_CARD_CMD = 10,
  EPVE_GET_REWARD_CMD = 11
}
PveCard_pb = {
  EPVE_INVITE_TEAM_CMD = 1,
  EPVE_REPLY_TEAM_CMD = 2,
  EPVE_ENTER_RAID_CMD = 3,
  EPVE_QUERY_ALL_CARD_CMD = 4,
  EPVE_SELECT_CARD_CMD = 5,
  EPVE_SELECTED_CARD_CMD = 6,
  EPVE_UPDATE_CARD_CMD = 7,
  EPVE_BEGIN_FIRE_CMD = 8,
  EPVE_FINISH_CARD_CMD = 9,
  EPVE_PLAY_CARD_CMD = 10,
  EPVE_GET_REWARD_CMD = 11
}
