QUEUEENTERPARAM = {
  QUEUE_ENTER_NOTIFY = 1,
  QUEUE_ENTER_REQ = 2,
  QUEUE_ENTER_RESULT = 3,
  QUEUE_ENTER_UPDATE = 4
}
EQUEUEENTERTYPE = {
  EQUEUEENTERTYPE_MIN = 0,
  EQUEUEENTERTYPE_GVG_ATT = 1,
  EQUEUEENTERTYPE_GVG_DEF = 2
}
QueueEnterCmd_pb = {
  QUEUE_ENTER_NOTIFY = 1,
  QUEUE_ENTER_REQ = 2,
  QUEUE_ENTER_RESULT = 3,
  QUEUE_ENTER_UPDATE = 4,
  EQUEUEENTERTYPE_MIN = 0,
  EQUEUEENTERTYPE_GVG_ATT = 1,
  EQUEUEENTERTYPE_GVG_DEF = 2
}
