SEALPARAM = {
  SEALPARAM_QUERYSEAL = 1,
  SEALPARAM_UPDATESEAL = 2,
  SEALPARAM_SEALTIMER = 3,
  SEALPARAM_BEGINSEAL = 4,
  SEALPARAM_ENDSEAL = 5,
  SEALPARAM_USERLEAVE = 6,
  SEALPARAM_QUERYLIST = 7,
  SEALPARAM_ACCEPTSEAL = 8
}
ESEALTYPE = {
  ESEALTYPE_MIN = 0,
  ESEALTYPE_NORMAL = 1,
  ESEALTYPE_PERSONAL = 2,
  ESEALTYPE_ACTIVITY = 3,
  ESEALTYPE_FADEJOB = 4,
  ESEALTYPE_MAX = 5
}
EFINISHTYPE = {
  EFINISHTYPE_MIN = 0,
  EFINISHTYPE_NORMAL = 1,
  EFINISHTYPE_QUICK = 2,
  EFINISHTYPE_QUICK_NOPROCESS = 3,
  EFINISHTYPE_MAX = 4
}
SceneSeal_pb = {
  SEALPARAM_QUERYSEAL = 1,
  SEALPARAM_UPDATESEAL = 2,
  SEALPARAM_SEALTIMER = 3,
  SEALPARAM_BEGINSEAL = 4,
  SEALPARAM_ENDSEAL = 5,
  SEALPARAM_USERLEAVE = 6,
  SEALPARAM_QUERYLIST = 7,
  SEALPARAM_ACCEPTSEAL = 8,
  ESEALTYPE_MIN = 0,
  ESEALTYPE_NORMAL = 1,
  ESEALTYPE_PERSONAL = 2,
  ESEALTYPE_ACTIVITY = 3,
  ESEALTYPE_FADEJOB = 4,
  ESEALTYPE_MAX = 5,
  EFINISHTYPE_MIN = 0,
  EFINISHTYPE_NORMAL = 1,
  EFINISHTYPE_QUICK = 2,
  EFINISHTYPE_QUICK_NOPROCESS = 3,
  EFINISHTYPE_MAX = 4
}
