INTERPARAM = {
  INTERPARAM_NEWINTERLOCUTION = 1,
  INTERPARAM_ANSWERINTER = 2,
  INTERPARAM_QUERYINTER = 3,
  INTERPARAM_QUERYPAPER = 4,
  INTERPARAM_PAPERQUESTION = 5,
  INTERPARAM_PAPERRESULT = 6
}
EQUERYSTATE = {
  EQUERYSTATE_OK = 1,
  EQUERYSTATE_ANSWERED_RIGHT = 2,
  EQUERYSTATE_ANSWERED_WRONG = 3,
  EQUERYSTATE_FAIL = 4
}
SceneInterlocution_pb = {
  INTERPARAM_NEWINTERLOCUTION = 1,
  INTERPARAM_ANSWERINTER = 2,
  INTERPARAM_QUERYINTER = 3,
  INTERPARAM_QUERYPAPER = 4,
  INTERPARAM_PAPERQUESTION = 5,
  INTERPARAM_PAPERRESULT = 6,
  EQUERYSTATE_OK = 1,
  EQUERYSTATE_ANSWERED_RIGHT = 2,
  EQUERYSTATE_ANSWERED_WRONG = 3,
  EQUERYSTATE_FAIL = 4
}
