AUGURYPARAM = {
  AUGURYPARAM_INVITE = 1,
  AUGURYPARAM_INVITE_REPLY = 2,
  AUGURYPARAM_CHAT = 3,
  AUGURYPARAM_TITLE = 4,
  AUGURYPARAM_ANSWER = 5,
  AUGURYPARAM_QUIT = 6,
  AUGURYPARAM_ASTROLOGY_DRAW_CARD = 7,
  AUGURYPARAM_ASTROLOGY_INFO = 8
}
EAUGURYTYPE = {
  EAUGURYTYPE_LOVE_SEASON = 1,
  EAUGURYTYPE_STAR_GUIDE = 2,
  EAUGURYTYPE_ADVENTURE = 3,
  EAUGURYTYPE_VALENTINE = 4,
  EAUGURYTYPE_ACTIVITY = 5
}
EASTROLOGYTYPE = {EASTROLOGYTYPE_CONSTELLATION = 1, EASTROLOGYTYPE_ACTIVITY = 2}
EREPLYTYPE = {EReplyType_Agree = 1, EReplyType_Refuse = 2}
SceneAugury_pb = {
  AUGURYPARAM_INVITE = 1,
  AUGURYPARAM_INVITE_REPLY = 2,
  AUGURYPARAM_CHAT = 3,
  AUGURYPARAM_TITLE = 4,
  AUGURYPARAM_ANSWER = 5,
  AUGURYPARAM_QUIT = 6,
  AUGURYPARAM_ASTROLOGY_DRAW_CARD = 7,
  AUGURYPARAM_ASTROLOGY_INFO = 8,
  EAUGURYTYPE_LOVE_SEASON = 1,
  EAUGURYTYPE_STAR_GUIDE = 2,
  EAUGURYTYPE_ADVENTURE = 3,
  EAUGURYTYPE_VALENTINE = 4,
  EAUGURYTYPE_ACTIVITY = 5,
  EASTROLOGYTYPE_CONSTELLATION = 1,
  EASTROLOGYTYPE_ACTIVITY = 2,
  EReplyType_Agree = 1,
  EReplyType_Refuse = 2
}
