ECHATROOMPARAM = {
  ECHATROOMPARAM_CREATE = 1,
  ECHATROOMPARAM_JOIN = 2,
  ECHATROOMPARAM_EXIT = 3,
  ECHATROOMPARAM_KICKMEMBER = 4,
  ECHATROOMPARAM_CHANGEOWNER = 5,
  ECHATROOMPARAM_ENTERROOM = 6,
  ECHATROOMPARAM_MEMBERUPDATE = 7,
  ECHATROOMPARAM_ROOMDATASYNC = 8,
  ECHATROOMPARAM_ROOMTIP = 9
}
ECHATROOMJOB = {ECHATROOM_OWNER = 1, ECHATROOM_MEMBER = 2}
ECHATROOMTYPE = {ECHATROOMTYPE_PUBLIC = 1, ECHATROOMTYPE_PRIVATE = 2}
ECHATROOMSYNC = {ECHATROOMSYNC_UPDATE = 1, ECHATROOMSYNC_REMOVE = 2}
ECHATROOMTIP = {
  ECHATROOMTIP_JOIN = 1,
  ECHATROOMTIP_EXIT = 2,
  ECHATROOMTIP_KICK = 3,
  ECHATROOMTIP_OWNERCHANGE = 4
}
SceneChatRoom_pb = {
  ECHATROOMPARAM_CREATE = 1,
  ECHATROOMPARAM_JOIN = 2,
  ECHATROOMPARAM_EXIT = 3,
  ECHATROOMPARAM_KICKMEMBER = 4,
  ECHATROOMPARAM_CHANGEOWNER = 5,
  ECHATROOMPARAM_ENTERROOM = 6,
  ECHATROOMPARAM_MEMBERUPDATE = 7,
  ECHATROOMPARAM_ROOMDATASYNC = 8,
  ECHATROOMPARAM_ROOMTIP = 9,
  ECHATROOM_OWNER = 1,
  ECHATROOM_MEMBER = 2,
  ECHATROOMTYPE_PUBLIC = 1,
  ECHATROOMTYPE_PRIVATE = 2,
  ECHATROOMSYNC_UPDATE = 1,
  ECHATROOMSYNC_REMOVE = 2,
  ECHATROOMTIP_JOIN = 1,
  ECHATROOMTIP_EXIT = 2,
  ECHATROOMTIP_KICK = 3,
  ECHATROOMTIP_OWNERCHANGE = 4
}
