TEAMRAIDPARAM = {
  TEAMRAIDPARAM_INVITE = 1,
  TEAMRAIDPARAM_REPLY = 2,
  TEAMRAIDPARAM_ENTER = 3,
  TEAMRAIDPARAM_ALTMANSHOW = 4,
  TEAMRAIDPARAM_IMAGE_CREATE = 6,
  TEAMRAIDPARAM_INVITE_MATCH = 7,
  TEAMRAIDPARAM_REPLY_MATCH = 8,
  TEAMRAIDPARAM_COMODO_TEAM_RAID_CREATE = 9,
  TEAMRAIDPARAM_GUILD_TEAM_RAID_CREATE = 11
}
TeamRaidCmd_pb = {
  TEAMRAIDPARAM_INVITE = 1,
  TEAMRAIDPARAM_REPLY = 2,
  TEAMRAIDPARAM_ENTER = 3,
  TEAMRAIDPARAM_ALTMANSHOW = 4,
  TEAMRAIDPARAM_IMAGE_CREATE = 6,
  TEAMRAIDPARAM_INVITE_MATCH = 7,
  TEAMRAIDPARAM_REPLY_MATCH = 8,
  TEAMRAIDPARAM_COMODO_TEAM_RAID_CREATE = 9,
  TEAMRAIDPARAM_GUILD_TEAM_RAID_CREATE = 11
}
