TECHTREEPARAM = {
  TECHTREEPARAM_UNLOCK = 1,
  TECHTREEPARAM_SYNCINFO = 2,
  TECHTREEPARAM_TOY_UNLOCK = 3,
  TECHTREEPARAM_TOY_SYNCINFO = 4,
  TECHTREEPARAM_MAKE_TOY = 5,
  TECHTREEPARAM_TOY_TRANS_POS = 6,
  TECHTREEPARAM_GET_LEVEL_AWARD = 7,
  TECHTREEPARAM_PRODUCE_COLLECT = 8,
  TECHTREEPARAM_PRODUCE_INFO = 9,
  TECHTREEPARAM_INJECT = 10,
  TECHTREEPARAM_INJECT_INFO = 11
}
TECHTREELEVELQUSETSTATE = {
  TECHTREE_LEVEL_STATE_NONE = 0,
  TECHTREE_LEVEL_STATE_UNLOCK = 1,
  TECHTREE_LEVEL_STATE_INPROCESS = 2,
  TECHTREE_LEVEL_STATE_COMPLETE = 3
}
TechTreeCmd_pb = {
  TECHTREEPARAM_UNLOCK = 1,
  TECHTREEPARAM_SYNCINFO = 2,
  TECHTREEPARAM_TOY_UNLOCK = 3,
  TECHTREEPARAM_TOY_SYNCINFO = 4,
  TECHTREEPARAM_MAKE_TOY = 5,
  TECHTREEPARAM_TOY_TRANS_POS = 6,
  TECHTREEPARAM_GET_LEVEL_AWARD = 7,
  TECHTREEPARAM_PRODUCE_COLLECT = 8,
  TECHTREEPARAM_PRODUCE_INFO = 9,
  TECHTREEPARAM_INJECT = 10,
  TECHTREEPARAM_INJECT_INFO = 11,
  TECHTREE_LEVEL_STATE_NONE = 0,
  TECHTREE_LEVEL_STATE_UNLOCK = 1,
  TECHTREE_LEVEL_STATE_INPROCESS = 2,
  TECHTREE_LEVEL_STATE_COMPLETE = 3
}
