TUTORPARAM = {
  TUTORPARAM_TASK_UPDATE_NTF = 1,
  TUTORPARAM_TASK_QUERY = 2,
  TUTORPARAM_TASK_TEACHER_REWARD = 3,
  TUTORPARAM_GROW_REWARD_UPDATE = 4,
  TUTORPARAM_GET_GROW_REWARD = 5,
  TUTORPARAM_TASK_UPDATE_BOX = 6
}
Tutor_pb = {
  TUTORPARAM_TASK_UPDATE_NTF = 1,
  TUTORPARAM_TASK_QUERY = 2,
  TUTORPARAM_TASK_TEACHER_REWARD = 3,
  TUTORPARAM_GROW_REWARD_UPDATE = 4,
  TUTORPARAM_GET_GROW_REWARD = 5,
  TUTORPARAM_TASK_UPDATE_BOX = 6
}
