USERAFKCMDPARAM = {
  USER_AFKCMD_REQ_AFK = 1,
  USER_AFKCMD_RET_AFK = 2,
  USER_AFKCMD_SYNC_STATINFO = 3
}
EAFKSTATUS = {
  EAFKSTATUS_OPEN = 0,
  EAFKSTATUS_TIMEOUT_EXIT = 1,
  EAFKSTATUS_NOBATTLE_EXIT = 2,
  EAFKSTATUS_RESTART_EXIT = 3
}
UserAfkCmd_pb = {
  USER_AFKCMD_REQ_AFK = 1,
  USER_AFKCMD_RET_AFK = 2,
  USER_AFKCMD_SYNC_STATINFO = 3,
  EAFKSTATUS_OPEN = 0,
  EAFKSTATUS_TIMEOUT_EXIT = 1,
  EAFKSTATUS_NOBATTLE_EXIT = 2,
  EAFKSTATUS_RESTART_EXIT = 3
}
