EUSERSHOWPARAM = {
  EUSERSHOW_NEW_PHOTO_FRAME = 1,
  EUSERSHOW_SYNC_PHOTO_FRAME = 2,
  EUSERSHOW_NEW_BACKGROUND_FRAME = 3,
  EUSERSHOW_SYNC_BACKGROUND_FRAME = 4,
  EUSERSHOW_USE_PHOTO_FRAME = 5,
  EUSERSHOW_USE_BACKGROUND_FRAME = 6,
  EUSERSHOW_SYNC_CHAT_FRAME = 7,
  EUSERSHOW_USE_CHAT_FRAME = 8
}
UserShow_pb = {
  EUSERSHOW_NEW_PHOTO_FRAME = 1,
  EUSERSHOW_SYNC_PHOTO_FRAME = 2,
  EUSERSHOW_NEW_BACKGROUND_FRAME = 3,
  EUSERSHOW_SYNC_BACKGROUND_FRAME = 4,
  EUSERSHOW_USE_PHOTO_FRAME = 5,
  EUSERSHOW_USE_BACKGROUND_FRAME = 6,
  EUSERSHOW_SYNC_CHAT_FRAME = 7,
  EUSERSHOW_USE_CHAT_FRAME = 8
}
