autoImport("EnchantThirdAttrResetView")
EnchantThirdAttrResetSubView = class("EnchantThirdAttrResetSubView", EnchantThirdAttrResetView)
EnchantThirdAttrResetSubView.ViewType = UIViewType.NormalLayer
autoImport("EnchantNewCombineView")
EnchantThirdAttrResetSubView.BrotherView = EnchantIntegerCombineView
EnchantThirdAttrResetSubView.EquipChooseControl = EquipChooseBord_CombineSize
