Table_EquipEnchant_t = {
  AddAttr = {
    {
      {500101, 200},
      {500102, 100},
      {500103, 5},
      {500104, 1}
    },
    {
      {500151, 200},
      {500152, 100},
      {500153, 10},
      {500154, 5}
    },
    {
      {500131, 200},
      {500132, 100},
      {500133, 10},
      {500134, 5}
    },
    {
      {500161, 200},
      {500162, 100},
      {500163, 10},
      {500164, 5}
    },
    {
      {500041, 200},
      {500042, 100},
      {500043, 10},
      {500044, 5}
    },
    {
      {500091, 200},
      {500092, 100},
      {500093, 5},
      {500094, 1}
    },
    {
      {500011, 200},
      {500012, 100},
      {500013, 10},
      {500014, 5}
    },
    {
      {500021, 200},
      {500022, 100},
      {500023, 10},
      {500024, 5}
    },
    {
      {500031, 200},
      {500032, 100},
      {500033, 10},
      {500034, 5}
    },
    {
      {500101, 200},
      {500102, 100},
      {500103, 50},
      {500104, 25}
    },
    {
      {500151, 200},
      {500152, 100},
      {500153, 50},
      {500154, 25}
    },
    {
      {500131, 200},
      {500132, 100},
      {500133, 50},
      {500134, 25}
    },
    {
      {500161, 200},
      {500162, 100},
      {500163, 50},
      {500164, 25}
    },
    {
      {500041, 200},
      {500042, 100},
      {500043, 50},
      {500044, 25}
    },
    {
      {500091, 200},
      {500092, 100},
      {500093, 50},
      {500094, 25}
    },
    {
      {500011, 200},
      {500012, 100},
      {500013, 50},
      {500014, 25}
    },
    {
      {500021, 200},
      {500022, 100},
      {500023, 50},
      {500024, 25}
    },
    {
      {500031, 200},
      {500032, 100},
      {500033, 50},
      {500034, 25}
    },
    {
      {500081, 200},
      {500082, 100},
      {500083, 25},
      {500084, 10}
    },
    {
      {500051, 200},
      {500052, 100},
      {500053, 50},
      {500054, 25}
    },
    {
      {500061, 200},
      {500062, 100},
      {500063, 25},
      {500064, 10}
    },
    {
      {500141, 200},
      {500142, 100},
      {500143, 5},
      {500144, 1}
    },
    {
      {500141, 200},
      {500142, 100},
      {500143, 50},
      {500144, 25}
    },
    {
      {500121, 200},
      {500122, 100},
      {500123, 50},
      {500124, 25}
    },
    {
      {500111, 200},
      {500112, 100},
      {500113, 50},
      {500114, 25}
    }
  },
  AttrBound = {
    {
      {1, 4}
    },
    {
      {1, 2}
    },
    {
      {1, 160}
    },
    {
      {1, 16}
    },
    {
      {1, 8}
    },
    {
      {2, 8}
    },
    {
      {2, 6}
    },
    {
      {20, 240}
    },
    {
      {0.01, 0.05}
    },
    {
      {8, 24}
    },
    {
      {4, 12}
    },
    {
      {1, 5}
    },
    {
      {4, 10}
    },
    {
      {4, 8}
    },
    {
      {40, 400}
    },
    {
      {0.02, 0.1}
    },
    {
      {10, 80}
    },
    {
      {8, 40}
    },
    {
      {4, 20}
    },
    {
      {6, 20}
    },
    {
      {3, 20}
    },
    {
      {0.01, 0.04}
    },
    {
      {1, 10}
    },
    {
      {0.01, 0.1}
    },
    {
      {0.01, 0.25}
    },
    {
      {1, 240}
    },
    {
      {1, 24}
    },
    {
      {1, 12}
    },
    {
      {30, 360}
    },
    {
      {8, 36}
    },
    {
      {6, 18}
    },
    {
      {60, 600}
    },
    {
      {12, 120}
    },
    {
      {12, 60}
    },
    {
      {6, 30}
    },
    {
      {5, 30}
    }
  },
  AttrType2 = {
    {"MDef"},
    {"Dex"},
    {"MaxSpPer"},
    {"Int"},
    {"Luk"},
    {"MAtk"},
    {"Str"},
    {
      "DamIncrease"
    },
    {"Def"},
    {"Atk"},
    {"Hit"},
    {"CriDamPer"},
    {"Vit"},
    {"EquipASPD"}
  },
  CantEnchant = {
    {
      AccessoryRate = 1,
      BraceletRate = 1,
      BracerRate = 1,
      EikonRate = 1,
      FaceRate = 1,
      HeadRate = 1,
      MouthRate = 1,
      OrbRate = 1,
      RobeRate = 1,
      ShieldRate = 1,
      ShoeRate = 1,
      TailRate = 1,
      WingRate = 1
    },
    {
      FaceRate = 1,
      HeadRate = 1,
      MouthRate = 1,
      TailRate = 1,
      WingRate = 1
    },
    {
      AccessoryRate = 1,
      ArmorRate = 1,
      AxeRate = 1,
      BookRate = 1,
      BowRate = 1,
      BraceletRate = 1,
      BracerRate = 1,
      DartsRate = 1,
      EikonRate = 1,
      FaceRate = 1,
      GloveRate = 1,
      HeadRate = 1,
      InstrumentRate = 1,
      KatarRate = 1,
      KnifeRate = 1,
      LashRate = 1,
      MaceRate = 1,
      MouthRate = 1,
      OrbRate = 1,
      PistolRate = 1,
      PotionRate = 1,
      RifleRate = 1,
      ShieldRate = 1,
      SpearRate = 1,
      StaffRate = 1,
      SwordRate = 1,
      TailRate = 1,
      WingRate = 1
    },
    {
      AccessoryRate = 1,
      FaceRate = 1,
      HeadRate = 1,
      MouthRate = 1,
      RobeRate = 1,
      ShoeRate = 1,
      TailRate = 1,
      WingRate = 1
    },
    {
      FaceRate = 1,
      HeadRate = 1,
      MouthRate = 1,
      RobeRate = 1,
      ShoeRate = 1,
      TailRate = 1,
      WingRate = 1
    },
    {
      AccessoryRate = 1,
      AxeRate = 1,
      BookRate = 1,
      BowRate = 1,
      BraceletRate = 1,
      BracerRate = 1,
      DartsRate = 1,
      EikonRate = 1,
      FaceRate = 1,
      GloveRate = 1,
      HeadRate = 1,
      InstrumentRate = 1,
      KatarRate = 1,
      KnifeRate = 1,
      LashRate = 1,
      MaceRate = 1,
      MouthRate = 1,
      OrbRate = 1,
      PistolRate = 1,
      PotionRate = 1,
      RifleRate = 1,
      ShieldRate = 1,
      SpearRate = 1,
      StaffRate = 1,
      SwordRate = 1,
      TailRate = 1,
      WingRate = 1
    },
    {
      AccessoryRate = 1,
      AxeRate = 1,
      BookRate = 1,
      BowRate = 1,
      DartsRate = 1,
      FaceRate = 1,
      GloveRate = 1,
      HeadRate = 1,
      InstrumentRate = 1,
      KatarRate = 1,
      KnifeRate = 1,
      LashRate = 1,
      MaceRate = 1,
      MouthRate = 1,
      PistolRate = 1,
      PotionRate = 1,
      RifleRate = 1,
      SpearRate = 1,
      StaffRate = 1,
      SwordRate = 1,
      TailRate = 1,
      WingRate = 1
    },
    {
      BraceletRate = 1,
      BracerRate = 1,
      EikonRate = 1,
      FaceRate = 1,
      HeadRate = 1,
      MouthRate = 1,
      OrbRate = 1,
      ShieldRate = 1,
      TailRate = 1,
      WingRate = 1
    },
    {
      ArmorRate = 1,
      FaceRate = 1,
      HeadRate = 1,
      MouthRate = 1,
      RobeRate = 1,
      ShoeRate = 1,
      TailRate = 1,
      WingRate = 1
    },
    {
      AccessoryRate = 1,
      ArmorRate = 1,
      BraceletRate = 1,
      BracerRate = 1,
      EikonRate = 1,
      FaceRate = 1,
      HeadRate = 1,
      MouthRate = 1,
      OrbRate = 1,
      ShieldRate = 1,
      TailRate = 1,
      WingRate = 1
    },
    {
      AccessoryRate = 1,
      BraceletRate = 1,
      BracerRate = 1,
      EikonRate = 1,
      FaceRate = 1,
      HeadRate = 1,
      MouthRate = 1,
      OrbRate = 1,
      ShieldRate = 1,
      TailRate = 1,
      WingRate = 1
    },
    {
      AccessoryRate = 1,
      ArmorRate = 1,
      AxeRate = 1,
      BookRate = 1,
      BowRate = 1,
      BraceletRate = 1,
      BracerRate = 1,
      DartsRate = 1,
      EikonRate = 1,
      FaceRate = 1,
      GloveRate = 1,
      InstrumentRate = 1,
      KatarRate = 1,
      KnifeRate = 1,
      LashRate = 1,
      MaceRate = 1,
      OrbRate = 1,
      PistolRate = 1,
      PotionRate = 1,
      RifleRate = 1,
      RobeRate = 1,
      ShieldRate = 1,
      ShoeRate = 1,
      SpearRate = 1,
      StaffRate = 1,
      SwordRate = 1
    },
    {
      AccessoryRate = 1,
      ArmorRate = 1,
      AxeRate = 1,
      BookRate = 1,
      BowRate = 1,
      BraceletRate = 1,
      BracerRate = 1,
      DartsRate = 1,
      EikonRate = 1,
      GloveRate = 1,
      InstrumentRate = 1,
      KatarRate = 1,
      KnifeRate = 1,
      LashRate = 1,
      MaceRate = 1,
      MouthRate = 1,
      OrbRate = 1,
      PistolRate = 1,
      PotionRate = 1,
      RifleRate = 1,
      RobeRate = 1,
      ShieldRate = 1,
      ShoeRate = 1,
      SpearRate = 1,
      StaffRate = 1,
      SwordRate = 1,
      TailRate = 1
    },
    {
      AccessoryRate = 1,
      ArmorRate = 1,
      AxeRate = 1,
      BookRate = 1,
      BowRate = 1,
      BraceletRate = 1,
      BracerRate = 1,
      DartsRate = 1,
      EikonRate = 1,
      GloveRate = 1,
      HeadRate = 1,
      InstrumentRate = 1,
      KatarRate = 1,
      KnifeRate = 1,
      LashRate = 1,
      MaceRate = 1,
      MouthRate = 1,
      OrbRate = 1,
      PistolRate = 1,
      PotionRate = 1,
      RifleRate = 1,
      RobeRate = 1,
      ShieldRate = 1,
      ShoeRate = 1,
      SpearRate = 1,
      StaffRate = 1,
      SwordRate = 1
    },
    {
      AccessoryRate = 1,
      ArmorRate = 1,
      AxeRate = 1,
      BookRate = 1,
      BowRate = 1,
      BraceletRate = 1,
      BracerRate = 1,
      DartsRate = 1,
      EikonRate = 1,
      GloveRate = 1,
      InstrumentRate = 1,
      KatarRate = 1,
      KnifeRate = 1,
      LashRate = 1,
      MaceRate = 1,
      OrbRate = 1,
      PistolRate = 1,
      PotionRate = 1,
      RifleRate = 1,
      RobeRate = 1,
      ShieldRate = 1,
      ShoeRate = 1,
      SpearRate = 1,
      StaffRate = 1,
      SwordRate = 1
    },
    {
      AccessoryRate = 1,
      ArmorRate = 1,
      AxeRate = 1,
      BookRate = 1,
      BowRate = 1,
      BraceletRate = 1,
      BracerRate = 1,
      DartsRate = 1,
      EikonRate = 1,
      FaceRate = 1,
      GloveRate = 1,
      InstrumentRate = 1,
      KatarRate = 1,
      KnifeRate = 1,
      LashRate = 1,
      MaceRate = 1,
      OrbRate = 1,
      PistolRate = 1,
      PotionRate = 1,
      RifleRate = 1,
      RobeRate = 1,
      ShieldRate = 1,
      ShoeRate = 1,
      SpearRate = 1,
      StaffRate = 1,
      SwordRate = 1,
      WingRate = 1
    },
    {
      AccessoryRate = 1,
      ArmorRate = 1,
      AxeRate = 1,
      BookRate = 1,
      BowRate = 1,
      BraceletRate = 1,
      BracerRate = 1,
      DartsRate = 1,
      EikonRate = 1,
      GloveRate = 1,
      HeadRate = 1,
      InstrumentRate = 1,
      KatarRate = 1,
      KnifeRate = 1,
      LashRate = 1,
      MaceRate = 1,
      OrbRate = 1,
      PistolRate = 1,
      PotionRate = 1,
      RifleRate = 1,
      RobeRate = 1,
      ShieldRate = 1,
      ShoeRate = 1,
      SpearRate = 1,
      StaffRate = 1,
      SwordRate = 1,
      TailRate = 1
    },
    {
      AccessoryRate = 1,
      ArmorRate = 1,
      AxeRate = 1,
      BookRate = 1,
      BowRate = 1,
      BraceletRate = 1,
      BracerRate = 1,
      DartsRate = 1,
      EikonRate = 1,
      FaceRate = 1,
      GloveRate = 1,
      HeadRate = 1,
      InstrumentRate = 1,
      KatarRate = 1,
      KnifeRate = 1,
      LashRate = 1,
      MaceRate = 1,
      MouthRate = 1,
      OrbRate = 1,
      PistolRate = 1,
      PotionRate = 1,
      RifleRate = 1,
      RobeRate = 1,
      ShieldRate = 1,
      ShoeRate = 1,
      SpearRate = 1,
      StaffRate = 1,
      SwordRate = 1
    },
    {
      AccessoryRate = 1,
      ArmorRate = 1,
      AxeRate = 1,
      BookRate = 1,
      BowRate = 1,
      BraceletRate = 1,
      BracerRate = 1,
      DartsRate = 1,
      EikonRate = 1,
      GloveRate = 1,
      HeadRate = 1,
      InstrumentRate = 1,
      KatarRate = 1,
      KnifeRate = 1,
      LashRate = 1,
      MaceRate = 1,
      MouthRate = 1,
      OrbRate = 1,
      PistolRate = 1,
      PotionRate = 1,
      RifleRate = 1,
      RobeRate = 1,
      ShieldRate = 1,
      ShoeRate = 1,
      SpearRate = 1,
      StaffRate = 1,
      SwordRate = 1,
      TailRate = 1
    },
    {
      AccessoryRate = 1,
      ArmorRate = 1,
      AxeRate = 1,
      BookRate = 1,
      BowRate = 1,
      BraceletRate = 1,
      BracerRate = 1,
      DartsRate = 1,
      EikonRate = 1,
      GloveRate = 1,
      InstrumentRate = 1,
      KatarRate = 1,
      KnifeRate = 1,
      LashRate = 1,
      MaceRate = 1,
      OrbRate = 1,
      PistolRate = 1,
      PotionRate = 1,
      RifleRate = 1,
      RobeRate = 1,
      ShieldRate = 1,
      ShoeRate = 1,
      SpearRate = 1,
      StaffRate = 1,
      SwordRate = 1,
      TailRate = 1,
      WingRate = 1
    },
    {
      AccessoryRate = 1,
      ArmorRate = 1,
      AxeRate = 1,
      BookRate = 1,
      BowRate = 1,
      BraceletRate = 1,
      BracerRate = 1,
      DartsRate = 1,
      EikonRate = 1,
      GloveRate = 1,
      HeadRate = 1,
      InstrumentRate = 1,
      KatarRate = 1,
      KnifeRate = 1,
      LashRate = 1,
      MaceRate = 1,
      MouthRate = 1,
      OrbRate = 1,
      PistolRate = 1,
      PotionRate = 1,
      RifleRate = 1,
      RobeRate = 1,
      ShieldRate = 1,
      ShoeRate = 1,
      SpearRate = 1,
      StaffRate = 1,
      SwordRate = 1,
      WingRate = 1
    },
    {
      AccessoryRate = 1,
      ArmorRate = 1,
      AxeRate = 1,
      BookRate = 1,
      BowRate = 1,
      BraceletRate = 1,
      BracerRate = 1,
      DartsRate = 1,
      EikonRate = 1,
      FaceRate = 1,
      GloveRate = 1,
      InstrumentRate = 1,
      KatarRate = 1,
      KnifeRate = 1,
      LashRate = 1,
      MaceRate = 1,
      OrbRate = 1,
      PistolRate = 1,
      PotionRate = 1,
      RifleRate = 1,
      RobeRate = 1,
      ShieldRate = 1,
      ShoeRate = 1,
      SpearRate = 1,
      StaffRate = 1,
      SwordRate = 1,
      TailRate = 1,
      WingRate = 1
    }
  },
  Condition = {
    {refinelv = 6, type = 1}
  },
  ItemCost = {
    {itemid = 135, num = 2},
    {itemid = 135, num = 4}
  },
  NoExchangeEnchant = {
    {StaffRate = 1},
    {
      AxeRate = 1,
      BowRate = 1,
      KatarRate = 1,
      KnifeRate = 1,
      SpearRate = 1,
      SwordRate = 1
    },
    {
      AxeRate = 1,
      DartsRate = 1,
      MaceRate = 1,
      SpearRate = 1,
      StaffRate = 1,
      SwordRate = 1
    }
  },
  NoShowEquip = {
    {
      ArmorRate = 1,
      AxeRate = 1,
      BookRate = 1,
      BowRate = 1,
      DartsRate = 1,
      GloveRate = 1,
      InstrumentRate = 1,
      KatarRate = 1,
      KnifeRate = 1,
      LashRate = 1,
      MaceRate = 1,
      PistolRate = 1,
      PotionRate = 1,
      RifleRate = 1,
      SpearRate = 1,
      StaffRate = 1,
      SwordRate = 1
    },
    {ArmorRate = 1},
    {
      ArmorRate = 1,
      AxeRate = 1,
      BookRate = 1,
      BowRate = 1,
      BraceletRate = 1,
      BracerRate = 1,
      DartsRate = 1,
      EikonRate = 1,
      GloveRate = 1,
      InstrumentRate = 1,
      KatarRate = 1,
      KnifeRate = 1,
      LashRate = 1,
      MaceRate = 1,
      OrbRate = 1,
      PistolRate = 1,
      PotionRate = 1,
      RifleRate = 1,
      ShieldRate = 1,
      SpearRate = 1,
      StaffRate = 1,
      SwordRate = 1
    },
    {
      ArmorRate = 1,
      BraceletRate = 1,
      BracerRate = 1,
      EikonRate = 1,
      OrbRate = 1,
      ShieldRate = 1
    },
    {
      BraceletRate = 1,
      BracerRate = 1,
      EikonRate = 1,
      OrbRate = 1,
      ShieldRate = 1
    },
    {
      AccessoryRate = 1,
      BraceletRate = 1,
      BracerRate = 1,
      EikonRate = 1,
      OrbRate = 1,
      ShieldRate = 1
    },
    {
      ArmorRate = 1,
      RobeRate = 1,
      ShoeRate = 1
    },
    {
      ArmorRate = 1,
      AxeRate = 1,
      BookRate = 1,
      BowRate = 1,
      DartsRate = 1,
      GloveRate = 1,
      InstrumentRate = 1,
      KatarRate = 1,
      KnifeRate = 1,
      LashRate = 1,
      MaceRate = 1,
      PistolRate = 1,
      PotionRate = 1,
      RifleRate = 1,
      RobeRate = 1,
      ShoeRate = 1,
      SpearRate = 1,
      StaffRate = 1,
      SwordRate = 1
    },
    {HeadRate = 1},
    {
      FaceRate = 1,
      TailRate = 1,
      WingRate = 1
    },
    {HeadRate = 1, MouthRate = 1},
    {FaceRate = 1, MouthRate = 1},
    {TailRate = 1},
    {FaceRate = 1, WingRate = 1},
    {TailRate = 1, WingRate = 1}
  },
  Stageconsumption1 = {
    {
      {7300, 10},
      {100, 10000}
    },
    {
      {7300, 5},
      {100, 10000}
    }
  },
  Stageconsumption2 = {
    {
      {7300, 30},
      {100, 10000}
    },
    {
      {7300, 15},
      {100, 10000}
    }
  },
  Stageconsumption3 = {
    {
      {7300, 60},
      {100, 10000}
    },
    {
      {7300, 30},
      {100, 10000}
    }
  },
  Stageconsumption4 = {
    {
      {7300, 120},
      {100, 10000}
    },
    {
      {7300, 60},
      {100, 10000}
    }
  },
  Stageconsumption5 = {
    {
      {7300, 240},
      {100, 10000}
    },
    {
      {7300, 120},
      {100, 10000}
    }
  }
}
Table_EquipEnchant = {
  [1] = {
    UniqID = 1001,
    EnchantType = 1,
    MaxNum = 2,
    AttrType = "Vit",
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[1],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[1]
  },
  [2] = {
    id = 2,
    UniqID = 1002,
    EnchantType = 1,
    MaxNum = 2,
    AttrType = "Str",
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[1],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[1]
  },
  [3] = {
    id = 3,
    UniqID = 1003,
    EnchantType = 1,
    MaxNum = 2,
    AttrType = "Int",
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[1],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[1]
  },
  [4] = {
    id = 4,
    UniqID = 1004,
    EnchantType = 1,
    MaxNum = 2,
    AttrType = "Luk",
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[2],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[2]
  },
  [5] = {
    id = 5,
    UniqID = 1005,
    EnchantType = 1,
    MaxNum = 2,
    AttrType = "Dex",
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[1],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[1]
  },
  [6] = {
    id = 6,
    UniqID = 1006,
    EnchantType = 1,
    MaxNum = 2,
    AttrType = "Agi",
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[1],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[1]
  },
  [7] = {
    id = 7,
    UniqID = 1007,
    EnchantType = 1,
    MaxNum = 2,
    AttrType = "MaxHp",
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[3],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[2]
  },
  [8] = {
    id = 8,
    UniqID = 1008,
    EnchantType = 1,
    MaxNum = 2,
    AttrType = "MaxSp",
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[4],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[2]
  },
  [9] = {
    id = 9,
    UniqID = 1009,
    EnchantType = 1,
    MaxNum = 2,
    AttrType = "Atk",
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[5],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[2]
  },
  [10] = {
    id = 10,
    UniqID = 1010,
    EnchantType = 1,
    MaxNum = 2,
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[5],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[2]
  },
  [11] = {
    id = 11,
    UniqID = 1011,
    EnchantType = 1,
    MaxNum = 2,
    AttrType = "Def",
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[1],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[2]
  },
  [12] = {
    id = 12,
    UniqID = 1012,
    EnchantType = 1,
    MaxNum = 2,
    AttrType = "MDef",
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[5],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[2]
  },
  [13] = {
    id = 13,
    UniqID = 2001,
    EnchantType = 2,
    AttrType = "Vit",
    AttrType2 = Table_EquipEnchant_t.AttrType2[1],
    AddAttr = Table_EquipEnchant_t.AddAttr[1],
    Condition = Table_EquipEnchant_t.Condition[1],
    Name = "##1110014",
    Dsc = "##1110015",
    ComBineAttr = "##1110016",
    AttrSectionDsc = "2.5%~10%",
    ItemCost = Table_EquipEnchant_t.ItemCost[1],
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[6],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[3]
  },
  [14] = {
    id = 14,
    UniqID = 2002,
    EnchantType = 2,
    AttrType = "Str",
    AttrType2 = Table_EquipEnchant_t.AttrType2[2],
    AddAttr = Table_EquipEnchant_t.AddAttr[2],
    Condition = Table_EquipEnchant_t.Condition[1],
    Name = "##159322",
    Dsc = "##116916",
    ComBineAttr = "##1110017",
    AttrSectionDsc = "1.5%~6%",
    ItemCost = Table_EquipEnchant_t.ItemCost[1],
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[6],
    NoShowEquip = Table_EquipEnchant_t.NoShowEquip[1],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[4]
  },
  [15] = {
    id = 15,
    UniqID = 2003,
    EnchantType = 2,
    AttrType = "Int",
    AttrType2 = Table_EquipEnchant_t.AttrType2[3],
    AddAttr = Table_EquipEnchant_t.AddAttr[3],
    Condition = Table_EquipEnchant_t.Condition[1],
    Name = "##1110018",
    Dsc = "##116920",
    ComBineAttr = "##1110019",
    AttrSectionDsc = "5%~20%",
    ItemCost = Table_EquipEnchant_t.ItemCost[1],
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[6],
    NoShowEquip = Table_EquipEnchant_t.NoShowEquip[2],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[5]
  },
  [16] = {
    id = 16,
    UniqID = 2004,
    EnchantType = 2,
    AttrType = "Luk",
    ItemCost = Table_EquipEnchant_t.ItemCost[1],
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[7],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[2]
  },
  [17] = {
    id = 17,
    UniqID = 2005,
    EnchantType = 2,
    AttrType = "Dex",
    AttrType2 = Table_EquipEnchant_t.AttrType2[4],
    AddAttr = Table_EquipEnchant_t.AddAttr[4],
    Condition = Table_EquipEnchant_t.Condition[1],
    Name = "##160583",
    Dsc = "##116921",
    ComBineAttr = "##1110020",
    AttrSectionDsc = "1.5%~6%",
    ItemCost = Table_EquipEnchant_t.ItemCost[1],
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[6],
    NoShowEquip = Table_EquipEnchant_t.NoShowEquip[3],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[5]
  },
  [18] = {
    id = 18,
    UniqID = 2006,
    EnchantType = 2,
    AttrType = "Agi",
    AttrType2 = Table_EquipEnchant_t.AttrType2[5],
    AddAttr = Table_EquipEnchant_t.AddAttr[5],
    Condition = Table_EquipEnchant_t.Condition[1],
    Name = "##1110021",
    Dsc = "##154581",
    ComBineAttr = "##1110022",
    AttrSectionDsc = "5%~20%",
    ItemCost = Table_EquipEnchant_t.ItemCost[1],
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[6],
    NoExchangeEnchant = Table_EquipEnchant_t.NoExchangeEnchant[1],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[1]
  },
  [19] = {
    id = 19,
    UniqID = 2007,
    EnchantType = 2,
    AttrType = "MaxHp",
    ItemCost = Table_EquipEnchant_t.ItemCost[1],
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[8],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[2]
  },
  [20] = {
    id = 20,
    UniqID = 2008,
    EnchantType = 2,
    AttrType = "MaxHpPer",
    ItemCost = Table_EquipEnchant_t.ItemCost[1],
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[9],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[6]
  },
  [21] = {
    id = 21,
    UniqID = 2009,
    EnchantType = 2,
    AttrType = "MaxSp",
    ItemCost = Table_EquipEnchant_t.ItemCost[1],
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[10],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[2]
  },
  [22] = {
    id = 22,
    UniqID = 2010,
    EnchantType = 2,
    AttrType = "MaxSpPer",
    AttrType2 = Table_EquipEnchant_t.AttrType2[6],
    AddAttr = Table_EquipEnchant_t.AddAttr[6],
    Condition = Table_EquipEnchant_t.Condition[1],
    Name = "##1110023",
    Dsc = "##149502",
    ComBineAttr = "##1110024",
    AttrSectionDsc = "2%~8%",
    ItemCost = Table_EquipEnchant_t.ItemCost[1],
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[9],
    NoShowEquip = Table_EquipEnchant_t.NoShowEquip[4],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[7]
  },
  [23] = {
    id = 23,
    UniqID = 2011,
    EnchantType = 2,
    AttrType = "Atk",
    AttrType2 = Table_EquipEnchant_t.AttrType2[7],
    AddAttr = Table_EquipEnchant_t.AddAttr[7],
    Condition = Table_EquipEnchant_t.Condition[1],
    Name = "##1110025",
    Dsc = "##116898",
    ComBineAttr = "##1110026",
    AttrSectionDsc = "5%~20%",
    ItemCost = Table_EquipEnchant_t.ItemCost[1],
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[11],
    NoShowEquip = Table_EquipEnchant_t.NoShowEquip[5],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[2]
  },
  [24] = {
    id = 24,
    UniqID = 2013,
    EnchantType = 2,
    AttrType2 = Table_EquipEnchant_t.AttrType2[4],
    AddAttr = Table_EquipEnchant_t.AddAttr[8],
    Condition = Table_EquipEnchant_t.Condition[1],
    Name = "##297335",
    Dsc = "##1110027",
    ComBineAttr = "##1110028",
    AttrSectionDsc = "2.5%~10%",
    ItemCost = Table_EquipEnchant_t.ItemCost[1],
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[11],
    NoShowEquip = Table_EquipEnchant_t.NoShowEquip[6],
    NoExchangeEnchant = Table_EquipEnchant_t.NoExchangeEnchant[2],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[2]
  },
  [25] = {
    id = 25,
    UniqID = 2015,
    EnchantType = 2,
    AttrType = "Def",
    ItemCost = Table_EquipEnchant_t.ItemCost[1],
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[7],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[2]
  },
  [26] = {
    id = 26,
    UniqID = 2017,
    EnchantType = 2,
    AttrType = "MDef",
    ItemCost = Table_EquipEnchant_t.ItemCost[1],
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[11],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[2]
  },
  [27] = {
    id = 27,
    UniqID = 2019,
    EnchantType = 2,
    AttrType = "Hit",
    AttrType2 = Table_EquipEnchant_t.AttrType2[2],
    AddAttr = Table_EquipEnchant_t.AddAttr[9],
    Condition = Table_EquipEnchant_t.Condition[1],
    Name = "##1110029",
    Dsc = "##1110030",
    ComBineAttr = "##1110031",
    AttrSectionDsc = "2.5%~10%",
    ItemCost = Table_EquipEnchant_t.ItemCost[1],
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[12],
    NoShowEquip = Table_EquipEnchant_t.NoShowEquip[6],
    NoExchangeEnchant = Table_EquipEnchant_t.NoExchangeEnchant[3],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[2]
  },
  [28] = {
    id = 28,
    UniqID = 2020,
    EnchantType = 2,
    AttrType = "Flee",
    ItemCost = Table_EquipEnchant_t.ItemCost[1],
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[12],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[2]
  },
  [29] = {
    id = 29,
    UniqID = 3001,
    AttrType = "Vit",
    AttrType2 = Table_EquipEnchant_t.AttrType2[1],
    AddAttr = Table_EquipEnchant_t.AddAttr[10],
    Condition = Table_EquipEnchant_t.Condition[1],
    Name = "##1110014",
    Dsc = "##1110015",
    ComBineAttr = "##1110016",
    AttrSectionDsc = "2.5%~10%",
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[13],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[3],
    Liftvalue = 1,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[1],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[1],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[1],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[1],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[1]
  },
  [30] = {
    id = 30,
    UniqID = 3002,
    AttrType = "Str",
    AttrType2 = Table_EquipEnchant_t.AttrType2[2],
    AddAttr = Table_EquipEnchant_t.AddAttr[11],
    Condition = Table_EquipEnchant_t.Condition[1],
    Name = "##159322",
    Dsc = "##116916",
    ComBineAttr = "##1110017",
    AttrSectionDsc = "1.5%~6%",
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[13],
    NoShowEquip = Table_EquipEnchant_t.NoShowEquip[1],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[4],
    Liftvalue = 1,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[1],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[1],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[1],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[1],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[1]
  },
  [31] = {
    id = 31,
    UniqID = 3003,
    AttrType = "Int",
    AttrType2 = Table_EquipEnchant_t.AttrType2[3],
    AddAttr = Table_EquipEnchant_t.AddAttr[12],
    Condition = Table_EquipEnchant_t.Condition[1],
    Name = "##1110018",
    Dsc = "##116920",
    ComBineAttr = "##1110019",
    AttrSectionDsc = "5%~20%",
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[13],
    NoShowEquip = Table_EquipEnchant_t.NoShowEquip[2],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[5],
    Liftvalue = 1,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[1],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[1],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[1],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[1],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[1]
  },
  [32] = {
    id = 32,
    UniqID = 3004,
    AttrType = "Luk",
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[14],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[2],
    Liftvalue = 1,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[1],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[1],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[1],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[1],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[1]
  },
  [33] = {
    id = 33,
    UniqID = 3005,
    AttrType = "Dex",
    AttrType2 = Table_EquipEnchant_t.AttrType2[4],
    AddAttr = Table_EquipEnchant_t.AddAttr[13],
    Condition = Table_EquipEnchant_t.Condition[1],
    Name = "##160583",
    Dsc = "##116921",
    ComBineAttr = "##1110020",
    AttrSectionDsc = "1.5%~6%",
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[13],
    NoShowEquip = Table_EquipEnchant_t.NoShowEquip[3],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[5],
    Liftvalue = 1,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[1],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[1],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[1],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[1],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[1]
  },
  [34] = {
    id = 34,
    UniqID = 3006,
    AttrType = "Agi",
    AttrType2 = Table_EquipEnchant_t.AttrType2[5],
    AddAttr = Table_EquipEnchant_t.AddAttr[14],
    Condition = Table_EquipEnchant_t.Condition[1],
    Name = "##1110021",
    Dsc = "##154581",
    ComBineAttr = "##1110022",
    AttrSectionDsc = "5%~20%",
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[13],
    NoExchangeEnchant = Table_EquipEnchant_t.NoExchangeEnchant[1],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[1],
    Liftvalue = 1,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[1],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[1],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[1],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[1],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[1]
  },
  [35] = {
    id = 35,
    UniqID = 3007,
    AttrType = "MaxHp",
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[15],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[2],
    Liftvalue = 10,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[2],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[2],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[2],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[2],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[2]
  },
  [36] = {
    id = 36,
    UniqID = 3008,
    AttrType = "MaxHpPer",
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[16],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[6],
    Liftvalue = 0.001,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[2],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[2],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[2],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[2],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[2]
  },
  [37] = {
    id = 37,
    UniqID = 3009,
    AttrType = "MaxSp",
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[17],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[2],
    Liftvalue = 2,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[2],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[2],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[2],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[2],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[2]
  },
  [38] = {
    id = 38,
    UniqID = 3010,
    AttrType = "MaxSpPer",
    AttrType2 = Table_EquipEnchant_t.AttrType2[6],
    AddAttr = Table_EquipEnchant_t.AddAttr[15],
    Condition = Table_EquipEnchant_t.Condition[1],
    Name = "##1110023",
    Dsc = "##149502",
    ComBineAttr = "##1110024",
    AttrSectionDsc = "2%~8%",
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[9],
    NoShowEquip = Table_EquipEnchant_t.NoShowEquip[4],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[7],
    Liftvalue = 0.002,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[2],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[2],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[2],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[2],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[2]
  },
  [39] = {
    id = 39,
    UniqID = 3011,
    AttrType = "Atk",
    AttrType2 = Table_EquipEnchant_t.AttrType2[7],
    AddAttr = Table_EquipEnchant_t.AddAttr[16],
    Condition = Table_EquipEnchant_t.Condition[1],
    Name = "##1110025",
    Dsc = "##116898",
    ComBineAttr = "##1110026",
    AttrSectionDsc = "5%~20%",
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[18],
    NoShowEquip = Table_EquipEnchant_t.NoShowEquip[5],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[2],
    Liftvalue = 1,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[2],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[2],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[2],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[2],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[2]
  },
  [40] = {
    id = 40,
    UniqID = 3013,
    AttrType2 = Table_EquipEnchant_t.AttrType2[4],
    AddAttr = Table_EquipEnchant_t.AddAttr[17],
    Condition = Table_EquipEnchant_t.Condition[1],
    Name = "##297335",
    Dsc = "##1110027",
    ComBineAttr = "##1110028",
    AttrSectionDsc = "2.5%~10%",
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[18],
    NoShowEquip = Table_EquipEnchant_t.NoShowEquip[6],
    NoExchangeEnchant = Table_EquipEnchant_t.NoExchangeEnchant[2],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[2],
    Liftvalue = 1,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[2],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[2],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[2],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[2],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[2]
  },
  [41] = {
    id = 41,
    UniqID = 3015,
    AttrType = "Def",
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[19],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[2],
    Liftvalue = 1,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[2],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[2],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[2],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[2],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[2]
  },
  [42] = {
    id = 42,
    UniqID = 3017,
    AttrType = "MDef",
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[20],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[2],
    Liftvalue = 1,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[2],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[2],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[2],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[2],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[2]
  },
  [43] = {
    id = 43,
    UniqID = 3019,
    AttrType = "Hit",
    AttrType2 = Table_EquipEnchant_t.AttrType2[2],
    AddAttr = Table_EquipEnchant_t.AddAttr[18],
    Condition = Table_EquipEnchant_t.Condition[1],
    Name = "##1110029",
    Dsc = "##1110030",
    ComBineAttr = "##1110031",
    AttrSectionDsc = "2.5%~10%",
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[21],
    NoShowEquip = Table_EquipEnchant_t.NoShowEquip[6],
    NoExchangeEnchant = Table_EquipEnchant_t.NoExchangeEnchant[3],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[2],
    Liftvalue = 1,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[2],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[2],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[2],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[2],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[2]
  },
  [44] = {
    id = 44,
    UniqID = 3020,
    AttrType = "Flee",
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[21],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[2],
    Liftvalue = 1,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[2],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[2],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[2],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[2],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[2]
  },
  [45] = {
    id = 45,
    UniqID = 3021,
    AttrType = "EquipASPD",
    AttrType2 = Table_EquipEnchant_t.AttrType2[8],
    AddAttr = Table_EquipEnchant_t.AddAttr[19],
    Condition = Table_EquipEnchant_t.Condition[1],
    Name = "##130849",
    Dsc = "##1110050",
    ComBineAttr = "##1110051",
    AttrSectionDsc = "2.5%~10%",
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[22],
    NoShowEquip = Table_EquipEnchant_t.NoShowEquip[7],
    NoExchangeEnchant = Table_EquipEnchant_t.NoExchangeEnchant[1],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[8],
    Liftvalue = 0.001,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[2],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[2],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[2],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[2],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[2]
  },
  [46] = {
    id = 46,
    UniqID = 3022,
    AttrType = "Cri",
    AttrType2 = Table_EquipEnchant_t.AttrType2[9],
    AddAttr = Table_EquipEnchant_t.AddAttr[20],
    Condition = Table_EquipEnchant_t.Condition[1],
    Name = "##144011",
    Dsc = "##1110052",
    ComBineAttr = "##1110053",
    AttrSectionDsc = "2.5%~10%",
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[23],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[9],
    Liftvalue = 1,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[1],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[1],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[1],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[1],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[1]
  },
  [47] = {
    id = 47,
    UniqID = 3023,
    AttrType = "CriRes",
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[23],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[2],
    Liftvalue = 1,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[1],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[1],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[1],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[1],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[1]
  },
  [48] = {
    id = 48,
    UniqID = 3024,
    AttrType = "CriDamPer",
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[24],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[2],
    Liftvalue = 0.002,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[2],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[2],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[2],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[2],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[2]
  },
  [49] = {
    id = 49,
    UniqID = 3025,
    AttrType = "CriDefPer",
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[24],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[2],
    Liftvalue = 0.002,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[2],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[2],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[2],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[2],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[2]
  },
  [50] = {
    id = 50,
    UniqID = 3026,
    AttrType = "HealEncPer",
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[9],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[10],
    Liftvalue = 0.001,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[2],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[2],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[2],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[2],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[2]
  },
  [51] = {
    id = 51,
    UniqID = 3027,
    AttrType = "BeHealEncPer",
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[9],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[6],
    Liftvalue = 0.001,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[2],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[2],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[2],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[2],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[2]
  },
  [52] = {
    id = 52,
    UniqID = 3028,
    AttrType = "DamIncrease",
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[22],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[2],
    Liftvalue = 0.001,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[2],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[2],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[2],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[2],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[2]
  },
  [53] = {
    id = 53,
    UniqID = 3029,
    AttrType = "DamReduc",
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[22],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[2],
    Liftvalue = 0.001,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[2],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[2],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[2],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[2],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[2]
  },
  [54] = {
    id = 54,
    UniqID = 3033,
    AttrType = "SilenceDef",
    AddAttr = Table_EquipEnchant_t.AddAttr[21],
    Condition = Table_EquipEnchant_t.Condition[1],
    Name = "##1110054",
    Dsc = "##149554",
    ComBineAttr = "##1110055",
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[25],
    NoShowEquip = Table_EquipEnchant_t.NoShowEquip[8],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[11],
    Liftvalue = 0.002,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[2],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[2],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[2],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[2],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[2]
  },
  [55] = {
    id = 55,
    UniqID = 3034,
    AttrType = "FreezeDef",
    AddAttr = Table_EquipEnchant_t.AddAttr[21],
    Condition = Table_EquipEnchant_t.Condition[1],
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[25],
    NoShowEquip = Table_EquipEnchant_t.NoShowEquip[8],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[11],
    Liftvalue = 0.002,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[2],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[2],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[2],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[2],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[2]
  },
  [56] = {
    id = 56,
    UniqID = 3035,
    AttrType = "StoneDef",
    AddAttr = Table_EquipEnchant_t.AddAttr[21],
    Condition = Table_EquipEnchant_t.Condition[1],
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[25],
    NoShowEquip = Table_EquipEnchant_t.NoShowEquip[8],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[11],
    Liftvalue = 0.002,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[2],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[2],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[2],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[2],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[2]
  },
  [57] = {
    id = 57,
    UniqID = 3036,
    AttrType = "StunDef",
    AddAttr = Table_EquipEnchant_t.AddAttr[21],
    Condition = Table_EquipEnchant_t.Condition[1],
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[25],
    NoShowEquip = Table_EquipEnchant_t.NoShowEquip[8],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[11],
    Liftvalue = 0.002,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[2],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[2],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[2],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[2],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[2]
  },
  [58] = {
    id = 58,
    UniqID = 3037,
    AttrType = "BlindDef",
    AddAttr = Table_EquipEnchant_t.AddAttr[21],
    Condition = Table_EquipEnchant_t.Condition[1],
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[25],
    NoShowEquip = Table_EquipEnchant_t.NoShowEquip[8],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[11],
    Liftvalue = 0.002,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[2],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[2],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[2],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[2],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[2]
  },
  [59] = {
    id = 59,
    UniqID = 3038,
    AttrType = "PoisonDef",
    AddAttr = Table_EquipEnchant_t.AddAttr[21],
    Condition = Table_EquipEnchant_t.Condition[1],
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[25],
    NoShowEquip = Table_EquipEnchant_t.NoShowEquip[8],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[11],
    Liftvalue = 0.002,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[2],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[2],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[2],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[2],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[2]
  },
  [60] = {
    id = 60,
    UniqID = 3039,
    AttrType = "SlowDef",
    AddAttr = Table_EquipEnchant_t.AddAttr[21],
    Condition = Table_EquipEnchant_t.Condition[1],
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[25],
    NoShowEquip = Table_EquipEnchant_t.NoShowEquip[8],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[11],
    Liftvalue = 0.002,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[2],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[2],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[2],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[2],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[2]
  },
  [61] = {
    id = 61,
    UniqID = 3040,
    AttrType = "ChaosDef",
    AddAttr = Table_EquipEnchant_t.AddAttr[21],
    Condition = Table_EquipEnchant_t.Condition[1],
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[25],
    NoShowEquip = Table_EquipEnchant_t.NoShowEquip[8],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[11],
    Liftvalue = 0.002,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[2],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[2],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[2],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[2],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[2]
  },
  [62] = {
    id = 62,
    UniqID = 3041,
    AttrType = "CurseDef",
    AddAttr = Table_EquipEnchant_t.AddAttr[21],
    Condition = Table_EquipEnchant_t.Condition[1],
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[25],
    NoShowEquip = Table_EquipEnchant_t.NoShowEquip[8],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[11],
    Liftvalue = 0.002,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[2],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[2],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[2],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[2],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[2]
  },
  [63] = {
    id = 63,
    UniqID = 4001,
    EnchantType = 1,
    MaxNum = 2,
    AttrType = "Vit",
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[1],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[12]
  },
  [64] = {
    id = 64,
    UniqID = 4002,
    EnchantType = 1,
    MaxNum = 2,
    AttrType = "Str",
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[1],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[13]
  },
  [65] = {
    id = 65,
    UniqID = 4003,
    EnchantType = 1,
    MaxNum = 2,
    AttrType = "Int",
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[1],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[14]
  },
  [66] = {
    id = 66,
    UniqID = 4004,
    EnchantType = 1,
    MaxNum = 2,
    AttrType = "Luk",
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[2],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[15]
  },
  [67] = {
    id = 67,
    UniqID = 4005,
    EnchantType = 1,
    MaxNum = 2,
    AttrType = "Dex",
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[1],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[16]
  },
  [68] = {
    id = 68,
    UniqID = 4006,
    EnchantType = 1,
    MaxNum = 2,
    AttrType = "Agi",
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[1],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[17]
  },
  [69] = {
    id = 69,
    UniqID = 4007,
    EnchantType = 1,
    MaxNum = 2,
    AttrType = "MaxHp",
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[26],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[15]
  },
  [70] = {
    id = 70,
    UniqID = 4008,
    EnchantType = 1,
    MaxNum = 2,
    AttrType = "MaxSp",
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[27],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[15]
  },
  [71] = {
    id = 71,
    UniqID = 4009,
    EnchantType = 1,
    MaxNum = 2,
    AttrType = "Atk",
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[28],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[15]
  },
  [72] = {
    id = 72,
    UniqID = 4010,
    EnchantType = 1,
    MaxNum = 2,
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[28],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[15]
  },
  [73] = {
    id = 73,
    UniqID = 4011,
    EnchantType = 1,
    MaxNum = 2,
    AttrType = "Def",
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[28],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[15]
  },
  [74] = {
    id = 74,
    UniqID = 4012,
    EnchantType = 1,
    MaxNum = 2,
    AttrType = "MDef",
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[28],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[15]
  },
  [75] = {
    id = 75,
    UniqID = 5001,
    EnchantType = 2,
    AttrType = "Vit",
    AttrType2 = Table_EquipEnchant_t.AttrType2[4],
    AddAttr = Table_EquipEnchant_t.AddAttr[22],
    Condition = Table_EquipEnchant_t.Condition[1],
    Name = "##169702",
    Dsc = "##149484",
    ComBineAttr = "##1110056",
    AttrSectionDsc = "2.5%~10%",
    ItemCost = Table_EquipEnchant_t.ItemCost[1],
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[6],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[12]
  },
  [76] = {
    id = 76,
    UniqID = 5002,
    EnchantType = 2,
    AttrType = "Str",
    AttrType2 = Table_EquipEnchant_t.AttrType2[10],
    AddAttr = Table_EquipEnchant_t.AddAttr[7],
    Condition = Table_EquipEnchant_t.Condition[1],
    Name = "##1110025",
    Dsc = "##116898",
    ComBineAttr = "##1110026",
    AttrSectionDsc = "5%~20%",
    ItemCost = Table_EquipEnchant_t.ItemCost[1],
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[6],
    NoShowEquip = Table_EquipEnchant_t.NoShowEquip[9],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[13]
  },
  [77] = {
    id = 77,
    UniqID = 5003,
    EnchantType = 2,
    AttrType = "Int",
    AttrType2 = Table_EquipEnchant_t.AttrType2[6],
    AddAttr = Table_EquipEnchant_t.AddAttr[8],
    Condition = Table_EquipEnchant_t.Condition[1],
    Name = "##297335",
    Dsc = "##1110027",
    ComBineAttr = "##1110028",
    AttrSectionDsc = "2.5%~10%",
    ItemCost = Table_EquipEnchant_t.ItemCost[1],
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[6],
    NoShowEquip = Table_EquipEnchant_t.NoShowEquip[10],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[14]
  },
  [78] = {
    id = 78,
    UniqID = 5004,
    EnchantType = 2,
    AttrType = "Luk",
    ItemCost = Table_EquipEnchant_t.ItemCost[1],
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[7],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[15]
  },
  [79] = {
    id = 79,
    UniqID = 5005,
    EnchantType = 2,
    AttrType = "Dex",
    AttrType2 = Table_EquipEnchant_t.AttrType2[11],
    AddAttr = Table_EquipEnchant_t.AddAttr[9],
    Condition = Table_EquipEnchant_t.Condition[1],
    Name = "##1110029",
    Dsc = "##1110030",
    ComBineAttr = "##1110031",
    AttrSectionDsc = "2.5%~10%",
    ItemCost = Table_EquipEnchant_t.ItemCost[1],
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[6],
    NoShowEquip = Table_EquipEnchant_t.NoShowEquip[11],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[16]
  },
  [80] = {
    id = 80,
    UniqID = 5006,
    EnchantType = 2,
    AttrType = "Agi",
    AttrType2 = Table_EquipEnchant_t.AttrType2[5],
    AddAttr = Table_EquipEnchant_t.AddAttr[5],
    Condition = Table_EquipEnchant_t.Condition[1],
    Name = "##1110021",
    Dsc = "##154581",
    ComBineAttr = "##1110022",
    AttrSectionDsc = "5%~20%",
    ItemCost = Table_EquipEnchant_t.ItemCost[1],
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[6],
    NoShowEquip = Table_EquipEnchant_t.NoShowEquip[12],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[17]
  },
  [81] = {
    id = 81,
    UniqID = 5007,
    EnchantType = 2,
    AttrType = "MaxHp",
    ItemCost = Table_EquipEnchant_t.ItemCost[1],
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[29],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[15]
  },
  [82] = {
    id = 82,
    UniqID = 5008,
    EnchantType = 2,
    AttrType = "MaxHpPer",
    ItemCost = Table_EquipEnchant_t.ItemCost[1],
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[9],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[18]
  },
  [83] = {
    id = 83,
    UniqID = 5009,
    EnchantType = 2,
    AttrType = "MaxSp",
    ItemCost = Table_EquipEnchant_t.ItemCost[1],
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[30],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[15]
  },
  [84] = {
    id = 84,
    UniqID = 5010,
    EnchantType = 2,
    AttrType = "MaxSpPer",
    AttrType2 = Table_EquipEnchant_t.AttrType2[4],
    AddAttr = Table_EquipEnchant_t.AddAttr[3],
    Condition = Table_EquipEnchant_t.Condition[1],
    Name = "##1110018",
    Dsc = "##116920",
    ComBineAttr = "##1110019",
    AttrSectionDsc = "5%~20%",
    ItemCost = Table_EquipEnchant_t.ItemCost[1],
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[9],
    NoShowEquip = Table_EquipEnchant_t.NoShowEquip[13],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[14]
  },
  [85] = {
    id = 85,
    UniqID = 5011,
    EnchantType = 2,
    AttrType = "Atk",
    ItemCost = Table_EquipEnchant_t.ItemCost[1],
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[31],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[15]
  },
  [86] = {
    id = 86,
    UniqID = 5013,
    EnchantType = 2,
    AttrType2 = Table_EquipEnchant_t.AttrType2[3],
    AddAttr = Table_EquipEnchant_t.AddAttr[6],
    Condition = Table_EquipEnchant_t.Condition[1],
    Name = "##1110023",
    Dsc = "##149502",
    ComBineAttr = "##1110024",
    AttrSectionDsc = "2%~8%",
    ItemCost = Table_EquipEnchant_t.ItemCost[1],
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[31],
    NoShowEquip = Table_EquipEnchant_t.NoShowEquip[14],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[15]
  },
  [87] = {
    id = 87,
    UniqID = 5015,
    EnchantType = 2,
    AttrType = "Def",
    ItemCost = Table_EquipEnchant_t.ItemCost[1],
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[31],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[15]
  },
  [88] = {
    id = 88,
    UniqID = 5017,
    EnchantType = 2,
    AttrType = "MDef",
    ItemCost = Table_EquipEnchant_t.ItemCost[1],
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[31],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[15]
  },
  [89] = {
    id = 89,
    UniqID = 5019,
    EnchantType = 2,
    AttrType = "Hit",
    ItemCost = Table_EquipEnchant_t.ItemCost[1],
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[6],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[15]
  },
  [90] = {
    id = 90,
    UniqID = 5020,
    EnchantType = 2,
    AttrType = "Flee",
    ItemCost = Table_EquipEnchant_t.ItemCost[1],
    ZenyCost = 5000,
    AttrBound = Table_EquipEnchant_t.AttrBound[6],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[15]
  },
  [91] = {
    id = 91,
    UniqID = 6001,
    AttrType = "Vit",
    AttrType2 = Table_EquipEnchant_t.AttrType2[4],
    AddAttr = Table_EquipEnchant_t.AddAttr[23],
    Condition = Table_EquipEnchant_t.Condition[1],
    Name = "##169702",
    Dsc = "##149484",
    ComBineAttr = "##1110056",
    AttrSectionDsc = "2.5%~10%",
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[13],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[12],
    Liftvalue = 1,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[1],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[1],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[1],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[1],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[1]
  },
  [92] = {
    id = 92,
    UniqID = 6002,
    AttrType = "Str",
    AttrType2 = Table_EquipEnchant_t.AttrType2[10],
    AddAttr = Table_EquipEnchant_t.AddAttr[16],
    Condition = Table_EquipEnchant_t.Condition[1],
    Name = "##1110025",
    Dsc = "##116898",
    ComBineAttr = "##1110026",
    AttrSectionDsc = "5%~20%",
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[13],
    NoShowEquip = Table_EquipEnchant_t.NoShowEquip[9],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[13],
    Liftvalue = 1,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[1],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[1],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[1],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[1],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[1]
  },
  [93] = {
    id = 93,
    UniqID = 6003,
    AttrType = "Int",
    AttrType2 = Table_EquipEnchant_t.AttrType2[6],
    AddAttr = Table_EquipEnchant_t.AddAttr[17],
    Condition = Table_EquipEnchant_t.Condition[1],
    Name = "##297335",
    Dsc = "##1110027",
    ComBineAttr = "##1110028",
    AttrSectionDsc = "2.5%~10%",
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[13],
    NoShowEquip = Table_EquipEnchant_t.NoShowEquip[10],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[14],
    Liftvalue = 1,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[1],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[1],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[1],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[1],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[1]
  },
  [94] = {
    id = 94,
    UniqID = 6004,
    AttrType = "Luk",
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[14],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[15],
    Liftvalue = 1,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[1],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[1],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[1],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[1],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[1]
  },
  [95] = {
    id = 95,
    UniqID = 6005,
    AttrType = "Dex",
    AttrType2 = Table_EquipEnchant_t.AttrType2[11],
    AddAttr = Table_EquipEnchant_t.AddAttr[18],
    Condition = Table_EquipEnchant_t.Condition[1],
    Name = "##1110029",
    Dsc = "##1110030",
    ComBineAttr = "##1110031",
    AttrSectionDsc = "2.5%~10%",
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[13],
    NoShowEquip = Table_EquipEnchant_t.NoShowEquip[11],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[16],
    Liftvalue = 1,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[1],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[1],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[1],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[1],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[1]
  },
  [96] = {
    id = 96,
    UniqID = 6006,
    AttrType = "Agi",
    AttrType2 = Table_EquipEnchant_t.AttrType2[5],
    AddAttr = Table_EquipEnchant_t.AddAttr[14],
    Condition = Table_EquipEnchant_t.Condition[1],
    Name = "##1110021",
    Dsc = "##154581",
    ComBineAttr = "##1110022",
    AttrSectionDsc = "5%~20%",
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[13],
    NoShowEquip = Table_EquipEnchant_t.NoShowEquip[12],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[17],
    Liftvalue = 1,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[1],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[1],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[1],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[1],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[1]
  },
  [97] = {
    id = 97,
    UniqID = 6007,
    AttrType = "MaxHp",
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[32],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[15],
    Liftvalue = 10,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[2],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[2],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[2],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[2],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[2]
  },
  [98] = {
    id = 98,
    UniqID = 6008,
    AttrType = "MaxHpPer",
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[16],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[18],
    Liftvalue = 0.001,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[2],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[2],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[2],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[2],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[2]
  },
  [99] = {
    id = 99,
    UniqID = 6009,
    AttrType = "MaxSp",
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[33],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[15],
    Liftvalue = 2,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[2],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[2],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[2],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[2],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[2]
  },
  [100] = {
    id = 100,
    UniqID = 6010,
    AttrType = "MaxSpPer",
    AttrType2 = Table_EquipEnchant_t.AttrType2[4],
    AddAttr = Table_EquipEnchant_t.AddAttr[12],
    Condition = Table_EquipEnchant_t.Condition[1],
    Name = "##1110018",
    Dsc = "##116920",
    ComBineAttr = "##1110019",
    AttrSectionDsc = "5%~20%",
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[9],
    NoShowEquip = Table_EquipEnchant_t.NoShowEquip[13],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[14],
    Liftvalue = 0.002,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[2],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[2],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[2],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[2],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[2]
  },
  [101] = {
    id = 101,
    UniqID = 6011,
    AttrType = "Atk",
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[34],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[15],
    Liftvalue = 1,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[2],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[2],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[2],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[2],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[2]
  },
  [102] = {
    id = 102,
    UniqID = 6013,
    AttrType2 = Table_EquipEnchant_t.AttrType2[3],
    AddAttr = Table_EquipEnchant_t.AddAttr[15],
    Condition = Table_EquipEnchant_t.Condition[1],
    Name = "##1110023",
    Dsc = "##149502",
    ComBineAttr = "##1110024",
    AttrSectionDsc = "2%~8%",
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[34],
    NoShowEquip = Table_EquipEnchant_t.NoShowEquip[14],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[15],
    Liftvalue = 1,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[2],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[2],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[2],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[2],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[2]
  },
  [103] = {
    id = 103,
    UniqID = 6015,
    AttrType = "Def",
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[35],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[15],
    Liftvalue = 1,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[2],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[2],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[2],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[2],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[2]
  },
  [104] = {
    id = 104,
    UniqID = 6017,
    AttrType = "MDef",
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[35],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[15],
    Liftvalue = 1,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[2],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[2],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[2],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[2],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[2]
  },
  [105] = {
    id = 105,
    UniqID = 6019,
    AttrType = "Hit",
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[36],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[15],
    Liftvalue = 1,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[2],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[2],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[2],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[2],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[2]
  },
  [106] = {
    id = 106,
    UniqID = 6020,
    AttrType = "Flee",
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[36],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[15],
    Liftvalue = 1,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[2],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[2],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[2],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[2],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[2]
  },
  [107] = {
    id = 107,
    UniqID = 6021,
    AttrType = "EquipASPD",
    AttrType2 = Table_EquipEnchant_t.AttrType2[12],
    AddAttr = Table_EquipEnchant_t.AddAttr[24],
    Condition = Table_EquipEnchant_t.Condition[1],
    Name = "##1110084",
    Dsc = "##158909",
    ComBineAttr = "##1110085",
    AttrSectionDsc = "2.5%~10%",
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[22],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[16],
    Liftvalue = 0.001,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[2],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[2],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[2],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[2],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[2]
  },
  [108] = {
    id = 108,
    UniqID = 6022,
    AttrType = "Cri",
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[23],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[19],
    Liftvalue = 1,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[1],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[1],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[1],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[1],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[1]
  },
  [109] = {
    id = 109,
    UniqID = 6023,
    AttrType = "CriRes",
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[23],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[15],
    Liftvalue = 1,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[1],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[1],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[1],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[1],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[1]
  },
  [110] = {
    id = 110,
    UniqID = 6024,
    AttrType = "CriDamPer",
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[24],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[20],
    Liftvalue = 0.002,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[2],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[2],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[2],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[2],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[2]
  },
  [111] = {
    id = 111,
    UniqID = 6025,
    AttrType = "CriDefPer",
    AttrType2 = Table_EquipEnchant_t.AttrType2[13],
    AddAttr = Table_EquipEnchant_t.AddAttr[25],
    Condition = Table_EquipEnchant_t.Condition[1],
    Name = "##1110086",
    Dsc = "##1110087",
    ComBineAttr = "##1110088",
    AttrSectionDsc = "5~20",
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[24],
    NoShowEquip = Table_EquipEnchant_t.NoShowEquip[15],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[15],
    Liftvalue = 0.002,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[2],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[2],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[2],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[2],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[2]
  },
  [112] = {
    id = 112,
    UniqID = 6026,
    AttrType = "HealEncPer",
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[9],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[15],
    Liftvalue = 0.001,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[2],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[2],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[2],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[2],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[2]
  },
  [113] = {
    id = 113,
    UniqID = 6027,
    AttrType = "BeHealEncPer",
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[9],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[15],
    Liftvalue = 0.001,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[2],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[2],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[2],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[2],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[2]
  },
  [114] = {
    id = 114,
    UniqID = 6028,
    AttrType = "DamIncrease",
    AttrType2 = Table_EquipEnchant_t.AttrType2[14],
    AddAttr = Table_EquipEnchant_t.AddAttr[19],
    Condition = Table_EquipEnchant_t.Condition[1],
    Name = "##130849",
    Dsc = "##1110050",
    ComBineAttr = "##1110051",
    AttrSectionDsc = "2.5%~10%",
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[22],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[21],
    Liftvalue = 0.001,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[2],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[2],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[2],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[2],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[2]
  },
  [115] = {
    id = 115,
    AttrType = "DamReduc",
    ItemCost = Table_EquipEnchant_t.ItemCost[2],
    AttrBound = Table_EquipEnchant_t.AttrBound[22],
    CantEnchant = Table_EquipEnchant_t.CantEnchant[22],
    Liftvalue = 0.001,
    Stageconsumption1 = Table_EquipEnchant_t.Stageconsumption1[2],
    Stageconsumption2 = Table_EquipEnchant_t.Stageconsumption2[2],
    Stageconsumption3 = Table_EquipEnchant_t.Stageconsumption3[2],
    Stageconsumption4 = Table_EquipEnchant_t.Stageconsumption4[2],
    Stageconsumption5 = Table_EquipEnchant_t.Stageconsumption5[2]
  }
}
local cell_mt = {
  __index = {
    AddAttr = _EmptyTable,
    AttrBound = _EmptyTable,
    AttrSectionDsc = "",
    AttrType = "MAtk",
    AttrType2 = _EmptyTable,
    CantEnchant = _EmptyTable,
    ComBineAttr = "",
    Condition = _EmptyTable,
    Dsc = "",
    EnchantType = 3,
    ExpressionOfMaxDown = 0.2,
    ExpressionOfMaxUp = 0.8,
    ItemCost = _EmptyTable,
    MaxNum = 3,
    Name = "",
    NoExchangeEnchant = _EmptyTable,
    NoShowEquip = _EmptyTable,
    Stageconsumption1 = _EmptyTable,
    Stageconsumption2 = _EmptyTable,
    Stageconsumption3 = _EmptyTable,
    Stageconsumption4 = _EmptyTable,
    Stageconsumption5 = _EmptyTable,
    UniqID = 6029,
    ZenyCost = 20000,
    id = 1
  }
}
for _, d in pairs(Table_EquipEnchant) do
  setmetatable(d, cell_mt)
end
